import { Word } from './types';

const words: Word[] = [
  { id: "1-401", korean: "뱀", english: "Snake", pronunciation: "baem", partOfSpeech: "noun", example: "뱀이 무서워요.", exampleTranslation: "I'm afraid of snakes.", category: "Animals" },
  { id: "1-402", korean: "호랑이", english: "Tiger", pronunciation: "horangi", partOfSpeech: "noun", example: "호랑이는 강해요.", exampleTranslation: "Tigers are strong.", category: "Animals" },
  { id: "1-403", korean: "코끼리", english: "Elephant", pronunciation: "kokkiri", partOfSpeech: "noun", example: "코끼리는 커요.", exampleTranslation: "Elephants are big.", category: "Animals" },
  { id: "1-404", korean: "원숭이", english: "Monkey", pronunciation: "wonsungi", partOfSpeech: "noun", example: "원숭이가 나무를 타요.", exampleTranslation: "The monkey climbs a tree.", category: "Animals" },
  { id: "1-405", korean: "곰", english: "Bear", pronunciation: "gom", partOfSpeech: "noun", example: "곰이 물고기를 잡아요.", exampleTranslation: "The bear catches fish.", category: "Animals" },
  { id: "1-406", korean: "사자", english: "Lion", pronunciation: "saja", partOfSpeech: "noun", example: "사자는 동물의 왕이에요.", exampleTranslation: "The lion is the king of animals.", category: "Animals" },
  { id: "1-407", korean: "기린", english: "Giraffe", pronunciation: "girin", partOfSpeech: "noun", example: "기린은 목이 길어요.", exampleTranslation: "Giraffes have long necks.", category: "Animals" },
  { id: "1-408", korean: "양", english: "Sheep", pronunciation: "yang", partOfSpeech: "noun", example: "양이 풀을 먹어요.", exampleTranslation: "The sheep eats grass.", category: "Animals" },
  { id: "1-409", korean: "염소", english: "Goat", pronunciation: "yeomso", partOfSpeech: "noun", example: "염소가 산에 있어요.", exampleTranslation: "The goat is on the mountain.", category: "Animals" },
  { id: "1-410", korean: "오리", english: "Duck", pronunciation: "ori", partOfSpeech: "noun", example: "오리가 연못에서 헤엄쳐요.", exampleTranslation: "The duck swims in the pond.", category: "Animals" },
  { id: "1-411", korean: "거북이", english: "Turtle", pronunciation: "geobuki", partOfSpeech: "noun", example: "거북이는 느려요.", exampleTranslation: "The turtle is slow.", category: "Animals" },
  { id: "1-412", korean: "개구리", english: "Frog", pronunciation: "gaeguri", partOfSpeech: "noun", example: "개구리가 뛰어요.", exampleTranslation: "The frog is jumping.", category: "Animals" },
  { id: "1-413", korean: "나비", english: "Butterfly", pronunciation: "nabi", partOfSpeech: "noun", example: "나비가 꽃에 앉았어요.", exampleTranslation: "The butterfly sat on a flower.", category: "Animals" },
  { id: "1-414", korean: "벌", english: "Bee", pronunciation: "beol", partOfSpeech: "noun", example: "벌이 꿀을 만들어요.", exampleTranslation: "Bees make honey.", category: "Animals" },
  { id: "1-415", korean: "개미", english: "Ant", pronunciation: "gaemi", partOfSpeech: "noun", example: "개미가 열심히 일해요.", exampleTranslation: "Ants work hard.", category: "Animals" },
  { id: "1-416", korean: "거미", english: "Spider", pronunciation: "geomi", partOfSpeech: "noun", example: "거미가 거미줄을 쳐요.", exampleTranslation: "The spider spins a web.", category: "Animals" },
  { id: "1-417", korean: "파리", english: "Fly (insect)", pronunciation: "pari", partOfSpeech: "noun", example: "파리가 날아다녀요.", exampleTranslation: "The fly is flying around.", category: "Animals" },
  { id: "1-418", korean: "모기", english: "Mosquito", pronunciation: "mogi", partOfSpeech: "noun", example: "모기에 물렸어요.", exampleTranslation: "I got bitten by a mosquito.", category: "Animals" },
  { id: "1-419", korean: "다람쥐", english: "Squirrel", pronunciation: "daramjwi", partOfSpeech: "noun", example: "다람쥐가 도토리를 먹어요.", exampleTranslation: "The squirrel eats acorns.", category: "Animals" },
  { id: "1-420", korean: "독수리", english: "Eagle", pronunciation: "doksuri", partOfSpeech: "noun", example: "독수리가 하늘을 날아요.", exampleTranslation: "The eagle flies in the sky.", category: "Animals" },
  { id: "1-421", korean: "비둘기", english: "Pigeon / Dove", pronunciation: "bidulgi", partOfSpeech: "noun", example: "비둘기가 공원에 있어요.", exampleTranslation: "Pigeons are in the park.", category: "Animals" },
  { id: "1-422", korean: "참새", english: "Sparrow", pronunciation: "chamsae", partOfSpeech: "noun", example: "참새가 지붕에 앉았어요.", exampleTranslation: "A sparrow sat on the roof.", category: "Animals" },
  { id: "1-423", korean: "까치", english: "Magpie", pronunciation: "kkachi", partOfSpeech: "noun", example: "까치가 울어요.", exampleTranslation: "The magpie is calling.", category: "Animals" },
  { id: "1-424", korean: "하마", english: "Hippopotamus", pronunciation: "hama", partOfSpeech: "noun", example: "하마는 물에서 살아요.", exampleTranslation: "Hippos live in water.", category: "Animals" },
  { id: "1-425", korean: "늑대", english: "Wolf", pronunciation: "neukdae", partOfSpeech: "noun", example: "늑대가 울부짖어요.", exampleTranslation: "The wolf howls.", category: "Animals" },
  { id: "1-426", korean: "여우", english: "Fox", pronunciation: "yeou", partOfSpeech: "noun", example: "여우가 영리해요.", exampleTranslation: "The fox is clever.", category: "Animals" },
  { id: "1-427", korean: "펭귄", english: "Penguin", pronunciation: "penggwin", partOfSpeech: "noun", example: "펭귄은 남극에 살아요.", exampleTranslation: "Penguins live in Antarctica.", category: "Animals" },
  { id: "1-428", korean: "돌고래", english: "Dolphin", pronunciation: "dolgorae", partOfSpeech: "noun", example: "돌고래가 물 위로 뛰어요.", exampleTranslation: "The dolphin jumps above the water.", category: "Animals" },
  { id: "1-429", korean: "고래", english: "Whale", pronunciation: "gorae", partOfSpeech: "noun", example: "고래는 바다에서 살아요.", exampleTranslation: "Whales live in the ocean.", category: "Animals" },
  { id: "1-430", korean: "악어", english: "Crocodile / Alligator", pronunciation: "ageo", partOfSpeech: "noun", example: "악어가 무서워요.", exampleTranslation: "Crocodiles are scary.", category: "Animals" },
  { id: "1-431", korean: "빨간색", english: "Red", pronunciation: "ppalgansaek", partOfSpeech: "noun", example: "빨간색 장미가 예뻐요.", exampleTranslation: "Red roses are pretty.", category: "Colors" },
  { id: "1-432", korean: "파란색", english: "Blue", pronunciation: "paransaek", partOfSpeech: "noun", example: "하늘이 파란색이에요.", exampleTranslation: "The sky is blue.", category: "Colors" },
  { id: "1-433", korean: "노란색", english: "Yellow", pronunciation: "noransaek", partOfSpeech: "noun", example: "노란색 꽃이 피었어요.", exampleTranslation: "Yellow flowers bloomed.", category: "Colors" },
  { id: "1-434", korean: "초록색", english: "Green", pronunciation: "choroksaek", partOfSpeech: "noun", example: "초록색 나무가 많아요.", exampleTranslation: "There are many green trees.", category: "Colors" },
  { id: "1-435", korean: "하얀색", english: "White", pronunciation: "hayansaek", partOfSpeech: "noun", example: "하얀색 눈이 내려요.", exampleTranslation: "White snow is falling.", category: "Colors" },
  { id: "1-436", korean: "검은색", english: "Black", pronunciation: "geomeunsaek", partOfSpeech: "noun", example: "검은색 고양이가 있어요.", exampleTranslation: "There is a black cat.", category: "Colors" },
  { id: "1-437", korean: "주황색", english: "Orange (color)", pronunciation: "juhwangsaek", partOfSpeech: "noun", example: "주황색 감이 맛있어요.", exampleTranslation: "The orange persimmon is delicious.", category: "Colors" },
  { id: "1-438", korean: "보라색", english: "Purple", pronunciation: "borasaek", partOfSpeech: "noun", example: "보라색 꽃이 예뻐요.", exampleTranslation: "Purple flowers are pretty.", category: "Colors" },
  { id: "1-439", korean: "분홍색", english: "Pink", pronunciation: "bunhongsaek", partOfSpeech: "noun", example: "분홍색 원피스를 샀어요.", exampleTranslation: "I bought a pink dress.", category: "Colors" },
  { id: "1-440", korean: "갈색", english: "Brown", pronunciation: "galsaek", partOfSpeech: "noun", example: "갈색 가방이에요.", exampleTranslation: "It's a brown bag.", category: "Colors" },
  { id: "1-441", korean: "회색", english: "Gray", pronunciation: "hoesaek", partOfSpeech: "noun", example: "오늘 하늘이 회색이에요.", exampleTranslation: "The sky is gray today.", category: "Colors" },
  { id: "1-442", korean: "금색", english: "Gold (color)", pronunciation: "geumsaek", partOfSpeech: "noun", example: "금색 반지가 빛나요.", exampleTranslation: "The gold ring shines.", category: "Colors" },
  { id: "1-443", korean: "은색", english: "Silver (color)", pronunciation: "eunsaek", partOfSpeech: "noun", example: "은색 차가 멋있어요.", exampleTranslation: "The silver car looks cool.", category: "Colors" },
  { id: "1-444", korean: "하늘색", english: "Sky blue / Light blue", pronunciation: "haneulsaek", partOfSpeech: "noun", example: "하늘색 셔츠가 어울려요.", exampleTranslation: "The sky blue shirt looks good on you.", category: "Colors" },
  { id: "1-445", korean: "연두색", english: "Yellow-green / Light green", pronunciation: "yeondusaek", partOfSpeech: "noun", example: "연두색 잎이 나왔어요.", exampleTranslation: "Light green leaves have come out.", category: "Colors" },
  { id: "1-446", korean: "남색", english: "Navy / Indigo", pronunciation: "namsaek", partOfSpeech: "noun", example: "남색 양복을 입었어요.", exampleTranslation: "I wore a navy suit.", category: "Colors" },
  { id: "1-447", korean: "빨갛다", english: "To be red", pronunciation: "ppalgata", partOfSpeech: "adjective", example: "얼굴이 빨갛게 됐어요.", exampleTranslation: "My face turned red.", category: "Colors" },
  { id: "1-448", korean: "파랗다", english: "To be blue", pronunciation: "parata", partOfSpeech: "adjective", example: "바다가 파래요.", exampleTranslation: "The sea is blue.", category: "Colors" },
  { id: "1-449", korean: "노랗다", english: "To be yellow", pronunciation: "norata", partOfSpeech: "adjective", example: "은행잎이 노래요.", exampleTranslation: "The ginkgo leaves are yellow.", category: "Colors" },
  { id: "1-450", korean: "까맣다", english: "To be black", pronunciation: "kkamata", partOfSpeech: "adjective", example: "머리카락이 까매요.", exampleTranslation: "The hair is black.", category: "Colors" },
  { id: "1-451", korean: "날씨", english: "Weather", pronunciation: "nalssi", partOfSpeech: "noun", example: "오늘 날씨가 좋아요.", exampleTranslation: "The weather is nice today.", category: "Weather & Nature" },
  { id: "1-452", korean: "비", english: "Rain", pronunciation: "bi", partOfSpeech: "noun", example: "비가 와요.", exampleTranslation: "It's raining.", category: "Weather & Nature" },
  { id: "1-453", korean: "눈", english: "Snow", pronunciation: "nun", partOfSpeech: "noun", example: "눈이 내려요.", exampleTranslation: "It's snowing.", category: "Weather & Nature" },
  { id: "1-454", korean: "바람", english: "Wind", pronunciation: "baram", partOfSpeech: "noun", example: "바람이 세게 불어요.", exampleTranslation: "The wind is blowing hard.", category: "Weather & Nature" },
  { id: "1-455", korean: "구름", english: "Cloud", pronunciation: "gureum", partOfSpeech: "noun", example: "구름이 많아요.", exampleTranslation: "There are many clouds.", category: "Weather & Nature" },
  { id: "1-456", korean: "해", english: "Sun", pronunciation: "hae", partOfSpeech: "noun", example: "해가 떴어요.", exampleTranslation: "The sun has risen.", category: "Weather & Nature" },
  { id: "1-457", korean: "달", english: "Moon", pronunciation: "dal", partOfSpeech: "noun", example: "달이 밝아요.", exampleTranslation: "The moon is bright.", category: "Weather & Nature" },
  { id: "1-458", korean: "별", english: "Star", pronunciation: "byeol", partOfSpeech: "noun", example: "별이 반짝여요.", exampleTranslation: "The stars are twinkling.", category: "Weather & Nature" },
  { id: "1-459", korean: "하늘", english: "Sky", pronunciation: "haneul", partOfSpeech: "noun", example: "하늘이 맑아요.", exampleTranslation: "The sky is clear.", category: "Weather & Nature" },
  { id: "1-460", korean: "산", english: "Mountain", pronunciation: "san", partOfSpeech: "noun", example: "산에 올라갔어요.", exampleTranslation: "I climbed the mountain.", category: "Weather & Nature" },
  { id: "1-461", korean: "바다", english: "Sea / Ocean", pronunciation: "bada", partOfSpeech: "noun", example: "바다가 아름다워요.", exampleTranslation: "The sea is beautiful.", category: "Weather & Nature" },
  { id: "1-462", korean: "강", english: "River", pronunciation: "gang", partOfSpeech: "noun", example: "강에서 수영했어요.", exampleTranslation: "I swam in the river.", category: "Weather & Nature" },
  { id: "1-463", korean: "꽃", english: "Flower", pronunciation: "kkot", partOfSpeech: "noun", example: "꽃이 예쁘게 피었어요.", exampleTranslation: "The flowers bloomed beautifully.", category: "Weather & Nature" },
  { id: "1-464", korean: "나무", english: "Tree", pronunciation: "namu", partOfSpeech: "noun", example: "나무가 크게 자랐어요.", exampleTranslation: "The tree grew tall.", category: "Weather & Nature" },
  { id: "1-465", korean: "풀", english: "Grass", pronunciation: "pul", partOfSpeech: "noun", example: "풀이 초록색이에요.", exampleTranslation: "The grass is green.", category: "Weather & Nature" },
  { id: "1-466", korean: "호수", english: "Lake", pronunciation: "hosu", partOfSpeech: "noun", example: "호수가 잔잔해요.", exampleTranslation: "The lake is calm.", category: "Weather & Nature" },
  { id: "1-467", korean: "섬", english: "Island", pronunciation: "seom", partOfSpeech: "noun", example: "제주도는 아름다운 섬이에요.", exampleTranslation: "Jeju is a beautiful island.", category: "Weather & Nature" },
  { id: "1-468", korean: "숲", english: "Forest", pronunciation: "sup", partOfSpeech: "noun", example: "숲에서 산책했어요.", exampleTranslation: "I took a walk in the forest.", category: "Weather & Nature" },
  { id: "1-469", korean: "돌", english: "Stone / Rock", pronunciation: "dol", partOfSpeech: "noun", example: "돌이 많아요.", exampleTranslation: "There are many rocks.", category: "Weather & Nature" },
  { id: "1-470", korean: "모래", english: "Sand", pronunciation: "morae", partOfSpeech: "noun", example: "해변에 모래가 있어요.", exampleTranslation: "There is sand on the beach.", category: "Weather & Nature" },
  { id: "1-471", korean: "봄", english: "Spring (season)", pronunciation: "bom", partOfSpeech: "noun", example: "봄에 꽃이 펴요.", exampleTranslation: "Flowers bloom in spring.", category: "Weather & Nature" },
  { id: "1-472", korean: "여름", english: "Summer", pronunciation: "yeoreum", partOfSpeech: "noun", example: "여름에 바다에 가요.", exampleTranslation: "I go to the sea in summer.", category: "Weather & Nature" },
  { id: "1-473", korean: "가을", english: "Autumn / Fall", pronunciation: "gaeul", partOfSpeech: "noun", example: "가을에 단풍이 예뻐요.", exampleTranslation: "Autumn leaves are pretty in fall.", category: "Weather & Nature" },
  { id: "1-474", korean: "겨울", english: "Winter", pronunciation: "gyeoul", partOfSpeech: "noun", example: "겨울에 눈이 와요.", exampleTranslation: "It snows in winter.", category: "Weather & Nature" },
  { id: "1-475", korean: "우산", english: "Umbrella", pronunciation: "usan", partOfSpeech: "noun", example: "우산을 가져가세요.", exampleTranslation: "Take an umbrella.", category: "Weather & Nature" },
  { id: "1-476", korean: "천둥", english: "Thunder", pronunciation: "cheondung", partOfSpeech: "noun", example: "천둥 소리가 나요.", exampleTranslation: "I hear thunder.", category: "Weather & Nature" },
  { id: "1-477", korean: "번개", english: "Lightning", pronunciation: "beongae", partOfSpeech: "noun", example: "번개가 쳤어요.", exampleTranslation: "Lightning struck.", category: "Weather & Nature" },
  { id: "1-478", korean: "안개", english: "Fog", pronunciation: "angae", partOfSpeech: "noun", example: "안개가 꼈어요.", exampleTranslation: "It's foggy.", category: "Weather & Nature" },
  { id: "1-479", korean: "무지개", english: "Rainbow", pronunciation: "mujigae", partOfSpeech: "noun", example: "비 온 후에 무지개가 떴어요.", exampleTranslation: "A rainbow appeared after the rain.", category: "Weather & Nature" },
  { id: "1-480", korean: "태풍", english: "Typhoon", pronunciation: "taepung", partOfSpeech: "noun", example: "태풍이 올 거예요.", exampleTranslation: "A typhoon is coming.", category: "Weather & Nature" },
  { id: "1-481", korean: "폭포", english: "Waterfall", pronunciation: "pokpo", partOfSpeech: "noun", example: "폭포가 멋있어요.", exampleTranslation: "The waterfall is magnificent.", category: "Weather & Nature" },
  { id: "1-482", korean: "잔디", english: "Lawn / Grass (trimmed)", pronunciation: "jandi", partOfSpeech: "noun", example: "잔디에 앉았어요.", exampleTranslation: "I sat on the grass.", category: "Weather & Nature" },
  { id: "1-483", korean: "온도", english: "Temperature", pronunciation: "ondo", partOfSpeech: "noun", example: "오늘 온도가 높아요.", exampleTranslation: "The temperature is high today.", category: "Weather & Nature" },
  { id: "1-484", korean: "습도", english: "Humidity", pronunciation: "seupdo", partOfSpeech: "noun", example: "습도가 높아서 더워요.", exampleTranslation: "It's hot because the humidity is high.", category: "Weather & Nature" },
  { id: "1-485", korean: "계절", english: "Season", pronunciation: "gyejeol", partOfSpeech: "noun", example: "어떤 계절을 좋아해요?", exampleTranslation: "Which season do you like?", category: "Weather & Nature" },
  { id: "1-486", korean: "해변", english: "Beach", pronunciation: "haebyeon", partOfSpeech: "noun", example: "해변에서 놀았어요.", exampleTranslation: "I played at the beach.", category: "Weather & Nature" },
  { id: "1-487", korean: "파도", english: "Wave (ocean)", pronunciation: "pado", partOfSpeech: "noun", example: "파도가 높아요.", exampleTranslation: "The waves are high.", category: "Weather & Nature" },
  { id: "1-488", korean: "이슬", english: "Dew", pronunciation: "iseul", partOfSpeech: "noun", example: "아침에 이슬이 내려요.", exampleTranslation: "Dew forms in the morning.", category: "Weather & Nature" },
  { id: "1-489", korean: "서리", english: "Frost", pronunciation: "seori", partOfSpeech: "noun", example: "서리가 내렸어요.", exampleTranslation: "Frost has formed.", category: "Weather & Nature" },
  { id: "1-490", korean: "얼음", english: "Ice", pronunciation: "eoreum", partOfSpeech: "noun", example: "얼음이 녹았어요.", exampleTranslation: "The ice melted.", category: "Weather & Nature" },
  { id: "1-491", korean: "집", english: "House / Home", pronunciation: "jip", partOfSpeech: "noun", example: "집에 가고 싶어요.", exampleTranslation: "I want to go home.", category: "Places" },
  { id: "1-492", korean: "학교", english: "School", pronunciation: "hakgyo", partOfSpeech: "noun", example: "학교에서 공부해요.", exampleTranslation: "I study at school.", category: "Places" },
  { id: "1-493", korean: "회사", english: "Company / Office", pronunciation: "hoesa", partOfSpeech: "noun", example: "회사에 다녀요.", exampleTranslation: "I work at a company.", category: "Places" },
  { id: "1-494", korean: "병원", english: "Hospital", pronunciation: "byeongwon", partOfSpeech: "noun", example: "병원에 가야 해요.", exampleTranslation: "I need to go to the hospital.", category: "Places" },
  { id: "1-495", korean: "은행", english: "Bank", pronunciation: "eunhaeng", partOfSpeech: "noun", example: "은행에서 돈을 찾았어요.", exampleTranslation: "I withdrew money from the bank.", category: "Places" },
  { id: "1-496", korean: "마트", english: "Supermarket / Mart", pronunciation: "mateu", partOfSpeech: "noun", example: "마트에서 장을 봐요.", exampleTranslation: "I go grocery shopping at the mart.", category: "Places" },
  { id: "1-497", korean: "공원", english: "Park", pronunciation: "gongwon", partOfSpeech: "noun", example: "공원에서 산책해요.", exampleTranslation: "I take a walk in the park.", category: "Places" },
  { id: "1-498", korean: "도서관", english: "Library", pronunciation: "doseogwan", partOfSpeech: "noun", example: "도서관에서 책을 빌렸어요.", exampleTranslation: "I borrowed a book from the library.", category: "Places" },
  { id: "1-499", korean: "식당", english: "Restaurant", pronunciation: "sikdang", partOfSpeech: "noun", example: "식당에서 밥을 먹어요.", exampleTranslation: "I eat at a restaurant.", category: "Places" },
  { id: "1-500", korean: "카페", english: "Cafe", pronunciation: "kape", partOfSpeech: "noun", example: "카페에서 커피를 마셔요.", exampleTranslation: "I drink coffee at a cafe.", category: "Places" },
  { id: "1-501", korean: "약국", english: "Pharmacy", pronunciation: "yakguk", partOfSpeech: "noun", example: "약국에서 약을 샀어요.", exampleTranslation: "I bought medicine at the pharmacy.", category: "Places" },
  { id: "1-502", korean: "우체국", english: "Post office", pronunciation: "ucheguk", partOfSpeech: "noun", example: "우체국에서 편지를 보냈어요.", exampleTranslation: "I sent a letter at the post office.", category: "Places" },
  { id: "1-503", korean: "경찰서", english: "Police station", pronunciation: "gyeongchalseo", partOfSpeech: "noun", example: "경찰서에 신고했어요.", exampleTranslation: "I reported it at the police station.", category: "Places" },
  { id: "1-504", korean: "소방서", english: "Fire station", pronunciation: "sobangseo", partOfSpeech: "noun", example: "소방서에 전화했어요.", exampleTranslation: "I called the fire station.", category: "Places" },
  { id: "1-505", korean: "교회", english: "Church", pronunciation: "gyohoe", partOfSpeech: "noun", example: "일요일에 교회에 가요.", exampleTranslation: "I go to church on Sunday.", category: "Places" },
  { id: "1-506", korean: "절", english: "Buddhist temple", pronunciation: "jeol", partOfSpeech: "noun", example: "절에 갔어요.", exampleTranslation: "I went to the temple.", category: "Places" },
  { id: "1-507", korean: "극장", english: "Theater / Cinema", pronunciation: "geukjang", partOfSpeech: "noun", example: "극장에서 영화를 봤어요.", exampleTranslation: "I watched a movie at the theater.", category: "Places" },
  { id: "1-508", korean: "박물관", english: "Museum", pronunciation: "bangmulgwan", partOfSpeech: "noun", example: "박물관에서 역사를 배웠어요.", exampleTranslation: "I learned history at the museum.", category: "Places" },
  { id: "1-509", korean: "백화점", english: "Department store", pronunciation: "baekhwajeom", partOfSpeech: "noun", example: "백화점에서 쇼핑했어요.", exampleTranslation: "I went shopping at the department store.", category: "Places" },
  { id: "1-510", korean: "시장", english: "Market", pronunciation: "sijang", partOfSpeech: "noun", example: "시장에서 과일을 샀어요.", exampleTranslation: "I bought fruit at the market.", category: "Places" },
  { id: "1-511", korean: "공항", english: "Airport", pronunciation: "gonghang", partOfSpeech: "noun", example: "공항에서 비행기를 탔어요.", exampleTranslation: "I took a plane at the airport.", category: "Places" },
  { id: "1-512", korean: "역", english: "Station (train/subway)", pronunciation: "yeok", partOfSpeech: "noun", example: "역에서 기다려요.", exampleTranslation: "I wait at the station.", category: "Places" },
  { id: "1-513", korean: "호텔", english: "Hotel", pronunciation: "hotel", partOfSpeech: "noun", example: "호텔에서 잤어요.", exampleTranslation: "I slept at a hotel.", category: "Places" },
  { id: "1-514", korean: "편의점", english: "Convenience store", pronunciation: "pyeonuijeom", partOfSpeech: "noun", example: "편의점에서 물을 샀어요.", exampleTranslation: "I bought water at the convenience store.", category: "Places" },
  { id: "1-515", korean: "대학교", english: "University", pronunciation: "daehakgyo", partOfSpeech: "noun", example: "대학교에 다녀요.", exampleTranslation: "I attend university.", category: "Places" },
  { id: "1-516", korean: "놀이터", english: "Playground", pronunciation: "noriteo", partOfSpeech: "noun", example: "아이들이 놀이터에서 놀아요.", exampleTranslation: "Children play at the playground.", category: "Places" },
  { id: "1-517", korean: "수영장", english: "Swimming pool", pronunciation: "suyeongjang", partOfSpeech: "noun", example: "수영장에서 수영해요.", exampleTranslation: "I swim at the swimming pool.", category: "Places" },
  { id: "1-518", korean: "체육관", english: "Gym", pronunciation: "cheyukgwan", partOfSpeech: "noun", example: "체육관에서 운동해요.", exampleTranslation: "I exercise at the gym.", category: "Places" },
  { id: "1-519", korean: "미용실", english: "Hair salon / Beauty salon", pronunciation: "miyongsil", partOfSpeech: "noun", example: "미용실에서 머리를 잘랐어요.", exampleTranslation: "I got a haircut at the salon.", category: "Places" },
  { id: "1-520", korean: "세탁소", english: "Laundromat / Dry cleaner", pronunciation: "setakso", partOfSpeech: "noun", example: "세탁소에 옷을 맡겼어요.", exampleTranslation: "I left clothes at the dry cleaner.", category: "Places" },
  { id: "1-521", korean: "주차장", english: "Parking lot", pronunciation: "juchajang", partOfSpeech: "noun", example: "주차장에 차를 세웠어요.", exampleTranslation: "I parked the car in the parking lot.", category: "Places" },
  { id: "1-522", korean: "교실", english: "Classroom", pronunciation: "gyosil", partOfSpeech: "noun", example: "교실에 학생이 많아요.", exampleTranslation: "There are many students in the classroom.", category: "Places" },
  { id: "1-523", korean: "화장실", english: "Restroom / Bathroom", pronunciation: "hwajangsil", partOfSpeech: "noun", example: "화장실이 어디예요?", exampleTranslation: "Where is the restroom?", category: "Places" },
  { id: "1-524", korean: "부엌", english: "Kitchen", pronunciation: "bueok", partOfSpeech: "noun", example: "부엌에서 요리해요.", exampleTranslation: "I cook in the kitchen.", category: "Places" },
  { id: "1-525", korean: "거실", english: "Living room", pronunciation: "geosil", partOfSpeech: "noun", example: "거실에서 텔레비전을 봐요.", exampleTranslation: "I watch TV in the living room.", category: "Places" },
  { id: "1-526", korean: "침실", english: "Bedroom", pronunciation: "chimsil", partOfSpeech: "noun", example: "침실에서 자요.", exampleTranslation: "I sleep in the bedroom.", category: "Places" },
  { id: "1-527", korean: "방", english: "Room", pronunciation: "bang", partOfSpeech: "noun", example: "방이 넓어요.", exampleTranslation: "The room is spacious.", category: "Places" },
  { id: "1-528", korean: "서점", english: "Bookstore", pronunciation: "seojeom", partOfSpeech: "noun", example: "서점에서 책을 샀어요.", exampleTranslation: "I bought a book at the bookstore.", category: "Places" },
  { id: "1-529", korean: "동물원", english: "Zoo", pronunciation: "dongmulwon", partOfSpeech: "noun", example: "동물원에서 동물을 봤어요.", exampleTranslation: "I saw animals at the zoo.", category: "Places" },
  { id: "1-530", korean: "놀이공원", english: "Amusement park", pronunciation: "norigongwon", partOfSpeech: "noun", example: "놀이공원에서 놀았어요.", exampleTranslation: "I played at the amusement park.", category: "Places" },
  { id: "1-531", korean: "정류장", english: "Bus stop", pronunciation: "jeongnyujang", partOfSpeech: "noun", example: "정류장에서 버스를 기다려요.", exampleTranslation: "I wait for the bus at the bus stop.", category: "Places" },
  { id: "1-532", korean: "광장", english: "Plaza / Square", pronunciation: "gwangjang", partOfSpeech: "noun", example: "광장에 사람이 많아요.", exampleTranslation: "There are many people in the plaza.", category: "Places" },
  { id: "1-533", korean: "거리", english: "Street", pronunciation: "geori", partOfSpeech: "noun", example: "거리에 사람이 많아요.", exampleTranslation: "There are many people on the street.", category: "Places" },
  { id: "1-534", korean: "다리", english: "Bridge", pronunciation: "dari", partOfSpeech: "noun", example: "다리를 건너요.", exampleTranslation: "I cross the bridge.", category: "Places" },
  { id: "1-535", korean: "길", english: "Road / Way", pronunciation: "gil", partOfSpeech: "noun", example: "이 길로 가세요.", exampleTranslation: "Go this way.", category: "Places" },
  { id: "1-536", korean: "나라", english: "Country", pronunciation: "nara", partOfSpeech: "noun", example: "어느 나라에서 왔어요?", exampleTranslation: "Which country are you from?", category: "Places" },
  { id: "1-537", korean: "도시", english: "City", pronunciation: "dosi", partOfSpeech: "noun", example: "서울은 큰 도시예요.", exampleTranslation: "Seoul is a big city.", category: "Places" },
  { id: "1-538", korean: "시골", english: "Countryside", pronunciation: "sigol", partOfSpeech: "noun", example: "시골에서 자랐어요.", exampleTranslation: "I grew up in the countryside.", category: "Places" },
  { id: "1-539", korean: "아파트", english: "Apartment", pronunciation: "apateu", partOfSpeech: "noun", example: "아파트에 살아요.", exampleTranslation: "I live in an apartment.", category: "Places" },
  { id: "1-540", korean: "층", english: "Floor / Story (building)", pronunciation: "cheung", partOfSpeech: "noun", example: "삼 층에 있어요.", exampleTranslation: "It's on the third floor.", category: "Places" },
  { id: "1-541", korean: "마당", english: "Yard / Garden", pronunciation: "madang", partOfSpeech: "noun", example: "마당에서 놀아요.", exampleTranslation: "I play in the yard.", category: "Places" },
  { id: "1-542", korean: "지하", english: "Basement / Underground", pronunciation: "jiha", partOfSpeech: "noun", example: "지하에 주차장이 있어요.", exampleTranslation: "There is a parking lot in the basement.", category: "Places" },
  { id: "1-543", korean: "옥상", english: "Rooftop", pronunciation: "oksang", partOfSpeech: "noun", example: "옥상에서 하늘을 봤어요.", exampleTranslation: "I looked at the sky from the rooftop.", category: "Places" },
  { id: "1-544", korean: "엘리베이터", english: "Elevator", pronunciation: "ellibeiteo", partOfSpeech: "noun", example: "엘리베이터를 타요.", exampleTranslation: "I take the elevator.", category: "Places" },
  { id: "1-545", korean: "계단", english: "Stairs", pronunciation: "gyedan", partOfSpeech: "noun", example: "계단으로 올라갔어요.", exampleTranslation: "I went up the stairs.", category: "Places" },
  { id: "1-546", korean: "복도", english: "Hallway / Corridor", pronunciation: "bokdo", partOfSpeech: "noun", example: "복도에서 뛰지 마세요.", exampleTranslation: "Don't run in the hallway.", category: "Places" },
  { id: "1-547", korean: "주소", english: "Address", pronunciation: "juso", partOfSpeech: "noun", example: "주소를 알려 주세요.", exampleTranslation: "Please tell me the address.", category: "Places" },
  { id: "1-548", korean: "세계", english: "World", pronunciation: "segye", partOfSpeech: "noun", example: "세계 여행을 하고 싶어요.", exampleTranslation: "I want to travel the world.", category: "Places" },
  { id: "1-549", korean: "노래방", english: "Karaoke room", pronunciation: "noraebang", partOfSpeech: "noun", example: "노래방에서 노래했어요.", exampleTranslation: "I sang at the karaoke room.", category: "Places" },
  { id: "1-550", korean: "찜질방", english: "Korean sauna / Jjimjilbang", pronunciation: "jjimjilbang", partOfSpeech: "noun", example: "찜질방에서 쉬었어요.", exampleTranslation: "I rested at the Korean sauna.", category: "Places" },
  { id: "1-551", korean: "옷", english: "Clothes", pronunciation: "ot", partOfSpeech: "noun", example: "새 옷을 샀어요.", exampleTranslation: "I bought new clothes.", category: "Clothing & Accessories" },
  { id: "1-552", korean: "바지", english: "Pants / Trousers", pronunciation: "baji", partOfSpeech: "noun", example: "바지가 길어요.", exampleTranslation: "The pants are long.", category: "Clothing & Accessories" },
  { id: "1-553", korean: "치마", english: "Skirt", pronunciation: "chima", partOfSpeech: "noun", example: "치마를 입었어요.", exampleTranslation: "I wore a skirt.", category: "Clothing & Accessories" },
  { id: "1-554", korean: "셔츠", english: "Shirt", pronunciation: "syeocheu", partOfSpeech: "noun", example: "하얀 셔츠를 입어요.", exampleTranslation: "I wear a white shirt.", category: "Clothing & Accessories" },
  { id: "1-555", korean: "모자", english: "Hat / Cap", pronunciation: "moja", partOfSpeech: "noun", example: "모자를 쓰세요.", exampleTranslation: "Wear a hat.", category: "Clothing & Accessories" },
  { id: "1-556", korean: "신발", english: "Shoes", pronunciation: "sinbal", partOfSpeech: "noun", example: "신발을 신으세요.", exampleTranslation: "Put on your shoes.", category: "Clothing & Accessories" },
  { id: "1-557", korean: "양말", english: "Socks", pronunciation: "yangmal", partOfSpeech: "noun", example: "양말을 신어요.", exampleTranslation: "I put on socks.", category: "Clothing & Accessories" },
  { id: "1-558", korean: "장갑", english: "Gloves", pronunciation: "janggap", partOfSpeech: "noun", example: "겨울에 장갑을 끼요.", exampleTranslation: "I wear gloves in winter.", category: "Clothing & Accessories" },
  { id: "1-559", korean: "가방", english: "Bag", pronunciation: "gabang", partOfSpeech: "noun", example: "가방이 무거워요.", exampleTranslation: "The bag is heavy.", category: "Clothing & Accessories" },
  { id: "1-560", korean: "안경", english: "Glasses / Eyeglasses", pronunciation: "angyeong", partOfSpeech: "noun", example: "안경을 써요.", exampleTranslation: "I wear glasses.", category: "Clothing & Accessories" },
  { id: "1-561", korean: "시계", english: "Watch / Clock", pronunciation: "sigye", partOfSpeech: "noun", example: "시계가 멈췄어요.", exampleTranslation: "The clock stopped.", category: "Clothing & Accessories" },
  { id: "1-562", korean: "목걸이", english: "Necklace", pronunciation: "mokgeori", partOfSpeech: "noun", example: "목걸이가 예뻐요.", exampleTranslation: "The necklace is pretty.", category: "Clothing & Accessories" },
  { id: "1-563", korean: "반지", english: "Ring", pronunciation: "banji", partOfSpeech: "noun", example: "반지를 끼었어요.", exampleTranslation: "I put on a ring.", category: "Clothing & Accessories" },
  { id: "1-564", korean: "귀걸이", english: "Earring", pronunciation: "gwigeori", partOfSpeech: "noun", example: "귀걸이를 했어요.", exampleTranslation: "I wore earrings.", category: "Clothing & Accessories" },
  { id: "1-565", korean: "넥타이", english: "Necktie", pronunciation: "nektai", partOfSpeech: "noun", example: "넥타이를 매세요.", exampleTranslation: "Put on a necktie.", category: "Clothing & Accessories" },
  { id: "1-566", korean: "코트", english: "Coat", pronunciation: "koteu", partOfSpeech: "noun", example: "겨울에 코트를 입어요.", exampleTranslation: "I wear a coat in winter.", category: "Clothing & Accessories" },
  { id: "1-567", korean: "재킷", english: "Jacket", pronunciation: "jaekit", partOfSpeech: "noun", example: "재킷을 벗으세요.", exampleTranslation: "Take off your jacket.", category: "Clothing & Accessories" },
  { id: "1-568", korean: "원피스", english: "Dress (one-piece)", pronunciation: "wonpiseu", partOfSpeech: "noun", example: "원피스를 입었어요.", exampleTranslation: "I wore a dress.", category: "Clothing & Accessories" },
  { id: "1-569", korean: "티셔츠", english: "T-shirt", pronunciation: "tisyeocheu", partOfSpeech: "noun", example: "티셔츠가 편해요.", exampleTranslation: "The T-shirt is comfortable.", category: "Clothing & Accessories" },
  { id: "1-570", korean: "청바지", english: "Jeans", pronunciation: "cheongbaji", partOfSpeech: "noun", example: "청바지를 좋아해요.", exampleTranslation: "I like jeans.", category: "Clothing & Accessories" },
  { id: "1-571", korean: "운동화", english: "Sneakers / Athletic shoes", pronunciation: "undonghwa", partOfSpeech: "noun", example: "운동화를 신었어요.", exampleTranslation: "I wore sneakers.", category: "Clothing & Accessories" },
  { id: "1-572", korean: "구두", english: "Dress shoes", pronunciation: "gudu", partOfSpeech: "noun", example: "구두가 예뻐요.", exampleTranslation: "The dress shoes are pretty.", category: "Clothing & Accessories" },
  { id: "1-573", korean: "슬리퍼", english: "Slippers", pronunciation: "seullipeo", partOfSpeech: "noun", example: "집에서 슬리퍼를 신어요.", exampleTranslation: "I wear slippers at home.", category: "Clothing & Accessories" },
  { id: "1-574", korean: "벨트", english: "Belt", pronunciation: "belteu", partOfSpeech: "noun", example: "벨트를 매요.", exampleTranslation: "I put on a belt.", category: "Clothing & Accessories" },
  { id: "1-575", korean: "스카프", english: "Scarf", pronunciation: "seukapeub", partOfSpeech: "noun", example: "스카프를 했어요.", exampleTranslation: "I wore a scarf.", category: "Clothing & Accessories" },
  { id: "1-576", korean: "수건", english: "Towel", pronunciation: "sugeon", partOfSpeech: "noun", example: "수건으로 닦으세요.", exampleTranslation: "Wipe with a towel.", category: "Clothing & Accessories" },
  { id: "1-577", korean: "속옷", english: "Underwear", pronunciation: "sogot", partOfSpeech: "noun", example: "속옷을 갈아입었어요.", exampleTranslation: "I changed my underwear.", category: "Clothing & Accessories" },
  { id: "1-578", korean: "잠옷", english: "Pajamas", pronunciation: "jamot", partOfSpeech: "noun", example: "잠옷으로 갈아입었어요.", exampleTranslation: "I changed into pajamas.", category: "Clothing & Accessories" },
  { id: "1-579", korean: "교복", english: "School uniform", pronunciation: "gyobok", partOfSpeech: "noun", example: "교복을 입고 학교에 가요.", exampleTranslation: "I go to school wearing a uniform.", category: "Clothing & Accessories" },
  { id: "1-580", korean: "양복", english: "Suit (formal)", pronunciation: "yangbok", partOfSpeech: "noun", example: "양복을 입고 출근해요.", exampleTranslation: "I go to work wearing a suit.", category: "Clothing & Accessories" },
  { id: "1-581", korean: "목도리", english: "Muffler / Scarf (winter)", pronunciation: "mokdori", partOfSpeech: "noun", example: "목도리를 하면 따뜻해요.", exampleTranslation: "It's warm when you wear a muffler.", category: "Clothing & Accessories" },
  { id: "1-582", korean: "팔찌", english: "Bracelet", pronunciation: "palji", partOfSpeech: "noun", example: "팔찌가 예뻐요.", exampleTranslation: "The bracelet is pretty.", category: "Clothing & Accessories" },
  { id: "1-583", korean: "지갑", english: "Wallet", pronunciation: "jigap", partOfSpeech: "noun", example: "지갑을 잃어버렸어요.", exampleTranslation: "I lost my wallet.", category: "Clothing & Accessories" },
  { id: "1-584", korean: "우비", english: "Raincoat", pronunciation: "ubi", partOfSpeech: "noun", example: "우비를 입고 나갔어요.", exampleTranslation: "I went out wearing a raincoat.", category: "Clothing & Accessories" },
  { id: "1-585", korean: "장화", english: "Rain boots", pronunciation: "janghwa", partOfSpeech: "noun", example: "비 올 때 장화를 신어요.", exampleTranslation: "I wear rain boots when it rains.", category: "Clothing & Accessories" },
  { id: "1-586", korean: "조끼", english: "Vest", pronunciation: "jokki", partOfSpeech: "noun", example: "조끼를 입었어요.", exampleTranslation: "I wore a vest.", category: "Clothing & Accessories" },
  { id: "1-587", korean: "한복", english: "Korean traditional clothing", pronunciation: "hanbok", partOfSpeech: "noun", example: "설날에 한복을 입어요.", exampleTranslation: "I wear hanbok on New Year's.", category: "Clothing & Accessories" },
  { id: "1-588", korean: "선글라스", english: "Sunglasses", pronunciation: "seongeullaseu", partOfSpeech: "noun", example: "선글라스를 써요.", exampleTranslation: "I wear sunglasses.", category: "Clothing & Accessories" },
  { id: "1-589", korean: "후드티", english: "Hoodie", pronunciation: "huduti", partOfSpeech: "noun", example: "후드티가 편해요.", exampleTranslation: "The hoodie is comfortable.", category: "Clothing & Accessories" },
  { id: "1-590", korean: "패딩", english: "Padded jacket / Puffer jacket", pronunciation: "paeding", partOfSpeech: "noun", example: "겨울에 패딩을 입어요.", exampleTranslation: "I wear a puffer jacket in winter.", category: "Clothing & Accessories" },
  { id: "1-591", korean: "가다", english: "To go", pronunciation: "gada", partOfSpeech: "verb", example: "학교에 가요.", exampleTranslation: "I go to school.", category: "Basic Verbs" },
  { id: "1-592", korean: "오다", english: "To come", pronunciation: "oda", partOfSpeech: "verb", example: "친구가 집에 왔어요.", exampleTranslation: "My friend came to my house.", category: "Basic Verbs" },
  { id: "1-593", korean: "먹다", english: "To eat", pronunciation: "meokda", partOfSpeech: "verb", example: "밥을 먹어요.", exampleTranslation: "I eat rice.", category: "Basic Verbs" },
  { id: "1-594", korean: "마시다", english: "To drink", pronunciation: "masida", partOfSpeech: "verb", example: "물을 마셔요.", exampleTranslation: "I drink water.", category: "Basic Verbs" },
  { id: "1-595", korean: "자다", english: "To sleep", pronunciation: "jada", partOfSpeech: "verb", example: "일찍 자요.", exampleTranslation: "I sleep early.", category: "Basic Verbs" },
  { id: "1-596", korean: "일어나다", english: "To wake up / To get up", pronunciation: "ireonada", partOfSpeech: "verb", example: "아침에 일어나요.", exampleTranslation: "I wake up in the morning.", category: "Basic Verbs" },
  { id: "1-597", korean: "앉다", english: "To sit", pronunciation: "anda", partOfSpeech: "verb", example: "의자에 앉으세요.", exampleTranslation: "Please sit on the chair.", category: "Basic Verbs" },
  { id: "1-598", korean: "서다", english: "To stand", pronunciation: "seoda", partOfSpeech: "verb", example: "줄을 서세요.", exampleTranslation: "Please stand in line.", category: "Basic Verbs" },
  { id: "1-599", korean: "걷다", english: "To walk", pronunciation: "geotda", partOfSpeech: "verb", example: "공원에서 걸어요.", exampleTranslation: "I walk in the park.", category: "Basic Verbs" },
  { id: "1-600", korean: "뛰다", english: "To run / To jump", pronunciation: "ttwida", partOfSpeech: "verb", example: "아이들이 뛰어요.", exampleTranslation: "The children are running.", category: "Basic Verbs" },
  { id: "1-601", korean: "보다", english: "To see / To watch", pronunciation: "boda", partOfSpeech: "verb", example: "영화를 봐요.", exampleTranslation: "I watch a movie.", category: "Basic Verbs" },
  { id: "1-602", korean: "듣다", english: "To listen / To hear", pronunciation: "deutda", partOfSpeech: "verb", example: "음악을 들어요.", exampleTranslation: "I listen to music.", category: "Basic Verbs" },
  { id: "1-603", korean: "말하다", english: "To speak / To say", pronunciation: "malhada", partOfSpeech: "verb", example: "한국어로 말해요.", exampleTranslation: "I speak in Korean.", category: "Basic Verbs" },
  { id: "1-604", korean: "읽다", english: "To read", pronunciation: "ikda", partOfSpeech: "verb", example: "책을 읽어요.", exampleTranslation: "I read a book.", category: "Basic Verbs" },
  { id: "1-605", korean: "쓰다", english: "To write", pronunciation: "sseuda", partOfSpeech: "verb", example: "편지를 써요.", exampleTranslation: "I write a letter.", category: "Basic Verbs" },
  { id: "1-606", korean: "공부하다", english: "To study", pronunciation: "gongbuhada", partOfSpeech: "verb", example: "한국어를 공부해요.", exampleTranslation: "I study Korean.", category: "Basic Verbs" },
  { id: "1-607", korean: "일하다", english: "To work", pronunciation: "ilhada", partOfSpeech: "verb", example: "회사에서 일해요.", exampleTranslation: "I work at a company.", category: "Basic Verbs" },
  { id: "1-608", korean: "놀다", english: "To play / To hang out", pronunciation: "nolda", partOfSpeech: "verb", example: "친구와 놀아요.", exampleTranslation: "I play with my friend.", category: "Basic Verbs" },
  { id: "1-609", korean: "쉬다", english: "To rest", pronunciation: "swida", partOfSpeech: "verb", example: "주말에 쉬어요.", exampleTranslation: "I rest on the weekend.", category: "Basic Verbs" },
  { id: "1-610", korean: "사다", english: "To buy", pronunciation: "sada", partOfSpeech: "verb", example: "옷을 샀어요.", exampleTranslation: "I bought clothes.", category: "Basic Verbs" },
  { id: "1-611", korean: "팔다", english: "To sell", pronunciation: "palda", partOfSpeech: "verb", example: "과일을 팔아요.", exampleTranslation: "I sell fruit.", category: "Basic Verbs" },
  { id: "1-612", korean: "주다", english: "To give", pronunciation: "juda", partOfSpeech: "verb", example: "선물을 줬어요.", exampleTranslation: "I gave a gift.", category: "Basic Verbs" },
  { id: "1-613", korean: "받다", english: "To receive", pronunciation: "batda", partOfSpeech: "verb", example: "편지를 받았어요.", exampleTranslation: "I received a letter.", category: "Basic Verbs" },
  { id: "1-614", korean: "만나다", english: "To meet", pronunciation: "mannada", partOfSpeech: "verb", example: "친구를 만나요.", exampleTranslation: "I meet my friend.", category: "Basic Verbs" },
  { id: "1-615", korean: "기다리다", english: "To wait", pronunciation: "gidarida", partOfSpeech: "verb", example: "버스를 기다려요.", exampleTranslation: "I wait for the bus.", category: "Basic Verbs" },
  { id: "1-616", korean: "찾다", english: "To find / To look for", pronunciation: "chatda", partOfSpeech: "verb", example: "열쇠를 찾아요.", exampleTranslation: "I look for the key.", category: "Basic Verbs" },
  { id: "1-617", korean: "열다", english: "To open", pronunciation: "yeolda", partOfSpeech: "verb", example: "문을 열어요.", exampleTranslation: "I open the door.", category: "Basic Verbs" },
  { id: "1-618", korean: "닫다", english: "To close", pronunciation: "datda", partOfSpeech: "verb", example: "창문을 닫아요.", exampleTranslation: "I close the window.", category: "Basic Verbs" },
  { id: "1-619", korean: "넣다", english: "To put in / To insert", pronunciation: "neota", partOfSpeech: "verb", example: "가방에 책을 넣어요.", exampleTranslation: "I put the book in the bag.", category: "Basic Verbs" },
  { id: "1-620", korean: "빼다", english: "To take out / To remove", pronunciation: "ppaeda", partOfSpeech: "verb", example: "주머니에서 돈을 빼요.", exampleTranslation: "I take money out of my pocket.", category: "Basic Verbs" },
  { id: "1-621", korean: "타다", english: "To ride / To board", pronunciation: "tada", partOfSpeech: "verb", example: "버스를 타요.", exampleTranslation: "I ride the bus.", category: "Basic Verbs" },
  { id: "1-622", korean: "내리다", english: "To get off / To descend", pronunciation: "naerida", partOfSpeech: "verb", example: "다음 역에서 내려요.", exampleTranslation: "I get off at the next station.", category: "Basic Verbs" },
  { id: "1-623", korean: "입다", english: "To wear (clothes)", pronunciation: "ipda", partOfSpeech: "verb", example: "코트를 입어요.", exampleTranslation: "I wear a coat.", category: "Basic Verbs" },
  { id: "1-624", korean: "벗다", english: "To take off (clothes)", pronunciation: "beotda", partOfSpeech: "verb", example: "신발을 벗으세요.", exampleTranslation: "Please take off your shoes.", category: "Basic Verbs" },
  { id: "1-625", korean: "씻다", english: "To wash", pronunciation: "ssitda", partOfSpeech: "verb", example: "손을 씻어요.", exampleTranslation: "I wash my hands.", category: "Basic Verbs" },
  { id: "1-626", korean: "닦다", english: "To wipe / To brush", pronunciation: "dakda", partOfSpeech: "verb", example: "이를 닦아요.", exampleTranslation: "I brush my teeth.", category: "Basic Verbs" },
  { id: "1-627", korean: "요리하다", english: "To cook", pronunciation: "yorihada", partOfSpeech: "verb", example: "저녁을 요리해요.", exampleTranslation: "I cook dinner.", category: "Basic Verbs" },
  { id: "1-628", korean: "청소하다", english: "To clean", pronunciation: "cheongsohada", partOfSpeech: "verb", example: "방을 청소해요.", exampleTranslation: "I clean the room.", category: "Basic Verbs" },
  { id: "1-629", korean: "운동하다", english: "To exercise", pronunciation: "undonghada", partOfSpeech: "verb", example: "매일 운동해요.", exampleTranslation: "I exercise every day.", category: "Basic Verbs" },
  { id: "1-630", korean: "전화하다", english: "To call (phone)", pronunciation: "jeonhwahada", partOfSpeech: "verb", example: "엄마에게 전화해요.", exampleTranslation: "I call my mom.", category: "Basic Verbs" },
  { id: "1-631", korean: "사랑하다", english: "To love", pronunciation: "saranghada", partOfSpeech: "verb", example: "가족을 사랑해요.", exampleTranslation: "I love my family.", category: "Basic Verbs" },
  { id: "1-632", korean: "좋아하다", english: "To like", pronunciation: "joahada", partOfSpeech: "verb", example: "음악을 좋아해요.", exampleTranslation: "I like music.", category: "Basic Verbs" },
  { id: "1-633", korean: "싫어하다", english: "To dislike / To hate", pronunciation: "sireohada", partOfSpeech: "verb", example: "거짓말을 싫어해요.", exampleTranslation: "I hate lies.", category: "Basic Verbs" },
  { id: "1-634", korean: "알다", english: "To know", pronunciation: "alda", partOfSpeech: "verb", example: "그 사람을 알아요.", exampleTranslation: "I know that person.", category: "Basic Verbs" },
  { id: "1-635", korean: "모르다", english: "To not know", pronunciation: "moreuda", partOfSpeech: "verb", example: "길을 몰라요.", exampleTranslation: "I don't know the way.", category: "Basic Verbs" },
  { id: "1-636", korean: "있다", english: "To exist / To have", pronunciation: "itda", partOfSpeech: "verb", example: "돈이 있어요.", exampleTranslation: "I have money.", category: "Basic Verbs" },
  { id: "1-637", korean: "없다", english: "To not exist / To not have", pronunciation: "eopda", partOfSpeech: "verb", example: "시간이 없어요.", exampleTranslation: "I don't have time.", category: "Basic Verbs" },
  { id: "1-638", korean: "되다", english: "To become", pronunciation: "doeda", partOfSpeech: "verb", example: "의사가 되고 싶어요.", exampleTranslation: "I want to become a doctor.", category: "Basic Verbs" },
  { id: "1-639", korean: "하다", english: "To do", pronunciation: "hada", partOfSpeech: "verb", example: "숙제를 해요.", exampleTranslation: "I do homework.", category: "Basic Verbs" },
  { id: "1-640", korean: "만들다", english: "To make", pronunciation: "mandeulda", partOfSpeech: "verb", example: "케이크를 만들어요.", exampleTranslation: "I make a cake.", category: "Basic Verbs" },
  { id: "1-641", korean: "배우다", english: "To learn", pronunciation: "baeuda", partOfSpeech: "verb", example: "한국어를 배워요.", exampleTranslation: "I learn Korean.", category: "Basic Verbs" },
  { id: "1-642", korean: "가르치다", english: "To teach", pronunciation: "gareuchida", partOfSpeech: "verb", example: "영어를 가르쳐요.", exampleTranslation: "I teach English.", category: "Basic Verbs" },
  { id: "1-643", korean: "살다", english: "To live", pronunciation: "salda", partOfSpeech: "verb", example: "서울에 살아요.", exampleTranslation: "I live in Seoul.", category: "Basic Verbs" },
  { id: "1-644", korean: "죽다", english: "To die", pronunciation: "jukda", partOfSpeech: "verb", example: "꽃이 죽었어요.", exampleTranslation: "The flower died.", category: "Basic Verbs" },
  { id: "1-645", korean: "태어나다", english: "To be born", pronunciation: "taeeонада", partOfSpeech: "verb", example: "서울에서 태어났어요.", exampleTranslation: "I was born in Seoul.", category: "Basic Verbs" },
  { id: "1-646", korean: "웃다", english: "To laugh / To smile", pronunciation: "utda", partOfSpeech: "verb", example: "아이가 웃어요.", exampleTranslation: "The child is laughing.", category: "Basic Verbs" },
  { id: "1-647", korean: "울다", english: "To cry", pronunciation: "ulda", partOfSpeech: "verb", example: "아기가 울어요.", exampleTranslation: "The baby is crying.", category: "Basic Verbs" },
  { id: "1-648", korean: "노래하다", english: "To sing", pronunciation: "noraehada", partOfSpeech: "verb", example: "노래를 불러요.", exampleTranslation: "I sing a song.", category: "Basic Verbs" },
  { id: "1-649", korean: "춤추다", english: "To dance", pronunciation: "chumchuda", partOfSpeech: "verb", example: "음악에 맞춰 춤춰요.", exampleTranslation: "I dance to the music.", category: "Basic Verbs" },
  { id: "1-650", korean: "수영하다", english: "To swim", pronunciation: "suyeonghada", partOfSpeech: "verb", example: "바다에서 수영해요.", exampleTranslation: "I swim in the sea.", category: "Basic Verbs" },
  { id: "1-651", korean: "그리다", english: "To draw / To paint", pronunciation: "geurida", partOfSpeech: "verb", example: "그림을 그려요.", exampleTranslation: "I draw a picture.", category: "Basic Verbs" },
  { id: "1-652", korean: "사진 찍다", english: "To take a photo", pronunciation: "sajin jjikda", partOfSpeech: "verb", example: "사진을 찍어요.", exampleTranslation: "I take a photo.", category: "Basic Verbs" },
  { id: "1-653", korean: "여행하다", english: "To travel", pronunciation: "yeohaenghada", partOfSpeech: "verb", example: "유럽을 여행했어요.", exampleTranslation: "I traveled to Europe.", category: "Basic Verbs" },
  { id: "1-654", korean: "도착하다", english: "To arrive", pronunciation: "dochakhada", partOfSpeech: "verb", example: "공항에 도착했어요.", exampleTranslation: "I arrived at the airport.", category: "Basic Verbs" },
  { id: "1-655", korean: "출발하다", english: "To depart", pronunciation: "chulbalhada", partOfSpeech: "verb", example: "아침에 출발해요.", exampleTranslation: "I depart in the morning.", category: "Basic Verbs" },
  { id: "1-656", korean: "들어가다", english: "To go in / To enter", pronunciation: "deureogada", partOfSpeech: "verb", example: "집에 들어가요.", exampleTranslation: "I go into the house.", category: "Basic Verbs" },
  { id: "1-657", korean: "나가다", english: "To go out / To exit", pronunciation: "nagada", partOfSpeech: "verb", example: "밖에 나가요.", exampleTranslation: "I go outside.", category: "Basic Verbs" },
  { id: "1-658", korean: "올라가다", english: "To go up", pronunciation: "ollagada", partOfSpeech: "verb", example: "산에 올라가요.", exampleTranslation: "I go up the mountain.", category: "Basic Verbs" },
  { id: "1-659", korean: "내려가다", english: "To go down", pronunciation: "naeryeogada", partOfSpeech: "verb", example: "계단을 내려가요.", exampleTranslation: "I go down the stairs.", category: "Basic Verbs" },
  { id: "1-660", korean: "돌아가다", english: "To go back / To return", pronunciation: "doragada", partOfSpeech: "verb", example: "집으로 돌아가요.", exampleTranslation: "I go back home.", category: "Basic Verbs" },
  { id: "1-661", korean: "돌아오다", english: "To come back / To return", pronunciation: "doraoda", partOfSpeech: "verb", example: "곧 돌아올게요.", exampleTranslation: "I'll come back soon.", category: "Basic Verbs" },
  { id: "1-662", korean: "보내다", english: "To send", pronunciation: "bonaeda", partOfSpeech: "verb", example: "편지를 보내요.", exampleTranslation: "I send a letter.", category: "Basic Verbs" },
  { id: "1-663", korean: "가지다", english: "To have / To hold", pronunciation: "gajida", partOfSpeech: "verb", example: "펜을 가지고 있어요.", exampleTranslation: "I have a pen.", category: "Basic Verbs" },
  { id: "1-664", korean: "놓다", english: "To put down / To place", pronunciation: "nota", partOfSpeech: "verb", example: "책상 위에 놓으세요.", exampleTranslation: "Please put it on the desk.", category: "Basic Verbs" },
  { id: "1-665", korean: "잡다", english: "To grab / To catch", pronunciation: "japda", partOfSpeech: "verb", example: "손을 잡으세요.", exampleTranslation: "Please hold my hand.", category: "Basic Verbs" },
  { id: "1-666", korean: "던지다", english: "To throw", pronunciation: "deonjida", partOfSpeech: "verb", example: "공을 던져요.", exampleTranslation: "I throw the ball.", category: "Basic Verbs" },
  { id: "1-667", korean: "치다", english: "To hit / To play (instrument)", pronunciation: "chida", partOfSpeech: "verb", example: "피아노를 쳐요.", exampleTranslation: "I play the piano.", category: "Basic Verbs" },
  { id: "1-668", korean: "잠들다", english: "To fall asleep", pronunciation: "jamdeulda", partOfSpeech: "verb", example: "아이가 잠들었어요.", exampleTranslation: "The child fell asleep.", category: "Basic Verbs" },
  { id: "1-669", korean: "깨다", english: "To wake up / To break", pronunciation: "kkaeda", partOfSpeech: "verb", example: "소리에 깼어요.", exampleTranslation: "I woke up to a sound.", category: "Basic Verbs" },
  { id: "1-670", korean: "끝나다", english: "To end / To finish", pronunciation: "kkeunnada", partOfSpeech: "verb", example: "수업이 끝났어요.", exampleTranslation: "The class ended.", category: "Basic Verbs" },
  { id: "1-671", korean: "시작하다", english: "To start / To begin", pronunciation: "sijakhada", partOfSpeech: "verb", example: "수업이 시작해요.", exampleTranslation: "The class starts.", category: "Basic Verbs" },
  { id: "1-672", korean: "준비하다", english: "To prepare", pronunciation: "junbihada", partOfSpeech: "verb", example: "시험을 준비해요.", exampleTranslation: "I prepare for the exam.", category: "Basic Verbs" },
  { id: "1-673", korean: "결혼하다", english: "To marry", pronunciation: "gyeolhonhada", partOfSpeech: "verb", example: "내년에 결혼해요.", exampleTranslation: "I'm getting married next year.", category: "Basic Verbs" },
  { id: "1-674", korean: "이사하다", english: "To move (house)", pronunciation: "isahada", partOfSpeech: "verb", example: "다음 달에 이사해요.", exampleTranslation: "I'm moving next month.", category: "Basic Verbs" },
  { id: "1-675", korean: "운전하다", english: "To drive", pronunciation: "unjeonhada", partOfSpeech: "verb", example: "차를 운전해요.", exampleTranslation: "I drive a car.", category: "Basic Verbs" },
  { id: "1-676", korean: "세수하다", english: "To wash one's face", pronunciation: "sesuhada", partOfSpeech: "verb", example: "아침에 세수해요.", exampleTranslation: "I wash my face in the morning.", category: "Basic Verbs" },
  { id: "1-677", korean: "샤워하다", english: "To take a shower", pronunciation: "syawohada", partOfSpeech: "verb", example: "저녁에 샤워해요.", exampleTranslation: "I take a shower in the evening.", category: "Basic Verbs" },
  { id: "1-678", korean: "빌리다", english: "To borrow / To lend", pronunciation: "billida", partOfSpeech: "verb", example: "책을 빌렸어요.", exampleTranslation: "I borrowed a book.", category: "Basic Verbs" },
  { id: "1-679", korean: "갈아타다", english: "To transfer (transportation)", pronunciation: "garatada", partOfSpeech: "verb", example: "지하철을 갈아타요.", exampleTranslation: "I transfer subways.", category: "Basic Verbs" },
  { id: "1-680", korean: "지나다", english: "To pass / To go by", pronunciation: "jinada", partOfSpeech: "verb", example: "시간이 빨리 지나요.", exampleTranslation: "Time passes quickly.", category: "Basic Verbs" },
  { id: "1-681", korean: "걸리다", english: "To take (time) / To catch (illness)", pronunciation: "geollida", partOfSpeech: "verb", example: "한 시간 걸려요.", exampleTranslation: "It takes one hour.", category: "Basic Verbs" },
  { id: "1-682", korean: "쓰다", english: "To use / To wear (hat/glasses)", pronunciation: "sseuda", partOfSpeech: "verb", example: "모자를 써요.", exampleTranslation: "I wear a hat.", category: "Basic Verbs" },
  { id: "1-683", korean: "고르다", english: "To choose / To pick", pronunciation: "goreuda", partOfSpeech: "verb", example: "하나를 골라요.", exampleTranslation: "I pick one.", category: "Basic Verbs" },
  { id: "1-684", korean: "바꾸다", english: "To change / To exchange", pronunciation: "bakkuda", partOfSpeech: "verb", example: "옷을 바꿨어요.", exampleTranslation: "I changed clothes.", category: "Basic Verbs" },
  { id: "1-685", korean: "끓이다", english: "To boil", pronunciation: "kkeurida", partOfSpeech: "verb", example: "물을 끓여요.", exampleTranslation: "I boil water.", category: "Basic Verbs" },
  { id: "1-686", korean: "굽다", english: "To grill / To bake", pronunciation: "gupda", partOfSpeech: "verb", example: "고기를 구워요.", exampleTranslation: "I grill meat.", category: "Basic Verbs" },
  { id: "1-687", korean: "튀기다", english: "To fry", pronunciation: "twigida", partOfSpeech: "verb", example: "감자를 튀겨요.", exampleTranslation: "I fry potatoes.", category: "Basic Verbs" },
  { id: "1-688", korean: "썰다", english: "To slice / To chop", pronunciation: "sseolda", partOfSpeech: "verb", example: "양파를 썰어요.", exampleTranslation: "I chop the onion.", category: "Basic Verbs" },
  { id: "1-689", korean: "볶다", english: "To stir-fry", pronunciation: "bokda", partOfSpeech: "verb", example: "야채를 볶아요.", exampleTranslation: "I stir-fry vegetables.", category: "Basic Verbs" },
  { id: "1-690", korean: "데우다", english: "To heat up / To warm up", pronunciation: "deuda", partOfSpeech: "verb", example: "음식을 데워요.", exampleTranslation: "I heat up the food.", category: "Basic Verbs" },
  { id: "1-691", korean: "빨다", english: "To wash (laundry)", pronunciation: "ppalda", partOfSpeech: "verb", example: "옷을 빨아요.", exampleTranslation: "I wash the clothes.", category: "Basic Verbs" },
  { id: "1-692", korean: "말리다", english: "To dry", pronunciation: "mallida", partOfSpeech: "verb", example: "머리를 말려요.", exampleTranslation: "I dry my hair.", category: "Basic Verbs" },
  { id: "1-693", korean: "다리다", english: "To iron", pronunciation: "darida", partOfSpeech: "verb", example: "셔츠를 다려요.", exampleTranslation: "I iron the shirt.", category: "Basic Verbs" },
  { id: "1-694", korean: "정리하다", english: "To organize / To tidy up", pronunciation: "jeongrihada", partOfSpeech: "verb", example: "책상을 정리해요.", exampleTranslation: "I tidy up the desk.", category: "Basic Verbs" },
  { id: "1-695", korean: "예약하다", english: "To reserve / To book", pronunciation: "yeyakhada", partOfSpeech: "verb", example: "식당을 예약했어요.", exampleTranslation: "I booked a restaurant.", category: "Basic Verbs" },
  { id: "1-696", korean: "주문하다", english: "To order", pronunciation: "jumunhada", partOfSpeech: "verb", example: "음식을 주문해요.", exampleTranslation: "I order food.", category: "Basic Verbs" },
  { id: "1-697", korean: "계산하다", english: "To pay / To calculate", pronunciation: "gyesanhada", partOfSpeech: "verb", example: "계산해 주세요.", exampleTranslation: "Please let me pay.", category: "Basic Verbs" },
  { id: "1-698", korean: "약속하다", english: "To promise / To make plans", pronunciation: "yaksokhada", partOfSpeech: "verb", example: "친구와 약속했어요.", exampleTranslation: "I made plans with my friend.", category: "Basic Verbs" },
  { id: "1-699", korean: "초대하다", english: "To invite", pronunciation: "chodaehada", partOfSpeech: "verb", example: "친구를 초대했어요.", exampleTranslation: "I invited my friend.", category: "Basic Verbs" },
  { id: "1-700", korean: "참가하다", english: "To participate", pronunciation: "chamgahada", partOfSpeech: "verb", example: "대회에 참가해요.", exampleTranslation: "I participate in the competition.", category: "Basic Verbs" },
  { id: "1-701", korean: "연습하다", english: "To practice", pronunciation: "yeonseupada", partOfSpeech: "verb", example: "매일 연습해요.", exampleTranslation: "I practice every day.", category: "Basic Verbs" },
  { id: "1-702", korean: "졸업하다", english: "To graduate", pronunciation: "joreopada", partOfSpeech: "verb", example: "대학교를 졸업했어요.", exampleTranslation: "I graduated from university.", category: "Basic Verbs" },
  { id: "1-703", korean: "입학하다", english: "To enter school / To enroll", pronunciation: "ipakhada", partOfSpeech: "verb", example: "초등학교에 입학했어요.", exampleTranslation: "I enrolled in elementary school.", category: "Basic Verbs" },
  { id: "1-704", korean: "출근하다", english: "To go to work", pronunciation: "chulgeunhada", partOfSpeech: "verb", example: "아침에 출근해요.", exampleTranslation: "I go to work in the morning.", category: "Basic Verbs" },
  { id: "1-705", korean: "퇴근하다", english: "To leave work", pronunciation: "toegeunhada", partOfSpeech: "verb", example: "여섯 시에 퇴근해요.", exampleTranslation: "I leave work at six.", category: "Basic Verbs" },
  { id: "1-706", korean: "인사하다", english: "To greet", pronunciation: "insahada", partOfSpeech: "verb", example: "선생님께 인사해요.", exampleTranslation: "I greet the teacher.", category: "Basic Verbs" },
  { id: "1-707", korean: "소개하다", english: "To introduce", pronunciation: "sogaehada", partOfSpeech: "verb", example: "자기소개를 해요.", exampleTranslation: "I introduce myself.", category: "Basic Verbs" },
  { id: "1-708", korean: "질문하다", english: "To ask a question", pronunciation: "jilmunhada", partOfSpeech: "verb", example: "선생님께 질문해요.", exampleTranslation: "I ask the teacher a question.", category: "Basic Verbs" },
  { id: "1-709", korean: "대답하다", english: "To answer / To reply", pronunciation: "daedaphada", partOfSpeech: "verb", example: "질문에 대답해요.", exampleTranslation: "I answer the question.", category: "Basic Verbs" },
  { id: "1-710", korean: "이야기하다", english: "To talk / To tell a story", pronunciation: "iyagihada", partOfSpeech: "verb", example: "친구와 이야기해요.", exampleTranslation: "I talk with my friend.", category: "Basic Verbs" },
  { id: "1-711", korean: "설명하다", english: "To explain", pronunciation: "seolmyeonghada", partOfSpeech: "verb", example: "자세히 설명해 주세요.", exampleTranslation: "Please explain in detail.", category: "Basic Verbs" },
  { id: "1-712", korean: "생각하다", english: "To think", pronunciation: "saenggakhada", partOfSpeech: "verb", example: "잘 생각해 보세요.", exampleTranslation: "Please think about it carefully.", category: "Basic Verbs" },
  { id: "1-713", korean: "믿다", english: "To believe / To trust", pronunciation: "mitda", partOfSpeech: "verb", example: "저를 믿으세요.", exampleTranslation: "Please trust me.", category: "Basic Verbs" },
  { id: "1-714", korean: "잊다", english: "To forget", pronunciation: "itda", partOfSpeech: "verb", example: "이름을 잊었어요.", exampleTranslation: "I forgot the name.", category: "Basic Verbs" },
  { id: "1-715", korean: "기억하다", english: "To remember", pronunciation: "gieokhada", partOfSpeech: "verb", example: "그 날을 기억해요.", exampleTranslation: "I remember that day.", category: "Basic Verbs" },
  { id: "1-716", korean: "느끼다", english: "To feel", pronunciation: "neukkida", partOfSpeech: "verb", example: "행복을 느껴요.", exampleTranslation: "I feel happiness.", category: "Basic Verbs" },
  { id: "1-717", korean: "결정하다", english: "To decide", pronunciation: "gyeoljeonghada", partOfSpeech: "verb", example: "빨리 결정하세요.", exampleTranslation: "Please decide quickly.", category: "Basic Verbs" },
  { id: "1-718", korean: "도와주다", english: "To help", pronunciation: "dowajuda", partOfSpeech: "verb", example: "저를 도와주세요.", exampleTranslation: "Please help me.", category: "Basic Verbs" },
  { id: "1-719", korean: "부르다", english: "To call / To sing", pronunciation: "bureuda", partOfSpeech: "verb", example: "이름을 불러요.", exampleTranslation: "I call the name.", category: "Basic Verbs" },
  { id: "1-720", korean: "지키다", english: "To protect / To keep", pronunciation: "jikida", partOfSpeech: "verb", example: "약속을 지켜요.", exampleTranslation: "I keep my promise.", category: "Basic Verbs" },
  { id: "1-721", korean: "바라다", english: "To wish / To hope", pronunciation: "barada", partOfSpeech: "verb", example: "행복을 바라요.", exampleTranslation: "I wish for happiness.", category: "Basic Verbs" },
  { id: "1-722", korean: "필요하다", english: "To need", pronunciation: "piryohada", partOfSpeech: "verb", example: "도움이 필요해요.", exampleTranslation: "I need help.", category: "Basic Verbs" },
  { id: "1-723", korean: "다니다", english: "To attend / To commute", pronunciation: "danida", partOfSpeech: "verb", example: "학교에 다녀요.", exampleTranslation: "I attend school.", category: "Basic Verbs" },
  { id: "1-724", korean: "넘어지다", english: "To fall down", pronunciation: "neomeojida", partOfSpeech: "verb", example: "길에서 넘어졌어요.", exampleTranslation: "I fell down on the road.", category: "Basic Verbs" },
  { id: "1-725", korean: "고치다", english: "To fix / To repair", pronunciation: "gochida", partOfSpeech: "verb", example: "컴퓨터를 고쳤어요.", exampleTranslation: "I fixed the computer.", category: "Basic Verbs" },
  { id: "1-726", korean: "깨뜨리다", english: "To break (something)", pronunciation: "kkaetteurida", partOfSpeech: "verb", example: "컵을 깨뜨렸어요.", exampleTranslation: "I broke the cup.", category: "Basic Verbs" },
  { id: "1-727", korean: "붙이다", english: "To attach / To stick", pronunciation: "buchida", partOfSpeech: "verb", example: "우표를 붙여요.", exampleTranslation: "I stick a stamp.", category: "Basic Verbs" },
  { id: "1-728", korean: "떼다", english: "To peel off / To remove", pronunciation: "tteda", partOfSpeech: "verb", example: "스티커를 떼요.", exampleTranslation: "I peel off the sticker.", category: "Basic Verbs" },
  { id: "1-729", korean: "켜다", english: "To turn on", pronunciation: "kyeoda", partOfSpeech: "verb", example: "불을 켜요.", exampleTranslation: "I turn on the light.", category: "Basic Verbs" },
  { id: "1-730", korean: "끄다", english: "To turn off", pronunciation: "kkeuda", partOfSpeech: "verb", example: "텔레비전을 꺼요.", exampleTranslation: "I turn off the TV.", category: "Basic Verbs" },
  { id: "1-731", korean: "신다", english: "To put on (shoes)", pronunciation: "sinda", partOfSpeech: "verb", example: "신발을 신어요.", exampleTranslation: "I put on shoes.", category: "Basic Verbs" },
  { id: "1-732", korean: "끼다", english: "To wear (ring/gloves)", pronunciation: "kkida", partOfSpeech: "verb", example: "장갑을 껴요.", exampleTranslation: "I wear gloves.", category: "Basic Verbs" },
  { id: "1-733", korean: "자르다", english: "To cut", pronunciation: "jareuda", partOfSpeech: "verb", example: "종이를 잘라요.", exampleTranslation: "I cut paper.", category: "Basic Verbs" },
  { id: "1-734", korean: "움직이다", english: "To move", pronunciation: "umjigida", partOfSpeech: "verb", example: "움직이지 마세요.", exampleTranslation: "Don't move.", category: "Basic Verbs" },
  { id: "1-735", korean: "나누다", english: "To share / To divide", pronunciation: "nanuda", partOfSpeech: "verb", example: "음식을 나눠 먹어요.", exampleTranslation: "We share and eat the food.", category: "Basic Verbs" },
  { id: "1-736", korean: "모으다", english: "To collect / To gather", pronunciation: "moeuda", partOfSpeech: "verb", example: "돈을 모아요.", exampleTranslation: "I save money.", category: "Basic Verbs" },
  { id: "1-737", korean: "싸다", english: "To pack / To wrap", pronunciation: "ssada", partOfSpeech: "verb", example: "짐을 싸요.", exampleTranslation: "I pack my bags.", category: "Basic Verbs" },
  { id: "1-738", korean: "세우다", english: "To park / To stop", pronunciation: "seuda", partOfSpeech: "verb", example: "차를 세워요.", exampleTranslation: "I park the car.", category: "Basic Verbs" },
  { id: "1-739", korean: "배달하다", english: "To deliver", pronunciation: "baedalhada", partOfSpeech: "verb", example: "음식을 배달해요.", exampleTranslation: "I deliver food.", category: "Basic Verbs" },
  { id: "1-740", korean: "확인하다", english: "To check / To confirm", pronunciation: "hwaginhada", partOfSpeech: "verb", example: "시간을 확인해요.", exampleTranslation: "I check the time.", category: "Basic Verbs" },
  { id: "1-741", korean: "크다", english: "To be big / Large", pronunciation: "keuda", partOfSpeech: "adjective", example: "이 집이 커요.", exampleTranslation: "This house is big.", category: "Basic Adjectives" },
  { id: "1-742", korean: "작다", english: "To be small / Little", pronunciation: "jakda", partOfSpeech: "adjective", example: "이 가방이 작아요.", exampleTranslation: "This bag is small.", category: "Basic Adjectives" },
  { id: "1-743", korean: "많다", english: "To be many / Much", pronunciation: "manta", partOfSpeech: "adjective", example: "사람이 많아요.", exampleTranslation: "There are many people.", category: "Basic Adjectives" },
  { id: "1-744", korean: "적다", english: "To be few / Little", pronunciation: "jeokda", partOfSpeech: "adjective", example: "학생이 적어요.", exampleTranslation: "There are few students.", category: "Basic Adjectives" },
  { id: "1-745", korean: "좋다", english: "To be good / Nice", pronunciation: "jota", partOfSpeech: "adjective", example: "날씨가 좋아요.", exampleTranslation: "The weather is nice.", category: "Basic Adjectives" },
  { id: "1-746", korean: "나쁘다", english: "To be bad", pronunciation: "nappeuda", partOfSpeech: "adjective", example: "기분이 나빠요.", exampleTranslation: "I feel bad.", category: "Basic Adjectives" },
  { id: "1-747", korean: "새롭다", english: "To be new", pronunciation: "saeropda", partOfSpeech: "adjective", example: "새로운 옷을 입었어요.", exampleTranslation: "I wore new clothes.", category: "Basic Adjectives" },
  { id: "1-748", korean: "오래되다", english: "To be old (things)", pronunciation: "oraedoeda", partOfSpeech: "adjective", example: "이 건물은 오래됐어요.", exampleTranslation: "This building is old.", category: "Basic Adjectives" },
  { id: "1-749", korean: "높다", english: "To be high / Tall", pronunciation: "nopda", partOfSpeech: "adjective", example: "산이 높아요.", exampleTranslation: "The mountain is high.", category: "Basic Adjectives" },
  { id: "1-750", korean: "낮다", english: "To be low", pronunciation: "natda", partOfSpeech: "adjective", example: "가격이 낮아요.", exampleTranslation: "The price is low.", category: "Basic Adjectives" },
  { id: "1-751", korean: "길다", english: "To be long", pronunciation: "gilda", partOfSpeech: "adjective", example: "머리가 길어요.", exampleTranslation: "The hair is long.", category: "Basic Adjectives" },
  { id: "1-752", korean: "짧다", english: "To be short (length)", pronunciation: "jjalda", partOfSpeech: "adjective", example: "바지가 짧아요.", exampleTranslation: "The pants are short.", category: "Basic Adjectives" },
  { id: "1-753", korean: "넓다", english: "To be wide / Spacious", pronunciation: "neolda", partOfSpeech: "adjective", example: "방이 넓어요.", exampleTranslation: "The room is spacious.", category: "Basic Adjectives" },
  { id: "1-754", korean: "좁다", english: "To be narrow", pronunciation: "jopda", partOfSpeech: "adjective", example: "길이 좁아요.", exampleTranslation: "The road is narrow.", category: "Basic Adjectives" },
  { id: "1-755", korean: "뜨겁다", english: "To be hot (touch)", pronunciation: "tteugeopda", partOfSpeech: "adjective", example: "물이 뜨거워요.", exampleTranslation: "The water is hot.", category: "Basic Adjectives" },
  { id: "1-756", korean: "차갑다", english: "To be cold (touch)", pronunciation: "chagapda", partOfSpeech: "adjective", example: "손이 차가워요.", exampleTranslation: "The hands are cold.", category: "Basic Adjectives" },
  { id: "1-757", korean: "덥다", english: "To be hot (weather)", pronunciation: "deopda", partOfSpeech: "adjective", example: "오늘 더워요.", exampleTranslation: "It's hot today.", category: "Basic Adjectives" },
  { id: "1-758", korean: "춥다", english: "To be cold (weather)", pronunciation: "chupda", partOfSpeech: "adjective", example: "겨울에 추워요.", exampleTranslation: "It's cold in winter.", category: "Basic Adjectives" },
  { id: "1-759", korean: "밝다", english: "To be bright", pronunciation: "balkda", partOfSpeech: "adjective", example: "방이 밝아요.", exampleTranslation: "The room is bright.", category: "Basic Adjectives" },
  { id: "1-760", korean: "어둡다", english: "To be dark", pronunciation: "eodupda", partOfSpeech: "adjective", example: "밖이 어두워요.", exampleTranslation: "It's dark outside.", category: "Basic Adjectives" },
  { id: "1-761", korean: "빠르다", english: "To be fast / Quick", pronunciation: "ppareuda", partOfSpeech: "adjective", example: "이 차가 빨라요.", exampleTranslation: "This car is fast.", category: "Basic Adjectives" },
  { id: "1-762", korean: "느리다", english: "To be slow", pronunciation: "neurida", partOfSpeech: "adjective", example: "거북이는 느려요.", exampleTranslation: "The turtle is slow.", category: "Basic Adjectives" },
  { id: "1-763", korean: "무겁다", english: "To be heavy", pronunciation: "mugeopda", partOfSpeech: "adjective", example: "가방이 무거워요.", exampleTranslation: "The bag is heavy.", category: "Basic Adjectives" },
  { id: "1-764", korean: "가볍다", english: "To be light (weight)", pronunciation: "gabyeopda", partOfSpeech: "adjective", example: "이 책은 가벼워요.", exampleTranslation: "This book is light.", category: "Basic Adjectives" },
  { id: "1-765", korean: "쉽다", english: "To be easy", pronunciation: "swipda", partOfSpeech: "adjective", example: "이 문제는 쉬워요.", exampleTranslation: "This problem is easy.", category: "Basic Adjectives" },
  { id: "1-766", korean: "어렵다", english: "To be difficult", pronunciation: "eoryeopda", partOfSpeech: "adjective", example: "한국어가 어려워요.", exampleTranslation: "Korean is difficult.", category: "Basic Adjectives" },
  { id: "1-767", korean: "맛있다", english: "To be delicious", pronunciation: "masitda", partOfSpeech: "adjective", example: "이 음식이 맛있어요.", exampleTranslation: "This food is delicious.", category: "Basic Adjectives" },
  { id: "1-768", korean: "맛없다", english: "To be tasteless / Not delicious", pronunciation: "madeopda", partOfSpeech: "adjective", example: "이 음식은 맛없어요.", exampleTranslation: "This food is not delicious.", category: "Basic Adjectives" },
  { id: "1-769", korean: "예쁘다", english: "To be pretty", pronunciation: "yeppeuda", partOfSpeech: "adjective", example: "꽃이 예뻐요.", exampleTranslation: "The flower is pretty.", category: "Basic Adjectives" },
  { id: "1-770", korean: "멋있다", english: "To be cool / Handsome", pronunciation: "meositda", partOfSpeech: "adjective", example: "저 사람은 멋있어요.", exampleTranslation: "That person is cool.", category: "Basic Adjectives" },
  { id: "1-771", korean: "귀엽다", english: "To be cute", pronunciation: "gwiyeopda", partOfSpeech: "adjective", example: "아기가 귀여워요.", exampleTranslation: "The baby is cute.", category: "Basic Adjectives" },
  { id: "1-772", korean: "아름답다", english: "To be beautiful", pronunciation: "areumdapda", partOfSpeech: "adjective", example: "경치가 아름다워요.", exampleTranslation: "The scenery is beautiful.", category: "Basic Adjectives" },
  { id: "1-773", korean: "깨끗하다", english: "To be clean", pronunciation: "kkaekkeuthada", partOfSpeech: "adjective", example: "방이 깨끗해요.", exampleTranslation: "The room is clean.", category: "Basic Adjectives" },
  { id: "1-774", korean: "더럽다", english: "To be dirty", pronunciation: "deoreopda", partOfSpeech: "adjective", example: "옷이 더러워요.", exampleTranslation: "The clothes are dirty.", category: "Basic Adjectives" },
  { id: "1-775", korean: "시끄럽다", english: "To be noisy / Loud", pronunciation: "sikkeureopda", partOfSpeech: "adjective", example: "밖이 시끄러워요.", exampleTranslation: "It's noisy outside.", category: "Basic Adjectives" },
  { id: "1-776", korean: "조용하다", english: "To be quiet", pronunciation: "joyonghada", partOfSpeech: "adjective", example: "도서관은 조용해요.", exampleTranslation: "The library is quiet.", category: "Basic Adjectives" },
  { id: "1-777", korean: "편하다", english: "To be comfortable", pronunciation: "pyeonhada", partOfSpeech: "adjective", example: "이 의자가 편해요.", exampleTranslation: "This chair is comfortable.", category: "Basic Adjectives" },
  { id: "1-778", korean: "불편하다", english: "To be uncomfortable", pronunciation: "bulpyeonhada", partOfSpeech: "adjective", example: "신발이 불편해요.", exampleTranslation: "The shoes are uncomfortable.", category: "Basic Adjectives" },
  { id: "1-779", korean: "비싸다", english: "To be expensive", pronunciation: "bissada", partOfSpeech: "adjective", example: "이 가방이 비싸요.", exampleTranslation: "This bag is expensive.", category: "Basic Adjectives" },
  { id: "1-780", korean: "싸다", english: "To be cheap", pronunciation: "ssada", partOfSpeech: "adjective", example: "이 물건이 싸요.", exampleTranslation: "This item is cheap.", category: "Basic Adjectives" },
  { id: "1-781", korean: "재미있다", english: "To be fun / Interesting", pronunciation: "jaemiitda", partOfSpeech: "adjective", example: "이 영화가 재미있어요.", exampleTranslation: "This movie is fun.", category: "Basic Adjectives" },
  { id: "1-782", korean: "재미없다", english: "To be boring / Not interesting", pronunciation: "jaemieopda", partOfSpeech: "adjective", example: "이 책은 재미없어요.", exampleTranslation: "This book is boring.", category: "Basic Adjectives" },
  { id: "1-783", korean: "위험하다", english: "To be dangerous", pronunciation: "wiheomhada", partOfSpeech: "adjective", example: "여기는 위험해요.", exampleTranslation: "It's dangerous here.", category: "Basic Adjectives" },
  { id: "1-784", korean: "안전하다", english: "To be safe", pronunciation: "anjeonhada", partOfSpeech: "adjective", example: "이 곳은 안전해요.", exampleTranslation: "This place is safe.", category: "Basic Adjectives" },
  { id: "1-785", korean: "중요하다", english: "To be important", pronunciation: "jungyohada", partOfSpeech: "adjective", example: "건강이 중요해요.", exampleTranslation: "Health is important.", category: "Basic Adjectives" },
  { id: "1-786", korean: "간단하다", english: "To be simple", pronunciation: "gandanhada", partOfSpeech: "adjective", example: "이 요리는 간단해요.", exampleTranslation: "This dish is simple.", category: "Basic Adjectives" },
  { id: "1-787", korean: "복잡하다", english: "To be complicated", pronunciation: "bokjaphada", partOfSpeech: "adjective", example: "이 문제는 복잡해요.", exampleTranslation: "This problem is complicated.", category: "Basic Adjectives" },
  { id: "1-788", korean: "따뜻하다", english: "To be warm", pronunciation: "ttatteuthada", partOfSpeech: "adjective", example: "봄에 따뜻해요.", exampleTranslation: "It's warm in spring.", category: "Basic Adjectives" },
  { id: "1-789", korean: "시원하다", english: "To be cool / Refreshing", pronunciation: "siwonhada", partOfSpeech: "adjective", example: "바람이 시원해요.", exampleTranslation: "The wind is cool.", category: "Basic Adjectives" },
  { id: "1-790", korean: "맵다", english: "To be spicy", pronunciation: "maepda", partOfSpeech: "adjective", example: "이 음식이 매워요.", exampleTranslation: "This food is spicy.", category: "Basic Adjectives" },
  { id: "1-791", korean: "달다", english: "To be sweet", pronunciation: "dalda", partOfSpeech: "adjective", example: "이 과일이 달아요.", exampleTranslation: "This fruit is sweet.", category: "Basic Adjectives" },
  { id: "1-792", korean: "짜다", english: "To be salty", pronunciation: "jjada", partOfSpeech: "adjective", example: "국이 짜요.", exampleTranslation: "The soup is salty.", category: "Basic Adjectives" },
  { id: "1-793", korean: "시다", english: "To be sour", pronunciation: "sida", partOfSpeech: "adjective", example: "레몬이 셔요.", exampleTranslation: "The lemon is sour.", category: "Basic Adjectives" },
  { id: "1-794", korean: "쓰다", english: "To be bitter", pronunciation: "sseuda", partOfSpeech: "adjective", example: "이 약이 써요.", exampleTranslation: "This medicine is bitter.", category: "Basic Adjectives" },
  { id: "1-795", korean: "같다", english: "To be the same", pronunciation: "gatda", partOfSpeech: "adjective", example: "우리는 나이가 같아요.", exampleTranslation: "We are the same age.", category: "Basic Adjectives" },
  { id: "1-796", korean: "다르다", english: "To be different", pronunciation: "dareuda", partOfSpeech: "adjective", example: "색이 달라요.", exampleTranslation: "The colors are different.", category: "Basic Adjectives" },
  { id: "1-797", korean: "바쁘다", english: "To be busy", pronunciation: "bappeuda", partOfSpeech: "adjective", example: "요즘 바빠요.", exampleTranslation: "I'm busy these days.", category: "Basic Adjectives" },
  { id: "1-798", korean: "한가하다", english: "To be free / Not busy", pronunciation: "hangahada", partOfSpeech: "adjective", example: "오늘 한가해요.", exampleTranslation: "I'm free today.", category: "Basic Adjectives" },
  { id: "1-799", korean: "유명하다", english: "To be famous", pronunciation: "yumyeonghada", partOfSpeech: "adjective", example: "이 식당은 유명해요.", exampleTranslation: "This restaurant is famous.", category: "Basic Adjectives" },
  { id: "1-800", korean: "특별하다", english: "To be special", pronunciation: "teukbyeolhada", partOfSpeech: "adjective", example: "오늘은 특별한 날이에요.", exampleTranslation: "Today is a special day.", category: "Basic Adjectives" },
];

export default words;
