export interface GrammarPoint {
  id: string;
  level: number;
  title: string;
  titleRomanized: string;
  meaning: string;
  explanation: string;
  structure: string;
  examples: {
    korean: string;
    english: string;
    highlight: string;
  }[];
  tips: string;
  category: string;
}

export const GRAMMAR_DATA: GrammarPoint[] = [
  // ===== LEVEL 1 (15 points) - Basic =====
  {
    id: 'g1-01',
    level: 1,
    title: '은/는',
    titleRomanized: 'eun/neun',
    meaning: 'Topic marker',
    explanation: 'Marks the topic of a sentence — what you are talking about. Use 은 after a consonant and 는 after a vowel.',
    structure: 'Noun + 은 (after consonant) / 는 (after vowel)',
    examples: [
      { korean: '저는 학생이에요.', english: 'I am a student.', highlight: '는' },
      { korean: '한국은 아름다워요.', english: 'Korea is beautiful.', highlight: '은' },
      { korean: '오늘은 날씨가 좋아요.', english: 'Today, the weather is nice.', highlight: '은' },
    ],
    tips: 'Unlike 이/가 (subject marker), 은/는 is used for contrast or to introduce a known topic. "As for X..."',
    category: 'Particles',
  },
  {
    id: 'g1-02',
    level: 1,
    title: '이/가',
    titleRomanized: 'i/ga',
    meaning: 'Subject marker',
    explanation: 'Marks the grammatical subject of a sentence — who or what performs the action. Use 이 after a consonant and 가 after a vowel.',
    structure: 'Noun + 이 (after consonant) / 가 (after vowel)',
    examples: [
      { korean: '비가 와요.', english: 'It is raining.', highlight: '가' },
      { korean: '고양이가 귀여워요.', english: 'The cat is cute.', highlight: '가' },
      { korean: '친구가 왔어요.', english: 'A friend came.', highlight: '가' },
    ],
    tips: 'Use 이/가 when introducing new information or emphasizing the subject. It answers "who?" or "what?".',
    category: 'Particles',
  },
  {
    id: 'g1-03',
    level: 1,
    title: '을/를',
    titleRomanized: 'eul/reul',
    meaning: 'Object marker',
    explanation: 'Marks the direct object of a verb — the thing being acted upon. Use 을 after a consonant and 를 after a vowel.',
    structure: 'Noun + 을 (after consonant) / 를 (after vowel)',
    examples: [
      { korean: '밥을 먹어요.', english: 'I eat rice.', highlight: '을' },
      { korean: '커피를 마셔요.', english: 'I drink coffee.', highlight: '를' },
      { korean: '한국어를 공부해요.', english: 'I study Korean.', highlight: '를' },
    ],
    tips: 'In casual speech, 을/를 is often dropped, but using it makes your sentences clearer and more correct.',
    category: 'Particles',
  },
  {
    id: 'g1-04',
    level: 1,
    title: '에',
    titleRomanized: 'e',
    meaning: 'Location / time particle',
    explanation: 'Indicates a location where something exists or a point in time. Used with verbs of existence (있다/없다) and for time expressions.',
    structure: 'Noun (place/time) + 에',
    examples: [
      { korean: '학교에 가요.', english: 'I go to school.', highlight: '에' },
      { korean: '서울에 살아요.', english: 'I live in Seoul.', highlight: '에' },
      { korean: '세 시에 만나요.', english: "Let's meet at three o'clock.", highlight: '에' },
    ],
    tips: 'Use 에 for destinations and static locations. For the location of an action (where something happens), use 에서 instead.',
    category: 'Particles',
  },
  {
    id: 'g1-05',
    level: 1,
    title: '에서',
    titleRomanized: 'eseo',
    meaning: 'Location of action',
    explanation: 'Marks the place where an action takes place. Unlike 에, which marks a static location or destination, 에서 is used when something is actively happening at that place.',
    structure: 'Noun (place) + 에서',
    examples: [
      { korean: '카페에서 공부해요.', english: 'I study at the café.', highlight: '에서' },
      { korean: '집에서 요리해요.', english: 'I cook at home.', highlight: '에서' },
      { korean: '회사에서 일해요.', english: 'I work at the company.', highlight: '에서' },
    ],
    tips: 'Remember: 에 = destination or existence, 에서 = where an action happens. "I am at school" = 학교에 있어요, "I study at school" = 학교에서 공부해요.',
    category: 'Particles',
  },
  {
    id: 'g1-06',
    level: 1,
    title: '의',
    titleRomanized: 'ui (spoken as "e")',
    meaning: 'Possessive particle',
    explanation: 'Shows possession or belonging, similar to "\'s" or "of" in English. In spoken Korean, 의 is often pronounced as "에".',
    structure: 'Noun + 의 + Noun',
    examples: [
      { korean: '저의 이름은 민수예요.', english: 'My name is Minsu.', highlight: '의' },
      { korean: '한국의 음식은 맛있어요.', english: 'Korean food is delicious.', highlight: '의' },
      { korean: '친구의 집에 갔어요.', english: "I went to my friend's house.", highlight: '의' },
    ],
    tips: 'In casual speech, 의 is often omitted, especially with pronouns. 나의 → 내, 저의 → 제, 너의 → 네.',
    category: 'Particles',
  },
  {
    id: 'g1-07',
    level: 1,
    title: '-아/어요',
    titleRomanized: '-a/eoyo',
    meaning: 'Polite present tense ending',
    explanation: 'The standard polite speech level used in everyday conversation. Add -아요 if the last vowel of the stem is ㅏ or ㅗ, and -어요 for all other vowels. 하다 becomes 해요.',
    structure: 'Verb/Adjective stem + 아요/어요/해요',
    examples: [
      { korean: '저는 한국어를 배워요.', english: 'I learn Korean.', highlight: '배워요' },
      { korean: '날씨가 좋아요.', english: 'The weather is good.', highlight: '좋아요' },
      { korean: '매일 운동해요.', english: 'I exercise every day.', highlight: '운동해요' },
    ],
    tips: 'This is the most common speech level. Use it with people you are not very close with, elders, or strangers.',
    category: 'Verb Endings',
  },
  {
    id: 'g1-08',
    level: 1,
    title: '-았/었어요',
    titleRomanized: '-at/eosseoyo',
    meaning: 'Polite past tense ending',
    explanation: 'Expresses completed actions or past states in polite speech. The vowel harmony rule is the same as present tense: -았어요 for ㅏ/ㅗ stems, -었어요 for others, 하다 becomes 했어요.',
    structure: 'Verb/Adjective stem + 았어요/었어요/했어요',
    examples: [
      { korean: '어제 친구를 만났어요.', english: 'I met a friend yesterday.', highlight: '만났어요' },
      { korean: '점심을 먹었어요.', english: 'I ate lunch.', highlight: '먹었어요' },
      { korean: '숙제를 했어요.', english: 'I did my homework.', highlight: '했어요' },
    ],
    tips: 'Past tense is straightforward — just add 았/었 before 어요. Watch for irregular verbs like 듣다 → 들었어요.',
    category: 'Verb Endings',
  },
  {
    id: 'g1-09',
    level: 1,
    title: '-(으)ㄹ 거예요',
    titleRomanized: '-(eu)l geoyeyo',
    meaning: 'Future tense (will / going to)',
    explanation: 'Expresses future plans or intentions, similar to "will" or "going to" in English. Use -ㄹ 거예요 after vowels and -을 거예요 after consonants.',
    structure: 'Verb stem + (으)ㄹ 거예요',
    examples: [
      { korean: '내일 서울에 갈 거예요.', english: 'I will go to Seoul tomorrow.', highlight: '갈 거예요' },
      { korean: '주말에 쉴 거예요.', english: 'I will rest on the weekend.', highlight: '쉴 거예요' },
      { korean: '저녁에 영화를 볼 거예요.', english: 'I will watch a movie in the evening.', highlight: '볼 거예요' },
    ],
    tips: 'This is the most common way to talk about future plans. For promises, use -(으)ㄹ게요 instead (Level 2).',
    category: 'Verb Endings',
  },
  {
    id: 'g1-10',
    level: 1,
    title: '-고 싶다',
    titleRomanized: '-go sipda',
    meaning: 'Want to do',
    explanation: 'Expresses a desire or wish to do something. Attach -고 싶다 directly to the verb stem. In polite form: -고 싶어요.',
    structure: 'Verb stem + 고 싶다/싶어요',
    examples: [
      { korean: '한국에 가고 싶어요.', english: 'I want to go to Korea.', highlight: '가고 싶어요' },
      { korean: '피자를 먹고 싶어요.', english: 'I want to eat pizza.', highlight: '먹고 싶어요' },
      { korean: '한국어를 잘하고 싶어요.', english: 'I want to be good at Korean.', highlight: '잘하고 싶어요' },
    ],
    tips: 'Use -고 싶어 하다 when talking about someone else\'s desires (third person). 그는 가고 싶어 해요.',
    category: 'Verb Endings',
  },
  {
    id: 'g1-11',
    level: 1,
    title: '-지 않다',
    titleRomanized: '-ji anta',
    meaning: 'Negation (do not / is not)',
    explanation: 'Negates a verb or adjective by attaching -지 않다 to the stem. This is a longer, slightly more formal way of negating compared to using 안.',
    structure: 'Verb/Adjective stem + 지 않다/않아요',
    examples: [
      { korean: '오늘은 바쁘지 않아요.', english: 'I am not busy today.', highlight: '바쁘지 않아요' },
      { korean: '고기를 먹지 않아요.', english: "I don't eat meat.", highlight: '먹지 않아요' },
      { korean: '그 영화는 재미있지 않았어요.', english: 'That movie was not interesting.', highlight: '재미있지 않았어요' },
    ],
    tips: 'You can negate any verb or adjective with -지 않다. It sounds slightly more careful or formal than 안.',
    category: 'Negation',
  },
  {
    id: 'g1-12',
    level: 1,
    title: '안',
    titleRomanized: 'an',
    meaning: 'Negation (short form)',
    explanation: 'A short negation word placed directly before the verb or adjective. It is simpler and more commonly used in casual speech than -지 않다.',
    structure: '안 + Verb/Adjective',
    examples: [
      { korean: '안 먹어요.', english: "I don't eat (it).", highlight: '안' },
      { korean: '오늘 안 추워요.', english: "It's not cold today.", highlight: '안' },
      { korean: '안 좋아요.', english: "It's not good.", highlight: '안' },
    ],
    tips: 'For 하다 verbs, put 안 before 하다: 공부 안 해요 (not 안 공부해요). Cannot be used with 있다/없다; use -지 않다 instead.',
    category: 'Negation',
  },
  {
    id: 'g1-13',
    level: 1,
    title: '-고',
    titleRomanized: '-go',
    meaning: 'And / and then',
    explanation: 'Connects two actions or states, meaning "and" or "and then." It simply joins clauses without implying cause or sequence unless context makes it clear.',
    structure: 'Verb/Adjective stem + 고',
    examples: [
      { korean: '아침을 먹고 학교에 가요.', english: 'I eat breakfast and go to school.', highlight: '먹고' },
      { korean: '이 방은 크고 밝아요.', english: 'This room is big and bright.', highlight: '크고' },
      { korean: '음악을 듣고 공부해요.', english: 'I listen to music and study.', highlight: '듣고' },
    ],
    tips: 'Unlike -아/어서, -고 does not imply a causal relationship. The two clauses can have different subjects.',
    category: 'Connectors',
  },
  {
    id: 'g1-14',
    level: 1,
    title: '-(으)ㄹ 수 있다/없다',
    titleRomanized: '-(eu)l su itda/eopda',
    meaning: 'Can / cannot',
    explanation: 'Expresses ability or possibility. 있다 means "can" and 없다 means "cannot." Attach -(으)ㄹ 수 to the verb stem.',
    structure: 'Verb stem + (으)ㄹ 수 있다/없다',
    examples: [
      { korean: '한국어를 말할 수 있어요.', english: 'I can speak Korean.', highlight: '말할 수 있어요' },
      { korean: '오늘은 갈 수 없어요.', english: "I can't go today.", highlight: '갈 수 없어요' },
      { korean: '여기서 수영할 수 있어요.', english: 'You can swim here.', highlight: '수영할 수 있어요' },
    ],
    tips: 'This is different from "know how to" — it indicates whether something is possible in a given situation.',
    category: 'Verb Endings',
  },
  {
    id: 'g1-15',
    level: 1,
    title: '-아/어서',
    titleRomanized: '-a/eoseo',
    meaning: 'Because / and then (sequential)',
    explanation: 'Connects two clauses with a causal or sequential relationship. It can mean "because" or indicate that one action follows another naturally.',
    structure: 'Verb/Adjective stem + 아서/어서/해서',
    examples: [
      { korean: '배가 고파서 밥을 먹었어요.', english: 'I was hungry, so I ate.', highlight: '고파서' },
      { korean: '만나서 반갑습니다.', english: 'Nice to meet you (lit. meeting you, I am glad).', highlight: '만나서' },
      { korean: '비가 와서 집에 있었어요.', english: 'It rained, so I stayed home.', highlight: '와서' },
    ],
    tips: 'You cannot use past tense (-았/었-) in the first clause with -아/어서. The tense is determined by the final verb.',
    category: 'Connectors',
  },

  // ===== LEVEL 2 (18 points) - Elementary =====
  {
    id: 'g2-01',
    level: 2,
    title: '-(으)ㄴ/는',
    titleRomanized: '-(eu)n/neun',
    meaning: 'Adjective/verb modifier (present/past)',
    explanation: 'Turns a verb or adjective into a modifier for a noun. For verbs, -는 is present tense and -(으)ㄴ is past. For adjectives, -(으)ㄴ is used for the present state.',
    structure: 'Verb stem + 는 (present) / (으)ㄴ (past); Adjective stem + (으)ㄴ',
    examples: [
      { korean: '제가 읽는 책이에요.', english: "It's a book I'm reading.", highlight: '읽는' },
      { korean: '어제 본 영화가 재미있었어요.', english: 'The movie I saw yesterday was fun.', highlight: '본' },
      { korean: '예쁜 꽃이에요.', english: "It's a pretty flower.", highlight: '예쁜' },
    ],
    tips: 'Adjective present: -(으)ㄴ (큰, 작은). Verb present: -는 (먹는, 가는). Verb past: -(으)ㄴ (먹은, 간).',
    category: 'Modifiers',
  },
  {
    id: 'g2-02',
    level: 2,
    title: '-(으)ㄹ',
    titleRomanized: '-(eu)l',
    meaning: 'Future modifier',
    explanation: 'Modifies a noun with a future or hypothetical meaning, turning a verb into "something that will be done" or "something to do."',
    structure: 'Verb stem + (으)ㄹ + Noun',
    examples: [
      { korean: '마실 물이 있어요?', english: 'Is there water to drink?', highlight: '마실' },
      { korean: '읽을 책을 가져왔어요.', english: 'I brought a book to read.', highlight: '읽을' },
      { korean: '할 일이 많아요.', english: 'I have a lot of things to do.', highlight: '할' },
    ],
    tips: 'This modifier implies something that has not happened yet or is planned. Compare: 먹는 사람 (person eating) vs 먹을 사람 (person who will eat).',
    category: 'Modifiers',
  },
  {
    id: 'g2-03',
    level: 2,
    title: '-지만',
    titleRomanized: '-jiman',
    meaning: 'But / however',
    explanation: 'Connects two contrasting clauses, similar to "but" or "however." It shows that the second clause is unexpected given the first.',
    structure: 'Verb/Adjective stem + 지만',
    examples: [
      { korean: '비싸지만 맛있어요.', english: "It's expensive, but delicious.", highlight: '비싸지만' },
      { korean: '피곤하지만 공부해야 해요.', english: "I'm tired, but I have to study.", highlight: '피곤하지만' },
      { korean: '한국어는 어렵지만 재미있어요.', english: 'Korean is hard, but fun.', highlight: '어렵지만' },
    ],
    tips: 'Unlike -(으)ㄴ데, -지만 is a simple contrast and does not carry background/contextual nuance.',
    category: 'Connectors',
  },
  {
    id: 'g2-04',
    level: 2,
    title: '-(으)면',
    titleRomanized: '-(eu)myeon',
    meaning: 'If / when',
    explanation: 'Expresses a conditional ("if") or a temporal condition ("when"). The second clause states what happens under that condition.',
    structure: 'Verb/Adjective stem + (으)면',
    examples: [
      { korean: '시간이 있으면 같이 가요.', english: "If you have time, let's go together.", highlight: '있으면' },
      { korean: '비가 오면 집에 있을 거예요.', english: "If it rains, I'll stay home.", highlight: '오면' },
      { korean: '봄이 오면 꽃이 피어요.', english: 'When spring comes, flowers bloom.', highlight: '오면' },
    ],
    tips: 'Cannot be used for past events that already happened. For past reasons, use -(으)니까 or -아/어서.',
    category: 'Connectors',
  },
  {
    id: 'g2-05',
    level: 2,
    title: '-(으)니까',
    titleRomanized: '-(eu)nikka',
    meaning: 'Because / since',
    explanation: 'Gives a reason or cause for the following clause. Unlike -아/어서, it can be used with imperative and suggestive sentences, and can take past tense in the first clause.',
    structure: 'Verb/Adjective stem + (으)니까',
    examples: [
      { korean: '배가 고프니까 밥 먹자.', english: "I'm hungry, so let's eat.", highlight: '고프니까' },
      { korean: '늦었으니까 택시 타요.', english: "We're late, so let's take a taxi.", highlight: '늦었으니까' },
      { korean: '비가 오니까 우산을 가져가세요.', english: "It's raining, so take an umbrella.", highlight: '오니까' },
    ],
    tips: 'Use -(으)니까 when giving a reason followed by a command or suggestion. -아/어서 cannot be used before commands.',
    category: 'Connectors',
  },
  {
    id: 'g2-06',
    level: 2,
    title: '-아/어 보다',
    titleRomanized: '-a/eo boda',
    meaning: 'Try doing',
    explanation: 'Expresses trying or experiencing an action. Used to suggest trying something or to talk about past experiences.',
    structure: 'Verb stem + 아/어 보다',
    examples: [
      { korean: '김치를 먹어 봤어요.', english: 'I have tried eating kimchi.', highlight: '먹어 봤어요' },
      { korean: '이 옷을 입어 보세요.', english: 'Try wearing these clothes.', highlight: '입어 보세요' },
      { korean: '한번 해 봐요.', english: 'Try it once.', highlight: '해 봐요' },
    ],
    tips: 'Past form (-아/어 봤다) means "have tried/experienced." Present form (-아/어 보다) means "try doing."',
    category: 'Verb Endings',
  },
  {
    id: 'g2-07',
    level: 2,
    title: '-고 있다',
    titleRomanized: '-go itda',
    meaning: 'Progressive (be doing)',
    explanation: 'Describes an action that is currently in progress, similar to the English "-ing" form. Shows an ongoing state.',
    structure: 'Verb stem + 고 있다/있어요',
    examples: [
      { korean: '지금 밥을 먹고 있어요.', english: 'I am eating right now.', highlight: '먹고 있어요' },
      { korean: '친구를 기다리고 있어요.', english: 'I am waiting for a friend.', highlight: '기다리고 있어요' },
      { korean: '음악을 듣고 있었어요.', english: 'I was listening to music.', highlight: '듣고 있었어요' },
    ],
    tips: 'For wearing clothes, use -고 있다 for the ongoing state: 모자를 쓰고 있어요 (wearing a hat).',
    category: 'Verb Endings',
  },
  {
    id: 'g2-08',
    level: 2,
    title: '-아/어야 하다',
    titleRomanized: '-a/eoya hada',
    meaning: 'Must / have to',
    explanation: 'Expresses obligation or necessity — something that must be done. The polite form is -아/어야 해요.',
    structure: 'Verb stem + 아/어야 하다/해요',
    examples: [
      { korean: '숙제를 해야 해요.', english: 'I have to do my homework.', highlight: '해야 해요' },
      { korean: '내일 일찍 일어나야 해요.', english: 'I have to wake up early tomorrow.', highlight: '일어나야 해요' },
      { korean: '약을 먹어야 해요.', english: 'I have to take medicine.', highlight: '먹어야 해요' },
    ],
    tips: 'To say "don\'t have to," use -지 않아도 되다: 가지 않아도 돼요 (You don\'t have to go).',
    category: 'Verb Endings',
  },
  {
    id: 'g2-09',
    level: 2,
    title: '-(으)ㄹ게요',
    titleRomanized: '-(eu)lgeyo',
    meaning: 'I will (promise/intention)',
    explanation: 'Expresses the speaker\'s promise or voluntary intention to do something. Only used in first person — it is a commitment to the listener.',
    structure: 'Verb stem + (으)ㄹ게요',
    examples: [
      { korean: '제가 할게요.', english: "I'll do it.", highlight: '할게요' },
      { korean: '내일 전화할게요.', english: "I'll call you tomorrow.", highlight: '전화할게요' },
      { korean: '조심할게요.', english: "I'll be careful.", highlight: '조심할게요' },
    ],
    tips: 'This is only for first person (I/we). It implies the decision is influenced by the listener. For general future plans, use -(으)ㄹ 거예요.',
    category: 'Verb Endings',
  },
  {
    id: 'g2-10',
    level: 2,
    title: '-(으)ㄹ까요?',
    titleRomanized: '-(eu)lkkayo',
    meaning: 'Shall we? / Do you think?',
    explanation: 'Used to make suggestions ("Shall we...?") or ask for opinions ("Do you think...?"). It invites the listener\'s input.',
    structure: 'Verb stem + (으)ㄹ까요?',
    examples: [
      { korean: '같이 갈까요?', english: 'Shall we go together?', highlight: '갈까요' },
      { korean: '뭐 먹을까요?', english: 'What shall we eat?', highlight: '먹을까요' },
      { korean: '내일 비가 올까요?', english: 'Do you think it will rain tomorrow?', highlight: '올까요' },
    ],
    tips: 'When suggesting an activity, -(으)ㄹ까요 is softer than -(으)ㅂ시다. Great for polite invitations.',
    category: 'Speech Levels',
  },
  {
    id: 'g2-11',
    level: 2,
    title: '-(으)ㅂ시다',
    titleRomanized: '-(eu)psida',
    meaning: "Let's (formal suggestion)",
    explanation: 'A formal way to suggest doing something together. More direct than -(으)ㄹ까요 and used in slightly more formal settings.',
    structure: 'Verb stem + (으)ㅂ시다',
    examples: [
      { korean: '같이 갑시다.', english: "Let's go together.", highlight: '갑시다' },
      { korean: '시작합시다!', english: "Let's begin!", highlight: '시작합시다' },
      { korean: '잠시 쉽시다.', english: "Let's take a short break.", highlight: '쉽시다' },
    ],
    tips: 'This is more formal and direct than -(으)ㄹ까요. In casual speech, -자 is used instead: 가자! (Let\'s go!).',
    category: 'Speech Levels',
  },
  {
    id: 'g2-12',
    level: 2,
    title: '-기 전에',
    titleRomanized: '-gi jeone',
    meaning: 'Before doing',
    explanation: 'Indicates that one action happens before another. Attach -기 전에 to the verb stem of the action that has not happened yet.',
    structure: 'Verb stem + 기 전에',
    examples: [
      { korean: '자기 전에 이를 닦아요.', english: 'I brush my teeth before sleeping.', highlight: '자기 전에' },
      { korean: '밥 먹기 전에 손을 씻어요.', english: 'I wash my hands before eating.', highlight: '먹기 전에' },
      { korean: '출발하기 전에 확인하세요.', english: 'Please check before departing.', highlight: '출발하기 전에' },
    ],
    tips: 'The verb before -기 전에 is always in the base form (no tense markers). The tense is in the main clause.',
    category: 'Time Expressions',
  },
  {
    id: 'g2-13',
    level: 2,
    title: '-(으)ㄴ 후에',
    titleRomanized: '-(eu)n hue',
    meaning: 'After doing',
    explanation: 'Expresses that one action follows another in time. The first action is completed before the second begins.',
    structure: 'Verb stem + (으)ㄴ 후에',
    examples: [
      { korean: '수업이 끝난 후에 만나요.', english: "Let's meet after class ends.", highlight: '끝난 후에' },
      { korean: '밥을 먹은 후에 커피를 마셔요.', english: 'I drink coffee after eating.', highlight: '먹은 후에' },
      { korean: '졸업한 후에 뭐 할 거예요?', english: 'What will you do after graduating?', highlight: '졸업한 후에' },
    ],
    tips: 'You can also use -고 나서 with a similar meaning: 밥을 먹고 나서 커피를 마셔요.',
    category: 'Time Expressions',
  },
  {
    id: 'g2-14',
    level: 2,
    title: '-는 동안',
    titleRomanized: '-neun dongan',
    meaning: 'While / during',
    explanation: 'Indicates that two actions happen at the same time. The first clause describes the duration during which the second action occurs.',
    structure: 'Verb stem + 는 동안',
    examples: [
      { korean: '기다리는 동안 책을 읽었어요.', english: 'I read a book while waiting.', highlight: '기다리는 동안' },
      { korean: '엄마가 요리하는 동안 저는 청소했어요.', english: 'While mom cooked, I cleaned.', highlight: '요리하는 동안' },
      { korean: '방학 동안 여행할 거예요.', english: 'I will travel during vacation.', highlight: '동안' },
    ],
    tips: 'With nouns, just use 동안 without -는: 수업 동안 (during class), 방학 동안 (during vacation).',
    category: 'Time Expressions',
  },
  {
    id: 'g2-15',
    level: 2,
    title: '-(으)러 가다/오다',
    titleRomanized: '-(eu)reo gada/oda',
    meaning: 'Go/come to do something',
    explanation: 'Expresses the purpose of going or coming somewhere. It can only be used with movement verbs like 가다 (go) and 오다 (come).',
    structure: 'Verb stem + (으)러 가다/오다',
    examples: [
      { korean: '밥 먹으러 가요.', english: "Let's go eat.", highlight: '먹으러' },
      { korean: '친구를 만나러 왔어요.', english: 'I came to meet a friend.', highlight: '만나러' },
      { korean: '한국어를 배우러 한국에 갔어요.', english: 'I went to Korea to learn Korean.', highlight: '배우러' },
    ],
    tips: 'This can only be used with 가다 and 오다. For general purpose ("in order to"), use -(으)려고.',
    category: 'Connectors',
  },
  {
    id: 'g2-16',
    level: 2,
    title: '-기로 하다',
    titleRomanized: '-giro hada',
    meaning: 'Decide to do',
    explanation: 'Expresses a decision or agreement to do something. Often used when a plan has been decided, either by oneself or with others.',
    structure: 'Verb stem + 기로 하다/했다',
    examples: [
      { korean: '내일 만나기로 했어요.', english: 'We decided to meet tomorrow.', highlight: '만나기로 했어요' },
      { korean: '다이어트를 하기로 했어요.', english: 'I decided to go on a diet.', highlight: '하기로 했어요' },
      { korean: '한국어를 열심히 공부하기로 했어요.', english: 'I decided to study Korean hard.', highlight: '공부하기로 했어요' },
    ],
    tips: 'The past form (-기로 했다) is most common because decisions are usually already made when reported.',
    category: 'Verb Endings',
  },
  {
    id: 'g2-17',
    level: 2,
    title: '-게 되다',
    titleRomanized: '-ge doeda',
    meaning: 'Come to / end up doing',
    explanation: 'Describes a change of state or situation that happened naturally or unintentionally. It implies the result was not entirely by choice.',
    structure: 'Verb stem + 게 되다/됐다',
    examples: [
      { korean: '한국에서 살게 됐어요.', english: 'I ended up living in Korea.', highlight: '살게 됐어요' },
      { korean: '그 사람을 좋아하게 됐어요.', english: 'I came to like that person.', highlight: '좋아하게 됐어요' },
      { korean: '한국어를 가르치게 됐어요.', english: 'I ended up teaching Korean.', highlight: '가르치게 됐어요' },
    ],
    tips: 'This is different from -기로 하다 (active decision). -게 되다 implies circumstances led to the result.',
    category: 'Verb Endings',
  },
  // ===== LEVEL 3 (20 points) - Intermediate =====
  {
    id: 'g3-01',
    level: 3,
    title: '-다고 하다',
    titleRomanized: '-dago hada',
    meaning: 'Indirect quotation (statement)',
    explanation: 'Reports what someone said as a statement. It is the most common indirect speech form. The tense is maintained from the original statement.',
    structure: 'Verb/Adjective stem + (ㄴ/는)다고 하다; Noun + (이)라고 하다',
    examples: [
      { korean: '친구가 내일 온다고 했어요.', english: 'My friend said they are coming tomorrow.', highlight: '온다고 했어요' },
      { korean: '선생님이 시험이 어렵다고 했어요.', english: 'The teacher said the test is hard.', highlight: '어렵다고 했어요' },
      { korean: '그 사람이 한국 사람이라고 했어요.', english: 'That person said they are Korean.', highlight: '한국 사람이라고 했어요' },
    ],
    tips: 'In casual speech, -다고 하다 is often shortened to -대요: 온다고 했어요 → 온대요.',
    category: 'Indirect Speech',
  },
  {
    id: 'g3-02',
    level: 3,
    title: '-냐고 하다',
    titleRomanized: '-nyago hada',
    meaning: 'Indirect quotation (question)',
    explanation: 'Reports what someone asked. The question is embedded within a statement. Used when relaying someone else\'s question.',
    structure: 'Verb/Adjective stem + (으)냐고 하다; Noun + (이)냐고 하다',
    examples: [
      { korean: '엄마가 밥 먹었냐고 했어요.', english: 'Mom asked if I ate.', highlight: '먹었냐고 했어요' },
      { korean: '친구가 어디 가냐고 물었어요.', english: 'My friend asked where I was going.', highlight: '가냐고 물었어요' },
      { korean: '선생님이 숙제 했냐고 했어요.', english: 'The teacher asked if I did the homework.', highlight: '했냐고 했어요' },
    ],
    tips: 'In casual speech, shortened to -냬요: 밥 먹었냐고 했어요 → 밥 먹었냬요.',
    category: 'Indirect Speech',
  },
  {
    id: 'g3-03',
    level: 3,
    title: '-자고 하다',
    titleRomanized: '-jago hada',
    meaning: 'Indirect quotation (suggestion)',
    explanation: 'Reports someone\'s suggestion ("Let\'s..."). Used to relay that someone proposed doing something together.',
    structure: 'Verb stem + 자고 하다',
    examples: [
      { korean: '친구가 같이 영화 보자고 했어요.', english: 'My friend suggested watching a movie together.', highlight: '보자고 했어요' },
      { korean: '언니가 쇼핑 가자고 했어요.', english: 'My sister suggested going shopping.', highlight: '가자고 했어요' },
      { korean: '반 친구들이 파티 하자고 했어요.', english: 'My classmates suggested having a party.', highlight: '하자고 했어요' },
    ],
    tips: 'Shortened form: -재요. 같이 가자고 했어요 → 같이 가재요.',
    category: 'Indirect Speech',
  },
  {
    id: 'g3-04',
    level: 3,
    title: '-(으)라고 하다',
    titleRomanized: '-(eu)rago hada',
    meaning: 'Indirect quotation (command)',
    explanation: 'Reports someone\'s command or instruction. Used when telling someone what another person told them to do.',
    structure: 'Verb stem + (으)라고 하다',
    examples: [
      { korean: '의사가 쉬라고 했어요.', english: 'The doctor told me to rest.', highlight: '쉬라고 했어요' },
      { korean: '엄마가 빨리 오라고 했어요.', english: 'Mom told me to come quickly.', highlight: '오라고 했어요' },
      { korean: '선생님이 조용히 하라고 했어요.', english: 'The teacher told us to be quiet.', highlight: '하라고 했어요' },
    ],
    tips: 'For negative commands: -지 말라고 하다. 엄마가 늦지 말라고 했어요 (Mom told me not to be late).',
    category: 'Indirect Speech',
  },
  {
    id: 'g3-05',
    level: 3,
    title: '-(으)면서',
    titleRomanized: '-(eu)myeonseo',
    meaning: 'While doing (simultaneous)',
    explanation: 'Indicates two actions happening simultaneously by the same subject. Both actions occur at the same time.',
    structure: 'Verb stem + (으)면서',
    examples: [
      { korean: '음악을 들으면서 공부해요.', english: 'I study while listening to music.', highlight: '들으면서' },
      { korean: '웃으면서 이야기했어요.', english: 'They talked while laughing.', highlight: '웃으면서' },
      { korean: '밥을 먹으면서 TV를 봐요.', english: 'I watch TV while eating.', highlight: '먹으면서' },
    ],
    tips: 'The subject must be the same in both clauses. For different subjects doing things simultaneously, use -는 동안.',
    category: 'Connectors',
  },
  {
    id: 'g3-06',
    level: 3,
    title: '-다가',
    titleRomanized: '-daga',
    meaning: 'While doing / then (interruption)',
    explanation: 'Indicates that one action was interrupted by another, or a change from one action to another. It shows a shift in activity.',
    structure: 'Verb stem + 다가',
    examples: [
      { korean: '공부하다가 잠들었어요.', english: 'I fell asleep while studying.', highlight: '공부하다가' },
      { korean: '걷다가 넘어졌어요.', english: 'I fell while walking.', highlight: '걷다가' },
      { korean: '버스를 타다가 지하철로 갈아탔어요.', english: 'I was on the bus and then transferred to the subway.', highlight: '타다가' },
    ],
    tips: 'Unlike -(으)면서, -다가 implies the first action stops or is interrupted when the second begins.',
    category: 'Connectors',
  },
  {
    id: 'g3-07',
    level: 3,
    title: '-(으)ㄹ 뿐만 아니라',
    titleRomanized: '-(eu)l ppunman anira',
    meaning: 'Not only... but also',
    explanation: 'Expresses that something is true and there is an additional point. Emphasizes that there is more than what was initially stated.',
    structure: 'Verb/Adjective stem + (으)ㄹ 뿐만 아니라',
    examples: [
      { korean: '그는 노래를 잘할 뿐만 아니라 춤도 잘 춰요.', english: 'He not only sings well but also dances well.', highlight: '잘할 뿐만 아니라' },
      { korean: '맛있을 뿐만 아니라 건강에도 좋아요.', english: "It's not only delicious but also good for health.", highlight: '맛있을 뿐만 아니라' },
      { korean: '한국어뿐만 아니라 일본어도 해요.', english: 'I speak not only Korean but also Japanese.', highlight: '한국어뿐만 아니라' },
    ],
    tips: 'With nouns, use 뿐만 아니라 directly: 커피뿐만 아니라 차도 좋아해요.',
    category: 'Connectors',
  },
  {
    id: 'g3-08',
    level: 3,
    title: '-는 바람에',
    titleRomanized: '-neun barame',
    meaning: 'Because of (negative cause)',
    explanation: 'Gives an unexpected or unwanted reason for a negative result. The cause is usually something sudden or unintended.',
    structure: 'Verb stem + 는 바람에',
    examples: [
      { korean: '비가 오는 바람에 소풍을 못 갔어요.', english: "Because it rained, we couldn't go on the picnic.", highlight: '오는 바람에' },
      { korean: '늦잠을 자는 바람에 지각했어요.', english: 'Because I overslept, I was late.', highlight: '자는 바람에' },
      { korean: '길이 막히는 바람에 늦었어요.', english: 'Because of traffic, I was late.', highlight: '막히는 바람에' },
    ],
    tips: 'Only used for negative or undesirable outcomes. For neutral/positive reasons, use -기 때문에 or -아/어서.',
    category: 'Connectors',
  },
  {
    id: 'g3-09',
    level: 3,
    title: '-는 데',
    titleRomanized: '-neun de',
    meaning: 'But / for context / regarding',
    explanation: 'Provides background information or sets up context for the main clause. It can also be used to softly contrast two situations.',
    structure: 'Verb stem + 는데; Adjective stem + (으)ㄴ데; Noun + 인데',
    examples: [
      { korean: '시간이 없는데 어떻게 해요?', english: "I don't have time — what should I do?", highlight: '없는데' },
      { korean: '한국어는 재미있는데 어려워요.', english: 'Korean is interesting, but it is hard.', highlight: '재미있는데' },
      { korean: '내일 시험인데 공부 안 했어요.', english: "I have an exam tomorrow, but I haven't studied.", highlight: '시험인데' },
    ],
    tips: 'This is one of the most versatile connectors. It sets up context, gives reasons, or provides soft contrast.',
    category: 'Connectors',
  },
  {
    id: 'g3-10',
    level: 3,
    title: '-기는 하지만',
    titleRomanized: '-gineun hajiman',
    meaning: 'Although / it is true that... but',
    explanation: 'Acknowledges that something is true while introducing a contrasting point. It concedes the first clause before presenting the second.',
    structure: 'Verb/Adjective stem + 기는 하지만',
    examples: [
      { korean: '맛있기는 하지만 비싸요.', english: "It is delicious, but it's expensive.", highlight: '맛있기는 하지만' },
      { korean: '알기는 하지만 설명하기 어려워요.', english: 'I do know it, but it is hard to explain.', highlight: '알기는 하지만' },
      { korean: '좋기는 하지만 너무 멀어요.', english: "It's nice, but it's too far.", highlight: '좋기는 하지만' },
    ],
    tips: 'Often shortened to -기는 한데: 맛있기는 한데 비싸요. Sounds natural in conversation.',
    category: 'Connectors',
  },
  {
    id: 'g3-11',
    level: 3,
    title: '-(으)ㄹ 텐데',
    titleRomanized: '-(eu)l tende',
    meaning: 'Probably / I suppose',
    explanation: 'Expresses the speaker\'s assumption or expectation about a situation, often followed by a suggestion or concern based on that assumption.',
    structure: 'Verb/Adjective stem + (으)ㄹ 텐데',
    examples: [
      { korean: '피곤할 텐데 좀 쉬세요.', english: "You must be tired, so please rest.", highlight: '피곤할 텐데' },
      { korean: '배고플 텐데 밥 먹을까요?', english: "You're probably hungry — shall we eat?", highlight: '배고플 텐데' },
      { korean: '내일 비가 올 텐데 우산 챙기세요.', english: "It'll probably rain tomorrow, so bring an umbrella.", highlight: '올 텐데' },
    ],
    tips: 'This shows concern or consideration for the listener. It is a warm, empathetic expression.',
    category: 'Verb Endings',
  },
  {
    id: 'g3-12',
    level: 3,
    title: '-더라고요',
    titleRomanized: '-deoragoyo',
    meaning: 'I noticed / I found out that',
    explanation: 'Shares a personal observation or discovery from direct experience. The speaker reports something they personally witnessed or realized.',
    structure: 'Verb/Adjective stem + 더라고요',
    examples: [
      { korean: '한국 음식이 정말 맛있더라고요.', english: 'I found that Korean food is really delicious.', highlight: '맛있더라고요' },
      { korean: '그 영화가 생각보다 재미있더라고요.', english: 'That movie was more fun than I expected.', highlight: '재미있더라고요' },
      { korean: '서울이 정말 크더라고요.', english: 'I noticed Seoul is really big.', highlight: '크더라고요' },
    ],
    tips: 'Can only be used about things you directly experienced. Cannot be used about yourself in present tense.',
    category: 'Speech Levels',
  },
  {
    id: 'g3-13',
    level: 3,
    title: '-거든요',
    titleRomanized: '-geodeunyo',
    meaning: 'You see / because (explanation)',
    explanation: 'Provides background explanation or justification. Often used to give a reason the listener may not know. It adds "you see" nuance.',
    structure: 'Verb/Adjective stem + 거든요',
    examples: [
      { korean: '내일 못 가요. 시험이 있거든요.', english: "I can't go tomorrow. I have an exam, you see.", highlight: '있거든요' },
      { korean: '좀 피곤해요. 어제 늦게 잤거든요.', english: "I'm a bit tired. I went to bed late yesterday, you see.", highlight: '잤거든요' },
      { korean: '이거 맛있어요. 유명한 가게거든요.', english: "This is delicious. It's a famous restaurant, you see.", highlight: '가게거든요' },
    ],
    tips: 'Use -거든요 when you are adding information the listener does not yet know. It is explanatory, not just causal.',
    category: 'Speech Levels',
  },
  {
    id: 'g3-14',
    level: 3,
    title: '-(으)ㄹ 만하다',
    titleRomanized: '-(eu)l manhada',
    meaning: 'Worth doing',
    explanation: 'Expresses that something is worth doing or experiencing. It recommends an action based on its value or quality.',
    structure: 'Verb stem + (으)ㄹ 만하다',
    examples: [
      { korean: '이 영화는 볼 만해요.', english: 'This movie is worth watching.', highlight: '볼 만해요' },
      { korean: '이 식당은 갈 만해요.', english: 'This restaurant is worth going to.', highlight: '갈 만해요' },
      { korean: '그 책은 읽을 만해요.', english: 'That book is worth reading.', highlight: '읽을 만해요' },
    ],
    tips: 'Can also mean "tolerable": 참을 만해요 (It\'s bearable). Context determines the exact nuance.',
    category: 'Verb Endings',
  },
  {
    id: 'g3-15',
    level: 3,
    title: '-는 척하다',
    titleRomanized: '-neun cheokhada',
    meaning: 'Pretend to do',
    explanation: 'Expresses that someone is pretending or acting as if something is true when it is not. Used to describe fake or insincere behavior.',
    structure: 'Verb stem + 는 척하다; Adjective stem + (으)ㄴ 척하다',
    examples: [
      { korean: '모르는 척했어요.', english: 'I pretended not to know.', highlight: '모르는 척했어요' },
      { korean: '자는 척하지 마세요.', english: "Don't pretend to sleep.", highlight: '자는 척하지' },
      { korean: '아픈 척하고 학교에 안 갔어요.', english: "I pretended to be sick and didn't go to school.", highlight: '아픈 척하고' },
    ],
    tips: 'Very commonly used in everyday speech. -는 체하다 is a more formal synonym.',
    category: 'Verb Endings',
  },
  {
    id: 'g3-16',
    level: 3,
    title: '-는 편이다',
    titleRomanized: '-neun pyeonida',
    meaning: 'Tend to / rather / on the ... side',
    explanation: 'Softens a statement by expressing a general tendency rather than an absolute. It means "tend to" or "relatively."',
    structure: 'Verb stem + 는 편이다; Adjective stem + (으)ㄴ 편이다',
    examples: [
      { korean: '저는 일찍 자는 편이에요.', english: 'I tend to go to bed early.', highlight: '자는 편이에요' },
      { korean: '한국어가 어려운 편이에요.', english: 'Korean is on the difficult side.', highlight: '어려운 편이에요' },
      { korean: '저는 매운 음식을 잘 먹는 편이에요.', english: 'I tend to eat spicy food well.', highlight: '먹는 편이에요' },
    ],
    tips: 'This makes your statement less absolute and more humble. Very useful in conversations to sound natural.',
    category: 'Verb Endings',
  },
  {
    id: 'g3-17',
    level: 3,
    title: '-도록',
    titleRomanized: '-dorok',
    meaning: 'So that / until / in order to',
    explanation: 'Expresses purpose ("so that"), extent ("until"), or manner. It indicates the goal or degree of the action.',
    structure: 'Verb stem + 도록',
    examples: [
      { korean: '늦지 않도록 일찍 출발하세요.', english: 'Leave early so that you are not late.', highlight: '않도록' },
      { korean: '밤새도록 공부했어요.', english: 'I studied all through the night (until dawn).', highlight: '밤새도록' },
      { korean: '잘 들리도록 크게 말해 주세요.', english: 'Please speak loudly so I can hear well.', highlight: '들리도록' },
    ],
    tips: 'When it means "until," it emphasizes the extent: 죽도록 (to the point of death, i.e., extremely).',
    category: 'Connectors',
  },
  {
    id: 'g3-18',
    level: 3,
    title: '-(으)ㄹ 정도로',
    titleRomanized: '-(eu)l jeongdoro',
    meaning: 'To the extent that',
    explanation: 'Describes the degree or extent of something by giving an extreme or illustrative comparison. It emphasizes how much.',
    structure: 'Verb/Adjective stem + (으)ㄹ 정도로',
    examples: [
      { korean: '울 정도로 감동적이었어요.', english: 'It was touching to the point of crying.', highlight: '울 정도로' },
      { korean: '못 걸을 정도로 아팠어요.', english: 'I was sick to the point of not being able to walk.', highlight: '못 걸을 정도로' },
      { korean: '눈이 안 보일 정도로 비가 왔어요.', english: "It rained so much you couldn't see.", highlight: '안 보일 정도로' },
    ],
    tips: 'Used for emphasis. The result clause usually describes an extreme state caused by the degree described.',
    category: 'Connectors',
  },
  {
    id: 'g3-19',
    level: 3,
    title: '-(으)ㄹ수록',
    titleRomanized: '-(eu)lsurok',
    meaning: 'The more... the more',
    explanation: 'Expresses a proportional relationship — as one thing increases, another also increases. Often paired with a comparative result.',
    structure: 'Verb/Adjective stem + (으)ㄹ수록',
    examples: [
      { korean: '공부할수록 재미있어요.', english: 'The more I study, the more interesting it is.', highlight: '공부할수록' },
      { korean: '많이 먹을수록 살이 쪄요.', english: 'The more you eat, the more weight you gain.', highlight: '먹을수록' },
      { korean: '갈수록 어려워져요.', english: 'It gets harder as it goes on.', highlight: '갈수록' },
    ],
    tips: 'A common set phrase is 갈수록 (as time goes on / increasingly). 바쁘면 바쁠수록 is an emphatic form.',
    category: 'Connectors',
  },
  {
    id: 'g3-20',
    level: 3,
    title: '-기 때문에',
    titleRomanized: '-gi ttaemune',
    meaning: 'Because (formal reason)',
    explanation: 'A formal way to express a reason or cause. It is more explicit and slightly more formal than -아/어서 or -(으)니까.',
    structure: 'Verb/Adjective stem + 기 때문에',
    examples: [
      { korean: '비가 오기 때문에 우산을 가져가세요.', english: "Because it's raining, please take an umbrella.", highlight: '오기 때문에' },
      { korean: '바쁘기 때문에 못 갔어요.', english: "Because I was busy, I couldn't go.", highlight: '바쁘기 때문에' },
      { korean: '건강이 중요하기 때문에 운동해요.', english: 'Because health is important, I exercise.', highlight: '중요하기 때문에' },
    ],
    tips: 'With nouns, use 때문에 directly: 비 때문에 못 갔어요 (I couldn\'t go because of the rain).',
    category: 'Connectors',
  },
  {
    id: 'g3-21',
    level: 3,
    title: '-는 대로',
    titleRomanized: '-neun daero',
    meaning: 'As soon as / according to',
    explanation: 'Has two meanings: (1) "as soon as" when something happens and (2) "according to" or "as" when following a method or instruction.',
    structure: 'Verb stem + 는 대로',
    examples: [
      { korean: '도착하는 대로 전화할게요.', english: "I'll call as soon as I arrive.", highlight: '도착하는 대로' },
      { korean: '선생님이 말하는 대로 하세요.', english: 'Do as the teacher says.', highlight: '말하는 대로' },
      { korean: '생각나는 대로 말해 주세요.', english: 'Please say whatever comes to mind.', highlight: '생각나는 대로' },
    ],
    tips: 'With nouns: 계획대로 (according to plan), 예정대로 (as scheduled).',
    category: 'Connectors',
  },

  // ===== LEVEL 4 (20 points) - Upper Intermediate =====
  {
    id: 'g4-01',
    level: 4,
    title: '-아/어지다',
    titleRomanized: '-a/eojida',
    meaning: 'Become / get (change of state or passive)',
    explanation: 'Attached to adjectives, it means "become" (a change of state). Attached to verbs, it can form a passive construction. Very commonly used.',
    structure: 'Adjective stem + 아/어지다; Verb stem + 아/어지다',
    examples: [
      { korean: '날씨가 따뜻해졌어요.', english: 'The weather has gotten warm.', highlight: '따뜻해졌어요' },
      { korean: '한국어가 점점 좋아져요.', english: 'I am gradually getting to like Korean.', highlight: '좋아져요' },
      { korean: '유리창이 깨졌어요.', english: 'The window got broken.', highlight: '깨졌어요' },
    ],
    tips: 'With adjectives, it always means "become." With some verbs, it creates passive meaning (꺼지다 from 끄다).',
    category: 'Verb Endings',
  },
  {
    id: 'g4-02',
    level: 4,
    title: '-(으)ㄹ 리가 없다',
    titleRomanized: '-(eu)l riga eopda',
    meaning: 'There is no way that / cannot be',
    explanation: 'Expresses strong disbelief or denial that something could be true. It means the speaker considers the situation impossible.',
    structure: 'Verb/Adjective stem + (으)ㄹ 리가 없다',
    examples: [
      { korean: '그가 거짓말을 할 리가 없어요.', english: 'There is no way he would lie.', highlight: '할 리가 없어요' },
      { korean: '벌써 도착했을 리가 없어요.', english: 'There is no way they arrived already.', highlight: '도착했을 리가 없어요' },
      { korean: '그런 일이 있을 리가 없어요.', english: 'There is no way that could have happened.', highlight: '있을 리가 없어요' },
    ],
    tips: 'For the opposite (it must be the case), use -(으)ㄹ 리가 있다? as a rhetorical question, or -(으)ㄹ 거예요.',
    category: 'Verb Endings',
  },
  {
    id: 'g4-03',
    level: 4,
    title: '-이/히/리/기',
    titleRomanized: '-i/hi/ri/gi',
    meaning: 'Passive voice suffixes',
    explanation: 'Korean passive voice is formed by adding specific suffixes to the verb stem. Each verb takes a fixed suffix; they must be memorized individually.',
    structure: 'Verb stem + 이/히/리/기 → Passive verb',
    examples: [
      { korean: '문이 열렸어요.', english: 'The door was opened.', highlight: '열렸어요' },
      { korean: '답이 찾아졌어요... 아니, 답이 찾겼어요.', english: 'The answer was found.', highlight: '찾겼어요' },
      { korean: '그 노래가 많이 들려요.', english: 'That song is heard a lot.', highlight: '들려요' },
    ],
    tips: 'Common pairs: 보다→보이다 (see→be seen), 듣다→들리다 (hear→be heard), 잡다→잡히다 (catch→be caught), 끊다→끊기다 (cut→be cut off).',
    category: 'Passive & Causative',
  },
  {
    id: 'g4-04',
    level: 4,
    title: '-이/히/리/기/우/추',
    titleRomanized: '-i/hi/ri/gi/u/chu',
    meaning: 'Causative suffixes',
    explanation: 'Creates causative verbs meaning "to make someone do" or "to cause something to happen." Each verb takes a specific suffix.',
    structure: 'Verb stem + 이/히/리/기/우/추 → Causative verb',
    examples: [
      { korean: '아이에게 옷을 입혔어요.', english: 'I dressed the child (made them wear clothes).', highlight: '입혔어요' },
      { korean: '아기를 재웠어요.', english: 'I put the baby to sleep.', highlight: '재웠어요' },
      { korean: '학생들을 웃겼어요.', english: 'I made the students laugh.', highlight: '웃겼어요' },
    ],
    tips: 'Common pairs: 먹다→먹이다 (eat→feed), 자다→재우다 (sleep→put to sleep), 읽다→읽히다 (read→make read), 웃다→웃기다 (laugh→make laugh).',
    category: 'Passive & Causative',
  },
  {
    id: 'g4-05',
    level: 4,
    title: '-(으)ㄴ/는 반면에',
    titleRomanized: '-(eu)n/neun banmyeone',
    meaning: 'On the other hand / while',
    explanation: 'Presents two contrasting facts or situations. Both sides are true, but they differ significantly from each other.',
    structure: 'Verb stem + 는 반면(에); Adjective stem + (으)ㄴ 반면(에)',
    examples: [
      { korean: '여름은 더운 반면에 겨울은 추워요.', english: 'Summer is hot, whereas winter is cold.', highlight: '더운 반면에' },
      { korean: '도시는 편리한 반면에 시끄러워요.', english: 'The city is convenient, but on the other hand, noisy.', highlight: '편리한 반면에' },
      { korean: '형은 키가 큰 반면에 동생은 작아요.', english: 'The older brother is tall, while the younger one is short.', highlight: '큰 반면에' },
    ],
    tips: 'This is a balanced contrast where neither side is more important. Different from -지만 which is a simple "but."',
    category: 'Connectors',
  },
  {
    id: 'g4-06',
    level: 4,
    title: '-(으)ㄴ/는 셈이다',
    titleRomanized: '-(eu)n/neun semida',
    meaning: 'It amounts to / practically',
    explanation: 'Expresses that a situation is equivalent to or can be considered as something. Used when drawing a conclusion about what a situation amounts to.',
    structure: 'Verb stem + 는/(으)ㄴ 셈이다',
    examples: [
      { korean: '거의 다 한 셈이에요.', english: "It's practically done.", highlight: '한 셈이에요' },
      { korean: '공짜로 산 셈이에요.', english: 'It amounts to getting it for free.', highlight: '산 셈이에요' },
      { korean: '매일 운동하는 셈이에요.', english: 'I practically exercise every day.', highlight: '운동하는 셈이에요' },
    ],
    tips: 'Used to summarize or reinterpret a situation. Often implies the result is better or worse than expected.',
    category: 'Verb Endings',
  },
  {
    id: 'g4-07',
    level: 4,
    title: '-는 한',
    titleRomanized: '-neun han',
    meaning: 'As long as',
    explanation: 'Sets a condition that must remain true for the main clause to hold. It means "as long as" or "so long as."',
    structure: 'Verb stem + 는 한; Adjective stem + (으)ㄴ 한',
    examples: [
      { korean: '노력하는 한 성공할 수 있어요.', english: 'As long as you try, you can succeed.', highlight: '노력하는 한' },
      { korean: '건강한 한 행복해요.', english: 'As long as I am healthy, I am happy.', highlight: '건강한 한' },
      { korean: '가능한 한 빨리 오세요.', english: 'Come as quickly as possible.', highlight: '가능한 한' },
    ],
    tips: '가능한 한 is a set phrase meaning "as much as possible."',
    category: 'Connectors',
  },
  {
    id: 'g4-08',
    level: 4,
    title: '-(으)ㄹ 뻔하다',
    titleRomanized: '-(eu)l ppeonhada',
    meaning: 'Almost did / nearly happened',
    explanation: 'Describes something that almost happened but did not. Used for events that were narrowly avoided, often negative.',
    structure: 'Verb stem + (으)ㄹ 뻔했다',
    examples: [
      { korean: '넘어질 뻔했어요.', english: 'I almost fell.', highlight: '넘어질 뻔했어요' },
      { korean: '지각할 뻔했어요.', english: 'I almost was late.', highlight: '지각할 뻔했어요' },
      { korean: '울 뻔했어요.', english: 'I almost cried.', highlight: '울 뻔했어요' },
    ],
    tips: 'Usually used in past tense. Implies relief that the event did not actually occur.',
    category: 'Verb Endings',
  },
  {
    id: 'g4-09',
    level: 4,
    title: '-(으)ㄹ 겸',
    titleRomanized: '-(eu)l gyeom',
    meaning: 'For the combined purpose of',
    explanation: 'Expresses doing something with multiple purposes at once. It means "while also" or "for the purpose of... and also."',
    structure: 'Verb stem + (으)ㄹ 겸 + Verb stem + (으)ㄹ 겸',
    examples: [
      { korean: '운동할 겸 산책했어요.', english: 'I took a walk, partly for exercise.', highlight: '운동할 겸' },
      { korean: '구경할 겸 쇼핑할 겸 명동에 갔어요.', english: 'I went to Myeongdong for sightseeing and shopping.', highlight: '구경할 겸 쇼핑할 겸' },
      { korean: '기분 전환할 겸 영화를 봤어요.', english: 'I watched a movie to change my mood.', highlight: '기분 전환할 겸' },
    ],
    tips: 'Often used in pairs: A할 겸 B할 겸. But a single -겸 is also natural.',
    category: 'Connectors',
  },
  {
    id: 'g4-10',
    level: 4,
    title: '-아/어 봤자',
    titleRomanized: '-a/eo bwatja',
    meaning: 'Even if you try / it is useless to',
    explanation: 'Expresses that doing something will be pointless or will not change the outcome. It dismisses the value of the action.',
    structure: 'Verb stem + 아/어 봤자',
    examples: [
      { korean: '말해 봤자 소용없어요.', english: "Even if you say it, it's useless.", highlight: '말해 봤자' },
      { korean: '서둘러 봤자 늦을 거예요.', english: "Even if you hurry, you'll be late.", highlight: '서둘러 봤자' },
      { korean: '공부해 봤자 시험에 안 나와요.', english: "Even if you study it, it won't be on the test.", highlight: '공부해 봤자' },
    ],
    tips: 'Always carries a negative or dismissive nuance about the result.',
    category: 'Connectors',
  },
  {
    id: 'g4-11',
    level: 4,
    title: '-고 말다',
    titleRomanized: '-go malda',
    meaning: 'End up doing (unfortunately)',
    explanation: 'Indicates that something happened in the end despite efforts to prevent it. Usually carries a sense of regret or resignation.',
    structure: 'Verb stem + 고 말다/말았다',
    examples: [
      { korean: '결국 울고 말았어요.', english: 'I ended up crying in the end.', highlight: '울고 말았어요' },
      { korean: '비밀을 말하고 말았어요.', english: 'I ended up telling the secret.', highlight: '말하고 말았어요' },
      { korean: '그만 넘어지고 말았어요.', english: 'I ended up falling down.', highlight: '넘어지고 말았어요' },
    ],
    tips: 'Often preceded by 결국 (in the end) or 그만 (inadvertently). Implies the result was unavoidable.',
    category: 'Verb Endings',
  },
  {
    id: 'g4-12',
    level: 4,
    title: '-(으)ㄹ 따름이다',
    titleRomanized: '-(eu)l ttareumida',
    meaning: 'Only / merely / all one can do',
    explanation: 'Expresses that the speaker can only do one thing and nothing else. It conveys helplessness or the limitation of options.',
    structure: 'Verb stem + (으)ㄹ 따름이다',
    examples: [
      { korean: '감사할 따름이에요.', english: 'I can only be grateful.', highlight: '감사할 따름이에요' },
      { korean: '기다릴 따름이에요.', english: 'All I can do is wait.', highlight: '기다릴 따름이에요' },
      { korean: '노력할 따름이에요.', english: 'I can only try my best.', highlight: '노력할 따름이에요' },
    ],
    tips: 'This sounds more formal and literary. In casual speech, -(으)ㄹ 수밖에 없다 is more natural.',
    category: 'Verb Endings',
  },
  {
    id: 'g4-13',
    level: 4,
    title: '-는 법이다',
    titleRomanized: '-neun beobida',
    meaning: 'It is natural that / that is how things are',
    explanation: 'States a general truth or natural law about life. It conveys that something is expected or inevitable.',
    structure: 'Verb stem + 는 법이다',
    examples: [
      { korean: '노력하면 성공하는 법이에요.', english: 'If you work hard, success will naturally follow.', highlight: '성공하는 법이에요' },
      { korean: '세월은 빠르게 지나가는 법이에요.', english: 'Time naturally passes quickly.', highlight: '지나가는 법이에요' },
      { korean: '사람은 실수하는 법이에요.', english: "It's natural for people to make mistakes.", highlight: '실수하는 법이에요' },
    ],
    tips: 'This is a proverbial tone. Use it to share wisdom or comfort someone about inevitable things.',
    category: 'Verb Endings',
  },
  {
    id: 'g4-14',
    level: 4,
    title: '-기 마련이다',
    titleRomanized: '-gi ryeonida',
    meaning: 'Bound to / inevitably',
    explanation: 'Expresses that something is bound to happen or is inevitable given the circumstances. Similar to -는 법이다 but stronger.',
    structure: 'Verb stem + 기 마련이다',
    examples: [
      { korean: '노력하면 결과가 있기 마련이에요.', english: 'If you work hard, there are bound to be results.', highlight: '있기 마련이에요' },
      { korean: '좋은 일 뒤에는 나쁜 일이 오기 마련이에요.', english: 'After good things, bad things are bound to come.', highlight: '오기 마련이에요' },
      { korean: '시간이 지나면 잊기 마련이에요.', english: "As time passes, you're bound to forget.", highlight: '잊기 마련이에요' },
    ],
    tips: 'Often used in writing and speeches. It sounds philosophical and wise.',
    category: 'Verb Endings',
  },
  {
    id: 'g4-15',
    level: 4,
    title: '-기에',
    titleRomanized: '-gie',
    meaning: 'Because / for (written/formal reason)',
    explanation: 'A concise, slightly formal way to express a reason. It is commonly used in writing and formal speech as a shorter alternative to -기 때문에.',
    structure: 'Verb/Adjective stem + 기에',
    examples: [
      { korean: '날씨가 좋기에 산책을 했어요.', english: 'Because the weather was nice, I took a walk.', highlight: '좋기에' },
      { korean: '시간이 없기에 택시를 탔어요.', english: 'Because there was no time, I took a taxi.', highlight: '없기에' },
      { korean: '가격이 싸기에 샀어요.', english: 'Because the price was cheap, I bought it.', highlight: '싸기에' },
    ],
    tips: 'More common in writing than in casual conversation. -길래 is a similar but more colloquial form.',
    category: 'Connectors',
  },
  {
    id: 'g4-16',
    level: 4,
    title: '-(으)ㄴ/는 이상',
    titleRomanized: '-(eu)n/neun isang',
    meaning: 'Since / given that / now that',
    explanation: 'Establishes a fact as the basis for the main clause. Once the condition in the first clause is accepted, the conclusion follows.',
    structure: 'Verb stem + 는/(으)ㄴ 이상',
    examples: [
      { korean: '약속한 이상 지켜야 해요.', english: 'Since you made a promise, you must keep it.', highlight: '약속한 이상' },
      { korean: '시작한 이상 끝까지 해야 해요.', english: 'Since you started, you must finish.', highlight: '시작한 이상' },
      { korean: '알고 있는 이상 모른 척할 수 없어요.', english: "Since I know, I can't pretend not to.", highlight: '알고 있는 이상' },
    ],
    tips: 'Implies a moral or logical obligation following from the established fact.',
    category: 'Connectors',
  },
  {
    id: 'g4-17',
    level: 4,
    title: '-(으)ㄴ/는 탓에',
    titleRomanized: '-(eu)n/neun tase',
    meaning: 'Due to / because of (blame)',
    explanation: 'Attributes a negative result to a specific cause. 탓 implies blame or fault, so the result is always undesirable.',
    structure: 'Verb stem + 는/(으)ㄴ 탓에; Noun + 탓에',
    examples: [
      { korean: '비가 온 탓에 경기가 취소됐어요.', english: 'The game was canceled due to rain.', highlight: '온 탓에' },
      { korean: '잠을 못 잔 탓에 피곤해요.', english: "I'm tired because I couldn't sleep.", highlight: '못 잔 탓에' },
      { korean: '날씨 탓에 비행기가 지연됐어요.', english: 'The flight was delayed due to the weather.', highlight: '날씨 탓에' },
    ],
    tips: 'Always used for negative outcomes. For positive outcomes, use 덕분에 (thanks to).',
    category: 'Connectors',
  },
  {
    id: 'g4-18',
    level: 4,
    title: '-고자',
    titleRomanized: '-goja',
    meaning: 'Intending to / in order to (formal)',
    explanation: 'Expresses a formal intention or purpose. Used in writing, speeches, and formal situations to state goals.',
    structure: 'Verb stem + 고자',
    examples: [
      { korean: '한국어를 배우고자 한국에 왔습니다.', english: 'I came to Korea intending to learn Korean.', highlight: '배우고자' },
      { korean: '건강을 지키고자 운동을 시작했습니다.', english: 'I started exercising in order to protect my health.', highlight: '지키고자' },
      { korean: '문제를 해결하고자 노력하고 있습니다.', english: 'I am trying in order to solve the problem.', highlight: '해결하고자' },
    ],
    tips: 'Very formal. In casual speech, -(으)려고 is used instead.',
    category: 'Connectors',
  },
  {
    id: 'g4-19',
    level: 4,
    title: '-(으)ㄹ지라도',
    titleRomanized: '-(eu)l jirado',
    meaning: 'Even if / even though',
    explanation: 'A strong concessive expression meaning "even if" something happens, the result will not change. More emphatic than -아/어도.',
    structure: 'Verb/Adjective stem + (으)ㄹ지라도',
    examples: [
      { korean: '아무리 어려울지라도 포기하지 마세요.', english: "No matter how hard it is, don't give up.", highlight: '어려울지라도' },
      { korean: '비가 올지라도 갈 거예요.', english: "Even if it rains, I'll go.", highlight: '올지라도' },
      { korean: '실패할지라도 도전해 보세요.', english: 'Even if you fail, try it.', highlight: '실패할지라도' },
    ],
    tips: 'More formal and emphatic than -아/어도. Common in speeches and motivational contexts.',
    category: 'Connectors',
  },
  {
    id: 'g4-20',
    level: 4,
    title: '-(으)ㄴ/는 데다가',
    titleRomanized: '-(eu)n/neun dedaga',
    meaning: 'In addition to / on top of that',
    explanation: 'Adds additional information to an already stated fact. It means "not only... but also" with cumulative emphasis.',
    structure: 'Verb stem + 는/(으)ㄴ 데다가',
    examples: [
      { korean: '비가 오는 데다가 바람도 불어요.', english: 'In addition to rain, the wind is blowing too.', highlight: '오는 데다가' },
      { korean: '맛있는 데다가 가격도 싸요.', english: "It's delicious and on top of that, it's cheap.", highlight: '맛있는 데다가' },
      { korean: '피곤한 데다가 배도 고파요.', english: "I'm tired and on top of that, I'm hungry.", highlight: '피곤한 데다가' },
    ],
    tips: 'The two things are usually of the same nature — both positive or both negative.',
    category: 'Connectors',
  },
  {
    id: 'g4-21',
    level: 4,
    title: '-(으)ㄹ 지경이다',
    titleRomanized: '-(eu)l jigyeongida',
    meaning: 'At the point of / on the verge of',
    explanation: 'Describes an extreme situation where one is on the verge of something. Used to emphasize how severe a condition has become.',
    structure: 'Verb stem + (으)ㄹ 지경이다',
    examples: [
      { korean: '너무 바빠서 쓰러질 지경이에요.', english: "I'm so busy I'm on the verge of collapsing.", highlight: '쓰러질 지경이에요' },
      { korean: '미칠 지경이에요.', english: "I'm at the point of going crazy.", highlight: '미칠 지경이에요' },
      { korean: '배가 터질 지경이에요.', english: "I'm so full I'm about to burst.", highlight: '터질 지경이에요' },
    ],
    tips: 'Always implies an extreme or exaggerated degree. The result has not actually happened yet.',
    category: 'Verb Endings',
  },

  // ===== LEVEL 5 (18 points) - Advanced =====
  {
    id: 'g5-01',
    level: 5,
    title: '-(으)ㄴ/는 바',
    titleRomanized: '-(eu)n/neun ba',
    meaning: 'The fact that / what (formal)',
    explanation: 'A formal expression referring to a fact, situation, or what has been stated. Common in news, academic writing, and formal speech.',
    structure: 'Verb stem + 는/(으)ㄴ 바',
    examples: [
      { korean: '제가 아는 바로는 그것은 사실이에요.', english: 'As far as I know, that is true.', highlight: '아는 바로는' },
      { korean: '앞서 말씀드린 바와 같이 진행하겠습니다.', english: 'As previously stated, we will proceed.', highlight: '말씀드린 바와 같이' },
      { korean: '조사한 바에 따르면 결과가 좋습니다.', english: 'According to what was investigated, the results are good.', highlight: '조사한 바에 따르면' },
    ],
    tips: 'Very formal. Common set phrases: 아는 바 (what I know), 들은 바 (what I heard).',
    category: 'Formal Expressions',
  },
  {
    id: 'g5-02',
    level: 5,
    title: '-(으)ㄹ진대',
    titleRomanized: '-(eu)ljindae',
    meaning: 'Given that / considering that',
    explanation: 'A literary and formal expression that sets up a premise or established fact, leading to a logical conclusion. Rarely used in everyday speech.',
    structure: 'Verb/Adjective stem + (으)ㄹ진대',
    examples: [
      { korean: '이미 결정된 일일진대 받아들여야 합니다.', english: 'Given that it has already been decided, we must accept it.', highlight: '일일진대' },
      { korean: '이리 된 바일진대 최선을 다합시다.', english: "Given that things have come to this, let's do our best.", highlight: '바일진대' },
      { korean: '약속한 일일진대 지키겠습니다.', english: 'Given that I promised, I will keep it.', highlight: '일일진대' },
    ],
    tips: 'Very literary and old-fashioned. You will encounter this in formal essays and literature.',
    category: 'Literary Forms',
  },
  {
    id: 'g5-03',
    level: 5,
    title: '-는 터에',
    titleRomanized: '-neun teoe',
    meaning: 'Since / being in the situation of',
    explanation: 'Describes the speaker\'s current situation as the background for the main clause. It sets up circumstances that lead to what follows.',
    structure: 'Verb stem + 는 터에',
    examples: [
      { korean: '마침 가는 터에 같이 갑시다.', english: "Since I'm going anyway, let's go together.", highlight: '가는 터에' },
      { korean: '바쁜 터에 도와줘서 고마워요.', english: "Thank you for helping even though you're busy.", highlight: '바쁜 터에' },
      { korean: '돈이 없는 터에 어떻게 해요?', english: "Since I have no money, what should I do?", highlight: '없는 터에' },
    ],
    tips: 'Similar to -(으)ㄴ/는 처지에. Used to describe one\'s circumstances as context.',
    category: 'Formal Expressions',
  },
  {
    id: 'g5-04',
    level: 5,
    title: '-(으)ㄴ들',
    titleRomanized: '-(eu)ndeul',
    meaning: 'Even if (rhetorical, literary)',
    explanation: 'A literary concessive meaning "even if." It often implies that even if the condition were true, the result would not change. Has a rhetorical tone.',
    structure: 'Verb/Adjective stem + (으)ㄴ들',
    examples: [
      { korean: '알았은들 어쩔 수 없었을 거예요.', english: "Even if I had known, I couldn't have done anything.", highlight: '알았은들' },
      { korean: '가본들 무슨 소용이에요?', english: 'Even if you go, what use is it?', highlight: '가본들' },
      { korean: '말한들 믿겠어요?', english: 'Even if I told you, would you believe it?', highlight: '말한들' },
    ],
    tips: 'Very literary and rhetorical. In everyday speech, -아/어도 or -더라도 would be used instead.',
    category: 'Literary Forms',
  },
  {
    id: 'g5-05',
    level: 5,
    title: '-기는커녕',
    titleRomanized: '-gineunkeonyeong',
    meaning: 'Far from / let alone',
    explanation: 'Strongly negates the first thing and presents something even less expected. Means "far from doing A, not even B."',
    structure: 'Verb stem + 기는커녕; Noun + (은/는)커녕',
    examples: [
      { korean: '도와주기는커녕 방해만 했어요.', english: 'Far from helping, they only got in the way.', highlight: '도와주기는커녕' },
      { korean: '밥은커녕 물도 못 마셨어요.', english: "Let alone rice, I couldn't even drink water.", highlight: '밥은커녕' },
      { korean: '감사하기는커녕 화를 냈어요.', english: 'Far from being thankful, they got angry.', highlight: '감사하기는커녕' },
    ],
    tips: 'The second clause always presents something lesser that also did not happen or is also negated.',
    category: 'Connectors',
  },
  {
    id: 'g5-06',
    level: 5,
    title: '-(으)ㄹ 망정',
    titleRomanized: '-(eu)l mangjeong',
    meaning: 'May well... but / even though... still',
    explanation: 'Concedes that the first clause may be true but asserts that the second clause holds despite it. It carries a strong stance.',
    structure: 'Verb/Adjective stem + (으)ㄹ 망정',
    examples: [
      { korean: '가난할 망정 정직해요.', english: 'Even though I may be poor, I am honest.', highlight: '가난할 망정' },
      { korean: '죽을 망정 거짓말은 안 해요.', english: "Even if I were to die, I won't lie.", highlight: '죽을 망정' },
      { korean: '늦을 망정 제대로 하겠어요.', english: "It may be late, but I'll do it properly.", highlight: '늦을 망정' },
    ],
    tips: 'Very strong expression of conviction. The speaker accepts the first clause but refuses to compromise on the second.',
    category: 'Literary Forms',
  },
  {
    id: 'g5-07',
    level: 5,
    title: '-(으)ㄹ 따름이다',
    titleRomanized: '-(eu)l ttareumida',
    meaning: 'All one can do is',
    explanation: 'Expresses that there is nothing else to do except the stated action. Conveys a sense of limitation or helpless acceptance.',
    structure: 'Verb stem + (으)ㄹ 따름이다',
    examples: [
      { korean: '바랄 따름입니다.', english: 'All I can do is hope.', highlight: '바랄 따름입니다' },
      { korean: '지켜볼 따름이에요.', english: 'All I can do is watch.', highlight: '지켜볼 따름이에요' },
      { korean: '최선을 다할 따름이에요.', english: 'All I can do is do my best.', highlight: '다할 따름이에요' },
    ],
    tips: 'More formal and literary than -(으)ㄹ 수밖에 없다. Often used in speeches and writing.',
    category: 'Formal Expressions',
  },
  {
    id: 'g5-08',
    level: 5,
    title: '-노라면',
    titleRomanized: '-noramyeon',
    meaning: 'If one keeps doing',
    explanation: 'Expresses that if someone continues an action over time, a certain result will follow. It combines ongoing action with a conditional.',
    structure: 'Verb stem + 노라면',
    examples: [
      { korean: '연습하노라면 잘하게 될 거예요.', english: 'If you keep practicing, you will get good at it.', highlight: '연습하노라면' },
      { korean: '살다 보면 힘들 때도 있고, 참고 견디노라면 좋은 날이 와요.', english: 'In life there are hard times, but if you endure, good days will come.', highlight: '견디노라면' },
      { korean: '노력하노라면 반드시 성과가 있어요.', english: 'If you keep working hard, there will surely be results.', highlight: '노력하노라면' },
    ],
    tips: 'Literary and encouraging. Used for motivational or proverbial statements.',
    category: 'Literary Forms',
  },
  {
    id: 'g5-09',
    level: 5,
    title: '-(으)리라',
    titleRomanized: '-(eu)rira',
    meaning: 'Will (literary future)',
    explanation: 'A literary or poetic form of expressing future tense, determination, or prediction. Not used in casual speech.',
    structure: 'Verb/Adjective stem + (으)리라',
    examples: [
      { korean: '반드시 성공하리라.', english: 'I shall surely succeed.', highlight: '성공하리라' },
      { korean: '좋은 날이 오리라 믿습니다.', english: 'I believe good days will come.', highlight: '오리라' },
      { korean: '그날을 잊지 않으리라.', english: 'I shall not forget that day.', highlight: '않으리라' },
    ],
    tips: 'Found in poetry, songs, formal speeches, and historical dramas. Very elevated register.',
    category: 'Literary Forms',
  },
  {
    id: 'g5-10',
    level: 5,
    title: '-(으)ㄹ진저',
    titleRomanized: '-(eu)ljinjeo',
    meaning: 'I wonder if / whether indeed',
    explanation: 'An archaic and literary expression used to wonder or doubt about something. Found in classical texts and formal literature.',
    structure: 'Verb/Adjective stem + (으)ㄹ진저',
    examples: [
      { korean: '그가 과연 올진저.', english: 'I wonder if he will indeed come.', highlight: '올진저' },
      { korean: '이 일이 가능할진저.', english: 'I wonder if this task is possible.', highlight: '가능할진저' },
      { korean: '진실을 알진저.', english: 'I wonder if they know the truth.', highlight: '알진저' },
    ],
    tips: 'Extremely literary and archaic. Seen in classical Korean literature and formal essays.',
    category: 'Literary Forms',
  },
  {
    id: 'g5-11',
    level: 5,
    title: '-거니와',
    titleRomanized: '-geoniwa',
    meaning: 'Not only... but also (literary)',
    explanation: 'A literary connector meaning "not only A, but also B." It adds information in a formal, cumulative way.',
    structure: 'Verb/Adjective stem + 거니와',
    examples: [
      { korean: '실력이 뛰어나거니와 성격도 좋아요.', english: 'Not only are their skills excellent, but their personality is good too.', highlight: '뛰어나거니와' },
      { korean: '맛이 좋거니와 건강에도 좋아요.', english: 'Not only does it taste good, but it is also healthy.', highlight: '좋거니와' },
      { korean: '경치가 아름답거니와 공기도 맑아요.', english: 'Not only is the scenery beautiful, but the air is clean too.', highlight: '아름답거니와' },
    ],
    tips: 'More literary than -(으)ㄹ 뿐만 아니라. Used in formal writing and speeches.',
    category: 'Literary Forms',
  },
  {
    id: 'g5-12',
    level: 5,
    title: '-(으)ㄴ/는 양',
    titleRomanized: '-(eu)n/neun yang',
    meaning: 'As if / as though',
    explanation: 'Describes someone acting as if something is the case when it may not be. It describes appearance or manner.',
    structure: 'Verb stem + 는/(으)ㄴ 양',
    examples: [
      { korean: '아무 일도 없는 양 행동했어요.', english: 'They acted as if nothing had happened.', highlight: '없는 양' },
      { korean: '모르는 양 시치미를 뗐어요.', english: 'They played dumb as if they did not know.', highlight: '모르는 양' },
      { korean: '다 아는 양 말했어요.', english: 'They spoke as if they knew everything.', highlight: '아는 양' },
    ],
    tips: 'Similar to -는 척하다 but more literary. -는 양 describes the manner rather than the act of pretending.',
    category: 'Literary Forms',
  },
  {
    id: 'g5-13',
    level: 5,
    title: '-더라도',
    titleRomanized: '-deorado',
    meaning: 'Even if / even though',
    explanation: 'A strong concessive meaning "even if" a situation is true or becomes true, the result remains unchanged. More emphatic than -아/어도.',
    structure: 'Verb/Adjective stem + 더라도',
    examples: [
      { korean: '힘들더라도 포기하지 마세요.', english: "Even if it's hard, don't give up.", highlight: '힘들더라도' },
      { korean: '실패하더라도 다시 시도하세요.', english: 'Even if you fail, try again.', highlight: '실패하더라도' },
      { korean: '비가 오더라도 갈 거예요.', english: "Even if it rains, I'll go.", highlight: '오더라도' },
    ],
    tips: 'Stronger than -아/어도. Often used with 아무리 (no matter how) for extra emphasis.',
    category: 'Connectors',
  },
  {
    id: 'g5-14',
    level: 5,
    title: '-(으)ㄹ 법하다',
    titleRomanized: '-(eu)l beopada',
    meaning: 'Likely to / it makes sense that',
    explanation: 'Expresses that something is likely or reasonable to happen given the circumstances. It shows logical expectation.',
    structure: 'Verb/Adjective stem + (으)ㄹ 법하다',
    examples: [
      { korean: '지금쯤 도착했을 법해요.', english: 'They should have arrived by now.', highlight: '도착했을 법해요' },
      { korean: '그럴 법한 이야기예요.', english: "That's a plausible story.", highlight: '그럴 법한' },
      { korean: '화가 났을 법도 해요.', english: "It's understandable that they would be angry.", highlight: '났을 법도 해요' },
    ],
    tips: 'Often used with -도: -(으)ㄹ 법도 하다, meaning "it would be reasonable/understandable."',
    category: 'Verb Endings',
  },
  {
    id: 'g5-15',
    level: 5,
    title: '-는 통에',
    titleRomanized: '-neun tonge',
    meaning: 'Because of (amid chaos/disruption)',
    explanation: 'Indicates that a negative result occurred because of a disruptive or chaotic situation. Similar to -는 바람에 but with a sense of commotion.',
    structure: 'Verb stem + 는 통에',
    examples: [
      { korean: '아이들이 떠드는 통에 집중할 수 없었어요.', english: "Because the children were noisy, I couldn't concentrate.", highlight: '떠드는 통에' },
      { korean: '전화가 오는 통에 잠을 못 잤어요.', english: "Because calls kept coming, I couldn't sleep.", highlight: '오는 통에' },
      { korean: '사람들이 밀치는 통에 넘어졌어요.', english: 'I fell because people were pushing.', highlight: '밀치는 통에' },
    ],
    tips: 'Only used for negative outcomes caused by chaotic or disruptive situations.',
    category: 'Connectors',
  },
  {
    id: 'g5-16',
    level: 5,
    title: '-(으)ㄴ/는 가운데',
    titleRomanized: '-(eu)n/neun gaunde',
    meaning: 'In the midst of / amidst',
    explanation: 'Describes an action or event taking place within a larger context or situation. Formal and commonly used in news.',
    structure: 'Verb stem + 는/(으)ㄴ 가운데',
    examples: [
      { korean: '어려운 상황 가운데에서도 희망을 잃지 않았어요.', english: 'Even amidst difficult circumstances, I did not lose hope.', highlight: '상황 가운데에서도' },
      { korean: '많은 관심이 쏠리는 가운데 행사가 시작됐어요.', english: 'The event began amidst much attention.', highlight: '쏠리는 가운데' },
      { korean: '바쁜 가운데 시간을 내 주셔서 감사합니다.', english: 'Thank you for making time amidst your busy schedule.', highlight: '바쁜 가운데' },
    ],
    tips: 'Common in news reports and formal writing. 가운데 literally means "middle."',
    category: 'Formal Expressions',
  },
  {
    id: 'g5-17',
    level: 5,
    title: '-(으)로 말미암아',
    titleRomanized: '-(eu)ro malmimaa',
    meaning: 'Owing to / because of (very formal)',
    explanation: 'A very formal and literary way to express cause or reason. Found in academic writing, legal documents, and formal speeches.',
    structure: 'Noun + (으)로 말미암아',
    examples: [
      { korean: '전쟁으로 말미암아 많은 사람이 고통받았어요.', english: 'Many people suffered owing to the war.', highlight: '전쟁으로 말미암아' },
      { korean: '그의 노력으로 말미암아 성공할 수 있었어요.', english: 'It was owing to his efforts that we could succeed.', highlight: '노력으로 말미암아' },
      { korean: '오해로 말미암아 문제가 생겼어요.', english: 'A problem arose owing to a misunderstanding.', highlight: '오해로 말미암아' },
    ],
    tips: 'Extremely formal. In everyday speech, use 때문에 or -아/어서 instead.',
    category: 'Formal Expressions',
  },
  {
    id: 'g5-18',
    level: 5,
    title: '-(으)ㄹ 나위 없다',
    titleRomanized: '-(eu)l nawi eopda',
    meaning: 'Could not be better / nothing more to wish for',
    explanation: 'Expresses that something is at the highest possible degree and nothing more is needed. It means "the best possible" or "beyond compare."',
    structure: 'Verb/Adjective stem + (으)ㄹ 나위 없다',
    examples: [
      { korean: '더할 나위 없이 행복해요.', english: "I couldn't be happier.", highlight: '더할 나위 없이' },
      { korean: '더할 나위 없는 기회예요.', english: "It's a perfect opportunity.", highlight: '더할 나위 없는' },
      { korean: '말할 나위 없이 중요해요.', english: 'It goes without saying that it is important.', highlight: '말할 나위 없이' },
    ],
    tips: 'Most commonly used as 더할 나위 없다 (couldn\'t be better). A very elegant expression.',
    category: 'Formal Expressions',
  },
  {
    id: 'g5-19',
    level: 5,
    title: '-건대',
    titleRomanized: '-geondae',
    meaning: 'As I see it / in my opinion (humble)',
    explanation: 'A humble and formal way to express one\'s opinion or observation. Used in writing and formal contexts to preface a personal view.',
    structure: 'Verb stem + 건대',
    examples: [
      { korean: '생각건대 이 방법이 최선이에요.', english: 'In my opinion, this method is the best.', highlight: '생각건대' },
      { korean: '보건대 상황이 좋지 않아요.', english: 'As I see it, the situation is not good.', highlight: '보건대' },
      { korean: '듣건대 그 소식은 사실이래요.', english: 'From what I hear, that news is true.', highlight: '듣건대' },
    ],
    tips: 'Mainly used with 생각하다, 보다, 듣다. Very formal and academic.',
    category: 'Formal Expressions',
  },

  // ===== LEVEL 6 (15 points) - Expert =====
  {
    id: 'g6-01',
    level: 6,
    title: '-(으)리만치',
    titleRomanized: '-(eu)rimanchi',
    meaning: 'To the extent that / so much that',
    explanation: 'A literary expression indicating the degree or extent of something. It emphasizes that something is true to such a degree that a consequence follows.',
    structure: 'Verb/Adjective stem + (으)리만치',
    examples: [
      { korean: '누구나 알리만치 유명한 사람이에요.', english: 'They are so famous that everyone knows them.', highlight: '알리만치' },
      { korean: '놀라리만치 실력이 좋아요.', english: 'Their skill is good to a surprising extent.', highlight: '놀라리만치' },
      { korean: '감탄하리만치 아름다운 풍경이에요.', english: 'The scenery is beautiful to the point of admiration.', highlight: '감탄하리만치' },
    ],
    tips: 'Very literary. In everyday Korean, -(으)ㄹ 정도로 or -(으)ㄹ 만큼 would be used instead.',
    category: 'Literary Forms',
  },
  {
    id: 'g6-02',
    level: 6,
    title: '-는 바이다',
    titleRomanized: '-neun baida',
    meaning: 'It is the case that (formal statement)',
    explanation: 'A very formal sentence ending used in official statements, declarations, and academic writing to assert a fact or position.',
    structure: 'Verb stem + 는 바이다',
    examples: [
      { korean: '이 사실을 엄중히 받아들이는 바입니다.', english: 'We take this fact very seriously.', highlight: '받아들이는 바입니다' },
      { korean: '다음과 같이 알리는 바입니다.', english: 'We hereby inform you as follows.', highlight: '알리는 바입니다' },
      { korean: '깊이 반성하는 바입니다.', english: 'We deeply reflect (on this matter).', highlight: '반성하는 바입니다' },
    ],
    tips: 'Found in official documents, news statements, and formal announcements. Very stiff and formal.',
    category: 'Formal Expressions',
  },
  {
    id: 'g6-03',
    level: 6,
    title: '-(으)련마는',
    titleRomanized: '-(eu)ryeonmaneun',
    meaning: 'Although one would expect / but contrary to expectation',
    explanation: 'An archaic concessive form expressing that something would be expected, but the reality is different. Found in classical and literary Korean.',
    structure: 'Verb/Adjective stem + (으)련마는',
    examples: [
      { korean: '알련마는 모르는 척했어요.', english: 'Although they would have known, they pretended not to.', highlight: '알련마는' },
      { korean: '힘들련마는 불평하지 않았어요.', english: 'Although it must have been hard, they did not complain.', highlight: '힘들련마는' },
      { korean: '보고 싶으련마는 갈 수 없어요.', english: 'Although I would want to see them, I cannot go.', highlight: '싶으련마는' },
    ],
    tips: 'Very archaic. Modern equivalents: -겠지만, -(으)ㄹ 텐데. Seen in literature and historical texts.',
    category: 'Archaic Forms',
  },
  {
    id: 'g6-04',
    level: 6,
    title: '-(으)ㄹ손가',
    titleRomanized: '-(eu)lsonka',
    meaning: 'Would it be? (rhetorical question)',
    explanation: 'A classical rhetorical question form implying that the answer is obvious (usually negative). Used in literary and poetic contexts.',
    structure: 'Verb/Adjective stem + (으)ㄹ손가',
    examples: [
      { korean: '누가 이 고통을 알손가.', english: 'Who would know this pain? (No one would.)', highlight: '알손가' },
      { korean: '어찌 잊을손가.', english: 'How could one forget? (One could not.)', highlight: '잊을손가' },
      { korean: '이것이 옳을손가.', english: 'Could this be right? (Probably not.)', highlight: '옳을손가' },
    ],
    tips: 'Extremely literary and poetic. The implied answer is usually "no." Modern equivalent: -(으)ㄹ 수 있겠는가?',
    category: 'Archaic Forms',
  },
  {
    id: 'g6-05',
    level: 6,
    title: '-는 지라',
    titleRomanized: '-neun jira',
    meaning: 'Because / since (formal literary)',
    explanation: 'A formal and slightly literary way to give a reason. Used in narrative writing and formal explanations. More elegant than -기 때문에.',
    structure: 'Verb stem + 는 지라; Adjective stem + (으)ㄴ 지라',
    examples: [
      { korean: '워낙 바쁜 지라 연락을 못 했어요.', english: "Since I was so busy, I couldn't contact you.", highlight: '바쁜 지라' },
      { korean: '아직 어린 지라 이해하기 어려울 거예요.', english: 'Since they are still young, it will be hard to understand.', highlight: '어린 지라' },
      { korean: '경험이 많은 지라 잘 처리했어요.', english: 'Since they have much experience, they handled it well.', highlight: '많은 지라' },
    ],
    tips: 'Sounds sophisticated and literary. Can be replaced by -(으)니까 in casual speech.',
    category: 'Literary Forms',
  },
  {
    id: 'g6-06',
    level: 6,
    title: '-매',
    titleRomanized: '-mae',
    meaning: 'Because (archaic)',
    explanation: 'An archaic causal connector meaning "because." Found in classical Korean literature, historical texts, and sometimes formal writing.',
    structure: 'Verb/Adjective stem + 매',
    examples: [
      { korean: '날이 밝았매 길을 떠났다.', english: 'Because the day had dawned, they set out.', highlight: '밝았매' },
      { korean: '비가 그쳤매 다시 나갔다.', english: 'Because the rain had stopped, they went out again.', highlight: '그쳤매' },
      { korean: '약속이 있었매 서둘러 갔다.', english: 'Because there was a prior engagement, they hurried.', highlight: '있었매' },
    ],
    tips: 'Extremely archaic. You will only encounter this in classical Korean texts or period dramas.',
    category: 'Archaic Forms',
  },
  {
    id: 'g6-07',
    level: 6,
    title: '-나마',
    titleRomanized: '-nama',
    meaning: 'Even though it is only / at least',
    explanation: 'Concedes that something is limited or insufficient but accepts it as better than nothing. It means "even if only" or "at least."',
    structure: 'Noun + (이)나마; Verb stem + (으)나마',
    examples: [
      { korean: '작으나마 도움이 되었으면 좋겠어요.', english: 'I hope it was helpful, however small.', highlight: '작으나마' },
      { korean: '이것이나마 감사해요.', english: 'I am grateful for at least this much.', highlight: '이것이나마' },
      { korean: '늦었으나마 축하해요.', english: 'Belated though it is, congratulations.', highlight: '늦었으나마' },
    ],
    tips: 'Very polite and humble. Good for expressions of modesty or gratitude.',
    category: 'Literary Forms',
  },
  {
    id: 'g6-08',
    level: 6,
    title: '-거들랑',
    titleRomanized: '-geodeullang',
    meaning: 'If at all / if it happens that (archaic conditional)',
    explanation: 'An archaic conditional form meaning "if" with an emphasis on the uncertainty of whether the condition will be met. Rarely used in modern speech.',
    structure: 'Verb stem + 거들랑',
    examples: [
      { korean: '오거들랑 전해 주세요.', english: 'If they happen to come, please pass this on.', highlight: '오거들랑' },
      { korean: '필요하거들랑 말씀하세요.', english: 'If you happen to need it, please let me know.', highlight: '필요하거들랑' },
      { korean: '보거들랑 연락해 주세요.', english: 'If you happen to see them, please contact me.', highlight: '보거들랑' },
    ],
    tips: 'Archaic. In modern Korean, -(으)면 or -거든 would be used instead.',
    category: 'Archaic Forms',
  },
  {
    id: 'g6-09',
    level: 6,
    title: '-(으)랴',
    titleRomanized: '-(eu)rya',
    meaning: 'Would it be? / Could it? (rhetorical)',
    explanation: 'A rhetorical question ending implying strong denial. The expected answer is "no." Used in literary and formal contexts for dramatic effect.',
    structure: 'Verb/Adjective stem + (으)랴',
    examples: [
      { korean: '그것을 누가 모르랴.', english: 'Who would not know that? (Everyone knows.)', highlight: '모르랴' },
      { korean: '이 아픔을 어찌 잊으랴.', english: 'How could one forget this pain?', highlight: '잊으랴' },
      { korean: '혼자서 할 수 있으랴.', english: 'Could one do it alone? (No.)', highlight: '있으랴' },
    ],
    tips: 'Poetic and dramatic. The answer is always implied to be negative.',
    category: 'Literary Forms',
  },
  {
    id: 'g6-10',
    level: 6,
    title: '-(으)리오',
    titleRomanized: '-(eu)rio',
    meaning: 'Would I/one...? (literary rhetorical)',
    explanation: 'A literary rhetorical question ending similar to -(으)랴. Strongly implies a negative answer. Found in poetry and elevated prose.',
    structure: 'Verb/Adjective stem + (으)리오',
    examples: [
      { korean: '어찌 그것을 모르리오.', english: 'How would I not know that?', highlight: '모르리오' },
      { korean: '누가 감히 반대하리오.', english: 'Who would dare oppose?', highlight: '반대하리오' },
      { korean: '이 은혜를 어찌 잊으리오.', english: 'How could I forget this kindness?', highlight: '잊으리오' },
    ],
    tips: 'Very poetic and classical. Similar to -(으)랴 but sometimes considered even more elevated.',
    category: 'Literary Forms',
  },
  {
    id: 'g6-11',
    level: 6,
    title: '-(으)ㄹ 양이면',
    titleRomanized: '-(eu)l yangimyeon',
    meaning: 'If it were to be the case that',
    explanation: 'A literary conditional expressing a hypothetical situation. It sets up a scenario that may or may not be realized.',
    structure: 'Verb/Adjective stem + (으)ㄹ 양이면',
    examples: [
      { korean: '떠날 양이면 미리 말해 주세요.', english: 'If you intend to leave, please tell me in advance.', highlight: '떠날 양이면' },
      { korean: '그만둘 양이면 지금 하세요.', english: 'If you plan to quit, do it now.', highlight: '그만둘 양이면' },
      { korean: '도와줄 양이면 제대로 도와주세요.', english: 'If you are going to help, help properly.', highlight: '도와줄 양이면' },
    ],
    tips: 'Literary and formal. Modern equivalent: -(으)려면 or -(으)ㄹ 거면.',
    category: 'Literary Forms',
  },
  {
    id: 'g6-12',
    level: 6,
    title: '-다시피 하다',
    titleRomanized: '-dasipi hada',
    meaning: 'Almost / practically / as good as',
    explanation: 'Expresses that something is so close to being true that it is practically the case. Shows an extreme degree approaching a state.',
    structure: 'Verb stem + 다시피 하다',
    examples: [
      { korean: '아시다시피 상황이 어려워요.', english: 'As you know, the situation is difficult.', highlight: '아시다시피' },
      { korean: '매일 울다시피 했어요.', english: 'I practically cried every day.', highlight: '울다시피 했어요' },
      { korean: '굶다시피 하면서 공부했어요.', english: 'I studied practically without eating.', highlight: '굶다시피 하면서' },
    ],
    tips: '아시다시피 (as you know) and 보시다시피 (as you can see) are very common set phrases.',
    category: 'Verb Endings',
  },
  {
    id: 'g6-13',
    level: 6,
    title: '-(으)ㄴ즉',
    titleRomanized: '-(eu)njeuk',
    meaning: 'Therefore / consequently (literary)',
    explanation: 'A literary conjunction expressing a logical conclusion or consequence. It connects a premise with its result in formal or classical writing.',
    structure: 'Verb/Adjective stem + (으)ㄴ즉',
    examples: [
      { korean: '들은즉 사정이 복잡하더군요.', english: 'Having heard about it, the situation was complicated.', highlight: '들은즉' },
      { korean: '알아본즉 그 말이 사실이었어요.', english: 'Upon looking into it, those words were true.', highlight: '알아본즉' },
      { korean: '생각한즉 그것이 최선이었어요.', english: 'Upon reflection, that was the best option.', highlight: '생각한즉' },
    ],
    tips: 'Literary and old-fashioned. Modern equivalents: -아/어 보니, -(으)ㄴ 결과.',
    category: 'Archaic Forms',
  },
  {
    id: 'g6-14',
    level: 6,
    title: '-노니',
    titleRomanized: '-noni',
    meaning: 'As I do / since I am doing (formal declarative)',
    explanation: 'A formal and literary ending used to declare one\'s action or state, often followed by a request or statement to the listener.',
    structure: 'Verb stem + 노니',
    examples: [
      { korean: '이제 말하노니 잘 들으세요.', english: 'As I now say this, listen carefully.', highlight: '말하노니' },
      { korean: '충고하노니 조심하세요.', english: 'As I advise you, please be careful.', highlight: '충고하노니' },
      { korean: '경고하노니 다시는 그러지 마세요.', english: 'As I warn you, do not do that again.', highlight: '경고하노니' },
    ],
    tips: 'Very authoritative and formal. Used by elders, teachers, or in historical/dramatic contexts.',
    category: 'Archaic Forms',
  },
  {
    id: 'g6-15',
    level: 6,
    title: '-(으)리라고는',
    titleRomanized: '-(eu)riragoneun',
    meaning: 'Would never have thought that',
    explanation: 'Expresses surprise that something happened, as the speaker never expected it. Often used with 생각하다, 상상하다, or 예상하다 in negative form.',
    structure: 'Verb/Adjective stem + (으)리라고는 + negative verb',
    examples: [
      { korean: '이렇게 될 거리라고는 생각도 못 했어요.', english: 'I never thought it would turn out like this.', highlight: '거리라고는' },
      { korean: '그가 떠나리라고는 상상도 못 했어요.', english: 'I never imagined he would leave.', highlight: '떠나리라고는' },
      { korean: '이렇게 어려우리라고는 몰랐어요.', english: 'I had no idea it would be this difficult.', highlight: '어려우리라고는' },
    ],
    tips: 'Always followed by a negative expression (못 했다, 몰랐다). Conveys genuine surprise.',
    category: 'Formal Expressions',
  },
];

export function getGrammarByLevel(level: number): GrammarPoint[] {
  return GRAMMAR_DATA.filter(g => g.level === level);
}

export const GRAMMAR_CATEGORIES: string[] = Array.from(
  new Set(GRAMMAR_DATA.map(g => g.category)),
);
