export interface ThemeLesson {
  id: string;
  title: string;
  titleKr: string;
  icon: string;
  color: string;
  description: string;
  words: ThemeWord[];
}

export interface ThemeWord {
  korean: string;
  english: string;
  pronunciation: string;
  example: string;
  exampleTranslation: string;
}

export const THEME_LESSONS: ThemeLesson[] = [
  {
    id: 'kdrama',
    title: 'K-Drama Expressions',
    titleKr: '드라마 표현',
    icon: 'film',
    color: '#FF6B6B',
    description: 'Popular phrases from Korean dramas',
    words: [
      { korean: '사랑해', english: 'I love you', pronunciation: 'sa-rang-hae', example: '나는 너를 사랑해.', exampleTranslation: 'I love you.' },
      { korean: '보고 싶어', english: 'I miss you', pronunciation: 'bo-go si-peo', example: '너무 보고 싶었어.', exampleTranslation: 'I missed you so much.' },
      { korean: '미안해', english: "I'm sorry", pronunciation: 'mi-an-hae', example: '정말 미안해.', exampleTranslation: "I'm really sorry." },
      { korean: '괜찮아', english: "It's okay", pronunciation: 'gwaen-chan-a', example: '괜찮아, 걱정 마.', exampleTranslation: "It's okay, don't worry." },
      { korean: '잠깐만', english: 'Wait a moment', pronunciation: 'jam-kkan-man', example: '잠깐만 기다려!', exampleTranslation: 'Wait a moment!' },
      { korean: '어떡해', english: 'What do I do?', pronunciation: 'eo-tteok-hae', example: '이제 어떡해?', exampleTranslation: 'What do I do now?' },
      { korean: '진짜?', english: 'Really?', pronunciation: 'jin-jja', example: '진짜? 정말이야?', exampleTranslation: 'Really? Is it true?' },
      { korean: '가지 마', english: "Don't go", pronunciation: 'ga-ji ma', example: '제발 가지 마.', exampleTranslation: "Please don't go." },
      { korean: '잘 했어', english: 'Good job', pronunciation: 'jal haess-eo', example: '정말 잘 했어!', exampleTranslation: 'You did really well!' },
      { korean: '힘내', english: 'Cheer up', pronunciation: 'him-nae', example: '힘내! 할 수 있어.', exampleTranslation: 'Cheer up! You can do it.' },
      { korean: '운명이야', english: "It's destiny", pronunciation: 'un-myeong-i-ya', example: '우리는 운명이야.', exampleTranslation: 'We are destiny.' },
      { korean: '첫눈에 반했어', english: 'Love at first sight', pronunciation: 'cheot-nun-e ban-haess-eo', example: '널 첫눈에 반했어.', exampleTranslation: 'I fell for you at first sight.' },
      { korean: '좋아해', english: 'I like you', pronunciation: 'jo-a-hae', example: '나 너 좋아해.', exampleTranslation: 'I like you.' },
      { korean: '헤어지자', english: "Let's break up", pronunciation: 'he-eo-ji-ja', example: '우리 헤어지자.', exampleTranslation: "Let's break up." },
      { korean: '내 편이 되어 줘', english: 'Be on my side', pronunciation: 'nae pyeon-i doe-eo jwo', example: '제발 내 편이 되어 줘.', exampleTranslation: 'Please be on my side.' },
      { korean: '오빠', english: 'Older brother (from a girl)', pronunciation: 'o-ppa', example: '오빠, 어디 가?', exampleTranslation: 'Oppa, where are you going?' },
      { korean: '언니', english: 'Older sister (from a girl)', pronunciation: 'eon-ni', example: '언니, 같이 가자.', exampleTranslation: 'Unnie, let us go together.' },
      { korean: '형', english: 'Older brother (from a boy)', pronunciation: 'hyeong', example: '형, 도와줘.', exampleTranslation: 'Hyung, help me.' },
      { korean: '누나', english: 'Older sister (from a boy)', pronunciation: 'nu-na', example: '누나가 최고야.', exampleTranslation: 'Noona is the best.' },
      { korean: '말도 안 돼', english: 'No way / Unbelievable', pronunciation: 'mal-do an dwae', example: '말도 안 돼! 거짓말이지?', exampleTranslation: 'No way! You are lying, right?' },
      { korean: '미치겠다', english: "I'm going crazy", pronunciation: 'mi-chi-get-da', example: '아, 진짜 미치겠다.', exampleTranslation: "Ah, I'm really going crazy." },
      { korean: '너밖에 없어', english: 'You are the only one', pronunciation: 'neo-bakk-e eops-eo', example: '나한테 너밖에 없어.', exampleTranslation: 'You are the only one for me.' },
      { korean: '짜증 나', english: "I'm annoyed", pronunciation: 'jja-jeung na', example: '아, 짜증 나!', exampleTranslation: 'Ah, so annoying!' },
      { korean: '배신자', english: 'Traitor', pronunciation: 'bae-sin-ja', example: '이 배신자!', exampleTranslation: 'You traitor!' },
      { korean: '우리 사이 뭐야?', english: 'What are we?', pronunciation: 'u-ri sa-i mwo-ya', example: '우리 사이 뭐야? 친구야?', exampleTranslation: 'What are we? Friends?' },
      { korean: '부장님', english: 'Department head', pronunciation: 'bu-jang-nim', example: '부장님, 보고서 올렸습니다.', exampleTranslation: 'Sir, I submitted the report.' },
      { korean: '대리님', english: 'Assistant manager', pronunciation: 'dae-ri-nim', example: '대리님, 회의 시간이에요.', exampleTranslation: 'It is meeting time, assistant manager.' },
      { korean: '야', english: 'Hey (informal)', pronunciation: 'ya', example: '야, 이리 와.', exampleTranslation: 'Hey, come here.' },
      { korean: '죽을래?', english: 'Do you want to die?', pronunciation: 'jug-eul-lae', example: '너 죽을래? 왜 그래!', exampleTranslation: 'Do you want to die? What is wrong with you!' },
      { korean: '나 갈게', english: "I'm leaving", pronunciation: 'na gal-ge', example: '나 먼저 갈게.', exampleTranslation: "I'll go first." },
      { korean: '잊지 마', english: "Don't forget", pronunciation: 'it-ji ma', example: '나를 잊지 마.', exampleTranslation: "Don't forget me." },
      { korean: '기다릴게', english: "I'll wait for you", pronunciation: 'gi-da-ril-ge', example: '여기서 기다릴게.', exampleTranslation: "I'll wait here for you." },
      { korean: '우리 결혼하자', english: "Let's get married", pronunciation: 'u-ri gyeol-hon-ha-ja', example: '나랑 결혼하자.', exampleTranslation: 'Marry me.' },
      { korean: '눈물', english: 'Tears', pronunciation: 'nun-mul', example: '눈물이 멈추지 않아.', exampleTranslation: 'The tears will not stop.' },
      { korean: '친구야', english: 'My friend', pronunciation: 'chin-gu-ya', example: '친구야, 오랜만이다!', exampleTranslation: 'My friend, long time no see!' },
    ],
  },
  {
    id: 'kpop',
    title: 'K-Pop Fan Talk',
    titleKr: '케이팝 팬 용어',
    icon: 'musical-notes',
    color: '#DDA0DD',
    description: 'Essential vocabulary for K-Pop fans',
    words: [
      { korean: '최애', english: 'Bias / Favorite', pronunciation: 'choe-ae', example: '내 최애는 지민이야.', exampleTranslation: 'My bias is Jimin.' },
      { korean: '컴백', english: 'Comeback', pronunciation: 'keom-baek', example: '다음 달에 컴백해요.', exampleTranslation: "They're coming back next month." },
      { korean: '총공', english: 'Mass streaming', pronunciation: 'chong-gong', example: '총공 시간이에요!', exampleTranslation: "It's time for mass streaming!" },
      { korean: '음원', english: 'Digital track', pronunciation: 'eum-won', example: '음원이 나왔어요.', exampleTranslation: 'The digital track is out.' },
      { korean: '떡밥', english: 'Teaser / Hint', pronunciation: 'tteok-bap', example: '떡밥이 나왔다!', exampleTranslation: 'A teaser dropped!' },
      { korean: '입덕', english: 'Becoming a fan', pronunciation: 'ip-deok', example: '이 영상 보고 입덕했어.', exampleTranslation: 'I became a fan after watching this.' },
      { korean: '덕질', english: 'Fan activities', pronunciation: 'deok-jil', example: '덕질이 행복해요.', exampleTranslation: 'Fan activities make me happy.' },
      { korean: '직캠', english: 'Fancam', pronunciation: 'jik-kaem', example: '직캠 조회수가 대박이야.', exampleTranslation: 'The fancam views are amazing.' },
      { korean: '팬싸', english: 'Fan sign event', pronunciation: 'paen-ssa', example: '팬싸에 당첨됐어!', exampleTranslation: 'I won the fan sign lottery!' },
      { korean: '멜론', english: 'Melon (music app)', pronunciation: 'mel-lon', example: '멜론 차트 1위!', exampleTranslation: 'Number 1 on Melon chart!' },
      { korean: '응원봉', english: 'Lightstick', pronunciation: 'eung-won-bong', example: '응원봉 색깔이 예뻐요.', exampleTranslation: 'The lightstick color is pretty.' },
      { korean: '포카', english: 'Photocard', pronunciation: 'po-ka', example: '포카 교환할 사람?', exampleTranslation: 'Anyone want to trade photocards?' },
      { korean: '앨범', english: 'Album', pronunciation: 'ael-beom', example: '새 앨범 샀어!', exampleTranslation: 'I bought the new album!' },
      { korean: '팬챈트', english: 'Fanchant', pronunciation: 'paen-chaen-teu', example: '팬챈트 연습했어요.', exampleTranslation: 'I practiced the fanchant.' },
      { korean: '콘서트', english: 'Concert', pronunciation: 'kon-seo-teu', example: '콘서트 티켓 구했어!', exampleTranslation: 'I got concert tickets!' },
      { korean: '음방', english: 'Music show', pronunciation: 'eum-bang', example: '오늘 음방 출연이래요.', exampleTranslation: 'They are appearing on the music show today.' },
      { korean: '1위', english: 'First place', pronunciation: 'il-wi', example: '1위 축하해요!', exampleTranslation: 'Congratulations on first place!' },
      { korean: '탈덕', english: 'Leaving a fandom', pronunciation: 'tal-deok', example: '탈덕하려고 했는데 못 했어.', exampleTranslation: 'I tried to leave the fandom but I could not.' },
      { korean: '올라운더', english: 'All-rounder', pronunciation: 'ol-la-un-deo', example: '진짜 올라운더야.', exampleTranslation: 'A true all-rounder.' },
      { korean: '안무', english: 'Choreography', pronunciation: 'an-mu', example: '이번 안무가 어렵대요.', exampleTranslation: 'They say this choreography is hard.' },
      { korean: '커버댄스', english: 'Cover dance', pronunciation: 'keo-beo-daen-seu', example: '커버댄스 영상 올렸어.', exampleTranslation: 'I uploaded a cover dance video.' },
      { korean: '예능', english: 'Variety show', pronunciation: 'ye-neung', example: '예능에 나왔어요!', exampleTranslation: 'They appeared on a variety show!' },
      { korean: '브이로그', english: 'Vlog', pronunciation: 'beu-i-ro-geu', example: '새 브이로그 올라왔다.', exampleTranslation: 'A new vlog was uploaded.' },
      { korean: '위버스', english: 'Weverse', pronunciation: 'wi-beo-seu', example: '위버스에 글 올렸어요.', exampleTranslation: 'They posted on Weverse.' },
      { korean: '셀카', english: 'Selfie', pronunciation: 'sel-ka', example: '셀카 올려 줘요!', exampleTranslation: 'Please post a selfie!' },
      { korean: '해시태그', english: 'Hashtag', pronunciation: 'hae-si-tae-geu', example: '해시태그 달아 주세요.', exampleTranslation: 'Please add the hashtag.' },
      { korean: '스밍', english: 'Streaming', pronunciation: 'seu-ming', example: '스밍 열심히 하자!', exampleTranslation: "Let's stream hard!" },
      { korean: '뮤비', english: 'Music video', pronunciation: 'myu-bi', example: '뮤비 조회수 1억 돌파!', exampleTranslation: 'MV surpassed 100 million views!' },
      { korean: '비하인드', english: 'Behind-the-scenes', pronunciation: 'bi-ha-in-deu', example: '비하인드 영상 봤어?', exampleTranslation: 'Did you watch the behind-the-scenes video?' },
      { korean: '티저', english: 'Teaser', pronunciation: 'ti-jeo', example: '티저 사진 공개됐어!', exampleTranslation: 'The teaser photo was released!' },
      { korean: '성덕', english: 'Successful fan (met their idol)', pronunciation: 'seong-deok', example: '드디어 성덕했어!', exampleTranslation: 'I finally became a successful fan!' },
      { korean: '떼창', english: 'Group singing along', pronunciation: 'tte-chang', example: '떼창이 소름 돋았어.', exampleTranslation: 'The group singalong gave me chills.' },
      { korean: '막방', english: 'Last broadcast / Final stage', pronunciation: 'mak-bang', example: '오늘이 막방이에요.', exampleTranslation: 'Today is the last broadcast.' },
      { korean: '본방사수', english: 'Watch the live broadcast', pronunciation: 'bon-bang-sa-su', example: '본방사수 해야 돼!', exampleTranslation: 'We have to watch the live broadcast!' },
      { korean: '개인기', english: 'Special talent / Party trick', pronunciation: 'gae-in-gi', example: '개인기가 너무 웃겨.', exampleTranslation: 'Their special talent is so funny.' },
    ],
  },
  {
    id: 'kfood',
    title: 'Korean Food & Dining',
    titleKr: '한식과 식사',
    icon: 'restaurant',
    color: '#FFE66D',
    description: 'Food vocabulary and ordering phrases',
    words: [
      { korean: '맛있게 드세요', english: 'Enjoy your meal', pronunciation: 'ma-sit-ge deu-se-yo', example: '맛있게 드세요!', exampleTranslation: 'Enjoy your meal!' },
      { korean: '잘 먹겠습니다', english: 'I will eat well (before eating)', pronunciation: 'jal meok-get-seum-ni-da', example: '잘 먹겠습니다!', exampleTranslation: 'Thank you for the food!' },
      { korean: '잘 먹었습니다', english: 'I ate well (after eating)', pronunciation: 'jal meog-eot-seum-ni-da', example: '잘 먹었습니다!', exampleTranslation: 'Thank you for the meal!' },
      { korean: '소주', english: 'Soju', pronunciation: 'so-ju', example: '소주 한 병 주세요.', exampleTranslation: 'One bottle of soju please.' },
      { korean: '삼겹살', english: 'Pork belly', pronunciation: 'sam-gyeop-sal', example: '삼겹살 먹으러 가자!', exampleTranslation: "Let's go eat pork belly!" },
      { korean: '반찬', english: 'Side dishes', pronunciation: 'ban-chan', example: '반찬 더 주세요.', exampleTranslation: 'More side dishes please.' },
      { korean: '매워요', english: "It's spicy", pronunciation: 'mae-wo-yo', example: '이거 너무 매워요!', exampleTranslation: 'This is too spicy!' },
      { korean: '배불러요', english: "I'm full", pronunciation: 'bae-bul-leo-yo', example: '배불러요, 더 못 먹어요.', exampleTranslation: "I'm full, I can't eat more." },
      { korean: '건배', english: 'Cheers!', pronunciation: 'geon-bae', example: '건배! 위하여!', exampleTranslation: 'Cheers! To us!' },
      { korean: '포장해 주세요', english: 'Please wrap it to go', pronunciation: 'po-jang-hae ju-se-yo', example: '이거 포장해 주세요.', exampleTranslation: 'Please wrap this to go.' },
      { korean: '떡볶이', english: 'Spicy rice cakes', pronunciation: 'tteok-bokk-i', example: '떡볶이 2인분 주세요.', exampleTranslation: 'Two servings of tteokbokki please.' },
      { korean: '비빔밥', english: 'Mixed rice', pronunciation: 'bi-bim-bap', example: '비빔밥 잘 비벼 드세요.', exampleTranslation: 'Mix the bibimbap well before eating.' },
      { korean: '찌개', english: 'Stew', pronunciation: 'jji-gae', example: '김치찌개가 맛있어요.', exampleTranslation: 'The kimchi stew is delicious.' },
      { korean: '김밥', english: 'Kimbap (seaweed rice roll)', pronunciation: 'gim-bap', example: '김밥 한 줄 주세요.', exampleTranslation: 'One roll of kimbap please.' },
      { korean: '라면', english: 'Ramen / Instant noodles', pronunciation: 'ra-myeon', example: '라면 먹을래?', exampleTranslation: 'Do you want to eat ramen?' },
      { korean: '치킨', english: 'Fried chicken', pronunciation: 'chi-kin', example: '치킨 배달시킬까?', exampleTranslation: 'Shall we order chicken delivery?' },
      { korean: '맥주', english: 'Beer', pronunciation: 'maek-ju', example: '치킨에는 맥주지!', exampleTranslation: 'Beer goes with chicken!' },
      { korean: '계산해 주세요', english: 'The bill please', pronunciation: 'gye-san-hae ju-se-yo', example: '계산해 주세요.', exampleTranslation: 'The bill please.' },
      { korean: '메뉴판', english: 'Menu', pronunciation: 'me-nyu-pan', example: '메뉴판 좀 볼게요.', exampleTranslation: 'Let me see the menu.' },
      { korean: '달아요', english: "It's sweet", pronunciation: 'dar-a-yo', example: '이 케이크 달아요.', exampleTranslation: 'This cake is sweet.' },
      { korean: '짜요', english: "It's salty", pronunciation: 'jja-yo', example: '국이 좀 짜요.', exampleTranslation: 'The soup is a bit salty.' },
      { korean: '싱거워요', english: "It's bland", pronunciation: 'sing-geo-wo-yo', example: '맛이 좀 싱거워요.', exampleTranslation: 'The flavor is a bit bland.' },
      { korean: '시장', english: 'Market', pronunciation: 'si-jang', example: '시장에서 장 봤어요.', exampleTranslation: 'I went grocery shopping at the market.' },
      { korean: '호떡', english: 'Sweet pancake', pronunciation: 'ho-tteok', example: '겨울에는 호떡이 최고야.', exampleTranslation: 'Hotteok is the best in winter.' },
      { korean: '붕어빵', english: 'Fish-shaped bread', pronunciation: 'bung-eo-ppang', example: '붕어빵 하나 주세요.', exampleTranslation: 'One bungeoppang please.' },
      { korean: '아메리카노', english: 'Americano', pronunciation: 'a-me-ri-ka-no', example: '아이스 아메리카노 한 잔 주세요.', exampleTranslation: 'One iced Americano please.' },
      { korean: '볶다', english: 'To stir-fry', pronunciation: 'bok-da', example: '야채를 먼저 볶으세요.', exampleTranslation: 'Stir-fry the vegetables first.' },
      { korean: '끓이다', english: 'To boil', pronunciation: 'kkeur-i-da', example: '물을 먼저 끓여 주세요.', exampleTranslation: 'Please boil the water first.' },
      { korean: '한 잔 더', english: 'One more glass', pronunciation: 'han jan deo', example: '소주 한 잔 더 할까요?', exampleTranslation: 'Shall we have one more glass of soju?' },
      { korean: '회식', english: 'Company dinner', pronunciation: 'hoe-sik', example: '오늘 회식이 있어요.', exampleTranslation: 'We have a company dinner today.' },
      { korean: '곱창', english: 'Intestines (grilled)', pronunciation: 'gop-chang', example: '곱창 맛집 아세요?', exampleTranslation: 'Do you know a good intestine restaurant?' },
      { korean: '냉면', english: 'Cold noodles', pronunciation: 'naeng-myeon', example: '여름에는 냉면이 최고야.', exampleTranslation: 'Cold noodles are the best in summer.' },
      { korean: '주문할게요', english: "I'd like to order", pronunciation: 'ju-mun-hal-ge-yo', example: '여기요, 주문할게요.', exampleTranslation: 'Excuse me, I would like to order.' },
      { korean: '얼마예요?', english: 'How much is it?', pronunciation: 'eol-ma-ye-yo', example: '이거 얼마예요?', exampleTranslation: 'How much is this?' },
      { korean: '배달', english: 'Delivery', pronunciation: 'bae-dal', example: '배달 시켜 먹자.', exampleTranslation: "Let's order delivery." },
    ],
  },
  {
    id: 'ktravel',
    title: 'Travel in Korea',
    titleKr: '한국 여행',
    icon: 'airplane',
    color: '#45B7D1',
    description: 'Essential phrases for traveling in Korea',
    words: [
      { korean: '여기 어디예요?', english: 'Where is this?', pronunciation: 'yeo-gi eo-di-ye-yo', example: '여기 어디예요? 길을 잃었어요.', exampleTranslation: "Where is this? I'm lost." },
      { korean: '화장실', english: 'Restroom', pronunciation: 'hwa-jang-sil', example: '화장실이 어디예요?', exampleTranslation: 'Where is the restroom?' },
      { korean: '지하철', english: 'Subway', pronunciation: 'ji-ha-cheol', example: '지하철역이 가까워요.', exampleTranslation: 'The subway station is close.' },
      { korean: '호텔', english: 'Hotel', pronunciation: 'ho-tel', example: '호텔 예약했어요.', exampleTranslation: 'I reserved a hotel.' },
      { korean: '관광지', english: 'Tourist spot', pronunciation: 'gwan-gwang-ji', example: '유명한 관광지예요.', exampleTranslation: "It's a famous tourist spot." },
      { korean: '환전', english: 'Currency exchange', pronunciation: 'hwan-jeon', example: '환전소가 어디예요?', exampleTranslation: 'Where is the currency exchange?' },
      { korean: '길을 잃었어요', english: "I'm lost", pronunciation: 'gir-eul il-eoss-eo-yo', example: '길을 잃었어요. 도와주세요.', exampleTranslation: "I'm lost. Please help me." },
      { korean: '사진 찍어 주세요', english: 'Please take a photo', pronunciation: 'sa-jin jjig-eo ju-se-yo', example: '사진 좀 찍어 주세요.', exampleTranslation: 'Could you take a photo please?' },
      { korean: '면세점', english: 'Duty-free shop', pronunciation: 'myeon-se-jeom', example: '면세점에서 쇼핑할 거예요.', exampleTranslation: "I'll shop at the duty-free." },
      { korean: '출구', english: 'Exit', pronunciation: 'chul-gu', example: '출구는 어디예요?', exampleTranslation: 'Where is the exit?' },
      { korean: '버스', english: 'Bus', pronunciation: 'beo-seu', example: '버스 정류장이 어디예요?', exampleTranslation: 'Where is the bus stop?' },
      { korean: '택시', english: 'Taxi', pronunciation: 'taek-si', example: '택시 타고 갈게요.', exampleTranslation: "I'll take a taxi." },
      { korean: 'KTX', english: 'KTX (high-speed train)', pronunciation: 'ke-i-ti-ek-seu', example: 'KTX로 부산까지 2시간이에요.', exampleTranslation: 'It is 2 hours to Busan by KTX.' },
      { korean: '게스트하우스', english: 'Guesthouse', pronunciation: 'ge-seu-teu-ha-u-seu', example: '게스트하우스에서 묵을 거예요.', exampleTranslation: "I'll stay at a guesthouse." },
      { korean: '깎아 주세요', english: 'Please give me a discount', pronunciation: 'kkakk-a ju-se-yo', example: '좀 깎아 주세요.', exampleTranslation: 'Please give me a discount.' },
      { korean: '도와주세요', english: 'Please help me', pronunciation: 'do-wa-ju-se-yo', example: '도와주세요! 급해요.', exampleTranslation: 'Please help me! It is urgent.' },
      { korean: '경찰서', english: 'Police station', pronunciation: 'gyeong-chal-seo', example: '가까운 경찰서가 어디예요?', exampleTranslation: 'Where is the nearest police station?' },
      { korean: '병원', english: 'Hospital', pronunciation: 'byeong-won', example: '병원에 가야 해요.', exampleTranslation: 'I need to go to the hospital.' },
      { korean: '오른쪽', english: 'Right side', pronunciation: 'o-reun-jjok', example: '오른쪽으로 가세요.', exampleTranslation: 'Go to the right.' },
      { korean: '왼쪽', english: 'Left side', pronunciation: 'oen-jjok', example: '왼쪽에 있어요.', exampleTranslation: 'It is on the left.' },
      { korean: '직진', english: 'Go straight', pronunciation: 'jik-jin', example: '직진하면 나와요.', exampleTranslation: 'Go straight and you will find it.' },
      { korean: '경복궁', english: 'Gyeongbokgung Palace', pronunciation: 'gyeong-bok-gung', example: '경복궁에 가 봤어요?', exampleTranslation: 'Have you been to Gyeongbokgung Palace?' },
      { korean: '명동', english: 'Myeongdong', pronunciation: 'myeong-dong', example: '명동에서 쇼핑할 거예요.', exampleTranslation: "I'll go shopping in Myeongdong." },
      { korean: '날씨', english: 'Weather', pronunciation: 'nal-ssi', example: '오늘 날씨가 좋아요.', exampleTranslation: 'The weather is nice today.' },
      { korean: '봄', english: 'Spring', pronunciation: 'bom', example: '봄에 벚꽃이 예뻐요.', exampleTranslation: 'Cherry blossoms are pretty in spring.' },
      { korean: '가을', english: 'Autumn', pronunciation: 'ga-eul', example: '가을 단풍이 아름다워요.', exampleTranslation: 'The autumn leaves are beautiful.' },
      { korean: '카드 돼요?', english: 'Do you accept cards?', pronunciation: 'ka-deu dwae-yo', example: '카드 돼요?', exampleTranslation: 'Do you accept cards?' },
      { korean: '현금', english: 'Cash', pronunciation: 'hyeon-geum', example: '현금으로 낼게요.', exampleTranslation: "I'll pay in cash." },
      { korean: '입장료', english: 'Admission fee', pronunciation: 'ip-jang-nyo', example: '입장료가 얼마예요?', exampleTranslation: 'How much is the admission fee?' },
      { korean: '한옥마을', english: 'Hanok Village', pronunciation: 'han-ok-ma-eul', example: '한옥마을에서 한복 입었어요.', exampleTranslation: 'I wore hanbok at Hanok Village.' },
      { korean: '편의점', english: 'Convenience store', pronunciation: 'pyeon-ui-jeom', example: '편의점이 근처에 있어요?', exampleTranslation: 'Is there a convenience store nearby?' },
      { korean: '짐', english: 'Luggage', pronunciation: 'jim', example: '짐을 맡길 수 있어요?', exampleTranslation: 'Can I leave my luggage?' },
      { korean: '예약', english: 'Reservation', pronunciation: 'ye-yak', example: '예약할 수 있어요?', exampleTranslation: 'Can I make a reservation?' },
      { korean: '와이파이', english: 'Wi-Fi', pronunciation: 'wa-i-pa-i', example: '와이파이 비밀번호가 뭐예요?', exampleTranslation: 'What is the Wi-Fi password?' },
      { korean: '공항', english: 'Airport', pronunciation: 'gong-hang', example: '공항까지 얼마나 걸려요?', exampleTranslation: 'How long does it take to the airport?' },
    ],
  },
  {
    id: 'kslang',
    title: 'Korean Internet Slang',
    titleKr: '인터넷 신조어',
    icon: 'phone-portrait',
    color: '#96CEB4',
    description: 'Modern slang used online & in daily life',
    words: [
      { korean: 'ㅋㅋㅋ', english: 'Haha (laughing)', pronunciation: 'keu-keu-keu', example: '진짜 웃기다 ㅋㅋㅋ', exampleTranslation: 'So funny haha.' },
      { korean: 'ㅎㅎ', english: 'Hehe (gentle laugh)', pronunciation: 'heu-heu', example: '귀엽다 ㅎㅎ', exampleTranslation: 'Cute hehe.' },
      { korean: '갑분싸', english: 'Sudden awkward silence', pronunciation: 'gap-bun-ssa', example: '갑분싸됐네...', exampleTranslation: 'It got awkward suddenly...' },
      { korean: '존맛', english: 'Super delicious', pronunciation: 'jon-mat', example: '이거 존맛이야!', exampleTranslation: 'This is super delicious!' },
      { korean: '꿀잼', english: 'So fun / Entertaining', pronunciation: 'kkul-jaem', example: '이 영화 꿀잼이야.', exampleTranslation: 'This movie is so fun.' },
      { korean: '노잼', english: 'Not fun / Boring', pronunciation: 'no-jaem', example: '완전 노잼이야.', exampleTranslation: 'Totally boring.' },
      { korean: '혼밥', english: 'Eating alone', pronunciation: 'hon-bap', example: '오늘 혼밥했어.', exampleTranslation: 'I ate alone today.' },
      { korean: '혼술', english: 'Drinking alone', pronunciation: 'hon-sul', example: '혼술 하는 중이야.', exampleTranslation: "I'm drinking alone." },
      { korean: '인싸', english: 'Popular person (insider)', pronunciation: 'in-ssa', example: '완전 인싸야!', exampleTranslation: 'Totally a social butterfly!' },
      { korean: '아싸', english: 'Loner (outsider)', pronunciation: 'a-ssa', example: '나는 아싸인데...', exampleTranslation: "I'm kind of a loner..." },
      { korean: 'ㄹㅇ', english: 'For real', pronunciation: 'ri-eol', example: 'ㄹㅇ 대박이야.', exampleTranslation: 'For real, that is amazing.' },
      { korean: 'ㅇㅇ', english: 'Yes / Yeah', pronunciation: 'eung-eung', example: 'ㅇㅇ 알겠어.', exampleTranslation: 'Yeah, got it.' },
      { korean: 'ㄴㄴ', english: 'No no', pronunciation: 'no-no', example: 'ㄴㄴ 그거 아니야.', exampleTranslation: 'No no, that is not it.' },
      { korean: 'ㅇㅈ', english: 'Agreed / Acknowledged', pronunciation: 'in-jeong', example: 'ㅇㅈ, 맞는 말이야.', exampleTranslation: 'Agreed, you are right.' },
      { korean: '대박', english: 'Amazing / Jackpot', pronunciation: 'dae-bak', example: '대박! 진짜야?', exampleTranslation: 'Amazing! Really?' },
      { korean: '헐', english: 'OMG / Whoa', pronunciation: 'heol', example: '헐, 믿을 수 없어.', exampleTranslation: 'OMG, I cannot believe it.' },
      { korean: '레전드', english: 'Legend / Legendary', pronunciation: 're-jeon-deu', example: '이건 레전드야.', exampleTranslation: 'This is legendary.' },
      { korean: '오지다', english: 'Intense / Awesome', pronunciation: 'o-ji-da', example: '이거 진짜 오진다.', exampleTranslation: 'This is really awesome.' },
      { korean: '극혐', english: 'Extreme disgust', pronunciation: 'geuk-hyeom', example: '벌레 극혐이야.', exampleTranslation: 'I absolutely hate bugs.' },
      { korean: '갓생', english: 'Living a productive life', pronunciation: 'gat-saeng', example: '오늘 갓생 살았다.', exampleTranslation: 'I lived a productive life today.' },
      { korean: '플렉스', english: 'Flex / Show off', pronunciation: 'peul-lek-seu', example: '오늘 플렉스 할 거야.', exampleTranslation: 'I am going to flex today.' },
      { korean: 'TMI', english: 'Too much information', pronunciation: 'ti-em-ai', example: 'TMI인데, 나 오늘 머리 감았어.', exampleTranslation: 'TMI, but I washed my hair today.' },
      { korean: '갈비', english: 'Worth it (cost-effective)', pronunciation: 'gal-bi', example: '가성비 좋다.', exampleTranslation: 'Good value for money.' },
      { korean: '넘사벽', english: 'Insurmountable wall', pronunciation: 'neom-sa-byeok', example: '실력이 넘사벽이야.', exampleTranslation: 'Their skill is on another level.' },
      { korean: '치이다', english: 'To be bombarded / Overwhelmed', pronunciation: 'chi-i-da', example: '일에 치여서 못 만나.', exampleTranslation: 'I am swamped with work so I cannot meet.' },
      { korean: 'GG', english: 'Good game / Give up', pronunciation: 'ji-ji', example: '이건 GG다.', exampleTranslation: 'This is game over.' },
      { korean: '버프', english: 'Buff / Boost', pronunciation: 'beo-peu', example: '오늘 컨디션 버프 받았어.', exampleTranslation: 'I got a condition buff today.' },
      { korean: '너프', english: 'Nerf / Weaken', pronunciation: 'neo-peu', example: '이번 패치에 너프됐어.', exampleTranslation: 'It got nerfed in this patch.' },
      { korean: '멘붕', english: 'Mental breakdown', pronunciation: 'men-bung', example: '시험 보고 멘붕 왔어.', exampleTranslation: 'I had a mental breakdown after the exam.' },
      { korean: '소확행', english: 'Small but certain happiness', pronunciation: 'so-hwak-haeng', example: '커피 한 잔이 소확행이야.', exampleTranslation: 'A cup of coffee is my small happiness.' },
      { korean: 'ㅠㅠ', english: 'Crying face', pronunciation: 'yu-yu', example: '너무 슬퍼 ㅠㅠ', exampleTranslation: 'So sad (crying).' },
      { korean: 'ㄷㄷ', english: 'Shivering / Shocked', pronunciation: 'deol-deol', example: '소름 ㄷㄷ', exampleTranslation: 'Goosebumps, so shocking.' },
      { korean: '찐', english: 'Real / Authentic', pronunciation: 'jjin', example: '찐 맛집이야.', exampleTranslation: 'It is an authentic great restaurant.' },
      { korean: '킹받다', english: 'To be extremely annoyed', pronunciation: 'king-bat-da', example: '진짜 킹받네.', exampleTranslation: 'That is so annoying.' },
      { korean: '갓', english: 'God-tier / Amazing', pronunciation: 'gat', example: '이 게임 갓겜이야.', exampleTranslation: 'This game is god-tier.' },
    ],
  },
  {
    id: 'kmanners',
    title: 'Korean Manners & Culture',
    titleKr: '한국 예절',
    icon: 'heart',
    color: '#FFEAA7',
    description: 'Cultural etiquette and polite expressions',
    words: [
      { korean: '수고하셨습니다', english: 'Thank you for your hard work', pronunciation: 'su-go-ha-syeot-seum-ni-da', example: '오늘도 수고하셨습니다.', exampleTranslation: 'Thank you for your hard work today.' },
      { korean: '실례합니다', english: 'Excuse me', pronunciation: 'sil-lye-ham-ni-da', example: '실례합니다, 지나갈게요.', exampleTranslation: 'Excuse me, let me pass.' },
      { korean: '덕분에', english: 'Thanks to you', pronunciation: 'deok-bun-e', example: '선생님 덕분에 합격했어요.', exampleTranslation: 'I passed thanks to you, teacher.' },
      { korean: '죄송합니다', english: "I'm sorry (formal)", pronunciation: 'joe-song-ham-ni-da', example: '늦어서 죄송합니다.', exampleTranslation: "I'm sorry for being late." },
      { korean: '잘 부탁드립니다', english: 'Please take care of me', pronunciation: 'jal bu-tak-deu-rim-ni-da', example: '앞으로 잘 부탁드립니다.', exampleTranslation: 'Please take care of me going forward.' },
      { korean: '어서 오세요', english: 'Welcome', pronunciation: 'eo-seo o-se-yo', example: '어서 오세요! 뭐 드실래요?', exampleTranslation: 'Welcome! What would you like?' },
      { korean: '안녕히 가세요', english: 'Goodbye (to someone leaving)', pronunciation: 'an-nyeong-hi ga-se-yo', example: '안녕히 가세요!', exampleTranslation: 'Goodbye!' },
      { korean: '안녕히 계세요', english: 'Goodbye (to someone staying)', pronunciation: 'an-nyeong-hi gye-se-yo', example: '안녕히 계세요!', exampleTranslation: 'Goodbye! (Stay well!)' },
      { korean: '존댓말', english: 'Formal/polite language', pronunciation: 'jon-daen-mal', example: '존댓말을 사용해 주세요.', exampleTranslation: 'Please use formal language.' },
      { korean: '반말', english: 'Informal language', pronunciation: 'ban-mal', example: '반말 해도 돼요?', exampleTranslation: 'Can I speak informally?' },
      { korean: '선배', english: 'Senior (school/work)', pronunciation: 'seon-bae', example: '선배님, 조언 감사합니다.', exampleTranslation: 'Senior, thank you for the advice.' },
      { korean: '후배', english: 'Junior (school/work)', pronunciation: 'hu-bae', example: '후배들을 잘 챙겨 줘.', exampleTranslation: 'Take good care of the juniors.' },
      { korean: '인사', english: 'Greeting / Bow', pronunciation: 'in-sa', example: '어른에게 인사하세요.', exampleTranslation: 'Greet the elders.' },
      { korean: '절', english: 'Deep bow', pronunciation: 'jeol', example: '설날에 어른들께 절해요.', exampleTranslation: 'We bow deeply to elders on New Year.' },
      { korean: '선물', english: 'Gift', pronunciation: 'seon-mul', example: '선물 준비했어요.', exampleTranslation: 'I prepared a gift.' },
      { korean: '두 손으로', english: 'With both hands', pronunciation: 'du son-eu-ro', example: '두 손으로 받으세요.', exampleTranslation: 'Please receive it with both hands.' },
      { korean: '회식', english: 'Team dinner / Company dinner', pronunciation: 'hoe-sik', example: '회식에 참석해야 해요.', exampleTranslation: 'I have to attend the company dinner.' },
      { korean: '야근', english: 'Overtime work', pronunciation: 'ya-geun', example: '오늘 야근이에요.', exampleTranslation: 'I have overtime today.' },
      { korean: '동기', english: 'Same-year colleague', pronunciation: 'dong-gi', example: '동기끼리 친해요.', exampleTranslation: 'Colleagues of the same year are close.' },
      { korean: '추석', english: 'Chuseok (Korean Thanksgiving)', pronunciation: 'chu-seok', example: '추석 잘 보내세요.', exampleTranslation: 'Have a great Chuseok.' },
      { korean: '설날', english: 'Seollal (Lunar New Year)', pronunciation: 'seol-nal', example: '설날에 세배해요.', exampleTranslation: 'We do the New Year bow on Seollal.' },
      { korean: '세배', english: 'New Year bow', pronunciation: 'se-bae', example: '할머니께 세배 드렸어요.', exampleTranslation: 'I did the New Year bow to grandmother.' },
      { korean: '세뱃돈', english: 'New Year money', pronunciation: 'se-baet-don', example: '세뱃돈 많이 받았어?', exampleTranslation: 'Did you get a lot of New Year money?' },
      { korean: '할머니', english: 'Grandmother', pronunciation: 'hal-meo-ni', example: '할머니, 건강하세요.', exampleTranslation: 'Grandmother, stay healthy.' },
      { korean: '할아버지', english: 'Grandfather', pronunciation: 'har-a-beo-ji', example: '할아버지가 이야기해 주셨어요.', exampleTranslation: 'Grandfather told me a story.' },
      { korean: '이모', english: 'Aunt (mother side) / Lady at restaurant', pronunciation: 'i-mo', example: '이모, 여기 물 주세요.', exampleTranslation: 'Excuse me, water please.' },
      { korean: '아저씨', english: 'Uncle / Middle-aged man', pronunciation: 'a-jeo-ssi', example: '아저씨, 감사합니다.', exampleTranslation: 'Thank you, sir.' },
      { korean: '안녕하세요', english: 'Hello (polite)', pronunciation: 'an-nyeong-ha-se-yo', example: '이웃에게 안녕하세요 인사해요.', exampleTranslation: 'I greet my neighbors with hello.' },
      { korean: '먼저 드세요', english: 'Please eat first (to elders)', pronunciation: 'meon-jeo deu-se-yo', example: '어른이 먼저 드세요.', exampleTranslation: 'The elder eats first.' },
      { korean: '자리 양보', english: 'Giving up your seat', pronunciation: 'ja-ri yang-bo', example: '어르신에게 자리 양보했어요.', exampleTranslation: 'I gave up my seat to an elderly person.' },
      { korean: '감사합니다', english: 'Thank you (formal)', pronunciation: 'gam-sa-ham-ni-da', example: '도와주셔서 감사합니다.', exampleTranslation: 'Thank you for helping me.' },
      { korean: '새해 복 많이 받으세요', english: 'Happy New Year', pronunciation: 'sae-hae bok man-i bad-eu-se-yo', example: '새해 복 많이 받으세요!', exampleTranslation: 'Happy New Year!' },
      { korean: '고생했어', english: 'You worked hard (informal)', pronunciation: 'go-saeng-haess-eo', example: '오늘 고생했어.', exampleTranslation: 'You worked hard today.' },
      { korean: '눈치', english: 'Social awareness / Reading the room', pronunciation: 'nun-chi', example: '눈치가 빨라야 해요.', exampleTranslation: 'You need to be quick at reading the room.' },
      { korean: '정', english: 'Affection / Emotional bond', pronunciation: 'jeong', example: '정이 많은 사람이에요.', exampleTranslation: 'They are a person full of affection.' },
    ],
  },
];
