export interface Word {
  id: string;
  korean: string;
  english: string;
  pronunciation: string;
  partOfSpeech: string;
  example: string;
  exampleTranslation: string;
  category: string;
}

export interface TopikLevel {
  id: string;
  level: string;
  sublevel: string;
  title: string;
  description: string;
  color: string;
  days: string;
}

export const TOPIK_LEVELS: TopikLevel[] = [
  { id: 'topik1-1', level: 'TOPIK I', sublevel: 'Level 1', title: 'Complete Beginner', description: 'Hangeul basics, greetings, numbers, daily essentials', color: '#4ECDC4', days: 'Days 1-30' },
  { id: 'topik1-2', level: 'TOPIK I', sublevel: 'Level 2', title: 'Elementary', description: 'Daily conversations, shopping, K-pop vocabulary', color: '#45B7D1', days: 'Days 31-60' },
  { id: 'topik2-3', level: 'TOPIK II', sublevel: 'Level 3', title: 'Pre-Intermediate', description: 'Social topics, K-drama expressions, travel', color: '#96CEB4', days: 'Days 61-90' },
  { id: 'topik2-4', level: 'TOPIK II', sublevel: 'Level 4', title: 'Intermediate', description: 'News, culture, formal Korean, business', color: '#FFEAA7', days: 'Days 91-120' },
  { id: 'topik2-5', level: 'TOPIK II', sublevel: 'Level 5', title: 'Upper Intermediate', description: 'Literature, media, abstract thinking, advanced grammar', color: '#FF8A65', days: 'Days 121-150' },
  { id: 'topik2-6', level: 'TOPIK II', sublevel: 'Level 6', title: 'Advanced', description: 'Academic writing, professional Korean, formal expressions', color: '#CE93D8', days: 'Days 151-180' },
];

const VOCABULARY_DATA: Record<string, Word[]> = {
  'topik1-1': [
    { id: '1-1', korean: '안녕하세요', english: 'Hello', pronunciation: 'an-nyeong-ha-se-yo', partOfSpeech: 'greeting', example: '안녕하세요, 만나서 반갑습니다.', exampleTranslation: 'Hello, nice to meet you.', category: 'Greetings' },
    { id: '1-2', korean: '감사합니다', english: 'Thank you', pronunciation: 'gam-sa-ham-ni-da', partOfSpeech: 'greeting', example: '도와주셔서 감사합니다.', exampleTranslation: 'Thank you for helping me.', category: 'Greetings' },
    { id: '1-3', korean: '네', english: 'Yes', pronunciation: 'ne', partOfSpeech: 'adverb', example: '네, 알겠습니다.', exampleTranslation: 'Yes, I understand.', category: 'Basics' },
    { id: '1-4', korean: '아니요', english: 'No', pronunciation: 'a-ni-yo', partOfSpeech: 'adverb', example: '아니요, 괜찮습니다.', exampleTranslation: 'No, it\'s okay.', category: 'Basics' },
    { id: '1-5', korean: '사랑', english: 'Love', pronunciation: 'sa-rang', partOfSpeech: 'noun', example: '사랑은 아름답습니다.', exampleTranslation: 'Love is beautiful.', category: 'Emotions' },
    { id: '1-6', korean: '물', english: 'Water', pronunciation: 'mul', partOfSpeech: 'noun', example: '물 한 잔 주세요.', exampleTranslation: 'Please give me a glass of water.', category: 'Food & Drink' },
    { id: '1-7', korean: '밥', english: 'Rice / Meal', pronunciation: 'bap', partOfSpeech: 'noun', example: '밥 먹었어요?', exampleTranslation: 'Have you eaten?', category: 'Food & Drink' },
    { id: '1-8', korean: '집', english: 'House / Home', pronunciation: 'jip', partOfSpeech: 'noun', example: '집에 가고 싶어요.', exampleTranslation: 'I want to go home.', category: 'Places' },
    { id: '1-9', korean: '학교', english: 'School', pronunciation: 'hak-gyo', partOfSpeech: 'noun', example: '학교에 갑니다.', exampleTranslation: 'I go to school.', category: 'Places' },
    { id: '1-10', korean: '친구', english: 'Friend', pronunciation: 'chin-gu', partOfSpeech: 'noun', example: '친구와 만났어요.', exampleTranslation: 'I met my friend.', category: 'People' },
    { id: '1-11', korean: '가족', english: 'Family', pronunciation: 'ga-jok', partOfSpeech: 'noun', example: '가족이 보고 싶어요.', exampleTranslation: 'I miss my family.', category: 'People' },
    { id: '1-12', korean: '하나', english: 'One', pronunciation: 'ha-na', partOfSpeech: 'number', example: '하나만 주세요.', exampleTranslation: 'Just give me one please.', category: 'Numbers' },
    { id: '1-13', korean: '둘', english: 'Two', pronunciation: 'dul', partOfSpeech: 'number', example: '둘이 함께 갔어요.', exampleTranslation: 'Two went together.', category: 'Numbers' },
    { id: '1-14', korean: '좋아요', english: 'I like it / Good', pronunciation: 'jo-a-yo', partOfSpeech: 'adjective', example: '이 노래 좋아요.', exampleTranslation: 'I like this song.', category: 'Emotions' },
    { id: '1-15', korean: '먹다', english: 'To eat', pronunciation: 'meok-da', partOfSpeech: 'verb', example: '같이 먹을까요?', exampleTranslation: 'Shall we eat together?', category: 'Actions' },
    { id: '1-16', korean: '가다', english: 'To go', pronunciation: 'ga-da', partOfSpeech: 'verb', example: '어디 가요?', exampleTranslation: 'Where are you going?', category: 'Actions' },
    { id: '1-17', korean: '오다', english: 'To come', pronunciation: 'o-da', partOfSpeech: 'verb', example: '여기로 오세요.', exampleTranslation: 'Please come here.', category: 'Actions' },
    { id: '1-18', korean: '이름', english: 'Name', pronunciation: 'i-reum', partOfSpeech: 'noun', example: '이름이 뭐예요?', exampleTranslation: 'What is your name?', category: 'Basics' },
    { id: '1-19', korean: '나라', english: 'Country', pronunciation: 'na-ra', partOfSpeech: 'noun', example: '어느 나라에서 왔어요?', exampleTranslation: 'Which country are you from?', category: 'Basics' },
    { id: '1-20', korean: '오늘', english: 'Today', pronunciation: 'o-neul', partOfSpeech: 'adverb', example: '오늘 날씨가 좋아요.', exampleTranslation: 'The weather is nice today.', category: 'Time' },
    { id: '1-21', korean: '내일', english: 'Tomorrow', pronunciation: 'nae-il', partOfSpeech: 'adverb', example: '내일 만나요.', exampleTranslation: 'See you tomorrow.', category: 'Time' },
    { id: '1-22', korean: '어제', english: 'Yesterday', pronunciation: 'eo-je', partOfSpeech: 'adverb', example: '어제 뭐 했어요?', exampleTranslation: 'What did you do yesterday?', category: 'Time' },
    { id: '1-23', korean: '사람', english: 'Person / People', pronunciation: 'sa-ram', partOfSpeech: 'noun', example: '좋은 사람이에요.', exampleTranslation: 'You are a good person.', category: 'People' },
    { id: '1-24', korean: '음식', english: 'Food', pronunciation: 'eum-sik', partOfSpeech: 'noun', example: '한국 음식을 좋아해요.', exampleTranslation: 'I like Korean food.', category: 'Food & Drink' },
    { id: '1-25', korean: '커피', english: 'Coffee', pronunciation: 'keo-pi', partOfSpeech: 'noun', example: '커피 마실래요?', exampleTranslation: 'Would you like coffee?', category: 'Food & Drink' },
    { id: '1-26', korean: '보다', english: 'To see / To watch', pronunciation: 'bo-da', partOfSpeech: 'verb', example: '영화를 봤어요.', exampleTranslation: 'I watched a movie.', category: 'Actions' },
    { id: '1-27', korean: '읽다', english: 'To read', pronunciation: 'ik-da', partOfSpeech: 'verb', example: '책을 읽어요.', exampleTranslation: 'I read a book.', category: 'Actions' },
    { id: '1-28', korean: '쓰다', english: 'To write', pronunciation: 'sseu-da', partOfSpeech: 'verb', example: '편지를 써요.', exampleTranslation: 'I write a letter.', category: 'Actions' },
    { id: '1-29', korean: '듣다', english: 'To listen / To hear', pronunciation: 'deut-da', partOfSpeech: 'verb', example: '음악을 들어요.', exampleTranslation: 'I listen to music.', category: 'Actions' },
    { id: '1-30', korean: '말하다', english: 'To speak / To say', pronunciation: 'mal-ha-da', partOfSpeech: 'verb', example: '한국어로 말해 주세요.', exampleTranslation: 'Please speak in Korean.', category: 'Actions' },
    { id: '1-31', korean: '공부하다', english: 'To study', pronunciation: 'gong-bu-ha-da', partOfSpeech: 'verb', example: '한국어를 공부해요.', exampleTranslation: 'I study Korean.', category: 'Actions' },
    { id: '1-32', korean: '일하다', english: 'To work', pronunciation: 'il-ha-da', partOfSpeech: 'verb', example: '회사에서 일해요.', exampleTranslation: 'I work at a company.', category: 'Actions' },
    { id: '1-33', korean: '자다', english: 'To sleep', pronunciation: 'ja-da', partOfSpeech: 'verb', example: '일찍 자요.', exampleTranslation: 'I sleep early.', category: 'Actions' },
    { id: '1-34', korean: '크다', english: 'Big / Large', pronunciation: 'keu-da', partOfSpeech: 'adjective', example: '이 집은 커요.', exampleTranslation: 'This house is big.', category: 'Descriptions' },
    { id: '1-35', korean: '작다', english: 'Small / Little', pronunciation: 'jak-da', partOfSpeech: 'adjective', example: '이 가방은 작아요.', exampleTranslation: 'This bag is small.', category: 'Descriptions' },
    { id: '1-36', korean: '많다', english: 'Many / Much', pronunciation: 'man-ta', partOfSpeech: 'adjective', example: '사람이 많아요.', exampleTranslation: 'There are many people.', category: 'Descriptions' },
    { id: '1-37', korean: '예쁘다', english: 'Pretty / Beautiful', pronunciation: 'ye-ppeu-da', partOfSpeech: 'adjective', example: '꽃이 예뻐요.', exampleTranslation: 'The flower is pretty.', category: 'Descriptions' },
    { id: '1-38', korean: '맛있다', english: 'Delicious', pronunciation: 'ma-sit-da', partOfSpeech: 'adjective', example: '이 음식 맛있어요!', exampleTranslation: 'This food is delicious!', category: 'Descriptions' },
    { id: '1-39', korean: '재미있다', english: 'Fun / Interesting', pronunciation: 'jae-mi-it-da', partOfSpeech: 'adjective', example: '이 영화 재미있어요.', exampleTranslation: 'This movie is fun.', category: 'Descriptions' },
    { id: '1-40', korean: '날씨', english: 'Weather', pronunciation: 'nal-ssi', partOfSpeech: 'noun', example: '오늘 날씨가 좋아요.', exampleTranslation: 'The weather is nice today.', category: 'Nature' },
    { id: '1-41', korean: '시간', english: 'Time', pronunciation: 'si-gan', partOfSpeech: 'noun', example: '시간이 없어요.', exampleTranslation: 'I don\'t have time.', category: 'Time' },
    { id: '1-42', korean: '돈', english: 'Money', pronunciation: 'don', partOfSpeech: 'noun', example: '돈이 얼마예요?', exampleTranslation: 'How much money is it?', category: 'Daily Life' },
    { id: '1-43', korean: '전화', english: 'Phone call', pronunciation: 'jeon-hwa', partOfSpeech: 'noun', example: '전화 받으세요.', exampleTranslation: 'Please answer the phone.', category: 'Daily Life' },
    { id: '1-44', korean: '버스', english: 'Bus', pronunciation: 'beo-seu', partOfSpeech: 'noun', example: '버스를 타요.', exampleTranslation: 'I take the bus.', category: 'Transportation' },
    { id: '1-45', korean: '역', english: 'Station', pronunciation: 'yeok', partOfSpeech: 'noun', example: '지하철역이 어디예요?', exampleTranslation: 'Where is the subway station?', category: 'Transportation' },
    { id: '1-46', korean: '병원', english: 'Hospital', pronunciation: 'byeong-won', partOfSpeech: 'noun', example: '병원에 가야 해요.', exampleTranslation: 'I need to go to the hospital.', category: 'Places' },
    { id: '1-47', korean: '은행', english: 'Bank', pronunciation: 'eun-haeng', partOfSpeech: 'noun', example: '은행에서 돈을 찾아요.', exampleTranslation: 'I withdraw money from the bank.', category: 'Places' },
    { id: '1-48', korean: '마트', english: 'Mart / Supermarket', pronunciation: 'ma-teu', partOfSpeech: 'noun', example: '마트에서 쇼핑해요.', exampleTranslation: 'I shop at the mart.', category: 'Places' },
    { id: '1-49', korean: '주말', english: 'Weekend', pronunciation: 'ju-mal', partOfSpeech: 'noun', example: '주말에 뭐 해요?', exampleTranslation: 'What do you do on weekends?', category: 'Time' },
    { id: '1-50', korean: '여행', english: 'Travel / Trip', pronunciation: 'yeo-haeng', partOfSpeech: 'noun', example: '한국 여행을 가고 싶어요.', exampleTranslation: 'I want to travel to Korea.', category: 'Activities' },
    { id: '1-51', korean: '생일', english: 'Birthday', pronunciation: 'saeng-il', partOfSpeech: 'noun', example: '생일 축하합니다!', exampleTranslation: 'Happy birthday!', category: 'Events' },
    { id: '1-52', korean: '선물', english: 'Gift / Present', pronunciation: 'seon-mul', partOfSpeech: 'noun', example: '선물을 받았어요.', exampleTranslation: 'I received a gift.', category: 'Events' },
    { id: '1-53', korean: '운동', english: 'Exercise / Sports', pronunciation: 'un-dong', partOfSpeech: 'noun', example: '매일 운동해요.', exampleTranslation: 'I exercise every day.', category: 'Activities' },
    { id: '1-54', korean: '노래', english: 'Song', pronunciation: 'no-rae', partOfSpeech: 'noun', example: '이 노래 알아요?', exampleTranslation: 'Do you know this song?', category: 'K-Culture' },
    { id: '1-55', korean: '드라마', english: 'Drama (TV)', pronunciation: 'deu-ra-ma', partOfSpeech: 'noun', example: '한국 드라마를 좋아해요.', exampleTranslation: 'I like Korean dramas.', category: 'K-Culture' },
    { id: '1-56', korean: '아이돌', english: 'Idol (K-pop)', pronunciation: 'a-i-dol', partOfSpeech: 'noun', example: '좋아하는 아이돌이 있어요?', exampleTranslation: 'Do you have a favorite idol?', category: 'K-Culture' },
    { id: '1-57', korean: '화이팅', english: 'Fighting! (encouragement)', pronunciation: 'hwa-i-ting', partOfSpeech: 'exclamation', example: '시험 화이팅!', exampleTranslation: 'Good luck on your exam!', category: 'K-Culture' },
    { id: '1-58', korean: '대박', english: 'Amazing! / Jackpot', pronunciation: 'dae-bak', partOfSpeech: 'exclamation', example: '이거 대박이야!', exampleTranslation: 'This is amazing!', category: 'K-Culture' },
    { id: '1-59', korean: '아파요', english: 'It hurts / I\'m sick', pronunciation: 'a-pa-yo', partOfSpeech: 'adjective', example: '머리가 아파요.', exampleTranslation: 'I have a headache.', category: 'Health' },
    { id: '1-60', korean: '행복하다', english: 'To be happy', pronunciation: 'haeng-bok-ha-da', partOfSpeech: 'adjective', example: '오늘 행복해요.', exampleTranslation: 'I\'m happy today.', category: 'Emotions' },
  ],
  'topik1-2': [
    { id: '2-1', korean: '주문하다', english: 'To order', pronunciation: 'ju-mun-ha-da', partOfSpeech: 'verb', example: '커피 한 잔 주문할게요.', exampleTranslation: 'I\'ll order one cup of coffee.', category: 'Shopping' },
    { id: '2-2', korean: '얼마예요', english: 'How much is it?', pronunciation: 'eol-ma-ye-yo', partOfSpeech: 'phrase', example: '이거 얼마예요?', exampleTranslation: 'How much is this?', category: 'Shopping' },
    { id: '2-3', korean: '계산하다', english: 'To pay / Calculate', pronunciation: 'gye-san-ha-da', partOfSpeech: 'verb', example: '여기서 계산할게요.', exampleTranslation: 'I\'ll pay here.', category: 'Shopping' },
    { id: '2-4', korean: '비싸다', english: 'Expensive', pronunciation: 'bi-ssa-da', partOfSpeech: 'adjective', example: '너무 비싸요.', exampleTranslation: 'It\'s too expensive.', category: 'Shopping' },
    { id: '2-5', korean: '싸다', english: 'Cheap / Inexpensive', pronunciation: 'ssa-da', partOfSpeech: 'adjective', example: '여기가 더 싸요.', exampleTranslation: 'It\'s cheaper here.', category: 'Shopping' },
    { id: '2-6', korean: '약속', english: 'Promise / Appointment', pronunciation: 'yak-sok', partOfSpeech: 'noun', example: '내일 약속이 있어요.', exampleTranslation: 'I have an appointment tomorrow.', category: 'Daily Life' },
    { id: '2-7', korean: '기다리다', english: 'To wait', pronunciation: 'gi-da-ri-da', partOfSpeech: 'verb', example: '잠깐만 기다려 주세요.', exampleTranslation: 'Please wait a moment.', category: 'Actions' },
    { id: '2-8', korean: '찾다', english: 'To find / To look for', pronunciation: 'chat-da', partOfSpeech: 'verb', example: '화장실을 찾고 있어요.', exampleTranslation: 'I\'m looking for the restroom.', category: 'Actions' },
    { id: '2-9', korean: '알다', english: 'To know', pronunciation: 'al-da', partOfSpeech: 'verb', example: '이 노래 알아요?', exampleTranslation: 'Do you know this song?', category: 'Actions' },
    { id: '2-10', korean: '모르다', english: 'To not know', pronunciation: 'mo-reu-da', partOfSpeech: 'verb', example: '잘 모르겠어요.', exampleTranslation: 'I\'m not sure.', category: 'Actions' },
    { id: '2-11', korean: '축하하다', english: 'To congratulate', pronunciation: 'chuk-ha-ha-da', partOfSpeech: 'verb', example: '결혼 축하해요!', exampleTranslation: 'Congratulations on your wedding!', category: 'Social' },
    { id: '2-12', korean: '초대하다', english: 'To invite', pronunciation: 'cho-dae-ha-da', partOfSpeech: 'verb', example: '파티에 초대할게요.', exampleTranslation: 'I\'ll invite you to the party.', category: 'Social' },
    { id: '2-13', korean: '걱정하다', english: 'To worry', pronunciation: 'geok-jeong-ha-da', partOfSpeech: 'verb', example: '걱정하지 마세요.', exampleTranslation: 'Don\'t worry.', category: 'Emotions' },
    { id: '2-14', korean: '실망하다', english: 'To be disappointed', pronunciation: 'sil-mang-ha-da', partOfSpeech: 'verb', example: '실망하지 마세요.', exampleTranslation: 'Don\'t be disappointed.', category: 'Emotions' },
    { id: '2-15', korean: '설레다', english: 'To be excited / Flutter', pronunciation: 'seol-le-da', partOfSpeech: 'verb', example: '마음이 설레요.', exampleTranslation: 'My heart is fluttering.', category: 'K-Culture' },
    { id: '2-16', korean: '멋있다', english: 'Cool / Handsome', pronunciation: 'meot-it-da', partOfSpeech: 'adjective', example: '오빠 진짜 멋있어!', exampleTranslation: 'Oppa, you\'re really cool!', category: 'K-Culture' },
    { id: '2-17', korean: '귀엽다', english: 'Cute', pronunciation: 'gwi-yeop-da', partOfSpeech: 'adjective', example: '정말 귀여워요!', exampleTranslation: 'So cute!', category: 'K-Culture' },
    { id: '2-18', korean: '오빠', english: 'Older brother (female speaker)', pronunciation: 'o-ppa', partOfSpeech: 'noun', example: '오빠, 어디 가요?', exampleTranslation: 'Oppa, where are you going?', category: 'K-Culture' },
    { id: '2-19', korean: '언니', english: 'Older sister (female speaker)', pronunciation: 'eon-ni', partOfSpeech: 'noun', example: '언니, 같이 가요.', exampleTranslation: 'Unnie, let\'s go together.', category: 'K-Culture' },
    { id: '2-20', korean: '선배', english: 'Senior (school/work)', pronunciation: 'seon-bae', partOfSpeech: 'noun', example: '선배님, 감사합니다.', exampleTranslation: 'Thank you, sunbae.', category: 'K-Culture' },
    { id: '2-21', korean: '후배', english: 'Junior (school/work)', pronunciation: 'hu-bae', partOfSpeech: 'noun', example: '후배를 도와주세요.', exampleTranslation: 'Please help the junior.', category: 'K-Culture' },
    { id: '2-22', korean: '치킨', english: 'Fried chicken', pronunciation: 'chi-kin', partOfSpeech: 'noun', example: '치킨 시킬까요?', exampleTranslation: 'Shall we order chicken?', category: 'K-Food' },
    { id: '2-23', korean: '떡볶이', english: 'Spicy rice cakes', pronunciation: 'tteok-bok-ki', partOfSpeech: 'noun', example: '떡볶이 좋아해요?', exampleTranslation: 'Do you like tteokbokki?', category: 'K-Food' },
    { id: '2-24', korean: '김치', english: 'Kimchi', pronunciation: 'gim-chi', partOfSpeech: 'noun', example: '김치 맛있어요.', exampleTranslation: 'Kimchi is delicious.', category: 'K-Food' },
    { id: '2-25', korean: '불고기', english: 'Bulgogi (grilled meat)', pronunciation: 'bul-go-gi', partOfSpeech: 'noun', example: '불고기 먹어 봤어요?', exampleTranslation: 'Have you tried bulgogi?', category: 'K-Food' },
    { id: '2-26', korean: '비빔밥', english: 'Bibimbap (mixed rice)', pronunciation: 'bi-bim-bap', partOfSpeech: 'noun', example: '비빔밥 하나 주세요.', exampleTranslation: 'One bibimbap please.', category: 'K-Food' },
    { id: '2-27', korean: '노래방', english: 'Karaoke room', pronunciation: 'no-rae-bang', partOfSpeech: 'noun', example: '노래방 가자!', exampleTranslation: 'Let\'s go to karaoke!', category: 'K-Culture' },
    { id: '2-28', korean: '편의점', english: 'Convenience store', pronunciation: 'pyeon-ui-jeom', partOfSpeech: 'noun', example: '편의점에서 사요.', exampleTranslation: 'I buy it at the convenience store.', category: 'Places' },
    { id: '2-29', korean: '카페', english: 'Cafe', pronunciation: 'ka-pe', partOfSpeech: 'noun', example: '카페에서 만나요.', exampleTranslation: 'Let\'s meet at the cafe.', category: 'Places' },
    { id: '2-30', korean: '지하철', english: 'Subway', pronunciation: 'ji-ha-cheol', partOfSpeech: 'noun', example: '지하철로 가요.', exampleTranslation: 'I go by subway.', category: 'Transportation' },
    { id: '2-31', korean: '택시', english: 'Taxi', pronunciation: 'taek-si', partOfSpeech: 'noun', example: '택시를 탈까요?', exampleTranslation: 'Shall we take a taxi?', category: 'Transportation' },
    { id: '2-32', korean: '비행기', english: 'Airplane', pronunciation: 'bi-haeng-gi', partOfSpeech: 'noun', example: '비행기로 가요.', exampleTranslation: 'I go by airplane.', category: 'Transportation' },
    { id: '2-33', korean: '여름', english: 'Summer', pronunciation: 'yeo-reum', partOfSpeech: 'noun', example: '여름에 한국에 갈 거예요.', exampleTranslation: 'I\'m going to Korea in summer.', category: 'Seasons' },
    { id: '2-34', korean: '겨울', english: 'Winter', pronunciation: 'gyeo-ul', partOfSpeech: 'noun', example: '겨울에 눈이 와요.', exampleTranslation: 'It snows in winter.', category: 'Seasons' },
    { id: '2-35', korean: '봄', english: 'Spring', pronunciation: 'bom', partOfSpeech: 'noun', example: '봄에 벚꽃이 예뻐요.', exampleTranslation: 'Cherry blossoms are pretty in spring.', category: 'Seasons' },
    { id: '2-36', korean: '가을', english: 'Autumn / Fall', pronunciation: 'ga-eul', partOfSpeech: 'noun', example: '가을 단풍이 아름다워요.', exampleTranslation: 'Autumn leaves are beautiful.', category: 'Seasons' },
    { id: '2-37', korean: '사진', english: 'Photo / Picture', pronunciation: 'sa-jin', partOfSpeech: 'noun', example: '사진 찍어 주세요.', exampleTranslation: 'Please take a photo.', category: 'Daily Life' },
    { id: '2-38', korean: '영화', english: 'Movie / Film', pronunciation: 'yeong-hwa', partOfSpeech: 'noun', example: '영화 보러 갈래요?', exampleTranslation: 'Do you want to go see a movie?', category: 'Entertainment' },
    { id: '2-39', korean: '게임', english: 'Game', pronunciation: 'ge-im', partOfSpeech: 'noun', example: '게임 같이 할래요?', exampleTranslation: 'Want to play a game together?', category: 'Entertainment' },
    { id: '2-40', korean: '피곤하다', english: 'To be tired', pronunciation: 'pi-gon-ha-da', partOfSpeech: 'adjective', example: '오늘 너무 피곤해요.', exampleTranslation: 'I\'m so tired today.', category: 'Emotions' },
    { id: '2-41', korean: '비', english: 'Rain', pronunciation: 'bi', partOfSpeech: 'noun', example: '오늘 비가 와요.', exampleTranslation: 'It\'s raining today.', category: 'Weather' },
    { id: '2-42', korean: '눈', english: 'Snow / Eye', pronunciation: 'nun', partOfSpeech: 'noun', example: '밖에 눈이 와요.', exampleTranslation: 'It\'s snowing outside.', category: 'Weather' },
    { id: '2-43', korean: '덥다', english: 'Hot (weather)', pronunciation: 'deop-da', partOfSpeech: 'adjective', example: '오늘 너무 더워요.', exampleTranslation: 'It\'s so hot today.', category: 'Weather' },
    { id: '2-44', korean: '춥다', english: 'Cold (weather)', pronunciation: 'chup-da', partOfSpeech: 'adjective', example: '겨울에 많이 추워요.', exampleTranslation: 'It\'s very cold in winter.', category: 'Weather' },
    { id: '2-45', korean: '머리', english: 'Head / Hair', pronunciation: 'meo-ri', partOfSpeech: 'noun', example: '머리가 아파요.', exampleTranslation: 'My head hurts.', category: 'Body' },
    { id: '2-46', korean: '손', english: 'Hand', pronunciation: 'son', partOfSpeech: 'noun', example: '손을 씻으세요.', exampleTranslation: 'Please wash your hands.', category: 'Body' },
    { id: '2-47', korean: '발', english: 'Foot', pronunciation: 'bal', partOfSpeech: 'noun', example: '발이 아파요.', exampleTranslation: 'My foot hurts.', category: 'Body' },
    { id: '2-48', korean: '옷', english: 'Clothes', pronunciation: 'ot', partOfSpeech: 'noun', example: '새 옷을 샀어요.', exampleTranslation: 'I bought new clothes.', category: 'Clothing' },
    { id: '2-49', korean: '신발', english: 'Shoes', pronunciation: 'sin-bal', partOfSpeech: 'noun', example: '신발을 벗어 주세요.', exampleTranslation: 'Please take off your shoes.', category: 'Clothing' },
    { id: '2-50', korean: '모자', english: 'Hat / Cap', pronunciation: 'mo-ja', partOfSpeech: 'noun', example: '모자를 쓰세요.', exampleTranslation: 'Please wear a hat.', category: 'Clothing' },
    { id: '2-51', korean: '오른쪽', english: 'Right side', pronunciation: 'o-reun-jjok', partOfSpeech: 'noun', example: '오른쪽으로 가세요.', exampleTranslation: 'Please go to the right.', category: 'Directions' },
    { id: '2-52', korean: '왼쪽', english: 'Left side', pronunciation: 'oen-jjok', partOfSpeech: 'noun', example: '왼쪽에 은행이 있어요.', exampleTranslation: 'There is a bank on the left.', category: 'Directions' },
    { id: '2-53', korean: '앞', english: 'Front / Ahead', pronunciation: 'ap', partOfSpeech: 'noun', example: '학교 앞에서 만나요.', exampleTranslation: 'Let\'s meet in front of the school.', category: 'Directions' },
    { id: '2-54', korean: '뒤', english: 'Behind / Back', pronunciation: 'dwi', partOfSpeech: 'noun', example: '건물 뒤에 주차장이 있어요.', exampleTranslation: 'There is a parking lot behind the building.', category: 'Directions' },
    { id: '2-55', korean: '방', english: 'Room', pronunciation: 'bang', partOfSpeech: 'noun', example: '방이 넓어요.', exampleTranslation: 'The room is spacious.', category: 'Housing' },
    { id: '2-56', korean: '부엌', english: 'Kitchen', pronunciation: 'bu-eok', partOfSpeech: 'noun', example: '부엌에서 요리해요.', exampleTranslation: 'I cook in the kitchen.', category: 'Housing' },
    { id: '2-57', korean: '화장실', english: 'Bathroom / Restroom', pronunciation: 'hwa-jang-sil', partOfSpeech: 'noun', example: '화장실이 어디예요?', exampleTranslation: 'Where is the restroom?', category: 'Housing' },
    { id: '2-58', korean: '수영', english: 'Swimming', pronunciation: 'su-yeong', partOfSpeech: 'noun', example: '수영하러 갈래요?', exampleTranslation: 'Do you want to go swimming?', category: 'Hobbies' },
    { id: '2-59', korean: '그림', english: 'Drawing / Painting', pronunciation: 'geu-rim', partOfSpeech: 'noun', example: '그림 그리는 걸 좋아해요.', exampleTranslation: 'I like drawing.', category: 'Hobbies' },
    { id: '2-60', korean: '요리하다', english: 'To cook', pronunciation: 'yo-ri-ha-da', partOfSpeech: 'verb', example: '주말에 요리해요.', exampleTranslation: 'I cook on weekends.', category: 'Hobbies' },
  ],
  'topik2-3': [
    { id: '3-1', korean: '경험', english: 'Experience', pronunciation: 'gyeong-heom', partOfSpeech: 'noun', example: '좋은 경험이었어요.', exampleTranslation: 'It was a good experience.', category: 'Life' },
    { id: '3-2', korean: '기회', english: 'Opportunity / Chance', pronunciation: 'gi-hoe', partOfSpeech: 'noun', example: '좋은 기회를 잡으세요.', exampleTranslation: 'Seize the good opportunity.', category: 'Life' },
    { id: '3-3', korean: '성공하다', english: 'To succeed', pronunciation: 'seong-gong-ha-da', partOfSpeech: 'verb', example: '꼭 성공할 거예요.', exampleTranslation: 'You will definitely succeed.', category: 'Life' },
    { id: '3-4', korean: '실패하다', english: 'To fail', pronunciation: 'sil-pae-ha-da', partOfSpeech: 'verb', example: '실패해도 괜찮아요.', exampleTranslation: 'It\'s okay even if you fail.', category: 'Life' },
    { id: '3-5', korean: '관계', english: 'Relationship', pronunciation: 'gwan-gye', partOfSpeech: 'noun', example: '좋은 관계를 유지해요.', exampleTranslation: 'Maintain good relationships.', category: 'Social' },
    { id: '3-6', korean: '문화', english: 'Culture', pronunciation: 'mun-hwa', partOfSpeech: 'noun', example: '한국 문화가 재미있어요.', exampleTranslation: 'Korean culture is interesting.', category: 'Culture' },
    { id: '3-7', korean: '전통', english: 'Tradition', pronunciation: 'jeon-tong', partOfSpeech: 'noun', example: '한국의 전통을 배워요.', exampleTranslation: 'I learn Korean traditions.', category: 'Culture' },
    { id: '3-8', korean: '존경하다', english: 'To respect', pronunciation: 'jon-gyeong-ha-da', partOfSpeech: 'verb', example: '선생님을 존경해요.', exampleTranslation: 'I respect my teacher.', category: 'Social' },
    { id: '3-9', korean: '그리워하다', english: 'To miss (someone)', pronunciation: 'geu-ri-wo-ha-da', partOfSpeech: 'verb', example: '고향이 그리워요.', exampleTranslation: 'I miss my hometown.', category: 'K-Drama' },
    { id: '3-10', korean: '이별', english: 'Farewell / Parting', pronunciation: 'i-byeol', partOfSpeech: 'noun', example: '이별은 슬퍼요.', exampleTranslation: 'Farewells are sad.', category: 'K-Drama' },
    { id: '3-11', korean: '운명', english: 'Destiny / Fate', pronunciation: 'un-myeong', partOfSpeech: 'noun', example: '우리는 운명이에요.', exampleTranslation: 'We are destiny.', category: 'K-Drama' },
    { id: '3-12', korean: '배우', english: 'Actor / Actress', pronunciation: 'bae-u', partOfSpeech: 'noun', example: '좋아하는 배우가 있어요?', exampleTranslation: 'Do you have a favorite actor?', category: 'K-Drama' },
    { id: '3-13', korean: '촬영', english: 'Filming / Shooting', pronunciation: 'chwal-yeong', partOfSpeech: 'noun', example: '드라마 촬영 중이에요.', exampleTranslation: 'They\'re filming a drama.', category: 'K-Drama' },
    { id: '3-14', korean: '인기', english: 'Popularity', pronunciation: 'in-gi', partOfSpeech: 'noun', example: '이 드라마가 인기 많아요.', exampleTranslation: 'This drama is very popular.', category: 'K-Drama' },
    { id: '3-15', korean: '연습하다', english: 'To practice', pronunciation: 'yeon-seup-ha-da', partOfSpeech: 'verb', example: '매일 연습해요.', exampleTranslation: 'I practice every day.', category: 'K-Pop' },
    { id: '3-16', korean: '무대', english: 'Stage', pronunciation: 'mu-dae', partOfSpeech: 'noun', example: '무대가 멋있었어요.', exampleTranslation: 'The stage was amazing.', category: 'K-Pop' },
    { id: '3-17', korean: '팬미팅', english: 'Fan meeting', pronunciation: 'paen-mi-ting', partOfSpeech: 'noun', example: '팬미팅에 갈 거예요.', exampleTranslation: 'I\'m going to the fan meeting.', category: 'K-Pop' },
    { id: '3-18', korean: '데뷔', english: 'Debut', pronunciation: 'de-bwi', partOfSpeech: 'noun', example: '올해 데뷔했어요.', exampleTranslation: 'They debuted this year.', category: 'K-Pop' },
    { id: '3-19', korean: '환경', english: 'Environment', pronunciation: 'hwan-gyeong', partOfSpeech: 'noun', example: '환경을 보호해야 해요.', exampleTranslation: 'We must protect the environment.', category: 'Society' },
    { id: '3-20', korean: '건강', english: 'Health', pronunciation: 'geon-gang', partOfSpeech: 'noun', example: '건강이 가장 중요해요.', exampleTranslation: 'Health is the most important.', category: 'Health' },
    { id: '3-21', korean: '계획', english: 'Plan', pronunciation: 'gye-hoek', partOfSpeech: 'noun', example: '여행 계획을 세웠어요.', exampleTranslation: 'I made a travel plan.', category: 'Daily Life' },
    { id: '3-22', korean: '소개하다', english: 'To introduce', pronunciation: 'so-gae-ha-da', partOfSpeech: 'verb', example: '자기소개를 해 주세요.', exampleTranslation: 'Please introduce yourself.', category: 'Social' },
    { id: '3-23', korean: '추천하다', english: 'To recommend', pronunciation: 'chu-cheon-ha-da', partOfSpeech: 'verb', example: '맛집 추천해 주세요.', exampleTranslation: 'Please recommend a good restaurant.', category: 'Social' },
    { id: '3-24', korean: '의견', english: 'Opinion', pronunciation: 'ui-gyeon', partOfSpeech: 'noun', example: '의견을 말해 주세요.', exampleTranslation: 'Please share your opinion.', category: 'Communication' },
    { id: '3-25', korean: '동의하다', english: 'To agree', pronunciation: 'dong-ui-ha-da', partOfSpeech: 'verb', example: '저도 동의해요.', exampleTranslation: 'I agree too.', category: 'Communication' },
    { id: '3-26', korean: '반대하다', english: 'To oppose / Disagree', pronunciation: 'ban-dae-ha-da', partOfSpeech: 'verb', example: '그 의견에 반대해요.', exampleTranslation: 'I disagree with that opinion.', category: 'Communication' },
    { id: '3-27', korean: '설명하다', english: 'To explain', pronunciation: 'seol-myeong-ha-da', partOfSpeech: 'verb', example: '다시 설명해 주세요.', exampleTranslation: 'Please explain again.', category: 'Communication' },
    { id: '3-28', korean: '비교하다', english: 'To compare', pronunciation: 'bi-gyo-ha-da', partOfSpeech: 'verb', example: '두 개를 비교해 봐요.', exampleTranslation: 'Let\'s compare the two.', category: 'Actions' },
    { id: '3-29', korean: '결정하다', english: 'To decide', pronunciation: 'gyeol-jeong-ha-da', partOfSpeech: 'verb', example: '빨리 결정해야 해요.', exampleTranslation: 'We need to decide quickly.', category: 'Actions' },
    { id: '3-30', korean: '포기하다', english: 'To give up', pronunciation: 'po-gi-ha-da', partOfSpeech: 'verb', example: '절대 포기하지 마세요.', exampleTranslation: 'Never give up.', category: 'Motivation' },
    { id: '3-31', korean: '노력하다', english: 'To make effort', pronunciation: 'no-ryeok-ha-da', partOfSpeech: 'verb', example: '열심히 노력할게요.', exampleTranslation: 'I\'ll try my best.', category: 'Motivation' },
    { id: '3-32', korean: '꿈', english: 'Dream', pronunciation: 'kkum', partOfSpeech: 'noun', example: '꿈을 이루세요.', exampleTranslation: 'Achieve your dream.', category: 'Motivation' },
    { id: '3-33', korean: '자신감', english: 'Confidence', pronunciation: 'ja-sin-gam', partOfSpeech: 'noun', example: '자신감을 가지세요.', exampleTranslation: 'Have confidence.', category: 'Motivation' },
    { id: '3-34', korean: '습관', english: 'Habit', pronunciation: 'seup-gwan', partOfSpeech: 'noun', example: '좋은 습관을 만드세요.', exampleTranslation: 'Create good habits.', category: 'Daily Life' },
    { id: '3-35', korean: '복잡하다', english: 'Complicated / Complex', pronunciation: 'bok-jap-ha-da', partOfSpeech: 'adjective', example: '이 문제가 복잡해요.', exampleTranslation: 'This problem is complicated.', category: 'Descriptions' },
    { id: '3-36', korean: '간단하다', english: 'Simple / Easy', pronunciation: 'gan-dan-ha-da', partOfSpeech: 'adjective', example: '간단한 질문이에요.', exampleTranslation: 'It\'s a simple question.', category: 'Descriptions' },
    { id: '3-37', korean: '정확하다', english: 'Accurate / Precise', pronunciation: 'jeong-hwak-ha-da', partOfSpeech: 'adjective', example: '정확하게 말해 주세요.', exampleTranslation: 'Please speak precisely.', category: 'Descriptions' },
    { id: '3-38', korean: '중요하다', english: 'Important', pronunciation: 'jung-yo-ha-da', partOfSpeech: 'adjective', example: '건강이 중요해요.', exampleTranslation: 'Health is important.', category: 'Descriptions' },
    { id: '3-39', korean: '필요하다', english: 'Necessary / Needed', pronunciation: 'pil-yo-ha-da', partOfSpeech: 'adjective', example: '뭐가 필요해요?', exampleTranslation: 'What do you need?', category: 'Descriptions' },
    { id: '3-40', korean: '특별하다', english: 'Special', pronunciation: 'teuk-byeol-ha-da', partOfSpeech: 'adjective', example: '특별한 날이에요.', exampleTranslation: 'It\'s a special day.', category: 'Descriptions' },
    { id: '3-41', korean: '예약하다', english: 'To reserve / Book', pronunciation: 'ye-yak-ha-da', partOfSpeech: 'verb', example: '호텔을 예약했어요.', exampleTranslation: 'I booked a hotel.', category: 'Travel' },
    { id: '3-42', korean: '관광지', english: 'Tourist attraction', pronunciation: 'gwan-gwang-ji', partOfSpeech: 'noun', example: '유명한 관광지에 갔어요.', exampleTranslation: 'I went to a famous tourist spot.', category: 'Travel' },
    { id: '3-43', korean: '출발하다', english: 'To depart', pronunciation: 'chul-bal-ha-da', partOfSpeech: 'verb', example: '내일 아침에 출발해요.', exampleTranslation: 'We depart tomorrow morning.', category: 'Travel' },
    { id: '3-44', korean: '도착하다', english: 'To arrive', pronunciation: 'do-chak-ha-da', partOfSpeech: 'verb', example: '공항에 도착했어요.', exampleTranslation: 'I arrived at the airport.', category: 'Travel' },
    { id: '3-45', korean: '뉴스', english: 'News', pronunciation: 'nyu-seu', partOfSpeech: 'noun', example: '오늘 뉴스를 봤어요?', exampleTranslation: 'Did you watch the news today?', category: 'Media' },
    { id: '3-46', korean: '기사', english: 'Article / News story', pronunciation: 'gi-sa', partOfSpeech: 'noun', example: '이 기사를 읽어 보세요.', exampleTranslation: 'Please read this article.', category: 'Media' },
    { id: '3-47', korean: '방송', english: 'Broadcast / Program', pronunciation: 'bang-song', partOfSpeech: 'noun', example: '그 방송 재미있었어요.', exampleTranslation: 'That program was interesting.', category: 'Media' },
    { id: '3-48', korean: '광고', english: 'Advertisement', pronunciation: 'gwang-go', partOfSpeech: 'noun', example: '이 광고가 유명해요.', exampleTranslation: 'This advertisement is famous.', category: 'Media' },
    { id: '3-49', korean: '회의', english: 'Meeting', pronunciation: 'hoe-ui', partOfSpeech: 'noun', example: '오후에 회의가 있어요.', exampleTranslation: 'There is a meeting in the afternoon.', category: 'Workplace' },
    { id: '3-50', korean: '보고서', english: 'Report', pronunciation: 'bo-go-seo', partOfSpeech: 'noun', example: '보고서를 작성해야 해요.', exampleTranslation: 'I need to write a report.', category: 'Workplace' },
    { id: '3-51', korean: '동료', english: 'Colleague', pronunciation: 'dong-ryo', partOfSpeech: 'noun', example: '동료와 점심을 먹었어요.', exampleTranslation: 'I had lunch with a colleague.', category: 'Workplace' },
    { id: '3-52', korean: '상사', english: 'Boss / Superior', pronunciation: 'sang-sa', partOfSpeech: 'noun', example: '상사에게 보고했어요.', exampleTranslation: 'I reported to my boss.', category: 'Workplace' },
    { id: '3-53', korean: '외롭다', english: 'Lonely', pronunciation: 'oe-rop-da', partOfSpeech: 'adjective', example: '혼자 있으면 외로워요.', exampleTranslation: 'I feel lonely when I\'m alone.', category: 'Emotions' },
    { id: '3-54', korean: '부럽다', english: 'Envious / Jealous', pronunciation: 'bu-reop-da', partOfSpeech: 'adjective', example: '정말 부러워요.', exampleTranslation: 'I\'m really envious.', category: 'Emotions' },
    { id: '3-55', korean: '감동하다', english: 'To be moved / Touched', pronunciation: 'gam-dong-ha-da', partOfSpeech: 'verb', example: '영화를 보고 감동했어요.', exampleTranslation: 'I was moved by the movie.', category: 'Emotions' },
    { id: '3-56', korean: '후회하다', english: 'To regret', pronunciation: 'hu-hoe-ha-da', partOfSpeech: 'verb', example: '후회하지 않을 거예요.', exampleTranslation: 'I won\'t regret it.', category: 'Emotions' },
    { id: '3-57', korean: '산', english: 'Mountain', pronunciation: 'san', partOfSpeech: 'noun', example: '주말에 산에 갈 거예요.', exampleTranslation: 'I\'m going to the mountain on the weekend.', category: 'Nature' },
    { id: '3-58', korean: '바다', english: 'Sea / Ocean', pronunciation: 'ba-da', partOfSpeech: 'noun', example: '바다가 정말 아름다워요.', exampleTranslation: 'The sea is really beautiful.', category: 'Nature' },
    { id: '3-59', korean: '하늘', english: 'Sky', pronunciation: 'ha-neul', partOfSpeech: 'noun', example: '오늘 하늘이 맑아요.', exampleTranslation: 'The sky is clear today.', category: 'Nature' },
    { id: '3-60', korean: '꽃', english: 'Flower', pronunciation: 'kkot', partOfSpeech: 'noun', example: '봄에 꽃이 많이 펴요.', exampleTranslation: 'Many flowers bloom in spring.', category: 'Nature' },
  ],
  'topik2-4': [
    { id: '4-1', korean: '경제', english: 'Economy', pronunciation: 'gyeong-je', partOfSpeech: 'noun', example: '경제가 성장하고 있어요.', exampleTranslation: 'The economy is growing.', category: 'Economy' },
    { id: '4-2', korean: '정치', english: 'Politics', pronunciation: 'jeong-chi', partOfSpeech: 'noun', example: '정치에 관심이 있어요.', exampleTranslation: 'I\'m interested in politics.', category: 'Politics' },
    { id: '4-3', korean: '사회', english: 'Society', pronunciation: 'sa-hoe', partOfSpeech: 'noun', example: '사회 문제를 해결해야 해요.', exampleTranslation: 'We need to solve social problems.', category: 'Politics' },
    { id: '4-4', korean: '기술', english: 'Technology', pronunciation: 'gi-sul', partOfSpeech: 'noun', example: '기술이 빠르게 발전해요.', exampleTranslation: 'Technology is advancing rapidly.', category: 'Science' },
    { id: '4-5', korean: '연구하다', english: 'To research', pronunciation: 'yeon-gu-ha-da', partOfSpeech: 'verb', example: '새로운 주제를 연구해요.', exampleTranslation: 'I research new topics.', category: 'Education' },
    { id: '4-6', korean: '발표하다', english: 'To present / Announce', pronunciation: 'bal-pyo-ha-da', partOfSpeech: 'verb', example: '내일 발표가 있어요.', exampleTranslation: 'I have a presentation tomorrow.', category: 'Education' },
    { id: '4-7', korean: '논쟁', english: 'Debate / Argument', pronunciation: 'non-jaeng', partOfSpeech: 'noun', example: '이 주제는 논쟁이 많아요.', exampleTranslation: 'This topic has much debate.', category: 'Politics' },
    { id: '4-8', korean: '주장하다', english: 'To argue / Claim', pronunciation: 'ju-jang-ha-da', partOfSpeech: 'verb', example: '자신의 의견을 주장해요.', exampleTranslation: 'They assert their opinion.', category: 'Politics' },
    { id: '4-9', korean: '해결하다', english: 'To solve / Resolve', pronunciation: 'hae-gyeol-ha-da', partOfSpeech: 'verb', example: '문제를 해결했어요.', exampleTranslation: 'I solved the problem.', category: 'Education' },
    { id: '4-10', korean: '영향', english: 'Influence / Impact', pronunciation: 'yeong-hyang', partOfSpeech: 'noun', example: '큰 영향을 미쳤어요.', exampleTranslation: 'It had a big impact.', category: 'Education' },
    { id: '4-11', korean: '조사하다', english: 'To investigate / Survey', pronunciation: 'jo-sa-ha-da', partOfSpeech: 'verb', example: '시장을 조사했어요.', exampleTranslation: 'I surveyed the market.', category: 'Economy' },
    { id: '4-12', korean: '분석하다', english: 'To analyze', pronunciation: 'bun-seok-ha-da', partOfSpeech: 'verb', example: '데이터를 분석해요.', exampleTranslation: 'I analyze the data.', category: 'Science' },
    { id: '4-13', korean: '적용하다', english: 'To apply', pronunciation: 'jeok-yong-ha-da', partOfSpeech: 'verb', example: '새 방법을 적용해요.', exampleTranslation: 'I apply a new method.', category: 'Science' },
    { id: '4-14', korean: '효과', english: 'Effect / Effectiveness', pronunciation: 'hyo-gwa', partOfSpeech: 'noun', example: '효과가 좋아요.', exampleTranslation: 'The effect is good.', category: 'Science' },
    { id: '4-15', korean: '구조', english: 'Structure', pronunciation: 'gu-jo', partOfSpeech: 'noun', example: '문장 구조를 배워요.', exampleTranslation: 'I learn sentence structure.', category: 'Education' },
    { id: '4-16', korean: '과정', english: 'Process / Course', pronunciation: 'gwa-jeong', partOfSpeech: 'noun', example: '학습 과정이 중요해요.', exampleTranslation: 'The learning process is important.', category: 'Education' },
    { id: '4-17', korean: '원인', english: 'Cause / Reason', pronunciation: 'won-in', partOfSpeech: 'noun', example: '원인을 찾아야 해요.', exampleTranslation: 'We need to find the cause.', category: 'Science' },
    { id: '4-18', korean: '결과', english: 'Result / Outcome', pronunciation: 'gyeol-gwa', partOfSpeech: 'noun', example: '좋은 결과를 얻었어요.', exampleTranslation: 'I got a good result.', category: 'Education' },
    { id: '4-19', korean: '책임', english: 'Responsibility', pronunciation: 'chaek-im', partOfSpeech: 'noun', example: '책임감이 중요해요.', exampleTranslation: 'Responsibility is important.', category: 'Law' },
    { id: '4-20', korean: '협력하다', english: 'To cooperate', pronunciation: 'hyeop-ryeok-ha-da', partOfSpeech: 'verb', example: '함께 협력합시다.', exampleTranslation: 'Let\'s cooperate together.', category: 'Politics' },
    { id: '4-21', korean: '존중하다', english: 'To respect', pronunciation: 'jon-jung-ha-da', partOfSpeech: 'verb', example: '서로 존중해야 해요.', exampleTranslation: 'We must respect each other.', category: 'Politics' },
    { id: '4-22', korean: '변화', english: 'Change', pronunciation: 'byeon-hwa', partOfSpeech: 'noun', example: '변화를 두려워하지 마세요.', exampleTranslation: 'Don\'t be afraid of change.', category: 'Education' },
    { id: '4-23', korean: '도전', english: 'Challenge', pronunciation: 'do-jeon', partOfSpeech: 'noun', example: '새로운 도전을 해요.', exampleTranslation: 'I take on new challenges.', category: 'Education' },
    { id: '4-24', korean: '성취', english: 'Achievement', pronunciation: 'seong-chwi', partOfSpeech: 'noun', example: '큰 성취를 이뤘어요.', exampleTranslation: 'I achieved great things.', category: 'Education' },
    { id: '4-25', korean: '갈등', english: 'Conflict', pronunciation: 'gal-deung', partOfSpeech: 'noun', example: '갈등을 해결해요.', exampleTranslation: 'I resolve the conflict.', category: 'Politics' },
    { id: '4-26', korean: '타협하다', english: 'To compromise', pronunciation: 'ta-hyeop-ha-da', partOfSpeech: 'verb', example: '서로 타협해야 해요.', exampleTranslation: 'We need to compromise.', category: 'Politics' },
    { id: '4-27', korean: '인정하다', english: 'To acknowledge / Admit', pronunciation: 'in-jeong-ha-da', partOfSpeech: 'verb', example: '실수를 인정해요.', exampleTranslation: 'I acknowledge my mistake.', category: 'Law' },
    { id: '4-28', korean: '증가하다', english: 'To increase', pronunciation: 'jeung-ga-ha-da', partOfSpeech: 'verb', example: '인구가 증가해요.', exampleTranslation: 'The population is increasing.', category: 'Economy' },
    { id: '4-29', korean: '감소하다', english: 'To decrease', pronunciation: 'gam-so-ha-da', partOfSpeech: 'verb', example: '비용이 감소했어요.', exampleTranslation: 'The cost decreased.', category: 'Economy' },
    { id: '4-30', korean: '유지하다', english: 'To maintain', pronunciation: 'yu-ji-ha-da', partOfSpeech: 'verb', example: '건강을 유지하세요.', exampleTranslation: 'Maintain your health.', category: 'Medicine' },
    { id: '4-31', korean: '선거', english: 'Election', pronunciation: 'seon-geo', partOfSpeech: 'noun', example: '다음 달에 선거가 있어요.', exampleTranslation: 'There is an election next month.', category: 'Politics' },
    { id: '4-32', korean: '투표하다', english: 'To vote', pronunciation: 'tu-pyo-ha-da', partOfSpeech: 'verb', example: '꼭 투표하세요.', exampleTranslation: 'Please make sure to vote.', category: 'Politics' },
    { id: '4-33', korean: '정책', english: 'Policy', pronunciation: 'jeong-chaek', partOfSpeech: 'noun', example: '새로운 정책이 발표되었어요.', exampleTranslation: 'A new policy was announced.', category: 'Politics' },
    { id: '4-34', korean: '법률', english: 'Law / Legislation', pronunciation: 'beom-nyul', partOfSpeech: 'noun', example: '법률을 잘 알아야 해요.', exampleTranslation: 'You need to know the law well.', category: 'Law' },
    { id: '4-35', korean: '권리', english: 'Right / Rights', pronunciation: 'gwon-ri', partOfSpeech: 'noun', example: '모든 사람은 평등한 권리가 있어요.', exampleTranslation: 'Everyone has equal rights.', category: 'Law' },
    { id: '4-36', korean: '의무', english: 'Duty / Obligation', pronunciation: 'ui-mu', partOfSpeech: 'noun', example: '국민의 의무를 다해야 해요.', exampleTranslation: 'You must fulfill your duties as a citizen.', category: 'Law' },
    { id: '4-37', korean: '범죄', english: 'Crime', pronunciation: 'beom-joe', partOfSpeech: 'noun', example: '범죄를 예방해야 해요.', exampleTranslation: 'We must prevent crime.', category: 'Law' },
    { id: '4-38', korean: '실험', english: 'Experiment', pronunciation: 'sil-heom', partOfSpeech: 'noun', example: '과학 실험을 했어요.', exampleTranslation: 'I did a science experiment.', category: 'Science' },
    { id: '4-39', korean: '발견하다', english: 'To discover', pronunciation: 'bal-gyeon-ha-da', partOfSpeech: 'verb', example: '새로운 사실을 발견했어요.', exampleTranslation: 'I discovered a new fact.', category: 'Science' },
    { id: '4-40', korean: '개발하다', english: 'To develop', pronunciation: 'gae-bal-ha-da', partOfSpeech: 'verb', example: '새 제품을 개발해요.', exampleTranslation: 'We are developing a new product.', category: 'Science' },
    { id: '4-41', korean: '이론', english: 'Theory', pronunciation: 'i-ron', partOfSpeech: 'noun', example: '이 이론은 유명해요.', exampleTranslation: 'This theory is famous.', category: 'Science' },
    { id: '4-42', korean: '증거', english: 'Evidence / Proof', pronunciation: 'jeung-geo', partOfSpeech: 'noun', example: '증거가 충분하지 않아요.', exampleTranslation: 'There is not enough evidence.', category: 'Law' },
    { id: '4-43', korean: '치료하다', english: 'To treat / Cure', pronunciation: 'chi-ryo-ha-da', partOfSpeech: 'verb', example: '병을 치료해야 해요.', exampleTranslation: 'The illness needs to be treated.', category: 'Medicine' },
    { id: '4-44', korean: '진단하다', english: 'To diagnose', pronunciation: 'jin-dan-ha-da', partOfSpeech: 'verb', example: '의사가 병을 진단했어요.', exampleTranslation: 'The doctor diagnosed the illness.', category: 'Medicine' },
    { id: '4-45', korean: '증상', english: 'Symptom', pronunciation: 'jeung-sang', partOfSpeech: 'noun', example: '어떤 증상이 있어요?', exampleTranslation: 'What symptoms do you have?', category: 'Medicine' },
    { id: '4-46', korean: '약', english: 'Medicine / Drug', pronunciation: 'yak', partOfSpeech: 'noun', example: '약을 먹어야 해요.', exampleTranslation: 'You need to take medicine.', category: 'Medicine' },
    { id: '4-47', korean: '수술', english: 'Surgery / Operation', pronunciation: 'su-sul', partOfSpeech: 'noun', example: '수술이 성공적이었어요.', exampleTranslation: 'The surgery was successful.', category: 'Medicine' },
    { id: '4-48', korean: '투자하다', english: 'To invest', pronunciation: 'tu-ja-ha-da', partOfSpeech: 'verb', example: '주식에 투자해요.', exampleTranslation: 'I invest in stocks.', category: 'Economy' },
    { id: '4-49', korean: '수출', english: 'Export', pronunciation: 'su-chul', partOfSpeech: 'noun', example: '한국은 반도체를 수출해요.', exampleTranslation: 'Korea exports semiconductors.', category: 'Economy' },
    { id: '4-50', korean: '수입', english: 'Import', pronunciation: 'su-ip', partOfSpeech: 'noun', example: '석유를 수입해요.', exampleTranslation: 'We import oil.', category: 'Economy' },
    { id: '4-51', korean: '무역', english: 'Trade / Commerce', pronunciation: 'mu-yeok', partOfSpeech: 'noun', example: '국제 무역이 중요해요.', exampleTranslation: 'International trade is important.', category: 'Economy' },
    { id: '4-52', korean: '세금', english: 'Tax', pronunciation: 'se-geum', partOfSpeech: 'noun', example: '세금을 내야 해요.', exampleTranslation: 'You need to pay taxes.', category: 'Economy' },
    { id: '4-53', korean: '교육', english: 'Education', pronunciation: 'gyo-yuk', partOfSpeech: 'noun', example: '교육이 미래를 바꿔요.', exampleTranslation: 'Education changes the future.', category: 'Education' },
    { id: '4-54', korean: '학위', english: 'Degree (academic)', pronunciation: 'hak-wi', partOfSpeech: 'noun', example: '석사 학위를 받았어요.', exampleTranslation: 'I received a master\'s degree.', category: 'Education' },
    { id: '4-55', korean: '장학금', english: 'Scholarship', pronunciation: 'jang-hak-geum', partOfSpeech: 'noun', example: '장학금을 받았어요.', exampleTranslation: 'I received a scholarship.', category: 'Education' },
    { id: '4-56', korean: '입학하다', english: 'To enroll / Enter school', pronunciation: 'ip-hak-ha-da', partOfSpeech: 'verb', example: '대학교에 입학했어요.', exampleTranslation: 'I enrolled in university.', category: 'Education' },
    { id: '4-57', korean: '졸업하다', english: 'To graduate', pronunciation: 'jol-eop-ha-da', partOfSpeech: 'verb', example: '작년에 졸업했어요.', exampleTranslation: 'I graduated last year.', category: 'Education' },
    { id: '4-58', korean: '예방하다', english: 'To prevent', pronunciation: 'ye-bang-ha-da', partOfSpeech: 'verb', example: '질병을 예방해야 해요.', exampleTranslation: 'We must prevent diseases.', category: 'Medicine' },
    { id: '4-59', korean: '오염', english: 'Pollution / Contamination', pronunciation: 'o-yeom', partOfSpeech: 'noun', example: '대기 오염이 심해요.', exampleTranslation: 'Air pollution is severe.', category: 'Science' },
    { id: '4-60', korean: '재판', english: 'Trial / Court hearing', pronunciation: 'jae-pan', partOfSpeech: 'noun', example: '재판이 내일 열려요.', exampleTranslation: 'The trial opens tomorrow.', category: 'Law' },
  ],
  'topik2-5': [
    { id: '5-1', korean: '창작하다', english: 'To create (art/literature)', pronunciation: 'chang-jak-ha-da', partOfSpeech: 'verb', example: '새로운 작품을 창작했어요.', exampleTranslation: 'I created a new work of art.', category: 'Literature' },
    { id: '5-2', korean: '비평', english: 'Criticism / Critique', pronunciation: 'bi-pyeong', partOfSpeech: 'noun', example: '문학 비평을 공부해요.', exampleTranslation: 'I study literary criticism.', category: 'Literature' },
    { id: '5-3', korean: '사상', english: 'Ideology / Thought', pronunciation: 'sa-sang', partOfSpeech: 'noun', example: '그의 사상은 많은 사람에게 영향을 줬어요.', exampleTranslation: 'His ideology influenced many people.', category: 'Philosophy' },
    { id: '5-4', korean: '심리', english: 'Psychology / Mentality', pronunciation: 'sim-ri', partOfSpeech: 'noun', example: '인간의 심리는 복잡해요.', exampleTranslation: 'Human psychology is complex.', category: 'Psychology' },
    { id: '5-5', korean: '철학', english: 'Philosophy', pronunciation: 'cheol-hak', partOfSpeech: 'noun', example: '동양 철학에 관심이 있어요.', exampleTranslation: 'I\'m interested in Eastern philosophy.', category: 'Philosophy' },
    { id: '5-6', korean: '미학', english: 'Aesthetics', pronunciation: 'mi-hak', partOfSpeech: 'noun', example: '한국 미학이 세계적으로 주목받고 있어요.', exampleTranslation: 'Korean aesthetics are gaining worldwide attention.', category: 'Arts' },
    { id: '5-7', korean: '논리', english: 'Logic', pronunciation: 'nol-ri', partOfSpeech: 'noun', example: '논리적으로 생각해 보세요.', exampleTranslation: 'Try to think logically.', category: 'Philosophy' },
    { id: '5-8', korean: '모순', english: 'Contradiction', pronunciation: 'mo-sun', partOfSpeech: 'noun', example: '그 주장에는 모순이 있어요.', exampleTranslation: 'There is a contradiction in that argument.', category: 'Philosophy' },
    { id: '5-9', korean: '편견', english: 'Prejudice / Bias', pronunciation: 'pyeon-gyeon', partOfSpeech: 'noun', example: '편견을 버려야 해요.', exampleTranslation: 'We must let go of prejudice.', category: 'Social Issues' },
    { id: '5-10', korean: '차별', english: 'Discrimination', pronunciation: 'cha-byeol', partOfSpeech: 'noun', example: '차별 없는 사회를 만들어야 해요.', exampleTranslation: 'We must create a society without discrimination.', category: 'Social Issues' },
    { id: '5-11', korean: '윤리', english: 'Ethics', pronunciation: 'yul-ri', partOfSpeech: 'noun', example: '윤리적 문제를 고민해야 해요.', exampleTranslation: 'We need to consider ethical issues.', category: 'Philosophy' },
    { id: '5-12', korean: '갈등', english: 'Conflict', pronunciation: 'gal-deung', partOfSpeech: 'noun', example: '세대 간의 갈등이 심해요.', exampleTranslation: 'The generational conflict is severe.', category: 'Social Issues' },
    { id: '5-13', korean: '보편적', english: 'Universal', pronunciation: 'bo-pyeon-jeok', partOfSpeech: 'adjective', example: '인권은 보편적 가치예요.', exampleTranslation: 'Human rights are a universal value.', category: 'Abstract Concepts' },
    { id: '5-14', korean: '주관적', english: 'Subjective', pronunciation: 'ju-gwan-jeok', partOfSpeech: 'adjective', example: '예술은 주관적이에요.', exampleTranslation: 'Art is subjective.', category: 'Abstract Concepts' },
    { id: '5-15', korean: '객관적', english: 'Objective', pronunciation: 'gaek-gwan-jeok', partOfSpeech: 'adjective', example: '객관적으로 판단해야 해요.', exampleTranslation: 'You must judge objectively.', category: 'Abstract Concepts' },
    { id: '5-16', korean: '추상적', english: 'Abstract', pronunciation: 'chu-sang-jeok', partOfSpeech: 'adjective', example: '이 개념은 매우 추상적이에요.', exampleTranslation: 'This concept is very abstract.', category: 'Abstract Concepts' },
    { id: '5-17', korean: '구체적', english: 'Concrete / Specific', pronunciation: 'gu-che-jeok', partOfSpeech: 'adjective', example: '구체적인 예를 들어 주세요.', exampleTranslation: 'Please give a specific example.', category: 'Abstract Concepts' },
    { id: '5-18', korean: '합리적', english: 'Rational / Reasonable', pronunciation: 'hap-ri-jeok', partOfSpeech: 'adjective', example: '합리적인 결정을 내려야 해요.', exampleTranslation: 'We need to make a rational decision.', category: 'Abstract Concepts' },
    { id: '5-19', korean: '혁신', english: 'Innovation', pronunciation: 'hyeok-sin', partOfSpeech: 'noun', example: '기술 혁신이 사회를 바꿔요.', exampleTranslation: 'Technological innovation changes society.', category: 'Social Issues' },
    { id: '5-20', korean: '진화', english: 'Evolution', pronunciation: 'jin-hwa', partOfSpeech: 'noun', example: '생물의 진화 과정을 연구해요.', exampleTranslation: 'I study the process of biological evolution.', category: 'Philosophy' },
    { id: '5-21', korean: '현상', english: 'Phenomenon', pronunciation: 'hyeon-sang', partOfSpeech: 'noun', example: '이 현상의 원인이 뭘까요?', exampleTranslation: 'What is the cause of this phenomenon?', category: 'Abstract Concepts' },
    { id: '5-22', korean: '개념', english: 'Concept', pronunciation: 'gae-nyeom', partOfSpeech: 'noun', example: '이 개념을 이해하기 어려워요.', exampleTranslation: 'This concept is difficult to understand.', category: 'Abstract Concepts' },
    { id: '5-23', korean: '범위', english: 'Scope / Range', pronunciation: 'beom-wi', partOfSpeech: 'noun', example: '연구 범위를 정해야 해요.', exampleTranslation: 'We need to define the scope of research.', category: 'Abstract Concepts' },
    { id: '5-24', korean: '기준', english: 'Standard / Criteria', pronunciation: 'gi-jun', partOfSpeech: 'noun', example: '평가 기준이 명확해야 해요.', exampleTranslation: 'The evaluation criteria must be clear.', category: 'Abstract Concepts' },
    { id: '5-25', korean: '맥락', english: 'Context', pronunciation: 'maek-rak', partOfSpeech: 'noun', example: '맥락을 이해해야 정확히 해석할 수 있어요.', exampleTranslation: 'You need to understand the context to interpret accurately.', category: 'Abstract Concepts' },
    { id: '5-26', korean: '의미', english: 'Meaning', pronunciation: 'ui-mi', partOfSpeech: 'noun', example: '이 단어의 의미가 뭐예요?', exampleTranslation: 'What is the meaning of this word?', category: 'Abstract Concepts' },
    { id: '5-27', korean: '상징', english: 'Symbol', pronunciation: 'sang-jing', partOfSpeech: 'noun', example: '비둘기는 평화의 상징이에요.', exampleTranslation: 'The dove is a symbol of peace.', category: 'Literature' },
    { id: '5-28', korean: '해석', english: 'Interpretation', pronunciation: 'hae-seok', partOfSpeech: 'noun', example: '이 작품은 다양한 해석이 가능해요.', exampleTranslation: 'This work allows for various interpretations.', category: 'Literature' },
    { id: '5-29', korean: '인식', english: 'Perception / Recognition', pronunciation: 'in-sik', partOfSpeech: 'noun', example: '사회적 인식이 변하고 있어요.', exampleTranslation: 'Social perception is changing.', category: 'Psychology' },
    { id: '5-30', korean: '가치', english: 'Value', pronunciation: 'ga-chi', partOfSpeech: 'noun', example: '가치관이 사람마다 달라요.', exampleTranslation: 'Values differ from person to person.', category: 'Philosophy' },
    { id: '5-31', korean: '태도', english: 'Attitude', pronunciation: 'tae-do', partOfSpeech: 'noun', example: '긍정적인 태도가 중요해요.', exampleTranslation: 'A positive attitude is important.', category: 'Psychology' },
    { id: '5-32', korean: '성격', english: 'Personality / Character', pronunciation: 'seong-gyeok', partOfSpeech: 'noun', example: '성격이 밝고 활발해요.', exampleTranslation: 'Their personality is bright and lively.', category: 'Psychology' },
    { id: '5-33', korean: '감정', english: 'Emotion', pronunciation: 'gam-jeong', partOfSpeech: 'noun', example: '감정을 잘 표현해야 해요.', exampleTranslation: 'You should express your emotions well.', category: 'Psychology' },
    { id: '5-34', korean: '의식', english: 'Consciousness', pronunciation: 'ui-sik', partOfSpeech: 'noun', example: '환경에 대한 의식이 높아졌어요.', exampleTranslation: 'Environmental consciousness has increased.', category: 'Psychology' },
    { id: '5-35', korean: '무의식', english: 'Unconscious', pronunciation: 'mu-ui-sik', partOfSpeech: 'noun', example: '무의식적으로 행동할 때가 있어요.', exampleTranslation: 'There are times when we act unconsciously.', category: 'Psychology' },
    { id: '5-36', korean: '동기', english: 'Motivation / Motive', pronunciation: 'dong-gi', partOfSpeech: 'noun', example: '공부의 동기를 찾으세요.', exampleTranslation: 'Find your motivation for studying.', category: 'Psychology' },
    { id: '5-37', korean: '본능', english: 'Instinct', pronunciation: 'bon-neung', partOfSpeech: 'noun', example: '생존 본능은 강해요.', exampleTranslation: 'The survival instinct is strong.', category: 'Psychology' },
    { id: '5-38', korean: '직관', english: 'Intuition', pronunciation: 'jik-gwan', partOfSpeech: 'noun', example: '직관에 따라 결정했어요.', exampleTranslation: 'I decided based on intuition.', category: 'Psychology' },
    { id: '5-39', korean: '통찰', english: 'Insight', pronunciation: 'tong-chal', partOfSpeech: 'noun', example: '깊은 통찰력이 필요해요.', exampleTranslation: 'Deep insight is needed.', category: 'Psychology' },
    { id: '5-40', korean: '성찰', english: 'Reflection / Introspection', pronunciation: 'seong-chal', partOfSpeech: 'noun', example: '자기 성찰의 시간을 가지세요.', exampleTranslation: 'Take time for self-reflection.', category: 'Philosophy' },
    { id: '5-41', korean: '소설', english: 'Novel', pronunciation: 'so-seol', partOfSpeech: 'noun', example: '이 소설은 베스트셀러예요.', exampleTranslation: 'This novel is a bestseller.', category: 'Literature' },
    { id: '5-42', korean: '시', english: 'Poem / Poetry', pronunciation: 'si', partOfSpeech: 'noun', example: '한국 시를 번역했어요.', exampleTranslation: 'I translated Korean poetry.', category: 'Literature' },
    { id: '5-43', korean: '수필', english: 'Essay', pronunciation: 'su-pil', partOfSpeech: 'noun', example: '수필을 쓰는 것을 좋아해요.', exampleTranslation: 'I like writing essays.', category: 'Literature' },
    { id: '5-44', korean: '작품', english: 'Work of art', pronunciation: 'jak-pum', partOfSpeech: 'noun', example: '이 작품은 유명한 화가의 것이에요.', exampleTranslation: 'This work is by a famous painter.', category: 'Arts' },
    { id: '5-45', korean: '표현', english: 'Expression', pronunciation: 'pyo-hyeon', partOfSpeech: 'noun', example: '감정을 표현하는 방법을 배워요.', exampleTranslation: 'I learn ways to express emotions.', category: 'Arts' },
    { id: '5-46', korean: '묘사하다', english: 'To describe / Depict', pronunciation: 'myo-sa-ha-da', partOfSpeech: 'verb', example: '작가가 인물을 생생하게 묘사했어요.', exampleTranslation: 'The author depicted the character vividly.', category: 'Literature' },
    { id: '5-47', korean: '서술하다', english: 'To narrate', pronunciation: 'seo-sul-ha-da', partOfSpeech: 'verb', example: '사건을 객관적으로 서술해요.', exampleTranslation: 'The events are narrated objectively.', category: 'Literature' },
    { id: '5-48', korean: '인용하다', english: 'To quote / Cite', pronunciation: 'in-yong-ha-da', partOfSpeech: 'verb', example: '유명한 말을 인용했어요.', exampleTranslation: 'I quoted a famous saying.', category: 'Literature' },
    { id: '5-49', korean: '비유', english: 'Metaphor / Simile', pronunciation: 'bi-yu', partOfSpeech: 'noun', example: '비유적 표현을 사용했어요.', exampleTranslation: 'A figurative expression was used.', category: 'Literature' },
    { id: '5-50', korean: '은유', english: 'Metaphor', pronunciation: 'eun-yu', partOfSpeech: 'noun', example: '이 시에는 은유가 많아요.', exampleTranslation: 'This poem has many metaphors.', category: 'Literature' },
    { id: '5-51', korean: '풍자', english: 'Satire', pronunciation: 'pung-ja', partOfSpeech: 'noun', example: '사회를 풍자하는 소설이에요.', exampleTranslation: 'It is a novel that satirizes society.', category: 'Literature' },
    { id: '5-52', korean: '역설', english: 'Paradox', pronunciation: 'yeok-seol', partOfSpeech: 'noun', example: '그의 주장에는 역설이 담겨 있어요.', exampleTranslation: 'His argument contains a paradox.', category: 'Philosophy' },
    { id: '5-53', korean: '서정적', english: 'Lyrical', pronunciation: 'seo-jeong-jeok', partOfSpeech: 'adjective', example: '서정적인 분위기의 노래예요.', exampleTranslation: 'It\'s a song with a lyrical atmosphere.', category: 'Arts' },
    { id: '5-54', korean: '서사적', english: 'Narrative / Epic', pronunciation: 'seo-sa-jeok', partOfSpeech: 'adjective', example: '서사적 구조가 뛰어난 영화예요.', exampleTranslation: 'It\'s a movie with an excellent narrative structure.', category: 'Arts' },
    { id: '5-55', korean: '비극적', english: 'Tragic', pronunciation: 'bi-geuk-jeok', partOfSpeech: 'adjective', example: '비극적인 결말이었어요.', exampleTranslation: 'It was a tragic ending.', category: 'Arts' },
    { id: '5-56', korean: '낭만적', english: 'Romantic', pronunciation: 'nang-man-jeok', partOfSpeech: 'adjective', example: '낭만적인 분위기에서 식사했어요.', exampleTranslation: 'We dined in a romantic atmosphere.', category: 'Arts' },
    { id: '5-57', korean: '사실적', english: 'Realistic', pronunciation: 'sa-sil-jeok', partOfSpeech: 'adjective', example: '이 영화는 사실적으로 묘사되었어요.', exampleTranslation: 'This movie was realistically depicted.', category: 'Arts' },
    { id: '5-58', korean: '자극', english: 'Stimulus', pronunciation: 'ja-geuk', partOfSpeech: 'noun', example: '새로운 자극이 필요해요.', exampleTranslation: 'I need new stimulation.', category: 'Psychology' },
    { id: '5-59', korean: '영감', english: 'Inspiration', pronunciation: 'yeong-gam', partOfSpeech: 'noun', example: '자연에서 영감을 받았어요.', exampleTranslation: 'I received inspiration from nature.', category: 'Arts' },
    { id: '5-60', korean: '창의력', english: 'Creativity', pronunciation: 'chang-ui-ryeok', partOfSpeech: 'noun', example: '창의력을 키우는 것이 중요해요.', exampleTranslation: 'It is important to develop creativity.', category: 'Arts' },
  ],
  'topik2-6': [
    { id: '6-1', korean: '논문', english: 'Thesis / Paper', pronunciation: 'non-mun', partOfSpeech: 'noun', example: '논문을 제출해야 해요.', exampleTranslation: 'I need to submit my thesis.', category: 'Academic Writing' },
    { id: '6-2', korean: '학술', english: 'Academic', pronunciation: 'hak-sul', partOfSpeech: 'noun', example: '학술 논문을 발표했어요.', exampleTranslation: 'I presented an academic paper.', category: 'Academic Writing' },
    { id: '6-3', korean: '근거', english: 'Basis / Evidence', pronunciation: 'geun-geo', partOfSpeech: 'noun', example: '과학적 근거가 필요해요.', exampleTranslation: 'Scientific evidence is needed.', category: 'Academic Writing' },
    { id: '6-4', korean: '전제', english: 'Premise', pronunciation: 'jeon-je', partOfSpeech: 'noun', example: '이 이론의 전제를 검토해야 해요.', exampleTranslation: 'We need to examine the premise of this theory.', category: 'Academic Writing' },
    { id: '6-5', korean: '가설', english: 'Hypothesis', pronunciation: 'ga-seol', partOfSpeech: 'noun', example: '가설을 세우고 실험을 했어요.', exampleTranslation: 'I set up a hypothesis and conducted an experiment.', category: 'Academic Writing' },
    { id: '6-6', korean: '입증하다', english: 'To prove / Verify', pronunciation: 'ip-jeung-ha-da', partOfSpeech: 'verb', example: '그 가설이 입증되었어요.', exampleTranslation: 'That hypothesis was proven.', category: 'Academic Writing' },
    { id: '6-7', korean: '반박하다', english: 'To refute', pronunciation: 'ban-bak-ha-da', partOfSpeech: 'verb', example: '상대방의 주장을 반박했어요.', exampleTranslation: 'I refuted the opponent\'s argument.', category: 'Academic Writing' },
    { id: '6-8', korean: '수정하다', english: 'To revise', pronunciation: 'su-jeong-ha-da', partOfSpeech: 'verb', example: '논문을 여러 번 수정했어요.', exampleTranslation: 'I revised the paper several times.', category: 'Academic Writing' },
    { id: '6-9', korean: '검증하다', english: 'To verify / Validate', pronunciation: 'geom-jeung-ha-da', partOfSpeech: 'verb', example: '실험 결과를 검증해야 해요.', exampleTranslation: 'We need to verify the experimental results.', category: 'Science' },
    { id: '6-10', korean: '체계', english: 'System', pronunciation: 'che-gye', partOfSpeech: 'noun', example: '교육 체계를 개선해야 해요.', exampleTranslation: 'We need to improve the education system.', category: 'Professional' },
    { id: '6-11', korean: '방법론', english: 'Methodology', pronunciation: 'bang-beop-ron', partOfSpeech: 'noun', example: '연구 방법론을 설명해 주세요.', exampleTranslation: 'Please explain the research methodology.', category: 'Academic Writing' },
    { id: '6-12', korean: '패러다임', english: 'Paradigm', pronunciation: 'pae-reo-da-im', partOfSpeech: 'noun', example: '새로운 패러다임이 필요해요.', exampleTranslation: 'A new paradigm is needed.', category: 'Philosophy' },
    { id: '6-13', korean: '담론', english: 'Discourse', pronunciation: 'dam-ron', partOfSpeech: 'noun', example: '사회적 담론이 활발해요.', exampleTranslation: 'Social discourse is active.', category: 'Philosophy' },
    { id: '6-14', korean: '함의', english: 'Implication', pronunciation: 'ham-ui', partOfSpeech: 'noun', example: '이 결과의 함의를 논의해야 해요.', exampleTranslation: 'We need to discuss the implications of this result.', category: 'Academic Writing' },
    { id: '6-15', korean: '시사하다', english: 'To imply / Suggest', pronunciation: 'si-sa-ha-da', partOfSpeech: 'verb', example: '이 연구는 중요한 사실을 시사해요.', exampleTranslation: 'This study suggests an important fact.', category: 'Academic Writing' },
    { id: '6-16', korean: '도출하다', english: 'To derive', pronunciation: 'do-chul-ha-da', partOfSpeech: 'verb', example: '결론을 도출했어요.', exampleTranslation: 'I derived a conclusion.', category: 'Academic Writing' },
    { id: '6-17', korean: '종합하다', english: 'To synthesize', pronunciation: 'jong-hap-ha-da', partOfSpeech: 'verb', example: '여러 의견을 종합했어요.', exampleTranslation: 'I synthesized various opinions.', category: 'Academic Writing' },
    { id: '6-18', korean: '귀납적', english: 'Inductive', pronunciation: 'gwi-nap-jeok', partOfSpeech: 'adjective', example: '귀납적 추론을 사용했어요.', exampleTranslation: 'I used inductive reasoning.', category: 'Philosophy' },
    { id: '6-19', korean: '연역적', english: 'Deductive', pronunciation: 'yeon-yeok-jeok', partOfSpeech: 'adjective', example: '연역적 방법으로 분석했어요.', exampleTranslation: 'I analyzed using a deductive method.', category: 'Philosophy' },
    { id: '6-20', korean: '실증적', english: 'Empirical', pronunciation: 'sil-jeung-jeok', partOfSpeech: 'adjective', example: '실증적 연구가 필요해요.', exampleTranslation: 'Empirical research is needed.', category: 'Science' },
    { id: '6-21', korean: '외교', english: 'Diplomacy', pronunciation: 'oe-gyo', partOfSpeech: 'noun', example: '외교 관계가 중요해요.', exampleTranslation: 'Diplomatic relations are important.', category: 'Diplomacy' },
    { id: '6-22', korean: '조약', english: 'Treaty', pronunciation: 'jo-yak', partOfSpeech: 'noun', example: '두 나라가 조약을 체결했어요.', exampleTranslation: 'The two countries signed a treaty.', category: 'Diplomacy' },
    { id: '6-23', korean: '협상하다', english: 'To negotiate', pronunciation: 'hyeop-sang-ha-da', partOfSpeech: 'verb', example: '무역 협상이 진행 중이에요.', exampleTranslation: 'Trade negotiations are underway.', category: 'Diplomacy' },
    { id: '6-24', korean: '타결하다', english: 'To reach agreement', pronunciation: 'ta-gyeol-ha-da', partOfSpeech: 'verb', example: '합의가 드디어 타결되었어요.', exampleTranslation: 'An agreement was finally reached.', category: 'Diplomacy' },
    { id: '6-25', korean: '비준하다', english: 'To ratify', pronunciation: 'bi-jun-ha-da', partOfSpeech: 'verb', example: '국회가 조약을 비준했어요.', exampleTranslation: 'The parliament ratified the treaty.', category: 'Diplomacy' },
    { id: '6-26', korean: '제재', english: 'Sanctions', pronunciation: 'je-jae', partOfSpeech: 'noun', example: '경제 제재가 강화되었어요.', exampleTranslation: 'Economic sanctions were strengthened.', category: 'Diplomacy' },
    { id: '6-27', korean: '주권', english: 'Sovereignty', pronunciation: 'ju-gwon', partOfSpeech: 'noun', example: '국가의 주권을 존중해야 해요.', exampleTranslation: 'We must respect national sovereignty.', category: 'Diplomacy' },
    { id: '6-28', korean: '이행하다', english: 'To implement / Fulfill', pronunciation: 'i-haeng-ha-da', partOfSpeech: 'verb', example: '약속을 이행해야 해요.', exampleTranslation: 'We must fulfill our promise.', category: 'Formal Expressions' },
    { id: '6-29', korean: '선언', english: 'Declaration', pronunciation: 'seon-eon', partOfSpeech: 'noun', example: '독립 선언을 발표했어요.', exampleTranslation: 'A declaration of independence was announced.', category: 'Diplomacy' },
    { id: '6-30', korean: '결의', english: 'Resolution', pronunciation: 'gyeol-ui', partOfSpeech: 'noun', example: '유엔 결의안이 통과되었어요.', exampleTranslation: 'The UN resolution was passed.', category: 'Diplomacy' },
    { id: '6-31', korean: '소송', english: 'Lawsuit', pronunciation: 'so-song', partOfSpeech: 'noun', example: '소송을 제기했어요.', exampleTranslation: 'A lawsuit was filed.', category: 'Law' },
    { id: '6-32', korean: '판결', english: 'Verdict / Ruling', pronunciation: 'pan-gyeol', partOfSpeech: 'noun', example: '법원의 판결이 나왔어요.', exampleTranslation: 'The court\'s verdict was issued.', category: 'Law' },
    { id: '6-33', korean: '헌법', english: 'Constitution', pronunciation: 'heon-beop', partOfSpeech: 'noun', example: '헌법에 보장된 권리예요.', exampleTranslation: 'It is a right guaranteed by the constitution.', category: 'Law' },
    { id: '6-34', korean: '조항', english: 'Provision / Clause', pronunciation: 'jo-hang', partOfSpeech: 'noun', example: '계약의 조항을 확인하세요.', exampleTranslation: 'Please check the provisions of the contract.', category: 'Law' },
    { id: '6-35', korean: '위반하다', english: 'To violate', pronunciation: 'wi-ban-ha-da', partOfSpeech: 'verb', example: '규정을 위반하면 처벌받아요.', exampleTranslation: 'You will be punished if you violate the regulations.', category: 'Law' },
    { id: '6-36', korean: '제정하다', english: 'To enact / Establish', pronunciation: 'je-jeong-ha-da', partOfSpeech: 'verb', example: '새로운 법을 제정했어요.', exampleTranslation: 'A new law was enacted.', category: 'Law' },
    { id: '6-37', korean: '개정하다', english: 'To amend', pronunciation: 'gae-jeong-ha-da', partOfSpeech: 'verb', example: '법률을 개정할 예정이에요.', exampleTranslation: 'The law is scheduled to be amended.', category: 'Law' },
    { id: '6-38', korean: '준수하다', english: 'To comply', pronunciation: 'jun-su-ha-da', partOfSpeech: 'verb', example: '규칙을 준수해 주세요.', exampleTranslation: 'Please comply with the rules.', category: 'Formal Expressions' },
    { id: '6-39', korean: '규제', english: 'Regulation', pronunciation: 'gyu-je', partOfSpeech: 'noun', example: '환경 규제가 강화되고 있어요.', exampleTranslation: 'Environmental regulations are being strengthened.', category: 'Law' },
    { id: '6-40', korean: '면책', english: 'Immunity / Exemption', pronunciation: 'myeon-chaek', partOfSpeech: 'noun', example: '외교관에게는 면책 특권이 있어요.', exampleTranslation: 'Diplomats have immunity privileges.', category: 'Law' },
    { id: '6-41', korean: '기각하다', english: 'To dismiss / Reject', pronunciation: 'gi-gak-ha-da', partOfSpeech: 'verb', example: '법원이 소송을 기각했어요.', exampleTranslation: 'The court dismissed the lawsuit.', category: 'Law' },
    { id: '6-42', korean: '항소하다', english: 'To appeal', pronunciation: 'hang-so-ha-da', partOfSpeech: 'verb', example: '판결에 불복하여 항소했어요.', exampleTranslation: 'They appealed against the ruling.', category: 'Law' },
    { id: '6-43', korean: '관할권', english: 'Jurisdiction', pronunciation: 'gwan-hal-gwon', partOfSpeech: 'noun', example: '이 사건은 이 법원의 관할권에 속해요.', exampleTranslation: 'This case falls under this court\'s jurisdiction.', category: 'Law' },
    { id: '6-44', korean: '간주하다', english: 'To regard / Consider', pronunciation: 'gan-ju-ha-da', partOfSpeech: 'verb', example: '이 행위를 범죄로 간주해요.', exampleTranslation: 'This act is regarded as a crime.', category: 'Formal Expressions' },
    { id: '6-45', korean: '촉구하다', english: 'To urge', pronunciation: 'chok-gu-ha-da', partOfSpeech: 'verb', example: '즉각적인 조치를 촉구했어요.', exampleTranslation: 'Immediate action was urged.', category: 'Formal Expressions' },
    { id: '6-46', korean: '불가피하다', english: 'Unavoidable', pronunciation: 'bul-ga-pi-ha-da', partOfSpeech: 'adjective', example: '이 결정은 불가피했어요.', exampleTranslation: 'This decision was unavoidable.', category: 'Formal Expressions' },
    { id: '6-47', korean: '획기적', english: 'Groundbreaking', pronunciation: 'hoek-gi-jeok', partOfSpeech: 'adjective', example: '획기적인 발견이었어요.', exampleTranslation: 'It was a groundbreaking discovery.', category: 'Science' },
    { id: '6-48', korean: '포괄적', english: 'Comprehensive', pronunciation: 'po-gwal-jeok', partOfSpeech: 'adjective', example: '포괄적인 조사가 필요해요.', exampleTranslation: 'A comprehensive investigation is needed.', category: 'Formal Expressions' },
    { id: '6-49', korean: '배타적', english: 'Exclusive', pronunciation: 'bae-ta-jeok', partOfSpeech: 'adjective', example: '배타적 경제 수역을 설정했어요.', exampleTranslation: 'An exclusive economic zone was established.', category: 'Diplomacy' },
    { id: '6-50', korean: '잠정적', english: 'Tentative / Provisional', pronunciation: 'jam-jeong-jeok', partOfSpeech: 'adjective', example: '잠정적 합의에 도달했어요.', exampleTranslation: 'A tentative agreement was reached.', category: 'Formal Expressions' },
    { id: '6-51', korean: '심층적', english: 'In-depth', pronunciation: 'sim-cheung-jeok', partOfSpeech: 'adjective', example: '심층적인 분석이 필요해요.', exampleTranslation: 'An in-depth analysis is needed.', category: 'Academic Writing' },
    { id: '6-52', korean: '총체적', english: 'Holistic', pronunciation: 'chong-che-jeok', partOfSpeech: 'adjective', example: '총체적인 접근이 필요해요.', exampleTranslation: 'A holistic approach is needed.', category: 'Academic Writing' },
    { id: '6-53', korean: '자율적', english: 'Autonomous', pronunciation: 'ja-yul-jeok', partOfSpeech: 'adjective', example: '자율적인 학습이 중요해요.', exampleTranslation: 'Autonomous learning is important.', category: 'Professional' },
    { id: '6-54', korean: '시행하다', english: 'To enforce', pronunciation: 'si-haeng-ha-da', partOfSpeech: 'verb', example: '새 제도를 시행해요.', exampleTranslation: 'A new system is being enforced.', category: 'Professional' },
    { id: '6-55', korean: '폐지하다', english: 'To abolish', pronunciation: 'pye-ji-ha-da', partOfSpeech: 'verb', example: '그 제도는 폐지되었어요.', exampleTranslation: 'That system was abolished.', category: 'Professional' },
    { id: '6-56', korean: '정립하다', english: 'To establish (a theory)', pronunciation: 'jeong-rip-ha-da', partOfSpeech: 'verb', example: '새로운 이론을 정립했어요.', exampleTranslation: 'A new theory was established.', category: 'Science' },
    { id: '6-57', korean: '수립하다', english: 'To formulate', pronunciation: 'su-rip-ha-da', partOfSpeech: 'verb', example: '장기 계획을 수립했어요.', exampleTranslation: 'A long-term plan was formulated.', category: 'Professional' },
    { id: '6-58', korean: '구축하다', english: 'To build / Construct', pronunciation: 'gu-chuk-ha-da', partOfSpeech: 'verb', example: '신뢰를 구축하는 것이 중요해요.', exampleTranslation: 'Building trust is important.', category: 'Professional' },
    { id: '6-59', korean: '통합하다', english: 'To integrate', pronunciation: 'tong-hap-ha-da', partOfSpeech: 'verb', example: '두 시스템을 통합했어요.', exampleTranslation: 'The two systems were integrated.', category: 'Professional' },
    { id: '6-60', korean: '재편하다', english: 'To reorganize', pronunciation: 'jae-pyeon-ha-da', partOfSpeech: 'verb', example: '조직을 재편할 계획이에요.', exampleTranslation: 'There are plans to reorganize the organization.', category: 'Professional' },
  ],
};

export function getWordsForLevel(levelId: string): Word[] {
  return VOCABULARY_DATA[levelId] || [];
}

export function getDailyWords(levelId: string, day: number, wordsPerDay: number = 20): Word[] {
  const allWords = getWordsForLevel(levelId);
  const startIndex = ((day - 1) * wordsPerDay) % allWords.length;
  const words: Word[] = [];
  for (let i = 0; i < wordsPerDay; i++) {
    words.push(allWords[(startIndex + i) % allWords.length]);
  }
  return words;
}

export function generateQuizOptions(correctWord: Word, allWords: Word[], count: number = 4): string[] {
  const options = [correctWord.english];
  const otherWords = allWords.filter(w => w.id !== correctWord.id);
  const shuffled = [...otherWords].sort(() => Math.random() - 0.5);
  for (const w of shuffled) {
    if (options.length >= count) break;
    if (!options.includes(w.english)) {
      options.push(w.english);
    }
  }
  while (options.length < count) {
    options.push(`Option ${options.length + 1}`);
  }
  return options.sort(() => Math.random() - 0.5);
}

export function getAllWords(): Word[] {
  return Object.values(VOCABULARY_DATA).flat();
}
