import { ThemeWord } from '../theme-data';

export const KDRAMA_WORDS: Record<number, ThemeWord[]> = {
  1: [
    { korean: '안녕하세요', english: 'Hello (formal)', pronunciation: 'an-nyeong-ha-se-yo', example: '안녕하세요, 처음 뵙겠습니다.', exampleTranslation: 'Hello, nice to meet you.' },
    { korean: '감사합니다', english: 'Thank you', pronunciation: 'gam-sa-ham-ni-da', example: '도와주셔서 감사합니다.', exampleTranslation: 'Thank you for helping me.' },
    { korean: '네', english: 'Yes', pronunciation: 'ne', example: '네, 알겠습니다.', exampleTranslation: 'Yes, I understand.' },
    { korean: '아니요', english: 'No', pronunciation: 'a-ni-yo', example: '아니요, 괜찮아요.', exampleTranslation: 'No, it is okay.' },
    { korean: '사랑', english: 'Love', pronunciation: 'sa-rang', example: '사랑은 아름다운 거야.', exampleTranslation: 'Love is a beautiful thing.' },
    { korean: '행복', english: 'Happiness', pronunciation: 'haeng-bok', example: '나는 지금 행복해.', exampleTranslation: 'I am happy right now.' },
    { korean: '슬픔', english: 'Sadness', pronunciation: 'seul-peum', example: '슬픔이 밀려왔어.', exampleTranslation: 'Sadness washed over me.' },
    { korean: '웃다', english: 'To laugh / smile', pronunciation: 'ut-da', example: '왜 웃어? 뭐가 웃겨?', exampleTranslation: 'Why are you laughing? What is funny?' },
    { korean: '울다', english: 'To cry', pronunciation: 'ul-da', example: '울지 마, 다 괜찮아질 거야.', exampleTranslation: 'Don\'t cry, everything will be okay.' },
    { korean: '가다', english: 'To go', pronunciation: 'ga-da', example: '같이 가자!', exampleTranslation: 'Let\'s go together!' },
    { korean: '오다', english: 'To come', pronunciation: 'o-da', example: '빨리 와!', exampleTranslation: 'Come quickly!' },
    { korean: '먹다', english: 'To eat', pronunciation: 'meok-da', example: '뭐 먹을래?', exampleTranslation: 'What do you want to eat?' },
    { korean: '마시다', english: 'To drink', pronunciation: 'ma-si-da', example: '물 좀 마실래?', exampleTranslation: 'Do you want to drink some water?' },
    { korean: '자다', english: 'To sleep', pronunciation: 'ja-da', example: '일찍 자, 내일 바쁘잖아.', exampleTranslation: 'Sleep early, you are busy tomorrow.' },
    { korean: '좋다', english: 'Good / to like', pronunciation: 'jo-ta', example: '오늘 날씨 좋다!', exampleTranslation: 'The weather is nice today!' },
    { korean: '싫다', english: 'To dislike', pronunciation: 'sil-ta', example: '그 사람 싫어.', exampleTranslation: 'I don\'t like that person.' },
    { korean: '예쁘다', english: 'Pretty', pronunciation: 'ye-ppeu-da', example: '오늘 정말 예쁘다.', exampleTranslation: 'You look really pretty today.' },
    { korean: '멋있다', english: 'Cool / handsome', pronunciation: 'meot-it-da', example: '와, 진짜 멋있다!', exampleTranslation: 'Wow, so cool!' },
    { korean: '아프다', english: 'To hurt / sick', pronunciation: 'a-peu-da', example: '어디 아파?', exampleTranslation: 'Where does it hurt?' },
    { korean: '배고프다', english: 'To be hungry', pronunciation: 'bae-go-peu-da', example: '배고파, 밥 먹자.', exampleTranslation: 'I\'m hungry, let\'s eat.' },
    { korean: '피곤하다', english: 'To be tired', pronunciation: 'pi-gon-ha-da', example: '오늘 너무 피곤해.', exampleTranslation: 'I am so tired today.' },
    { korean: '집', english: 'Home / house', pronunciation: 'jip', example: '집에 가고 싶어.', exampleTranslation: 'I want to go home.' },
    { korean: '학교', english: 'School', pronunciation: 'hak-gyo', example: '학교에서 만나자.', exampleTranslation: 'Let\'s meet at school.' },
    { korean: '친구', english: 'Friend', pronunciation: 'chin-gu', example: '너는 내 소중한 친구야.', exampleTranslation: 'You are my precious friend.' },
    { korean: '가족', english: 'Family', pronunciation: 'ga-jok', example: '가족이 제일 중요해.', exampleTranslation: 'Family is the most important.' },
    { korean: '엄마', english: 'Mom', pronunciation: 'eom-ma', example: '엄마, 나 왔어!', exampleTranslation: 'Mom, I\'m home!' },
    { korean: '아빠', english: 'Dad', pronunciation: 'a-ppa', example: '아빠가 보고 싶어.', exampleTranslation: 'I miss Dad.' },
    { korean: '이름', english: 'Name', pronunciation: 'i-reum', example: '이름이 뭐예요?', exampleTranslation: 'What is your name?' },
    { korean: '나이', english: 'Age', pronunciation: 'na-i', example: '나이가 어떻게 되세요?', exampleTranslation: 'How old are you?' },
    { korean: '물', english: 'Water', pronunciation: 'mul', example: '물 한 잔 주세요.', exampleTranslation: 'One glass of water please.' },
    { korean: '밥', english: 'Rice / meal', pronunciation: 'bap', example: '밥 먹었어?', exampleTranslation: 'Have you eaten?' },
    { korean: '사람', english: 'Person', pronunciation: 'sa-ram', example: '좋은 사람 만났어.', exampleTranslation: 'I met a good person.' },
    { korean: '시간', english: 'Time', pronunciation: 'si-gan', example: '시간이 없어!', exampleTranslation: 'There\'s no time!' },
    { korean: '오늘', english: 'Today', pronunciation: 'o-neul', example: '오늘 뭐 해?', exampleTranslation: 'What are you doing today?' },
    { korean: '내일', english: 'Tomorrow', pronunciation: 'nae-il', example: '내일 만나자.', exampleTranslation: 'Let\'s meet tomorrow.' },
    { korean: '어제', english: 'Yesterday', pronunciation: 'eo-je', example: '어제 뭐 했어?', exampleTranslation: 'What did you do yesterday?' },
    { korean: '지금', english: 'Now', pronunciation: 'ji-geum', example: '지금 어디야?', exampleTranslation: 'Where are you now?' },
    { korean: '여기', english: 'Here', pronunciation: 'yeo-gi', example: '여기 앉아.', exampleTranslation: 'Sit here.' },
    { korean: '거기', english: 'There', pronunciation: 'geo-gi', example: '거기 서!', exampleTranslation: 'Stop right there!' },
    { korean: '왜', english: 'Why', pronunciation: 'wae', example: '왜 그래?', exampleTranslation: 'What\'s wrong?' },
    { korean: '어디', english: 'Where', pronunciation: 'eo-di', example: '어디 가?', exampleTranslation: 'Where are you going?' },
    { korean: '누구', english: 'Who', pronunciation: 'nu-gu', example: '누구세요?', exampleTranslation: 'Who is it?' },
    { korean: '뭐', english: 'What', pronunciation: 'mwo', example: '뭐라고?', exampleTranslation: 'What did you say?' },
    { korean: '어떻게', english: 'How', pronunciation: 'eo-tteo-ke', example: '어떻게 알았어?', exampleTranslation: 'How did you know?' },
    { korean: '많이', english: 'A lot', pronunciation: 'ma-ni', example: '많이 먹어.', exampleTranslation: 'Eat a lot.' },
    { korean: '조금', english: 'A little', pronunciation: 'jo-geum', example: '조금만 기다려.', exampleTranslation: 'Wait just a little.' },
    { korean: '빨리', english: 'Quickly', pronunciation: 'ppal-li', example: '빨리 나와!', exampleTranslation: 'Come out quickly!' },
    { korean: '천천히', english: 'Slowly', pronunciation: 'cheon-cheon-hi', example: '천천히 말해 줘.', exampleTranslation: 'Speak slowly please.' },
    { korean: '같이', english: 'Together', pronunciation: 'ga-chi', example: '같이 있고 싶어.', exampleTranslation: 'I want to be together.' },
    { korean: '혼자', english: 'Alone', pronunciation: 'hon-ja', example: '혼자 있고 싶어.', exampleTranslation: 'I want to be alone.' },
    { korean: '정말', english: 'Really / truly', pronunciation: 'jeong-mal', example: '정말이야?', exampleTranslation: 'Is it true?' },
    { korean: '너무', english: 'Too much / very', pronunciation: 'neo-mu', example: '너무 좋아!', exampleTranslation: 'So great!' },
    { korean: '또', english: 'Again', pronunciation: 'tto', example: '또 만나자.', exampleTranslation: 'Let\'s meet again.' },
    { korean: '안', english: 'Not (negation)', pronunciation: 'an', example: '안 돼!', exampleTranslation: 'No! / You can\'t!' },
    { korean: '잘', english: 'Well', pronunciation: 'jal', example: '잘 자.', exampleTranslation: 'Good night.' },
    { korean: '못', english: 'Cannot', pronunciation: 'mot', example: '못 가.', exampleTranslation: 'I can\'t go.' },
    { korean: '더', english: 'More', pronunciation: 'deo', example: '더 이상 못 참아.', exampleTranslation: 'I can\'t take it anymore.' },
    { korean: '남자', english: 'Man', pronunciation: 'nam-ja', example: '저 남자 누구야?', exampleTranslation: 'Who is that man?' },
    { korean: '여자', english: 'Woman', pronunciation: 'yeo-ja', example: '그 여자 예쁘다.', exampleTranslation: 'That woman is pretty.' },
    { korean: '아이', english: 'Child', pronunciation: 'a-i', example: '아이가 울고 있어.', exampleTranslation: 'The child is crying.' },
    { korean: '선생님', english: 'Teacher', pronunciation: 'seon-saeng-nim', example: '선생님, 감사합니다.', exampleTranslation: 'Thank you, teacher.' },
    { korean: '의사', english: 'Doctor', pronunciation: 'ui-sa', example: '의사 선생님을 만나야 해.', exampleTranslation: 'I need to see a doctor.' },
    { korean: '일', english: 'Work / day', pronunciation: 'il', example: '일이 많아.', exampleTranslation: 'I have a lot of work.' },
    { korean: '돈', english: 'Money', pronunciation: 'don', example: '돈이 없어.', exampleTranslation: 'I have no money.' },
    { korean: '꿈', english: 'Dream', pronunciation: 'kkum', example: '꿈이 뭐야?', exampleTranslation: 'What is your dream?' },
    { korean: '마음', english: 'Heart / mind', pronunciation: 'ma-eum', example: '내 마음 알아?', exampleTranslation: 'Do you know my heart?' },
    { korean: '눈', english: 'Eyes / snow', pronunciation: 'nun', example: '눈이 예쁘다.', exampleTranslation: 'Your eyes are pretty.' },
    { korean: '손', english: 'Hand', pronunciation: 'son', example: '손 잡아도 돼?', exampleTranslation: 'Can I hold your hand?' },
    { korean: '전화', english: 'Phone call', pronunciation: 'jeon-hwa', example: '전화 좀 받아!', exampleTranslation: 'Answer the phone!' },
    { korean: '문', english: 'Door', pronunciation: 'mun', example: '문 열어!', exampleTranslation: 'Open the door!' },
    { korean: '차', english: 'Car / tea', pronunciation: 'cha', example: '차 타자.', exampleTranslation: 'Let\'s get in the car.' },
    { korean: '노래', english: 'Song', pronunciation: 'no-rae', example: '이 노래 좋다.', exampleTranslation: 'This song is nice.' },
    { korean: '기분', english: 'Mood / feeling', pronunciation: 'gi-bun', example: '기분이 좋아.', exampleTranslation: 'I\'m in a good mood.' },
    { korean: '걱정', english: 'Worry', pronunciation: 'geok-jeong', example: '걱정하지 마.', exampleTranslation: 'Don\'t worry.' },
    { korean: '약속', english: 'Promise', pronunciation: 'yak-sok', example: '약속해 줘.', exampleTranslation: 'Promise me.' },
    { korean: '비밀', english: 'Secret', pronunciation: 'bi-mil', example: '비밀이야, 말하지 마.', exampleTranslation: 'It\'s a secret, don\'t tell anyone.' },
    { korean: '미안', english: 'Sorry (casual)', pronunciation: 'mi-an', example: '미안, 늦었어.', exampleTranslation: 'Sorry, I\'m late.' },
    { korean: '고마워', english: 'Thanks (casual)', pronunciation: 'go-ma-wo', example: '진심으로 고마워.', exampleTranslation: 'Thank you sincerely.' },
    { korean: '알았어', english: 'Got it', pronunciation: 'ar-ass-eo', example: '알았어, 알았어!', exampleTranslation: 'Okay, okay!' },
    { korean: '몰라', english: 'I don\'t know', pronunciation: 'mol-la', example: '나도 몰라.', exampleTranslation: 'I don\'t know either.' },
    { korean: '싫어', english: 'I don\'t like it', pronunciation: 'sir-eo', example: '싫어! 안 할 거야.', exampleTranslation: 'No! I won\'t do it.' },
    { korean: '무서워', english: 'I\'m scared', pronunciation: 'mu-seo-wo', example: '무서워, 같이 가.', exampleTranslation: 'I\'m scared, come with me.' },
    { korean: '기다려', english: 'Wait', pronunciation: 'gi-da-ryeo', example: '잠깐 기다려!', exampleTranslation: 'Wait a moment!' },
    { korean: '도와줘', english: 'Help me', pronunciation: 'do-wa-jwo', example: '제발 도와줘!', exampleTranslation: 'Please help me!' },
    { korean: '앉아', english: 'Sit down', pronunciation: 'an-ja', example: '여기 앉아.', exampleTranslation: 'Sit here.' },
    { korean: '일어나', english: 'Get up / wake up', pronunciation: 'ir-eo-na', example: '일어나! 학교 가야지.', exampleTranslation: 'Wake up! You have to go to school.' },
    { korean: '조심해', english: 'Be careful', pronunciation: 'jo-sim-hae', example: '조심해, 위험해!', exampleTranslation: 'Be careful, it\'s dangerous!' },
    { korean: '축하해', english: 'Congratulations', pronunciation: 'chuk-ha-hae', example: '합격 축하해!', exampleTranslation: 'Congratulations on passing!' },
    { korean: '화이팅', english: 'Fighting! (cheer)', pronunciation: 'hwa-i-ting', example: '시험 화이팅!', exampleTranslation: 'Good luck on the exam!' },
    { korean: '대박', english: 'Awesome / jackpot', pronunciation: 'dae-bak', example: '대박! 진짜야?', exampleTranslation: 'Awesome! For real?' },
    { korean: '바보', english: 'Fool / dummy', pronunciation: 'ba-bo', example: '이 바보야!', exampleTranslation: 'You dummy!' },
    { korean: '귀엽다', english: 'Cute', pronunciation: 'gwi-yeop-da', example: '아, 진짜 귀엽다!', exampleTranslation: 'Ah, so cute!' },
    { korean: '무슨 일', english: 'What happened', pronunciation: 'mu-seun il', example: '무슨 일이야?', exampleTranslation: 'What happened?' },
    { korean: '다시', english: 'Again', pronunciation: 'da-si', example: '다시 한번 해 봐.', exampleTranslation: 'Try again.' },
    { korean: '아직', english: 'Still / yet', pronunciation: 'a-jik', example: '아직 안 왔어?', exampleTranslation: 'Hasn\'t come yet?' },
    { korean: '벌써', english: 'Already', pronunciation: 'beol-sseo', example: '벌써 끝났어?', exampleTranslation: 'Already finished?' },
    { korean: '항상', english: 'Always', pronunciation: 'hang-sang', example: '항상 네 편이야.', exampleTranslation: 'I\'m always on your side.' },
    { korean: '절대', english: 'Absolutely / never', pronunciation: 'jeol-dae', example: '절대 안 돼!', exampleTranslation: 'Absolutely not!' },
    { korean: '그래', english: 'Okay / yeah', pronunciation: 'geu-rae', example: '그래, 알겠어.', exampleTranslation: 'Okay, I understand.' },
    { korean: '나가', english: 'Get out', pronunciation: 'na-ga', example: '당장 나가!', exampleTranslation: 'Get out right now!' },
  ],
  2: [
    { korean: '남자친구', english: 'Boyfriend', pronunciation: 'nam-ja-chin-gu', example: '남자친구 생겼어?', exampleTranslation: 'Did you get a boyfriend?' },
    { korean: '여자친구', english: 'Girlfriend', pronunciation: 'yeo-ja-chin-gu', example: '여자친구가 예뻐요.', exampleTranslation: 'My girlfriend is pretty.' },
    { korean: '소개팅', english: 'Blind date', pronunciation: 'so-gae-ting', example: '내일 소개팅이 있어.', exampleTranslation: 'I have a blind date tomorrow.' },
    { korean: '고백', english: 'Confession (of love)', pronunciation: 'go-baek', example: '오늘 고백할 거야.', exampleTranslation: 'I\'m going to confess today.' },
    { korean: '데이트', english: 'Date', pronunciation: 'de-i-teu', example: '주말에 데이트하자.', exampleTranslation: 'Let\'s go on a date this weekend.' },
    { korean: '설렘', english: 'Flutter / excitement', pronunciation: 'seol-lem', example: '설렘이 멈추지 않아.', exampleTranslation: 'My heart won\'t stop fluttering.' },
    { korean: '질투', english: 'Jealousy', pronunciation: 'jil-tu', example: '질투하는 거야?', exampleTranslation: 'Are you jealous?' },
    { korean: '외로움', english: 'Loneliness', pronunciation: 'oe-ro-um', example: '외로움을 느끼고 있어.', exampleTranslation: 'I\'m feeling lonely.' },
    { korean: '거짓말', english: 'Lie', pronunciation: 'geo-jin-mal', example: '거짓말하지 마!', exampleTranslation: 'Don\'t lie!' },
    { korean: '진심', english: 'Sincerity / true feelings', pronunciation: 'jin-sim', example: '진심이야, 믿어 줘.', exampleTranslation: 'I\'m sincere, please believe me.' },
    { korean: '오해', english: 'Misunderstanding', pronunciation: 'o-hae', example: '오해하지 마.', exampleTranslation: 'Don\'t misunderstand.' },
    { korean: '화', english: 'Anger', pronunciation: 'hwa', example: '왜 화를 내?', exampleTranslation: 'Why are you angry?' },
    { korean: '용서', english: 'Forgiveness', pronunciation: 'yong-seo', example: '용서해 줄 수 있어?', exampleTranslation: 'Can you forgive me?' },
    { korean: '이별', english: 'Parting / farewell', pronunciation: 'i-byeol', example: '이별은 항상 슬프다.', exampleTranslation: 'Partings are always sad.' },
    { korean: '추억', english: 'Memory / remembrance', pronunciation: 'chu-eok', example: '좋은 추억 만들자.', exampleTranslation: 'Let\'s make good memories.' },
    { korean: '행복하다', english: 'To be happy', pronunciation: 'haeng-bok-ha-da', example: '너와 함께여서 행복해.', exampleTranslation: 'I\'m happy to be with you.' },
    { korean: '슬프다', english: 'To be sad', pronunciation: 'seul-peu-da', example: '왜 이렇게 슬퍼?', exampleTranslation: 'Why are you so sad?' },
    { korean: '화나다', english: 'To be angry', pronunciation: 'hwa-na-da', example: '진짜 화나!', exampleTranslation: 'I\'m really angry!' },
    { korean: '부끄럽다', english: 'To be embarrassed', pronunciation: 'bu-kkeu-reop-da', example: '부끄러워서 말 못 했어.', exampleTranslation: 'I was too embarrassed to say it.' },
    { korean: '그립다', english: 'To miss (someone)', pronunciation: 'geu-rip-da', example: '고향이 그립다.', exampleTranslation: 'I miss my hometown.' },
    { korean: '실망하다', english: 'To be disappointed', pronunciation: 'sil-mang-ha-da', example: '너한테 실망했어.', exampleTranslation: 'I\'m disappointed in you.' },
    { korean: '후회하다', english: 'To regret', pronunciation: 'hu-hoe-ha-da', example: '후회하지 않을 거야.', exampleTranslation: 'I won\'t regret it.' },
    { korean: '믿다', english: 'To believe / trust', pronunciation: 'mit-da', example: '나를 믿어 줘.', exampleTranslation: 'Trust me.' },
    { korean: '사귀다', english: 'To date / go out', pronunciation: 'sa-gwi-da', example: '우리 사귀는 거야?', exampleTranslation: 'Are we dating?' },
    { korean: '결혼', english: 'Marriage', pronunciation: 'gyeol-hon', example: '결혼 생각 있어?', exampleTranslation: 'Are you thinking about marriage?' },
    { korean: '이혼', english: 'Divorce', pronunciation: 'i-hon', example: '이혼하고 싶어.', exampleTranslation: 'I want a divorce.' },
    { korean: '사과하다', english: 'To apologize', pronunciation: 'sa-gwa-ha-da', example: '먼저 사과해.', exampleTranslation: 'Apologize first.' },
    { korean: '약혼', english: 'Engagement', pronunciation: 'ya-kon', example: '약혼 축하해!', exampleTranslation: 'Congratulations on the engagement!' },
    { korean: '선물', english: 'Gift / present', pronunciation: 'seon-mul', example: '생일 선물 준비했어.', exampleTranslation: 'I prepared a birthday gift.' },
    { korean: '생일', english: 'Birthday', pronunciation: 'saeng-il', example: '생일 축하해!', exampleTranslation: 'Happy birthday!' },
    { korean: '회사', english: 'Company / office', pronunciation: 'hoe-sa', example: '회사에 늦겠다!', exampleTranslation: 'I\'m going to be late to the office!' },
    { korean: '학생', english: 'Student', pronunciation: 'hak-saeng', example: '아직 학생이에요.', exampleTranslation: 'I\'m still a student.' },
    { korean: '선배', english: 'Senior (at school/work)', pronunciation: 'seon-bae', example: '선배, 도와주세요.', exampleTranslation: 'Senior, please help me.' },
    { korean: '후배', english: 'Junior (at school/work)', pronunciation: 'hu-bae', example: '후배가 들어왔어.', exampleTranslation: 'A new junior came in.' },
    { korean: '동료', english: 'Colleague', pronunciation: 'dong-nyo', example: '동료들이랑 밥 먹었어.', exampleTranslation: 'I ate with my colleagues.' },
    { korean: '출근', english: 'Going to work', pronunciation: 'chul-geun', example: '출근 시간이야!', exampleTranslation: 'It\'s time to go to work!' },
    { korean: '퇴근', english: 'Leaving work', pronunciation: 'toe-geun', example: '오늘 일찍 퇴근해도 돼?', exampleTranslation: 'Can I leave work early today?' },
    { korean: '주말', english: 'Weekend', pronunciation: 'ju-mal', example: '주말에 뭐 해?', exampleTranslation: 'What are you doing this weekend?' },
    { korean: '방학', english: 'School vacation', pronunciation: 'bang-hak', example: '방학이라서 신나!', exampleTranslation: 'I\'m excited because it\'s vacation!' },
    { korean: '여행', english: 'Travel', pronunciation: 'yeo-haeng', example: '여행 가고 싶다.', exampleTranslation: 'I want to travel.' },
    { korean: '영화', english: 'Movie', pronunciation: 'yeong-hwa', example: '영화 보러 갈래?', exampleTranslation: 'Do you want to go see a movie?' },
    { korean: '음악', english: 'Music', pronunciation: 'eum-ak', example: '무슨 음악 좋아해?', exampleTranslation: 'What music do you like?' },
    { korean: '사진', english: 'Photo', pronunciation: 'sa-jin', example: '같이 사진 찍자.', exampleTranslation: 'Let\'s take a photo together.' },
    { korean: '카페', english: 'Cafe', pronunciation: 'ka-pe', example: '카페에서 만날까?', exampleTranslation: 'Shall we meet at a cafe?' },
    { korean: '병원', english: 'Hospital', pronunciation: 'byeong-won', example: '병원에 가 봐.', exampleTranslation: 'Go to the hospital.' },
    { korean: '식당', english: 'Restaurant', pronunciation: 'sik-dang', example: '맛있는 식당 알아?', exampleTranslation: 'Do you know a good restaurant?' },
    { korean: '공원', english: 'Park', pronunciation: 'gong-won', example: '공원에서 산책하자.', exampleTranslation: 'Let\'s take a walk in the park.' },
    { korean: '날씨', english: 'Weather', pronunciation: 'nal-ssi', example: '오늘 날씨 어때?', exampleTranslation: 'How is the weather today?' },
    { korean: '비', english: 'Rain', pronunciation: 'bi', example: '비가 와, 우산 가져가.', exampleTranslation: 'It\'s raining, take an umbrella.' },
    { korean: '첫눈', english: 'First snow', pronunciation: 'cheot-nun', example: '첫눈이 왔어!', exampleTranslation: 'The first snow came!' },
    { korean: '봄', english: 'Spring', pronunciation: 'bom', example: '봄이 오면 벚꽃이 펴.', exampleTranslation: 'Cherry blossoms bloom when spring comes.' },
    { korean: '여름', english: 'Summer', pronunciation: 'yeo-reum', example: '여름에 바다 가자.', exampleTranslation: 'Let\'s go to the sea in summer.' },
    { korean: '겨울', english: 'Winter', pronunciation: 'gyeo-ul', example: '겨울이 너무 추워.', exampleTranslation: 'Winter is so cold.' },
    { korean: '옷', english: 'Clothes', pronunciation: 'ot', example: '새 옷 샀어.', exampleTranslation: 'I bought new clothes.' },
    { korean: '전화하다', english: 'To make a phone call', pronunciation: 'jeon-hwa-ha-da', example: '나중에 전화할게.', exampleTranslation: 'I\'ll call you later.' },
    { korean: '문자', english: 'Text message', pronunciation: 'mun-ja', example: '문자 보냈어.', exampleTranslation: 'I sent a text message.' },
    { korean: '만나다', english: 'To meet', pronunciation: 'man-na-da', example: '언제 만날까?', exampleTranslation: 'When shall we meet?' },
    { korean: '기억', english: 'Memory', pronunciation: 'gi-eok', example: '그때 기억나?', exampleTranslation: 'Do you remember that time?' },
    { korean: '계획', english: 'Plan', pronunciation: 'gye-hoek', example: '무슨 계획 있어?', exampleTranslation: 'Do you have any plans?' },
    { korean: '이유', english: 'Reason', pronunciation: 'i-yu', example: '이유가 뭐야?', exampleTranslation: 'What is the reason?' },
    { korean: '대답', english: 'Answer / reply', pronunciation: 'dae-dap', example: '대답 좀 해 봐!', exampleTranslation: 'Give me an answer!' },
    { korean: '실수', english: 'Mistake', pronunciation: 'sil-su', example: '실수했어, 미안해.', exampleTranslation: 'I made a mistake, sorry.' },
    { korean: '노력', english: 'Effort', pronunciation: 'no-ryeok', example: '더 노력할게.', exampleTranslation: 'I\'ll try harder.' },
    { korean: '건강', english: 'Health', pronunciation: 'geon-gang', example: '건강이 제일 중요해.', exampleTranslation: 'Health is the most important thing.' },
    { korean: '습관', english: 'Habit', pronunciation: 'seup-gwan', example: '나쁜 습관 고쳐야 해.', exampleTranslation: 'You need to fix bad habits.' },
    { korean: '특별하다', english: 'To be special', pronunciation: 'teuk-byeol-ha-da', example: '너는 특별해.', exampleTranslation: 'You are special.' },
    { korean: '중요하다', english: 'To be important', pronunciation: 'jung-yo-ha-da', example: '이건 정말 중요해.', exampleTranslation: 'This is really important.' },
    { korean: '위험하다', english: 'To be dangerous', pronunciation: 'wi-heom-ha-da', example: '거기 가면 위험해!', exampleTranslation: 'It\'s dangerous to go there!' },
    { korean: '편하다', english: 'To be comfortable', pronunciation: 'pyeon-ha-da', example: '너랑 있으면 편해.', exampleTranslation: 'I\'m comfortable when I\'m with you.' },
    { korean: '어렵다', english: 'Difficult', pronunciation: 'eo-ryeop-da', example: '한국어 어렵다!', exampleTranslation: 'Korean is difficult!' },
    { korean: '쉽다', english: 'Easy', pronunciation: 'swip-da', example: '이건 쉬운 문제야.', exampleTranslation: 'This is an easy problem.' },
    { korean: '재미있다', english: 'Fun / interesting', pronunciation: 'jae-mi-it-da', example: '이 드라마 재미있다!', exampleTranslation: 'This drama is fun!' },
    { korean: '심심하다', english: 'To be bored', pronunciation: 'sim-sim-ha-da', example: '심심해, 뭐 하자.', exampleTranslation: 'I\'m bored, let\'s do something.' },
    { korean: '춥다', english: 'Cold (weather)', pronunciation: 'chup-da', example: '오늘 진짜 춥다.', exampleTranslation: 'It\'s really cold today.' },
    { korean: '덥다', english: 'Hot (weather)', pronunciation: 'deop-da', example: '너무 더워!', exampleTranslation: 'It\'s too hot!' },
    { korean: '놀라다', english: 'To be surprised', pronunciation: 'nol-la-da', example: '깜짝 놀랐어!', exampleTranslation: 'I was so surprised!' },
    { korean: '궁금하다', english: 'To be curious', pronunciation: 'gung-geum-ha-da', example: '그 사람이 궁금해.', exampleTranslation: 'I\'m curious about that person.' },
    { korean: '부탁하다', english: 'To ask a favor', pronunciation: 'bu-tak-ha-da', example: '부탁 하나만 할게.', exampleTranslation: 'Let me ask one favor.' },
    { korean: '감동', english: 'Being moved / touched', pronunciation: 'gam-dong', example: '감동이야, 고마워.', exampleTranslation: 'I\'m moved, thank you.' },
    { korean: '자신감', english: 'Confidence', pronunciation: 'ja-sin-gam', example: '자신감을 가져!', exampleTranslation: 'Have confidence!' },
    { korean: '응원', english: 'Cheering / support', pronunciation: 'eung-won', example: '항상 응원할게.', exampleTranslation: 'I\'ll always support you.' },
    { korean: '기대', english: 'Expectation', pronunciation: 'gi-dae', example: '기대하고 있을게.', exampleTranslation: 'I\'ll be looking forward to it.' },
    { korean: '연락', english: 'Contact', pronunciation: 'yeol-lak', example: '연락해 줘.', exampleTranslation: 'Contact me.' },
    { korean: '소식', english: 'News / updates', pronunciation: 'so-sik', example: '무슨 소식 있어?', exampleTranslation: 'Any news?' },
    { korean: '관심', english: 'Interest / attention', pronunciation: 'gwan-sim', example: '나한테 관심 있어?', exampleTranslation: 'Are you interested in me?' },
    { korean: '포기하다', english: 'To give up', pronunciation: 'po-gi-ha-da', example: '절대 포기하지 마.', exampleTranslation: 'Never give up.' },
    { korean: '참다', english: 'To endure', pronunciation: 'cham-da', example: '더 이상 못 참아!', exampleTranslation: 'I can\'t endure it anymore!' },
    { korean: '속상하다', english: 'To be upset', pronunciation: 'sok-sang-ha-da', example: '속상해서 울었어.', exampleTranslation: 'I cried because I was upset.' },
    { korean: '다행이다', english: 'What a relief', pronunciation: 'da-haeng-i-da', example: '무사해서 다행이다.', exampleTranslation: 'I\'m relieved you\'re safe.' },
    { korean: '익숙하다', english: 'To be familiar / used to', pronunciation: 'ik-suk-ha-da', example: '아직 익숙하지 않아.', exampleTranslation: 'I\'m not used to it yet.' },
    { korean: '어울리다', english: 'To suit / match', pronunciation: 'eo-ul-li-da', example: '그 옷 잘 어울려.', exampleTranslation: 'That outfit suits you well.' },
    { korean: '사이', english: 'Relationship / between', pronunciation: 'sa-i', example: '우리 사이 좋잖아.', exampleTranslation: 'We have a good relationship.' },
    { korean: '인연', english: 'Fate / connection', pronunciation: 'in-yeon', example: '우리는 인연인가 봐.', exampleTranslation: 'We must be fated.' },
    { korean: '상처', english: 'Wound / hurt', pronunciation: 'sang-cheo', example: '상처 받았어.', exampleTranslation: 'I was hurt.' },
    { korean: '위로', english: 'Comfort / consolation', pronunciation: 'wi-ro', example: '네가 위로가 돼.', exampleTranslation: 'You are my comfort.' },
    { korean: '힘들다', english: 'To be tough / hard', pronunciation: 'him-deul-da', example: '요즘 많이 힘들어.', exampleTranslation: 'Things are really tough lately.' },
    { korean: '부럽다', english: 'To be envious', pronunciation: 'bu-reop-da', example: '정말 부럽다!', exampleTranslation: 'I\'m so envious!' },
    { korean: '안타깝다', english: 'To feel sorry / regrettable', pronunciation: 'an-ta-kkap-da', example: '정말 안타까워.', exampleTranslation: 'That\'s really unfortunate.' },
    { korean: '설마', english: 'No way / surely not', pronunciation: 'seol-ma', example: '설마 사실이야?', exampleTranslation: 'Surely it\'s not true?' },
    { korean: '떨어지다', english: 'To fall / be apart', pronunciation: 'tteol-eo-ji-da', example: '떨어지기 싫어.', exampleTranslation: 'I don\'t want to be apart.' },
  ],
  3: [
    { korean: '사장님', english: 'Boss / CEO', pronunciation: 'sa-jang-nim', example: '사장님, 보고 드리겠습니다.', exampleTranslation: 'Boss, I\'ll give you the report.' },
    { korean: '과장님', english: 'Section chief', pronunciation: 'gwa-jang-nim', example: '과장님이 부르셔요.', exampleTranslation: 'The section chief is calling for you.' },
    { korean: '회의', english: 'Meeting', pronunciation: 'hoe-ui', example: '회의가 길어졌어요.', exampleTranslation: 'The meeting ran long.' },
    { korean: '보고서', english: 'Report', pronunciation: 'bo-go-seo', example: '보고서 다 썼어?', exampleTranslation: 'Did you finish writing the report?' },
    { korean: '프로젝트', english: 'Project', pronunciation: 'peu-ro-jek-teu', example: '이번 프로젝트 중요해요.', exampleTranslation: 'This project is important.' },
    { korean: '승진', english: 'Promotion', pronunciation: 'seung-jin', example: '드디어 승진했어!', exampleTranslation: 'I finally got promoted!' },
    { korean: '월급', english: 'Salary', pronunciation: 'wol-geup', example: '월급이 적어요.', exampleTranslation: 'The salary is low.' },
    { korean: '야근', english: 'Overtime work', pronunciation: 'ya-geun', example: '오늘도 야근이야.', exampleTranslation: 'I have overtime again today.' },
    { korean: '사표', english: 'Resignation letter', pronunciation: 'sa-pyo', example: '사표 내고 싶어.', exampleTranslation: 'I want to submit my resignation.' },
    { korean: '면접', english: 'Job interview', pronunciation: 'myeon-jeop', example: '면접 잘 봤어?', exampleTranslation: 'Did the interview go well?' },
    { korean: '전문가', english: 'Expert / specialist', pronunciation: 'jeon-mun-ga', example: '이 분야 전문가예요.', exampleTranslation: 'I\'m an expert in this field.' },
    { korean: '경쟁', english: 'Competition', pronunciation: 'gyeong-jaeng', example: '경쟁이 치열해.', exampleTranslation: 'The competition is fierce.' },
    { korean: '성공', english: 'Success', pronunciation: 'seong-gong', example: '반드시 성공할 거야.', exampleTranslation: 'I will definitely succeed.' },
    { korean: '실패', english: 'Failure', pronunciation: 'sil-pae', example: '실패해도 괜찮아.', exampleTranslation: 'It\'s okay to fail.' },
    { korean: '기회', english: 'Opportunity', pronunciation: 'gi-hoe', example: '이번이 마지막 기회야.', exampleTranslation: 'This is the last opportunity.' },
    { korean: '책임', english: 'Responsibility', pronunciation: 'chaek-im', example: '내가 책임질게.', exampleTranslation: 'I\'ll take responsibility.' },
    { korean: '결정', english: 'Decision', pronunciation: 'gyeol-jeong', example: '빨리 결정해.', exampleTranslation: 'Make a decision quickly.' },
    { korean: '의견', english: 'Opinion', pronunciation: 'ui-gyeon', example: '네 의견은 뭐야?', exampleTranslation: 'What is your opinion?' },
    { korean: '반대', english: 'Opposition / against', pronunciation: 'ban-dae', example: '부모님이 반대하셔.', exampleTranslation: 'My parents are against it.' },
    { korean: '찬성', english: 'Agreement / in favor', pronunciation: 'chan-seong', example: '나는 찬성이야.', exampleTranslation: 'I\'m in favor.' },
    { korean: '목표', english: 'Goal', pronunciation: 'mok-pyo', example: '목표를 세워야 해.', exampleTranslation: 'You need to set a goal.' },
    { korean: '능력', english: 'Ability', pronunciation: 'neung-nyeok', example: '능력이 있는 사람이야.', exampleTranslation: 'They are a capable person.' },
    { korean: '자격', english: 'Qualification', pronunciation: 'ja-gyeok', example: '그럴 자격이 있어?', exampleTranslation: 'Are you qualified for that?' },
    { korean: '태도', english: 'Attitude', pronunciation: 'tae-do', example: '태도가 문제야.', exampleTranslation: 'The attitude is the problem.' },
    { korean: '분위기', english: 'Atmosphere / mood', pronunciation: 'bun-wi-gi', example: '분위기 좋은 곳이야.', exampleTranslation: 'It\'s a place with great atmosphere.' },
    { korean: '인상', english: 'Impression', pronunciation: 'in-sang', example: '첫인상이 좋았어.', exampleTranslation: 'The first impression was good.' },
    { korean: '매력', english: 'Charm / attractiveness', pronunciation: 'mae-ryeok', example: '매력이 넘쳐.', exampleTranslation: 'You\'re overflowing with charm.' },
    { korean: '존경하다', english: 'To respect', pronunciation: 'jon-gyeong-ha-da', example: '선생님을 존경해요.', exampleTranslation: 'I respect you, teacher.' },
    { korean: '무시하다', english: 'To ignore / disrespect', pronunciation: 'mu-si-ha-da', example: '나를 무시하지 마.', exampleTranslation: 'Don\'t ignore me.' },
    { korean: '배신하다', english: 'To betray', pronunciation: 'bae-sin-ha-da', example: '네가 나를 배신했어!', exampleTranslation: 'You betrayed me!' },
    { korean: '의심하다', english: 'To suspect / doubt', pronunciation: 'ui-sim-ha-da', example: '나를 의심하는 거야?', exampleTranslation: 'Are you doubting me?' },
    { korean: '고민', english: 'Worry / concern', pronunciation: 'go-min', example: '고민이 많아.', exampleTranslation: 'I have many worries.' },
    { korean: '선택', english: 'Choice', pronunciation: 'seon-taek', example: '어려운 선택이야.', exampleTranslation: 'It\'s a difficult choice.' },
    { korean: '조건', english: 'Condition', pronunciation: 'jo-geon', example: '조건이 뭐야?', exampleTranslation: 'What are the conditions?' },
    { korean: '상황', english: 'Situation', pronunciation: 'sang-hwang', example: '상황이 안 좋아.', exampleTranslation: 'The situation is not good.' },
    { korean: '문제', english: 'Problem', pronunciation: 'mun-je', example: '문제가 생겼어.', exampleTranslation: 'A problem came up.' },
    { korean: '해결', english: 'Solution / resolution', pronunciation: 'hae-gyeol', example: '해결 방법을 찾아야 해.', exampleTranslation: 'We need to find a solution.' },
    { korean: '증거', english: 'Evidence', pronunciation: 'jeung-geo', example: '증거가 있어?', exampleTranslation: 'Do you have evidence?' },
    { korean: '진실', english: 'Truth', pronunciation: 'jin-sil', example: '진실을 말해 줘.', exampleTranslation: 'Tell me the truth.' },
    { korean: '거짓', english: 'Falsehood', pronunciation: 'geo-jit', example: '다 거짓이었어.', exampleTranslation: 'It was all a lie.' },
    { korean: '기밀', english: 'Classified / confidential', pronunciation: 'gi-mil', example: '이건 회사 기밀이야.', exampleTranslation: 'This is company confidential information.' },
    { korean: '소문', english: 'Rumor', pronunciation: 'so-mun', example: '이상한 소문이 돌아.', exampleTranslation: 'Strange rumors are going around.' },
    { korean: '오해하다', english: 'To misunderstand', pronunciation: 'o-hae-ha-da', example: '완전히 오해했어.', exampleTranslation: 'I completely misunderstood.' },
    { korean: '설명하다', english: 'To explain', pronunciation: 'seol-myeong-ha-da', example: '제대로 설명해 봐.', exampleTranslation: 'Try to explain properly.' },
    { korean: '주장하다', english: 'To insist / claim', pronunciation: 'ju-jang-ha-da', example: '끝까지 주장할 거야?', exampleTranslation: 'Are you going to insist until the end?' },
    { korean: '인정하다', english: 'To acknowledge / admit', pronunciation: 'in-jeong-ha-da', example: '실수를 인정해.', exampleTranslation: 'Acknowledge your mistake.' },
    { korean: '거절하다', english: 'To refuse / reject', pronunciation: 'geo-jeol-ha-da', example: '그 제안을 거절했어.', exampleTranslation: 'I refused that offer.' },
    { korean: '부탁', english: 'Request / favor', pronunciation: 'bu-tak', example: '부탁이 있는데...', exampleTranslation: 'I have a favor to ask...' },
    { korean: '허락', english: 'Permission', pronunciation: 'heo-rak', example: '허락해 주세요.', exampleTranslation: 'Please give me permission.' },
    { korean: '약속하다', english: 'To promise', pronunciation: 'yak-sok-ha-da', example: '다시는 안 그러겠다고 약속해.', exampleTranslation: 'Promise you won\'t do it again.' },
    { korean: '복수', english: 'Revenge', pronunciation: 'bok-su', example: '복수할 거야.', exampleTranslation: 'I will get revenge.' },
    { korean: '정의', english: 'Justice', pronunciation: 'jeong-ui', example: '정의는 반드시 승리한다.', exampleTranslation: 'Justice will always prevail.' },
    { korean: '권력', english: 'Power / authority', pronunciation: 'gwon-ryeok', example: '권력을 남용하지 마.', exampleTranslation: 'Don\'t abuse your power.' },
    { korean: '음모', english: 'Conspiracy / plot', pronunciation: 'eum-mo', example: '이건 음모야.', exampleTranslation: 'This is a conspiracy.' },
    { korean: '협박', english: 'Threat / blackmail', pronunciation: 'hyeop-bak', example: '나를 협박하는 거야?', exampleTranslation: 'Are you threatening me?' },
    { korean: '계약', english: 'Contract', pronunciation: 'gye-yak', example: '계약서에 사인해.', exampleTranslation: 'Sign the contract.' },
    { korean: '조사', english: 'Investigation', pronunciation: 'jo-sa', example: '경찰이 조사 중이야.', exampleTranslation: 'The police are investigating.' },
    { korean: '범인', english: 'Criminal / culprit', pronunciation: 'beom-in', example: '범인을 잡아야 해.', exampleTranslation: 'We need to catch the culprit.' },
    { korean: '알리바이', english: 'Alibi', pronunciation: 'al-li-ba-i', example: '알리바이가 있어?', exampleTranslation: 'Do you have an alibi?' },
    { korean: '사건', english: 'Incident / case', pronunciation: 'sa-geon', example: '이 사건은 복잡해.', exampleTranslation: 'This case is complicated.' },
    { korean: '단서', english: 'Clue', pronunciation: 'dan-seo', example: '중요한 단서를 찾았어.', exampleTranslation: 'I found an important clue.' },
    { korean: '용의자', english: 'Suspect', pronunciation: 'yong-ui-ja', example: '용의자가 있어요?', exampleTranslation: 'Is there a suspect?' },
    { korean: '변호사', english: 'Lawyer', pronunciation: 'byeon-ho-sa', example: '변호사를 불러 주세요.', exampleTranslation: 'Please call a lawyer.' },
    { korean: '검사', english: 'Prosecutor', pronunciation: 'geom-sa', example: '검사가 기소했어요.', exampleTranslation: 'The prosecutor filed charges.' },
    { korean: '판사', english: 'Judge', pronunciation: 'pan-sa', example: '판사님, 이의 있습니다.', exampleTranslation: 'Your Honor, I object.' },
    { korean: '재판', english: 'Trial', pronunciation: 'jae-pan', example: '재판이 다음 주야.', exampleTranslation: 'The trial is next week.' },
    { korean: '무죄', english: 'Not guilty', pronunciation: 'mu-joe', example: '무죄를 주장해요.', exampleTranslation: 'I plead not guilty.' },
    { korean: '유죄', english: 'Guilty', pronunciation: 'yu-joe', example: '유죄 판결을 받았어.', exampleTranslation: 'He received a guilty verdict.' },
    { korean: '사실', english: 'Fact', pronunciation: 'sa-sil', example: '사실을 밝혀야 해.', exampleTranslation: 'We need to uncover the facts.' },
    { korean: '양심', english: 'Conscience', pronunciation: 'yang-sim', example: '양심이 없어?', exampleTranslation: 'Don\'t you have a conscience?' },
    { korean: '도덕', english: 'Morality', pronunciation: 'do-deok', example: '도덕적으로 옳지 않아.', exampleTranslation: 'It\'s not morally right.' },
    { korean: '신뢰', english: 'Trust', pronunciation: 'sin-roe', example: '신뢰가 깨졌어.', exampleTranslation: 'Trust is broken.' },
    { korean: '배려', english: 'Consideration', pronunciation: 'bae-ryeo', example: '배려가 부족해.', exampleTranslation: 'There\'s a lack of consideration.' },
    { korean: '체면', english: 'Face / dignity', pronunciation: 'che-myeon', example: '체면이 중요해?', exampleTranslation: 'Is face that important?' },
    { korean: '눈치', english: 'Social awareness / tact', pronunciation: 'nun-chi', example: '눈치 좀 봐!', exampleTranslation: 'Read the room!' },
    { korean: '예의', english: 'Manners / etiquette', pronunciation: 'ye-ui', example: '예의를 지켜!', exampleTranslation: 'Mind your manners!' },
    { korean: '존댓말', english: 'Formal speech', pronunciation: 'jon-daen-mal', example: '존댓말 쓰세요.', exampleTranslation: 'Please use formal speech.' },
    { korean: '반말', english: 'Informal speech', pronunciation: 'ban-mal', example: '반말 하지 마.', exampleTranslation: 'Don\'t speak informally to me.' },
    { korean: '맞선', english: 'Arranged date / matchmaking', pronunciation: 'mat-seon', example: '맞선 보러 가요.', exampleTranslation: 'I\'m going on an arranged date.' },
    { korean: '시어머니', english: 'Mother-in-law (husband\'s)', pronunciation: 'si-eo-meo-ni', example: '시어머니가 오신대요.', exampleTranslation: 'Mother-in-law is coming.' },
    { korean: '며느리', english: 'Daughter-in-law', pronunciation: 'myeo-neu-ri', example: '며느리가 참 착해요.', exampleTranslation: 'The daughter-in-law is very kind.' },
    { korean: '장인어른', english: 'Father-in-law (wife\'s father)', pronunciation: 'jang-in-eo-reun', example: '장인어른을 뵈러 갔어요.', exampleTranslation: 'I went to see my father-in-law.' },
    { korean: '재벌', english: 'Conglomerate / chaebol', pronunciation: 'jae-beol', example: '재벌 아들이래!', exampleTranslation: 'He\'s a chaebol\'s son!' },
    { korean: '상속', english: 'Inheritance', pronunciation: 'sang-sok', example: '상속 문제로 싸워요.', exampleTranslation: 'They\'re fighting over the inheritance.' },
    { korean: '유산', english: 'Legacy / inheritance', pronunciation: 'yu-san', example: '유산을 남기셨어요.', exampleTranslation: 'He left an inheritance.' },
    { korean: '주식', english: 'Stock / shares', pronunciation: 'ju-sik', example: '주식이 폭락했어!', exampleTranslation: 'The stocks crashed!' },
    { korean: '투자', english: 'Investment', pronunciation: 'tu-ja', example: '현명하게 투자해야 해.', exampleTranslation: 'You need to invest wisely.' },
    { korean: '파산', english: 'Bankruptcy', pronunciation: 'pa-san', example: '회사가 파산했어.', exampleTranslation: 'The company went bankrupt.' },
    { korean: '감시하다', english: 'To surveil / monitor', pronunciation: 'gam-si-ha-da', example: '누군가 나를 감시해.', exampleTranslation: 'Someone is watching me.' },
    { korean: '추적하다', english: 'To chase / track', pronunciation: 'chu-jeok-ha-da', example: '범인을 추적 중이야.', exampleTranslation: 'We\'re tracking the criminal.' },
    { korean: '탈출하다', english: 'To escape', pronunciation: 'tal-chul-ha-da', example: '여기서 탈출해야 해.', exampleTranslation: 'We need to escape from here.' },
    { korean: '납치', english: 'Kidnapping', pronunciation: 'nap-chi', example: '아이가 납치당했어!', exampleTranslation: 'The child was kidnapped!' },
    { korean: '위기', english: 'Crisis', pronunciation: 'wi-gi', example: '지금 위기 상황이야.', exampleTranslation: 'This is a crisis situation.' },
    { korean: '긴급', english: 'Urgent / emergency', pronunciation: 'gin-geup', example: '긴급 상황이에요!', exampleTranslation: 'It\'s an emergency!' },
    { korean: '수상하다', english: 'Suspicious', pronunciation: 'su-sang-ha-da', example: '그 사람 좀 수상해.', exampleTranslation: 'That person is suspicious.' },
    { korean: '기막히다', english: 'To be dumbfounded', pronunciation: 'gi-mak-hi-da', example: '기가 막혀서 말이 안 나와.', exampleTranslation: 'I\'m so dumbfounded I can\'t speak.' },
    { korean: '어이없다', english: 'Absurd / ridiculous', pronunciation: 'eo-i-eop-da', example: '정말 어이가 없네.', exampleTranslation: 'This is truly absurd.' },
    { korean: '억울하다', english: 'To feel wronged / unjust', pronunciation: 'eok-ul-ha-da', example: '너무 억울해!', exampleTranslation: 'It\'s so unfair!' },
    { korean: '뻔뻔하다', english: 'Shameless', pronunciation: 'ppeon-ppeon-ha-da', example: '어쩜 그렇게 뻔뻔해?', exampleTranslation: 'How can you be so shameless?' },
    { korean: '한심하다', english: 'Pathetic', pronunciation: 'han-sim-ha-da', example: '정말 한심하다.', exampleTranslation: 'How pathetic.' },
  ],
  4: [
    { korean: '갈등', english: 'Conflict', pronunciation: 'gal-deung', example: '가족 간의 갈등이 깊어.', exampleTranslation: 'The conflict within the family is deep.' },
    { korean: '화해하다', english: 'To reconcile', pronunciation: 'hwa-hae-ha-da', example: '이제 화해하자.', exampleTranslation: 'Let\'s reconcile now.' },
    { korean: '고독', english: 'Solitude / loneliness', pronunciation: 'go-dok', example: '고독한 밤이야.', exampleTranslation: 'It\'s a lonely night.' },
    { korean: '절망', english: 'Despair', pronunciation: 'jeol-mang', example: '절망 속에서 희망을 찾았어.', exampleTranslation: 'I found hope in despair.' },
    { korean: '희망', english: 'Hope', pronunciation: 'hui-mang', example: '아직 희망이 있어.', exampleTranslation: 'There is still hope.' },
    { korean: '그리움', english: 'Longing / yearning', pronunciation: 'geu-ri-um', example: '그리움이 사무쳐.', exampleTranslation: 'The longing is overwhelming.' },
    { korean: '한', english: 'Deep resentment / unresolved grief', pronunciation: 'han', example: '가슴에 한이 맺혔어.', exampleTranslation: 'Deep resentment is lodged in my heart.' },
    { korean: '원망', english: 'Resentment / blame', pronunciation: 'won-mang', example: '원망하지 않을게.', exampleTranslation: 'I won\'t resent you.' },
    { korean: '동정', english: 'Sympathy / compassion', pronunciation: 'dong-jeong', example: '동정은 필요 없어.', exampleTranslation: 'I don\'t need your sympathy.' },
    { korean: '존재', english: 'Existence', pronunciation: 'jon-jae', example: '네 존재 자체가 힘이 돼.', exampleTranslation: 'Your very existence gives me strength.' },
    { korean: '운명', english: 'Fate / destiny', pronunciation: 'un-myeong', example: '운명에 맞서 싸워야 해.', exampleTranslation: 'We must fight against fate.' },
    { korean: '기적', english: 'Miracle', pronunciation: 'gi-jeok', example: '기적이 일어났어.', exampleTranslation: 'A miracle happened.' },
    { korean: '고통', english: 'Pain / suffering', pronunciation: 'go-tong', example: '이 고통이 언제 끝날까.', exampleTranslation: 'When will this suffering end.' },
    { korean: '치유', english: 'Healing', pronunciation: 'chi-yu', example: '시간이 치유해 줄 거야.', exampleTranslation: 'Time will heal everything.' },
    { korean: '성장', english: 'Growth', pronunciation: 'seong-jang', example: '아픔 속에서 성장해.', exampleTranslation: 'You grow through pain.' },
    { korean: '변화', english: 'Change', pronunciation: 'byeon-hwa', example: '변화가 필요한 때야.', exampleTranslation: 'It\'s time for change.' },
    { korean: '결심', english: 'Resolution / determination', pronunciation: 'gyeol-sim', example: '결심했어, 떠날 거야.', exampleTranslation: 'I\'ve made my decision, I\'m leaving.' },
    { korean: '각오', english: 'Resolve / preparedness', pronunciation: 'gak-o', example: '각오하고 왔어.', exampleTranslation: 'I came prepared.' },
    { korean: '진정하다', english: 'To calm down', pronunciation: 'jin-jeong-ha-da', example: '진정해, 흥분하지 마.', exampleTranslation: 'Calm down, don\'t get excited.' },
    { korean: '폭로하다', english: 'To expose / reveal', pronunciation: 'pok-ro-ha-da', example: '모든 걸 폭로하겠어.', exampleTranslation: 'I\'ll expose everything.' },
    { korean: '고발하다', english: 'To report / accuse', pronunciation: 'go-bal-ha-da', example: '당신을 고발하겠어요.', exampleTranslation: 'I will report you.' },
    { korean: '위증하다', english: 'To commit perjury', pronunciation: 'wi-jeung-ha-da', example: '위증하면 안 돼요.', exampleTranslation: 'You must not commit perjury.' },
    { korean: '모함하다', english: 'To frame / falsely accuse', pronunciation: 'mo-ham-ha-da', example: '나를 모함하지 마!', exampleTranslation: 'Don\'t frame me!' },
    { korean: '협상', english: 'Negotiation', pronunciation: 'hyeop-sang', example: '협상의 여지가 있어.', exampleTranslation: 'There is room for negotiation.' },
    { korean: '타협', english: 'Compromise', pronunciation: 'ta-hyeop', example: '타협할 수 없어.', exampleTranslation: 'I can\'t compromise.' },
    { korean: '양보하다', english: 'To yield / concede', pronunciation: 'yang-bo-ha-da', example: '이번만 양보할게.', exampleTranslation: 'I\'ll concede just this once.' },
    { korean: '당당하다', english: 'To be confident / dignified', pronunciation: 'dang-dang-ha-da', example: '당당하게 살아.', exampleTranslation: 'Live with dignity.' },
    { korean: '비겁하다', english: 'To be cowardly', pronunciation: 'bi-geop-ha-da', example: '그런 짓은 비겁해.', exampleTranslation: 'That kind of act is cowardly.' },
    { korean: '고귀하다', english: 'Noble / precious', pronunciation: 'go-gwi-ha-da', example: '모든 생명은 고귀해요.', exampleTranslation: 'All life is precious.' },
    { korean: '비참하다', english: 'Miserable / wretched', pronunciation: 'bi-cham-ha-da', example: '비참한 최후를 맞았어.', exampleTranslation: 'He met a miserable end.' },
    { korean: '처절하다', english: 'Desperate / gut-wrenching', pronunciation: 'cheo-jeol-ha-da', example: '처절한 싸움이었어.', exampleTranslation: 'It was a desperate fight.' },
    { korean: '참담하다', english: 'Devastating / tragic', pronunciation: 'cham-dam-ha-da', example: '참담한 결과야.', exampleTranslation: 'It\'s a devastating result.' },
    { korean: '황당하다', english: 'Absurd / preposterous', pronunciation: 'hwang-dang-ha-da', example: '너무 황당해서 웃겼어.', exampleTranslation: 'It was so absurd that it was funny.' },
    { korean: '통쾌하다', english: 'Satisfying / exhilarating', pronunciation: 'tong-kwae-ha-da', example: '통쾌한 승리야!', exampleTranslation: 'It\'s a satisfying victory!' },
    { korean: '유언', english: 'Last words / will', pronunciation: 'yu-eon', example: '아버지의 유언이야.', exampleTranslation: 'These are Father\'s last words.' },
    { korean: '유서', english: 'Suicide note / will', pronunciation: 'yu-seo', example: '유서를 남겼어요.', exampleTranslation: 'He left a note behind.' },
    { korean: '장례식', english: 'Funeral', pronunciation: 'jang-nye-sik', example: '장례식에 참석했어요.', exampleTranslation: 'I attended the funeral.' },
    { korean: '임종', english: 'Deathbed', pronunciation: 'im-jong', example: '임종을 지켰어요.', exampleTranslation: 'I kept vigil at the deathbed.' },
    { korean: '유족', english: 'Bereaved family', pronunciation: 'yu-jok', example: '유족에게 위로를 전해요.', exampleTranslation: 'We offer condolences to the bereaved family.' },
    { korean: '상속인', english: 'Heir', pronunciation: 'sang-sok-in', example: '정당한 상속인이에요.', exampleTranslation: 'I am the rightful heir.' },
    { korean: '횡령', english: 'Embezzlement', pronunciation: 'hoeng-nyeong', example: '회삿돈을 횡령했어.', exampleTranslation: 'He embezzled company money.' },
    { korean: '뇌물', english: 'Bribe', pronunciation: 'noe-mul', example: '뇌물을 받았어요.', exampleTranslation: 'He received a bribe.' },
    { korean: '비리', english: 'Corruption', pronunciation: 'bi-ri', example: '비리가 밝혀졌어.', exampleTranslation: 'The corruption was uncovered.' },
    { korean: '고소하다', english: 'To file a lawsuit', pronunciation: 'go-so-ha-da', example: '고소하겠어, 법정에서 만나.', exampleTranslation: 'I\'ll sue you, see you in court.' },
    { korean: '무고', english: 'False accusation', pronunciation: 'mu-go', example: '이건 무고야!', exampleTranslation: 'This is a false accusation!' },
    { korean: '정당방위', english: 'Self-defense', pronunciation: 'jeong-dang-bang-wi', example: '정당방위였어요.', exampleTranslation: 'It was self-defense.' },
    { korean: '증인', english: 'Witness', pronunciation: 'jeung-in', example: '증인이 필요해요.', exampleTranslation: 'We need a witness.' },
    { korean: '진술', english: 'Testimony / statement', pronunciation: 'jin-sul', example: '진술을 번복했어요.', exampleTranslation: 'He retracted his statement.' },
    { korean: '억지', english: 'Forced / unreasonable', pronunciation: 'eok-ji', example: '억지 부리지 마.', exampleTranslation: 'Don\'t be unreasonable.' },
    { korean: '가식', english: 'Pretense / affectation', pronunciation: 'ga-sik', example: '가식적인 사람이야.', exampleTranslation: 'He\'s a pretentious person.' },
    { korean: '위선', english: 'Hypocrisy', pronunciation: 'wi-seon', example: '위선자 같으니!', exampleTranslation: 'You hypocrite!' },
    { korean: '집착', english: 'Obsession', pronunciation: 'jip-chak', example: '집착하지 마.', exampleTranslation: 'Don\'t be obsessive.' },
    { korean: '맹세', english: 'Oath / vow', pronunciation: 'maeng-se', example: '영원히 사랑하겠다고 맹세해.', exampleTranslation: 'I vow to love you forever.' },
    { korean: '숙명', english: 'Predestined fate', pronunciation: 'sung-myeong', example: '이것이 우리의 숙명이야.', exampleTranslation: 'This is our predestined fate.' },
    { korean: '속죄', english: 'Atonement', pronunciation: 'sok-joe', example: '평생 속죄하며 살겠어.', exampleTranslation: 'I will live my life atoning.' },
    { korean: '대가', english: 'Price / cost', pronunciation: 'dae-ga', example: '큰 대가를 치르게 될 거야.', exampleTranslation: 'You will pay a heavy price.' },
    { korean: '야망', english: 'Ambition', pronunciation: 'ya-mang', example: '야망이 대단하시네요.', exampleTranslation: 'Your ambition is impressive.' },
    { korean: '욕심', english: 'Greed / desire', pronunciation: 'yok-sim', example: '욕심을 버려.', exampleTranslation: 'Let go of your greed.' },
    { korean: '굴복하다', english: 'To submit / surrender', pronunciation: 'gul-bok-ha-da', example: '절대 굴복하지 않겠어.', exampleTranslation: 'I will never surrender.' },
    { korean: '저항하다', english: 'To resist', pronunciation: 'jeo-hang-ha-da', example: '끝까지 저항할 거야.', exampleTranslation: 'I will resist to the end.' },
    { korean: '항변하다', english: 'To protest / plead', pronunciation: 'hang-byeon-ha-da', example: '억울하다고 항변했어.', exampleTranslation: 'He protested that he was wronged.' },
    { korean: '자수하다', english: 'To turn oneself in', pronunciation: 'ja-su-ha-da', example: '자수하는 게 나아.', exampleTranslation: 'It\'s better to turn yourself in.' },
    { korean: '탄원', english: 'Petition / plea', pronunciation: 'tan-won', example: '탄원서를 제출했어요.', exampleTranslation: 'I submitted a petition.' },
    { korean: '공소', english: 'Prosecution / indictment', pronunciation: 'gong-so', example: '공소시효가 지났어요.', exampleTranslation: 'The statute of limitations has passed.' },
    { korean: '석방', english: 'Release (from prison)', pronunciation: 'seok-bang', example: '내일 석방돼요.', exampleTranslation: 'He will be released tomorrow.' },
    { korean: '가석방', english: 'Parole', pronunciation: 'ga-seok-bang', example: '가석방으로 나왔어요.', exampleTranslation: 'He came out on parole.' },
    { korean: '수감', english: 'Imprisonment', pronunciation: 'su-gam', example: '3년간 수감됐어요.', exampleTranslation: 'He was imprisoned for 3 years.' },
    { korean: '냉정하다', english: 'Cold / composed', pronunciation: 'naeng-jeong-ha-da', example: '너무 냉정하지 마.', exampleTranslation: 'Don\'t be so cold.' },
    { korean: '열정', english: 'Passion', pronunciation: 'yeol-jeong', example: '열정이 넘치는 사람이야.', exampleTranslation: 'He\'s a person full of passion.' },
    { korean: '충격', english: 'Shock', pronunciation: 'chung-gyeok', example: '충격적인 사실이야.', exampleTranslation: 'It\'s a shocking fact.' },
    { korean: '배경', english: 'Background', pronunciation: 'bae-gyeong', example: '집안 배경이 좋아.', exampleTranslation: 'He has a good family background.' },
    { korean: '명예', english: 'Honor / reputation', pronunciation: 'myeong-ye', example: '명예를 걸겠어.', exampleTranslation: 'I will stake my honor on it.' },
    { korean: '위엄', english: 'Dignity / majesty', pronunciation: 'wi-eom', example: '위엄 있는 모습이야.', exampleTranslation: 'It\'s a dignified appearance.' },
    { korean: '품위', english: 'Grace / dignity', pronunciation: 'pum-wi', example: '품위를 지켜.', exampleTranslation: 'Maintain your dignity.' },
    { korean: '의리', english: 'Loyalty / brotherhood', pronunciation: 'ui-ri', example: '의리 있는 사람이야.', exampleTranslation: 'He\'s a loyal person.' },
    { korean: '배은망덕', english: 'Ingratitude', pronunciation: 'bae-eun-mang-deok', example: '배은망덕한 놈!', exampleTranslation: 'You ungrateful wretch!' },
    { korean: '간절하다', english: 'Earnest / desperate', pronunciation: 'gan-jeol-ha-da', example: '간절히 바라고 있어.', exampleTranslation: 'I am desperately wishing for it.' },
    { korean: '서글프다', english: 'Sorrowful / melancholy', pronunciation: 'seo-geul-peu-da', example: '서글픈 눈빛이야.', exampleTranslation: 'Those are sorrowful eyes.' },
    { korean: '처량하다', english: 'Pitiful / wretched', pronunciation: 'cheo-ryang-ha-da', example: '처량한 신세가 됐어.', exampleTranslation: 'I\'ve become pitiful.' },
    { korean: '씁쓸하다', english: 'Bitter / bittersweet', pronunciation: 'sseup-sseul-ha-da', example: '씁쓸한 웃음을 지었어.', exampleTranslation: 'He gave a bitter smile.' },
    { korean: '허무하다', english: 'Futile / vain', pronunciation: 'heo-mu-ha-da', example: '다 허무하게 끝났어.', exampleTranslation: 'It all ended in vain.' },
    { korean: '찬란하다', english: 'Brilliant / radiant', pronunciation: 'chan-ran-ha-da', example: '찬란한 미래가 기다려.', exampleTranslation: 'A brilliant future awaits.' },
    { korean: '처참하다', english: 'Tragic / ghastly', pronunciation: 'cheo-cham-ha-da', example: '처참한 광경이었어.', exampleTranslation: 'It was a ghastly scene.' },
    { korean: '잔인하다', english: 'Cruel', pronunciation: 'jan-in-ha-da', example: '너무 잔인한 짓이야.', exampleTranslation: 'That\'s too cruel.' },
    { korean: '무정하다', english: 'Heartless', pronunciation: 'mu-jeong-ha-da', example: '어쩜 그렇게 무정해.', exampleTranslation: 'How can you be so heartless.' },
    { korean: '순수하다', english: 'Pure / innocent', pronunciation: 'sun-su-ha-da', example: '순수한 마음이 좋아.', exampleTranslation: 'I like your pure heart.' },
    { korean: '뜻밖', english: 'Unexpected', pronunciation: 'tteut-bak', example: '뜻밖의 만남이었어.', exampleTranslation: 'It was an unexpected encounter.' },
    { korean: '운명적', english: 'Fateful', pronunciation: 'un-myeong-jeok', example: '운명적인 만남이야.', exampleTranslation: 'It\'s a fateful encounter.' },
    { korean: '불가피하다', english: 'Inevitable / unavoidable', pronunciation: 'bul-ga-pi-ha-da', example: '불가피한 선택이었어.', exampleTranslation: 'It was an unavoidable choice.' },
    { korean: '복잡하다', english: 'Complicated', pronunciation: 'bok-jap-ha-da', example: '사정이 복잡해.', exampleTranslation: 'The circumstances are complicated.' },
    { korean: '막막하다', english: 'Hopeless / overwhelming', pronunciation: 'mak-mak-ha-da', example: '앞이 막막해.', exampleTranslation: 'The future looks bleak.' },
    { korean: '답답하다', english: 'Frustrated / stuffy', pronunciation: 'dap-dap-ha-da', example: '속이 답답해.', exampleTranslation: 'I feel frustrated inside.' },
    { korean: '아쉽다', english: 'Regretful / pity', pronunciation: 'a-swip-da', example: '아쉽지만 어쩔 수 없어.', exampleTranslation: 'It\'s regrettable but can\'t be helped.' },
    { korean: '서운하다', english: 'Hurt / disappointed', pronunciation: 'seo-un-ha-da', example: '서운하게 하지 마.', exampleTranslation: 'Don\'t hurt my feelings.' },
    { korean: '뿌듯하다', english: 'Proud / gratified', pronunciation: 'ppeu-deut-ha-da', example: '뿌듯한 마음이야.', exampleTranslation: 'I feel proud.' },
    { korean: '감격하다', english: 'To be deeply moved', pronunciation: 'gam-gyeok-ha-da', example: '감격해서 눈물이 났어.', exampleTranslation: 'I was so moved that I cried.' },
    { korean: '전율', english: 'Thrill / shiver', pronunciation: 'jeon-yul', example: '전율이 느껴져.', exampleTranslation: 'I feel a thrill.' },
    { korean: '오싹하다', english: 'Creepy / chilling', pronunciation: 'o-ssak-ha-da', example: '등골이 오싹해.', exampleTranslation: 'A chill runs down my spine.' },
    { korean: '떨리다', english: 'To tremble / shake', pronunciation: 'tteol-li-da', example: '긴장돼서 떨려.', exampleTranslation: 'I\'m trembling with nervousness.' },
    { korean: '절박하다', english: 'Desperate / urgent', pronunciation: 'jeol-bak-ha-da', example: '절박한 심정이야.', exampleTranslation: 'I feel desperate.' },
  ],
  5: [
    { korean: '비유하다', english: 'To use metaphor / compare', pronunciation: 'bi-yu-ha-da', example: '인생을 여행에 비유하다.', exampleTranslation: 'To compare life to a journey.' },
    { korean: '은유', english: 'Metaphor', pronunciation: 'eun-yu', example: '그건 은유적 표현이야.', exampleTranslation: 'That\'s a metaphorical expression.' },
    { korean: '풍자', english: 'Satire', pronunciation: 'pung-ja', example: '사회를 풍자하는 드라마야.', exampleTranslation: 'It\'s a drama that satirizes society.' },
    { korean: '역설', english: 'Paradox / irony', pronunciation: 'yeok-seol', example: '인생의 역설이야.', exampleTranslation: 'It\'s one of life\'s paradoxes.' },
    { korean: '모순', english: 'Contradiction', pronunciation: 'mo-sun', example: '모순된 말을 하고 있어.', exampleTranslation: 'You\'re saying contradictory things.' },
    { korean: '허상', english: 'Illusion / phantom', pronunciation: 'heo-sang', example: '행복은 허상이었어.', exampleTranslation: 'Happiness was an illusion.' },
    { korean: '환상', english: 'Fantasy / illusion', pronunciation: 'hwan-sang', example: '환상에서 깨어나.', exampleTranslation: 'Wake up from the fantasy.' },
    { korean: '덧없다', english: 'Transient / fleeting', pronunciation: 'deot-eop-da', example: '인생은 덧없는 것이야.', exampleTranslation: 'Life is a fleeting thing.' },
    { korean: '무상하다', english: 'Impermanent / transient', pronunciation: 'mu-sang-ha-da', example: '세상만사 무상하다.', exampleTranslation: 'All things in this world are impermanent.' },
    { korean: '허탈하다', english: 'Hollow / empty (feeling)', pronunciation: 'heo-tal-ha-da', example: '허탈한 마음을 감출 수 없어.', exampleTranslation: 'I can\'t hide this hollow feeling.' },
    { korean: '비통하다', english: 'Grief-stricken', pronunciation: 'bi-tong-ha-da', example: '비통한 심정이에요.', exampleTranslation: 'I am grief-stricken.' },
    { korean: '처연하다', english: 'Forlorn / desolate', pronunciation: 'cheo-yeon-ha-da', example: '처연한 표정을 짓고 있었어.', exampleTranslation: 'He wore a forlorn expression.' },
    { korean: '애절하다', english: 'Mournful / plaintive', pronunciation: 'ae-jeol-ha-da', example: '애절한 목소리로 노래했어.', exampleTranslation: 'She sang in a mournful voice.' },
    { korean: '절절하다', english: 'Deeply moving / earnest', pronunciation: 'jeol-jeol-ha-da', example: '절절한 사랑 이야기야.', exampleTranslation: 'It\'s a deeply moving love story.' },
    { korean: '격분하다', english: 'To be enraged', pronunciation: 'gyeok-bun-ha-da', example: '격분한 나머지 소리를 질렀어.', exampleTranslation: 'In a fit of rage, he screamed.' },
    { korean: '경악하다', english: 'To be horrified', pronunciation: 'gyeong-ak-ha-da', example: '경악할 만한 사실이야.', exampleTranslation: 'It\'s a horrifying truth.' },
    { korean: '애도', english: 'Mourning / condolence', pronunciation: 'ae-do', example: '깊은 애도를 표합니다.', exampleTranslation: 'We express our deepest condolences.' },
    { korean: '비애', english: 'Sorrow / pathos', pronunciation: 'bi-ae', example: '비애에 잠긴 표정이야.', exampleTranslation: 'His expression is immersed in sorrow.' },
    { korean: '격동', english: 'Upheaval / turmoil', pronunciation: 'gyeok-dong', example: '격동의 시대를 살았어.', exampleTranslation: 'We lived in turbulent times.' },
    { korean: '파란만장', english: 'Eventful / tumultuous', pronunciation: 'pa-ran-man-jang', example: '파란만장한 인생이었어.', exampleTranslation: 'It was a tumultuous life.' },
    { korean: '천신만고', english: 'Great hardships', pronunciation: 'cheon-sin-man-go', example: '천신만고 끝에 성공했어.', exampleTranslation: 'After great hardships, I succeeded.' },
    { korean: '사면초가', english: 'Surrounded by enemies', pronunciation: 'sa-myeon-cho-ga', example: '사면초가에 몰렸어.', exampleTranslation: 'I\'m surrounded from all sides.' },
    { korean: '자업자득', english: 'Reaping what you sow', pronunciation: 'ja-eop-ja-deuk', example: '자업자득이야.', exampleTranslation: 'You brought this upon yourself.' },
    { korean: '인과응보', english: 'Karma / cause and effect', pronunciation: 'in-gwa-eung-bo', example: '인과응보라 했잖아.', exampleTranslation: 'They say it\'s karma.' },
    { korean: '대의', english: 'Greater cause / righteousness', pronunciation: 'dae-ui', example: '대의를 위해 희생해야 해.', exampleTranslation: 'You must sacrifice for the greater cause.' },
    { korean: '소신', english: 'Conviction / belief', pronunciation: 'so-sin', example: '소신껏 행동해.', exampleTranslation: 'Act according to your convictions.' },
    { korean: '신념', english: 'Belief / faith', pronunciation: 'sin-nyeom', example: '신념을 꺾지 마.', exampleTranslation: 'Don\'t break your faith.' },
    { korean: '고결하다', english: 'Noble / virtuous', pronunciation: 'go-gyeol-ha-da', example: '고결한 정신을 가진 사람이야.', exampleTranslation: 'He is a person of noble spirit.' },
    { korean: '숭고하다', english: 'Sublime / lofty', pronunciation: 'sung-go-ha-da', example: '숭고한 희생이었어.', exampleTranslation: 'It was a sublime sacrifice.' },
    { korean: '경이롭다', english: 'Marvelous / wondrous', pronunciation: 'gyeong-i-rop-da', example: '경이로운 세계야.', exampleTranslation: 'It\'s a wondrous world.' },
    { korean: '통렬하다', english: 'Scathing / sharp', pronunciation: 'tong-ryeol-ha-da', example: '통렬한 비판이었어.', exampleTranslation: 'It was a scathing critique.' },
    { korean: '신랄하다', english: 'Acerbic / biting', pronunciation: 'sin-ral-ha-da', example: '신랄한 비평을 했어.', exampleTranslation: 'He made a biting criticism.' },
    { korean: '논쟁', english: 'Debate / controversy', pronunciation: 'non-jaeng', example: '논쟁의 여지가 있어.', exampleTranslation: 'There is room for debate.' },
    { korean: '반박하다', english: 'To refute', pronunciation: 'ban-bak-ha-da', example: '강하게 반박했어.', exampleTranslation: 'He strongly refuted it.' },
    { korean: '항의하다', english: 'To protest', pronunciation: 'hang-ui-ha-da', example: '부당함에 항의했어.', exampleTranslation: 'I protested against the injustice.' },
    { korean: '변론하다', english: 'To argue (in court)', pronunciation: 'byeon-ron-ha-da', example: '무죄를 변론했어요.', exampleTranslation: 'He argued for innocence.' },
    { korean: '호소하다', english: 'To appeal / plead', pronunciation: 'ho-so-ha-da', example: '절박하게 호소했어.', exampleTranslation: 'He appealed desperately.' },
    { korean: '궁지', english: 'Corner / dead end', pronunciation: 'gung-ji', example: '궁지에 몰렸어.', exampleTranslation: 'I\'m driven into a corner.' },
    { korean: '딜레마', english: 'Dilemma', pronunciation: 'dil-le-ma', example: '딜레마에 빠졌어.', exampleTranslation: 'I\'m caught in a dilemma.' },
    { korean: '갈림길', english: 'Crossroads', pronunciation: 'gal-lim-gil', example: '인생의 갈림길에 서 있어.', exampleTranslation: 'I stand at life\'s crossroads.' },
    { korean: '전환점', english: 'Turning point', pronunciation: 'jeon-hwan-jeom', example: '인생의 전환점이야.', exampleTranslation: 'This is a turning point in life.' },
    { korean: '진퇴양난', english: 'Between a rock and a hard place', pronunciation: 'jin-toe-yang-nan', example: '진퇴양난이야.', exampleTranslation: 'I\'m between a rock and a hard place.' },
    { korean: '속이다', english: 'To deceive', pronunciation: 'sok-i-da', example: '나를 속인 거야?', exampleTranslation: 'Did you deceive me?' },
    { korean: '조종하다', english: 'To manipulate', pronunciation: 'jo-jong-ha-da', example: '사람을 조종하지 마.', exampleTranslation: 'Don\'t manipulate people.' },
    { korean: '이간질', english: 'Sowing discord', pronunciation: 'i-gan-jil', example: '이간질하지 마!', exampleTranslation: 'Don\'t try to sow discord!' },
    { korean: '농락하다', english: 'To toy with / play someone', pronunciation: 'nong-nak-ha-da', example: '사람 감정을 농락하지 마.', exampleTranslation: 'Don\'t toy with people\'s feelings.' },
    { korean: '기만', english: 'Deception / fraud', pronunciation: 'gi-man', example: '이건 기만이야!', exampleTranslation: 'This is deception!' },
    { korean: '은폐하다', english: 'To conceal / cover up', pronunciation: 'eun-pye-ha-da', example: '진실을 은폐했어.', exampleTranslation: 'They concealed the truth.' },
    { korean: '사주하다', english: 'To instigate', pronunciation: 'sa-ju-ha-da', example: '누가 사주한 거야?', exampleTranslation: 'Who instigated this?' },
    { korean: '매수하다', english: 'To buy off / bribe', pronunciation: 'mae-su-ha-da', example: '증인을 매수했어.', exampleTranslation: 'They bribed the witness.' },
    { korean: '실체', english: 'True nature / substance', pronunciation: 'sil-che', example: '실체가 드러났어.', exampleTranslation: 'The true nature was revealed.' },
    { korean: '진상', english: 'Truth / reality of a matter', pronunciation: 'jin-sang', example: '진상을 밝혀야 해.', exampleTranslation: 'We must uncover the truth.' },
    { korean: '내막', english: 'Inside story', pronunciation: 'nae-mak', example: '내막을 알고 있어.', exampleTranslation: 'I know the inside story.' },
    { korean: '실마리', english: 'Thread / lead', pronunciation: 'sil-ma-ri', example: '실마리를 찾았어!', exampleTranslation: 'I found a lead!' },
    { korean: '전말', english: 'Full story / details', pronunciation: 'jeon-mal', example: '사건의 전말을 듣고 싶어.', exampleTranslation: 'I want to hear the full story of the incident.' },
    { korean: '번민하다', english: 'To agonize', pronunciation: 'beon-min-ha-da', example: '밤새 번민했어.', exampleTranslation: 'I agonized all night.' },
    { korean: '방황하다', english: 'To wander / be lost', pronunciation: 'bang-hwang-ha-da', example: '한동안 방황했어.', exampleTranslation: 'I wandered for a while.' },
    { korean: '좌절', english: 'Frustration / setback', pronunciation: 'jwa-jeol', example: '좌절하지 마.', exampleTranslation: 'Don\'t be discouraged.' },
    { korean: '극복하다', english: 'To overcome', pronunciation: 'geuk-bok-ha-da', example: '어려움을 극복해야 해.', exampleTranslation: 'You must overcome the difficulties.' },
    { korean: '초월하다', english: 'To transcend', pronunciation: 'cho-wol-ha-da', example: '한계를 초월해.', exampleTranslation: 'Transcend your limits.' },
    { korean: '통찰', english: 'Insight', pronunciation: 'tong-chal', example: '깊은 통찰력이 있어.', exampleTranslation: 'He has deep insight.' },
    { korean: '성찰', english: 'Introspection / reflection', pronunciation: 'seong-chal', example: '자기 성찰이 필요해.', exampleTranslation: 'Self-reflection is needed.' },
    { korean: '각성', english: 'Awakening', pronunciation: 'gak-seong', example: '드디어 각성했어.', exampleTranslation: 'He finally awakened.' },
    { korean: '깨달음', english: 'Realization / enlightenment', pronunciation: 'kkae-dar-eum', example: '깨달음을 얻었어.', exampleTranslation: 'I gained enlightenment.' },
    { korean: '용기', english: 'Courage', pronunciation: 'yong-gi', example: '용기를 내.', exampleTranslation: 'Have courage.' },
    { korean: '인내', english: 'Patience / endurance', pronunciation: 'in-nae', example: '인내심이 대단해.', exampleTranslation: 'Your patience is remarkable.' },
    { korean: '헌신', english: 'Devotion / dedication', pronunciation: 'heon-sin', example: '헌신적인 사랑이야.', exampleTranslation: 'It\'s a devoted love.' },
    { korean: '자존심', english: 'Pride / self-respect', pronunciation: 'ja-jon-sim', example: '자존심이 허락하지 않아.', exampleTranslation: 'My pride won\'t allow it.' },
    { korean: '체념하다', english: 'To resign / give up', pronunciation: 'che-nyeom-ha-da', example: '체념하고 떠나야 해.', exampleTranslation: 'I must give up and leave.' },
    { korean: '달관', english: 'Philosophical acceptance', pronunciation: 'dal-gwan', example: '인생을 달관한 듯해.', exampleTranslation: 'He seems to have attained philosophical acceptance of life.' },
    { korean: '관조하다', english: 'To contemplate / observe', pronunciation: 'gwan-jo-ha-da', example: '삶을 관조하는 태도야.', exampleTranslation: 'It\'s an attitude of contemplating life.' },
    { korean: '사무치다', english: 'To penetrate deeply (emotion)', pronunciation: 'sa-mu-chi-da', example: '그리움이 뼛속까지 사무쳐.', exampleTranslation: 'The longing penetrates to the bone.' },
    { korean: '가슴이 찢어지다', english: 'Heart-rending', pronunciation: 'ga-seum-i jji-jeo-ji-da', example: '가슴이 찢어지는 아픔이야.', exampleTranslation: 'It\'s a heart-rending pain.' },
    { korean: '감화', english: 'Inspiration / moral influence', pronunciation: 'gam-hwa', example: '그 분의 삶에 감화받았어.', exampleTranslation: 'I was inspired by his life.' },
    { korean: '귀감', english: 'Model / example to follow', pronunciation: 'gwi-gam', example: '모두의 귀감이 되는 분이야.', exampleTranslation: 'He is a model for everyone.' },
    { korean: '선의', english: 'Good intentions', pronunciation: 'seon-ui', example: '선의로 한 일이야.', exampleTranslation: 'It was done with good intentions.' },
    { korean: '악의', english: 'Malice / ill will', pronunciation: 'ak-ui', example: '악의 없이 한 말이야.', exampleTranslation: 'I said it without malice.' },
    { korean: '순교', english: 'Martyrdom', pronunciation: 'sun-gyo', example: '사랑을 위한 순교야.', exampleTranslation: 'It\'s martyrdom for love.' },
    { korean: '의지', english: 'Will / willpower', pronunciation: 'ui-ji', example: '강한 의지를 가져야 해.', exampleTranslation: 'You must have strong willpower.' },
    { korean: '고뇌', english: 'Anguish / agony', pronunciation: 'go-noe', example: '깊은 고뇌에 빠졌어.', exampleTranslation: 'I fell into deep anguish.' },
    { korean: '번뇌', english: 'Worldly cares / torment', pronunciation: 'beon-noe', example: '번뇌에서 벗어나고 싶어.', exampleTranslation: 'I want to free myself from worldly torments.' },
    { korean: '울분', english: 'Indignation / pent-up anger', pronunciation: 'ul-bun', example: '울분을 삼켰어.', exampleTranslation: 'I swallowed my indignation.' },
    { korean: '패배', english: 'Defeat', pronunciation: 'pae-bae', example: '패배를 인정해야 해.', exampleTranslation: 'You must accept defeat.' },
    { korean: '승리', english: 'Victory', pronunciation: 'seung-ni', example: '최후의 승리는 우리 거야.', exampleTranslation: 'The final victory is ours.' },
    { korean: '결말', english: 'Ending / conclusion', pronunciation: 'gyeol-mal', example: '어떤 결말이 올까.', exampleTranslation: 'What ending will come.' },
    { korean: '반전', english: 'Plot twist', pronunciation: 'ban-jeon', example: '반전이 기다리고 있어.', exampleTranslation: 'A plot twist awaits.' },
    { korean: '복선', english: 'Foreshadowing', pronunciation: 'bok-seon', example: '이 장면이 복선이었어.', exampleTranslation: 'This scene was foreshadowing.' },
    { korean: '서사', english: 'Narrative / epic', pronunciation: 'seo-sa', example: '웅장한 서사야.', exampleTranslation: 'It\'s a grand narrative.' },
    { korean: '구원', english: 'Salvation / rescue', pronunciation: 'gu-won', example: '구원의 손길이 필요해.', exampleTranslation: 'A helping hand of salvation is needed.' },
    { korean: '속박', english: 'Bondage / restraint', pronunciation: 'sok-bak', example: '속박에서 벗어나야 해.', exampleTranslation: 'You must break free from bondage.' },
    { korean: '해방', english: 'Liberation', pronunciation: 'hae-bang', example: '드디어 해방됐어.', exampleTranslation: 'I\'m finally liberated.' },
    { korean: '응징', english: 'Punishment / retribution', pronunciation: 'eung-jing', example: '악인에 대한 응징이야.', exampleTranslation: 'It\'s retribution for the evildoer.' },
    { korean: '심판', english: 'Judgment', pronunciation: 'sim-pan', example: '하늘의 심판을 받을 거야.', exampleTranslation: 'You will face divine judgment.' },
    { korean: '통한', english: 'Deep regret / bitter grudge', pronunciation: 'tong-han', example: '통한의 눈물을 흘렸어.', exampleTranslation: 'He shed tears of deep regret.' },
    { korean: '비극', english: 'Tragedy', pronunciation: 'bi-geuk', example: '비극적인 결말이야.', exampleTranslation: 'It\'s a tragic ending.' },
    { korean: '서막', english: 'Prologue / prelude', pronunciation: 'seo-mak', example: '이건 시작의 서막에 불과해.', exampleTranslation: 'This is merely the prelude to the beginning.' },
    { korean: '종막', english: 'Epilogue / finale', pronunciation: 'jong-mak', example: '드디어 종막을 내려야 할 때야.', exampleTranslation: 'It\'s time to bring down the final curtain.' },
    { korean: '대서사시', english: 'Grand epic', pronunciation: 'dae-seo-sa-si', example: '한 편의 대서사시 같은 삶이야.', exampleTranslation: 'It\'s a life like a grand epic.' },
    { korean: '카타르시스', english: 'Catharsis', pronunciation: 'ka-ta-reu-si-seu', example: '마지막 장면에서 카타르시스를 느꼈어.', exampleTranslation: 'I felt catharsis in the last scene.' },
    { korean: '서정적', english: 'Lyrical / poetic', pronunciation: 'seo-jeong-jeok', example: '서정적인 분위기의 드라마야.', exampleTranslation: 'It\'s a drama with a lyrical atmosphere.' },
  ],
  6: [
    { korean: '호사다마', english: 'Good things invite trouble', pronunciation: 'ho-sa-da-ma', example: '호사다마라더니 역시...', exampleTranslation: 'They say good things invite trouble, and sure enough...' },
    { korean: '새옹지마', english: 'A blessing in disguise', pronunciation: 'sae-ong-ji-ma', example: '새옹지마라고, 다 잘 될 거야.', exampleTranslation: 'A blessing in disguise—everything will work out.' },
    { korean: '권선징악', english: 'Good is rewarded and evil punished', pronunciation: 'gwon-seon-jing-ak', example: '결국 권선징악이야.', exampleTranslation: 'In the end, good is rewarded and evil is punished.' },
    { korean: '유비무환', english: 'Being prepared averts disaster', pronunciation: 'yu-bi-mu-hwan', example: '유비무환이라고 했잖아.', exampleTranslation: 'As they say, preparation averts disaster.' },
    { korean: '일석이조', english: 'Killing two birds with one stone', pronunciation: 'il-seok-i-jo', example: '일석이조의 계획이야.', exampleTranslation: 'It\'s a plan that kills two birds with one stone.' },
    { korean: '전화위복', english: 'Turning disaster into fortune', pronunciation: 'jeon-hwa-wi-bok', example: '전화위복이 될 수 있어.', exampleTranslation: 'It can turn disaster into fortune.' },
    { korean: '고진감래', english: 'After hardship comes sweetness', pronunciation: 'go-jin-gam-rae', example: '고진감래, 좋은 날이 올 거야.', exampleTranslation: 'After hardship comes sweetness—good days will come.' },
    { korean: '각골난망', english: 'Unforgettable gratitude', pronunciation: 'gak-gol-nan-mang', example: '각골난망의 은혜입니다.', exampleTranslation: 'It\'s a favor I\'ll never forget.' },
    { korean: '풍전등화', english: 'In imminent danger', pronunciation: 'pung-jeon-deung-hwa', example: '회사가 풍전등화야.', exampleTranslation: 'The company is in imminent danger.' },
    { korean: '사필귀정', english: 'Things will sort themselves out', pronunciation: 'sa-pil-gwi-jeong', example: '사필귀정이야, 진실은 밝혀져.', exampleTranslation: 'Things sort themselves out—the truth will come to light.' },
    { korean: '이심전심', english: 'Heart-to-heart communication', pronunciation: 'i-sim-jeon-sim', example: '이심전심이라 말 안 해도 알아.', exampleTranslation: 'Heart to heart, I know without words.' },
    { korean: '동병상련', english: 'Shared hardship breeds sympathy', pronunciation: 'dong-byeong-sang-ryeon', example: '동병상련으로 서로를 이해해.', exampleTranslation: 'Through shared hardship, we understand each other.' },
    { korean: '오매불망', english: 'Unable to forget day or night', pronunciation: 'o-mae-bul-mang', example: '오매불망 당신만 생각했어요.', exampleTranslation: 'Day and night, I could only think of you.' },
    { korean: '일편단심', english: 'Unwavering devotion', pronunciation: 'il-pyeon-dan-sim', example: '일편단심 한 사람만 사랑했어.', exampleTranslation: 'With unwavering devotion, I loved only one person.' },
    { korean: '혈혈단신', english: 'All alone in the world', pronunciation: 'hyeol-hyeol-dan-sin', example: '혈혈단신으로 이 세상에 남았어.', exampleTranslation: 'I was left all alone in this world.' },
    { korean: '자포자기', english: 'Giving up in despair', pronunciation: 'ja-po-ja-gi', example: '자포자기하지 마.', exampleTranslation: 'Don\'t give up in despair.' },
    { korean: '오리무중', english: 'Completely in the dark', pronunciation: 'o-ri-mu-jung', example: '사건이 오리무중이야.', exampleTranslation: 'The case is completely in the dark.' },
    { korean: '대기만성', english: 'Great talents mature late', pronunciation: 'dae-gi-man-seong', example: '대기만성이라고, 아직 때가 안 됐어.', exampleTranslation: 'Great talents mature late—the time hasn\'t come yet.' },
    { korean: '과유불급', english: 'Too much is as bad as too little', pronunciation: 'gwa-yu-bul-geup', example: '과유불급이야, 적당히 해.', exampleTranslation: 'Too much is as bad as too little—do it in moderation.' },
    { korean: '금지옥엽', english: 'Precious child', pronunciation: 'geum-ji-ok-yeop', example: '금지옥엽으로 키웠어요.', exampleTranslation: 'I raised the child like a precious treasure.' },
    { korean: '천재일우', english: 'Once in a thousand years opportunity', pronunciation: 'cheon-jae-il-u', example: '천재일우의 기회야.', exampleTranslation: 'It\'s a once-in-a-lifetime opportunity.' },
    { korean: '형설지공', english: 'Success through hard study', pronunciation: 'hyeong-seol-ji-gong', example: '형설지공으로 성공했어.', exampleTranslation: 'He succeeded through diligent study.' },
    { korean: '와신상담', english: 'Enduring hardship to achieve revenge', pronunciation: 'wa-sin-sang-dam', example: '와신상담하며 기회를 기다렸어.', exampleTranslation: 'I endured hardships and waited for the right moment.' },
    { korean: '오합지졸', english: 'Ragtag band / disorganized group', pronunciation: 'o-hap-ji-jol', example: '오합지졸 같은 조직이야.', exampleTranslation: 'It\'s a ragtag organization.' },
    { korean: '낙화유수', english: 'Fallen flowers on flowing water (mutual love)', pronunciation: 'nak-hwa-yu-su', example: '낙화유수처럼 서로에게 끌려.', exampleTranslation: 'Like fallen flowers on flowing water, they\'re drawn to each other.' },
    { korean: '연목구어', english: 'Climbing a tree to find fish (impossible task)', pronunciation: 'yeon-mok-gu-eo', example: '그건 연목구어야.', exampleTranslation: 'That\'s like climbing a tree to find a fish.' },
    { korean: '청출어람', english: 'Student surpasses the master', pronunciation: 'cheong-chul-eo-ram', example: '청출어람이네, 스승보다 낫다.', exampleTranslation: 'The student has surpassed the master.' },
    { korean: '풍찬노숙', english: 'Sleeping rough / enduring harsh conditions', pronunciation: 'pung-chan-no-suk', example: '풍찬노숙을 하며 떠돌았어.', exampleTranslation: 'He wandered, sleeping rough in harsh conditions.' },
    { korean: '함흥차사', english: 'Messenger who never returns (no news)', pronunciation: 'ham-heung-cha-sa', example: '보낸 사람이 함흥차사야.', exampleTranslation: 'The person I sent never came back with news.' },
    { korean: '조삼모사', english: 'Tricking with the same thing differently presented', pronunciation: 'jo-sam-mo-sa', example: '조삼모사 같은 수법이야.', exampleTranslation: 'It\'s a deceptive trick.' },
    { korean: '격세지감', english: 'Feeling of a different era', pronunciation: 'gyeok-se-ji-gam', example: '격세지감을 느껴요.', exampleTranslation: 'I feel like it\'s a different era.' },
    { korean: '비분강개', english: 'Righteous indignation', pronunciation: 'bi-bun-gang-gae', example: '비분강개를 금할 수 없어.', exampleTranslation: 'I cannot contain my righteous indignation.' },
    { korean: '경거망동', english: 'Rash and reckless behavior', pronunciation: 'gyeong-geo-mang-dong', example: '경거망동하지 마.', exampleTranslation: 'Don\'t act rashly.' },
    { korean: '우유부단', english: 'Indecisive / wishy-washy', pronunciation: 'u-yu-bu-dan', example: '우유부단한 성격이야.', exampleTranslation: 'He has an indecisive personality.' },
    { korean: '안하무인', english: 'Arrogant / acting as if no one else exists', pronunciation: 'an-ha-mu-in', example: '안하무인 격으로 행동해.', exampleTranslation: 'He acts arrogantly as if nobody else matters.' },
    { korean: '교언영색', english: 'Flattering words and deceitful looks', pronunciation: 'gyo-eon-yeong-saek', example: '교언영색으로 사람을 속여.', exampleTranslation: 'He deceives people with flattery and false pretenses.' },
    { korean: '명불허전', english: 'Living up to one\'s reputation', pronunciation: 'myeong-bul-heo-jeon', example: '명불허전이네요.', exampleTranslation: 'It truly lives up to its reputation.' },
    { korean: '기상천외', english: 'Extraordinary / out of this world', pronunciation: 'gi-sang-cheon-oe', example: '기상천외한 발상이야.', exampleTranslation: 'It\'s an extraordinary idea.' },
    { korean: '적반하장', english: 'The guilty party accuses the innocent', pronunciation: 'jeok-ban-ha-jang', example: '적반하장도 유분수지!', exampleTranslation: 'The nerve of the guilty accusing the innocent!' },
    { korean: '감언이설', english: 'Sweet talk / honeyed words', pronunciation: 'gam-eon-i-seol', example: '감언이설에 속지 마.', exampleTranslation: 'Don\'t be fooled by sweet talk.' },
    { korean: '구사일생', english: 'Narrow escape from death', pronunciation: 'gu-sa-il-saeng', example: '구사일생으로 살아남았어.', exampleTranslation: 'I narrowly escaped death.' },
    { korean: '백전백승', english: 'Invincible / winning every battle', pronunciation: 'baek-jeon-baek-seung', example: '그는 백전백승의 장군이야.', exampleTranslation: 'He is an invincible general.' },
    { korean: '이전투구', english: 'Mud-slinging fight', pronunciation: 'i-jeon-tu-gu', example: '이전투구 같은 싸움이야.', exampleTranslation: 'It\'s a mud-slinging fight.' },
    { korean: '어부지리', english: 'Profiting from others\' conflict', pronunciation: 'eo-bu-ji-ri', example: '어부지리로 이득을 봤어.', exampleTranslation: 'I profited from others\' conflict.' },
    { korean: '위풍당당', english: 'Dignified and imposing', pronunciation: 'wi-pung-dang-dang', example: '위풍당당하게 걸어왔어.', exampleTranslation: 'He walked in with an imposing air.' },
    { korean: '용두사미', english: 'Strong start, weak finish', pronunciation: 'yong-du-sa-mi', example: '용두사미로 끝났어.', exampleTranslation: 'It ended with a strong start but a weak finish.' },
    { korean: '대동소이', english: 'More or less the same', pronunciation: 'dae-dong-so-i', example: '결과는 대동소이해.', exampleTranslation: 'The results are more or less the same.' },
    { korean: '유유상종', english: 'Birds of a feather flock together', pronunciation: 'yu-yu-sang-jong', example: '유유상종이라고, 역시 같은 부류야.', exampleTranslation: 'Birds of a feather, as expected they\'re the same kind.' },
    { korean: '아전인수', english: 'Self-serving interpretation', pronunciation: 'a-jeon-in-su', example: '아전인수 격으로 해석하네.', exampleTranslation: 'You\'re interpreting it in a self-serving way.' },
    { korean: '일촉즉발', english: 'On the verge of eruption', pronunciation: 'il-chok-jeuk-bal', example: '일촉즉발의 상황이야.', exampleTranslation: 'It\'s a volatile situation.' },
    { korean: '점입가경', english: 'Going from bad to worse', pronunciation: 'jeom-ip-ga-gyeong', example: '상황이 점입가경이야.', exampleTranslation: 'The situation is going from bad to worse.' },
    { korean: '진수성찬', english: 'Lavish feast', pronunciation: 'jin-su-seong-chan', example: '진수성찬을 차려놨어.', exampleTranslation: 'A lavish feast was prepared.' },
    { korean: '설상가상', english: 'Adding insult to injury', pronunciation: 'seol-sang-ga-sang', example: '설상가상으로 비까지 와.', exampleTranslation: 'To make matters worse, it\'s even raining.' },
    { korean: '천방지축', english: 'Reckless / out of control', pronunciation: 'cheon-bang-ji-chuk', example: '천방지축으로 뛰어다녀.', exampleTranslation: 'He runs around recklessly.' },
    { korean: '무위도식', english: 'Idle living without purpose', pronunciation: 'mu-wi-do-sik', example: '무위도식하며 세월을 보내.', exampleTranslation: 'He spends his days living idly.' },
    { korean: '마이동풍', english: 'Like wind in a horse\'s ear (ignored advice)', pronunciation: 'ma-i-dong-pung', example: '충고가 마이동풍이야.', exampleTranslation: 'My advice falls on deaf ears.' },
    { korean: '허심탄회', english: 'Open and candid', pronunciation: 'heo-sim-tan-hoe', example: '허심탄회하게 이야기하자.', exampleTranslation: 'Let\'s talk openly and candidly.' },
    { korean: '면종복배', english: 'Obedient in face, defiant behind', pronunciation: 'myeon-jong-bok-bae', example: '면종복배하는 사람이야.', exampleTranslation: 'He\'s obedient to your face but defiant behind your back.' },
    { korean: '구밀복검', english: 'Honey in mouth, sword in belly', pronunciation: 'gu-mil-bok-geom', example: '구밀복검인 사람을 조심해.', exampleTranslation: 'Beware of those with honey on their lips and a sword in their heart.' },
    { korean: '견물생심', english: 'Seeing something creates desire', pronunciation: 'gyeon-mul-saeng-sim', example: '견물생심이라고, 보니까 갖고 싶어.', exampleTranslation: 'Seeing it makes me want it.' },
    { korean: '일취월장', english: 'Rapid improvement', pronunciation: 'il-chwi-wol-jang', example: '실력이 일취월장했어.', exampleTranslation: 'Your skills have improved rapidly.' },
    { korean: '탁상공론', english: 'Armchair theory / impractical discussion', pronunciation: 'tak-sang-gong-ron', example: '탁상공론은 그만해.', exampleTranslation: 'Stop the armchair theorizing.' },
    { korean: '잔혹무도', english: 'Cruel and heartless', pronunciation: 'jan-hok-mu-do', example: '잔혹무도한 행위야.', exampleTranslation: 'It\'s a cruel and heartless act.' },
    { korean: '자초지종', english: 'The whole story from beginning to end', pronunciation: 'ja-cho-ji-jong', example: '자초지종을 설명해 봐.', exampleTranslation: 'Explain the whole story from start to finish.' },
    { korean: '좌불안석', english: 'Restless with anxiety', pronunciation: 'jwa-bul-an-seok', example: '좌불안석이야, 결과가 걱정돼.', exampleTranslation: 'I\'m restless with worry about the results.' },
    { korean: '전전긍긍', english: 'Trembling with anxiety', pronunciation: 'jeon-jeon-geung-geung', example: '전전긍긍하며 소식을 기다려.', exampleTranslation: 'I wait for news, trembling with anxiety.' },
    { korean: '노심초사', english: 'Anxiously worried', pronunciation: 'no-sim-cho-sa', example: '노심초사하며 아이를 기다렸어.', exampleTranslation: 'I waited anxiously for the child.' },
    { korean: '수수방관', english: 'Standing by idly', pronunciation: 'su-su-bang-gwan', example: '수수방관만 하고 있을 거야?', exampleTranslation: 'Are you just going to stand by and watch?' },
    { korean: '사생결단', english: 'Fighting to the death', pronunciation: 'sa-saeng-gyeol-dan', example: '사생결단의 각오로 임해.', exampleTranslation: 'I face it with a do-or-die resolve.' },
    { korean: '불철주야', english: 'Day and night without rest', pronunciation: 'bul-cheol-ju-ya', example: '불철주야 노력했어.', exampleTranslation: 'I worked day and night without rest.' },
    { korean: '금시초문', english: 'Hearing it for the first time', pronunciation: 'geum-si-cho-mun', example: '금시초문이야, 처음 듣는 얘기야.', exampleTranslation: 'This is the first I\'ve heard of it.' },
    { korean: '대경실색', english: 'Turning pale with shock', pronunciation: 'dae-gyeong-sil-saek', example: '소식을 듣고 대경실색했어.', exampleTranslation: 'Upon hearing the news, he turned pale with shock.' },
    { korean: '의기양양', english: 'Triumphant / elated', pronunciation: 'ui-gi-yang-yang', example: '의기양양하게 돌아왔어.', exampleTranslation: 'He returned triumphantly.' },
    { korean: '자화자찬', english: 'Self-praise / tooting one\'s own horn', pronunciation: 'ja-hwa-ja-chan', example: '자화자찬은 그만해.', exampleTranslation: 'Stop singing your own praises.' },
    { korean: '군계일학', english: 'A crane among chickens (outstanding person)', pronunciation: 'gun-gye-il-hak', example: '군계일학 같은 존재야.', exampleTranslation: 'He stands out like a crane among chickens.' },
    { korean: '진퇴유곡', english: 'No way forward or backward', pronunciation: 'jin-toe-yu-gok', example: '진퇴유곡의 상황이에요.', exampleTranslation: 'There\'s no way forward or backward.' },
    { korean: '자강불식', english: 'Ceaseless self-improvement', pronunciation: 'ja-gang-bul-sik', example: '자강불식의 정신으로 살아.', exampleTranslation: 'Live with the spirit of ceaseless self-improvement.' },
    { korean: '불가항력', english: 'Force majeure / irresistible force', pronunciation: 'bul-ga-hang-nyeok', example: '불가항력이었어요.', exampleTranslation: 'It was an irresistible force.' },
    { korean: '절차탁마', english: 'Polishing and refining oneself', pronunciation: 'jeol-cha-tak-ma', example: '절차탁마하며 성장해야 해.', exampleTranslation: 'You must grow by constantly refining yourself.' },
    { korean: '막무가내', english: 'Unreasonable insistence', pronunciation: 'mak-mu-ga-nae', example: '막무가내로 우기고 있어.', exampleTranslation: 'He\'s unreasonably insisting.' },
    { korean: '무소불위', english: 'Omnipotent power / unchecked authority', pronunciation: 'mu-so-bul-wi', example: '무소불위의 권력을 휘둘러.', exampleTranslation: 'He wields unchecked power.' },
    { korean: '풍비박산', english: 'Completely shattered', pronunciation: 'pung-bi-bak-san', example: '계획이 풍비박산 났어.', exampleTranslation: 'The plan was completely shattered.' },
    { korean: '속수무책', english: 'Helpless / no measures to take', pronunciation: 'sok-su-mu-chaek', example: '속수무책으로 당했어.', exampleTranslation: 'I was helplessly overwhelmed.' },
    { korean: '유언비어', english: 'Baseless rumors / false rumors', pronunciation: 'yu-eon-bi-eo', example: '유언비어를 퍼뜨리지 마.', exampleTranslation: 'Don\'t spread baseless rumors.' },
    { korean: '작심삼일', english: 'Resolution lasting only three days', pronunciation: 'jak-sim-sam-il', example: '또 작심삼일이야?', exampleTranslation: 'Your resolution only lasted three days again?' },
    { korean: '지록위마', english: 'Calling a deer a horse (distorting truth)', pronunciation: 'ji-rok-wi-ma', example: '지록위마 같은 거짓말이야.', exampleTranslation: 'It\'s a lie that distorts the truth.' },
    { korean: '파죽지세', english: 'Unstoppable momentum', pronunciation: 'pa-juk-ji-se', example: '파죽지세로 밀어붙여.', exampleTranslation: 'Push forward with unstoppable momentum.' },
    { korean: '천고마비', english: 'Clear autumn skies (harvest time)', pronunciation: 'cheon-go-ma-bi', example: '천고마비의 계절이야.', exampleTranslation: 'It\'s the season of clear autumn skies.' },
    { korean: '이판사판', english: 'All or nothing / desperate', pronunciation: 'i-pan-sa-pan', example: '이판사판이야, 해 보자!', exampleTranslation: 'It\'s all or nothing—let\'s do it!' },
    { korean: '인면수심', english: 'Human face, beast heart (cold-hearted)', pronunciation: 'in-myeon-su-sim', example: '인면수심인 사람이야.', exampleTranslation: 'He has a human face but a beast\'s heart.' },
    { korean: '가인박명', english: 'A beauty\'s fate is often tragic', pronunciation: 'ga-in-bak-myeong', example: '가인박명이라더니...', exampleTranslation: 'They say a beauty\'s fate is tragic, and sure enough...' },
    { korean: '백년해로', english: 'Growing old together (marital bliss)', pronunciation: 'baek-nyeon-hae-ro', example: '백년해로 하세요.', exampleTranslation: 'May you grow old together happily.' },
    { korean: '칠전팔기', english: 'Fall seven times, rise eight', pronunciation: 'chil-jeon-pal-gi', example: '칠전팔기의 정신으로 살아.', exampleTranslation: 'Live with the spirit of falling seven times and rising eight.' },
    { korean: '살신성인', english: 'Sacrificing oneself for a noble cause', pronunciation: 'sal-sin-seong-in', example: '살신성인의 정신이야.', exampleTranslation: 'It\'s the spirit of self-sacrifice for a noble cause.' },
    { korean: '부전자전', english: 'Like father, like son', pronunciation: 'bu-jeon-ja-jeon', example: '부전자전이네.', exampleTranslation: 'Like father, like son.' },
    { korean: '소탐대실', english: 'Losing the big picture for small gains', pronunciation: 'so-tam-dae-sil', example: '소탐대실하지 마.', exampleTranslation: 'Don\'t lose the big picture chasing small gains.' },
    { korean: '금상첨화', english: 'Icing on the cake', pronunciation: 'geum-sang-cheom-hwa', example: '합격에 장학금까지, 금상첨화야!', exampleTranslation: 'Passing plus a scholarship—icing on the cake!' },
    { korean: '일망타진', english: 'Wiping out in one sweep', pronunciation: 'il-mang-ta-jin', example: '범죄 조직을 일망타진했어.', exampleTranslation: 'We wiped out the criminal organization in one sweep.' },
    { korean: '동귀어진', english: 'Perishing together with the enemy', pronunciation: 'dong-gwi-eo-jin', example: '동귀어진할 각오야.', exampleTranslation: 'I\'m prepared to take you down with me.' },
    { korean: '배수진', english: 'Burning bridges / no retreat', pronunciation: 'bae-su-jin', example: '배수진을 쳤어.', exampleTranslation: 'I\'ve burned all bridges behind me.' },
  ],
};
