import { ThemeWord } from '../theme-data';

export const KFOOD_WORDS: Record<number, ThemeWord[]> = {
  1: [
    { korean: '밥', english: 'Rice (cooked)', pronunciation: 'bap', example: '밥 먹었어?', exampleTranslation: 'Have you eaten rice?' },
    { korean: '김치', english: 'Kimchi', pronunciation: 'gim-chi', example: '김치가 맛있어요.', exampleTranslation: 'The kimchi is delicious.' },
    { korean: '물', english: 'Water', pronunciation: 'mul', example: '물 한 잔 주세요.', exampleTranslation: 'One glass of water please.' },
    { korean: '고기', english: 'Meat', pronunciation: 'go-gi', example: '고기 좋아해요?', exampleTranslation: 'Do you like meat?' },
    { korean: '야채', english: 'Vegetables', pronunciation: 'ya-chae', example: '야채를 많이 먹어야 해요.', exampleTranslation: 'You should eat a lot of vegetables.' },
    { korean: '과일', english: 'Fruit', pronunciation: 'gwa-il', example: '과일이 신선해요.', exampleTranslation: 'The fruit is fresh.' },
    { korean: '국', english: 'Soup', pronunciation: 'guk', example: '국이 뜨거워요.', exampleTranslation: 'The soup is hot.' },
    { korean: '빵', english: 'Bread', pronunciation: 'ppang', example: '아침에 빵을 먹었어요.', exampleTranslation: 'I ate bread in the morning.' },
    { korean: '달걀', english: 'Egg', pronunciation: 'dal-gyal', example: '달걀 프라이 해 줘.', exampleTranslation: 'Make me a fried egg.' },
    { korean: '우유', english: 'Milk', pronunciation: 'u-yu', example: '우유를 매일 마셔요.', exampleTranslation: 'I drink milk every day.' },
    { korean: '사과', english: 'Apple', pronunciation: 'sa-gwa', example: '사과 하나 주세요.', exampleTranslation: 'One apple please.' },
    { korean: '배', english: 'Pear', pronunciation: 'bae', example: '한국 배는 달아요.', exampleTranslation: 'Korean pears are sweet.' },
    { korean: '포도', english: 'Grape', pronunciation: 'po-do', example: '포도가 맛있어요.', exampleTranslation: 'The grapes are delicious.' },
    { korean: '딸기', english: 'Strawberry', pronunciation: 'ttal-gi', example: '딸기 케이크 좋아해요.', exampleTranslation: 'I like strawberry cake.' },
    { korean: '수박', english: 'Watermelon', pronunciation: 'su-bak', example: '여름에 수박이 최고야.', exampleTranslation: 'Watermelon is the best in summer.' },
    { korean: '바나나', english: 'Banana', pronunciation: 'ba-na-na', example: '바나나 우유 마실래?', exampleTranslation: 'Do you want banana milk?' },
    { korean: '귤', english: 'Tangerine', pronunciation: 'gyul', example: '제주 귤이 유명해요.', exampleTranslation: 'Jeju tangerines are famous.' },
    { korean: '감', english: 'Persimmon', pronunciation: 'gam', example: '가을에 감이 맛있어요.', exampleTranslation: 'Persimmons are delicious in autumn.' },
    { korean: '소고기', english: 'Beef', pronunciation: 'so-go-gi', example: '한우 소고기가 비싸요.', exampleTranslation: 'Korean beef is expensive.' },
    { korean: '돼지고기', english: 'Pork', pronunciation: 'dwae-ji-go-gi', example: '돼지고기 볶음 만들자.', exampleTranslation: 'Let\'s make stir-fried pork.' },
    { korean: '닭고기', english: 'Chicken meat', pronunciation: 'dak-go-gi', example: '닭고기가 부드러워요.', exampleTranslation: 'The chicken is tender.' },
    { korean: '생선', english: 'Fish', pronunciation: 'saeng-seon', example: '생선구이 좋아해요?', exampleTranslation: 'Do you like grilled fish?' },
    { korean: '새우', english: 'Shrimp', pronunciation: 'sae-u', example: '새우튀김 맛있어요.', exampleTranslation: 'Fried shrimp is delicious.' },
    { korean: '오징어', english: 'Squid', pronunciation: 'o-jing-eo', example: '오징어볶음 먹을래?', exampleTranslation: 'Do you want stir-fried squid?' },
    { korean: '두부', english: 'Tofu', pronunciation: 'du-bu', example: '순두부찌개 주세요.', exampleTranslation: 'Soft tofu stew please.' },
    { korean: '콩', english: 'Bean / Soybean', pronunciation: 'kong', example: '콩으로 두부를 만들어요.', exampleTranslation: 'Tofu is made from soybeans.' },
    { korean: '쌀', english: 'Rice (uncooked)', pronunciation: 'ssal', example: '쌀을 씻어 주세요.', exampleTranslation: 'Please wash the rice.' },
    { korean: '면', english: 'Noodles', pronunciation: 'myeon', example: '면 요리를 좋아해요.', exampleTranslation: 'I like noodle dishes.' },
    { korean: '떡', english: 'Rice cake', pronunciation: 'tteok', example: '설날에 떡을 먹어요.', exampleTranslation: 'We eat rice cake on New Year\'s.' },
    { korean: '소금', english: 'Salt', pronunciation: 'so-geum', example: '소금을 좀 넣어 주세요.', exampleTranslation: 'Please add some salt.' },
    { korean: '설탕', english: 'Sugar', pronunciation: 'seol-tang', example: '설탕을 너무 많이 넣었어요.', exampleTranslation: 'I put too much sugar.' },
    { korean: '간장', english: 'Soy sauce', pronunciation: 'gan-jang', example: '간장에 찍어 먹어요.', exampleTranslation: 'Dip it in soy sauce and eat.' },
    { korean: '고추장', english: 'Red pepper paste', pronunciation: 'go-chu-jang', example: '고추장이 매워요.', exampleTranslation: 'The red pepper paste is spicy.' },
    { korean: '된장', english: 'Soybean paste', pronunciation: 'doen-jang', example: '된장찌개 끓여 줄게.', exampleTranslation: 'I\'ll make soybean paste stew.' },
    { korean: '참기름', english: 'Sesame oil', pronunciation: 'cham-gi-reum', example: '참기름 향이 좋아요.', exampleTranslation: 'The sesame oil smells great.' },
    { korean: '식초', english: 'Vinegar', pronunciation: 'sik-cho', example: '식초를 조금 넣으세요.', exampleTranslation: 'Add a little vinegar.' },
    { korean: '마늘', english: 'Garlic', pronunciation: 'ma-neul', example: '한국 요리에 마늘이 많이 들어가요.', exampleTranslation: 'Korean food uses a lot of garlic.' },
    { korean: '양파', english: 'Onion', pronunciation: 'yang-pa', example: '양파를 썰어 주세요.', exampleTranslation: 'Please slice the onion.' },
    { korean: '고추', english: 'Chili pepper', pronunciation: 'go-chu', example: '고추가 매워요.', exampleTranslation: 'The chili pepper is spicy.' },
    { korean: '파', english: 'Green onion', pronunciation: 'pa', example: '파를 송송 썰어 주세요.', exampleTranslation: 'Please chop the green onion finely.' },
    { korean: '배추', english: 'Napa cabbage', pronunciation: 'bae-chu', example: '배추로 김치를 담가요.', exampleTranslation: 'We make kimchi with napa cabbage.' },
    { korean: '무', english: 'Radish', pronunciation: 'mu', example: '무를 깍둑썰기 해 주세요.', exampleTranslation: 'Please dice the radish.' },
    { korean: '당근', english: 'Carrot', pronunciation: 'dang-geun', example: '당근을 채 썰어요.', exampleTranslation: 'Julienne the carrot.' },
    { korean: '감자', english: 'Potato', pronunciation: 'gam-ja', example: '감자탕 먹을래?', exampleTranslation: 'Do you want potato stew?' },
    { korean: '고구마', english: 'Sweet potato', pronunciation: 'go-gu-ma', example: '군고구마 먹고 싶어.', exampleTranslation: 'I want to eat roasted sweet potato.' },
    { korean: '버섯', english: 'Mushroom', pronunciation: 'beo-seot', example: '버섯전 만들자.', exampleTranslation: 'Let\'s make mushroom pancakes.' },
    { korean: '김', english: 'Seaweed (dried)', pronunciation: 'gim', example: '김을 밥에 싸 먹어요.', exampleTranslation: 'Wrap rice in seaweed and eat.' },
    { korean: '미역', english: 'Seaweed (wakame)', pronunciation: 'mi-yeok', example: '생일에 미역국을 먹어요.', exampleTranslation: 'We eat seaweed soup on birthdays.' },
    { korean: '오이', english: 'Cucumber', pronunciation: 'o-i', example: '오이를 냉장고에 넣어.', exampleTranslation: 'Put the cucumber in the fridge.' },
    { korean: '상추', english: 'Lettuce', pronunciation: 'sang-chu', example: '상추에 고기 싸 먹어요.', exampleTranslation: 'Wrap meat in lettuce and eat.' },
    { korean: '깻잎', english: 'Perilla leaf', pronunciation: 'kkaen-nip', example: '깻잎에 밥 싸 먹으면 맛있어요.', exampleTranslation: 'It\'s delicious to wrap rice in perilla leaves.' },
    { korean: '호박', english: 'Zucchini / Pumpkin', pronunciation: 'ho-bak', example: '호박전이 맛있어요.', exampleTranslation: 'Zucchini pancakes are delicious.' },
    { korean: '콩나물', english: 'Bean sprouts', pronunciation: 'kong-na-mul', example: '콩나물국 끓여 줘.', exampleTranslation: 'Make me bean sprout soup.' },
    { korean: '시금치', english: 'Spinach', pronunciation: 'si-geum-chi', example: '시금치 나물 해 줄게.', exampleTranslation: 'I\'ll make spinach side dish.' },
    { korean: '밀가루', english: 'Flour', pronunciation: 'mil-ga-ru', example: '밀가루로 전을 부쳐요.', exampleTranslation: 'We make pancakes with flour.' },
    { korean: '기름', english: 'Oil', pronunciation: 'gi-reum', example: '기름을 두르세요.', exampleTranslation: 'Add oil to the pan.' },
    { korean: '후추', english: 'Black pepper', pronunciation: 'hu-chu', example: '후추를 좀 뿌려 주세요.', exampleTranslation: 'Please sprinkle some black pepper.' },
    { korean: '차', english: 'Tea', pronunciation: 'cha', example: '녹차 한 잔 할래요?', exampleTranslation: 'Would you like a cup of green tea?' },
    { korean: '커피', english: 'Coffee', pronunciation: 'keo-pi', example: '커피 마시러 가자.', exampleTranslation: 'Let\'s go get coffee.' },
    { korean: '주스', english: 'Juice', pronunciation: 'ju-seu', example: '오렌지 주스 주세요.', exampleTranslation: 'Orange juice please.' },
    { korean: '아이스크림', english: 'Ice cream', pronunciation: 'a-i-seu-keu-rim', example: '아이스크림 먹고 싶어.', exampleTranslation: 'I want ice cream.' },
    { korean: '과자', english: 'Snack / Cookie', pronunciation: 'gwa-ja', example: '과자 좀 사 와.', exampleTranslation: 'Buy some snacks.' },
    { korean: '케이크', english: 'Cake', pronunciation: 'ke-i-keu', example: '생일 케이크 샀어!', exampleTranslation: 'I bought a birthday cake!' },
    { korean: '초콜릿', english: 'Chocolate', pronunciation: 'cho-kol-lit', example: '초콜릿 좋아해요.', exampleTranslation: 'I like chocolate.' },
    { korean: '젓가락', english: 'Chopsticks', pronunciation: 'jeot-ga-rak', example: '젓가락 사용할 수 있어요?', exampleTranslation: 'Can you use chopsticks?' },
    { korean: '숟가락', english: 'Spoon', pronunciation: 'sut-ga-rak', example: '숟가락으로 국 먹어요.', exampleTranslation: 'Eat soup with a spoon.' },
    { korean: '접시', english: 'Plate', pronunciation: 'jeop-si', example: '접시에 담아 주세요.', exampleTranslation: 'Please put it on a plate.' },
    { korean: '그릇', english: 'Bowl', pronunciation: 'geu-reut', example: '밥그릇 좀 가져와.', exampleTranslation: 'Bring me a rice bowl.' },
    { korean: '컵', english: 'Cup', pronunciation: 'keop', example: '컵에 물 따라 줘.', exampleTranslation: 'Pour water into the cup.' },
    { korean: '냄비', english: 'Pot', pronunciation: 'naem-bi', example: '큰 냄비에 물을 끓여요.', exampleTranslation: 'Boil water in a big pot.' },
    { korean: '프라이팬', english: 'Frying pan', pronunciation: 'peu-ra-i-paen', example: '프라이팬에 기름을 두르세요.', exampleTranslation: 'Add oil to the frying pan.' },
    { korean: '칼', english: 'Knife', pronunciation: 'kal', example: '칼로 야채를 썰어요.', exampleTranslation: 'Cut vegetables with a knife.' },
    { korean: '도마', english: 'Cutting board', pronunciation: 'do-ma', example: '도마 위에서 썰어요.', exampleTranslation: 'Cut on the cutting board.' },
    { korean: '냉장고', english: 'Refrigerator', pronunciation: 'naeng-jang-go', example: '냉장고에 넣어 두세요.', exampleTranslation: 'Put it in the refrigerator.' },
    { korean: '전자레인지', english: 'Microwave', pronunciation: 'jeon-ja-re-in-ji', example: '전자레인지에 데워 먹어.', exampleTranslation: 'Heat it in the microwave and eat.' },
    { korean: '식당', english: 'Restaurant', pronunciation: 'sik-dang', example: '저 식당 가 볼까?', exampleTranslation: 'Shall we try that restaurant?' },
    { korean: '맛', english: 'Taste / Flavor', pronunciation: 'mat', example: '맛이 어때요?', exampleTranslation: 'How does it taste?' },
    { korean: '맛있다', english: 'Delicious', pronunciation: 'ma-sit-da', example: '이 음식 정말 맛있다!', exampleTranslation: 'This food is really delicious!' },
    { korean: '맛없다', english: 'Not tasty', pronunciation: 'ma-deop-da', example: '이건 좀 맛없어.', exampleTranslation: 'This is not very tasty.' },
    { korean: '배고프다', english: 'To be hungry', pronunciation: 'bae-go-peu-da', example: '배고파, 뭐 먹자.', exampleTranslation: 'I\'m hungry, let\'s eat something.' },
    { korean: '목마르다', english: 'To be thirsty', pronunciation: 'mok-ma-reu-da', example: '목말라, 물 좀 줘.', exampleTranslation: 'I\'m thirsty, give me water.' },
    { korean: '뜨겁다', english: 'Hot (temperature)', pronunciation: 'tteu-geop-da', example: '조심해, 뜨거워!', exampleTranslation: 'Be careful, it\'s hot!' },
    { korean: '차갑다', english: 'Cold (temperature)', pronunciation: 'cha-gap-da', example: '차가운 물 주세요.', exampleTranslation: 'Cold water please.' },
    { korean: '달다', english: 'Sweet', pronunciation: 'dal-da', example: '이 과자가 달아요.', exampleTranslation: 'This snack is sweet.' },
    { korean: '짜다', english: 'Salty', pronunciation: 'jja-da', example: '좀 짜지 않아요?', exampleTranslation: 'Isn\'t it a bit salty?' },
    { korean: '맵다', english: 'Spicy', pronunciation: 'maep-da', example: '이 음식은 매워요.', exampleTranslation: 'This food is spicy.' },
    { korean: '시다', english: 'Sour', pronunciation: 'si-da', example: '레몬이 셔요.', exampleTranslation: 'The lemon is sour.' },
    { korean: '쓰다', english: 'Bitter', pronunciation: 'sseu-da', example: '이 약은 써요.', exampleTranslation: 'This medicine is bitter.' },
    { korean: '싱겁다', english: 'Bland', pronunciation: 'sing-geop-da', example: '국이 싱거워요.', exampleTranslation: 'The soup is bland.' },
    { korean: '아침', english: 'Breakfast / Morning', pronunciation: 'a-chim', example: '아침 먹었어?', exampleTranslation: 'Did you eat breakfast?' },
    { korean: '점심', english: 'Lunch', pronunciation: 'jeom-sim', example: '점심 같이 먹을래?', exampleTranslation: 'Want to eat lunch together?' },
    { korean: '저녁', english: 'Dinner / Evening', pronunciation: 'jeo-nyeok', example: '저녁 뭐 먹을까?', exampleTranslation: 'What shall we eat for dinner?' },
    { korean: '간식', english: 'Snack (between meals)', pronunciation: 'gan-sik', example: '간식으로 과일 먹자.', exampleTranslation: 'Let\'s have fruit as a snack.' },
    { korean: '배부르다', english: 'To be full', pronunciation: 'bae-bu-reu-da', example: '배불러서 더 못 먹어.', exampleTranslation: 'I\'m so full I can\'t eat more.' },
    { korean: '요리', english: 'Cooking / Dish', pronunciation: 'yo-ri', example: '요리 잘해요?', exampleTranslation: 'Are you good at cooking?' },
    { korean: '음식', english: 'Food', pronunciation: 'eum-sik', example: '한국 음식 좋아해요?', exampleTranslation: 'Do you like Korean food?' },
    { korean: '먹다', english: 'To eat', pronunciation: 'meok-da', example: '많이 먹어!', exampleTranslation: 'Eat a lot!' },
    { korean: '마시다', english: 'To drink', pronunciation: 'ma-si-da', example: '뭐 마실래요?', exampleTranslation: 'What would you like to drink?' },
    { korean: '사다', english: 'To buy', pronunciation: 'sa-da', example: '장 보러 갈까?', exampleTranslation: 'Shall we go grocery shopping?' },
    { korean: '복숭아', english: 'Peach', pronunciation: 'bok-sung-a', example: '복숭아가 달콤해요.', exampleTranslation: 'The peach is sweet.' },
  ],
  2: [
    { korean: '주문하다', english: 'To order', pronunciation: 'ju-mun-ha-da', example: '주문하시겠어요?', exampleTranslation: 'Would you like to order?' },
    { korean: '메뉴', english: 'Menu', pronunciation: 'me-nyu', example: '메뉴 좀 보여 주세요.', exampleTranslation: 'Please show me the menu.' },
    { korean: '추천하다', english: 'To recommend', pronunciation: 'chu-cheon-ha-da', example: '뭐 추천해요?', exampleTranslation: 'What do you recommend?' },
    { korean: '예약하다', english: 'To reserve', pronunciation: 'ye-yak-ha-da', example: '내일 저녁 예약하고 싶어요.', exampleTranslation: 'I want to make a reservation for tomorrow evening.' },
    { korean: '계산하다', english: 'To pay / calculate', pronunciation: 'gye-san-ha-da', example: '카드로 계산할게요.', exampleTranslation: 'I\'ll pay by card.' },
    { korean: '맛집', english: 'Famous restaurant', pronunciation: 'mat-jip', example: '이 근처에 맛집 있어요?', exampleTranslation: 'Is there a famous restaurant nearby?' },
    { korean: '배달하다', english: 'To deliver', pronunciation: 'bae-dal-ha-da', example: '배달 얼마나 걸려요?', exampleTranslation: 'How long does delivery take?' },
    { korean: '포장하다', english: 'To pack / wrap', pronunciation: 'po-jang-ha-da', example: '포장해 가도 돼요?', exampleTranslation: 'Can I get it to go?' },
    { korean: '인분', english: 'Serving / portion', pronunciation: 'in-bun', example: '2인분 주세요.', exampleTranslation: 'Two servings please.' },
    { korean: '리필', english: 'Refill', pronunciation: 'ri-pil', example: '반찬 리필 돼요?', exampleTranslation: 'Can I get a refill on side dishes?' },
    { korean: '재료', english: 'Ingredient', pronunciation: 'jae-ryo', example: '재료가 신선해요.', exampleTranslation: 'The ingredients are fresh.' },
    { korean: '레시피', english: 'Recipe', pronunciation: 're-si-pi', example: '이 레시피 알려 주세요.', exampleTranslation: 'Please share this recipe.' },
    { korean: '조리법', english: 'Cooking method', pronunciation: 'jo-ri-beop', example: '조리법이 간단해요.', exampleTranslation: 'The cooking method is simple.' },
    { korean: '굽다', english: 'To grill / bake', pronunciation: 'gup-da', example: '고기를 잘 구워 주세요.', exampleTranslation: 'Please grill the meat well.' },
    { korean: '볶다', english: 'To stir-fry', pronunciation: 'bok-da', example: '센 불에 볶아요.', exampleTranslation: 'Stir-fry on high heat.' },
    { korean: '끓이다', english: 'To boil', pronunciation: 'kkeur-i-da', example: '30분 동안 끓이세요.', exampleTranslation: 'Boil for 30 minutes.' },
    { korean: '찌다', english: 'To steam', pronunciation: 'jji-da', example: '만두를 찌면 맛있어요.', exampleTranslation: 'Steamed dumplings are delicious.' },
    { korean: '튀기다', english: 'To deep-fry', pronunciation: 'twi-gi-da', example: '감자를 튀겨 주세요.', exampleTranslation: 'Please deep-fry the potatoes.' },
    { korean: '썰다', english: 'To slice / cut', pronunciation: 'sseol-da', example: '양파를 얇게 썰어요.', exampleTranslation: 'Slice the onion thinly.' },
    { korean: '섞다', english: 'To mix', pronunciation: 'seok-da', example: '잘 섞어서 드세요.', exampleTranslation: 'Mix well and eat.' },
    { korean: '데치다', english: 'To blanch', pronunciation: 'de-chi-da', example: '시금치를 데쳐 주세요.', exampleTranslation: 'Please blanch the spinach.' },
    { korean: '졸이다', english: 'To simmer / reduce', pronunciation: 'jor-i-da', example: '소스를 졸여 주세요.', exampleTranslation: 'Please simmer the sauce.' },
    { korean: '양념', english: 'Seasoning / Marinade', pronunciation: 'yang-nyeom', example: '양념이 잘 배었어요.', exampleTranslation: 'The seasoning is well absorbed.' },
    { korean: '양념치킨', english: 'Seasoned fried chicken', pronunciation: 'yang-nyeom-chi-kin', example: '양념치킨 반 후라이드 반이요.', exampleTranslation: 'Half seasoned and half fried chicken.' },
    { korean: '후라이드', english: 'Fried (chicken)', pronunciation: 'hu-ra-i-deu', example: '후라이드치킨이 바삭해요.', exampleTranslation: 'The fried chicken is crispy.' },
    { korean: '삼겹살', english: 'Pork belly', pronunciation: 'sam-gyeop-sal', example: '삼겹살 2인분 주세요.', exampleTranslation: 'Two servings of pork belly please.' },
    { korean: '불고기', english: 'Bulgogi (marinated beef)', pronunciation: 'bul-go-gi', example: '불고기 맛있게 만드는 법 알아?', exampleTranslation: 'Do you know how to make delicious bulgogi?' },
    { korean: '갈비', english: 'Ribs', pronunciation: 'gal-bi', example: '갈비가 부드럽고 맛있어요.', exampleTranslation: 'The ribs are tender and delicious.' },
    { korean: '비빔밥', english: 'Mixed rice bowl', pronunciation: 'bi-bim-bap', example: '전주 비빔밥이 유명해요.', exampleTranslation: 'Jeonju bibimbap is famous.' },
    { korean: '김치찌개', english: 'Kimchi stew', pronunciation: 'gim-chi-jji-gae', example: '김치찌개에 두부 넣어 줘.', exampleTranslation: 'Put tofu in the kimchi stew.' },
    { korean: '된장찌개', english: 'Soybean paste stew', pronunciation: 'doen-jang-jji-gae', example: '된장찌개 냄새가 좋아요.', exampleTranslation: 'The soybean paste stew smells good.' },
    { korean: '순두부찌개', english: 'Soft tofu stew', pronunciation: 'sun-du-bu-jji-gae', example: '순두부찌개 맵게 해 주세요.', exampleTranslation: 'Please make the soft tofu stew spicy.' },
    { korean: '라면', english: 'Instant noodles', pronunciation: 'ra-myeon', example: '라면에 달걀 넣을까?', exampleTranslation: 'Should I add an egg to the ramen?' },
    { korean: '떡볶이', english: 'Spicy rice cakes', pronunciation: 'tteok-bokk-i', example: '떡볶이 매운맛으로 주세요.', exampleTranslation: 'Spicy tteokbokki please.' },
    { korean: '김밥', english: 'Seaweed rice roll', pronunciation: 'gim-bap', example: '참치김밥 두 줄 주세요.', exampleTranslation: 'Two rolls of tuna kimbap please.' },
    { korean: '치킨', english: 'Fried chicken', pronunciation: 'chi-kin', example: '치킨 시켜 먹자.', exampleTranslation: 'Let\'s order fried chicken.' },
    { korean: '소주', english: 'Soju', pronunciation: 'so-ju', example: '소주 한 병 더요.', exampleTranslation: 'One more bottle of soju.' },
    { korean: '맥주', english: 'Beer', pronunciation: 'maek-ju', example: '생맥주 한 잔 주세요.', exampleTranslation: 'One draft beer please.' },
    { korean: '막걸리', english: 'Rice wine', pronunciation: 'mak-geol-li', example: '비 오는 날에는 막걸리지.', exampleTranslation: 'Makgeolli is perfect on rainy days.' },
    { korean: '반찬', english: 'Side dishes', pronunciation: 'ban-chan', example: '반찬이 다양해요.', exampleTranslation: 'The side dishes are varied.' },
    { korean: '밑반찬', english: 'Basic side dishes', pronunciation: 'mit-ban-chan', example: '밑반찬을 미리 만들어 놓자.', exampleTranslation: 'Let\'s prepare the basic side dishes in advance.' },
    { korean: '찌개', english: 'Stew', pronunciation: 'jji-gae', example: '찌개가 보글보글 끓어요.', exampleTranslation: 'The stew is bubbling.' },
    { korean: '전', english: 'Korean pancake', pronunciation: 'jeon', example: '비 오는 날에 전 부치자.', exampleTranslation: 'Let\'s make pancakes on a rainy day.' },
    { korean: '만두', english: 'Dumplings', pronunciation: 'man-du', example: '만두 직접 빚었어요.', exampleTranslation: 'I made dumplings by hand.' },
    { korean: '냉면', english: 'Cold noodles', pronunciation: 'naeng-myeon', example: '물냉면으로 주세요.', exampleTranslation: 'Water-based cold noodles please.' },
    { korean: '잡채', english: 'Glass noodle stir-fry', pronunciation: 'jap-chae', example: '잡채 만들어 볼까?', exampleTranslation: 'Shall we make japchae?' },
    { korean: '볶음밥', english: 'Fried rice', pronunciation: 'bokk-eum-bap', example: '김치볶음밥 해 줘.', exampleTranslation: 'Make me kimchi fried rice.' },
    { korean: '죽', english: 'Porridge', pronunciation: 'juk', example: '아플 때 죽 먹어.', exampleTranslation: 'Eat porridge when you\'re sick.' },
    { korean: '국수', english: 'Noodle soup', pronunciation: 'guk-su', example: '잔치국수 좋아해요.', exampleTranslation: 'I like banquet noodles.' },
    { korean: '회', english: 'Raw fish / Sashimi', pronunciation: 'hoe', example: '오늘 회 먹으러 갈까?', exampleTranslation: 'Shall we go eat raw fish today?' },
    { korean: '구이', english: 'Grilled dish', pronunciation: 'gu-i', example: '생선구이 주세요.', exampleTranslation: 'Grilled fish please.' },
    { korean: '찜', english: 'Steamed dish', pronunciation: 'jjim', example: '갈비찜 만들어 줘.', exampleTranslation: 'Make braised short ribs.' },
    { korean: '탕', english: 'Thick soup / Stew', pronunciation: 'tang', example: '삼계탕 먹으러 가자.', exampleTranslation: 'Let\'s go eat chicken ginseng soup.' },
    { korean: '신선하다', english: 'To be fresh', pronunciation: 'sin-seon-ha-da', example: '재료가 정말 신선해요.', exampleTranslation: 'The ingredients are really fresh.' },
    { korean: '바삭하다', english: 'To be crispy', pronunciation: 'ba-sak-ha-da', example: '튀김이 바삭해요.', exampleTranslation: 'The fried food is crispy.' },
    { korean: '부드럽다', english: 'To be soft / tender', pronunciation: 'bu-deu-reop-da', example: '고기가 부드러워요.', exampleTranslation: 'The meat is tender.' },
    { korean: '쫄깃하다', english: 'To be chewy', pronunciation: 'jjol-git-ha-da', example: '면이 쫄깃해요.', exampleTranslation: 'The noodles are chewy.' },
    { korean: '고소하다', english: 'To be nutty / savory', pronunciation: 'go-so-ha-da', example: '참기름이 고소해요.', exampleTranslation: 'The sesame oil is nutty.' },
    { korean: '시원하다', english: 'Refreshing (taste)', pronunciation: 'si-won-ha-da', example: '국물이 시원해요.', exampleTranslation: 'The broth is refreshing.' },
    { korean: '담백하다', english: 'Light / mild flavor', pronunciation: 'dam-baek-ha-da', example: '맛이 담백해서 좋아요.', exampleTranslation: 'I like it because the flavor is mild.' },
    { korean: '느끼하다', english: 'Greasy / heavy', pronunciation: 'neu-kki-ha-da', example: '좀 느끼해서 콜라 마셔야 해.', exampleTranslation: 'It\'s greasy so I need to drink cola.' },
    { korean: '감칠맛', english: 'Umami', pronunciation: 'gam-chil-mat', example: '감칠맛이 나요.', exampleTranslation: 'It has an umami flavor.' },
    { korean: '향', english: 'Aroma / Fragrance', pronunciation: 'hyang', example: '음식 향이 좋아요.', exampleTranslation: 'The food smells great.' },
    { korean: '식감', english: 'Texture (food)', pronunciation: 'sik-gam', example: '식감이 좋아요.', exampleTranslation: 'The texture is great.' },
    { korean: '한식', english: 'Korean food', pronunciation: 'han-sik', example: '한식 먹고 싶어요.', exampleTranslation: 'I want to eat Korean food.' },
    { korean: '양식', english: 'Western food', pronunciation: 'yang-sik', example: '오늘은 양식 먹자.', exampleTranslation: 'Let\'s eat Western food today.' },
    { korean: '중식', english: 'Chinese food', pronunciation: 'jung-sik', example: '중식당에 가자.', exampleTranslation: 'Let\'s go to a Chinese restaurant.' },
    { korean: '일식', english: 'Japanese food', pronunciation: 'il-sik', example: '일식집 예약했어.', exampleTranslation: 'I reserved a Japanese restaurant.' },
    { korean: '분식', english: 'Snack food / flour-based food', pronunciation: 'bun-sik', example: '분식집에서 떡볶이 먹자.', exampleTranslation: 'Let\'s eat tteokbokki at a snack bar.' },
    { korean: '야식', english: 'Late-night snack', pronunciation: 'ya-sik', example: '야식으로 뭐 먹을래?', exampleTranslation: 'What do you want for a late-night snack?' },
    { korean: '디저트', english: 'Dessert', pronunciation: 'di-jeo-teu', example: '디저트 먹을래요?', exampleTranslation: 'Do you want dessert?' },
    { korean: '카페', english: 'Cafe', pronunciation: 'ka-pe', example: '카페에서 만나자.', exampleTranslation: 'Let\'s meet at a cafe.' },
    { korean: '식사', english: 'Meal', pronunciation: 'sik-sa', example: '식사하셨어요?', exampleTranslation: 'Have you had your meal?' },
    { korean: '간', english: 'Seasoning level / Saltiness', pronunciation: 'gan', example: '간 좀 봐 주세요.', exampleTranslation: 'Please taste and check the seasoning.' },
    { korean: '불', english: 'Fire / Heat', pronunciation: 'bul', example: '불을 줄여 주세요.', exampleTranslation: 'Please reduce the heat.' },
    { korean: '냄새', english: 'Smell', pronunciation: 'naem-sae', example: '맛있는 냄새가 나요.', exampleTranslation: 'It smells delicious.' },
    { korean: '국물', english: 'Broth / Soup base', pronunciation: 'gung-mul', example: '국물이 진해요.', exampleTranslation: 'The broth is rich.' },
    { korean: '고명', english: 'Garnish', pronunciation: 'go-myeong', example: '고명을 올려 주세요.', exampleTranslation: 'Please add the garnish.' },
    { korean: '뚜껑', english: 'Lid', pronunciation: 'ttu-kkeong', example: '뚜껑을 덮고 끓이세요.', exampleTranslation: 'Cover with a lid and boil.' },
    { korean: '행주', english: 'Kitchen towel', pronunciation: 'haeng-ju', example: '행주로 닦아 주세요.', exampleTranslation: 'Please wipe with a kitchen towel.' },
    { korean: '앞치마', english: 'Apron', pronunciation: 'ap-chi-ma', example: '앞치마 하고 요리하자.', exampleTranslation: 'Let\'s wear an apron and cook.' },
    { korean: '뷔페', english: 'Buffet', pronunciation: 'bwi-pe', example: '뷔페에서 점심 먹자.', exampleTranslation: 'Let\'s eat lunch at the buffet.' },
    { korean: '포크', english: 'Fork', pronunciation: 'po-keu', example: '포크 주세요.', exampleTranslation: 'Fork please.' },
    { korean: '냅킨', english: 'Napkin', pronunciation: 'naep-kin', example: '냅킨 더 필요해요.', exampleTranslation: 'I need more napkins.' },
    { korean: '양', english: 'Amount / Quantity', pronunciation: 'yang', example: '양이 많아요.', exampleTranslation: 'The portion is large.' },
    { korean: '가격', english: 'Price', pronunciation: 'ga-gyeok', example: '가격이 착해요.', exampleTranslation: 'The price is reasonable.' },
    { korean: '서비스', english: 'Free extra / Service', pronunciation: 'seo-bi-seu', example: '이건 서비스예요.', exampleTranslation: 'This is on the house.' },
    { korean: '웨이터', english: 'Waiter', pronunciation: 'we-i-teo', example: '저기요! 여기 주문이요.', exampleTranslation: 'Excuse me! We\'d like to order.' },
    { korean: '주방', english: 'Kitchen', pronunciation: 'ju-bang', example: '주방이 깨끗해요.', exampleTranslation: 'The kitchen is clean.' },
    { korean: '테이블', english: 'Table', pronunciation: 'te-i-beul', example: '빈 테이블 있어요?', exampleTranslation: 'Is there an empty table?' },
    { korean: '메뉴판', english: 'Menu board', pronunciation: 'me-nyu-pan', example: '메뉴판 좀 볼게요.', exampleTranslation: 'Let me see the menu.' },
    { korean: '영수증', english: 'Receipt', pronunciation: 'yeong-su-jeung', example: '영수증 주세요.', exampleTranslation: 'Please give me the receipt.' },
    { korean: '팁', english: 'Tip', pronunciation: 'tip', example: '한국에서는 팁 안 줘도 돼요.', exampleTranslation: 'You don\'t need to tip in Korea.' },
    { korean: '젓다', english: 'To stir', pronunciation: 'jeot-da', example: '잘 저어 주세요.', exampleTranslation: 'Please stir well.' },
    { korean: '다지다', english: 'To mince / chop finely', pronunciation: 'da-ji-da', example: '마늘을 다져 주세요.', exampleTranslation: 'Please mince the garlic.' },
    { korean: '담다', english: 'To put in / serve', pronunciation: 'dam-da', example: '그릇에 담아 주세요.', exampleTranslation: 'Please serve it in a bowl.' },
    { korean: '채우다', english: 'To fill', pronunciation: 'chae-u-da', example: '물을 반쯤 채우세요.', exampleTranslation: 'Fill it about half with water.' },
    { korean: '버리다', english: 'To throw away', pronunciation: 'beo-ri-da', example: '남은 음식 버려야 해요.', exampleTranslation: 'We need to throw away the leftover food.' },
    { korean: '익히다', english: 'To cook / ripen', pronunciation: 'ik-hi-da', example: '고기를 잘 익혀 주세요.', exampleTranslation: 'Please cook the meat thoroughly.' },
    { korean: '쟁반', english: 'Tray', pronunciation: 'jaeng-ban', example: '쟁반에 음식을 올려 주세요.', exampleTranslation: 'Please put the food on the tray.' },
  ],
  3: [
    { korean: '삼계탕', english: 'Chicken ginseng soup', pronunciation: 'sam-gye-tang', example: '여름 보양식으로 삼계탕을 먹어요.', exampleTranslation: 'We eat samgyetang as a summer stamina food.' },
    { korean: '곱창', english: 'Grilled intestines', pronunciation: 'gop-chang', example: '곱창에 소주 한 잔 어때요?', exampleTranslation: 'How about a glass of soju with grilled intestines?' },
    { korean: '족발', english: 'Braised pig feet', pronunciation: 'jok-bal', example: '족발 중자 하나 주세요.', exampleTranslation: 'One medium jokbal please.' },
    { korean: '보쌈', english: 'Wrapped pork belly', pronunciation: 'bo-ssam', example: '보쌈에 막국수 같이 먹으면 맛있어요.', exampleTranslation: 'Bossam tastes great with buckwheat noodles.' },
    { korean: '순대', english: 'Blood sausage', pronunciation: 'sun-dae', example: '시장 순대가 맛있어요.', exampleTranslation: 'Market sundae is delicious.' },
    { korean: '해장국', english: 'Hangover soup', pronunciation: 'hae-jang-guk', example: '술 마신 다음 날 해장국 먹자.', exampleTranslation: 'Let\'s eat hangover soup the day after drinking.' },
    { korean: '부대찌개', english: 'Army stew', pronunciation: 'bu-dae-jji-gae', example: '부대찌개에 라면 사리 추가해요.', exampleTranslation: 'Add ramen noodles to the army stew.' },
    { korean: '감자탕', english: 'Pork bone potato stew', pronunciation: 'gam-ja-tang', example: '감자탕은 뼈를 우려내서 만들어요.', exampleTranslation: 'Gamjatang is made by boiling pork bones.' },
    { korean: '칼국수', english: 'Knife-cut noodle soup', pronunciation: 'kal-guk-su', example: '손칼국수 맛집 알아?', exampleTranslation: 'Do you know a good kalguksu place?' },
    { korean: '수제비', english: 'Hand-pulled dough soup', pronunciation: 'su-je-bi', example: '수제비 반죽을 얇게 뜯어요.', exampleTranslation: 'Tear the sujebi dough thinly.' },
    { korean: '김치전', english: 'Kimchi pancake', pronunciation: 'gim-chi-jeon', example: '묵은지로 김치전 부쳐요.', exampleTranslation: 'Make kimchi pancake with aged kimchi.' },
    { korean: '해물파전', english: 'Seafood green onion pancake', pronunciation: 'hae-mul-pa-jeon', example: '비 오는 날 해물파전에 막걸리!', exampleTranslation: 'Seafood pancake with makgeolli on rainy days!' },
    { korean: '떡국', english: 'Rice cake soup', pronunciation: 'tteok-guk', example: '설날에 떡국을 먹어야 한 살 더 먹어요.', exampleTranslation: 'You need to eat tteokguk on New Year\'s to age one more year.' },
    { korean: '갈비탕', english: 'Short rib soup', pronunciation: 'gal-bi-tang', example: '갈비탕 국물이 진해요.', exampleTranslation: 'The galbitang broth is rich.' },
    { korean: '설렁탕', english: 'Ox bone soup', pronunciation: 'seol-leong-tang', example: '설렁탕에 소금 넣어서 간 맞춰 드세요.', exampleTranslation: 'Add salt to your seolleongtang to adjust the taste.' },
    { korean: '곰탕', english: 'Beef bone soup', pronunciation: 'gom-tang', example: '곰탕을 오래 끓여야 맛있어요.', exampleTranslation: 'Gomtang needs to be boiled for a long time to be delicious.' },
    { korean: '육개장', english: 'Spicy beef soup', pronunciation: 'yuk-gae-jang', example: '육개장이 얼큰해요.', exampleTranslation: 'The yukgaejang is spicy and warming.' },
    { korean: '닭갈비', english: 'Spicy stir-fried chicken', pronunciation: 'dak-gal-bi', example: '춘천 닭갈비가 유명해요.', exampleTranslation: 'Chuncheon dak-galbi is famous.' },
    { korean: '제육볶음', english: 'Spicy stir-fried pork', pronunciation: 'je-yuk-bokk-eum', example: '제육볶음 백반 하나요.', exampleTranslation: 'One set meal with spicy pork stir-fry please.' },
    { korean: '돈까스', english: 'Pork cutlet', pronunciation: 'don-kka-seu', example: '돈까스 소스 더 주세요.', exampleTranslation: 'More pork cutlet sauce please.' },
    { korean: '짜장면', english: 'Black bean noodles', pronunciation: 'jja-jang-myeon', example: '짜장면이랑 탕수육 시키자.', exampleTranslation: 'Let\'s order jajangmyeon and sweet and sour pork.' },
    { korean: '짬뽕', english: 'Spicy seafood noodle soup', pronunciation: 'jjam-ppong', example: '짬뽕 좋아해요? 짜장면 좋아해요?', exampleTranslation: 'Do you like jjamppong or jajangmyeon?' },
    { korean: '탕수육', english: 'Sweet and sour pork', pronunciation: 'tang-su-yuk', example: '탕수육은 찍먹? 부먹?', exampleTranslation: 'Sweet and sour pork: dip or pour?' },
    { korean: '고등어', english: 'Mackerel', pronunciation: 'go-deung-eo', example: '고등어구이가 맛있어요.', exampleTranslation: 'Grilled mackerel is delicious.' },
    { korean: '쌈', english: 'Wrap (lettuce wrap)', pronunciation: 'ssam', example: '쌈에 고기 올려서 먹어요.', exampleTranslation: 'Put meat on the wrap and eat.' },
    { korean: '쌈장', english: 'Wrap sauce', pronunciation: 'ssam-jang', example: '쌈장 맛있게 만들어 봐.', exampleTranslation: 'Try making delicious ssamjang.' },
    { korean: '젓갈', english: 'Salted fermented seafood', pronunciation: 'jeot-gal', example: '새우젓갈이 김치에 들어가요.', exampleTranslation: 'Salted shrimp goes into kimchi.' },
    { korean: '나물', english: 'Seasoned vegetables', pronunciation: 'na-mul', example: '나물 반찬을 만들었어요.', exampleTranslation: 'I made seasoned vegetable side dishes.' },
    { korean: '무침', english: 'Seasoned / mixed side dish', pronunciation: 'mu-chim', example: '오이무침 해 줄까?', exampleTranslation: 'Shall I make seasoned cucumber?' },
    { korean: '절이다', english: 'To pickle / salt', pronunciation: 'jeor-i-da', example: '배추를 소금에 절여요.', exampleTranslation: 'Salt the napa cabbage.' },
    { korean: '무치다', english: 'To season / dress', pronunciation: 'mu-chi-da', example: '콩나물을 무쳐요.', exampleTranslation: 'Season the bean sprouts.' },
    { korean: '조리다', english: 'To braise / cook down', pronunciation: 'jo-ri-da', example: '간장에 조려서 만들어요.', exampleTranslation: 'It\'s made by braising in soy sauce.' },
    { korean: '볶음', english: 'Stir-fry dish', pronunciation: 'bokk-eum', example: '멸치볶음 만들었어요.', exampleTranslation: 'I made stir-fried anchovies.' },
    { korean: '조림', english: 'Braised dish', pronunciation: 'jo-rim', example: '감자조림 맛있어요.', exampleTranslation: 'Braised potatoes are delicious.' },
    { korean: '무생채', english: 'Seasoned raw radish', pronunciation: 'mu-saeng-chae', example: '무생채가 새콤해요.', exampleTranslation: 'The seasoned raw radish is tangy.' },
    { korean: '젓가락질', english: 'Using chopsticks', pronunciation: 'jeot-ga-rak-jil', example: '젓가락질 잘 하시네요!', exampleTranslation: 'You\'re good with chopsticks!' },
    { korean: '숟가락질', english: 'Using a spoon', pronunciation: 'sut-ga-rak-jil', example: '밥은 숟가락으로 먹어요.', exampleTranslation: 'Eat rice with a spoon.' },
    { korean: '회식', english: 'Company dinner', pronunciation: 'hoe-sik', example: '오늘 회식 장소가 어디예요?', exampleTranslation: 'Where is the company dinner today?' },
    { korean: '건배', english: 'Cheers / Toast', pronunciation: 'geon-bae', example: '건배! 우리의 성공을 위하여!', exampleTranslation: 'Cheers! To our success!' },
    { korean: '원샷', english: 'Bottoms up', pronunciation: 'won-syat', example: '원샷! 다 마셔!', exampleTranslation: 'Bottoms up! Drink it all!' },
    { korean: '안주', english: 'Drinking snack', pronunciation: 'an-ju', example: '소주 안주로 뭐 먹을래?', exampleTranslation: 'What snack do you want with soju?' },
    { korean: '이차', english: 'Second round (drinking)', pronunciation: 'i-cha', example: '이차 갈까요?', exampleTranslation: 'Shall we go for a second round?' },
    { korean: '포차', english: 'Street bar / tent bar', pronunciation: 'po-cha', example: '포차에서 한잔하자.', exampleTranslation: 'Let\'s have a drink at a street bar.' },
    { korean: '구내식당', english: 'Cafeteria', pronunciation: 'gu-nae-sik-dang', example: '구내식당 메뉴가 뭐야?', exampleTranslation: 'What\'s on the cafeteria menu?' },
    { korean: '백반', english: 'Set meal with rice', pronunciation: 'baek-ban', example: '백반집에서 점심 먹자.', exampleTranslation: 'Let\'s eat lunch at a set meal place.' },
    { korean: '한정식', english: 'Korean full-course meal', pronunciation: 'han-jeong-sik', example: '한정식 코스로 예약했어요.', exampleTranslation: 'I reserved a Korean full-course meal.' },
    { korean: '상차림', english: 'Table setting', pronunciation: 'sang-cha-rim', example: '상차림이 정갈해요.', exampleTranslation: 'The table setting is neat.' },
    { korean: '수저', english: 'Spoon and chopsticks set', pronunciation: 'su-jeo', example: '수저 놓아 주세요.', exampleTranslation: 'Please set out the spoon and chopsticks.' },
    { korean: '식탁', english: 'Dining table', pronunciation: 'sik-tak', example: '식탁에 앉아서 먹자.', exampleTranslation: 'Let\'s sit at the dining table and eat.' },
    { korean: '물수건', english: 'Wet towel', pronunciation: 'mul-su-geon', example: '물수건으로 손 닦으세요.', exampleTranslation: 'Wipe your hands with a wet towel.' },
    { korean: '곁들이다', english: 'To serve alongside', pronunciation: 'gyeot-deur-i-da', example: '샐러드를 곁들여 드세요.', exampleTranslation: 'Serve with salad.' },
    { korean: '비법', english: 'Secret recipe', pronunciation: 'bi-beop', example: '할머니의 비법 레시피예요.', exampleTranslation: 'It\'s grandmother\'s secret recipe.' },
    { korean: '손맛', english: 'Hand taste / cooking touch', pronunciation: 'son-mat', example: '엄마 손맛이 최고야.', exampleTranslation: 'Mom\'s cooking touch is the best.' },
    { korean: '밥상', english: 'Dining table (traditional)', pronunciation: 'bap-sang', example: '밥상을 차렸어요.', exampleTranslation: 'I set the table for a meal.' },
    { korean: '한상', english: 'Full table of dishes', pronunciation: 'han-sang', example: '한상 가득 차려 놓았네!', exampleTranslation: 'You\'ve prepared a full spread!' },
    { korean: '곱빼기', english: 'Extra-large portion', pronunciation: 'gop-ppae-gi', example: '곱빼기로 주세요.', exampleTranslation: 'Extra-large portion please.' },
    { korean: '사리', english: 'Extra noodle/rice cake', pronunciation: 'sa-ri', example: '라면 사리 추가요.', exampleTranslation: 'Add extra noodles please.' },
    { korean: '공기밥', english: 'Bowl of steamed rice', pronunciation: 'gong-gi-bap', example: '공기밥 하나 더 주세요.', exampleTranslation: 'One more bowl of rice please.' },
    { korean: '누룽지', english: 'Scorched rice', pronunciation: 'nu-rung-ji', example: '누룽지에 물 부어서 먹어요.', exampleTranslation: 'Pour water over scorched rice and eat.' },
    { korean: '소스', english: 'Sauce', pronunciation: 'so-seu', example: '소스를 뿌려 주세요.', exampleTranslation: 'Please drizzle the sauce.' },
    { korean: '절임', english: 'Pickled food', pronunciation: 'jeor-im', example: '마늘 절임 만들어 봤어.', exampleTranslation: 'I tried making pickled garlic.' },
    { korean: '장아찌', english: 'Pickled vegetables', pronunciation: 'jang-a-jji', example: '간장 장아찌 맛있어요.', exampleTranslation: 'Soy sauce pickled vegetables are delicious.' },
    { korean: '볶음면', english: 'Stir-fried noodles', pronunciation: 'bokk-eum-myeon', example: '해물볶음면 먹어 볼래?', exampleTranslation: 'Do you want to try seafood stir-fried noodles?' },
    { korean: '양꼬치', english: 'Lamb skewer', pronunciation: 'yang-kko-chi', example: '양꼬치에 칭따오 맥주!', exampleTranslation: 'Lamb skewers with Tsingtao beer!' },
    { korean: '편의점 도시락', english: 'Convenience store lunch box', pronunciation: 'pyeon-ui-jeom-do-si-rak', example: '편의점 도시락이 맛있어졌어요.', exampleTranslation: 'Convenience store lunch boxes have gotten better.' },
    { korean: '배달 앱', english: 'Delivery app', pronunciation: 'bae-dal aep', example: '배달 앱으로 시켜 먹자.', exampleTranslation: 'Let\'s order through a delivery app.' },
    { korean: '먹방', english: 'Eating broadcast', pronunciation: 'meok-bang', example: '유튜브에서 먹방 봤어요.', exampleTranslation: 'I watched a mukbang on YouTube.' },
    { korean: '쿡방', english: 'Cooking broadcast', pronunciation: 'kuk-bang', example: '쿡방 보고 따라 만들었어요.', exampleTranslation: 'I followed a cooking show and made it.' },
    { korean: '푸드 트럭', english: 'Food truck', pronunciation: 'pu-deu teu-reok', example: '푸드 트럭에서 타코 먹자.', exampleTranslation: 'Let\'s eat tacos at the food truck.' },
    { korean: '포장마차', english: 'Street food stall', pronunciation: 'po-jang-ma-cha', example: '포장마차에서 떡볶이 먹었어요.', exampleTranslation: 'I ate tteokbokki at a street food stall.' },
    { korean: '길거리 음식', english: 'Street food', pronunciation: 'gil-geo-ri eum-sik', example: '한국 길거리 음식이 유명해요.', exampleTranslation: 'Korean street food is famous.' },
    { korean: '호떡', english: 'Sweet stuffed pancake', pronunciation: 'ho-tteok', example: '겨울에 호떡이 최고야.', exampleTranslation: 'Hotteok is the best in winter.' },
    { korean: '붕어빵', english: 'Fish-shaped pastry', pronunciation: 'bung-eo-ppang', example: '붕어빵 팥 앙금이 맛있어요.', exampleTranslation: 'Bungeoppang with red bean filling is delicious.' },
    { korean: '어묵', english: 'Fish cake', pronunciation: 'eo-muk', example: '어묵 국물이 시원해요.', exampleTranslation: 'Fish cake broth is refreshing.' },
    { korean: '튀김', english: 'Deep-fried food', pronunciation: 'twi-gim', example: '모듬 튀김 주세요.', exampleTranslation: 'Assorted fried food please.' },
    { korean: '오뎅', english: 'Fish cake (Japanese style)', pronunciation: 'o-deng', example: '오뎅 국물 한 잔 주세요.', exampleTranslation: 'One cup of fish cake broth please.' },
    { korean: '토스트', english: 'Korean egg toast', pronunciation: 'to-seu-teu', example: '길거리 토스트 먹어 봤어?', exampleTranslation: 'Have you tried Korean street toast?' },
    { korean: '닭꼬치', english: 'Chicken skewer', pronunciation: 'dak-kko-chi', example: '닭꼬치 양념맛으로 주세요.', exampleTranslation: 'Seasoned chicken skewer please.' },
    { korean: '핫도그', english: 'Korean corn dog', pronunciation: 'hat-do-geu', example: '한국식 핫도그 먹어 봤어?', exampleTranslation: 'Have you tried Korean corn dogs?' },
    { korean: '소떡소떡', english: 'Sausage and rice cake skewer', pronunciation: 'so-tteok-so-tteok', example: '소떡소떡에 소스 뿌려 주세요.', exampleTranslation: 'Please drizzle sauce on the sotteok sotteok.' },
    { korean: '계란빵', english: 'Egg bread', pronunciation: 'gye-ran-ppang', example: '겨울에 계란빵이 인기 많아요.', exampleTranslation: 'Egg bread is popular in winter.' },
    { korean: '호두과자', english: 'Walnut pastry', pronunciation: 'ho-du-gwa-ja', example: '천안 호두과자가 유명해요.', exampleTranslation: 'Cheonan walnut pastries are famous.' },
    { korean: '군밤', english: 'Roasted chestnuts', pronunciation: 'gun-bam', example: '겨울에 군밤 먹으면 따뜻해요.', exampleTranslation: 'Eating roasted chestnuts warms you up in winter.' },
    { korean: '약과', english: 'Honey pastry', pronunciation: 'yak-gwa', example: '요즘 약과가 유행이에요.', exampleTranslation: 'Yakgwa is trendy these days.' },
    { korean: '떡꼬치', english: 'Rice cake skewer', pronunciation: 'tteok-kko-chi', example: '떡꼬치에 양념 발라 주세요.', exampleTranslation: 'Please put sauce on the rice cake skewer.' },
    { korean: '인절미', english: 'Soybean powder rice cake', pronunciation: 'in-jeol-mi', example: '인절미 콩가루가 고소해요.', exampleTranslation: 'The soybean powder on injeolmi is nutty.' },
    { korean: '수정과', english: 'Cinnamon persimmon punch', pronunciation: 'su-jeong-gwa', example: '식혜랑 수정과 중에 뭐 마실래?', exampleTranslation: 'Do you want sikhye or sujeonggwa?' },
    { korean: '식혜', english: 'Sweet rice punch', pronunciation: 'sik-hye', example: '식당에서 식혜를 후식으로 줬어요.', exampleTranslation: 'The restaurant gave us sikhye as dessert.' },
    { korean: '팥빙수', english: 'Shaved ice with red beans', pronunciation: 'pat-bing-su', example: '여름에 팥빙수 먹으러 가자.', exampleTranslation: 'Let\'s go eat patbingsu in summer.' },
    { korean: '붕어빵 틀', english: 'Fish-shaped bread mold', pronunciation: 'bung-eo-ppang teul', example: '붕어빵 틀에 반죽을 부어요.', exampleTranslation: 'Pour batter into the fish-shaped mold.' },
    { korean: '모듬', english: 'Assorted / Mixed platter', pronunciation: 'mo-deum', example: '모듬 회 주세요.', exampleTranslation: 'Assorted sashimi platter please.' },
    { korean: '가마솥', english: 'Iron cauldron', pronunciation: 'ga-ma-sot', example: '가마솥에 밥을 지었어요.', exampleTranslation: 'I cooked rice in an iron cauldron.' },
    { korean: '솥밥', english: 'Stone pot rice', pronunciation: 'sot-bap', example: '솥밥이 고슬고슬해요.', exampleTranslation: 'The stone pot rice is perfectly cooked.' },
    { korean: '비빔', english: 'Mixed / Mixing', pronunciation: 'bi-bim', example: '잘 비벼서 먹어요.', exampleTranslation: 'Mix well and eat.' },
    { korean: '숙성', english: 'Aging / Maturing', pronunciation: 'suk-seong', example: '고기를 숙성시키면 더 맛있어요.', exampleTranslation: 'Aged meat tastes better.' },
    { korean: '불맛', english: 'Wok hei / fire-kissed flavor', pronunciation: 'bul-mat', example: '볶음밥에 불맛이 나요.', exampleTranslation: 'The fried rice has that wok-hei flavor.' },
    { korean: '도시락', english: 'Lunch box', pronunciation: 'do-si-rak', example: '도시락 싸서 소풍 가자.', exampleTranslation: 'Let\'s pack a lunch box and go on a picnic.' },
    { korean: '꼬치', english: 'Skewer', pronunciation: 'kko-chi', example: '꼬치 구워 먹자.', exampleTranslation: 'Let\'s grill skewers.' },
    { korean: '국자', english: 'Ladle', pronunciation: 'guk-ja', example: '국자로 국을 떠 주세요.', exampleTranslation: 'Please ladle the soup.' },
    { korean: '체', english: 'Sieve / Strainer', pronunciation: 'che', example: '체에 밀가루를 걸러요.', exampleTranslation: 'Sift the flour through a sieve.' },
  ],
  4: [
    { korean: '전주 비빔밥', english: 'Jeonju bibimbap', pronunciation: 'jeon-ju bi-bim-bap', example: '전주에 가면 꼭 비빔밥을 먹어야 해요.', exampleTranslation: 'If you go to Jeonju, you must eat bibimbap.' },
    { korean: '춘천 닭갈비', english: 'Chuncheon dakgalbi', pronunciation: 'chun-cheon dak-gal-bi', example: '춘천 닭갈비 골목에 가 봤어요?', exampleTranslation: 'Have you been to Chuncheon dakgalbi alley?' },
    { korean: '부산 밀면', english: 'Busan wheat noodles', pronunciation: 'bu-san mil-myeon', example: '부산 밀면은 냉면보다 쫄깃해요.', exampleTranslation: 'Busan milmyeon is chewier than naengmyeon.' },
    { korean: '통영 충무김밥', english: 'Tongyeong chungmu kimbap', pronunciation: 'tong-yeong chung-mu-gim-bap', example: '통영에서 충무김밥 먹어 봤어요.', exampleTranslation: 'I tried chungmu kimbap in Tongyeong.' },
    { korean: '제주 흑돼지', english: 'Jeju black pork', pronunciation: 'je-ju heuk-dwae-ji', example: '제주도 흑돼지는 꼭 먹어 봐야 해요.', exampleTranslation: 'You must try Jeju black pork.' },
    { korean: '안동 찜닭', english: 'Andong braised chicken', pronunciation: 'an-dong jjim-dak', example: '안동 찜닭은 간장 양념이 특징이에요.', exampleTranslation: 'Andong jjimdak is characterized by soy sauce seasoning.' },
    { korean: '대구 막창', english: 'Daegu grilled intestines', pronunciation: 'dae-gu mak-chang', example: '대구에서 막창 맛집 찾았어요.', exampleTranslation: 'I found a good makchang place in Daegu.' },
    { korean: '군산 짬뽕', english: 'Gunsan jjamppong', pronunciation: 'gun-san jjam-ppong', example: '군산 짬뽕은 해물이 듬뿍 들어가요.', exampleTranslation: 'Gunsan jjamppong is loaded with seafood.' },
    { korean: '속초 닭강정', english: 'Sokcho sweet fried chicken', pronunciation: 'sok-cho dak-gang-jeong', example: '속초 닭강정은 관광객에게 인기예요.', exampleTranslation: 'Sokcho dakgangjung is popular with tourists.' },
    { korean: '광주 상무지구 맛집', english: 'Gwangju Sangmu food district', pronunciation: 'gwang-ju sang-mu-ji-gu mat-jip', example: '광주는 음식이 맛있기로 유명해요.', exampleTranslation: 'Gwangju is famous for delicious food.' },
    { korean: '영양소', english: 'Nutrient', pronunciation: 'yeong-yang-so', example: '이 음식에는 영양소가 풍부해요.', exampleTranslation: 'This food is rich in nutrients.' },
    { korean: '단백질', english: 'Protein', pronunciation: 'dan-baek-jil', example: '단백질을 충분히 섭취하세요.', exampleTranslation: 'Make sure to get enough protein.' },
    { korean: '탄수화물', english: 'Carbohydrate', pronunciation: 'tan-su-hwa-mul', example: '탄수화물을 줄이고 있어요.', exampleTranslation: 'I\'m reducing carbohydrates.' },
    { korean: '지방', english: 'Fat', pronunciation: 'ji-bang', example: '지방 함량이 낮아요.', exampleTranslation: 'The fat content is low.' },
    { korean: '비타민', english: 'Vitamin', pronunciation: 'bi-ta-min', example: '과일에 비타민이 많아요.', exampleTranslation: 'Fruits are rich in vitamins.' },
    { korean: '칼로리', english: 'Calorie', pronunciation: 'kal-lo-ri', example: '이 음식은 칼로리가 높아요.', exampleTranslation: 'This food is high in calories.' },
    { korean: '식이섬유', english: 'Dietary fiber', pronunciation: 'sig-i-seom-yu', example: '식이섬유가 풍부한 음식을 먹어요.', exampleTranslation: 'Eat foods rich in dietary fiber.' },
    { korean: '무기질', english: 'Mineral', pronunciation: 'mu-gi-jil', example: '해조류에 무기질이 많아요.', exampleTranslation: 'Seaweed is rich in minerals.' },
    { korean: '발효', english: 'Fermentation', pronunciation: 'bal-hyo', example: '김치는 발효 식품이에요.', exampleTranslation: 'Kimchi is a fermented food.' },
    { korean: '발효 식품', english: 'Fermented food', pronunciation: 'bal-hyo sik-pum', example: '한국은 발효 식품이 발달했어요.', exampleTranslation: 'Korea has well-developed fermented foods.' },
    { korean: '유산균', english: 'Lactic acid bacteria', pronunciation: 'yu-san-gyun', example: '김치에 유산균이 풍부해요.', exampleTranslation: 'Kimchi is rich in lactic acid bacteria.' },
    { korean: '미생물', english: 'Microorganism', pronunciation: 'mi-saeng-mul', example: '발효에는 미생물이 중요해요.', exampleTranslation: 'Microorganisms are important in fermentation.' },
    { korean: '식품 첨가물', english: 'Food additive', pronunciation: 'sik-pum cheom-ga-mul', example: '식품 첨가물 없이 만들었어요.', exampleTranslation: 'It was made without food additives.' },
    { korean: '유기농', english: 'Organic', pronunciation: 'yu-gi-nong', example: '유기농 채소를 사용해요.', exampleTranslation: 'We use organic vegetables.' },
    { korean: '무농약', english: 'Pesticide-free', pronunciation: 'mu-nong-yak', example: '무농약 쌀로 밥을 지어요.', exampleTranslation: 'We cook rice with pesticide-free rice.' },
    { korean: '방부제', english: 'Preservative', pronunciation: 'bang-bu-je', example: '방부제가 들어 있지 않아요.', exampleTranslation: 'It contains no preservatives.' },
    { korean: '음식 평론가', english: 'Food critic', pronunciation: 'eum-sik pyeong-non-ga', example: '유명한 음식 평론가가 추천했어요.', exampleTranslation: 'A famous food critic recommended it.' },
    { korean: '맛 평가', english: 'Taste evaluation', pronunciation: 'mat pyeong-ga', example: '맛 평가를 해 보겠습니다.', exampleTranslation: 'I will do a taste evaluation.' },
    { korean: '질감', english: 'Mouthfeel / Texture quality', pronunciation: 'jil-gam', example: '질감이 아주 좋아요.', exampleTranslation: 'The texture quality is very good.' },
    { korean: '풍미', english: 'Flavor profile', pronunciation: 'pung-mi', example: '풍미가 깊어요.', exampleTranslation: 'The flavor profile is deep.' },
    { korean: '감미롭다', english: 'Sweet and pleasant', pronunciation: 'gam-mi-rop-da', example: '와인이 감미로워요.', exampleTranslation: 'The wine is sweet and pleasant.' },
    { korean: '깔끔하다', english: 'Clean taste', pronunciation: 'kkal-kkeum-ha-da', example: '맛이 깔끔해요.', exampleTranslation: 'The taste is clean.' },
    { korean: '구수하다', english: 'Savory / toasty flavor', pronunciation: 'gu-su-ha-da', example: '된장찌개가 구수해요.', exampleTranslation: 'The doenjang jjigae has a savory flavor.' },
    { korean: '칼칼하다', english: 'Sharp spicy taste', pronunciation: 'kal-kal-ha-da', example: '칼칼한 국물이 시원해요.', exampleTranslation: 'The sharp spicy broth is refreshing.' },
    { korean: '얼큰하다', english: 'Hot and spicy (broth)', pronunciation: 'eol-keun-ha-da', example: '얼큰한 짬뽕이 먹고 싶어요.', exampleTranslation: 'I want to eat a hot and spicy jjamppong.' },
    { korean: '새콤달콤하다', english: 'Sweet and sour', pronunciation: 'sae-kom-dal-kom-ha-da', example: '새콤달콤한 소스가 맛있어요.', exampleTranslation: 'The sweet and sour sauce is delicious.' },
    { korean: '진하다', english: 'Rich / Thick (flavor)', pronunciation: 'jin-ha-da', example: '국물이 진해서 맛있어요.', exampleTranslation: 'The broth is rich and delicious.' },
    { korean: '슬로우 푸드', english: 'Slow food', pronunciation: 'seul-lo-u pu-deu', example: '슬로우 푸드 운동에 관심 있어요.', exampleTranslation: 'I\'m interested in the slow food movement.' },
    { korean: '패스트 푸드', english: 'Fast food', pronunciation: 'pae-seu-teu pu-deu', example: '패스트 푸드를 줄이고 있어요.', exampleTranslation: 'I\'m reducing fast food.' },
    { korean: '비건', english: 'Vegan', pronunciation: 'bi-geon', example: '비건 식당이 늘고 있어요.', exampleTranslation: 'Vegan restaurants are increasing.' },
    { korean: '채식주의자', english: 'Vegetarian', pronunciation: 'chae-sik-ju-ui-ja', example: '채식주의자를 위한 메뉴 있어요?', exampleTranslation: 'Do you have a menu for vegetarians?' },
    { korean: '글루텐 프리', english: 'Gluten-free', pronunciation: 'geul-lu-ten peu-ri', example: '글루텐 프리 메뉴 있어요?', exampleTranslation: 'Do you have a gluten-free menu?' },
    { korean: '알레르기', english: 'Allergy', pronunciation: 'al-le-reu-gi', example: '땅콩 알레르기가 있어요.', exampleTranslation: 'I have a peanut allergy.' },
    { korean: '식중독', english: 'Food poisoning', pronunciation: 'sik-jung-dok', example: '여름에 식중독 조심하세요.', exampleTranslation: 'Be careful of food poisoning in summer.' },
    { korean: '유통기한', english: 'Expiration date', pronunciation: 'yu-tong-gi-han', example: '유통기한을 확인하세요.', exampleTranslation: 'Check the expiration date.' },
    { korean: '원산지', english: 'Place of origin', pronunciation: 'won-san-ji', example: '원산지가 어디예요?', exampleTranslation: 'Where is the place of origin?' },
    { korean: '식재료', english: 'Food ingredients', pronunciation: 'sik-jae-ryo', example: '신선한 식재료를 사용해요.', exampleTranslation: 'We use fresh food ingredients.' },
    { korean: '제철 재료', english: 'Seasonal ingredients', pronunciation: 'je-cheol jae-ryo', example: '제철 재료로 요리하면 맛있어요.', exampleTranslation: 'Cooking with seasonal ingredients is delicious.' },
    { korean: '보양식', english: 'Stamina food', pronunciation: 'bo-yang-sik', example: '여름 보양식으로 삼계탕이 좋아요.', exampleTranslation: 'Samgyetang is great as summer stamina food.' },
    { korean: '궁중 요리', english: 'Royal court cuisine', pronunciation: 'gung-jung yo-ri', example: '궁중 요리를 재현한 식당이에요.', exampleTranslation: 'It\'s a restaurant that recreates royal court cuisine.' },
    { korean: '가정식', english: 'Home-style cooking', pronunciation: 'ga-jeong-sik', example: '가정식 백반이 먹고 싶어요.', exampleTranslation: 'I want home-style cooking.' },
    { korean: '웰빙', english: 'Well-being (food)', pronunciation: 'wel-bing', example: '웰빙 식단을 추구해요.', exampleTranslation: 'I pursue a well-being diet.' },
    { korean: '건강식', english: 'Health food', pronunciation: 'geon-gang-sik', example: '건강식으로 먹어야 해요.', exampleTranslation: 'We need to eat healthy food.' },
    { korean: '다이어트 식단', english: 'Diet meal plan', pronunciation: 'da-i-eo-teu sik-dan', example: '다이어트 식단을 짜고 있어요.', exampleTranslation: 'I\'m planning a diet meal plan.' },
    { korean: '균형 잡힌 식단', english: 'Balanced diet', pronunciation: 'gyun-hyeong jap-hin sik-dan', example: '균형 잡힌 식단이 중요해요.', exampleTranslation: 'A balanced diet is important.' },
    { korean: '간헐적 단식', english: 'Intermittent fasting', pronunciation: 'gan-hyeol-jeok dan-sik', example: '간헐적 단식을 하고 있어요.', exampleTranslation: 'I\'m doing intermittent fasting.' },
    { korean: '매운맛', english: 'Spicy level', pronunciation: 'mae-un-mat', example: '매운맛 단계를 골라 주세요.', exampleTranslation: 'Please choose the spicy level.' },
    { korean: '단맛', english: 'Sweetness', pronunciation: 'dan-mat', example: '단맛이 적당해요.', exampleTranslation: 'The sweetness is just right.' },
    { korean: '짠맛', english: 'Saltiness', pronunciation: 'jjan-mat', example: '짠맛이 강해요.', exampleTranslation: 'The saltiness is strong.' },
    { korean: '신맛', english: 'Sourness', pronunciation: 'sin-mat', example: '신맛이 나요.', exampleTranslation: 'It has a sour taste.' },
    { korean: '쓴맛', english: 'Bitterness', pronunciation: 'sseun-mat', example: '약간의 쓴맛이 있어요.', exampleTranslation: 'It has a slight bitterness.' },
    { korean: '향신료', english: 'Spice', pronunciation: 'hyang-sin-ryo', example: '향신료를 넣으면 맛이 달라져요.', exampleTranslation: 'Adding spices changes the flavor.' },
    { korean: '허브', english: 'Herb', pronunciation: 'heo-beu', example: '허브를 넣어서 향을 냈어요.', exampleTranslation: 'I added herbs for fragrance.' },
    { korean: '숙성 고기', english: 'Aged meat', pronunciation: 'suk-seong go-gi', example: '숙성 고기 전문점에 가 봤어요.', exampleTranslation: 'I visited an aged meat specialty restaurant.' },
    { korean: '건조', english: 'Drying (food preservation)', pronunciation: 'geon-jo', example: '건조 방법으로 보존해요.', exampleTranslation: 'It\'s preserved by drying.' },
    { korean: '훈제', english: 'Smoking (food)', pronunciation: 'hun-je', example: '훈제 오리가 맛있어요.', exampleTranslation: 'Smoked duck is delicious.' },
    { korean: '염장', english: 'Salt preservation', pronunciation: 'yeom-jang', example: '염장 기법으로 생선을 보관해요.', exampleTranslation: 'We preserve fish with the salt preservation technique.' },
    { korean: '담그다', english: 'To ferment / brew', pronunciation: 'dam-geu-da', example: '직접 김치를 담가요.', exampleTranslation: 'I make kimchi myself.' },
    { korean: '삭히다', english: 'To ferment (fish)', pronunciation: 'sak-hi-da', example: '홍어를 삭혀서 먹어요.', exampleTranslation: 'We ferment skate and eat it.' },
    { korean: '띄우다', english: 'To ferment (soy)', pronunciation: 'tti-u-da', example: '메주를 띄워서 된장을 만들어요.', exampleTranslation: 'We ferment meju to make doenjang.' },
    { korean: '식문화', english: 'Food culture', pronunciation: 'sik-mun-hwa', example: '한국 식문화가 세계적으로 주목받고 있어요.', exampleTranslation: 'Korean food culture is gaining global attention.' },
    { korean: '밥심', english: 'Energy from rice', pronunciation: 'bap-sim', example: '한국 사람은 밥심으로 살아요.', exampleTranslation: 'Koreans live on the energy of rice.' },
    { korean: '미식가', english: 'Gourmet / Foodie', pronunciation: 'mi-sik-ga', example: '그는 유명한 미식가예요.', exampleTranslation: 'He is a famous gourmet.' },
    { korean: '맛 기행', english: 'Food journey / tour', pronunciation: 'mat gi-haeng', example: '전국 맛 기행을 떠났어요.', exampleTranslation: 'I went on a nationwide food tour.' },
    { korean: '조청', english: 'Rice malt syrup', pronunciation: 'jo-cheong', example: '조청을 양념에 넣으면 윤기가 나요.', exampleTranslation: 'Adding rice malt syrup gives the seasoning a gloss.' },
    { korean: '매실청', english: 'Plum extract', pronunciation: 'mae-sil-cheong', example: '매실청으로 고기 잡내를 잡아요.', exampleTranslation: 'Plum extract removes the gamey smell from meat.' },
    { korean: '들기름', english: 'Perilla oil', pronunciation: 'deul-gi-reum', example: '들기름 막국수가 고소해요.', exampleTranslation: 'Perilla oil buckwheat noodles are nutty.' },
    { korean: '들깨', english: 'Perilla seed', pronunciation: 'deul-kkae', example: '들깨를 갈아서 넣으세요.', exampleTranslation: 'Grind perilla seeds and add them.' },
    { korean: '쪽파', english: 'Chives', pronunciation: 'jjok-pa', example: '쪽파를 송송 썰어 넣으세요.', exampleTranslation: 'Finely chop the chives and add them.' },
    { korean: '부추', english: 'Garlic chives', pronunciation: 'bu-chu', example: '부추전이 향이 좋아요.', exampleTranslation: 'Garlic chive pancakes have a nice aroma.' },
    { korean: '생강', english: 'Ginger', pronunciation: 'saeng-gang', example: '생강차 마실래요?', exampleTranslation: 'Would you like ginger tea?' },
    { korean: '깨', english: 'Sesame seeds', pronunciation: 'kkae', example: '깨를 뿌려서 마무리해요.', exampleTranslation: 'Finish by sprinkling sesame seeds.' },
    { korean: '채수', english: 'Vegetable stock', pronunciation: 'chae-su', example: '채수로 국물을 내요.', exampleTranslation: 'I make the broth with vegetable stock.' },
    { korean: '육수', english: 'Meat/bone broth', pronunciation: 'yuk-su', example: '사골 육수가 뽀얗게 우러났어요.', exampleTranslation: 'The bone broth came out milky white.' },
    { korean: '다시마', english: 'Kelp', pronunciation: 'da-si-ma', example: '다시마로 육수를 내요.', exampleTranslation: 'I make stock with kelp.' },
    { korean: '멸치', english: 'Anchovy', pronunciation: 'myeol-chi', example: '멸치 육수가 기본이에요.', exampleTranslation: 'Anchovy stock is the base.' },
    { korean: '새우젓', english: 'Salted shrimp', pronunciation: 'sae-u-jeot', example: '새우젓으로 간을 맞춰요.', exampleTranslation: 'Season with salted shrimp.' },
    { korean: '액젓', english: 'Fish sauce', pronunciation: 'aek-jeot', example: '액젓을 넣으면 감칠맛이 나요.', exampleTranslation: 'Adding fish sauce gives umami flavor.' },
    { korean: '김장', english: 'Kimchi making season', pronunciation: 'gim-jang', example: '김장철이 돌아왔어요.', exampleTranslation: 'Kimchi making season has come again.' },
    { korean: '장독대', english: 'Jar terrace (for fermentation)', pronunciation: 'jang-dok-dae', example: '할머니 집 뒤뜰에 장독대가 있어요.', exampleTranslation: 'There\'s a jar terrace in grandmother\'s backyard.' },
    { korean: '메주', english: 'Fermented soybean brick', pronunciation: 'me-ju', example: '메주를 말려서 장을 담가요.', exampleTranslation: 'We dry meju to make soy paste.' },
    { korean: '장', english: 'Fermented paste (general)', pronunciation: 'jang', example: '한국의 장 문화는 독특해요.', exampleTranslation: 'Korea\'s fermented paste culture is unique.' },
    { korean: '장담그기', english: 'Making fermented paste', pronunciation: 'jang-dam-geu-gi', example: '봄에 장담그기를 해요.', exampleTranslation: 'We make fermented paste in spring.' },
    { korean: '숙성시키다', english: 'To age / mature', pronunciation: 'suk-seong-si-ki-da', example: '김치를 냉장고에서 숙성시켜요.', exampleTranslation: 'I age the kimchi in the refrigerator.' },
    { korean: '묵은지', english: 'Aged kimchi', pronunciation: 'mug-eun-ji', example: '묵은지 김치찌개가 맛있어요.', exampleTranslation: 'Aged kimchi stew is delicious.' },
    { korean: '가니쉬', english: 'Garnish (plating)', pronunciation: 'ga-ni-swi', example: '가니쉬로 요리를 마무리해요.', exampleTranslation: 'Finish the dish with a garnish.' },
    { korean: '플레이팅', english: 'Plating', pronunciation: 'peul-le-i-ting', example: '플레이팅이 예뻐요.', exampleTranslation: 'The plating is beautiful.' },
    { korean: '맛의 조화', english: 'Harmony of flavors', pronunciation: 'mas-ui jo-hwa', example: '맛의 조화가 훌륭해요.', exampleTranslation: 'The harmony of flavors is excellent.' },
    { korean: '식품 인증', english: 'Food certification', pronunciation: 'sik-pum in-jeung', example: '식품 인증을 받았어요.', exampleTranslation: 'We received food certification.' },
    { korean: '전통 시장', english: 'Traditional market', pronunciation: 'jeon-tong si-jang', example: '전통 시장에서 먹거리를 즐겨요.', exampleTranslation: 'Enjoy food at the traditional market.' },
  ],
  5: [
    { korean: '분자 요리', english: 'Molecular gastronomy', pronunciation: 'bun-ja yo-ri', example: '분자 요리로 새로운 식감을 만들어요.', exampleTranslation: 'Molecular gastronomy creates new textures.' },
    { korean: '수비드', english: 'Sous vide', pronunciation: 'su-bi-deu', example: '수비드로 조리하면 육즙이 보존돼요.', exampleTranslation: 'Cooking sous vide preserves the meat juices.' },
    { korean: '미슐랭', english: 'Michelin', pronunciation: 'mi-syul-laeng', example: '미슐랭 별을 받은 한식당이에요.', exampleTranslation: 'It\'s a Korean restaurant awarded a Michelin star.' },
    { korean: '파인 다이닝', english: 'Fine dining', pronunciation: 'pa-in da-i-ning', example: '한식 파인 다이닝이 인기예요.', exampleTranslation: 'Korean fine dining is popular.' },
    { korean: '오마카세', english: 'Omakase', pronunciation: 'o-ma-ka-se', example: '오마카세 코스를 즐겼어요.', exampleTranslation: 'I enjoyed the omakase course.' },
    { korean: '디구스타시옹', english: 'Degustation', pronunciation: 'di-gu-seu-ta-si-ong', example: '디구스타시옹 코스를 예약했어요.', exampleTranslation: 'I reserved a degustation course.' },
    { korean: '셰프', english: 'Chef', pronunciation: 'sye-peu', example: '이 식당 셰프가 유명해요.', exampleTranslation: 'The chef of this restaurant is famous.' },
    { korean: '주방장', english: 'Head chef', pronunciation: 'ju-bang-jang', example: '주방장님의 특별 메뉴예요.', exampleTranslation: 'It\'s the head chef\'s special menu.' },
    { korean: '수셰프', english: 'Sous chef', pronunciation: 'su-sye-peu', example: '수셰프가 디저트를 담당해요.', exampleTranslation: 'The sous chef is in charge of desserts.' },
    { korean: '파티시에', english: 'Pastry chef', pronunciation: 'pa-ti-si-e', example: '파티시에가 만든 디저트예요.', exampleTranslation: 'It\'s a dessert made by the pastry chef.' },
    { korean: '소믈리에', english: 'Sommelier', pronunciation: 'so-meul-li-e', example: '소믈리에가 와인을 추천해 줬어요.', exampleTranslation: 'The sommelier recommended wine.' },
    { korean: '바리스타', english: 'Barista', pronunciation: 'ba-ri-seu-ta', example: '바리스타가 직접 내린 커피예요.', exampleTranslation: 'It\'s coffee brewed by the barista.' },
    { korean: '푸드 스타일리스트', english: 'Food stylist', pronunciation: 'pu-deu seu-ta-il-li-seu-teu', example: '푸드 스타일리스트가 촬영을 준비해요.', exampleTranslation: 'The food stylist prepares for the shoot.' },
    { korean: '푸드 칼럼니스트', english: 'Food columnist', pronunciation: 'pu-deu kal-leom-ni-seu-teu', example: '푸드 칼럼니스트가 리뷰를 썼어요.', exampleTranslation: 'The food columnist wrote a review.' },
    { korean: '미각', english: 'Sense of taste', pronunciation: 'mi-gak', example: '셰프는 미각이 뛰어나야 해요.', exampleTranslation: 'A chef needs an excellent sense of taste.' },
    { korean: '후각', english: 'Sense of smell', pronunciation: 'hu-gak', example: '후각도 맛을 느끼는 데 중요해요.', exampleTranslation: 'The sense of smell is also important for tasting.' },
    { korean: '시각적 요소', english: 'Visual element', pronunciation: 'si-gak-jeok yo-so', example: '음식의 시각적 요소도 중요해요.', exampleTranslation: 'Visual elements of food are also important.' },
    { korean: '테루아', english: 'Terroir', pronunciation: 'te-ru-a', example: '테루아가 맛에 영향을 줘요.', exampleTranslation: 'Terroir affects the taste.' },
    { korean: '제로 웨이스트', english: 'Zero waste', pronunciation: 'je-ro we-i-seu-teu', example: '제로 웨이스트 식당이 늘고 있어요.', exampleTranslation: 'Zero waste restaurants are increasing.' },
    { korean: '로컬 푸드', english: 'Local food', pronunciation: 'ro-keol pu-deu', example: '로컬 푸드 운동이 활발해요.', exampleTranslation: 'The local food movement is active.' },
    { korean: '팜 투 테이블', english: 'Farm to table', pronunciation: 'pam tu te-i-beul', example: '팜 투 테이블 레스토랑이에요.', exampleTranslation: 'It\'s a farm-to-table restaurant.' },
    { korean: '식품 과학', english: 'Food science', pronunciation: 'sik-pum gwa-hak', example: '식품 과학을 전공하고 있어요.', exampleTranslation: 'I\'m majoring in food science.' },
    { korean: '식품 공학', english: 'Food engineering', pronunciation: 'sik-pum gong-hak', example: '식품 공학 기술이 발전했어요.', exampleTranslation: 'Food engineering technology has advanced.' },
    { korean: '식품 안전', english: 'Food safety', pronunciation: 'sik-pum an-jeon', example: '식품 안전 기준이 엄격해요.', exampleTranslation: 'Food safety standards are strict.' },
    { korean: '위생 관리', english: 'Hygiene management', pronunciation: 'wi-saeng gwan-ri', example: '주방 위생 관리가 중요해요.', exampleTranslation: 'Kitchen hygiene management is important.' },
    { korean: 'HACCP', english: 'HACCP certification', pronunciation: 'hae-seop', example: 'HACCP 인증을 받은 공장이에요.', exampleTranslation: 'It\'s a HACCP-certified factory.' },
    { korean: '식품 위생법', english: 'Food hygiene law', pronunciation: 'sik-pum wi-saeng-beop', example: '식품 위생법을 준수해야 해요.', exampleTranslation: 'We must comply with food hygiene law.' },
    { korean: '식품 산업', english: 'Food industry', pronunciation: 'sik-pum san-eop', example: '한국 식품 산업이 성장하고 있어요.', exampleTranslation: 'The Korean food industry is growing.' },
    { korean: '가공식품', english: 'Processed food', pronunciation: 'ga-gong-sik-pum', example: '가공식품을 줄이려고 해요.', exampleTranslation: 'I\'m trying to reduce processed food.' },
    { korean: '냉동식품', english: 'Frozen food', pronunciation: 'naeng-dong-sik-pum', example: '냉동식품의 품질이 좋아졌어요.', exampleTranslation: 'The quality of frozen food has improved.' },
    { korean: '레토르트', english: 'Retort food (ready-to-eat)', pronunciation: 're-to-reu-teu', example: '레토르트 식품이 편리해요.', exampleTranslation: 'Retort foods are convenient.' },
    { korean: '밀키트', english: 'Meal kit', pronunciation: 'mil-ki-teu', example: '밀키트로 간편하게 요리해요.', exampleTranslation: 'I cook easily with meal kits.' },
    { korean: '프랜차이즈', english: 'Franchise', pronunciation: 'peu-raen-cha-i-jeu', example: '프랜차이즈 식당이 많아요.', exampleTranslation: 'There are many franchise restaurants.' },
    { korean: '상권', english: 'Commercial district', pronunciation: 'sang-gwon', example: '이 상권은 식당이 많아요.', exampleTranslation: 'This commercial district has many restaurants.' },
    { korean: '원가', english: 'Cost price', pronunciation: 'won-ga', example: '원가 대비 판매가를 정해요.', exampleTranslation: 'We set selling prices based on cost.' },
    { korean: '마진', english: 'Margin / Profit', pronunciation: 'ma-jin', example: '마진이 얼마나 남아요?', exampleTranslation: 'How much margin is left?' },
    { korean: '메뉴 개발', english: 'Menu development', pronunciation: 'me-nyu gae-bal', example: '새로운 메뉴를 개발하고 있어요.', exampleTranslation: 'We\'re developing a new menu.' },
    { korean: '시식회', english: 'Tasting event', pronunciation: 'si-sik-hoe', example: '신메뉴 시식회를 열었어요.', exampleTranslation: 'We held a tasting event for new menu items.' },
    { korean: '고객 만족도', english: 'Customer satisfaction', pronunciation: 'go-gaek man-jok-do', example: '고객 만족도가 높아요.', exampleTranslation: 'Customer satisfaction is high.' },
    { korean: '회전율', english: 'Turnover rate', pronunciation: 'hoe-jeon-yul', example: '테이블 회전율이 중요해요.', exampleTranslation: 'Table turnover rate is important.' },
    { korean: '식품 표시', english: 'Food labeling', pronunciation: 'sik-pum pyo-si', example: '식품 표시를 잘 읽어 보세요.', exampleTranslation: 'Read the food labels carefully.' },
    { korean: '영양 성분표', english: 'Nutrition facts label', pronunciation: 'yeong-yang seong-bun-pyo', example: '영양 성분표를 확인하세요.', exampleTranslation: 'Check the nutrition facts label.' },
    { korean: '원재료명', english: 'Raw material name', pronunciation: 'won-jae-ryo-myeong', example: '원재료명을 확인해 주세요.', exampleTranslation: 'Please check the raw material names.' },
    { korean: '유전자 변형', english: 'Genetically modified', pronunciation: 'yu-jeon-ja byeon-hyeong', example: '유전자 변형 식품이 아니에요.', exampleTranslation: 'It\'s not a genetically modified food.' },
    { korean: '수입 식품', english: 'Imported food', pronunciation: 'su-ip sik-pum', example: '수입 식품 코너에 가 봤어?', exampleTranslation: 'Have you been to the imported food section?' },
    { korean: '수출', english: 'Export', pronunciation: 'su-chul', example: '한식의 수출이 늘고 있어요.', exampleTranslation: 'Exports of Korean food are increasing.' },
    { korean: '한류 음식', english: 'Hallyu food', pronunciation: 'hal-lyu eum-sik', example: '한류 덕분에 한국 음식이 인기예요.', exampleTranslation: 'Korean food is popular thanks to Hallyu.' },
    { korean: '글로벌 한식', english: 'Global Korean cuisine', pronunciation: 'geul-lo-beol han-sik', example: '글로벌 한식 시장이 확대되고 있어요.', exampleTranslation: 'The global Korean food market is expanding.' },
    { korean: '퓨전 한식', english: 'Fusion Korean food', pronunciation: 'pyu-jeon han-sik', example: '퓨전 한식이 젊은층에 인기예요.', exampleTranslation: 'Fusion Korean food is popular with young people.' },
    { korean: '현지화', english: 'Localization', pronunciation: 'hyeon-ji-hwa', example: '한식의 현지화가 중요해요.', exampleTranslation: 'Localization of Korean food is important.' },
    { korean: '당도', english: 'Sugar content / Brix', pronunciation: 'dang-do', example: '과일의 당도를 측정해요.', exampleTranslation: 'We measure the sugar content of fruit.' },
    { korean: '산도', english: 'Acidity', pronunciation: 'san-do', example: '와인의 산도가 적당해요.', exampleTranslation: 'The acidity of the wine is moderate.' },
    { korean: '염도', english: 'Salinity', pronunciation: 'yeom-do', example: '김치의 염도를 확인해요.', exampleTranslation: 'We check the salinity of the kimchi.' },
    { korean: '수분 함량', english: 'Moisture content', pronunciation: 'su-bun ham-nyang', example: '수분 함량이 적절해야 해요.', exampleTranslation: 'The moisture content needs to be appropriate.' },
    { korean: '저온 숙성', english: 'Low-temperature aging', pronunciation: 'jeo-on suk-seong', example: '저온 숙성 삼겹살이 인기예요.', exampleTranslation: 'Low-temperature aged pork belly is popular.' },
    { korean: '드라이 에이징', english: 'Dry aging', pronunciation: 'deu-ra-i e-i-jing', example: '드라이 에이징 스테이크가 맛있어요.', exampleTranslation: 'Dry-aged steak is delicious.' },
    { korean: '웻 에이징', english: 'Wet aging', pronunciation: 'wet e-i-jing', example: '웻 에이징은 진공 포장으로 해요.', exampleTranslation: 'Wet aging is done with vacuum packaging.' },
    { korean: '마이야르 반응', english: 'Maillard reaction', pronunciation: 'ma-i-ya-reu ban-eung', example: '마이야르 반응으로 갈색이 돼요.', exampleTranslation: 'The Maillard reaction creates browning.' },
    { korean: '캐러멜화', english: 'Caramelization', pronunciation: 'kae-reo-mel-hwa', example: '양파를 캐러멜화시켜요.', exampleTranslation: 'Caramelize the onions.' },
    { korean: '유화', english: 'Emulsification', pronunciation: 'yu-hwa', example: '소스를 유화시켜 만들어요.', exampleTranslation: 'We make the sauce by emulsification.' },
    { korean: '겔화', english: 'Gelation', pronunciation: 'gel-hwa', example: '한천으로 겔화시켜요.', exampleTranslation: 'Gelate with agar.' },
    { korean: '삼투압', english: 'Osmotic pressure', pronunciation: 'sam-tu-ap', example: '절임은 삼투압 원리를 이용해요.', exampleTranslation: 'Pickling uses the principle of osmotic pressure.' },
    { korean: '효소', english: 'Enzyme', pronunciation: 'hyo-so', example: '효소가 발효를 촉진해요.', exampleTranslation: 'Enzymes accelerate fermentation.' },
    { korean: '균주', english: 'Bacterial strain', pronunciation: 'gyun-ju', example: '다양한 균주가 발효에 관여해요.', exampleTranslation: 'Various bacterial strains are involved in fermentation.' },
    { korean: '항산화', english: 'Antioxidant', pronunciation: 'hang-san-hwa', example: '김치에 항산화 성분이 있어요.', exampleTranslation: 'Kimchi contains antioxidant components.' },
    { korean: '프로바이오틱스', english: 'Probiotics', pronunciation: 'peu-ro-ba-i-o-tik-seu', example: '김치는 천연 프로바이오틱스예요.', exampleTranslation: 'Kimchi is a natural probiotic.' },
    { korean: '프리바이오틱스', english: 'Prebiotics', pronunciation: 'peu-ri-ba-i-o-tik-seu', example: '프리바이오틱스가 장 건강에 좋아요.', exampleTranslation: 'Prebiotics are good for gut health.' },
    { korean: '식품 저장', english: 'Food storage', pronunciation: 'sik-pum jeo-jang', example: '올바른 식품 저장법을 알아야 해요.', exampleTranslation: 'You need to know proper food storage methods.' },
    { korean: '진공 포장', english: 'Vacuum packaging', pronunciation: 'jin-gong po-jang', example: '진공 포장으로 신선도를 유지해요.', exampleTranslation: 'Vacuum packaging maintains freshness.' },
    { korean: '콜드 체인', english: 'Cold chain', pronunciation: 'kol-deu che-in', example: '콜드 체인 시스템이 중요해요.', exampleTranslation: 'The cold chain system is important.' },
    { korean: '푸드테크', english: 'Foodtech', pronunciation: 'pu-deu-te-keu', example: '푸드테크 스타트업이 성장하고 있어요.', exampleTranslation: 'Foodtech startups are growing.' },
    { korean: '대체육', english: 'Alternative meat', pronunciation: 'dae-che-yuk', example: '대체육 시장이 커지고 있어요.', exampleTranslation: 'The alternative meat market is growing.' },
    { korean: '배양육', english: 'Cultured meat', pronunciation: 'bae-yang-yuk', example: '배양육 기술이 발전하고 있어요.', exampleTranslation: 'Cultured meat technology is advancing.' },
    { korean: '식물성 단백질', english: 'Plant-based protein', pronunciation: 'sing-mul-seong dan-baek-jil', example: '식물성 단백질 제품이 다양해요.', exampleTranslation: 'There are various plant-based protein products.' },
    { korean: '지속 가능한 식품', english: 'Sustainable food', pronunciation: 'ji-sok ga-neung-han sik-pum', example: '지속 가능한 식품 생산이 중요해요.', exampleTranslation: 'Sustainable food production is important.' },
    { korean: '탄소 발자국', english: 'Carbon footprint (food)', pronunciation: 'tan-so bal-ja-guk', example: '음식의 탄소 발자국을 줄여야 해요.', exampleTranslation: 'We need to reduce the carbon footprint of food.' },
    { korean: '스마트 팜', english: 'Smart farm', pronunciation: 'seu-ma-teu pam', example: '스마트 팜에서 채소를 재배해요.', exampleTranslation: 'We grow vegetables on a smart farm.' },
    { korean: '도시 농업', english: 'Urban farming', pronunciation: 'do-si nong-eop', example: '도시 농업이 주목받고 있어요.', exampleTranslation: 'Urban farming is getting attention.' },
    { korean: '식량 안보', english: 'Food security', pronunciation: 'sing-nyang an-bo', example: '식량 안보가 국가 과제예요.', exampleTranslation: 'Food security is a national priority.' },
    { korean: '음식물 쓰레기', english: 'Food waste', pronunciation: 'eum-sing-mul sseu-re-gi', example: '음식물 쓰레기를 줄여야 해요.', exampleTranslation: 'We need to reduce food waste.' },
    { korean: '업사이클링 식품', english: 'Upcycled food', pronunciation: 'eop-sa-i-keul-ling sik-pum', example: '업사이클링 식품이 환경에 좋아요.', exampleTranslation: 'Upcycled food is good for the environment.' },
    { korean: '식품 트렌드', english: 'Food trend', pronunciation: 'sik-pum teu-ren-deu', example: '올해 식품 트렌드가 뭐예요?', exampleTranslation: 'What\'s this year\'s food trend?' },
    { korean: '간편식', english: 'Convenience food / HMR', pronunciation: 'gan-pyeon-sik', example: '1인 가구가 늘면서 간편식이 인기예요.', exampleTranslation: 'Convenience food is popular as single-person households increase.' },
    { korean: '가성비', english: 'Cost-effectiveness', pronunciation: 'ga-seong-bi', example: '이 식당은 가성비가 좋아요.', exampleTranslation: 'This restaurant is cost-effective.' },
    { korean: '맛집 탐방', english: 'Restaurant exploration', pronunciation: 'mat-jip tam-bang', example: '주말에 맛집 탐방 갈까?', exampleTranslation: 'Shall we go restaurant exploring this weekend?' },
    { korean: '쿠킹 클래스', english: 'Cooking class', pronunciation: 'ku-king keul-lae-seu', example: '한식 쿠킹 클래스에 참여했어요.', exampleTranslation: 'I participated in a Korean cooking class.' },
    { korean: '레시피 개발', english: 'Recipe development', pronunciation: 're-si-pi gae-bal', example: '새로운 레시피를 개발 중이에요.', exampleTranslation: 'I\'m developing a new recipe.' },
    { korean: '조리 과학', english: 'Culinary science', pronunciation: 'jo-ri gwa-hak', example: '조리 과학을 공부하고 있어요.', exampleTranslation: 'I\'m studying culinary science.' },
    { korean: '테이스팅 노트', english: 'Tasting notes', pronunciation: 'te-i-seu-ting no-teu', example: '테이스팅 노트를 작성해요.', exampleTranslation: 'I write tasting notes.' },
    { korean: '페어링', english: 'Pairing (food & drink)', pronunciation: 'pe-eo-ring', example: '와인 페어링 코스예요.', exampleTranslation: 'It\'s a wine pairing course.' },
    { korean: '식재료 유통', english: 'Ingredient distribution', pronunciation: 'sik-jae-ryo yu-tong', example: '식재료 유통 과정을 공부해요.', exampleTranslation: 'I study ingredient distribution processes.' },
    { korean: '외식 산업', english: 'Dining-out industry', pronunciation: 'oe-sik san-eop', example: '외식 산업이 회복되고 있어요.', exampleTranslation: 'The dining-out industry is recovering.' },
    { korean: '케이터링', english: 'Catering', pronunciation: 'ke-i-teo-ring', example: '행사 케이터링을 맡았어요.', exampleTranslation: 'We handled the event catering.' },
    { korean: '식품 마케팅', english: 'Food marketing', pronunciation: 'sik-pum ma-ke-ting', example: '식품 마케팅 전략을 세웠어요.', exampleTranslation: 'We established a food marketing strategy.' },
    { korean: '브랜딩', english: 'Branding (food)', pronunciation: 'beu-raen-ding', example: '식품 브랜딩이 중요해요.', exampleTranslation: 'Food branding is important.' },
    { korean: '소비자 분석', english: 'Consumer analysis', pronunciation: 'so-bi-ja bun-seok', example: '소비자 분석을 통해 트렌드를 파악해요.', exampleTranslation: 'We identify trends through consumer analysis.' },
    { korean: '식품 포장 디자인', english: 'Food packaging design', pronunciation: 'sik-pum po-jang di-ja-in', example: '식품 포장 디자인이 매출에 영향을 줘요.', exampleTranslation: 'Food packaging design affects sales.' },
    { korean: '셀프 서비스', english: 'Self-service', pronunciation: 'sel-peu seo-bi-seu', example: '물은 셀프 서비스예요.', exampleTranslation: 'Water is self-service.' },
    { korean: '무인 식당', english: 'Unmanned restaurant', pronunciation: 'mu-in sik-dang', example: '무인 식당이 늘고 있어요.', exampleTranslation: 'Unmanned restaurants are increasing.' },
    { korean: '식품 위해 요소', english: 'Food hazard factor', pronunciation: 'sik-pum wi-hae yo-so', example: '식품 위해 요소를 관리해요.', exampleTranslation: 'We manage food hazard factors.' },
  ],
  6: [
    { korean: '수라상', english: 'Royal dining table', pronunciation: 'su-ra-sang', example: '조선 시대 수라상은 12첩 반상이었어요.', exampleTranslation: 'The Joseon-era royal dining table was a 12-dish setting.' },
    { korean: '궁중 음식', english: 'Royal court food', pronunciation: 'gung-jung eum-sik', example: '궁중 음식의 역사를 연구해요.', exampleTranslation: 'I research the history of royal court food.' },
    { korean: '반상차림', english: 'Traditional table setting', pronunciation: 'ban-sang-cha-rim', example: '3첩 반상에서 12첩 반상까지 있어요.', exampleTranslation: 'There are settings from 3-dish to 12-dish spreads.' },
    { korean: '첩', english: 'Dish count (table setting)', pronunciation: 'cheop', example: '5첩 반상은 다섯 가지 반찬이에요.', exampleTranslation: 'A 5-cheop table has five side dishes.' },
    { korean: '전통 한식', english: 'Traditional Korean cuisine', pronunciation: 'jeon-tong han-sik', example: '전통 한식의 맥을 잇고 있어요.', exampleTranslation: 'We are carrying on the tradition of Korean cuisine.' },
    { korean: '의궤', english: 'Royal protocol records', pronunciation: 'ui-gwe', example: '의궤에 궁중 연회 음식이 기록돼 있어요.', exampleTranslation: 'Royal banquet foods are recorded in the uigwe.' },
    { korean: '조선왕조실록', english: 'Annals of the Joseon Dynasty', pronunciation: 'jo-seon-wang-jo-sil-lok', example: '조선왕조실록에 식재료 기록이 있어요.', exampleTranslation: 'There are ingredient records in the Joseon Annals.' },
    { korean: '음식디미방', english: 'Eumsikdimibang (oldest Korean cookbook)', pronunciation: 'eum-sik-di-mi-bang', example: '음식디미방은 1670년에 쓰여졌어요.', exampleTranslation: 'Eumsikdimibang was written in 1670.' },
    { korean: '규합총서', english: 'Gyuhap Chongseo (housekeeping encyclopedia)', pronunciation: 'gyu-hap-chong-seo', example: '규합총서에 전통 요리법이 수록돼 있어요.', exampleTranslation: 'Traditional recipes are included in Gyuhap Chongseo.' },
    { korean: '전통 장류', english: 'Traditional fermented pastes', pronunciation: 'jeon-tong jang-nyu', example: '전통 장류의 맛은 지역마다 달라요.', exampleTranslation: 'The taste of traditional fermented pastes varies by region.' },
    { korean: '장 담그기', english: 'Fermented paste making', pronunciation: 'jang dam-geu-gi', example: '장 담그기는 유네스코 무형문화유산이에요.', exampleTranslation: 'Paste making is a UNESCO intangible cultural heritage.' },
    { korean: '종가 음식', english: 'Head family house food', pronunciation: 'jong-ga eum-sik', example: '종가 음식은 대대로 전해져요.', exampleTranslation: 'Head family house food is passed down through generations.' },
    { korean: '사찰 음식', english: 'Temple food', pronunciation: 'sa-chal eum-sik', example: '사찰 음식은 오신채를 사용하지 않아요.', exampleTranslation: 'Temple food does not use the five pungent vegetables.' },
    { korean: '오신채', english: 'Five pungent vegetables', pronunciation: 'o-sin-chae', example: '오신채는 마늘, 파, 부추, 달래, 흥거예요.', exampleTranslation: 'The five pungent vegetables are garlic, green onion, chives, wild chives, and asafoetida.' },
    { korean: '약식동원', english: 'Food as medicine philosophy', pronunciation: 'yak-sik-dong-won', example: '약식동원은 한국 음식 철학이에요.', exampleTranslation: 'Food as medicine is a Korean food philosophy.' },
    { korean: '신토불이', english: 'Body and soil are one', pronunciation: 'sin-to-bul-i', example: '신토불이는 지역 먹거리를 강조해요.', exampleTranslation: 'Sintoburi emphasizes local food.' },
    { korean: '음양오행', english: 'Yin-yang five elements', pronunciation: 'eum-yang-o-haeng', example: '한식은 음양오행 사상에 기초해요.', exampleTranslation: 'Korean food is based on yin-yang five elements philosophy.' },
    { korean: '오색', english: 'Five colors (food philosophy)', pronunciation: 'o-saek', example: '한식의 오색은 빨강, 노랑, 흰, 검정, 초록이에요.', exampleTranslation: 'The five colors of Korean food are red, yellow, white, black, and green.' },
    { korean: '오미', english: 'Five flavors', pronunciation: 'o-mi', example: '오미의 조화가 한식의 핵심이에요.', exampleTranslation: 'The harmony of five flavors is the essence of Korean food.' },
    { korean: '발효 과학', english: 'Fermentation science', pronunciation: 'bal-hyo gwa-hak', example: '발효 과학을 깊이 연구해요.', exampleTranslation: 'I deeply research fermentation science.' },
    { korean: '김치학', english: 'Kimchi studies', pronunciation: 'gim-chi-hak', example: '김치학은 과학적 연구 분야예요.', exampleTranslation: 'Kimchi studies is a scientific research field.' },
    { korean: '류코노스톡', english: 'Leuconostoc (kimchi bacteria)', pronunciation: 'ryu-ko-no-seu-tok', example: '류코노스톡이 김치 발효의 핵심 균이에요.', exampleTranslation: 'Leuconostoc is the key bacteria in kimchi fermentation.' },
    { korean: '젖산 발효', english: 'Lactic acid fermentation', pronunciation: 'jeot-san bal-hyo', example: '김치는 젖산 발효 과정을 거쳐요.', exampleTranslation: 'Kimchi undergoes lactic acid fermentation.' },
    { korean: '아미노산', english: 'Amino acid', pronunciation: 'a-mi-no-san', example: '된장에 아미노산이 풍부해요.', exampleTranslation: 'Doenjang is rich in amino acids.' },
    { korean: '글루타민산', english: 'Glutamic acid', pronunciation: 'geul-lu-ta-min-san', example: '글루타민산이 감칠맛을 만들어요.', exampleTranslation: 'Glutamic acid creates umami flavor.' },
    { korean: '단백질 분해', english: 'Protein decomposition', pronunciation: 'dan-baek-jil bun-hae', example: '발효 과정에서 단백질 분해가 일어나요.', exampleTranslation: 'Protein decomposition occurs during fermentation.' },
    { korean: '누룩', english: 'Nuruk (fermentation starter)', pronunciation: 'nu-ruk', example: '누룩으로 전통주를 빚어요.', exampleTranslation: 'We brew traditional liquor with nuruk.' },
    { korean: '국균', english: 'Aspergillus (mold for fermentation)', pronunciation: 'guk-gyun', example: '국균은 장류 발효에 핵심이에요.', exampleTranslation: 'Aspergillus is essential for fermented paste making.' },
    { korean: '곰팡이', english: 'Mold (in fermentation)', pronunciation: 'gom-pang-i', example: '유익한 곰팡이가 발효를 도와요.', exampleTranslation: 'Beneficial mold helps fermentation.' },
    { korean: '효모', english: 'Yeast', pronunciation: 'hyo-mo', example: '효모가 알코올 발효를 일으켜요.', exampleTranslation: 'Yeast causes alcoholic fermentation.' },
    { korean: '전통주', english: 'Traditional Korean liquor', pronunciation: 'jeon-tong-ju', example: '전통주 복원 사업이 진행 중이에요.', exampleTranslation: 'A traditional liquor restoration project is underway.' },
    { korean: '약주', english: 'Refined rice wine', pronunciation: 'yak-ju', example: '약주는 맑게 거른 술이에요.', exampleTranslation: 'Yakju is a clear filtered liquor.' },
    { korean: '청주', english: 'Clear rice wine', pronunciation: 'cheong-ju', example: '청주는 요리에도 사용해요.', exampleTranslation: 'Cheongju is also used in cooking.' },
    { korean: '소곡주', english: 'Sogokju (wheat wine)', pronunciation: 'so-gok-ju', example: '한산 소곡주는 충남의 전통주예요.', exampleTranslation: 'Hansan Sogokju is a traditional liquor of Chungnam.' },
    { korean: '안동소주', english: 'Andong soju', pronunciation: 'an-dong-so-ju', example: '안동소주는 전통 증류식 소주예요.', exampleTranslation: 'Andong soju is traditional distilled soju.' },
    { korean: '증류', english: 'Distillation', pronunciation: 'jeung-nyu', example: '증류 과정에서 알코올 도수가 높아져요.', exampleTranslation: 'Alcohol content increases during distillation.' },
    { korean: '양조', english: 'Brewing', pronunciation: 'yang-jo', example: '전통 양조 기법을 배우고 있어요.', exampleTranslation: 'I\'m learning traditional brewing techniques.' },
    { korean: '주모', english: 'Mother of vinegar', pronunciation: 'ju-mo', example: '초산 발효에 주모가 필요해요.', exampleTranslation: 'Mother of vinegar is needed for acetic acid fermentation.' },
    { korean: '무형문화재', english: 'Intangible cultural heritage', pronunciation: 'mu-hyeong-mun-hwa-jae', example: '김치 담그기가 무형문화재예요.', exampleTranslation: 'Kimchi making is an intangible cultural heritage.' },
    { korean: '식품 명인', english: 'Food master', pronunciation: 'sik-pum myeong-in', example: '대한민국 식품 명인으로 지정됐어요.', exampleTranslation: 'They were designated a Korean food master.' },
    { korean: '조리 기능장', english: 'Master chef certificate', pronunciation: 'jo-ri gi-neung-jang', example: '조리 기능장 자격을 취득했어요.', exampleTranslation: 'They obtained the master chef certificate.' },
    { korean: '한식 세계화', english: 'Korean food globalization', pronunciation: 'han-sik se-gye-hwa', example: '한식 세계화 정책이 추진되고 있어요.', exampleTranslation: 'Korean food globalization policies are being promoted.' },
    { korean: '김치 유네스코', english: 'Kimchi UNESCO heritage', pronunciation: 'gim-chi yu-ne-seu-ko', example: '김장 문화가 유네스코에 등재됐어요.', exampleTranslation: 'Kimjang culture was registered with UNESCO.' },
    { korean: '한식 철학', english: 'Korean food philosophy', pronunciation: 'han-sik cheol-hak', example: '한식 철학의 근본은 자연과의 조화예요.', exampleTranslation: 'The foundation of Korean food philosophy is harmony with nature.' },
    { korean: '자연 발효', english: 'Natural fermentation', pronunciation: 'ja-yeon bal-hyo', example: '자연 발효는 시간과 정성이 필요해요.', exampleTranslation: 'Natural fermentation requires time and care.' },
    { korean: '인공 발효', english: 'Artificial fermentation', pronunciation: 'in-gong bal-hyo', example: '인공 발효로 시간을 단축해요.', exampleTranslation: 'Artificial fermentation shortens the time.' },
    { korean: '식품 미생물학', english: 'Food microbiology', pronunciation: 'sik-pum mi-saeng-mul-hak', example: '식품 미생물학을 전공했어요.', exampleTranslation: 'I majored in food microbiology.' },
    { korean: '관능 평가', english: 'Sensory evaluation', pronunciation: 'gwan-neung pyeong-ga', example: '관능 평가를 통해 품질을 판단해요.', exampleTranslation: 'We judge quality through sensory evaluation.' },
    { korean: '식품 레올로지', english: 'Food rheology', pronunciation: 'sik-pum re-ol-lo-ji', example: '식품 레올로지는 물성을 연구해요.', exampleTranslation: 'Food rheology studies physical properties.' },
    { korean: '물성', english: 'Physical properties (food)', pronunciation: 'mul-seong', example: '떡의 물성을 분석해요.', exampleTranslation: 'We analyze the physical properties of rice cake.' },
    { korean: '텍스처 프로파일', english: 'Texture profile analysis', pronunciation: 'tek-seu-cheo peu-ro-pa-il', example: '텍스처 프로파일 분석을 실시해요.', exampleTranslation: 'We conduct texture profile analysis.' },
    { korean: '전분 호화', english: 'Starch gelatinization', pronunciation: 'jeon-bun ho-hwa', example: '전분 호화 온도를 측정해요.', exampleTranslation: 'We measure the starch gelatinization temperature.' },
    { korean: '전분 노화', english: 'Starch retrogradation', pronunciation: 'jeon-bun no-hwa', example: '떡의 전분 노화를 방지해야 해요.', exampleTranslation: 'We need to prevent starch retrogradation in rice cakes.' },
    { korean: '단백질 변성', english: 'Protein denaturation', pronunciation: 'dan-baek-jil byeon-seong', example: '열에 의해 단백질 변성이 일어나요.', exampleTranslation: 'Protein denaturation occurs due to heat.' },
    { korean: '지질 산화', english: 'Lipid oxidation', pronunciation: 'ji-jil san-hwa', example: '지질 산화를 방지해야 보존 기간이 늘어나요.', exampleTranslation: 'Preventing lipid oxidation extends the shelf life.' },
    { korean: '수분 활성도', english: 'Water activity', pronunciation: 'su-bun hwal-seong-do', example: '수분 활성도가 낮으면 미생물 성장이 억제돼요.', exampleTranslation: 'Low water activity inhibits microbial growth.' },
    { korean: '비효소적 갈변', english: 'Non-enzymatic browning', pronunciation: 'bi-hyo-so-jeok gal-byeon', example: '비효소적 갈변은 마이야르 반응의 일종이에요.', exampleTranslation: 'Non-enzymatic browning is a type of Maillard reaction.' },
    { korean: '효소적 갈변', english: 'Enzymatic browning', pronunciation: 'hyo-so-jeok gal-byeon', example: '사과의 변색은 효소적 갈변이에요.', exampleTranslation: 'Apple discoloration is enzymatic browning.' },
    { korean: '동결 건조', english: 'Freeze drying', pronunciation: 'dong-gyeol geon-jo', example: '동결 건조로 영양소를 보존해요.', exampleTranslation: 'Freeze drying preserves nutrients.' },
    { korean: '고압 처리', english: 'High-pressure processing', pronunciation: 'go-ap cheo-ri', example: '고압 처리로 살균해요.', exampleTranslation: 'We sterilize with high-pressure processing.' },
    { korean: '살균', english: 'Sterilization', pronunciation: 'sal-gyun', example: '저온 살균 방법을 사용해요.', exampleTranslation: 'We use pasteurization methods.' },
    { korean: '멸균', english: 'Complete sterilization', pronunciation: 'myeol-gyun', example: '멸균 처리를 거쳐 유통해요.', exampleTranslation: 'It\'s distributed after complete sterilization.' },
    { korean: '향미 성분', english: 'Flavor compound', pronunciation: 'hyang-mi seong-bun', example: '발효 과정에서 향미 성분이 생겨요.', exampleTranslation: 'Flavor compounds are created during fermentation.' },
    { korean: '관능 검사', english: 'Sensory test', pronunciation: 'gwan-neung geom-sa', example: '전문 패널이 관능 검사를 실시해요.', exampleTranslation: 'A professional panel conducts sensory tests.' },
    { korean: '관능적 특성', english: 'Sensory characteristics', pronunciation: 'gwan-neung-jeok teuk-seong', example: '김치의 관능적 특성을 분석해요.', exampleTranslation: 'We analyze the sensory characteristics of kimchi.' },
    { korean: '식이 요법', english: 'Dietary therapy', pronunciation: 'sig-i yo-beop', example: '전통 식이 요법을 연구해요.', exampleTranslation: 'I research traditional dietary therapy.' },
    { korean: '약선 요리', english: 'Medicinal cuisine', pronunciation: 'yak-seon yo-ri', example: '약선 요리는 건강을 위한 음식이에요.', exampleTranslation: 'Medicinal cuisine is food for health.' },
    { korean: '보양', english: 'Nourishment / Health tonic', pronunciation: 'bo-yang', example: '보양 음식으로 기력을 회복해요.', exampleTranslation: 'Recover vitality with nourishing food.' },
    { korean: '식양생', english: 'Food-based health cultivation', pronunciation: 'sig-yang-saeng', example: '식양생은 음식으로 건강을 돌보는 것이에요.', exampleTranslation: 'Sigyangseang is taking care of health through food.' },
    { korean: '향토 음식', english: 'Local traditional food', pronunciation: 'hyang-to eum-sik', example: '각 지역의 향토 음식이 다양해요.', exampleTranslation: 'Each region has diverse local traditional foods.' },
    { korean: '향토 식재료', english: 'Local traditional ingredients', pronunciation: 'hyang-to sik-jae-ryo', example: '향토 식재료를 발굴하고 있어요.', exampleTranslation: 'We are discovering local traditional ingredients.' },
    { korean: '식생활 문화', english: 'Food lifestyle culture', pronunciation: 'sik-saeng-hwal mun-hwa', example: '한국인의 식생활 문화가 변하고 있어요.', exampleTranslation: 'Korean food lifestyle culture is changing.' },
    { korean: '제례 음식', english: 'Ancestral rite food', pronunciation: 'je-rye eum-sik', example: '제례 음식에는 규칙이 있어요.', exampleTranslation: 'There are rules for ancestral rite foods.' },
    { korean: '통과의례 음식', english: 'Rite of passage food', pronunciation: 'tong-gwa-ui-rye eum-sik', example: '돌잔치에 수수팥떡을 놓아요.', exampleTranslation: 'We place sorghum rice cake at a first birthday party.' },
    { korean: '세시 음식', english: 'Seasonal ritual food', pronunciation: 'se-si eum-sik', example: '정월대보름에 오곡밥을 먹어요.', exampleTranslation: 'We eat five-grain rice on the first full moon.' },
    { korean: '절기 음식', english: 'Solar term food', pronunciation: 'jeol-gi eum-sik', example: '동지에 팥죽을 먹어요.', exampleTranslation: 'We eat red bean porridge on the winter solstice.' },
    { korean: '절식', english: 'Festival food', pronunciation: 'jeol-sik', example: '추석 절식으로 송편을 빚어요.', exampleTranslation: 'We make songpyeon as Chuseok festival food.' },
    { korean: '약밥', english: 'Sweet rice with nuts and dates', pronunciation: 'yak-bap', example: '정월대보름에 약밥을 만들어 먹어요.', exampleTranslation: 'We make and eat yakbap on the first full moon.' },
    { korean: '송편', english: 'Half-moon rice cake', pronunciation: 'song-pyeon', example: '추석에 온 가족이 송편을 빚어요.', exampleTranslation: 'The whole family makes songpyeon on Chuseok.' },
    { korean: '수수팥떡', english: 'Sorghum red bean rice cake', pronunciation: 'su-su-pat-tteok', example: '아이 돌에 수수팥떡을 해요.', exampleTranslation: 'We make sorghum rice cake for a child\'s first birthday.' },
    { korean: '오곡밥', english: 'Five-grain rice', pronunciation: 'o-gok-bap', example: '정월대보름에 오곡밥을 먹어요.', exampleTranslation: 'We eat five-grain rice on the first full moon.' },
    { korean: '백설기', english: 'White steamed rice cake', pronunciation: 'baek-seol-gi', example: '백일에 백설기를 해요.', exampleTranslation: 'We make baekseolgi for a baby\'s 100th day.' },
    { korean: '한과', english: 'Traditional Korean confection', pronunciation: 'han-gwa', example: '명절에 한과를 만들어요.', exampleTranslation: 'We make Korean confections for holidays.' },
    { korean: '강정', english: 'Puffed rice confection', pronunciation: 'gang-jeong', example: '깨강정이 고소해요.', exampleTranslation: 'Sesame gangjung is nutty.' },
    { korean: '다식', english: 'Tea confection', pronunciation: 'da-sik', example: '다식은 차와 함께 먹는 과자예요.', exampleTranslation: 'Dasik is a confection eaten with tea.' },
    { korean: '전통 다과', english: 'Traditional tea and confections', pronunciation: 'jeon-tong da-gwa', example: '전통 다과를 즐기는 문화가 있어요.', exampleTranslation: 'There is a culture of enjoying traditional tea and confections.' },
    { korean: '향토 발효', english: 'Regional fermentation tradition', pronunciation: 'hyang-to bal-hyo', example: '지역마다 고유한 향토 발효 방식이 있어요.', exampleTranslation: 'Each region has its unique fermentation tradition.' },
    { korean: '삭임', english: 'Controlled fermentation', pronunciation: 'sag-im', example: '삭임 과정을 통해 깊은 맛이 나요.', exampleTranslation: 'Deep flavor comes through the controlled fermentation process.' },
    { korean: '식품 인류학', english: 'Food anthropology', pronunciation: 'sik-pum in-ryu-hak', example: '식품 인류학적 관점에서 한식을 봐요.', exampleTranslation: 'I look at Korean food from a food anthropology perspective.' },
    { korean: '가스트로노미', english: 'Gastronomy', pronunciation: 'ga-seu-teu-ro-no-mi', example: '가스트로노미는 음식과 문화의 학문이에요.', exampleTranslation: 'Gastronomy is the study of food and culture.' },
    { korean: '식문화 유산', english: 'Culinary heritage', pronunciation: 'sik-mun-hwa yu-san', example: '한국의 식문화 유산을 보존해야 해요.', exampleTranslation: 'We must preserve Korea\'s culinary heritage.' },
    { korean: '전승', english: 'Transmission / Heritage passing', pronunciation: 'jeon-seung', example: '어머니에서 딸로 전승되는 음식이에요.', exampleTranslation: 'It\'s food transmitted from mother to daughter.' },
    { korean: '복원', english: 'Restoration (of recipes)', pronunciation: 'bok-won', example: '고문헌을 통해 옛 요리를 복원해요.', exampleTranslation: 'We restore old recipes through historical documents.' },
    { korean: '고문헌', english: 'Historical documents', pronunciation: 'go-mun-heon', example: '고문헌에서 전통 조리법을 찾아요.', exampleTranslation: 'We find traditional recipes in historical documents.' },
    { korean: '해체 요리', english: 'Deconstructed cuisine', pronunciation: 'hae-che yo-ri', example: '전통 한식을 해체하여 재해석했어요.', exampleTranslation: 'We deconstructed and reinterpreted traditional Korean food.' },
    { korean: '미식 외교', english: 'Gastrodiplomacy', pronunciation: 'mi-sik oe-gyo', example: '한식을 통한 미식 외교가 활발해요.', exampleTranslation: 'Gastrodiplomacy through Korean food is active.' },
    { korean: '식품 고고학', english: 'Food archaeology', pronunciation: 'sik-pum go-go-hak', example: '식품 고고학으로 고대 식생활을 연구해요.', exampleTranslation: 'Food archaeology studies ancient diets.' },
    { korean: '원형 복원', english: 'Original form restoration', pronunciation: 'won-hyeong bok-won', example: '전통 음식의 원형을 복원하는 연구예요.', exampleTranslation: 'It\'s research to restore the original form of traditional food.' },
    { korean: '한식 아카이브', english: 'Korean food archive', pronunciation: 'han-sik a-ka-i-beu', example: '한식 아카이브에 고문헌 자료가 있어요.', exampleTranslation: 'The Korean food archive has historical document materials.' },
    { korean: '조리 원리', english: 'Cooking principles', pronunciation: 'jo-ri won-ri', example: '전통 한식의 조리 원리를 연구해요.', exampleTranslation: 'I research the cooking principles of traditional Korean food.' },
  ],
};
