import { ThemeWord } from '../theme-data';

export const KPOP_WORDS: Record<number, ThemeWord[]> = {
  1: [
    { korean: '최애', english: 'Bias / Favorite member', pronunciation: 'choe-ae', example: '내 최애는 지민이야.', exampleTranslation: 'My bias is Jimin.' },
    { korean: '컴백', english: 'Comeback', pronunciation: 'keom-baek', example: '다음 달에 컴백한대!', exampleTranslation: 'They say they\'re coming back next month!' },
    { korean: '앨범', english: 'Album', pronunciation: 'ael-beom', example: '새 앨범 샀어!', exampleTranslation: 'I bought the new album!' },
    { korean: '콘서트', english: 'Concert', pronunciation: 'kon-seo-teu', example: '콘서트 티켓 구했어!', exampleTranslation: 'I got concert tickets!' },
    { korean: '아이돌', english: 'Idol', pronunciation: 'a-i-dol', example: '내가 좋아하는 아이돌이야.', exampleTranslation: 'This is the idol I like.' },
    { korean: '노래', english: 'Song', pronunciation: 'no-rae', example: '이 노래 너무 좋아!', exampleTranslation: 'I love this song!' },
    { korean: '춤', english: 'Dance', pronunciation: 'chum', example: '춤을 정말 잘 춰.', exampleTranslation: 'They dance really well.' },
    { korean: '팬', english: 'Fan', pronunciation: 'paen', example: '나는 열성적인 팬이야.', exampleTranslation: 'I am a passionate fan.' },
    { korean: '가수', english: 'Singer', pronunciation: 'ga-su', example: '좋아하는 가수가 누구야?', exampleTranslation: 'Who is your favorite singer?' },
    { korean: '그룹', english: 'Group', pronunciation: 'geu-rup', example: '이 그룹 진짜 대박이야.', exampleTranslation: 'This group is really amazing.' },
    { korean: '멤버', english: 'Member', pronunciation: 'mem-beo', example: '멤버가 몇 명이야?', exampleTranslation: 'How many members are there?' },
    { korean: '음악', english: 'Music', pronunciation: 'eum-ak', example: '케이팝 음악을 좋아해요.', exampleTranslation: 'I like K-Pop music.' },
    { korean: '무대', english: 'Stage', pronunciation: 'mu-dae', example: '무대가 정말 멋있었어.', exampleTranslation: 'The stage was really cool.' },
    { korean: '데뷔', english: 'Debut', pronunciation: 'de-bwi', example: '올해 데뷔했어요.', exampleTranslation: 'They debuted this year.' },
    { korean: '연습생', english: 'Trainee', pronunciation: 'yeon-seup-saeng', example: '연습생 기간이 길었대.', exampleTranslation: 'They say the trainee period was long.' },
    { korean: '뮤직비디오', english: 'Music video', pronunciation: 'myu-jik-bi-di-o', example: '뮤직비디오가 예술이야.', exampleTranslation: 'The music video is art.' },
    { korean: '팬클럽', english: 'Fan club', pronunciation: 'paen-keul-leop', example: '팬클럽에 가입했어.', exampleTranslation: 'I joined the fan club.' },
    { korean: '응원', english: 'Cheering / Support', pronunciation: 'eung-won', example: '항상 응원할게!', exampleTranslation: 'I will always cheer for you!' },
    { korean: '사인', english: 'Autograph', pronunciation: 'sa-in', example: '사인 받고 싶어!', exampleTranslation: 'I want to get an autograph!' },
    { korean: '포스터', english: 'Poster', pronunciation: 'po-seu-teo', example: '방에 포스터 붙였어.', exampleTranslation: 'I put up a poster in my room.' },
    { korean: '영상', english: 'Video', pronunciation: 'yeong-sang', example: '이 영상 봤어?', exampleTranslation: 'Did you watch this video?' },
    { korean: '사진', english: 'Photo', pronunciation: 'sa-jin', example: '사진이 너무 예뻐!', exampleTranslation: 'The photo is so pretty!' },
    { korean: '목소리', english: 'Voice', pronunciation: 'mok-so-ri', example: '목소리가 정말 좋아.', exampleTranslation: 'The voice is really nice.' },
    { korean: '보컬', english: 'Vocal', pronunciation: 'bo-keol', example: '보컬이 대단해.', exampleTranslation: 'The vocals are amazing.' },
    { korean: '래퍼', english: 'Rapper', pronunciation: 'rae-peo', example: '래퍼 파트가 좋았어.', exampleTranslation: 'The rapper part was good.' },
    { korean: '댄서', english: 'Dancer', pronunciation: 'daen-seo', example: '메인 댄서가 누구야?', exampleTranslation: 'Who is the main dancer?' },
    { korean: '리더', english: 'Leader', pronunciation: 'ri-deo', example: '리더가 멘트를 잘해.', exampleTranslation: 'The leader gives good speeches.' },
    { korean: '센터', english: 'Center', pronunciation: 'sen-teo', example: '이번 곡 센터는 누구야?', exampleTranslation: 'Who is the center for this song?' },
    { korean: '막내', english: 'Youngest member', pronunciation: 'mak-nae', example: '막내가 귀여워.', exampleTranslation: 'The youngest member is cute.' },
    { korean: '귀엽다', english: 'Cute', pronunciation: 'gwi-yeop-da', example: '아, 진짜 귀엽다!', exampleTranslation: 'Ah, so cute!' },
    { korean: '멋있다', english: 'Cool / Handsome', pronunciation: 'meot-it-da', example: '무대에서 정말 멋있다!', exampleTranslation: 'So cool on stage!' },
    { korean: '예쁘다', english: 'Pretty', pronunciation: 'ye-ppeu-da', example: '오늘 정말 예쁘다!', exampleTranslation: 'So pretty today!' },
    { korean: '잘생기다', english: 'Handsome', pronunciation: 'jal-saeng-gi-da', example: '와, 진짜 잘생겼다.', exampleTranslation: 'Wow, really handsome.' },
    { korean: '좋아하다', english: 'To like', pronunciation: 'jo-a-ha-da', example: '이 그룹 정말 좋아해.', exampleTranslation: 'I really like this group.' },
    { korean: '듣다', english: 'To listen', pronunciation: 'deut-da', example: '매일 노래 듣고 있어.', exampleTranslation: 'I listen to their songs every day.' },
    { korean: '보다', english: 'To watch / see', pronunciation: 'bo-da', example: '무대 영상 보고 있어.', exampleTranslation: 'I\'m watching stage videos.' },
    { korean: '따라하다', english: 'To follow / imitate', pronunciation: 'tta-ra-ha-da', example: '안무 따라하고 있어.', exampleTranslation: 'I\'m following the choreography.' },
    { korean: '응원하다', english: 'To cheer for', pronunciation: 'eung-won-ha-da', example: '끝까지 응원할게.', exampleTranslation: 'I will cheer for you until the end.' },
    { korean: '사랑하다', english: 'To love', pronunciation: 'sa-rang-ha-da', example: '팬들을 사랑해요.', exampleTranslation: 'I love the fans.' },
    { korean: '기다리다', english: 'To wait', pronunciation: 'gi-da-ri-da', example: '컴백을 기다리고 있어.', exampleTranslation: 'I\'m waiting for the comeback.' },
    { korean: '재생', english: 'Play (music)', pronunciation: 'jae-saeng', example: '노래 재생해 줘.', exampleTranslation: 'Play the song for me.' },
    { korean: '가사', english: 'Lyrics', pronunciation: 'ga-sa', example: '가사가 정말 감동적이야.', exampleTranslation: 'The lyrics are really touching.' },
    { korean: '제목', english: 'Title', pronunciation: 'je-mok', example: '이 노래 제목이 뭐야?', exampleTranslation: 'What is the title of this song?' },
    { korean: '신곡', english: 'New song', pronunciation: 'sin-gok', example: '신곡 들어 봤어?', exampleTranslation: 'Have you listened to the new song?' },
    { korean: '인기', english: 'Popularity', pronunciation: 'in-gi', example: '요즘 인기가 엄청나.', exampleTranslation: 'Their popularity is incredible these days.' },
    { korean: '무료', english: 'Free', pronunciation: 'mu-ryo', example: '이 콘텐츠는 무료야.', exampleTranslation: 'This content is free.' },
    { korean: '연예인', english: 'Celebrity', pronunciation: 'yeon-ye-in', example: '좋아하는 연예인 있어?', exampleTranslation: 'Do you have a favorite celebrity?' },
    { korean: '오빠', english: 'Oppa (older brother/male idol)', pronunciation: 'o-ppa', example: '오빠, 사랑해요!', exampleTranslation: 'Oppa, I love you!' },
    { korean: '언니', english: 'Unnie (older sister/female idol)', pronunciation: 'eon-ni', example: '언니 너무 예뻐요!', exampleTranslation: 'Unnie, you\'re so pretty!' },
    { korean: '형', english: 'Hyung (older brother from a male)', pronunciation: 'hyeong', example: '형, 같이 노래하자.', exampleTranslation: 'Hyung, let\'s sing together.' },
    { korean: '누나', english: 'Noona (older sister from a male)', pronunciation: 'nu-na', example: '누나가 춤을 잘 춰.', exampleTranslation: 'Noona dances well.' },
    { korean: '대박', english: 'Amazing / Jackpot', pronunciation: 'dae-bak', example: '이번 무대 대박이다!', exampleTranslation: 'This stage is amazing!' },
    { korean: '진짜', english: 'Really / For real', pronunciation: 'jin-jja', example: '진짜 잘한다!', exampleTranslation: 'They\'re really good!' },
    { korean: '최고', english: 'The best', pronunciation: 'choe-go', example: '우리 그룹이 최고야!', exampleTranslation: 'Our group is the best!' },
    { korean: '화이팅', english: 'Fighting! (cheer)', pronunciation: 'hwa-i-ting', example: '오늘 공연도 화이팅!', exampleTranslation: 'Fighting for today\'s performance too!' },
    { korean: '감동', english: 'Emotion / Touched', pronunciation: 'gam-dong', example: '공연 보고 감동받았어.', exampleTranslation: 'I was moved by the performance.' },
    { korean: '행복', english: 'Happiness', pronunciation: 'haeng-bok', example: '덕질이 나의 행복이야.', exampleTranslation: 'Fangirling is my happiness.' },
    { korean: '소원', english: 'Wish', pronunciation: 'so-won', example: '콘서트 가는 게 소원이야.', exampleTranslation: 'Going to a concert is my wish.' },
    { korean: '선물', english: 'Gift / Present', pronunciation: 'seon-mul', example: '팬들에게 선물 받았대.', exampleTranslation: 'They received gifts from fans.' },
    { korean: '생일', english: 'Birthday', pronunciation: 'saeng-il', example: '오늘 최애 생일이야!', exampleTranslation: 'Today is my bias\'s birthday!' },
    { korean: '축하', english: 'Congratulations', pronunciation: 'chuk-ha', example: '1위 축하해요!', exampleTranslation: 'Congratulations on first place!' },
    { korean: '함께', english: 'Together', pronunciation: 'ham-kke', example: '팬들과 함께 해요.', exampleTranslation: 'Let\'s be together with fans.' },
    { korean: '오늘', english: 'Today', pronunciation: 'o-neul', example: '오늘 무대가 있어!', exampleTranslation: 'There\'s a stage performance today!' },
    { korean: '내일', english: 'Tomorrow', pronunciation: 'nae-il', example: '내일 앨범 나와!', exampleTranslation: 'The album comes out tomorrow!' },
    { korean: '매일', english: 'Every day', pronunciation: 'mae-il', example: '매일 노래 듣고 있어.', exampleTranslation: 'I listen to their songs every day.' },
    { korean: '처음', english: 'First time', pronunciation: 'cheo-eum', example: '처음으로 콘서트에 갔어.', exampleTranslation: 'I went to a concert for the first time.' },
    { korean: '다시', english: 'Again', pronunciation: 'da-si', example: '다시 한번 들어 볼래.', exampleTranslation: 'I want to listen again.' },
    { korean: '같이', english: 'Together / With', pronunciation: 'ga-chi', example: '같이 콘서트 갈래?', exampleTranslation: 'Do you want to go to the concert together?' },
    { korean: '많이', english: 'A lot', pronunciation: 'man-i', example: '많이 사랑해 주세요.', exampleTranslation: 'Please love us a lot.' },
    { korean: '너무', english: 'So / Too much', pronunciation: 'neo-mu', example: '너무 좋아서 울었어.', exampleTranslation: 'I cried because I liked it so much.' },
    { korean: '정말', english: 'Really / Truly', pronunciation: 'jeong-mal', example: '정말 멋있었어!', exampleTranslation: 'It was really cool!' },
    { korean: '빨리', english: 'Quickly / Hurry', pronunciation: 'ppal-li', example: '빨리 컴백해 줘!', exampleTranslation: 'Please come back quickly!' },
    { korean: '잘하다', english: 'To do well', pronunciation: 'jal-ha-da', example: '노래를 정말 잘한다.', exampleTranslation: 'They sing really well.' },
    { korean: '부르다', english: 'To sing / call', pronunciation: 'bu-reu-da', example: '이 노래를 불러 줘.', exampleTranslation: 'Sing this song for me.' },
    { korean: '연습', english: 'Practice', pronunciation: 'yeon-seup', example: '매일 연습해요.', exampleTranslation: 'They practice every day.' },
    { korean: '공연', english: 'Performance / Show', pronunciation: 'gong-yeon', example: '공연이 곧 시작해!', exampleTranslation: 'The performance is about to start!' },
    { korean: '음반', english: 'Music record / Album', pronunciation: 'eum-ban', example: '음반 판매량이 높아.', exampleTranslation: 'Album sales are high.' },
    { korean: '차트', english: 'Chart', pronunciation: 'cha-teu', example: '차트 1위 했어!', exampleTranslation: 'They got number 1 on the chart!' },
    { korean: '순위', english: 'Ranking', pronunciation: 'sun-wi', example: '순위가 올라갔어!', exampleTranslation: 'The ranking went up!' },
    { korean: '투표', english: 'Voting', pronunciation: 'tu-pyo', example: '투표 잊지 마세요!', exampleTranslation: 'Don\'t forget to vote!' },
    { korean: '우승', english: 'Win / Victory', pronunciation: 'u-seung', example: '오늘 우승할 수 있어!', exampleTranslation: 'We can win today!' },
    { korean: '소속사', english: 'Entertainment agency', pronunciation: 'so-sok-sa', example: '어느 소속사야?', exampleTranslation: 'Which agency are they under?' },
    { korean: '활동', english: 'Activities / Promotions', pronunciation: 'hwal-dong', example: '이번 활동 기대돼!', exampleTranslation: 'I\'m looking forward to these promotions!' },
    { korean: '방송', english: 'Broadcast', pronunciation: 'bang-song', example: '오늘 방송 나와!', exampleTranslation: 'They\'re on a broadcast today!' },
    { korean: '잠깐', english: 'A moment', pronunciation: 'jam-kkan', example: '잠깐, 이거 봐!', exampleTranslation: 'Wait, look at this!' },
    { korean: '미소', english: 'Smile', pronunciation: 'mi-so', example: '미소가 너무 예뻐.', exampleTranslation: 'The smile is so pretty.' },
    { korean: '눈물', english: 'Tears', pronunciation: 'nun-mul', example: '감동의 눈물이 났어.', exampleTranslation: 'Tears of emotion came out.' },
    { korean: '무지개', english: 'Rainbow', pronunciation: 'mu-ji-gae', example: '응원봉 무지개 바다야!', exampleTranslation: 'It\'s a rainbow ocean of lightsticks!' },
    { korean: '꿈', english: 'Dream', pronunciation: 'kkum', example: '콘서트 가는 게 꿈이야.', exampleTranslation: 'Going to a concert is my dream.' },
    { korean: '약속', english: 'Promise', pronunciation: 'yak-sok', example: '팬들과의 약속이에요.', exampleTranslation: 'It\'s a promise with the fans.' },
    { korean: '고마워', english: 'Thank you (informal)', pronunciation: 'go-ma-wo', example: '항상 고마워요!', exampleTranslation: 'Thank you always!' },
    { korean: '보고 싶다', english: 'I miss you', pronunciation: 'bo-go sip-da', example: '보고 싶어요, 빨리 돌아와!', exampleTranslation: 'I miss you, come back soon!' },
    { korean: '기쁘다', english: 'Happy / Glad', pronunciation: 'gi-ppeu-da', example: '1위 해서 기쁘다!', exampleTranslation: 'Happy that they got first place!' },
    { korean: '놀라다', english: 'To be surprised', pronunciation: 'nol-la-da', example: '갑자기 컴백해서 놀랐어!', exampleTranslation: 'I was surprised by the sudden comeback!' },
    { korean: '힘내다', english: 'To cheer up / push through', pronunciation: 'him-nae-da', example: '힘내! 우리가 응원할게.', exampleTranslation: 'Cheer up! We\'ll support you.' },
    { korean: '소리', english: 'Sound', pronunciation: 'so-ri', example: '팬들 소리가 엄청나.', exampleTranslation: 'The fans\' cheers are incredible.' },
    { korean: '마이크', english: 'Microphone', pronunciation: 'ma-i-keu', example: '라이브 마이크인데 잘한다.', exampleTranslation: 'They sing well even with a live mic.' },
    { korean: '유튜브', english: 'YouTube', pronunciation: 'yu-tyu-beu', example: '유튜브에서 뮤비 봤어.', exampleTranslation: 'I watched the MV on YouTube.' },
    { korean: '댓글', english: 'Comment', pronunciation: 'daet-geul', example: '댓글 많이 달아 줘!', exampleTranslation: 'Please leave lots of comments!' },
    { korean: '조회수', english: 'View count', pronunciation: 'jo-hoe-su', example: '조회수가 1억이야!', exampleTranslation: 'The view count is 100 million!' },
  ],
  2: [
    { korean: '팬챈트', english: 'Fanchant', pronunciation: 'paen-chaen-teu', example: '팬챈트 연습했어요.', exampleTranslation: 'I practiced the fanchant.' },
    { korean: '응원봉', english: 'Lightstick', pronunciation: 'eung-won-bong', example: '응원봉 색깔이 예뻐요.', exampleTranslation: 'The lightstick color is pretty.' },
    { korean: '뮤비', english: 'MV (Music Video)', pronunciation: 'myu-bi', example: '뮤비 조회수 1억 돌파!', exampleTranslation: 'MV surpassed 100 million views!' },
    { korean: '스밍', english: 'Streaming', pronunciation: 'seu-ming', example: '스밍 열심히 하자!', exampleTranslation: 'Let\'s stream hard!' },
    { korean: '음방', english: 'Music show', pronunciation: 'eum-bang', example: '오늘 음방 출연이래요.', exampleTranslation: 'They\'re appearing on the music show today.' },
    { korean: '안무', english: 'Choreography', pronunciation: 'an-mu', example: '이번 안무가 어렵대요.', exampleTranslation: 'They say this choreography is hard.' },
    { korean: '입덕', english: 'Becoming a fan', pronunciation: 'ip-deok', example: '이 영상 보고 입덕했어.', exampleTranslation: 'I became a fan after watching this.' },
    { korean: '덕질', english: 'Fan activities / Fangirling', pronunciation: 'deok-jil', example: '덕질이 행복해요.', exampleTranslation: 'Fan activities make me happy.' },
    { korean: '직캠', english: 'Fancam', pronunciation: 'jik-kaem', example: '직캠 조회수가 대박이야.', exampleTranslation: 'The fancam views are amazing.' },
    { korean: '팬싸', english: 'Fan signing event', pronunciation: 'paen-ssa', example: '팬싸에 당첨됐어!', exampleTranslation: 'I won the fan signing lottery!' },
    { korean: '포카', english: 'Photocard', pronunciation: 'po-ka', example: '포카 교환할 사람?', exampleTranslation: 'Anyone want to trade photocards?' },
    { korean: '총공', english: 'Mass streaming', pronunciation: 'chong-gong', example: '총공 시간이에요!', exampleTranslation: 'It\'s time for mass streaming!' },
    { korean: '음원', english: 'Digital music track', pronunciation: 'eum-won', example: '음원이 자정에 나와요.', exampleTranslation: 'The digital track drops at midnight.' },
    { korean: '떡밥', english: 'Teaser hint / Bait', pronunciation: 'tteok-bap', example: '떡밥이 나왔다!', exampleTranslation: 'A teaser hint dropped!' },
    { korean: '셀카', english: 'Selfie', pronunciation: 'sel-ka', example: '셀카 올려 줘요!', exampleTranslation: 'Please post a selfie!' },
    { korean: '비하인드', english: 'Behind-the-scenes', pronunciation: 'bi-ha-in-deu', example: '비하인드 영상 봤어?', exampleTranslation: 'Did you see the behind-the-scenes video?' },
    { korean: '티저', english: 'Teaser', pronunciation: 'ti-jeo', example: '티저 사진 공개됐어!', exampleTranslation: 'The teaser photo was released!' },
    { korean: '브이로그', english: 'Vlog', pronunciation: 'beu-i-ro-geu', example: '새 브이로그 올라왔다.', exampleTranslation: 'A new vlog was uploaded.' },
    { korean: '위버스', english: 'Weverse (fan platform)', pronunciation: 'wi-beo-seu', example: '위버스에 글 올렸어요.', exampleTranslation: 'They posted on Weverse.' },
    { korean: '해시태그', english: 'Hashtag', pronunciation: 'hae-si-tae-geu', example: '해시태그 달아 주세요.', exampleTranslation: 'Please add the hashtag.' },
    { korean: '탈덕', english: 'Leaving a fandom', pronunciation: 'tal-deok', example: '탈덕하려다 못 했어.', exampleTranslation: 'I tried to leave the fandom but couldn\'t.' },
    { korean: '성덕', english: 'Successful fan (met idol)', pronunciation: 'seong-deok', example: '드디어 성덕했어!', exampleTranslation: 'I finally became a successful fan!' },
    { korean: '커버댄스', english: 'Cover dance', pronunciation: 'keo-beo-daen-seu', example: '커버댄스 영상 올렸어.', exampleTranslation: 'I uploaded a cover dance video.' },
    { korean: '예능', english: 'Variety show', pronunciation: 'ye-neung', example: '예능에 나왔어요!', exampleTranslation: 'They appeared on a variety show!' },
    { korean: '떼창', english: 'Group sing-along', pronunciation: 'tte-chang', example: '떼창이 소름 돋았어.', exampleTranslation: 'The group sing-along gave me chills.' },
    { korean: '막방', english: 'Last broadcast stage', pronunciation: 'mak-bang', example: '오늘이 막방이에요.', exampleTranslation: 'Today is the last broadcast.' },
    { korean: '본방사수', english: 'Watch the live broadcast', pronunciation: 'bon-bang-sa-su', example: '본방사수 해야 돼!', exampleTranslation: 'We have to watch the live broadcast!' },
    { korean: '개인기', english: 'Special talent', pronunciation: 'gae-in-gi', example: '개인기가 너무 웃겨.', exampleTranslation: 'Their special talent is so funny.' },
    { korean: '올라운더', english: 'All-rounder', pronunciation: 'ol-la-un-deo', example: '진짜 올라운더야.', exampleTranslation: 'A true all-rounder.' },
    { korean: '멜론', english: 'Melon (music chart/app)', pronunciation: 'mel-lon', example: '멜론 차트 1위!', exampleTranslation: 'Number 1 on Melon chart!' },
    { korean: '팬덤', english: 'Fandom', pronunciation: 'paen-deom', example: '팬덤이 정말 커.', exampleTranslation: 'The fandom is really big.' },
    { korean: '덕후', english: 'Hardcore fan / Otaku', pronunciation: 'deok-hu', example: '나는 완전 덕후야.', exampleTranslation: 'I am a total hardcore fan.' },
    { korean: '갤러리', english: 'Gallery (fan community)', pronunciation: 'gael-leo-ri', example: '갤러리에 사진 올렸어.', exampleTranslation: 'I posted a photo on the gallery.' },
    { korean: '굿즈', english: 'Goods / Merchandise', pronunciation: 'gut-jeu', example: '새 굿즈가 나왔어!', exampleTranslation: 'New merchandise came out!' },
    { korean: '솔로', english: 'Solo', pronunciation: 'sol-lo', example: '솔로 앨범 냈어요.', exampleTranslation: 'They released a solo album.' },
    { korean: '유닛', english: 'Unit (subgroup)', pronunciation: 'yu-nit', example: '유닛 활동 시작했어.', exampleTranslation: 'Unit activities have started.' },
    { korean: '피처링', english: 'Featuring', pronunciation: 'pi-cheo-ring', example: '피처링 조합이 좋아.', exampleTranslation: 'The featuring combination is great.' },
    { korean: '타이틀곡', english: 'Title track', pronunciation: 'ta-i-teul-gok', example: '타이틀곡이 중독성 있어.', exampleTranslation: 'The title track is addictive.' },
    { korean: '수록곡', english: 'B-side track', pronunciation: 'su-rok-gok', example: '수록곡도 다 좋아.', exampleTranslation: 'The B-side tracks are all good too.' },
    { korean: '음원 사재기', english: 'Chart manipulation', pronunciation: 'eum-won sa-jae-gi', example: '음원 사재기 의혹이 있어.', exampleTranslation: 'There are suspicions of chart manipulation.' },
    { korean: '역주행', english: 'Reverse charting (belated hit)', pronunciation: 'yeok-ju-haeng', example: '역주행으로 1위 했어!', exampleTranslation: 'They got number 1 through reverse charting!' },
    { korean: '올킬', english: 'All-kill (top all charts)', pronunciation: 'ol-kil', example: '실시간 올킬 달성!', exampleTranslation: 'Achieved a real-time all-kill!' },
    { korean: '프리뷰', english: 'Preview', pronunciation: 'peu-ri-byu', example: '앨범 프리뷰 들어 봤어?', exampleTranslation: 'Did you listen to the album preview?' },
    { korean: '하이라이트', english: 'Highlight medley', pronunciation: 'ha-i-ra-i-teu', example: '하이라이트 메들리 공개됐어.', exampleTranslation: 'The highlight medley was released.' },
    { korean: '트레일러', english: 'Trailer', pronunciation: 'teu-re-il-leo', example: '컴백 트레일러 봤어?', exampleTranslation: 'Did you watch the comeback trailer?' },
    { korean: '콘셉트', english: 'Concept', pronunciation: 'kon-sep-teu', example: '이번 콘셉트가 뭐야?', exampleTranslation: 'What is the concept this time?' },
    { korean: '스포일러', english: 'Spoiler', pronunciation: 'seu-po-il-leo', example: '또 스포일러 했어!', exampleTranslation: 'They spoiled it again!' },
    { korean: '일정', english: 'Schedule', pronunciation: 'il-jeong', example: '오늘 일정이 빡빡해.', exampleTranslation: 'Today\'s schedule is packed.' },
    { korean: '공항 패션', english: 'Airport fashion', pronunciation: 'gong-hang pae-syeon', example: '공항 패션이 화제야.', exampleTranslation: 'The airport fashion is a hot topic.' },
    { korean: '출국', english: 'Departure (leaving country)', pronunciation: 'chul-guk', example: '내일 출국이래요.', exampleTranslation: 'They\'re departing the country tomorrow.' },
    { korean: '입국', english: 'Arrival (entering country)', pronunciation: 'ip-guk', example: '오늘 입국해요!', exampleTranslation: 'They arrive in the country today!' },
    { korean: '팬미팅', english: 'Fan meeting', pronunciation: 'paen-mi-ting', example: '팬미팅 티켓 있어?', exampleTranslation: 'Do you have fan meeting tickets?' },
    { korean: '생방송', english: 'Live broadcast', pronunciation: 'saeng-bang-song', example: '지금 생방송 하고 있어!', exampleTranslation: 'They\'re doing a live broadcast now!' },
    { korean: '연습 영상', english: 'Practice video', pronunciation: 'yeon-seup yeong-sang', example: '안무 연습 영상 나왔어.', exampleTranslation: 'The dance practice video came out.' },
    { korean: '릴레이 댄스', english: 'Relay dance', pronunciation: 'ril-le-i daen-seu', example: '릴레이 댄스 귀여워!', exampleTranslation: 'The relay dance is cute!' },
    { korean: '챌린지', english: 'Challenge (dance/viral)', pronunciation: 'chael-lin-ji', example: '챌린지 영상 찍었어.', exampleTranslation: 'I filmed a challenge video.' },
    { korean: '쇼츠', english: 'Shorts (short video)', pronunciation: 'syo-cheu', example: '쇼츠로 바이럴 됐어.', exampleTranslation: 'It went viral through Shorts.' },
    { korean: '라이브', english: 'Live (streaming)', pronunciation: 'ra-i-beu', example: '라이브 켰어요!', exampleTranslation: 'They started a live stream!' },
    { korean: '실시간', english: 'Real-time', pronunciation: 'sil-si-gan', example: '실시간 트렌드 1위!', exampleTranslation: 'Number 1 in real-time trends!' },
    { korean: '스트리밍', english: 'Streaming', pronunciation: 'seu-teu-ri-ming', example: '스트리밍 열심히 해요.', exampleTranslation: 'Let\'s stream diligently.' },
    { korean: '다운로드', english: 'Download', pronunciation: 'da-un-ro-deu', example: '음원 다운로드 했어.', exampleTranslation: 'I downloaded the music track.' },
    { korean: '구독', english: 'Subscribe', pronunciation: 'gu-dok', example: '채널 구독 해 주세요.', exampleTranslation: 'Please subscribe to the channel.' },
    { korean: '알림', english: 'Notification', pronunciation: 'al-lim', example: '알림 설정 해 놨어.', exampleTranslation: 'I set up notifications.' },
    { korean: '트위터', english: 'Twitter / X', pronunciation: 'teu-wi-teo', example: '트위터에서 화제야.', exampleTranslation: 'It\'s a hot topic on Twitter.' },
    { korean: '인스타그램', english: 'Instagram', pronunciation: 'in-seu-ta-geu-raem', example: '인스타에 사진 올렸어.', exampleTranslation: 'They posted a photo on Instagram.' },
    { korean: '틱톡', english: 'TikTok', pronunciation: 'tik-tok', example: '틱톡 챌린지 유행이야.', exampleTranslation: 'The TikTok challenge is trending.' },
    { korean: '좋아요', english: 'Like (button)', pronunciation: 'jo-a-yo', example: '좋아요 많이 눌러 줘!', exampleTranslation: 'Please press like a lot!' },
    { korean: '리트윗', english: 'Retweet', pronunciation: 'ri-teu-wit', example: '리트윗 부탁해요.', exampleTranslation: 'Please retweet.' },
    { korean: '공유', english: 'Share', pronunciation: 'gong-yu', example: '링크 공유해 줘.', exampleTranslation: 'Share the link.' },
    { korean: '트렌드', english: 'Trend', pronunciation: 'teu-ren-deu', example: '전 세계 트렌드 1위!', exampleTranslation: 'Number 1 trending worldwide!' },
    { korean: '해외 팬', english: 'International fan', pronunciation: 'hae-oe paen', example: '해외 팬이 많아졌어.', exampleTranslation: 'International fans have increased.' },
    { korean: '팬아트', english: 'Fan art', pronunciation: 'paen-a-teu', example: '팬아트 그렸어요.', exampleTranslation: 'I drew fan art.' },
    { korean: '팬픽', english: 'Fan fiction', pronunciation: 'paen-pik', example: '팬픽 읽는 게 재밌어.', exampleTranslation: 'Reading fan fiction is fun.' },
    { korean: '언박싱', english: 'Unboxing', pronunciation: 'eon-bak-sing', example: '앨범 언박싱 영상이야.', exampleTranslation: 'It\'s an album unboxing video.' },
    { korean: '포토북', english: 'Photobook', pronunciation: 'po-to-buk', example: '포토북 화보가 예뻐.', exampleTranslation: 'The photobook pictorial is pretty.' },
    { korean: '시상식', english: 'Awards ceremony', pronunciation: 'si-sang-sik', example: '시상식에서 수상했어!', exampleTranslation: 'They won at the awards ceremony!' },
    { korean: '신인상', english: 'Rookie award', pronunciation: 'sin-in-sang', example: '신인상 받았어요!', exampleTranslation: 'They received the rookie award!' },
    { korean: '대상', english: 'Grand prize / Daesang', pronunciation: 'dae-sang', example: '대상 축하해요!', exampleTranslation: 'Congratulations on the grand prize!' },
    { korean: '본상', english: 'Main prize / Bonsang', pronunciation: 'bon-sang', example: '본상도 대단해.', exampleTranslation: 'The main prize is also great.' },
    { korean: '레드카펫', english: 'Red carpet', pronunciation: 're-deu-ka-pet', example: '레드카펫 의상이 멋져!', exampleTranslation: 'The red carpet outfit is gorgeous!' },
    { korean: '수상 소감', english: 'Award acceptance speech', pronunciation: 'su-sang so-gam', example: '수상 소감에서 울었어.', exampleTranslation: 'They cried during the acceptance speech.' },
    { korean: '콜라보', english: 'Collaboration', pronunciation: 'kol-la-bo', example: '콜라보 소식이야!', exampleTranslation: 'It\'s collaboration news!' },
    { korean: '기대하다', english: 'To look forward to', pronunciation: 'gi-dae-ha-da', example: '컴백 너무 기대돼!', exampleTranslation: 'I\'m so looking forward to the comeback!' },
    { korean: '감사하다', english: 'To be grateful', pronunciation: 'gam-sa-ha-da', example: '팬들에게 항상 감사해요.', exampleTranslation: 'I\'m always grateful to the fans.' },
    { korean: '자랑스럽다', english: 'To be proud', pronunciation: 'ja-rang-seu-reop-da', example: '우리 아이돌이 자랑스러워!', exampleTranslation: 'I\'m proud of our idol!' },
    { korean: '설레다', english: 'To be excited / thrilled', pronunciation: 'seol-le-da', example: '콘서트 생각에 설레.', exampleTranslation: 'I\'m thrilled thinking about the concert.' },
    { korean: '중독되다', english: 'To be addicted', pronunciation: 'jung-dok-doe-da', example: '이 노래에 중독됐어.', exampleTranslation: 'I\'m addicted to this song.' },
    { korean: '들리다', english: 'To be heard', pronunciation: 'deul-li-da', example: '팬챈트가 잘 들려!', exampleTranslation: 'The fanchant can be heard clearly!' },
    { korean: '빠지다', english: 'To fall into / get hooked', pronunciation: 'ppa-ji-da', example: '이 그룹에 완전 빠졌어.', exampleTranslation: 'I\'m completely hooked on this group.' },
    { korean: '뿌듯하다', english: 'To feel proud', pronunciation: 'ppu-deut-ha-da', example: '성장한 모습이 뿌듯해.', exampleTranslation: 'I feel proud seeing them grow.' },
    { korean: '울컥하다', english: 'To get choked up', pronunciation: 'ul-keok-ha-da', example: '수상 소감 듣고 울컥했어.', exampleTranslation: 'I got choked up listening to the acceptance speech.' },
    { korean: '소름 돋다', english: 'To get goosebumps', pronunciation: 'so-reum dot-da', example: '고음 듣고 소름 돋았어.', exampleTranslation: 'I got goosebumps hearing the high note.' },
    { korean: '힐링', english: 'Healing', pronunciation: 'hil-ling', example: '이 노래가 힐링이야.', exampleTranslation: 'This song is healing.' },
    { korean: '케미', english: 'Chemistry', pronunciation: 'ke-mi', example: '멤버들 케미가 좋아.', exampleTranslation: 'The members have good chemistry.' },
    { korean: '비주얼', english: 'Visual (looks)', pronunciation: 'bi-ju-eol', example: '비주얼이 미쳤어.', exampleTranslation: 'The visual is insane.' },
    { korean: '멘트', english: 'Comment / Speech (on stage)', pronunciation: 'men-teu', example: '멘트가 감동이었어.', exampleTranslation: 'The speech was touching.' },
    { korean: '고음', english: 'High note', pronunciation: 'go-eum', example: '고음 파트가 대박!', exampleTranslation: 'The high note part is incredible!' },
    { korean: '저음', english: 'Low note / Bass', pronunciation: 'jeo-eum', example: '저음이 매력적이야.', exampleTranslation: 'The low notes are charming.' },
    { korean: '랩', english: 'Rap', pronunciation: 'raep', example: '랩 파트가 불 뿜어.', exampleTranslation: 'The rap part is fire.' },
    { korean: '떡상하다', english: 'To surge in popularity', pronunciation: 'tteok-sang-ha-da', example: '이 직캠으로 떡상했어.', exampleTranslation: 'They surged in popularity with this fancam.' },
  ],
  3: [
    { korean: '인기가요', english: 'Inkigayo (SBS music show)', pronunciation: 'in-gi-ga-yo', example: '인기가요 출연 확정!', exampleTranslation: 'Confirmed appearance on Inkigayo!' },
    { korean: '뮤직뱅크', english: 'Music Bank (KBS music show)', pronunciation: 'myu-jik-baeng-keu', example: '뮤직뱅크 1위 후보야.', exampleTranslation: 'They\'re candidates for first on Music Bank.' },
    { korean: '엠카운트다운', english: 'M Countdown (Mnet music show)', pronunciation: 'em-ka-un-teu-da-un', example: '엠카운트다운 무대가 좋았어.', exampleTranslation: 'The M Countdown stage was great.' },
    { korean: '쇼 음악중심', english: 'Show! Music Core (MBC)', pronunciation: 'syo eum-ak-jung-sim', example: '음악중심에서 1위 했어!', exampleTranslation: 'They won first on Music Core!' },
    { korean: '더쇼', english: 'The Show (SBS MTV)', pronunciation: 'deo-syo', example: '더쇼에서 첫 1위 했어!', exampleTranslation: 'They got their first win on The Show!' },
    { korean: '쇼챔피언', english: 'Show Champion', pronunciation: 'syo-chaem-pi-eon', example: '쇼챔피언 방청 갔어.', exampleTranslation: 'I went to the Show Champion recording.' },
    { korean: '팬카페', english: 'Fan cafe (online community)', pronunciation: 'paen-ka-pe', example: '팬카페 등업 했어.', exampleTranslation: 'I leveled up on the fan cafe.' },
    { korean: '등급', english: 'Level / Grade (fan cafe)', pronunciation: 'deung-geup', example: '최고 등급으로 올라갔어.', exampleTranslation: 'I reached the highest level.' },
    { korean: '생카', english: 'Birthday cafe event', pronunciation: 'saeng-ka', example: '생카 이벤트 어디야?', exampleTranslation: 'Where is the birthday cafe event?' },
    { korean: '조공', english: 'Fan tribute gift', pronunciation: 'jo-gong', example: '조공으로 간식차 보냈어.', exampleTranslation: 'I sent a snack truck as a tribute.' },
    { korean: '간식차', english: 'Snack truck (fan gift)', pronunciation: 'gan-sik-cha', example: '촬영장에 간식차 보냈어.', exampleTranslation: 'We sent a snack truck to the filming set.' },
    { korean: '커피차', english: 'Coffee truck (fan gift)', pronunciation: 'keo-pi-cha', example: '팬들이 커피차 보내줬어.', exampleTranslation: 'Fans sent a coffee truck.' },
    { korean: '광고', english: 'Advertisement', pronunciation: 'gwang-go', example: '지하철 광고 봤어?', exampleTranslation: 'Did you see the subway advertisement?' },
    { korean: '전광판', english: 'Billboard / LED screen', pronunciation: 'jeon-gwang-pan', example: '생일 전광판 광고 올렸어.', exampleTranslation: 'We put up a birthday billboard ad.' },
    { korean: '센일', english: 'Birthday (fan term from 생일)', pronunciation: 'sen-il', example: '센일 축하해요!', exampleTranslation: 'Happy birthday!' },
    { korean: '버블', english: 'Bubble (messaging app)', pronunciation: 'beo-beul', example: '버블 메시지 왔어!', exampleTranslation: 'A Bubble message came!' },
    { korean: '블라인드', english: 'Blind (hidden post)', pronunciation: 'beul-la-in-deu', example: '블라인드 처리됐어.', exampleTranslation: 'The post was blinded/hidden.' },
    { korean: '뮤직어워드', english: 'Music award', pronunciation: 'myu-jik-eo-wo-deu', example: '뮤직어워드 시즌이야.', exampleTranslation: 'It\'s music award season.' },
    { korean: '연말 시상식', english: 'Year-end awards ceremony', pronunciation: 'yeon-mal si-sang-sik', example: '연말 시상식 기대돼!', exampleTranslation: 'Looking forward to year-end awards!' },
    { korean: '본선', english: 'Main round / Finals', pronunciation: 'bon-seon', example: '오디션 본선에 올라갔어.', exampleTranslation: 'They advanced to the main round of the audition.' },
    { korean: '오디션', english: 'Audition', pronunciation: 'o-di-syeon', example: '오디션 프로그램 봤어?', exampleTranslation: 'Did you watch the audition program?' },
    { korean: '서바이벌', english: 'Survival (show)', pronunciation: 'seo-ba-i-beol', example: '서바이벌 프로그램에서 데뷔했어.', exampleTranslation: 'They debuted from a survival program.' },
    { korean: '투어', english: 'Tour', pronunciation: 'tu-eo', example: '월드 투어 일정 나왔어!', exampleTranslation: 'The world tour schedule is out!' },
    { korean: '앵콜', english: 'Encore', pronunciation: 'aeng-kol', example: '앵콜 무대에서 울었어.', exampleTranslation: 'They cried during the encore stage.' },
    { korean: '리허설', english: 'Rehearsal', pronunciation: 'ri-heo-seol', example: '리허설 영상 유출됐어.', exampleTranslation: 'The rehearsal video leaked.' },
    { korean: '세트리스트', english: 'Setlist', pronunciation: 'se-teu-ri-seu-teu', example: '콘서트 세트리스트 궁금해.', exampleTranslation: 'I\'m curious about the concert setlist.' },
    { korean: '프로듀서', english: 'Producer', pronunciation: 'peu-ro-dyu-seo', example: '유명 프로듀서가 참여했어.', exampleTranslation: 'A famous producer participated.' },
    { korean: '작곡가', english: 'Composer / Songwriter', pronunciation: 'jak-gok-ga', example: '작곡가가 직접 만든 곡이야.', exampleTranslation: 'It\'s a song the composer made themselves.' },
    { korean: '작사가', english: 'Lyricist', pronunciation: 'jak-sa-ga', example: '가사를 직접 작사했어.', exampleTranslation: 'They wrote the lyrics themselves.' },
    { korean: '편곡', english: 'Arrangement', pronunciation: 'pyeon-gok', example: '편곡이 세련됐어.', exampleTranslation: 'The arrangement is sophisticated.' },
    { korean: '녹음', english: 'Recording', pronunciation: 'nok-eum', example: '녹음실에서 작업 중이야.', exampleTranslation: 'They\'re working in the recording studio.' },
    { korean: '안무가', english: 'Choreographer', pronunciation: 'an-mu-ga', example: '유명 안무가가 만든 안무야.', exampleTranslation: 'It\'s choreography made by a famous choreographer.' },
    { korean: '스타일리스트', english: 'Stylist', pronunciation: 'seu-ta-il-li-seu-teu', example: '스타일리스트 센스가 좋아.', exampleTranslation: 'The stylist has good sense.' },
    { korean: '메이크업', english: 'Makeup', pronunciation: 'me-i-keu-eop', example: '오늘 메이크업이 예술이야.', exampleTranslation: 'Today\'s makeup is art.' },
    { korean: '코디', english: 'Coordi (outfit coordinator)', pronunciation: 'ko-di', example: '코디 잘한다!', exampleTranslation: 'The outfits are well coordinated!' },
    { korean: '스케줄', english: 'Schedule', pronunciation: 'seu-ke-jul', example: '스케줄이 너무 바빠.', exampleTranslation: 'The schedule is too busy.' },
    { korean: '기획사', english: 'Entertainment company', pronunciation: 'gi-hoek-sa', example: '기획사에서 공지 났어.', exampleTranslation: 'The entertainment company made an announcement.' },
    { korean: '대형 기획사', english: 'Big entertainment company', pronunciation: 'dae-hyeong gi-hoek-sa', example: '대형 기획사 소속이야.', exampleTranslation: 'They belong to a big entertainment company.' },
    { korean: '매니저', english: 'Manager', pronunciation: 'mae-ni-jeo', example: '매니저가 같이 왔어.', exampleTranslation: 'The manager came along.' },
    { korean: '공식', english: 'Official', pronunciation: 'gong-sik', example: '공식 계정에서 발표했어.', exampleTranslation: 'The official account announced it.' },
    { korean: '비공식', english: 'Unofficial', pronunciation: 'bi-gong-sik', example: '비공식 팬 계정이야.', exampleTranslation: 'It\'s an unofficial fan account.' },
    { korean: '루머', english: 'Rumor', pronunciation: 'ru-meo', example: '루머에 속지 마세요.', exampleTranslation: 'Don\'t be fooled by rumors.' },
    { korean: '공지', english: 'Announcement / Notice', pronunciation: 'gong-ji', example: '공지 확인했어?', exampleTranslation: 'Did you check the announcement?' },
    { korean: '계정', english: 'Account', pronunciation: 'gye-jeong', example: '부계정으로 스밍해.', exampleTranslation: 'I stream with a secondary account.' },
    { korean: '부계정', english: 'Secondary account', pronunciation: 'bu-gye-jeong', example: '부계정 만들었어.', exampleTranslation: 'I made a secondary account.' },
    { korean: '본계정', english: 'Main account', pronunciation: 'bon-gye-jeong', example: '본계정에 올렸어.', exampleTranslation: 'I posted on my main account.' },
    { korean: '팔로우', english: 'Follow', pronunciation: 'pal-lo-u', example: '공식 계정 팔로우 해!', exampleTranslation: 'Follow the official account!' },
    { korean: '언팔', english: 'Unfollow', pronunciation: 'eon-pal', example: '언팔하지 마세요.', exampleTranslation: 'Please don\'t unfollow.' },
    { korean: '뮤트', english: 'Mute', pronunciation: 'myu-teu', example: '스포 계정 뮤트했어.', exampleTranslation: 'I muted the spoiler account.' },
    { korean: '차단', english: 'Block', pronunciation: 'cha-dan', example: '악플러 차단했어.', exampleTranslation: 'I blocked the hater.' },
    { korean: '악플', english: 'Malicious comment', pronunciation: 'ak-peul', example: '악플 쓰지 마세요.', exampleTranslation: 'Don\'t write malicious comments.' },
    { korean: '선플', english: 'Positive comment', pronunciation: 'seon-peul', example: '선플 많이 달아 주세요.', exampleTranslation: 'Please leave lots of positive comments.' },
    { korean: '홈마', english: 'Fansite master', pronunciation: 'hom-ma', example: '홈마 사진 퀄리티 대박.', exampleTranslation: 'The fansite master\'s photo quality is amazing.' },
    { korean: '마스터', english: 'Master (fansite owner)', pronunciation: 'ma-seu-teo', example: '마스터님 사진 공유해 주세요.', exampleTranslation: 'Master, please share the photos.' },
    { korean: '프리뷰 사진', english: 'Preview photo', pronunciation: 'peu-ri-byu sa-jin', example: '프리뷰 사진 올라왔어.', exampleTranslation: 'Preview photos were posted.' },
    { korean: '보정', english: 'Photo editing / Touch-up', pronunciation: 'bo-jeong', example: '보정 사진 기대돼.', exampleTranslation: 'Looking forward to the edited photos.' },
    { korean: '직찍', english: 'Direct photo (taken by fan)', pronunciation: 'jik-jjik', example: '직찍 사진 올렸어.', exampleTranslation: 'I posted a fan-taken photo.' },
    { korean: '영통', english: 'Video call (fan event)', pronunciation: 'yeong-tong', example: '영통 팬싸 당첨됐어!', exampleTranslation: 'I won the video call fan signing!' },
    { korean: '대기실', english: 'Waiting room / Green room', pronunciation: 'dae-gi-sil', example: '대기실 비하인드 봤어?', exampleTranslation: 'Did you see the waiting room behind-the-scenes?' },
    { korean: '응원법', english: 'Cheering guide', pronunciation: 'eung-won-beop', example: '응원법 외우고 있어.', exampleTranslation: 'I\'m memorizing the cheering guide.' },
    { korean: '떼창 영상', english: 'Group singing video', pronunciation: 'tte-chang yeong-sang', example: '떼창 영상 소름 돋아.', exampleTranslation: 'The group singing video gives goosebumps.' },
    { korean: '팬송', english: 'Fan song', pronunciation: 'paen-song', example: '팬송 가사가 감동이야.', exampleTranslation: 'The fan song lyrics are touching.' },
    { korean: '선공개', english: 'Pre-release', pronunciation: 'seon-gong-gae', example: '선공개 곡 들었어?', exampleTranslation: 'Did you hear the pre-release song?' },
    { korean: '후속곡', english: 'Follow-up song', pronunciation: 'hu-sok-gok', example: '후속곡 활동 시작했어.', exampleTranslation: 'Promotions for the follow-up song started.' },
    { korean: '더블 타이틀', english: 'Double title track', pronunciation: 'deo-beul ta-i-teul', example: '이번에 더블 타이틀이래.', exampleTranslation: 'It\'s a double title track this time.' },
    { korean: '미니앨범', english: 'Mini album / EP', pronunciation: 'mi-ni-ael-beom', example: '미니앨범으로 나왔어.', exampleTranslation: 'It was released as a mini album.' },
    { korean: '정규앨범', english: 'Full-length album', pronunciation: 'jeong-gyu-ael-beom', example: '드디어 정규앨범이야!', exampleTranslation: 'It\'s finally a full-length album!' },
    { korean: '리패키지', english: 'Repackage album', pronunciation: 'ri-pae-ki-ji', example: '리패키지 앨범 사야 해.', exampleTranslation: 'I need to buy the repackage album.' },
    { korean: '싱글', english: 'Single', pronunciation: 'sing-geul', example: '디지털 싱글 발매됐어.', exampleTranslation: 'A digital single was released.' },
    { korean: '컨셉트 포토', english: 'Concept photo', pronunciation: 'keon-sep-teu po-to', example: '컨셉트 포토 공개됐어!', exampleTranslation: 'The concept photos were revealed!' },
    { korean: '트랙리스트', english: 'Tracklist', pronunciation: 'teu-raek-ri-seu-teu', example: '트랙리스트 확인했어?', exampleTranslation: 'Did you check the tracklist?' },
    { korean: '유통사', english: 'Distributor', pronunciation: 'yu-tong-sa', example: '유통사가 바뀌었어.', exampleTranslation: 'The distributor changed.' },
    { korean: '선주문', english: 'Pre-order', pronunciation: 'seon-ju-mun', example: '선주문 시작했어!', exampleTranslation: 'Pre-orders have started!' },
    { korean: '초동', english: 'First week sales', pronunciation: 'cho-dong', example: '초동 100만 장 돌파!', exampleTranslation: 'First week sales exceeded 1 million!' },
    { korean: '누적', english: 'Cumulative', pronunciation: 'nu-jeok', example: '누적 판매량 대단해.', exampleTranslation: 'The cumulative sales are amazing.' },
    { korean: '음원 차트', english: 'Music chart', pronunciation: 'eum-won cha-teu', example: '음원 차트에 진입했어.', exampleTranslation: 'They entered the music chart.' },
    { korean: '빌보드', english: 'Billboard', pronunciation: 'bil-bo-deu', example: '빌보드 차트에 올랐어!', exampleTranslation: 'They made it onto the Billboard chart!' },
    { korean: '아이차트', english: 'iChart', pronunciation: 'a-i-cha-teu', example: '아이차트 올킬 달성!', exampleTranslation: 'Achieved an iChart all-kill!' },
    { korean: '음원 강자', english: 'Digital chart powerhouse', pronunciation: 'eum-won gang-ja', example: '음원 강자로 불려요.', exampleTranslation: 'They\'re called a digital chart powerhouse.' },
    { korean: '덕통사고', english: 'Accidentally becoming a fan', pronunciation: 'deok-tong-sa-go', example: '덕통사고 당했어.', exampleTranslation: 'I accidentally became a fan.' },
    { korean: '겹덕', english: 'Multifandom (liking multiple groups)', pronunciation: 'gyeop-deok', example: '나는 겹덕이야.', exampleTranslation: 'I\'m a multifandom.' },
    { korean: '최애곡', english: 'Favorite song', pronunciation: 'choe-ae-gok', example: '최애곡이 바뀌었어.', exampleTranslation: 'My favorite song changed.' },
    { korean: '떡상', english: 'Sudden rise in popularity', pronunciation: 'tteok-sang', example: '이 영상으로 떡상했어.', exampleTranslation: 'They surged in popularity with this video.' },
    { korean: '명곡', english: 'Masterpiece song', pronunciation: 'myeong-gok', example: '이건 진짜 명곡이야.', exampleTranslation: 'This is truly a masterpiece song.' },
    { korean: '떡락', english: 'Sudden drop in popularity', pronunciation: 'tteok-rak', example: '논란 후에 떡락했어.', exampleTranslation: 'They dropped after the controversy.' },
    { korean: '논란', english: 'Controversy', pronunciation: 'nol-lan', example: '논란이 커지고 있어.', exampleTranslation: 'The controversy is growing.' },
    { korean: '해명', english: 'Clarification / Explanation', pronunciation: 'hae-myeong', example: '소속사에서 해명했어.', exampleTranslation: 'The agency issued a clarification.' },
    { korean: '사과', english: 'Apology', pronunciation: 'sa-gwa', example: '공식 사과문을 발표했어.', exampleTranslation: 'They released an official apology.' },
    { korean: '복귀', english: 'Return / Comeback (from hiatus)', pronunciation: 'bok-gwi', example: '활동 복귀 소식이야!', exampleTranslation: 'It\'s news of their return to activities!' },
    { korean: '하이터치', english: 'High touch (fan event)', pronunciation: 'ha-i-teo-chi', example: '하이터치 이벤트 있어!', exampleTranslation: 'There\'s a high-touch event!' },
    { korean: '포토타임', english: 'Photo time', pronunciation: 'po-to-ta-im', example: '포토타임에 포즈 잡아.', exampleTranslation: 'Strike a pose during photo time.' },
    { korean: '무반주', english: 'A cappella / No accompaniment', pronunciation: 'mu-ban-ju', example: '무반주 라이브가 대단해.', exampleTranslation: 'The a cappella live is amazing.' },
    { korean: '립싱크', english: 'Lip sync', pronunciation: 'rip-sing-keu', example: '립싱크 아니라 라이브야.', exampleTranslation: 'It\'s not lip sync, it\'s live.' },
    { korean: '라이브 실력', english: 'Live singing ability', pronunciation: 'ra-i-beu sil-lyeok', example: '라이브 실력이 좋아.', exampleTranslation: 'Their live singing ability is good.' },
    { korean: '퍼포먼스', english: 'Performance', pronunciation: 'peo-po-meon-seu', example: '퍼포먼스가 압도적이야.', exampleTranslation: 'The performance is overwhelming.' },
    { korean: '안무 영상', english: 'Dance practice video', pronunciation: 'an-mu yeong-sang', example: '안무 영상 몇 번이나 봤어.', exampleTranslation: 'I\'ve watched the dance practice video so many times.' },
    { korean: '포인트 안무', english: 'Signature dance move', pronunciation: 'po-in-teu an-mu', example: '포인트 안무가 중독돼.', exampleTranslation: 'The signature dance move is addictive.' },
    { korean: '칼군무', english: 'Synchronized dance', pronunciation: 'kal-gun-mu', example: '칼군무가 소름 돋아.', exampleTranslation: 'The synchronized dance gives goosebumps.' },
    { korean: '방청객', english: 'Live audience member', pronunciation: 'bang-cheong-gaek', example: '방청객으로 참여했어.', exampleTranslation: 'I participated as a live audience member.' },
    { korean: '음악 프로그램', english: 'Music program', pronunciation: 'eum-ak peu-ro-geu-raem', example: '음악 프로그램 MC가 됐어.', exampleTranslation: 'They became a music program MC.' },
  ],
  4: [
    { korean: '프로듀싱', english: 'Producing', pronunciation: 'peu-ro-dyu-sing', example: '멤버가 직접 프로듀싱했어.', exampleTranslation: 'The member produced it themselves.' },
    { korean: '자작곡', english: 'Self-composed song', pronunciation: 'ja-jak-gok', example: '자작곡이 앨범에 수록됐어.', exampleTranslation: 'Their self-composed song was included in the album.' },
    { korean: '작곡', english: 'Composing', pronunciation: 'jak-gok', example: '작곡에 참여했어.', exampleTranslation: 'They participated in composing.' },
    { korean: '작사', english: 'Writing lyrics', pronunciation: 'jak-sa', example: '가사를 직접 작사했대.', exampleTranslation: 'They wrote the lyrics themselves.' },
    { korean: '믹싱', english: 'Mixing', pronunciation: 'mik-sing', example: '믹싱이 깔끔해.', exampleTranslation: 'The mixing is clean.' },
    { korean: '마스터링', english: 'Mastering', pronunciation: 'ma-seu-teo-ring', example: '마스터링 퀄리티가 좋아.', exampleTranslation: 'The mastering quality is good.' },
    { korean: '비트', english: 'Beat', pronunciation: 'bi-teu', example: '비트가 중독성 있어.', exampleTranslation: 'The beat is addictive.' },
    { korean: '멜로디', english: 'Melody', pronunciation: 'mel-lo-di', example: '멜로디가 귀에 꽂혀.', exampleTranslation: 'The melody is stuck in my head.' },
    { korean: '후렴구', english: 'Chorus / Refrain', pronunciation: 'hu-ryeom-gu', example: '후렴구가 중독적이야.', exampleTranslation: 'The chorus is addictive.' },
    { korean: '도입부', english: 'Intro', pronunciation: 'do-ip-bu', example: '도입부부터 소름 돋아.', exampleTranslation: 'I get goosebumps from the intro.' },
    { korean: '아웃트로', english: 'Outro', pronunciation: 'a-ut-teu-ro', example: '아웃트로가 여운이 있어.', exampleTranslation: 'The outro leaves a lingering feeling.' },
    { korean: '브릿지', english: 'Bridge (song section)', pronunciation: 'beu-rit-ji', example: '브릿지 파트가 멋져.', exampleTranslation: 'The bridge part is gorgeous.' },
    { korean: '킬링파트', english: 'Killing part (iconic section)', pronunciation: 'kil-ling-pa-teu', example: '킬링파트가 귀에 꽂혀.', exampleTranslation: 'The killing part is stuck in my ear.' },
    { korean: '파트 분배', english: 'Part distribution', pronunciation: 'pa-teu bun-bae', example: '파트 분배가 공평해.', exampleTranslation: 'The part distribution is fair.' },
    { korean: '포메이션', english: 'Formation (dance)', pronunciation: 'po-me-i-syeon', example: '포메이션 변화가 멋져.', exampleTranslation: 'The formation changes are amazing.' },
    { korean: '군무', english: 'Group dance', pronunciation: 'gun-mu', example: '군무가 정말 깔끔해.', exampleTranslation: 'The group dance is really clean.' },
    { korean: '솔로 파트', english: 'Solo part', pronunciation: 'sol-lo pa-teu', example: '솔로 파트에서 빛났어.', exampleTranslation: 'They shone during the solo part.' },
    { korean: '세계관', english: 'Worldview / Universe', pronunciation: 'se-gye-gwan', example: '세계관이 복잡해.', exampleTranslation: 'The worldview is complex.' },
    { korean: '스토리라인', english: 'Storyline', pronunciation: 'seu-to-ri-ra-in', example: '뮤비 스토리라인 해석했어.', exampleTranslation: 'I analyzed the MV storyline.' },
    { korean: '콘셉트 사진', english: 'Concept photo', pronunciation: 'kon-sep-teu sa-jin', example: '콘셉트 사진 분위기 좋다.', exampleTranslation: 'The concept photo mood is great.' },
    { korean: '앨범 자켓', english: 'Album jacket photo', pronunciation: 'ael-beom ja-ket', example: '앨범 자켓이 예술이야.', exampleTranslation: 'The album jacket is art.' },
    { korean: '아트워크', english: 'Artwork', pronunciation: 'a-teu-wo-keu', example: '아트워크 디자인이 독특해.', exampleTranslation: 'The artwork design is unique.' },
    { korean: '뮤직비디오 감독', english: 'Music video director', pronunciation: 'myu-jik-bi-di-o gam-dok', example: '유명 감독이 찍었어.', exampleTranslation: 'A famous director filmed it.' },
    { korean: '안무 창작', english: 'Choreography creation', pronunciation: 'an-mu chang-jak', example: '본인이 안무 창작했어.', exampleTranslation: 'They created the choreography themselves.' },
    { korean: '무대 연출', english: 'Stage direction', pronunciation: 'mu-dae yeon-chul', example: '무대 연출이 화려해.', exampleTranslation: 'The stage direction is spectacular.' },
    { korean: '특수효과', english: 'Special effects', pronunciation: 'teuk-su-hyo-gwa', example: '무대 특수효과가 대박이야.', exampleTranslation: 'The stage special effects are incredible.' },
    { korean: '음색', english: 'Tone / Timbre', pronunciation: 'eum-saek', example: '음색이 독특해서 좋아.', exampleTranslation: 'I like the unique tone.' },
    { korean: '성량', english: 'Vocal volume / Power', pronunciation: 'seong-nyang', example: '성량이 엄청나.', exampleTranslation: 'The vocal power is enormous.' },
    { korean: '가창력', english: 'Singing ability', pronunciation: 'ga-chang-nyeok', example: '가창력이 뛰어나.', exampleTranslation: 'The singing ability is outstanding.' },
    { korean: '음역대', english: 'Vocal range', pronunciation: 'eum-yeok-dae', example: '음역대가 넓어.', exampleTranslation: 'The vocal range is wide.' },
    { korean: '고음 불안정', english: 'Unstable high notes', pronunciation: 'go-eum bul-an-jeong', example: '오늘 고음이 좀 불안정했어.', exampleTranslation: 'The high notes were a bit unstable today.' },
    { korean: '음이탈', english: 'Off-pitch / Off-key', pronunciation: 'eum-i-tal', example: '음이탈 없이 완벽했어.', exampleTranslation: 'It was perfect without going off-pitch.' },
    { korean: '애드리브', english: 'Ad-lib', pronunciation: 'ae-deu-ri-beu', example: '애드리브가 소름이야.', exampleTranslation: 'The ad-libs give goosebumps.' },
    { korean: '플로우', english: 'Flow (rap)', pronunciation: 'peul-lo-u', example: '랩 플로우가 좋아.', exampleTranslation: 'The rap flow is great.' },
    { korean: '라임', english: 'Rhyme (rap)', pronunciation: 'ra-im', example: '라임이 기가 막혀.', exampleTranslation: 'The rhymes are incredible.' },
    { korean: '딕션', english: 'Diction', pronunciation: 'dik-syeon', example: '딕션이 좋아서 가사가 잘 들려.', exampleTranslation: 'The diction is good so the lyrics are clear.' },
    { korean: '표현력', english: 'Expressiveness', pronunciation: 'pyo-hyeon-nyeok', example: '표현력이 뛰어나.', exampleTranslation: 'The expressiveness is outstanding.' },
    { korean: '감정 전달', english: 'Emotional delivery', pronunciation: 'gam-jeong jeon-dal', example: '감정 전달이 정말 좋아.', exampleTranslation: 'The emotional delivery is really good.' },
    { korean: '몰입감', english: 'Immersion / Engagement', pronunciation: 'mol-ip-gam', example: '무대 몰입감이 대단해.', exampleTranslation: 'The stage immersion is incredible.' },
    { korean: '카리스마', english: 'Charisma', pronunciation: 'ka-ri-seu-ma', example: '무대 위 카리스마가 대박.', exampleTranslation: 'The charisma on stage is incredible.' },
    { korean: '아우라', english: 'Aura', pronunciation: 'a-u-ra', example: '아우라가 남다르다.', exampleTranslation: 'The aura is different from others.' },
    { korean: '무대 매너', english: 'Stage manners', pronunciation: 'mu-dae mae-neo', example: '무대 매너가 프로야.', exampleTranslation: 'The stage manners are professional.' },
    { korean: '팬 서비스', english: 'Fan service', pronunciation: 'paen seo-bi-seu', example: '팬 서비스가 최고야.', exampleTranslation: 'The fan service is the best.' },
    { korean: '리액션', english: 'Reaction', pronunciation: 'ri-aek-syeon', example: '리액션 영상 찍었어.', exampleTranslation: 'I filmed a reaction video.' },
    { korean: '해석', english: 'Interpretation / Analysis', pronunciation: 'hae-seok', example: '뮤비 해석 영상 봤어?', exampleTranslation: 'Did you watch the MV interpretation video?' },
    { korean: '이스터에그', english: 'Easter egg', pronunciation: 'i-seu-teo-e-geu', example: '뮤비에 이스터에그 많아.', exampleTranslation: 'There are many easter eggs in the MV.' },
    { korean: '떡밥 회수', english: 'Callback / Payoff', pronunciation: 'tteok-bap hoe-su', example: '드디어 떡밥 회수됐어!', exampleTranslation: 'The foreshadowing was finally resolved!' },
    { korean: '상징', english: 'Symbol', pronunciation: 'sang-jing', example: '이 장면의 상징이 뭘까?', exampleTranslation: 'What does this scene symbolize?' },
    { korean: '컨셉 변화', english: 'Concept change', pronunciation: 'keon-sep byeon-hwa', example: '이번에 컨셉 변화가 컸어.', exampleTranslation: 'The concept change was big this time.' },
    { korean: '성장형', english: 'Growth-type (artist)', pronunciation: 'seong-jang-hyeong', example: '성장형 아이돌이야.', exampleTranslation: 'They\'re a growth-type idol.' },
    { korean: '다재다능', english: 'Multi-talented', pronunciation: 'da-jae-da-neung', example: '진짜 다재다능해.', exampleTranslation: 'They\'re truly multi-talented.' },
    { korean: '센스', english: 'Sense / Wit', pronunciation: 'sen-seu', example: '예능 센스가 좋아.', exampleTranslation: 'They have good variety show sense.' },
    { korean: '반전 매력', english: 'Unexpected charm / Gap charm', pronunciation: 'ban-jeon mae-ryeok', example: '반전 매력이 있어.', exampleTranslation: 'They have unexpected charm.' },
    { korean: '비글미', english: 'Beagle-like energy (playfulness)', pronunciation: 'bi-geul-mi', example: '비글미가 넘쳐.', exampleTranslation: 'Overflowing with playful energy.' },
    { korean: '깐부', english: 'Close partner / Buddy', pronunciation: 'kkan-bu', example: '둘이 완전 깐부야.', exampleTranslation: 'Those two are total buddies.' },
    { korean: '상호작용', english: 'Interaction', pronunciation: 'sang-ho-jak-yong', example: '팬과의 상호작용이 좋아.', exampleTranslation: 'The interaction with fans is great.' },
    { korean: '멀티캠', english: 'Multi-cam', pronunciation: 'meol-ti-kaem', example: '멀티캠으로 각도별 봤어.', exampleTranslation: 'I watched from different angles on multi-cam.' },
    { korean: '방청', english: 'Live audience viewing', pronunciation: 'bang-cheong', example: '음방 방청 갔어.', exampleTranslation: 'I went to a music show live audience recording.' },
    { korean: '예매', english: 'Advance ticket purchase', pronunciation: 'ye-mae', example: '콘서트 예매 전쟁이야.', exampleTranslation: 'Concert ticket booking is a war.' },
    { korean: '티켓팅', english: 'Ticketing (rush)', pronunciation: 'ti-ke-ting', example: '티켓팅 성공했어!', exampleTranslation: 'I succeeded in ticketing!' },
    { korean: '연석', english: 'Consecutive seats', pronunciation: 'yeon-seok', example: '연석으로 잡았어.', exampleTranslation: 'I got consecutive seats.' },
    { korean: '앞줄', english: 'Front row', pronunciation: 'ap-jul', example: '앞줄에서 봤어!', exampleTranslation: 'I watched from the front row!' },
    { korean: '스탠딩', english: 'Standing (concert)', pronunciation: 'seu-taen-ding', example: '스탠딩 구역이야.', exampleTranslation: 'It\'s a standing area.' },
    { korean: '관람 매너', english: 'Viewing etiquette', pronunciation: 'gwal-lam mae-neo', example: '관람 매너 지켜 주세요.', exampleTranslation: 'Please observe viewing etiquette.' },
    { korean: '떼창 문화', english: 'Group singing culture', pronunciation: 'tte-chang mun-hwa', example: '한국 떼창 문화가 유명해.', exampleTranslation: 'Korean group singing culture is famous.' },
    { korean: '원곡', english: 'Original song', pronunciation: 'won-gok', example: '원곡보다 커버가 더 좋아.', exampleTranslation: 'The cover is better than the original.' },
    { korean: '리메이크', english: 'Remake', pronunciation: 'ri-me-i-keu', example: '명곡 리메이크했어.', exampleTranslation: 'They remade a classic song.' },
    { korean: '샘플링', english: 'Sampling', pronunciation: 'saem-peul-ling', example: '유명한 곡을 샘플링했어.', exampleTranslation: 'They sampled a famous song.' },
    { korean: '음원 깡패', english: 'Digital monster (chart dominator)', pronunciation: 'eum-won kkang-pae', example: '음원 깡패라 불려.', exampleTranslation: 'They\'re called a digital monster.' },
    { korean: '실물', english: 'In person (real appearance)', pronunciation: 'sil-mul', example: '실물이 더 예뻐!', exampleTranslation: 'They\'re even prettier in person!' },
    { korean: '본체', english: 'True self / Origin', pronunciation: 'bon-che', example: '귀여움의 본체야.', exampleTranslation: 'They\'re the epitome of cuteness.' },
    { korean: '텐션', english: 'Energy / Tension (mood)', pronunciation: 'ten-syeon', example: '오늘 텐션이 높아!', exampleTranslation: 'The energy is high today!' },
    { korean: '비주얼 센터', english: 'Visual center', pronunciation: 'bi-ju-eol sen-teo', example: '비주얼 센터가 누구야?', exampleTranslation: 'Who is the visual center?' },
    { korean: '올해의 신인', english: 'Rookie of the year', pronunciation: 'ol-hae-ui sin-in', example: '올해의 신인 후보야.', exampleTranslation: 'They\'re a candidate for rookie of the year.' },
    { korean: '분량', english: 'Screen time / Portion', pronunciation: 'bun-nyang', example: '뮤비 분량이 많아서 좋아.', exampleTranslation: 'I\'m happy they have a lot of screen time in the MV.' },
    { korean: '무대 의상', english: 'Stage outfit / Costume', pronunciation: 'mu-dae ui-sang', example: '무대 의상이 화려해.', exampleTranslation: 'The stage costumes are splendid.' },
    { korean: '헤어 스타일', english: 'Hairstyle', pronunciation: 'he-eo seu-ta-il', example: '새 헤어 스타일 대박!', exampleTranslation: 'The new hairstyle is amazing!' },
    { korean: '팬 문화', english: 'Fan culture', pronunciation: 'paen mun-hwa', example: '건강한 팬 문화를 만들자.', exampleTranslation: 'Let\'s create a healthy fan culture.' },
    { korean: '덕질 비용', english: 'Fangirling expenses', pronunciation: 'deok-jil bi-yong', example: '덕질 비용이 만만찮아.', exampleTranslation: 'Fangirling expenses are not cheap.' },
    { korean: '포토카드 거래', english: 'Photocard trading', pronunciation: 'po-to-ka-deu geo-rae', example: '포토카드 거래 조심해.', exampleTranslation: 'Be careful with photocard trading.' },
    { korean: '랜덤', english: 'Random (photocard)', pronunciation: 'raen-deom', example: '랜덤으로 최애 나왔어!', exampleTranslation: 'I got my bias from the random draw!' },
    { korean: '미공개', english: 'Unreleased', pronunciation: 'mi-gong-gae', example: '미공개 사진이 유출됐어.', exampleTranslation: 'Unreleased photos were leaked.' },
    { korean: '워터마크', english: 'Watermark', pronunciation: 'wo-teo-ma-keu', example: '워터마크 지우지 마세요.', exampleTranslation: 'Don\'t remove the watermark.' },
    { korean: '저작권', english: 'Copyright', pronunciation: 'jeo-jak-gwon', example: '저작권 문제 조심해야 해.', exampleTranslation: 'We need to be careful about copyright issues.' },
    { korean: '음악 방송 점수', english: 'Music show score', pronunciation: 'eum-ak bang-song jeom-su', example: '음악 방송 점수 계산법이 복잡해.', exampleTranslation: 'The music show scoring system is complicated.' },
    { korean: '사전 투표', english: 'Pre-voting', pronunciation: 'sa-jeon tu-pyo', example: '사전 투표 잊지 마!', exampleTranslation: 'Don\'t forget the pre-voting!' },
    { korean: '문자 투표', english: 'Text voting', pronunciation: 'mun-ja tu-pyo', example: '문자 투표도 중요해.', exampleTranslation: 'Text voting is important too.' },
    { korean: '음원 점수', english: 'Digital score', pronunciation: 'eum-won jeom-su', example: '음원 점수가 높아야 해.', exampleTranslation: 'The digital score needs to be high.' },
    { korean: '방송 점수', english: 'Broadcast score', pronunciation: 'bang-song jeom-su', example: '방송 점수도 반영돼.', exampleTranslation: 'The broadcast score is also reflected.' },
    { korean: '음반 점수', english: 'Album sales score', pronunciation: 'eum-ban jeom-su', example: '음반 점수가 높아.', exampleTranslation: 'The album sales score is high.' },
    { korean: '레전드 무대', english: 'Legendary stage', pronunciation: 're-jen-deu mu-dae', example: '이건 레전드 무대야.', exampleTranslation: 'This is a legendary stage.' },
    { korean: '떡밥 정리', english: 'Theory compilation', pronunciation: 'tteok-bap jeong-ri', example: '세계관 떡밥 정리 봤어?', exampleTranslation: 'Did you see the worldview theory compilation?' },
    { korean: '인성', english: 'Personality / Character', pronunciation: 'in-seong', example: '인성이 정말 좋아.', exampleTranslation: 'Their personality is really great.' },
    { korean: '소통', english: 'Communication', pronunciation: 'so-tong', example: '팬과 소통을 잘해.', exampleTranslation: 'They communicate well with fans.' },
    { korean: '선배', english: 'Senior (in the industry)', pronunciation: 'seon-bae', example: '선배 그룹에게 인사했어.', exampleTranslation: 'They greeted the senior group.' },
    { korean: '후배', english: 'Junior (in the industry)', pronunciation: 'hu-bae', example: '후배 그룹을 챙겨 줘.', exampleTranslation: 'They take care of junior groups.' },
    { korean: '동기', english: 'Same debut year peers', pronunciation: 'dong-gi', example: '동기 그룹이랑 친해.', exampleTranslation: 'They\'re close with groups that debuted the same year.' },
    { korean: '세대교체', english: 'Generational shift', pronunciation: 'se-dae-gyo-che', example: '4세대 아이돌 세대교체 중이야.', exampleTranslation: '4th gen idol generational shift is happening.' },
    { korean: '비하인드 콘텐츠', english: 'Behind-the-scenes content', pronunciation: 'bi-ha-in-deu kon-ten-cheu', example: '비하인드 콘텐츠가 재밌어.', exampleTranslation: 'The behind-the-scenes content is fun.' },
    { korean: '라이브 방송', english: 'Live broadcast', pronunciation: 'ra-i-beu bang-song', example: '라이브 방송에서 팬들과 소통해.', exampleTranslation: 'They communicate with fans during live broadcasts.' },
  ],
  5: [
    { korean: '음악 산업', english: 'Music industry', pronunciation: 'eum-ak san-eop', example: '한국 음악 산업이 성장하고 있어.', exampleTranslation: 'The Korean music industry is growing.' },
    { korean: '엔터테인먼트', english: 'Entertainment', pronunciation: 'en-teo-te-in-meon-teu', example: '엔터테인먼트 산업의 구조가 복잡해.', exampleTranslation: 'The structure of the entertainment industry is complex.' },
    { korean: '음원 유통', english: 'Music distribution', pronunciation: 'eum-won yu-tong', example: '디지털 음원 유통 방식이 변했어.', exampleTranslation: 'Digital music distribution methods have changed.' },
    { korean: '수익 구조', english: 'Revenue structure', pronunciation: 'su-ik gu-jo', example: '아이돌 수익 구조를 분석해 봤어.', exampleTranslation: 'I analyzed the idol revenue structure.' },
    { korean: '저작권료', english: 'Copyright royalties', pronunciation: 'jeo-jak-gwon-nyo', example: '자작곡 저작권료가 들어와.', exampleTranslation: 'Copyright royalties from self-composed songs come in.' },
    { korean: '음원 수익', english: 'Streaming revenue', pronunciation: 'eum-won su-ik', example: '음원 수익 배분이 공정해야 해.', exampleTranslation: 'Streaming revenue distribution should be fair.' },
    { korean: '초동 판매량', english: 'First week sales volume', pronunciation: 'cho-dong pan-mae-ryang', example: '초동 판매량이 신기록이야.', exampleTranslation: 'First week sales set a new record.' },
    { korean: '누적 판매량', english: 'Cumulative sales volume', pronunciation: 'nu-jeok pan-mae-ryang', example: '누적 판매량 500만 장 돌파!', exampleTranslation: 'Cumulative sales exceeded 5 million copies!' },
    { korean: '시장 분석', english: 'Market analysis', pronunciation: 'si-jang bun-seok', example: '케이팝 시장 분석 보고서야.', exampleTranslation: 'It\'s a K-Pop market analysis report.' },
    { korean: '글로벌 시장', english: 'Global market', pronunciation: 'geul-lo-beol si-jang', example: '글로벌 시장에서 인정받았어.', exampleTranslation: 'They were recognized in the global market.' },
    { korean: '해외 진출', english: 'Overseas expansion', pronunciation: 'hae-oe jin-chul', example: '해외 진출에 성공했어.', exampleTranslation: 'They succeeded in overseas expansion.' },
    { korean: '문화 수출', english: 'Cultural export', pronunciation: 'mun-hwa su-chul', example: '케이팝은 한국의 문화 수출이야.', exampleTranslation: 'K-Pop is Korea\'s cultural export.' },
    { korean: '한류', english: 'Korean Wave / Hallyu', pronunciation: 'hal-lyu', example: '한류의 영향력이 커지고 있어.', exampleTranslation: 'The influence of the Korean Wave is growing.' },
    { korean: '소프트 파워', english: 'Soft power', pronunciation: 'so-peu-teu pa-wo', example: '케이팝은 소프트 파워의 상징이야.', exampleTranslation: 'K-Pop is a symbol of soft power.' },
    { korean: '문화 콘텐츠', english: 'Cultural content', pronunciation: 'mun-hwa kon-ten-cheu', example: '문화 콘텐츠 산업이 발전하고 있어.', exampleTranslation: 'The cultural content industry is developing.' },
    { korean: '전략적 마케팅', english: 'Strategic marketing', pronunciation: 'jeon-ryak-jeok ma-ke-ting', example: '전략적 마케팅이 성공 요인이야.', exampleTranslation: 'Strategic marketing is a success factor.' },
    { korean: '브랜드 가치', english: 'Brand value', pronunciation: 'beu-raen-deu ga-chi', example: '그룹의 브랜드 가치가 높아.', exampleTranslation: 'The group\'s brand value is high.' },
    { korean: '광고 모델', english: 'Brand ambassador', pronunciation: 'gwang-go mo-del', example: '글로벌 브랜드 광고 모델이야.', exampleTranslation: 'They\'re a global brand ambassador.' },
    { korean: '스폰서십', english: 'Sponsorship', pronunciation: 'seu-pon-seo-sip', example: '스폰서십 계약을 체결했어.', exampleTranslation: 'They signed a sponsorship deal.' },
    { korean: '음악 이론', english: 'Music theory', pronunciation: 'eum-ak i-ron', example: '음악 이론을 공부하고 있어.', exampleTranslation: 'I\'m studying music theory.' },
    { korean: '화성학', english: 'Harmony (music theory)', pronunciation: 'hwa-seong-hak', example: '화성학 기반의 편곡이야.', exampleTranslation: 'It\'s an arrangement based on harmony theory.' },
    { korean: '박자', english: 'Rhythm / Time signature', pronunciation: 'bak-ja', example: '박자가 복잡한 곡이야.', exampleTranslation: 'It\'s a song with a complex rhythm.' },
    { korean: '템포', english: 'Tempo', pronunciation: 'tem-po', example: '템포가 점점 빨라져.', exampleTranslation: 'The tempo gradually speeds up.' },
    { korean: '전조', english: 'Key change / Modulation', pronunciation: 'jeon-jo', example: '후반부 전조가 소름이야.', exampleTranslation: 'The key change in the latter half gives goosebumps.' },
    { korean: '장조', english: 'Major key', pronunciation: 'jang-jo', example: '장조로 밝은 느낌이야.', exampleTranslation: 'It feels bright in a major key.' },
    { korean: '단조', english: 'Minor key', pronunciation: 'dan-jo', example: '단조의 우울한 분위기야.', exampleTranslation: 'It has a melancholic mood in a minor key.' },
    { korean: '음계', english: 'Scale', pronunciation: 'eum-gye', example: '5음계를 활용한 곡이야.', exampleTranslation: 'It\'s a song that utilizes a pentatonic scale.' },
    { korean: '코드 진행', english: 'Chord progression', pronunciation: 'ko-deu jin-haeng', example: '코드 진행이 독특해.', exampleTranslation: 'The chord progression is unique.' },
    { korean: '신디사이저', english: 'Synthesizer', pronunciation: 'sin-di-sa-i-jeo', example: '신디사이저 사운드가 인상적이야.', exampleTranslation: 'The synthesizer sound is impressive.' },
    { korean: '일렉트로닉', english: 'Electronic', pronunciation: 'il-lek-teu-ro-nik', example: '일렉트로닉 장르를 시도했어.', exampleTranslation: 'They tried the electronic genre.' },
    { korean: '힙합', english: 'Hip-hop', pronunciation: 'hip-hap', example: '힙합 기반의 곡이야.', exampleTranslation: 'It\'s a hip-hop based song.' },
    { korean: '알앤비', english: 'R&B', pronunciation: 'al-aen-bi', example: '알앤비 느낌이 좋아.', exampleTranslation: 'The R&B vibe is nice.' },
    { korean: '팝', english: 'Pop', pronunciation: 'pap', example: '팝 장르로 전환했어.', exampleTranslation: 'They switched to the pop genre.' },
    { korean: '댄스 팝', english: 'Dance pop', pronunciation: 'daen-seu pap', example: '댄스 팝 장르에 강해.', exampleTranslation: 'They\'re strong in the dance pop genre.' },
    { korean: '발라드', english: 'Ballad', pronunciation: 'bal-la-deu', example: '발라드 곡이 감동이야.', exampleTranslation: 'The ballad song is touching.' },
    { korean: '장르 혼합', english: 'Genre fusion', pronunciation: 'jang-reu hon-hap', example: '장르 혼합이 신선해.', exampleTranslation: 'The genre fusion is refreshing.' },
    { korean: '실험적', english: 'Experimental', pronunciation: 'sil-heom-jeok', example: '실험적인 음악을 시도해.', exampleTranslation: 'They try experimental music.' },
    { korean: '보컬 테크닉', english: 'Vocal technique', pronunciation: 'bo-keol te-keu-nik', example: '보컬 테크닉이 뛰어나.', exampleTranslation: 'The vocal technique is excellent.' },
    { korean: '비브라토', english: 'Vibrato', pronunciation: 'bi-beu-ra-to', example: '비브라토가 아름다워.', exampleTranslation: 'The vibrato is beautiful.' },
    { korean: '팔세토', english: 'Falsetto', pronunciation: 'pal-se-to', example: '팔세토 음색이 독특해.', exampleTranslation: 'The falsetto tone is unique.' },
    { korean: '벨팅', english: 'Belting', pronunciation: 'bel-ting', example: '벨팅 고음이 소름 돋아.', exampleTranslation: 'The belting high notes give goosebumps.' },
    { korean: '두성', english: 'Head voice', pronunciation: 'du-seong', example: '두성 전환이 자연스러워.', exampleTranslation: 'The head voice transition is natural.' },
    { korean: '흉성', english: 'Chest voice', pronunciation: 'hyung-seong', example: '흉성이 풍부해.', exampleTranslation: 'The chest voice is rich.' },
    { korean: '호흡', english: 'Breathing (technique)', pronunciation: 'ho-heup', example: '호흡 조절이 완벽해.', exampleTranslation: 'Breath control is perfect.' },
    { korean: '동시대', english: 'Contemporary', pronunciation: 'dong-si-dae', example: '동시대 음악 트렌드를 반영해.', exampleTranslation: 'It reflects contemporary music trends.' },
    { korean: '영향력', english: 'Influence', pronunciation: 'yeong-hyang-nyeok', example: '음악적 영향력이 대단해.', exampleTranslation: 'The musical influence is significant.' },
    { korean: '선구자', english: 'Pioneer', pronunciation: 'seon-gu-ja', example: '케이팝의 선구자 역할을 했어.', exampleTranslation: 'They played the role of K-Pop pioneer.' },
    { korean: '트렌드세터', english: 'Trendsetter', pronunciation: 'teu-ren-deu-se-teo', example: '음악 트렌드세터로 불려.', exampleTranslation: 'They\'re called a music trendsetter.' },
    { korean: '대중성', english: 'Public appeal', pronunciation: 'dae-jung-seong', example: '대중성과 예술성을 겸비했어.', exampleTranslation: 'They combine public appeal and artistry.' },
    { korean: '예술성', english: 'Artistry', pronunciation: 'ye-sul-seong', example: '예술성이 높은 앨범이야.', exampleTranslation: 'It\'s an album with high artistry.' },
    { korean: '완성도', english: 'Completeness / Quality', pronunciation: 'wan-seong-do', example: '앨범 완성도가 높아.', exampleTranslation: 'The album quality is high.' },
    { korean: '음악적 성장', english: 'Musical growth', pronunciation: 'eum-ak-jeok seong-jang', example: '음악적 성장이 눈에 띄어.', exampleTranslation: 'The musical growth is noticeable.' },
    { korean: '자아 탐색', english: 'Self-exploration', pronunciation: 'ja-a tam-saek', example: '앨범이 자아 탐색을 다뤄.', exampleTranslation: 'The album deals with self-exploration.' },
    { korean: '정체성', english: 'Identity', pronunciation: 'jeong-che-seong', example: '음악적 정체성을 찾았어.', exampleTranslation: 'They found their musical identity.' },
    { korean: '메시지', english: 'Message', pronunciation: 'me-si-ji', example: '곡에 담긴 메시지가 깊어.', exampleTranslation: 'The message in the song is deep.' },
    { korean: '사회적 메시지', english: 'Social message', pronunciation: 'sa-hoe-jeok me-si-ji', example: '사회적 메시지를 담았어.', exampleTranslation: 'They included a social message.' },
    { korean: '세대 공감', english: 'Generational empathy', pronunciation: 'se-dae gong-gam', example: '세대 공감을 얻었어.', exampleTranslation: 'They gained generational empathy.' },
    { korean: '공감대', english: 'Common ground / Empathy', pronunciation: 'gong-gam-dae', example: '팬들과 공감대를 형성했어.', exampleTranslation: 'They formed common ground with fans.' },
    { korean: '문화적 영향', english: 'Cultural influence', pronunciation: 'mun-hwa-jeok yeong-hyang', example: '케이팝의 문화적 영향이 커.', exampleTranslation: 'K-Pop\'s cultural influence is significant.' },
    { korean: '다국적', english: 'Multinational', pronunciation: 'da-guk-jeok', example: '다국적 멤버로 구성됐어.', exampleTranslation: 'It\'s composed of multinational members.' },
    { korean: '다문화', english: 'Multicultural', pronunciation: 'da-mun-hwa', example: '다문화적 요소를 담았어.', exampleTranslation: 'It contains multicultural elements.' },
    { korean: '현지화', english: 'Localization', pronunciation: 'hyeon-ji-hwa', example: '현지화 전략이 성공적이야.', exampleTranslation: 'The localization strategy is successful.' },
    { korean: '팬 참여형', english: 'Fan-participatory', pronunciation: 'paen cham-yeo-hyeong', example: '팬 참여형 콘텐츠가 많아.', exampleTranslation: 'There is a lot of fan-participatory content.' },
    { korean: '디지털 마케팅', english: 'Digital marketing', pronunciation: 'di-ji-teol ma-ke-ting', example: '디지털 마케팅 전략이 뛰어나.', exampleTranslation: 'The digital marketing strategy is excellent.' },
    { korean: '바이럴 마케팅', english: 'Viral marketing', pronunciation: 'ba-i-reol ma-ke-ting', example: '바이럴 마케팅으로 성공했어.', exampleTranslation: 'They succeeded through viral marketing.' },
    { korean: '콘텐츠 전략', english: 'Content strategy', pronunciation: 'kon-ten-cheu jeon-ryak', example: '콘텐츠 전략이 체계적이야.', exampleTranslation: 'The content strategy is systematic.' },
    { korean: '팬 경제', english: 'Fan economy', pronunciation: 'paen gyeong-je', example: '팬 경제가 산업을 이끌어.', exampleTranslation: 'The fan economy drives the industry.' },
    { korean: '아이돌 시스템', english: 'Idol system', pronunciation: 'a-i-dol si-seu-tem', example: '한국의 아이돌 시스템은 독특해.', exampleTranslation: 'Korea\'s idol system is unique.' },
    { korean: '연습생 시스템', english: 'Trainee system', pronunciation: 'yeon-seup-saeng si-seu-tem', example: '연습생 시스템의 장단점이 있어.', exampleTranslation: 'There are pros and cons to the trainee system.' },
    { korean: '데뷔 전략', english: 'Debut strategy', pronunciation: 'de-bwi jeon-ryak', example: '데뷔 전략이 잘 짜여 있어.', exampleTranslation: 'The debut strategy is well planned.' },
    { korean: '활동 주기', english: 'Promotion cycle', pronunciation: 'hwal-dong ju-gi', example: '활동 주기가 짧아졌어.', exampleTranslation: 'The promotion cycle has gotten shorter.' },
    { korean: '계약 기간', english: 'Contract period', pronunciation: 'gye-yak gi-gan', example: '계약 기간이 7년이야.', exampleTranslation: 'The contract period is 7 years.' },
    { korean: '재계약', english: 'Contract renewal', pronunciation: 'jae-gye-yak', example: '재계약 여부가 관심사야.', exampleTranslation: 'Whether they\'ll renew the contract is of interest.' },
    { korean: '해체', english: 'Disbandment', pronunciation: 'hae-che', example: '해체 소식에 충격받았어.', exampleTranslation: 'I was shocked by the disbandment news.' },
    { korean: '솔로 활동', english: 'Solo activities', pronunciation: 'sol-lo hwal-dong', example: '솔로 활동도 성공적이야.', exampleTranslation: 'Solo activities are also successful.' },
    { korean: '개인 활동', english: 'Individual activities', pronunciation: 'gae-in hwal-dong', example: '개인 활동이 다양해.', exampleTranslation: 'Individual activities are diverse.' },
    { korean: '그룹 활동', english: 'Group activities', pronunciation: 'geu-rup hwal-dong', example: '그룹 활동에 집중하고 있어.', exampleTranslation: 'They\'re focusing on group activities.' },
    { korean: '병역', english: 'Military service', pronunciation: 'byeong-yeok', example: '병역 입대 날짜가 정해졌어.', exampleTranslation: 'The military enlistment date was set.' },
    { korean: '입대', english: 'Military enlistment', pronunciation: 'ip-dae', example: '입대 전 마지막 콘서트야.', exampleTranslation: 'It\'s the last concert before military enlistment.' },
    { korean: '전역', english: 'Military discharge', pronunciation: 'jeon-yeok', example: '전역 후 바로 활동 재개했어.', exampleTranslation: 'They resumed activities right after military discharge.' },
    { korean: '세계화', english: 'Globalization', pronunciation: 'se-gye-hwa', example: '케이팝의 세계화가 가속화되고 있어.', exampleTranslation: 'K-Pop globalization is accelerating.' },
    { korean: '음악적 혁신', english: 'Musical innovation', pronunciation: 'eum-ak-jeok hyeok-sin', example: '음악적 혁신을 이끌었어.', exampleTranslation: 'They led musical innovation.' },
    { korean: '산업 동향', english: 'Industry trends', pronunciation: 'san-eop dong-hyang', example: '엔터 산업 동향을 분석했어.', exampleTranslation: 'I analyzed entertainment industry trends.' },
    { korean: '팬덤 문화', english: 'Fandom culture', pronunciation: 'paen-deom mun-hwa', example: '팬덤 문화가 진화하고 있어.', exampleTranslation: 'Fandom culture is evolving.' },
    { korean: '팬덤 경제학', english: 'Fandom economics', pronunciation: 'paen-deom gyeong-je-hak', example: '팬덤 경제학이 주목받고 있어.', exampleTranslation: 'Fandom economics is getting attention.' },
    { korean: '디지털 전환', english: 'Digital transformation', pronunciation: 'di-ji-teol jeon-hwan', example: '음악 산업의 디지털 전환이 빨라.', exampleTranslation: 'Digital transformation in the music industry is fast.' },
    { korean: '플랫폼 전략', english: 'Platform strategy', pronunciation: 'peul-laet-pom jeon-ryak', example: '플랫폼 전략이 중요해졌어.', exampleTranslation: 'Platform strategy has become important.' },
    { korean: '알고리즘', english: 'Algorithm', pronunciation: 'al-go-ri-jeum', example: '알고리즘 추천으로 알게 됐어.', exampleTranslation: 'I discovered them through algorithm recommendations.' },
    { korean: '데이터 분석', english: 'Data analysis', pronunciation: 'de-i-teo bun-seok', example: '팬덤 데이터 분석이 활발해.', exampleTranslation: 'Fandom data analysis is active.' },
    { korean: '인플루언서', english: 'Influencer', pronunciation: 'in-peul-lu-eon-seo', example: '아이돌이 인플루언서 역할도 해.', exampleTranslation: 'Idols also play the role of influencers.' },
    { korean: '크로스오버', english: 'Crossover', pronunciation: 'keu-ro-seu-o-beo', example: '장르 크로스오버를 시도했어.', exampleTranslation: 'They attempted a genre crossover.' },
    { korean: '글로벌 콜라보', english: 'Global collaboration', pronunciation: 'geul-lo-beol kol-la-bo', example: '글로벌 콜라보 곡이야.', exampleTranslation: 'It\'s a global collaboration track.' },
    { korean: '문화 교류', english: 'Cultural exchange', pronunciation: 'mun-hwa gyo-ryu', example: '음악을 통한 문화 교류야.', exampleTranslation: 'It\'s cultural exchange through music.' },
    { korean: '팬 커뮤니티', english: 'Fan community', pronunciation: 'paen keo-myu-ni-ti', example: '온라인 팬 커뮤니티가 활발해.', exampleTranslation: 'Online fan communities are active.' },
    { korean: '참여 문화', english: 'Participatory culture', pronunciation: 'cham-yeo mun-hwa', example: '팬들의 참여 문화가 특별해.', exampleTranslation: 'The participatory culture of fans is special.' },
    { korean: '집단 지성', english: 'Collective intelligence', pronunciation: 'jip-dan ji-seong', example: '팬덤의 집단 지성이 대단해.', exampleTranslation: 'The collective intelligence of the fandom is amazing.' },
    { korean: '음악 저작물', english: 'Musical work', pronunciation: 'eum-ak jeo-jak-mul', example: '음악 저작물의 보호가 필요해.', exampleTranslation: 'Protection of musical works is needed.' },
    { korean: '문화 경쟁력', english: 'Cultural competitiveness', pronunciation: 'mun-hwa gyeong-jaeng-nyeok', example: '케이팝의 문화 경쟁력이 높아.', exampleTranslation: 'K-Pop\'s cultural competitiveness is high.' },
    { korean: '미디어 전략', english: 'Media strategy', pronunciation: 'mi-di-eo jeon-ryak', example: '미디어 전략이 체계적이야.', exampleTranslation: 'The media strategy is systematic.' },
    { korean: '음악 생태계', english: 'Music ecosystem', pronunciation: 'eum-ak saeng-tae-gye', example: '건강한 음악 생태계가 필요해.', exampleTranslation: 'A healthy music ecosystem is needed.' },
  ],
  6: [
    { korean: '음악학', english: 'Musicology', pronunciation: 'eum-ak-hak', example: '음악학적 관점에서 분석했어.', exampleTranslation: 'I analyzed it from a musicological perspective.' },
    { korean: '민족음악학', english: 'Ethnomusicology', pronunciation: 'min-jok-eum-ak-hak', example: '민족음악학적으로 케이팝을 연구해.', exampleTranslation: 'They study K-Pop from an ethnomusicological perspective.' },
    { korean: '대중음악론', english: 'Popular music theory', pronunciation: 'dae-jung-eum-ak-non', example: '대중음악론 수업에서 케이팝을 다뤄.', exampleTranslation: 'K-Pop is covered in popular music theory class.' },
    { korean: '문화 비평', english: 'Cultural criticism', pronunciation: 'mun-hwa bi-pyeong', example: '문화 비평가들이 케이팝을 분석해.', exampleTranslation: 'Cultural critics analyze K-Pop.' },
    { korean: '미학', english: 'Aesthetics', pronunciation: 'mi-hak', example: '케이팝의 미학을 연구하고 있어.', exampleTranslation: 'I\'m studying the aesthetics of K-Pop.' },
    { korean: '기호학', english: 'Semiotics', pronunciation: 'gi-ho-hak', example: '뮤직비디오를 기호학적으로 해석해.', exampleTranslation: 'They interpret music videos semiotically.' },
    { korean: '수용 미학', english: 'Reception aesthetics', pronunciation: 'su-yong mi-hak', example: '수용 미학의 관점에서 팬덤을 봐.', exampleTranslation: 'They view fandom from the perspective of reception aesthetics.' },
    { korean: '포스트모더니즘', english: 'Postmodernism', pronunciation: 'po-seu-teu-mo-deo-ni-jeum', example: '포스트모더니즘적 요소가 보여.', exampleTranslation: 'Postmodernist elements are visible.' },
    { korean: '하이브리드', english: 'Hybrid', pronunciation: 'ha-i-beu-ri-deu', example: '하이브리드 장르의 음악이야.', exampleTranslation: 'It\'s hybrid genre music.' },
    { korean: '트랜스미디어', english: 'Transmedia', pronunciation: 'teu-raen-seu-mi-di-eo', example: '트랜스미디어 스토리텔링을 활용해.', exampleTranslation: 'They utilize transmedia storytelling.' },
    { korean: '내러티브', english: 'Narrative', pronunciation: 'nae-reo-ti-beu', example: '앨범 전체를 관통하는 내러티브야.', exampleTranslation: 'It\'s a narrative that runs through the entire album.' },
    { korean: '시각적 서사', english: 'Visual narrative', pronunciation: 'si-gak-jeok seo-sa', example: '뮤비의 시각적 서사가 풍부해.', exampleTranslation: 'The visual narrative of the MV is rich.' },
    { korean: '음향 설계', english: 'Sound design', pronunciation: 'eum-hyang seol-gye', example: '음향 설계가 세밀해.', exampleTranslation: 'The sound design is meticulous.' },
    { korean: '프로덕션', english: 'Production', pronunciation: 'peu-ro-deok-syeon', example: '프로덕션 퀄리티가 할리우드급이야.', exampleTranslation: 'The production quality is Hollywood-level.' },
    { korean: '포스트 프로덕션', english: 'Post-production', pronunciation: 'po-seu-teu peu-ro-deok-syeon', example: '포스트 프로덕션에 공을 들였어.', exampleTranslation: 'They put effort into post-production.' },
    { korean: '엔터테인먼트 법률', english: 'Entertainment law', pronunciation: 'en-teo-te-in-meon-teu beom-nyul', example: '엔터테인먼트 법률이 개정됐어.', exampleTranslation: 'Entertainment law was revised.' },
    { korean: '노예 계약', english: 'Slave contract', pronunciation: 'no-ye gye-yak', example: '노예 계약 관행이 사라지고 있어.', exampleTranslation: 'The practice of slave contracts is disappearing.' },
    { korean: '공정 거래', english: 'Fair trade', pronunciation: 'gong-jeong geo-rae', example: '공정 거래 문제가 논의되고 있어.', exampleTranslation: 'Fair trade issues are being discussed.' },
    { korean: '지적 재산권', english: 'Intellectual property rights', pronunciation: 'ji-jeok jae-san-gwon', example: '지적 재산권 보호가 중요해.', exampleTranslation: 'Protecting intellectual property rights is important.' },
    { korean: '초상권', english: 'Personality rights / Image rights', pronunciation: 'cho-sang-gwon', example: '초상권 침해가 문제야.', exampleTranslation: 'Violation of image rights is an issue.' },
    { korean: '퍼블리시티권', english: 'Right of publicity', pronunciation: 'peo-beul-li-si-ti-gwon', example: '퍼블리시티권에 대한 논의가 필요해.', exampleTranslation: 'Discussion about the right of publicity is needed.' },
    { korean: '수익 분배 구조', english: 'Revenue sharing structure', pronunciation: 'su-ik bun-bae gu-jo', example: '수익 분배 구조의 투명성이 요구돼.', exampleTranslation: 'Transparency in revenue sharing structure is demanded.' },
    { korean: '기업 공개', english: 'IPO (Initial Public Offering)', pronunciation: 'gi-eop gong-gae', example: '엔터 회사가 기업 공개를 했어.', exampleTranslation: 'The entertainment company went public.' },
    { korean: '주가', english: 'Stock price', pronunciation: 'ju-ga', example: '컴백 소식에 주가가 올랐어.', exampleTranslation: 'The stock price rose on comeback news.' },
    { korean: '시가총액', english: 'Market capitalization', pronunciation: 'si-ga-chong-aek', example: '시가총액이 업계 최고야.', exampleTranslation: 'The market capitalization is the highest in the industry.' },
    { korean: '멀티레이블', english: 'Multi-label (system)', pronunciation: 'meol-ti-re-i-beol', example: '멀티레이블 체제로 운영해.', exampleTranslation: 'They operate under a multi-label system.' },
    { korean: '인수 합병', english: 'Merger and acquisition', pronunciation: 'in-su hap-byeong', example: '인수 합병으로 대형 엔터가 됐어.', exampleTranslation: 'They became a major entertainment company through M&A.' },
    { korean: '기업 지배 구조', english: 'Corporate governance', pronunciation: 'gi-eop ji-bae gu-jo', example: '기업 지배 구조가 논란이야.', exampleTranslation: 'Corporate governance is controversial.' },
    { korean: '문화 자본', english: 'Cultural capital', pronunciation: 'mun-hwa ja-bon', example: '케이팝이 문화 자본으로 작용해.', exampleTranslation: 'K-Pop functions as cultural capital.' },
    { korean: '상징 자본', english: 'Symbolic capital', pronunciation: 'sang-jing ja-bon', example: '아이돌의 상징 자본이 커.', exampleTranslation: 'The idol\'s symbolic capital is significant.' },
    { korean: '문화 산업론', english: 'Cultural industry theory', pronunciation: 'mun-hwa san-eop-non', example: '문화 산업론 관점에서 분석해.', exampleTranslation: 'Analyze from the cultural industry theory perspective.' },
    { korean: '규범적 미학', english: 'Normative aesthetics', pronunciation: 'gyu-beom-jeok mi-hak', example: '케이팝의 규범적 미학을 탐구해.', exampleTranslation: 'They explore the normative aesthetics of K-Pop.' },
    { korean: '아방가르드', english: 'Avant-garde', pronunciation: 'a-bang-ga-reu-deu', example: '아방가르드적인 시도가 돋보여.', exampleTranslation: 'The avant-garde attempt stands out.' },
    { korean: '키치', english: 'Kitsch', pronunciation: 'ki-chi', example: '키치적 요소를 의도적으로 활용해.', exampleTranslation: 'They intentionally use kitsch elements.' },
    { korean: '패러디', english: 'Parody', pronunciation: 'pae-reo-di', example: '패러디와 오마주의 경계야.', exampleTranslation: 'It\'s on the boundary between parody and homage.' },
    { korean: '오마주', english: 'Homage', pronunciation: 'o-ma-ju', example: '과거 명곡에 대한 오마주야.', exampleTranslation: 'It\'s an homage to a past classic song.' },
    { korean: '인터텍스트성', english: 'Intertextuality', pronunciation: 'in-teo-tek-seu-teu-seong', example: '뮤비의 인터텍스트성이 풍부해.', exampleTranslation: 'The intertextuality of the MV is rich.' },
    { korean: '자기 지시성', english: 'Self-referentiality', pronunciation: 'ja-gi ji-si-seong', example: '가사에 자기 지시성이 있어.', exampleTranslation: 'There is self-referentiality in the lyrics.' },
    { korean: '메타 서사', english: 'Meta-narrative', pronunciation: 'me-ta seo-sa', example: '메타 서사 구조를 활용했어.', exampleTranslation: 'They utilized a meta-narrative structure.' },
    { korean: '탈장르', english: 'Post-genre / Genre-defying', pronunciation: 'tal-jang-reu', example: '탈장르적 실험이 흥미로워.', exampleTranslation: 'The post-genre experiment is interesting.' },
    { korean: '음악 비평', english: 'Music criticism', pronunciation: 'eum-ak bi-pyeong', example: '전문 음악 비평가의 리뷰야.', exampleTranslation: 'It\'s a review by a professional music critic.' },
    { korean: '담론', english: 'Discourse', pronunciation: 'dam-non', example: '케이팝 담론이 확장되고 있어.', exampleTranslation: 'K-Pop discourse is expanding.' },
    { korean: '헤게모니', english: 'Hegemony', pronunciation: 'he-ge-mo-ni', example: '문화적 헤게모니의 변화야.', exampleTranslation: 'It\'s a change in cultural hegemony.' },
    { korean: '주체성', english: 'Subjectivity / Agency', pronunciation: 'ju-che-seong', example: '아이돌의 주체성이 중요해.', exampleTranslation: 'The idol\'s agency is important.' },
    { korean: '타자화', english: 'Othering', pronunciation: 'ta-ja-hwa', example: '동양 음악의 타자화에 대한 비판이야.', exampleTranslation: 'It\'s a critique of the othering of Eastern music.' },
    { korean: '오리엔탈리즘', english: 'Orientalism', pronunciation: 'o-ri-en-tal-li-jeum', example: '오리엔탈리즘적 시각을 경계해야 해.', exampleTranslation: 'We should be wary of Orientalist perspectives.' },
    { korean: '글로컬', english: 'Glocal', pronunciation: 'geul-lo-keol', example: '글로컬 전략으로 성공했어.', exampleTranslation: 'They succeeded with a glocal strategy.' },
    { korean: '문화 혼종성', english: 'Cultural hybridity', pronunciation: 'mun-hwa hon-jong-seong', example: '케이팝의 문화 혼종성이 매력이야.', exampleTranslation: 'K-Pop\'s cultural hybridity is its charm.' },
    { korean: '탈식민주의', english: 'Postcolonialism', pronunciation: 'tal-sik-min-ju-ui', example: '탈식민주의 관점에서 한류를 분석해.', exampleTranslation: 'Analyzing Hallyu from a postcolonial perspective.' },
    { korean: '디아스포라', english: 'Diaspora', pronunciation: 'di-a-seu-po-ra', example: '한국 디아스포라와 케이팝의 관계야.', exampleTranslation: 'It\'s about the relationship between Korean diaspora and K-Pop.' },
    { korean: '감정 노동', english: 'Emotional labor', pronunciation: 'gam-jeong no-dong', example: '아이돌의 감정 노동 문제야.', exampleTranslation: 'It\'s the issue of emotional labor by idols.' },
    { korean: '정동 이론', english: 'Affect theory', pronunciation: 'jeong-dong i-ron', example: '정동 이론으로 팬덤을 분석해.', exampleTranslation: 'Analyzing fandom through affect theory.' },
    { korean: '수행성', english: 'Performativity', pronunciation: 'su-haeng-seong', example: '아이돌의 수행성에 대한 연구야.', exampleTranslation: 'It\'s research on idol performativity.' },
    { korean: '스펙터클', english: 'Spectacle', pronunciation: 'seu-pek-teo-keul', example: '콘서트는 하나의 스펙터클이야.', exampleTranslation: 'A concert is a spectacle.' },
    { korean: '시뮬라크르', english: 'Simulacrum', pronunciation: 'si-myul-la-keu-reu', example: '아이돌의 이미지는 시뮬라크르야.', exampleTranslation: 'The idol\'s image is a simulacrum.' },
    { korean: '페르소나', english: 'Persona', pronunciation: 'pe-reu-so-na', example: '무대 위의 페르소나와 실제 모습이 달라.', exampleTranslation: 'The on-stage persona differs from reality.' },
    { korean: '아이덴티티', english: 'Identity (cultural)', pronunciation: 'a-i-den-ti-ti', example: '그룹의 아이덴티티를 구축했어.', exampleTranslation: 'They built the group\'s identity.' },
    { korean: '젠더 수행', english: 'Gender performance', pronunciation: 'jen-deo su-haeng', example: '케이팝의 젠더 수행이 주목받아.', exampleTranslation: 'K-Pop\'s gender performance draws attention.' },
    { korean: '남성성', english: 'Masculinity', pronunciation: 'nam-seong-seong', example: '새로운 남성성을 제시해.', exampleTranslation: 'They present a new masculinity.' },
    { korean: '여성성', english: 'Femininity', pronunciation: 'yeo-seong-seong', example: '여성성의 다양한 표현이야.', exampleTranslation: 'It\'s diverse expressions of femininity.' },
    { korean: '신체 정치학', english: 'Body politics', pronunciation: 'sin-che jeong-chi-hak', example: '아이돌의 신체 정치학을 논해.', exampleTranslation: 'They discuss body politics of idols.' },
    { korean: '감시 사회', english: 'Surveillance society', pronunciation: 'gam-si sa-hoe', example: '아이돌에 대한 감시 사회적 시선이야.', exampleTranslation: 'It\'s about the surveillance society\'s gaze on idols.' },
    { korean: '준사회적 관계', english: 'Parasocial relationship', pronunciation: 'jun-sa-hoe-jeok gwan-gye', example: '팬과 아이돌의 준사회적 관계야.', exampleTranslation: 'It\'s the parasocial relationship between fans and idols.' },
    { korean: '프로슈머', english: 'Prosumer', pronunciation: 'peu-ro-syu-meo', example: '팬은 프로슈머로서 역할을 해.', exampleTranslation: 'Fans play a role as prosumers.' },
    { korean: '참여적 팬덤', english: 'Participatory fandom', pronunciation: 'cham-yeo-jeok paen-deom', example: '참여적 팬덤의 특성을 연구해.', exampleTranslation: 'They research the characteristics of participatory fandom.' },
    { korean: '팬덤 조직화', english: 'Fandom organization', pronunciation: 'paen-deom jo-jik-hwa', example: '팬덤 조직화가 체계적이야.', exampleTranslation: 'Fandom organization is systematic.' },
    { korean: '집단 효능감', english: 'Collective efficacy', pronunciation: 'jip-dan hyo-neung-gam', example: '팬덤의 집단 효능감이 높아.', exampleTranslation: 'The fandom\'s collective efficacy is high.' },
    { korean: '사회적 자본', english: 'Social capital', pronunciation: 'sa-hoe-jeok ja-bon', example: '팬덤이 사회적 자본을 축적해.', exampleTranslation: 'The fandom accumulates social capital.' },
    { korean: '미디어 리터러시', english: 'Media literacy', pronunciation: 'mi-di-eo ri-teo-reo-si', example: '팬들의 미디어 리터러시가 높아.', exampleTranslation: 'Fans\' media literacy is high.' },
    { korean: '플랫폼 자본주의', english: 'Platform capitalism', pronunciation: 'peul-laet-pom ja-bon-ju-ui', example: '플랫폼 자본주의와 팬덤의 관계야.', exampleTranslation: 'It\'s about the relationship between platform capitalism and fandom.' },
    { korean: '데이터 주권', english: 'Data sovereignty', pronunciation: 'de-i-teo ju-gwon', example: '팬 데이터 주권 문제가 대두돼.', exampleTranslation: 'Fan data sovereignty issues are emerging.' },
    { korean: '음악 사회학', english: 'Sociology of music', pronunciation: 'eum-ak sa-hoe-hak', example: '음악 사회학적 분석이 필요해.', exampleTranslation: 'A sociological analysis of music is needed.' },
    { korean: '문화 정치학', english: 'Cultural politics', pronunciation: 'mun-hwa jeong-chi-hak', example: '케이팝과 문화 정치학의 접점이야.', exampleTranslation: 'It\'s the intersection of K-Pop and cultural politics.' },
    { korean: '상품화', english: 'Commodification', pronunciation: 'sang-pum-hwa', example: '음악의 상품화에 대한 비판이야.', exampleTranslation: 'It\'s criticism of the commodification of music.' },
    { korean: '물신주의', english: 'Fetishism', pronunciation: 'mul-sin-ju-ui', example: '아이돌에 대한 물신주의적 소비야.', exampleTranslation: 'It\'s fetishistic consumption of idols.' },
    { korean: '스타 시스템', english: 'Star system', pronunciation: 'seu-ta si-seu-tem', example: '스타 시스템의 구조적 문제야.', exampleTranslation: 'It\'s a structural issue of the star system.' },
    { korean: '문화 제국주의', english: 'Cultural imperialism', pronunciation: 'mun-hwa je-guk-ju-ui', example: '문화 제국주의 논쟁이 있어.', exampleTranslation: 'There is a cultural imperialism debate.' },
    { korean: '역문화 제국주의', english: 'Reverse cultural imperialism', pronunciation: 'yeok-mun-hwa je-guk-ju-ui', example: '한류를 역문화 제국주의로 보는 시각이 있어.', exampleTranslation: 'Some view Hallyu as reverse cultural imperialism.' },
    { korean: '문화 다양성', english: 'Cultural diversity', pronunciation: 'mun-hwa da-yang-seong', example: '문화 다양성 보장이 중요해.', exampleTranslation: 'Ensuring cultural diversity is important.' },
    { korean: '창작 자유', english: 'Creative freedom', pronunciation: 'chang-jak ja-yu', example: '예술가의 창작 자유를 존중해야 해.', exampleTranslation: 'We should respect artists\' creative freedom.' },
    { korean: '예술적 자율성', english: 'Artistic autonomy', pronunciation: 'ye-sul-jeok ja-yul-seong', example: '예술적 자율성이 보장돼야 해.', exampleTranslation: 'Artistic autonomy should be guaranteed.' },
    { korean: '상업성', english: 'Commerciality', pronunciation: 'sang-eop-seong', example: '예술성과 상업성의 균형이 중요해.', exampleTranslation: 'The balance between artistry and commerciality is important.' },
    { korean: '문화 소비', english: 'Cultural consumption', pronunciation: 'mun-hwa so-bi', example: '문화 소비 패턴이 변하고 있어.', exampleTranslation: 'Cultural consumption patterns are changing.' },
    { korean: '수용자 이론', english: 'Audience theory', pronunciation: 'su-yong-ja i-ron', example: '수용자 이론으로 팬 행동을 분석해.', exampleTranslation: 'Analyzing fan behavior through audience theory.' },
    { korean: '텍스트 분석', english: 'Textual analysis', pronunciation: 'tek-seu-teu bun-seok', example: '가사의 텍스트 분석을 수행했어.', exampleTranslation: 'I conducted a textual analysis of the lyrics.' },
    { korean: '디지털 인문학', english: 'Digital humanities', pronunciation: 'di-ji-teol in-mun-hak', example: '디지털 인문학으로 케이팝을 연구해.', exampleTranslation: 'They study K-Pop through digital humanities.' },
    { korean: '문화 연구', english: 'Cultural studies', pronunciation: 'mun-hwa yeon-gu', example: '문화 연구 분야에서 케이팝이 주목받아.', exampleTranslation: 'K-Pop draws attention in cultural studies.' },
    { korean: '비판적 담론', english: 'Critical discourse', pronunciation: 'bi-pan-jeok dam-non', example: '비판적 담론이 건강한 산업을 만들어.', exampleTranslation: 'Critical discourse creates a healthy industry.' },
    { korean: '탈중심화', english: 'Decentralization', pronunciation: 'tal-jung-sim-hwa', example: '음악 산업의 탈중심화가 진행 중이야.', exampleTranslation: 'Decentralization of the music industry is underway.' },
    { korean: '네트워크 효과', english: 'Network effect', pronunciation: 'ne-teu-wo-keu hyo-gwa', example: '팬덤의 네트워크 효과가 강력해.', exampleTranslation: 'The network effect of the fandom is powerful.' },
    { korean: '콘텐츠 생태계', english: 'Content ecosystem', pronunciation: 'kon-ten-cheu saeng-tae-gye', example: '케이팝 콘텐츠 생태계가 확장되고 있어.', exampleTranslation: 'The K-Pop content ecosystem is expanding.' },
    { korean: '지속 가능성', english: 'Sustainability', pronunciation: 'ji-sok ga-neung-seong', example: '케이팝 산업의 지속 가능성을 논해.', exampleTranslation: 'They discuss the sustainability of the K-Pop industry.' },
    { korean: '윤리적 소비', english: 'Ethical consumption', pronunciation: 'yun-ri-jeok so-bi', example: '팬덤의 윤리적 소비가 논의돼.', exampleTranslation: 'Ethical consumption by fandoms is being discussed.' },
    { korean: '정신 건강', english: 'Mental health', pronunciation: 'jeong-sin geon-gang', example: '아이돌의 정신 건강 보호가 중요해.', exampleTranslation: 'Protecting idols\' mental health is important.' },
    { korean: '소진 증후군', english: 'Burnout syndrome', pronunciation: 'so-jin jeung-hu-gun', example: '과도한 스케줄로 소진 증후군이 생겨.', exampleTranslation: 'Burnout syndrome develops from excessive schedules.' },
    { korean: '예술적 표현', english: 'Artistic expression', pronunciation: 'ye-sul-jeok pyo-hyeon', example: '예술적 표현의 자유가 중요해.', exampleTranslation: 'Freedom of artistic expression is important.' },
    { korean: '총체예술', english: 'Gesamtkunstwerk (total artwork)', pronunciation: 'chong-che-ye-sul', example: '케이팝은 총체예술에 가까워.', exampleTranslation: 'K-Pop is close to a total artwork.' },
    { korean: '문화적 전유', english: 'Cultural appropriation', pronunciation: 'mun-hwa-jeok jeon-yu', example: '문화적 전유 논란이 있었어.', exampleTranslation: 'There was a cultural appropriation controversy.' },
    { korean: '초국가적', english: 'Transnational', pronunciation: 'cho-guk-ga-jeok', example: '케이팝은 초국가적 현상이야.', exampleTranslation: 'K-Pop is a transnational phenomenon.' },
    { korean: '매개체', english: 'Medium / Mediator', pronunciation: 'mae-gae-che', example: '음악이 문화 교류의 매개체야.', exampleTranslation: 'Music is a medium for cultural exchange.' },
  ],
};
