import { ThemeWord } from '../theme-data';

export const SLANG_WORDS: Record<number, ThemeWord[]> = {
  1: [
    { korean: 'ㅋㅋ', english: 'Haha (laughing)', pronunciation: 'keu-keu', example: '너무 웃겨 ㅋㅋ', exampleTranslation: 'So funny haha.' },
    { korean: 'ㅎㅎ', english: 'Hehe (soft laugh)', pronunciation: 'heu-heu', example: '고마워 ㅎㅎ', exampleTranslation: 'Thanks hehe.' },
    { korean: '대박', english: 'Amazing / Jackpot', pronunciation: 'dae-bak', example: '대박! 진짜야?', exampleTranslation: 'Amazing! Really?' },
    { korean: '화이팅', english: 'Fighting / You can do it', pronunciation: 'hwa-i-ting', example: '시험 화이팅!', exampleTranslation: 'Good luck on the exam!' },
    { korean: 'ㅠㅠ', english: 'Crying face', pronunciation: 'yu-yu', example: '너무 슬퍼 ㅠㅠ', exampleTranslation: 'So sad (crying).' },
    { korean: 'ㅜㅜ', english: 'Tears / Crying', pronunciation: 'u-u', example: '시험 망했어 ㅜㅜ', exampleTranslation: 'I failed the exam (crying).' },
    { korean: 'ㅇㅇ', english: 'Yes / Yeah', pronunciation: 'eung-eung', example: 'ㅇㅇ 알겠어.', exampleTranslation: 'Yeah, got it.' },
    { korean: 'ㄴㄴ', english: 'No no', pronunciation: 'no-no', example: 'ㄴㄴ 그거 아니야.', exampleTranslation: 'No no, that is not it.' },
    { korean: 'ㄱㄱ', english: 'Go go / Let us go', pronunciation: 'go-go', example: '밥 먹으러 ㄱㄱ', exampleTranslation: 'Let us go eat.' },
    { korean: 'ㅇㅋ', english: 'OK', pronunciation: 'o-kei', example: 'ㅇㅋ 나중에 보자.', exampleTranslation: 'OK, see you later.' },
    { korean: '짱', english: 'The best / Awesome', pronunciation: 'jjang', example: '너 짱이야!', exampleTranslation: 'You are the best!' },
    { korean: '꿀', english: 'Honey / Something great', pronunciation: 'kkul', example: '이거 꿀팁이야.', exampleTranslation: 'This is a great tip.' },
    { korean: '헐', english: 'OMG / Wow', pronunciation: 'heol', example: '헐, 진짜?', exampleTranslation: 'OMG, really?' },
    { korean: '아싸', english: 'Yes! / Hooray', pronunciation: 'a-ssa', example: '아싸! 합격했어!', exampleTranslation: 'Yes! I passed!' },
    { korean: 'ㅇㄷ', english: 'Where?', pronunciation: 'eo-di', example: '지금 ㅇㄷ?', exampleTranslation: 'Where are you now?' },
    { korean: 'ㄳ', english: 'Thanks', pronunciation: 'gam-sa', example: 'ㄳ 도와줘서.', exampleTranslation: 'Thanks for helping.' },
    { korean: 'ㅈㅅ', english: 'Sorry', pronunciation: 'joe-song', example: 'ㅈㅅ 늦었어.', exampleTranslation: 'Sorry, I am late.' },
    { korean: 'ㅂㅂ', english: 'Bye bye', pronunciation: 'ba-i-ba-i', example: '나 간다 ㅂㅂ', exampleTranslation: 'I am leaving, bye bye.' },
    { korean: '넹', english: 'Yes (cute)', pronunciation: 'neng', example: '넹 알겠습니다!', exampleTranslation: 'Yes, understood!' },
    { korean: '넵', english: 'Yes (polite cute)', pronunciation: 'nep', example: '넵! 바로 할게요.', exampleTranslation: 'Yes! I will do it right away.' },
    { korean: '웅', english: 'Yeah (casual)', pronunciation: 'ung', example: '웅, 맞아.', exampleTranslation: 'Yeah, that is right.' },
    { korean: '당근', english: 'Of course (slang)', pronunciation: 'dang-geun', example: '당근이지!', exampleTranslation: 'Of course!' },
    { korean: '완전', english: 'Totally / Completely', pronunciation: 'wan-jeon', example: '완전 맛있어!', exampleTranslation: 'Totally delicious!' },
    { korean: '존나', english: 'Very / Extremely (vulgar)', pronunciation: 'jon-na', example: '존나 웃기다.', exampleTranslation: 'Extremely funny.' },
    { korean: '졸라', english: 'Very (slang)', pronunciation: 'jol-la', example: '졸라 재밌어.', exampleTranslation: 'Really fun.' },
    { korean: '겁나', english: 'Really / Super', pronunciation: 'geom-na', example: '겁나 빠르다.', exampleTranslation: 'Super fast.' },
    { korean: '개', english: 'Very / Super (prefix)', pronunciation: 'gae', example: '개맛있어!', exampleTranslation: 'Super delicious!' },
    { korean: '핵', english: 'Ultra / Nuclear (intensifier)', pronunciation: 'haek', example: '핵귀여워!', exampleTranslation: 'Ultra cute!' },
    { korean: '꺄', english: 'Squeal of excitement', pronunciation: 'kkya', example: '꺄! 좋아!', exampleTranslation: 'Squeal! I love it!' },
    { korean: '흠', english: 'Hmm', pronunciation: 'heum', example: '흠... 잘 모르겠어.', exampleTranslation: 'Hmm... I am not sure.' },
    { korean: '엥', english: 'Huh? / What?', pronunciation: 'eng', example: '엥? 무슨 말이야?', exampleTranslation: 'Huh? What do you mean?' },
    { korean: '잉', english: 'Huh? (cute)', pronunciation: 'ing', example: '잉? 어디 갔어?', exampleTranslation: 'Huh? Where did you go?' },
    { korean: '오키', english: 'Okie / OK', pronunciation: 'o-ki', example: '오키 그러자!', exampleTranslation: 'Okie, let us do that!' },
    { korean: '구래', english: 'OK then (casual)', pronunciation: 'gu-rae', example: '구래 알겠어.', exampleTranslation: 'OK then, I understand.' },
    { korean: '안녕', english: 'Hi / Bye (casual)', pronunciation: 'an-nyeong', example: '안녕~ 잘 지냈어?', exampleTranslation: 'Hi~ How have you been?' },
    { korean: '방가', english: 'Nice to see you (slang)', pronunciation: 'bang-ga', example: '오랜만이야! 방가!', exampleTranslation: 'Long time no see! Nice to see you!' },
    { korean: '수고', english: 'Good work (abbreviated)', pronunciation: 'su-go', example: '오늘도 수고!', exampleTranslation: 'Good work today too!' },
    { korean: '고고', english: 'Let us go', pronunciation: 'go-go', example: '카페 고고!', exampleTranslation: 'Let us go to a cafe!' },
    { korean: '꿀잼', english: 'Super fun / Entertaining', pronunciation: 'kkul-jaem', example: '이 드라마 꿀잼이야!', exampleTranslation: 'This drama is super fun!' },
    { korean: '노잼', english: 'Not fun / Boring', pronunciation: 'no-jaem', example: '이 영화 노잼이야.', exampleTranslation: 'This movie is boring.' },
    { korean: '맛집', english: 'Good restaurant', pronunciation: 'mat-jip', example: '여기 맛집이야!', exampleTranslation: 'This is a great restaurant!' },
    { korean: '먹스타그램', english: 'Food Instagram', pronunciation: 'meok-seu-ta-geu-raem', example: '먹스타그램 올려야지.', exampleTranslation: 'I should post on food Instagram.' },
    { korean: '셀스타그램', english: 'Selfie Instagram', pronunciation: 'sel-seu-ta-geu-raem', example: '셀스타그램 찍자!', exampleTranslation: 'Let us take selfies for Instagram!' },
    { korean: '갠찮아', english: 'It is OK (texting)', pronunciation: 'gaen-chan-a', example: '갠찮아 걱정 마.', exampleTranslation: 'It is OK, do not worry.' },
    { korean: '미안', english: 'Sorry (casual)', pronunciation: 'mi-an', example: '미안 늦어서.', exampleTranslation: 'Sorry for being late.' },
    { korean: '고마워', english: 'Thanks (casual)', pronunciation: 'go-ma-wo', example: '고마워 진짜!', exampleTranslation: 'Thanks, really!' },
    { korean: '최고', english: 'The best', pronunciation: 'choe-go', example: '넌 최고야!', exampleTranslation: 'You are the best!' },
    { korean: '쩔어', english: 'Awesome / Sick', pronunciation: 'jjeor-eo', example: '이 노래 쩔어!', exampleTranslation: 'This song is awesome!' },
    { korean: '굿', english: 'Good', pronunciation: 'gut', example: '굿! 잘했어.', exampleTranslation: 'Good! Well done.' },
    { korean: '히히', english: 'Hehe (playful)', pronunciation: 'hi-hi', example: '히히 나 먼저 먹었어.', exampleTranslation: 'Hehe I ate first.' },
    { korean: '우와', english: 'Wow', pronunciation: 'u-wa', example: '우와 진짜 예쁘다!', exampleTranslation: 'Wow, really pretty!' },
    { korean: '아이고', english: 'Oh my / Goodness', pronunciation: 'a-i-go', example: '아이고, 피곤해.', exampleTranslation: 'Oh my, I am tired.' },
    { korean: '에이', english: 'Aw / Come on', pronunciation: 'e-i', example: '에이, 장난이야.', exampleTranslation: 'Aw, I am just kidding.' },
    { korean: '땡큐', english: 'Thank you (Konglish)', pronunciation: 'ttaeng-kyu', example: '땡큐! 최고야!', exampleTranslation: 'Thank you! You are the best!' },
    { korean: '쏘리', english: 'Sorry (Konglish)', pronunciation: 'sso-ri', example: '쏘리 ㅠㅠ 미안해.', exampleTranslation: 'Sorry (crying) I am sorry.' },
    { korean: '럽스타그램', english: 'Love Instagram / Couple post', pronunciation: 'reop-seu-ta-geu-raem', example: '럽스타그램 올리지 마.', exampleTranslation: 'Do not post couple photos.' },
    { korean: '셀카', english: 'Selfie', pronunciation: 'sel-ka', example: '셀카 찍자!', exampleTranslation: 'Let us take a selfie!' },
    { korean: '존예', english: 'Super pretty', pronunciation: 'jon-ye', example: '존예 실화냐?', exampleTranslation: 'So pretty, is this real?' },
    { korean: '존잘', english: 'Super handsome', pronunciation: 'jon-jal', example: '존잘이다 진짜.', exampleTranslation: 'So handsome, seriously.' },
    { korean: '맞팔', english: 'Follow back', pronunciation: 'mat-pal', example: '맞팔 해줄게!', exampleTranslation: 'I will follow you back!' },
    { korean: '좋아요', english: 'Like (SNS)', pronunciation: 'jo-a-yo', example: '좋아요 눌러 줘!', exampleTranslation: 'Press like!' },
    { korean: '댓글', english: 'Comment (online)', pronunciation: 'daet-geul', example: '댓글 달아 줘.', exampleTranslation: 'Leave a comment.' },
    { korean: '공유', english: 'Share (SNS)', pronunciation: 'gong-yu', example: '이거 공유해 줘.', exampleTranslation: 'Share this.' },
    { korean: '팔로우', english: 'Follow (SNS)', pronunciation: 'pal-lo-u', example: '팔로우 했어!', exampleTranslation: 'I followed you!' },
    { korean: '언팔', english: 'Unfollow', pronunciation: 'eon-pal', example: '걔가 나를 언팔했어.', exampleTranslation: 'They unfollowed me.' },
    { korean: '디엠', english: 'DM / Direct message', pronunciation: 'di-em', example: '디엠으로 보내 줘.', exampleTranslation: 'Send it by DM.' },
    { korean: '스토리', english: 'Story (SNS)', pronunciation: 'seu-to-ri', example: '스토리 올렸어!', exampleTranslation: 'I posted a story!' },
    { korean: '피드', english: 'Feed (SNS)', pronunciation: 'pi-deu', example: '피드 정리했어.', exampleTranslation: 'I cleaned up my feed.' },
    { korean: '태그', english: 'Tag (SNS)', pronunciation: 'tae-geu', example: '나 태그해 줘!', exampleTranslation: 'Tag me!' },
    { korean: '리플', english: 'Reply / Comment', pronunciation: 'ri-peul', example: '리플 달아 줘.', exampleTranslation: 'Leave a reply.' },
    { korean: '톡', english: 'KakaoTalk / Chat', pronunciation: 'tok', example: '톡 보내 줘.', exampleTranslation: 'Send me a KaTalk message.' },
    { korean: '카톡', english: 'KakaoTalk', pronunciation: 'ka-tok', example: '카톡으로 연락해.', exampleTranslation: 'Contact me on KakaoTalk.' },
    { korean: '프사', english: 'Profile picture', pronunciation: 'peu-sa', example: '프사 바꿨어!', exampleTranslation: 'I changed my profile picture!' },
    { korean: '배사', english: 'Background picture', pronunciation: 'bae-sa', example: '배사 예쁘다!', exampleTranslation: 'Your background picture is pretty!' },
    { korean: '읽씹', english: 'Read but not reply', pronunciation: 'ik-ssip', example: '또 읽씹이야?', exampleTranslation: 'Read and ignored again?' },
    { korean: '안읽씹', english: 'Not even read', pronunciation: 'an-ik-ssip', example: '안읽씹 당했어.', exampleTranslation: 'They did not even read my message.' },
    { korean: '이모티콘', english: 'Emoticon / Sticker', pronunciation: 'i-mo-ti-kon', example: '이모티콘 보내 줘!', exampleTranslation: 'Send me a sticker!' },
    { korean: '짤', english: 'Meme image / GIF', pronunciation: 'jjal', example: '재밌는 짤 봤어.', exampleTranslation: 'I saw a funny meme.' },
    { korean: '인스타', english: 'Instagram', pronunciation: 'in-seu-ta', example: '인스타에 올렸어.', exampleTranslation: 'I posted on Instagram.' },
    { korean: '유튜브', english: 'YouTube', pronunciation: 'yu-tyu-beu', example: '유튜브에서 봤어.', exampleTranslation: 'I saw it on YouTube.' },
    { korean: '구독', english: 'Subscribe', pronunciation: 'gu-dok', example: '구독 눌러 주세요!', exampleTranslation: 'Please subscribe!' },
    { korean: '알림', english: 'Notification', pronunciation: 'al-lim', example: '알림 설정했어.', exampleTranslation: 'I set up notifications.' },
    { korean: '검색', english: 'Search', pronunciation: 'geom-saek', example: '검색해 봐.', exampleTranslation: 'Search for it.' },
    { korean: '업로드', english: 'Upload', pronunciation: 'eop-lo-deu', example: '영상 업로드했어.', exampleTranslation: 'I uploaded the video.' },
    { korean: '다운로드', english: 'Download', pronunciation: 'da-un-lo-deu', example: '앱 다운로드해.', exampleTranslation: 'Download the app.' },
    { korean: '와이파이', english: 'Wi-Fi', pronunciation: 'wa-i-pa-i', example: '와이파이 연결해 줘.', exampleTranslation: 'Connect the Wi-Fi.' },
    { korean: '충전', english: 'Charge (phone)', pronunciation: 'chung-jeon', example: '폰 충전해야 돼.', exampleTranslation: 'I need to charge my phone.' },
    { korean: '배터리', english: 'Battery', pronunciation: 'bae-teo-ri', example: '배터리 없어!', exampleTranslation: 'No battery!' },
    { korean: '폰', english: 'Phone', pronunciation: 'pon', example: '폰 어디 있어?', exampleTranslation: 'Where is my phone?' },
    { korean: '앱', english: 'App', pronunciation: 'aep', example: '이 앱 좋아.', exampleTranslation: 'This app is good.' },
    { korean: '캡처', english: 'Screenshot', pronunciation: 'kaep-cheo', example: '캡처해서 보내 줘.', exampleTranslation: 'Take a screenshot and send it.' },
    { korean: '인증샷', english: 'Proof photo', pronunciation: 'in-jeung-syat', example: '인증샷 올려!', exampleTranslation: 'Post a proof photo!' },
    { korean: '꾸미기', english: 'Decorating / Customizing', pronunciation: 'kku-mi-gi', example: '프로필 꾸미기 했어.', exampleTranslation: 'I customized my profile.' },
    { korean: '반말', english: 'Informal speech', pronunciation: 'ban-mal', example: '반말해도 돼?', exampleTranslation: 'Can I speak casually?' },
    { korean: '존댓말', english: 'Formal speech', pronunciation: 'jon-daen-mal', example: '존댓말 쓰세요.', exampleTranslation: 'Please use formal speech.' },
    { korean: '멘붕', english: 'Mental breakdown', pronunciation: 'men-bung', example: '시험 보고 멘붕이야.', exampleTranslation: 'I had a mental breakdown after the exam.' },
    { korean: '심쿵', english: 'Heart flutter', pronunciation: 'sim-kung', example: '심쿵했어!', exampleTranslation: 'My heart fluttered!' },
    { korean: '뭐해', english: 'What are you doing? (texting)', pronunciation: 'mwo-hae', example: '뭐해? 심심해.', exampleTranslation: 'What are you doing? I am bored.' },
    { korean: '개이득', english: 'Big profit / Great deal', pronunciation: 'gae-i-deuk', example: '반값이면 개이득이지!', exampleTranslation: 'Half price is a great deal!' },
    { korean: '극호감', english: 'Extremely likeable', pronunciation: 'geuk-ho-gam', example: '첫인상이 극호감이야.', exampleTranslation: 'The first impression is extremely likeable.' },
  ],
  2: [
    { korean: '갑분싸', english: 'Sudden awkward silence', pronunciation: 'gap-bun-ssa', example: '그 말 하니까 갑분싸됐어.', exampleTranslation: 'It got awkward after that comment.' },
    { korean: '별다줄', english: 'Everything gets abbreviated', pronunciation: 'byeol-da-jul', example: '요즘 별다줄이야.', exampleTranslation: 'These days everything gets abbreviated.' },
    { korean: '인싸', english: 'Insider / Popular person', pronunciation: 'in-ssa', example: '걔는 완전 인싸야.', exampleTranslation: 'They are totally an insider.' },
    { korean: '아웃싸이더', english: 'Outsider / Loner', pronunciation: 'a-ut-ssa-i-deo', example: '나는 아웃싸이더라서 혼자 먹어.', exampleTranslation: 'I eat alone because I am an outsider.' },
    { korean: '존맛탱', english: 'Extremely delicious', pronunciation: 'jon-mat-taeng', example: '이 피자 존맛탱이야!', exampleTranslation: 'This pizza is extremely delicious!' },
    { korean: '핵노잼', english: 'Extremely boring', pronunciation: 'haek-no-jaem', example: '그 영화 핵노잼이었어.', exampleTranslation: 'That movie was extremely boring.' },
    { korean: '찐', english: 'Real / Genuine', pronunciation: 'jjin', example: '이거 찐이야.', exampleTranslation: 'This is the real deal.' },
    { korean: '레전드', english: 'Legend / Legendary', pronunciation: 'le-jeon-deu', example: '이 장면 레전드야.', exampleTranslation: 'This scene is legendary.' },
    { korean: '실화냐', english: 'Is this real?', pronunciation: 'sil-hwa-nya', example: '실화냐? 대박이다.', exampleTranslation: 'Is this real? Amazing.' },
    { korean: '인정', english: 'Acknowledged / Agree', pronunciation: 'in-jeong', example: '인정! 그 말이 맞아.', exampleTranslation: 'Agreed! That is correct.' },
    { korean: '극혐', english: 'Extreme disgust', pronunciation: 'geuk-hyeom', example: '벌레 극혐이야.', exampleTranslation: 'I absolutely hate bugs.' },
    { korean: '존버', english: 'Hold on tenaciously', pronunciation: 'jon-beo', example: '존버하면 이긴다.', exampleTranslation: 'If you hold on, you win.' },
    { korean: '갓', english: 'God (prefix for greatness)', pronunciation: 'gat', example: '갓겜이다!', exampleTranslation: 'This is an amazing game!' },
    { korean: '뇌절', english: 'Cringe / Overdoing it', pronunciation: 'noe-jeol', example: '그만해 뇌절이야.', exampleTranslation: 'Stop it, you are being cringe.' },
    { korean: '오지다', english: 'Intense / Awesome', pronunciation: 'o-ji-da', example: '이거 진짜 오지네.', exampleTranslation: 'This is really intense.' },
    { korean: '킹받다', english: 'To be annoyed / Triggered', pronunciation: 'king-bat-da', example: '킹받네 진짜.', exampleTranslation: 'So triggered, seriously.' },
    { korean: '억까', english: 'Unfair criticism', pronunciation: 'eok-kka', example: '그건 억까야.', exampleTranslation: 'That is unfair criticism.' },
    { korean: '쩐다', english: 'Rich / Incredible', pronunciation: 'jjeon-da', example: '돈 쩐다!', exampleTranslation: 'So rich!' },
    { korean: '개꿀', english: 'Super easy / Jackpot', pronunciation: 'gae-kkul', example: '이 과제 개꿀이야.', exampleTranslation: 'This assignment is super easy.' },
    { korean: '띠용', english: 'Surprised sound effect', pronunciation: 'tti-yong', example: '띠용? 이게 뭐야?', exampleTranslation: 'Huh? What is this?' },
    { korean: '뭔말', english: 'What are you saying? (abbreviation)', pronunciation: 'mwon-mal', example: '뭔말이야 그게?', exampleTranslation: 'What are you even saying?' },
    { korean: '짭', english: 'Fake / Counterfeit', pronunciation: 'jjap', example: '이거 짭 아니야?', exampleTranslation: 'Is this not fake?' },
    { korean: '꿀벌', english: 'Hard worker (lit. honey bee)', pronunciation: 'kkul-beol', example: '너 진짜 꿀벌이다.', exampleTranslation: 'You are really a hard worker.' },
    { korean: '뻥', english: 'Lie / Bluff', pronunciation: 'ppeong', example: '뻥치지 마.', exampleTranslation: 'Do not lie.' },
    { korean: '빠순이', english: 'Obsessive fan (female)', pronunciation: 'ppa-sun-i', example: '빠순이처럼 굴지 마.', exampleTranslation: 'Do not act like an obsessive fan.' },
    { korean: '일코', english: 'Pretending to be normal (fan hiding)', pronunciation: 'il-ko', example: '회사에서 일코 중이야.', exampleTranslation: 'I am hiding my fandom at work.' },
    { korean: '본캐', english: 'Main character / Main account', pronunciation: 'bon-kae', example: '이게 내 본캐야.', exampleTranslation: 'This is my main account.' },
    { korean: '부캐', english: 'Side character / Alt account', pronunciation: 'bu-kae', example: '부캐로 활동해.', exampleTranslation: 'I am active on my alt account.' },
    { korean: '취저', english: 'Hits my taste (abbreviation)', pronunciation: 'chwi-jeo', example: '이 노래 취저야!', exampleTranslation: 'This song is totally my taste!' },
    { korean: '갬성', english: 'Vibes / Aesthetic mood', pronunciation: 'gaem-seong', example: '이 카페 갬성이네.', exampleTranslation: 'This cafe has great vibes.' },
    { korean: '무물', english: 'Ask me anything', pronunciation: 'mu-mul', example: '심심하니까 무물 받아.', exampleTranslation: 'I am bored so ask me anything.' },
    { korean: '레게노', english: 'Legend (funny spelling)', pronunciation: 'le-ge-no', example: '이거 레게노 아니야?', exampleTranslation: 'Is this not legendary?' },
    { korean: '알잘딱깔센', english: 'Handle it well on your own', pronunciation: 'al-jal-ttak-kkal-sen', example: '알잘딱깔센으로 해 줘.', exampleTranslation: 'Handle it well on your own.' },
    { korean: '갈비', english: 'Like ratio (abbreviation)', pronunciation: 'gal-bi', example: '갈비가 반반이네.', exampleTranslation: 'The like ratio is 50-50.' },
    { korean: '만반잘부', english: 'Nice to meet you (abbreviation)', pronunciation: 'man-ban-jal-bu', example: '만반잘부! 잘 지내자.', exampleTranslation: 'Nice to meet you! Let us get along.' },
    { korean: '오놀아놈', english: 'Played today too (abbreviation)', pronunciation: 'o-nol-a-nom', example: '오놀아놈 인정.', exampleTranslation: 'Admit it, played again today.' },
    { korean: '커엽', english: 'Cute (deliberate misspelling)', pronunciation: 'keo-yeop', example: '강아지 커엽다!', exampleTranslation: 'The puppy is so cute!' },
    { korean: '웃프다', english: 'Funny but sad', pronunciation: 'ut-peu-da', example: '이 이야기 웃프다.', exampleTranslation: 'This story is funny but sad.' },
    { korean: '꼰대', english: 'Boomer / Old-fashioned person', pronunciation: 'kkon-dae', example: '완전 꼰대처럼 말하네.', exampleTranslation: 'Talking like a total boomer.' },
    { korean: '급식충', english: 'Immature kid (school lunch insect)', pronunciation: 'geup-sik-chung', example: '급식충같이 굴지 마.', exampleTranslation: 'Do not act like an immature kid.' },
    { korean: '갓생', english: 'Living productively (God life)', pronunciation: 'gat-saeng', example: '오늘 갓생 살았어!', exampleTranslation: 'I lived productively today!' },
    { korean: '벼락치기', english: 'Cramming before exam', pronunciation: 'byeo-rak-chi-gi', example: '시험 전날 벼락치기했어.', exampleTranslation: 'I crammed the night before the exam.' },
    { korean: '올킬', english: 'All-kill / Perfect sweep', pronunciation: 'ol-kil', example: '음악 차트 올킬이야!', exampleTranslation: 'They swept all the music charts!' },
    { korean: '번아웃', english: 'Burnout', pronunciation: 'beon-a-ut', example: '번아웃 왔어.', exampleTranslation: 'I have burnout.' },
    { korean: '손민수', english: 'Copying someone (from a character name)', pronunciation: 'son-min-su', example: '그거 손민수한 거지?', exampleTranslation: 'You copied that, right?' },
    { korean: '갬축', english: 'Congrats (abbreviation)', pronunciation: 'gaem-chuk', example: '합격 갬축!', exampleTranslation: 'Congrats on passing!' },
    { korean: '점메추', english: 'Lunch recommendation (abbreviation)', pronunciation: 'jeom-me-chu', example: '점메추 해 줘!', exampleTranslation: 'Give me a lunch recommendation!' },
    { korean: '저메추', english: 'Dinner recommendation (abbreviation)', pronunciation: 'jeo-me-chu', example: '저메추 뭐가 좋을까?', exampleTranslation: 'What is a good dinner recommendation?' },
    { korean: '비담', english: 'Visual in charge (abbreviation)', pronunciation: 'bi-dam', example: '걔가 우리 팀 비담이야.', exampleTranslation: 'They are the visual of our team.' },
    { korean: '그냥저냥', english: 'So-so / Meh', pronunciation: 'geu-nyang-jeo-nyang', example: '그냥저냥 살고 있어.', exampleTranslation: 'I am living so-so.' },
    { korean: '가성비', english: 'Cost-effectiveness / Value for money', pronunciation: 'ga-seong-bi', example: '이거 가성비 좋아!', exampleTranslation: 'This has great value for money!' },
    { korean: '가심비', english: 'Emotional satisfaction value', pronunciation: 'ga-sim-bi', example: '가심비로 따지면 이게 낫지.', exampleTranslation: 'In terms of emotional value, this is better.' },
    { korean: '소확행', english: 'Small but certain happiness', pronunciation: 'so-hwak-haeng', example: '커피 한 잔이 소확행이야.', exampleTranslation: 'A cup of coffee is a small certain happiness.' },
    { korean: '워라밸', english: 'Work-life balance', pronunciation: 'wo-ra-bael', example: '워라밸 좋은 회사 가고 싶어.', exampleTranslation: 'I want to work at a company with good work-life balance.' },
    { korean: '혼밥', english: 'Eating alone', pronunciation: 'hon-bap', example: '오늘도 혼밥이야.', exampleTranslation: 'Eating alone again today.' },
    { korean: '혼술', english: 'Drinking alone', pronunciation: 'hon-sul', example: '혼술 한잔 할까?', exampleTranslation: 'Shall I have a drink alone?' },
    { korean: '혼코노', english: 'Karaoke alone', pronunciation: 'hon-ko-no', example: '혼코노 갔다 왔어.', exampleTranslation: 'I went to karaoke alone.' },
    { korean: '텐션', english: 'Energy / Excitement level', pronunciation: 'ten-syeon', example: '텐션 높아!', exampleTranslation: 'High energy!' },
    { korean: '팩트폭력', english: 'Harsh truth (fact violence)', pronunciation: 'paek-teu-pok-lyeok', example: '팩폭 당했어.', exampleTranslation: 'I was hit with a harsh truth.' },
    { korean: '풀매', english: 'Full makeup', pronunciation: 'pul-mae', example: '오늘 풀매했어.', exampleTranslation: 'I did full makeup today.' },
    { korean: '생얼', english: 'Bare face / No makeup', pronunciation: 'saeng-eol', example: '생얼도 예뻐!', exampleTranslation: 'Pretty even without makeup!' },
    { korean: '현타', english: 'Reality check / Coming back to reality', pronunciation: 'hyeon-ta', example: '쇼핑 후에 현타 왔어.', exampleTranslation: 'Reality hit me after shopping.' },
    { korean: '뽕', english: 'Thrill / Rush', pronunciation: 'ppong', example: '운동하면 뽕 오지.', exampleTranslation: 'You get a rush from exercising.' },
    { korean: '혼영', english: 'Watching movie alone', pronunciation: 'hon-yeong', example: '혼영도 나쁘지 않아.', exampleTranslation: 'Watching a movie alone is not bad.' },
    { korean: '할많하않', english: 'Lots to say but will not', pronunciation: 'hal-man-ha-an', example: '할많하않... 그냥 넘어가자.', exampleTranslation: 'So much to say but I will not... Let us move on.' },
    { korean: '고답이', english: 'Expected / Predictable answer', pronunciation: 'go-dap-i', example: '그건 고답이지.', exampleTranslation: 'That is the expected answer.' },
    { korean: '직관', english: 'Watching live (sports/concert)', pronunciation: 'jik-gwan', example: '이번 주말에 직관 가!', exampleTranslation: 'I am going to watch live this weekend!' },
    { korean: '핫플', english: 'Hot place / Trending spot', pronunciation: 'hat-peul', example: '여기 요즘 핫플이야.', exampleTranslation: 'This place is trending these days.' },
    { korean: '가보자고', english: 'Let us do it / Let us go for it', pronunciation: 'ga-bo-ja-go', example: '가보자고! 해보는 거야!', exampleTranslation: 'Let us go for it! Just try!' },
    { korean: '어쩔티비', english: 'So what? Deal with it', pronunciation: 'eo-jjeol-ti-bi', example: '싫으면 어쩔티비.', exampleTranslation: 'If you do not like it, deal with it.' },
    { korean: '저쩔티비', english: 'Response to "so what"', pronunciation: 'jeo-jjeol-ti-bi', example: '어쩔티비? 저쩔티비!', exampleTranslation: 'So what? Right back at you!' },
    { korean: '삼귀다', english: 'Pre-dating / Getting to know someone', pronunciation: 'sam-gwi-da', example: '지금 삼귀는 중이야.', exampleTranslation: 'We are in the getting-to-know stage.' },
    { korean: '썸', english: 'Flirting stage / Something going on', pronunciation: 'sseom', example: '우리 썸 타는 중이야.', exampleTranslation: 'We are in the flirting stage.' },
    { korean: '밀당', english: 'Push-pull (in dating)', pronunciation: 'mil-dang', example: '밀당하지 마.', exampleTranslation: 'Do not play push-pull.' },
    { korean: '쿨내', english: 'Cool vibe / Playing it cool', pronunciation: 'kul-nae', example: '쿨내 진동이야.', exampleTranslation: 'The cool vibe is strong.' },
    { korean: '설레다', english: 'To feel excited / Flutter', pronunciation: 'seol-le-da', example: '설레서 잠이 안 와.', exampleTranslation: 'I cannot sleep because I am excited.' },
    { korean: '모쏠', english: 'Never dated before', pronunciation: 'mo-ssol', example: '나 모쏠이야 ㅠㅠ', exampleTranslation: 'I have never dated (crying).' },
    { korean: '과몰입', english: 'Getting too invested', pronunciation: 'gwa-mol-ip', example: '드라마에 과몰입했어.', exampleTranslation: 'I got too invested in the drama.' },
    { korean: '관종', english: 'Attention seeker', pronunciation: 'gwan-jong', example: '완전 관종이네.', exampleTranslation: 'Total attention seeker.' },
    { korean: '복세편살', english: 'Live comfortably (abbreviation)', pronunciation: 'bok-se-pyeon-sal', example: '복세편살이 목표야.', exampleTranslation: 'My goal is to live comfortably.' },
    { korean: '쩝쩝박사', english: 'Food expert / Foodie', pronunciation: 'jjeop-jjeop-bak-sa', example: '넌 진짜 쩝쩝박사야.', exampleTranslation: 'You are a true foodie.' },
    { korean: '스불재', english: 'Will not miss the fun (abbreviation)', pronunciation: 'seu-bul-jae', example: '유행은 스불재!', exampleTranslation: 'Will not miss out on trends!' },
    { korean: '존웃', english: 'Super funny', pronunciation: 'jon-ut', example: '이거 존웃이야 ㅋㅋ', exampleTranslation: 'This is super funny haha.' },
    { korean: '갓벽', english: 'God + perfect', pronunciation: 'gat-byeok', example: '이 디자인 갓벽이야.', exampleTranslation: 'This design is god-tier perfect.' },
    { korean: '머선129', english: 'What is this (dialect meme)', pronunciation: 'meo-seon-il-i-gu', example: '머선129... 이게 뭐야.', exampleTranslation: 'What on earth... what is this.' },
    { korean: '좋댓구알', english: 'Like-comment-subscribe-notify', pronunciation: 'jot-daet-gu-al', example: '좋댓구알 부탁드립니다!', exampleTranslation: 'Like, comment, subscribe, and turn on notifications!' },
    { korean: '갈무리', english: 'Screenshot / Capture', pronunciation: 'gal-mu-ri', example: '대화 갈무리했어.', exampleTranslation: 'I screenshotted the conversation.' },
    { korean: '비번', english: 'Password (abbreviation)', pronunciation: 'bi-beon', example: '와이파이 비번 뭐야?', exampleTranslation: 'What is the Wi-Fi password?' },
    { korean: '드디어', english: 'Finally', pronunciation: 'deu-di-eo', example: '드디어 끝났다!', exampleTranslation: 'Finally finished!' },
    { korean: '솔직히', english: 'Honestly', pronunciation: 'sol-jik-hi', example: '솔직히 별로야.', exampleTranslation: 'Honestly, it is not great.' },
    { korean: '리얼', english: 'Real / For real', pronunciation: 'ri-eol', example: '리얼? 진짜야?', exampleTranslation: 'For real? Is it true?' },
    { korean: 'TMI', english: 'Too much information', pronunciation: 'ti-em-a-i', example: 'TMI인데 나 오늘 늦잠 잤어.', exampleTranslation: 'TMI but I overslept today.' },
    { korean: 'TMO', english: 'Too much opinion', pronunciation: 'ti-em-o', example: '그건 좀 TMO인데.', exampleTranslation: 'That is a bit too much opinion.' },
    { korean: 'JMT', english: 'Super delicious (Jeon-mal-mat-it)', pronunciation: 'je-i-em-ti', example: '이 떡볶이 JMT!', exampleTranslation: 'This tteokbokki is delicious!' },
    { korean: 'MBTI', english: 'MBTI personality type', pronunciation: 'em-bi-ti-a-i', example: 'MBTI가 뭐야?', exampleTranslation: 'What is your MBTI?' },
    { korean: '개취', english: 'Personal preference (abbreviation)', pronunciation: 'gae-chwi', example: '그건 개취야.', exampleTranslation: 'That is personal preference.' },
    { korean: '띵작', english: 'Masterpiece (slang)', pronunciation: 'tting-jak', example: '이 영화 띵작이야.', exampleTranslation: 'This movie is a masterpiece.' },
    { korean: '뜻밖의행복', english: 'Unexpected happiness', pronunciation: 'tteut-bakk-ui-haeng-bok', example: '뜻밖의 행복을 찾았어.', exampleTranslation: 'I found unexpected happiness.' },
    { korean: '팬심', english: 'Fan heart / Devotion as a fan', pronunciation: 'paen-sim', example: '팬심으로 사는 거야.', exampleTranslation: 'I live on my fan devotion.' },
    { korean: '갓띵작', english: 'God-tier masterpiece', pronunciation: 'gat-tting-jak', example: '이번 시즌 갓띵작이야.', exampleTranslation: 'This season is a god-tier masterpiece.' },
  ],
  3: [
    { korean: '어그로', english: 'Aggro / Trolling for attention', pronunciation: 'eo-geu-ro', example: '어그로 끌지 마.', exampleTranslation: 'Do not troll for attention.' },
    { korean: '정보글', english: 'Information post', pronunciation: 'jeong-bo-geul', example: '좋은 정보글이네요.', exampleTranslation: 'This is a good information post.' },
    { korean: '스압', english: 'Scroll pressure (long post warning)', pronunciation: 'seu-ap', example: '스압 주의!', exampleTranslation: 'Warning: long post ahead!' },
    { korean: '귀요미', english: 'Cutie / Cute person', pronunciation: 'gwi-yo-mi', example: '우리 아이 귀요미야!', exampleTranslation: 'My child is such a cutie!' },
    { korean: '롤', english: 'LOL / League of Legends', pronunciation: 'rol', example: '롤 한 판 하자.', exampleTranslation: 'Let us play a game of LoL.' },
    { korean: '겜', english: 'Game (abbreviation)', pronunciation: 'gem', example: '겜 하러 가자.', exampleTranslation: 'Let us go play games.' },
    { korean: '트수', english: 'Twitter user (abbreviation)', pronunciation: 'teu-su', example: '트수들 사이에서 화제야.', exampleTranslation: 'It is a hot topic among Twitter users.' },
    { korean: '디시', english: 'DCinside (Korean forum)', pronunciation: 'di-si', example: '디시에서 봤어.', exampleTranslation: 'I saw it on DCinside.' },
    { korean: '에펨코리아', english: 'FM Korea (Korean forum)', pronunciation: 'e-pem-ko-ri-a', example: '에펨코리아에 글 올렸어.', exampleTranslation: 'I posted on FM Korea.' },
    { korean: '꿀팁', english: 'Honey tip / Great advice', pronunciation: 'kkul-tip', example: '꿀팁 공유합니다.', exampleTranslation: 'Sharing a great tip.' },
    { korean: '브금', english: 'BGM / Background music', pronunciation: 'beu-geum', example: '이 브금 뭐야?', exampleTranslation: 'What is this BGM?' },
    { korean: '게시판', english: 'Bulletin board / Forum', pronunciation: 'ge-si-pan', example: '게시판에 올려 줘.', exampleTranslation: 'Post it on the forum.' },
    { korean: '채널', english: 'Channel', pronunciation: 'chae-neol', example: '유튜브 채널 시작했어.', exampleTranslation: 'I started a YouTube channel.' },
    { korean: '실시간', english: 'Real-time / Trending', pronunciation: 'sil-si-gan', example: '실시간 검색어 1위야!', exampleTranslation: 'It is number 1 on real-time search!' },
    { korean: '리트윗', english: 'Retweet', pronunciation: 'ri-teu-wit', example: '이거 리트윗해 줘.', exampleTranslation: 'Retweet this.' },
    { korean: '밈', english: 'Meme', pronunciation: 'mim', example: '이 밈 존웃이야 ㅋㅋ', exampleTranslation: 'This meme is so funny haha.' },
    { korean: '고인물', english: 'Veteran / Long-time expert', pronunciation: 'go-in-mul', example: '걔는 롤 고인물이야.', exampleTranslation: 'They are a LoL veteran.' },
    { korean: '뉴비', english: 'Newbie', pronunciation: 'nyu-bi', example: '뉴비라서 잘 몰라요.', exampleTranslation: 'I do not know well because I am a newbie.' },
    { korean: '트롤', english: 'Troll', pronunciation: 'teu-rol', example: '트롤하지 마.', exampleTranslation: 'Do not troll.' },
    { korean: '캐리', english: 'Carry (game)', pronunciation: 'kae-ri', example: '내가 캐리할게.', exampleTranslation: 'I will carry the game.' },
    { korean: '딜러', english: 'Dealer / DPS (game)', pronunciation: 'dil-leo', example: '딜러 한 명 더 필요해.', exampleTranslation: 'We need one more DPS.' },
    { korean: '탱커', english: 'Tanker (game)', pronunciation: 'taeng-keo', example: '탱커 역할 해 줘.', exampleTranslation: 'Play the tank role.' },
    { korean: '힐러', english: 'Healer (game)', pronunciation: 'hil-leo', example: '힐러 없으면 못 이겨.', exampleTranslation: 'We cannot win without a healer.' },
    { korean: 'GG', english: 'Good game', pronunciation: 'ji-ji', example: 'GG 잘했어.', exampleTranslation: 'Good game, well played.' },
    { korean: '버프', english: 'Buff (game)', pronunciation: 'beo-peu', example: '이번 패치에 버프 받았어.', exampleTranslation: 'Got buffed in this patch.' },
    { korean: '너프', english: 'Nerf (game)', pronunciation: 'neo-peu', example: '이 캐릭터 너프 좀 해라.', exampleTranslation: 'Please nerf this character.' },
    { korean: '쿨타임', english: 'Cooldown (game)', pronunciation: 'kul-ta-im', example: '쿨타임 아직 안 돌았어.', exampleTranslation: 'Cooldown is not ready yet.' },
    { korean: '파밍', english: 'Farming (game)', pronunciation: 'pa-ming', example: '파밍 좀 하고 올게.', exampleTranslation: 'I will farm a bit and come back.' },
    { korean: '스킬', english: 'Skill (game)', pronunciation: 'seu-kil', example: '스킬 쓰는 타이밍이 중요해.', exampleTranslation: 'The timing of using skills is important.' },
    { korean: '랭크', english: 'Rank (game)', pronunciation: 'raeng-keu', example: '랭크 게임 하자.', exampleTranslation: 'Let us play ranked.' },
    { korean: '솔랭', english: 'Solo ranked game', pronunciation: 'sol-raeng', example: '오늘 솔랭 돌려야지.', exampleTranslation: 'I should play solo ranked today.' },
    { korean: '듀오', english: 'Duo (game)', pronunciation: 'dyu-o', example: '듀오 할 사람?', exampleTranslation: 'Anyone want to duo?' },
    { korean: '매크로', english: 'Macro (game strategy)', pronunciation: 'mae-keu-ro', example: '매크로가 중요해.', exampleTranslation: 'Macro strategy is important.' },
    { korean: '피딩', english: 'Feeding / Dying too much (game)', pronunciation: 'pi-ding', example: '피딩하지 마!', exampleTranslation: 'Stop feeding!' },
    { korean: '원딜', english: 'ADC / Marksman (game)', pronunciation: 'won-dil', example: '원딜이 잘해야 이겨.', exampleTranslation: 'The ADC needs to play well to win.' },
    { korean: '정글', english: 'Jungler (game)', pronunciation: 'jeong-geul', example: '정글 도와줘!', exampleTranslation: 'Help me, jungler!' },
    { korean: '서폿', english: 'Support (game)', pronunciation: 'seo-pot', example: '서폿 감사해요.', exampleTranslation: 'Thanks, support.' },
    { korean: '핫도그', english: 'Hot issue / Trending debate', pronunciation: 'hat-do-geu', example: '이거 지금 핫도그야.', exampleTranslation: 'This is a trending debate right now.' },
    { korean: '입털', english: 'Chatting / Running mouth', pronunciation: 'ip-teol', example: '입털지 말고 일해.', exampleTranslation: 'Stop chatting and work.' },
    { korean: '키보드 워리어', english: 'Keyboard warrior', pronunciation: 'ki-bo-deu wo-ri-eo', example: '키보드 워리어가 많아.', exampleTranslation: 'There are many keyboard warriors.' },
    { korean: '댓글알바', english: 'Paid commenter', pronunciation: 'daet-geul-al-ba', example: '댓글알바 아니야?', exampleTranslation: 'Are you not a paid commenter?' },
    { korean: '잼민이', english: 'Annoying young kid (online)', pronunciation: 'jaem-min-i', example: '잼민이들이 도배했어.', exampleTranslation: 'The kids spammed everywhere.' },
    { korean: '도배', english: 'Spamming / Flooding', pronunciation: 'do-bae', example: '도배하지 마세요.', exampleTranslation: 'Please do not spam.' },
    { korean: '정모', english: 'Offline meetup', pronunciation: 'jeong-mo', example: '이번 달에 정모 하자.', exampleTranslation: 'Let us have a meetup this month.' },
    { korean: '번개', english: 'Flash meetup / Impromptu gathering', pronunciation: 'beon-gae', example: '오늘 저녁 번개!', exampleTranslation: 'Flash meetup tonight!' },
    { korean: '작성자', english: 'Original poster / Author', pronunciation: 'jak-seong-ja', example: '작성자 본인입니다.', exampleTranslation: 'I am the original poster.' },
    { korean: '익명', english: 'Anonymous', pronunciation: 'ik-myeong', example: '익명으로 올릴게.', exampleTranslation: 'I will post anonymously.' },
    { korean: '움짤', english: 'Animated GIF', pronunciation: 'um-jjal', example: '이 움짤 웃겨 ㅋㅋ', exampleTranslation: 'This GIF is funny haha.' },
    { korean: '혐짤', english: 'Disturbing image', pronunciation: 'hyeom-jjal', example: '혐짤 주의!', exampleTranslation: 'Warning: disturbing image!' },
    { korean: '짤방', english: 'Image post / Meme image', pronunciation: 'jjal-bang', example: '짤방 저장했어.', exampleTranslation: 'I saved the meme image.' },
    { korean: '드립', english: 'Joke / Witty comment', pronunciation: 'deu-rip', example: '그 드립 존웃이야.', exampleTranslation: 'That joke is hilarious.' },
    { korean: '패드립', english: 'Parent-dissing joke (offensive)', pronunciation: 'pae-deu-rip', example: '패드립은 선 넘어.', exampleTranslation: 'Parent-dissing jokes cross the line.' },
    { korean: '어그로꾼', english: 'Troll / Attention seeker', pronunciation: 'eo-geu-ro-kkun', example: '어그로꾼 무시해.', exampleTranslation: 'Ignore the troll.' },
    { korean: '대리', english: 'Boosting (game)', pronunciation: 'dae-ri', example: '대리는 금지야.', exampleTranslation: 'Boosting is forbidden.' },
    { korean: '핵유저', english: 'Hacker / Cheat user (game)', pronunciation: 'haek-yu-jeo', example: '핵유저 신고했어.', exampleTranslation: 'I reported the cheat user.' },
    { korean: '치트키', english: 'Cheat key', pronunciation: 'chi-teu-ki', example: '인생 치트키가 있으면 좋겠다.', exampleTranslation: 'I wish there was a cheat key for life.' },
    { korean: '버그', english: 'Bug / Glitch', pronunciation: 'beo-geu', example: '이거 버그 아니야?', exampleTranslation: 'Is this not a bug?' },
    { korean: '렉', english: 'Lag', pronunciation: 'rek', example: '렉 걸려서 못 했어.', exampleTranslation: 'I could not play because of lag.' },
    { korean: '서버', english: 'Server', pronunciation: 'seo-beo', example: '서버 터졌어!', exampleTranslation: 'The server crashed!' },
    { korean: '리부팅', english: 'Rebooting / Restart', pronunciation: 'ri-bu-ting', example: '컴퓨터 리부팅해야 돼.', exampleTranslation: 'I need to reboot the computer.' },
    { korean: '구글링', english: 'Googling', pronunciation: 'gu-geul-ling', example: '구글링해 봐.', exampleTranslation: 'Try Googling it.' },
    { korean: '나무위키', english: 'Namuwiki (Korean wiki)', pronunciation: 'na-mu-wi-ki', example: '나무위키에 다 있어.', exampleTranslation: 'It is all on Namuwiki.' },
    { korean: '클릭', english: 'Click', pronunciation: 'keul-lik', example: '여기 클릭해 봐.', exampleTranslation: 'Click here.' },
    { korean: '공감', english: 'Empathy / Agree (upvote)', pronunciation: 'gong-gam', example: '공감 눌렀어요.', exampleTranslation: 'I pressed agree.' },
    { korean: '비공감', english: 'Disagree (downvote)', pronunciation: 'bi-gong-gam', example: '비공감이 더 많네.', exampleTranslation: 'There are more downvotes.' },
    { korean: '혼파망', english: 'Soul destroyed (abbreviation)', pronunciation: 'hon-pa-mang', example: '시험 결과 보고 혼파망.', exampleTranslation: 'My soul was destroyed after seeing the exam results.' },
    { korean: '무한도전', english: 'Infinite Challenge (show reference)', pronunciation: 'mu-han-do-jeon', example: '무한도전 다시 하면 좋겠다.', exampleTranslation: 'I wish Infinite Challenge would come back.' },
    { korean: '런닝맨', english: 'Running Man (show)', pronunciation: 'reon-ning-maen', example: '런닝맨 어제 봤어?', exampleTranslation: 'Did you watch Running Man yesterday?' },
    { korean: '음식점', english: 'Restaurant', pronunciation: 'eum-sik-jeom', example: '맛있는 음식점 추천해 줘.', exampleTranslation: 'Recommend a good restaurant.' },
    { korean: '플렉스', english: 'Flex / Show off spending', pronunciation: 'peul-lek-seu', example: '오늘은 플렉스할 거야!', exampleTranslation: 'I am going to flex today!' },
    { korean: '영끌', english: 'Borrowing everything possible', pronunciation: 'yeong-kkeul', example: '영끌해서 집 샀어.', exampleTranslation: 'I borrowed everything to buy a house.' },
    { korean: '빚투', english: 'Investing with debt', pronunciation: 'bit-tu', example: '빚투는 위험해.', exampleTranslation: 'Investing with debt is dangerous.' },
    { korean: '코인', english: 'Cryptocurrency', pronunciation: 'ko-in', example: '코인 투자했어?', exampleTranslation: 'Did you invest in crypto?' },
    { korean: '주린이', english: 'Stock market beginner', pronunciation: 'ju-rin-i', example: '나 주린이인데 추천해 줘.', exampleTranslation: 'I am a stock beginner, recommend something.' },
    { korean: '코린이', english: 'Crypto beginner', pronunciation: 'ko-rin-i', example: '코린이도 쉽게 할 수 있어.', exampleTranslation: 'Even crypto beginners can do it easily.' },
    { korean: '존버족', english: 'HODL gang / Diamond hands', pronunciation: 'jon-beo-jok', example: '나는 존버족이야.', exampleTranslation: 'I am in the HODL gang.' },
    { korean: '떡상', english: 'Skyrocketing (price)', pronunciation: 'tteok-sang', example: '이 코인 떡상했어!', exampleTranslation: 'This coin skyrocketed!' },
    { korean: '떡락', english: 'Plummeting (price)', pronunciation: 'tteok-rak', example: '주가가 떡락했어.', exampleTranslation: 'The stock price plummeted.' },
    { korean: '직딩', english: 'Office worker (slang)', pronunciation: 'jik-tting', example: '직딩은 힘들어.', exampleTranslation: 'Being an office worker is tough.' },
    { korean: '대딩', english: 'College student (slang)', pronunciation: 'dae-tting', example: '대딩 때가 좋았어.', exampleTranslation: 'College days were good.' },
    { korean: '자취', english: 'Living alone', pronunciation: 'ja-chwi', example: '자취 시작했어.', exampleTranslation: 'I started living alone.' },
    { korean: '조별과제', english: 'Group project (dreaded)', pronunciation: 'jo-byeol-gwa-je', example: '조별과제 또야?', exampleTranslation: 'Group project again?' },
    { korean: '무임승차', english: 'Free rider (group project)', pronunciation: 'mu-im-seung-cha', example: '무임승차하지 마.', exampleTranslation: 'Do not be a free rider.' },
    { korean: '광탈', english: 'Eliminated early', pronunciation: 'gwang-tal', example: '첫 라운드에서 광탈했어.', exampleTranslation: 'I was eliminated in the first round.' },
    { korean: '뻘글', english: 'Pointless post', pronunciation: 'ppeol-geul', example: '뻘글 올리지 마.', exampleTranslation: 'Do not post pointless stuff.' },
    { korean: '답정너', english: 'Already decided answer', pronunciation: 'dap-jeong-neo', example: '그건 답정너잖아.', exampleTranslation: 'You already decided the answer.' },
    { korean: '흑역사', english: 'Dark history / Past embarrassment', pronunciation: 'heuk-yeok-sa', example: '내 흑역사 들추지 마.', exampleTranslation: 'Do not dig up my dark history.' },
    { korean: '핵인싸', english: 'Super popular person', pronunciation: 'haek-in-ssa', example: '걔는 핵인싸야.', exampleTranslation: 'They are super popular.' },
    { korean: '커뮤', english: 'Community / Forum', pronunciation: 'keo-myu', example: '커뮤에서 핫한 글이야.', exampleTranslation: 'It is a hot post on the community.' },
    { korean: '반박불가', english: 'Irrefutable / Cannot argue', pronunciation: 'ban-bak-bul-ga', example: '이건 반박불가야.', exampleTranslation: 'This is irrefutable.' },
    { korean: '스포', english: 'Spoiler', pronunciation: 'seu-po', example: '스포하지 마!', exampleTranslation: 'No spoilers!' },
    { korean: '떡밥', english: 'Bait / Teaser / Discussion topic', pronunciation: 'tteok-bap', example: '새로운 떡밥이 나왔어.', exampleTranslation: 'New discussion bait came out.' },
    { korean: '오피셜', english: 'Official', pronunciation: 'o-pi-syeol', example: '오피셜로 확인됐어.', exampleTranslation: 'It was officially confirmed.' },
    { korean: '어그로성', english: 'Trollish / Baiting nature', pronunciation: 'eo-geu-ro-seong', example: '어그로성 글 신고했어.', exampleTranslation: 'I reported the baiting post.' },
    { korean: '인생겜', english: 'Game of a lifetime', pronunciation: 'in-saeng-gem', example: '이건 내 인생겜이야.', exampleTranslation: 'This is the game of my lifetime.' },
    { korean: '세젤예', english: 'Prettiest in the world (abbreviation)', pronunciation: 'se-jel-ye', example: '우리 언니 세젤예!', exampleTranslation: 'My older sister is the prettiest in the world!' },
    { korean: '세젤귀', english: 'Cutest in the world (abbreviation)', pronunciation: 'se-jel-gwi', example: '이 강아지 세젤귀야.', exampleTranslation: 'This puppy is the cutest in the world.' },
    { korean: '야민정음', english: 'Yaminjeongeum (visual wordplay)', pronunciation: 'ya-min-jeong-eum', example: '야민정음으로 머리를 띠리로 쓰기도 해.', exampleTranslation: 'In Yaminjeongeum, you write words with visually similar characters.' },
    { korean: '클라스', english: 'Class / Level (showing quality)', pronunciation: 'keul-la-seu', example: '역시 클라스가 다르네.', exampleTranslation: 'As expected, the class is different.' },
    { korean: '미존', english: 'Insanely handsome (abbreviation)', pronunciation: 'mi-jon', example: '걔 미존이야 진짜.', exampleTranslation: 'He is insanely handsome, seriously.' },
  ],
  4: [
    { korean: '시발비용', english: 'Stress-spending (frustration cost)', pronunciation: 'si-bal-bi-yong', example: '시발비용으로 치킨 시켰어.', exampleTranslation: 'I ordered chicken as stress-spending.' },
    { korean: '갓생러', english: 'Person living productively', pronunciation: 'gat-saeng-reo', example: '갓생러가 되고 싶어.', exampleTranslation: 'I want to be someone who lives productively.' },
    { korean: '내로남불', english: 'Double standard (ok for me, not for you)', pronunciation: 'nae-ro-nam-bul', example: '그건 내로남불이야.', exampleTranslation: 'That is a double standard.' },
    { korean: '선넘다', english: 'Cross the line', pronunciation: 'seon-neom-da', example: '그 말은 선 넘었어.', exampleTranslation: 'That comment crossed the line.' },
    { korean: '오은영', english: 'Dr. Oh Eun-young (therapy reference)', pronunciation: 'o-eun-yeong', example: '오은영 선생님이 필요해.', exampleTranslation: 'I need Dr. Oh Eun-young.' },
    { korean: '기승전결', english: 'Story arc (intro-rise-climax-end)', pronunciation: 'gi-seung-jeon-gyeol', example: '기승전치킨이네.', exampleTranslation: 'Everything leads back to chicken.' },
    { korean: '삼천포', english: 'Going off topic', pronunciation: 'sam-cheon-po', example: '또 삼천포로 빠졌네.', exampleTranslation: 'You went off topic again.' },
    { korean: '고구마', english: 'Frustrating (like choking on sweet potato)', pronunciation: 'go-gu-ma', example: '답답해서 고구마 100개야.', exampleTranslation: 'So frustrating, like eating 100 sweet potatoes.' },
    { korean: '사이다', english: 'Refreshing resolution (like soda)', pronunciation: 'sa-i-da', example: '사이다 전개였어!', exampleTranslation: 'That was a refreshing development!' },
    { korean: '국뽕', english: 'Excessive nationalism', pronunciation: 'guk-ppong', example: '국뽕이 너무 심해.', exampleTranslation: 'The nationalism is too excessive.' },
    { korean: '갬르가다', english: 'To gamble / Risk it all', pronunciation: 'gaem-reu-ga-da', example: '이번에 갬르갔어.', exampleTranslation: 'I gambled on this one.' },
    { korean: '프로불편러', english: 'Professional complainer', pronunciation: 'peu-ro-bul-pyeon-reo', example: '프로불편러 등장.', exampleTranslation: 'Here comes the professional complainer.' },
    { korean: '카공족', english: 'Study-at-cafe people', pronunciation: 'ka-gong-jok', example: '카공족이 자리를 다 차지했어.', exampleTranslation: 'The cafe studiers took all the seats.' },
    { korean: '빌런', english: 'Villain / Annoying person', pronunciation: 'bil-leon', example: '층간소음 빌런 때문에 못 자.', exampleTranslation: 'I cannot sleep because of the noise villain.' },
    { korean: '진상', english: 'Difficult customer / Rude person', pronunciation: 'jin-sang', example: '진상 손님 때문에 힘들었어.', exampleTranslation: 'It was hard because of a difficult customer.' },
    { korean: '을매나', english: 'How much (aegyo style)', pronunciation: 'eul-mae-na', example: '을매나 좋아하는데!', exampleTranslation: 'I like it so much!' },
    { korean: '뻔뻔하다', english: 'Shameless', pronunciation: 'ppeon-ppeon-ha-da', example: '뻔뻔하게 굴지 마.', exampleTranslation: 'Do not be shameless.' },
    { korean: '엄근진', english: 'Serious face (abbreviation)', pronunciation: 'eom-geun-jin', example: '왜 이렇게 엄근진이야?', exampleTranslation: 'Why so serious?' },
    { korean: '간떨어지다', english: 'Scared to death (liver drop)', pronunciation: 'gan-tteor-eo-ji-da', example: '간 떨어질 뻔했어.', exampleTranslation: 'I was scared to death.' },
    { korean: '빨리빨리', english: 'Hurry hurry (culture)', pronunciation: 'ppal-li-ppal-li', example: '빨리빨리 문화가 특징이야.', exampleTranslation: 'The hurry hurry culture is a defining trait.' },
    { korean: '눈치', english: 'Social awareness / Reading the room', pronunciation: 'nun-chi', example: '눈치가 빠르네.', exampleTranslation: 'You are quick at reading the room.' },
    { korean: '눈치게임', english: 'Game of social awareness', pronunciation: 'nun-chi-ge-im', example: '직장생활은 눈치게임이야.', exampleTranslation: 'Work life is a game of social awareness.' },
    { korean: '영혼없다', english: 'Soulless / Going through the motions', pronunciation: 'yeong-hon-eop-da', example: '영혼 없는 사과였어.', exampleTranslation: 'It was a soulless apology.' },
    { korean: '진심', english: 'Sincere / For real', pronunciation: 'jin-sim', example: '이건 진심이야.', exampleTranslation: 'This is sincere.' },
    { korean: '급발진', english: 'Sudden outburst / Rage', pronunciation: 'geup-bal-jin', example: '갑자기 급발진하지 마.', exampleTranslation: 'Do not suddenly have a rage outburst.' },
    { korean: '극대노', english: 'Extremely angry (abbreviation)', pronunciation: 'geuk-dae-no', example: '극대노 상태야 지금.', exampleTranslation: 'I am extremely angry right now.' },
    { korean: '소신발언', english: 'Speaking one is mind boldly', pronunciation: 'so-sin-bal-eon', example: '소신발언 합니다.', exampleTranslation: 'I am going to speak my mind boldly.' },
    { korean: '사바사', english: 'Depends on the person', pronunciation: 'sa-ba-sa', example: '그건 사바사야.', exampleTranslation: 'That depends on the person.' },
    { korean: '케바케', english: 'Case by case', pronunciation: 'ke-ba-ke', example: '그건 케바케지.', exampleTranslation: 'That is case by case.' },
    { korean: '뇌피셜', english: 'Personal opinion (brain + official)', pronunciation: 'noe-pi-syeol', example: '이건 뇌피셜이야.', exampleTranslation: 'This is just my personal opinion.' },
    { korean: '주작', english: 'Rigged / Scripted', pronunciation: 'ju-jak', example: '이거 주작 아니야?', exampleTranslation: 'Is this not rigged?' },
    { korean: '조작', english: 'Manipulation / Fabrication', pronunciation: 'jo-jak', example: '투표 조작 의혹이야.', exampleTranslation: 'There are vote manipulation suspicions.' },
    { korean: '편가르기', english: 'Taking sides / Division', pronunciation: 'pyeon-ga-reu-gi', example: '편가르기하지 마.', exampleTranslation: 'Do not take sides.' },
    { korean: '기레기', english: 'Trash journalist', pronunciation: 'gi-re-gi', example: '기레기 기사야 그거.', exampleTranslation: 'That is trash journalism.' },
    { korean: '찐따', english: 'Loser / Outcast (offensive)', pronunciation: 'jjin-tta', example: '그런 말 하면 안 돼.', exampleTranslation: 'You should not use that kind of word.' },
    { korean: '억울하다', english: 'Feeling wronged', pronunciation: 'eok-ul-ha-da', example: '억울해서 미치겠어.', exampleTranslation: 'I feel so wronged I could go crazy.' },
    { korean: '열폭', english: 'Jealous outburst (inferiority explosion)', pronunciation: 'yeol-pok', example: '열폭하지 마.', exampleTranslation: 'Do not have a jealous outburst.' },
    { korean: '흑우', english: 'Sucker / Gullible person', pronunciation: 'heuk-u', example: '이 가격에 사면 흑우야.', exampleTranslation: 'You are a sucker if you buy at this price.' },
    { korean: '갓물주', english: 'Generous landlord / God-tier owner', pronunciation: 'gat-mul-ju', example: '우리 갓물주 최고야.', exampleTranslation: 'Our landlord is the best.' },
    { korean: '마상', english: 'Emotional wound (heart damage)', pronunciation: 'ma-sang', example: '마상 입었어.', exampleTranslation: 'My feelings were hurt.' },
    { korean: '정색', english: 'Keeping a straight face / Dead serious', pronunciation: 'jeong-saek', example: '갑자기 정색하지 마.', exampleTranslation: 'Do not suddenly go dead serious.' },
    { korean: '너드', english: 'Nerd', pronunciation: 'neo-deu', example: '나는 너드라서 괜찮아.', exampleTranslation: 'I am a nerd so it is fine.' },
    { korean: '너나잘해', english: 'Mind your own business', pronunciation: 'neo-na-jal-hae', example: '너나 잘해 진짜.', exampleTranslation: 'Mind your own business, seriously.' },
    { korean: '비호감', english: 'Unlikeable / Off-putting', pronunciation: 'bi-ho-gam', example: '첫인상이 비호감이야.', exampleTranslation: 'The first impression is off-putting.' },
    { korean: '대환장', english: 'Total chaos / Pandemonium', pronunciation: 'dae-hwan-jang', example: '대환장 파티였어.', exampleTranslation: 'It was total pandemonium.' },
    { korean: '스윗하다', english: 'Sweet / Caring', pronunciation: 'seu-wit-ha-da', example: '남자친구가 스윗해.', exampleTranslation: 'My boyfriend is sweet.' },
    { korean: '츤데레', english: 'Tsundere / Cold outside warm inside', pronunciation: 'cheun-de-re', example: '걔는 츤데레야.', exampleTranslation: 'They are tsundere.' },
    { korean: '쿨하다', english: 'Cool / Unbothered', pronunciation: 'kul-ha-da', example: '쿨하게 넘어가자.', exampleTranslation: 'Let us let it go coolly.' },
    { korean: '스으앵', english: 'Passing by quickly (sound effect)', pronunciation: 'seu-eu-aeng', example: '시간이 스으앵 지나갔어.', exampleTranslation: 'Time flew by quickly.' },
    { korean: '킹왕짱', english: 'King of kings / Ultimate best', pronunciation: 'king-wang-jjang', example: '넌 킹왕짱이야!', exampleTranslation: 'You are the absolute best!' },
    { korean: '금수저', english: 'Born rich (gold spoon)', pronunciation: 'geum-su-jeo', example: '걔는 금수저야.', exampleTranslation: 'They were born rich.' },
    { korean: '흙수저', english: 'Born poor (dirt spoon)', pronunciation: 'heuk-su-jeo', example: '흙수저 탈출하고 싶어.', exampleTranslation: 'I want to escape poverty.' },
    { korean: '수저론', english: 'Spoon class theory', pronunciation: 'su-jeo-ron', example: '수저론이 현실이야.', exampleTranslation: 'Spoon class theory is reality.' },
    { korean: 'N포세대', english: 'Give-up generation', pronunciation: 'en-po-se-dae', example: 'N포세대라는 말이 슬프다.', exampleTranslation: 'The term give-up generation is sad.' },
    { korean: '헬조선', english: 'Hell Joseon (criticizing Korea)', pronunciation: 'hel-jo-seon', example: '헬조선이라는 말이 유행했어.', exampleTranslation: 'The term Hell Joseon was trending.' },
    { korean: '탈조선', english: 'Escaping Korea', pronunciation: 'tal-jo-seon', example: '탈조선하고 싶다는 사람도 있어.', exampleTranslation: 'Some people say they want to leave Korea.' },
    { korean: '이생망', english: 'This life is ruined (abbreviation)', pronunciation: 'i-saeng-mang', example: '이생망이야 나.', exampleTranslation: 'My life is ruined.' },
    { korean: '인생은실전', english: 'Life is no practice', pronunciation: 'in-saeng-eun-sil-jeon', example: '인생은 실전이야.', exampleTranslation: 'Life is the real deal, no practice.' },
    { korean: '뚝심', english: 'Determination / Grit', pronunciation: 'ttuk-sim', example: '뚝심 있게 밀어붙여.', exampleTranslation: 'Push through with determination.' },
    { korean: '오바이트', english: 'Over the top / Exaggerating', pronunciation: 'o-ba-i-teu', example: '그건 좀 오바이트야.', exampleTranslation: 'That is a bit over the top.' },
    { korean: '무념무상', english: 'Empty mind / No thoughts', pronunciation: 'mu-nyeom-mu-sang', example: '무념무상 상태야 지금.', exampleTranslation: 'I am in a state of no thoughts right now.' },
    { korean: '초딩', english: 'Elementary schooler (slang)', pronunciation: 'cho-tting', example: '초딩 때 생각나네.', exampleTranslation: 'It reminds me of elementary school days.' },
    { korean: '중딩', english: 'Middle schooler (slang)', pronunciation: 'jung-tting', example: '중딩 시절이 그립다.', exampleTranslation: 'I miss my middle school days.' },
    { korean: '고딩', english: 'High schooler (slang)', pronunciation: 'go-tting', example: '고딩이면 공부해야지.', exampleTranslation: 'If you are a high schooler, you should study.' },
    { korean: '학식', english: 'Campus cafeteria food', pronunciation: 'hak-sik', example: '오늘 학식 뭐야?', exampleTranslation: 'What is on the campus cafeteria menu today?' },
    { korean: '자퇴', english: 'Dropping out of school', pronunciation: 'ja-toe', example: '자퇴하고 사업 시작했대.', exampleTranslation: 'They say he dropped out and started a business.' },
    { korean: '현실도피', english: 'Escapism / Avoiding reality', pronunciation: 'hyeon-sil-do-pi', example: '게임은 현실도피야.', exampleTranslation: 'Gaming is escapism.' },
    { korean: '현생', english: 'Real life (abbreviation)', pronunciation: 'hyeon-saeng', example: '현생이 바빠.', exampleTranslation: 'Real life is busy.' },
    { korean: '정줄놓', english: 'Lost my mind (abbreviation)', pronunciation: 'jeong-jul-not', example: '정줄놓은 상태야.', exampleTranslation: 'I have lost my mind.' },
    { korean: '가즈아', english: 'Let us gooo (exaggerated)', pronunciation: 'ga-jeu-a', example: '주식 가즈아!', exampleTranslation: 'To the moon with stocks!' },
    { korean: '조곤조곤', english: 'Softly / Calmly speaking', pronunciation: 'jo-gon-jo-gon', example: '조곤조곤 말해 줘.', exampleTranslation: 'Speak to me softly.' },
    { korean: '호들갑', english: 'Making a big fuss', pronunciation: 'ho-deul-gap', example: '호들갑 떨지 마.', exampleTranslation: 'Do not make a big fuss.' },
    { korean: '싸바싸바', english: 'Bribing / Schmoozing', pronunciation: 'ssa-ba-ssa-ba', example: '싸바싸바해야 되나?', exampleTranslation: 'Do I need to schmooze?' },
    { korean: '뇌섹남', english: 'Brainy sexy man', pronunciation: 'noe-sek-nam', example: '걔는 완전 뇌섹남이야.', exampleTranslation: 'He is totally a brainy sexy man.' },
    { korean: '뇌섹녀', english: 'Brainy sexy woman', pronunciation: 'noe-sek-nyeo', example: '그 여자 뇌섹녀야.', exampleTranslation: 'She is a brainy sexy woman.' },
    { korean: '손절', english: 'Cut ties / Unfriend', pronunciation: 'son-jeol', example: '그 친구 손절했어.', exampleTranslation: 'I cut ties with that friend.' },
    { korean: '갬성터지다', english: 'Vibes exploding', pronunciation: 'gaem-seong-teo-ji-da', example: '이 노래 갬성 터진다.', exampleTranslation: 'This song has incredible vibes.' },
    { korean: '일머리', english: 'Work smarts / Common sense at work', pronunciation: 'il-meo-ri', example: '일머리가 좋네.', exampleTranslation: 'You have good work smarts.' },
    { korean: '어쩌라고', english: 'So what? / What do you want me to do?', pronunciation: 'eo-jjeo-ra-go', example: '어쩌라고 진짜.', exampleTranslation: 'So what, seriously.' },
    { korean: '마자마자', english: 'Right right (cute agreement)', pronunciation: 'ma-ja-ma-ja', example: '마자마자 그 말이 맞아!', exampleTranslation: 'Right right, that is correct!' },
    { korean: '그건좀', english: 'That is a bit... (disapproval)', pronunciation: 'geu-geon-jom', example: '그건 좀 아닌 것 같아.', exampleTranslation: 'I think that is a bit wrong.' },
    { korean: '미쳤다', english: 'Crazy (admiration or shock)', pronunciation: 'mi-chyeot-da', example: '이 퍼포먼스 미쳤다!', exampleTranslation: 'This performance is insane!' },
    { korean: '장인', english: 'Master / Expert (gaming)', pronunciation: 'jang-in', example: '걔는 리신 장인이야.', exampleTranslation: 'He is a Lee Sin master.' },
    { korean: '하극상', english: 'Insubordination / Beating higher rank', pronunciation: 'ha-geuk-sang', example: '하극상 매치였어!', exampleTranslation: 'It was an underdog upset match!' },
    { korean: '정신줄놓다', english: 'Lost one is mind', pronunciation: 'jeong-sin-jul-not-da', example: '요즘 정신줄 놓고 살아.', exampleTranslation: 'I have been out of it lately.' },
    { korean: '꼬우면', english: 'If you do not like it', pronunciation: 'kko-u-myeon', example: '꼬우면 니가 해.', exampleTranslation: 'If you do not like it, do it yourself.' },
    { korean: '공감능력', english: 'Empathy ability', pronunciation: 'gong-gam-neung-ryeok', example: '공감능력이 부족해.', exampleTranslation: 'Lacking in empathy.' },
    { korean: '호불호', english: 'Like or dislike / Divisive', pronunciation: 'ho-bul-ho', example: '이건 호불호 갈리는 맛이야.', exampleTranslation: 'This is a divisive flavor.' },
    { korean: '양비론', english: 'Both sides are wrong argument', pronunciation: 'yang-bi-ron', example: '양비론 펴지 마.', exampleTranslation: 'Do not argue that both sides are wrong.' },
    { korean: '어른스럽다', english: 'Mature / Adult-like', pronunciation: 'eo-reun-seu-reop-da', example: '어른스럽게 행동해.', exampleTranslation: 'Act maturely.' },
    { korean: '허세', english: 'Pretending / Showing off', pronunciation: 'heo-se', example: '허세 부리지 마.', exampleTranslation: 'Stop showing off.' },
    { korean: '깡', english: 'Guts / Boldness', pronunciation: 'kkang', example: '깡이 있네!', exampleTranslation: 'You have got guts!' },
    { korean: '뚝배기', english: 'Face (slang / stone pot)', pronunciation: 'ttuk-bae-gi', example: '뚝배기보다 장맛이지.', exampleTranslation: 'What matters is the inside, not the outside.' },
    { korean: '감성팔이', english: 'Exploiting emotions for profit', pronunciation: 'gam-seong-pal-i', example: '감성팔이하지 마.', exampleTranslation: 'Do not exploit emotions.' },
    { korean: '제곧내', english: 'Title says it all (abbreviation)', pronunciation: 'je-got-nae', example: '제곧내. 추천합니다.', exampleTranslation: 'Title says it all. I recommend it.' },
    { korean: '칼퇴', english: 'Leaving work on time sharp', pronunciation: 'kal-toe', example: '오늘은 칼퇴할 거야.', exampleTranslation: 'I am leaving work on time today.' },
    { korean: '야근', english: 'Working overtime / Night work', pronunciation: 'ya-geun', example: '또 야근이야 ㅠㅠ', exampleTranslation: 'Overtime again (crying).' },
    { korean: '워크맨', english: 'Workman (YouTube show reference)', pronunciation: 'wo-keu-maen', example: '워크맨처럼 체험해 봤어.', exampleTranslation: 'I tried experiencing it like Workman.' },
    { korean: '피로사회', english: 'Burnout society / Fatigued society', pronunciation: 'pi-ro-sa-hoe', example: '우리는 피로사회에 살고 있어.', exampleTranslation: 'We live in a burnout society.' },
    { korean: '삼포세대', english: 'Three-give-up generation', pronunciation: 'sam-po-se-dae', example: '삼포세대라는 말이 나온 이유가 있어.', exampleTranslation: 'There is a reason the term three-give-up generation appeared.' },
  ],
  5: [
    { korean: '여론조작', english: 'Public opinion manipulation', pronunciation: 'yeo-ron-jo-jak', example: '여론조작 의혹이 있어.', exampleTranslation: 'There are suspicions of public opinion manipulation.' },
    { korean: '대중문화', english: 'Popular culture', pronunciation: 'dae-jung-mun-hwa', example: '대중문화가 빠르게 변한다.', exampleTranslation: 'Popular culture changes quickly.' },
    { korean: '미디어 리터러시', english: 'Media literacy', pronunciation: 'mi-di-eo ri-teo-reo-si', example: '미디어 리터러시 교육이 필요해.', exampleTranslation: 'Media literacy education is needed.' },
    { korean: '팩트체크', english: 'Fact check', pronunciation: 'paek-teu-che-keu', example: '팩트체크부터 하자.', exampleTranslation: 'Let us fact check first.' },
    { korean: '확증편향', english: 'Confirmation bias', pronunciation: 'hwak-jeung-pyeon-hyang', example: '확증편향에 빠지기 쉬워.', exampleTranslation: 'It is easy to fall into confirmation bias.' },
    { korean: '에코챔버', english: 'Echo chamber', pronunciation: 'e-ko-chaem-beo', example: '에코챔버 효과가 심해.', exampleTranslation: 'The echo chamber effect is severe.' },
    { korean: '가짜뉴스', english: 'Fake news', pronunciation: 'ga-jja-nyu-seu', example: '가짜뉴스에 속지 마.', exampleTranslation: 'Do not be fooled by fake news.' },
    { korean: '진영논리', english: 'Partisan logic / Tribalism', pronunciation: 'jin-yeong-nol-li', example: '진영논리로 판단하면 안 돼.', exampleTranslation: 'You should not judge by partisan logic.' },
    { korean: '혐오표현', english: 'Hate speech', pronunciation: 'hyeom-o-pyo-hyeon', example: '혐오표현은 삼가야 해.', exampleTranslation: 'Hate speech should be avoided.' },
    { korean: '프레이밍', english: 'Framing (media technique)', pronunciation: 'peu-re-i-ming', example: '언론의 프레이밍에 주의해.', exampleTranslation: 'Be careful of media framing.' },
    { korean: '어뷰징', english: 'Abusing (system/clicks)', pronunciation: 'eo-byu-jing', example: '조회수 어뷰징이 문제야.', exampleTranslation: 'View count abuse is a problem.' },
    { korean: '알고리즘', english: 'Algorithm', pronunciation: 'al-go-ri-jeum', example: '알고리즘에 갇혀 있어.', exampleTranslation: 'I am trapped by the algorithm.' },
    { korean: '필터버블', english: 'Filter bubble', pronunciation: 'pil-teo-beo-beul', example: '필터버블을 깨야 해.', exampleTranslation: 'We need to break the filter bubble.' },
    { korean: '인포데믹', english: 'Infodemic', pronunciation: 'in-po-de-mik', example: '인포데믹이 심각해.', exampleTranslation: 'The infodemic is serious.' },
    { korean: '디지털 디톡스', english: 'Digital detox', pronunciation: 'di-ji-teol di-tok-seu', example: '디지털 디톡스가 필요해.', exampleTranslation: 'I need a digital detox.' },
    { korean: '스크린타임', english: 'Screen time', pronunciation: 'seu-keu-rin-ta-im', example: '스크린타임을 줄여야 돼.', exampleTranslation: 'I need to reduce my screen time.' },
    { korean: '도파민중독', english: 'Dopamine addiction', pronunciation: 'do-pa-min-jung-dok', example: '숏폼이 도파민중독을 유발해.', exampleTranslation: 'Short-form content causes dopamine addiction.' },
    { korean: '숏폼', english: 'Short-form content', pronunciation: 'syot-pom', example: '숏폼 영상이 대세야.', exampleTranslation: 'Short-form videos are the trend.' },
    { korean: '크리에이터', english: 'Creator / Content creator', pronunciation: 'keu-ri-e-i-teo', example: '크리에이터가 되고 싶어.', exampleTranslation: 'I want to become a content creator.' },
    { korean: '인플루언서', english: 'Influencer', pronunciation: 'in-peul-lu-eon-seo', example: '인플루언서 마케팅이 대세야.', exampleTranslation: 'Influencer marketing is the trend.' },
    { korean: '뒷광고', english: 'Hidden advertisement / Undisclosed sponsorship', pronunciation: 'dwit-gwang-go', example: '뒷광고 논란이 터졌어.', exampleTranslation: 'A hidden advertisement scandal broke out.' },
    { korean: '협찬', english: 'Sponsorship / Paid promotion', pronunciation: 'hyeop-chan', example: '이거 협찬 받은 거야?', exampleTranslation: 'Did you receive sponsorship for this?' },
    { korean: '네이티브광고', english: 'Native advertising', pronunciation: 'ne-i-ti-beu-gwang-go', example: '네이티브광고인지 구분이 안 돼.', exampleTranslation: 'I cannot tell if it is native advertising.' },
    { korean: '바이럴', english: 'Viral', pronunciation: 'ba-i-reol', example: '바이럴 마케팅 성공했어.', exampleTranslation: 'The viral marketing was successful.' },
    { korean: '주류문화', english: 'Mainstream culture', pronunciation: 'ju-ryu-mun-hwa', example: '비주류가 주류문화가 됐어.', exampleTranslation: 'The subculture became mainstream.' },
    { korean: '서브컬처', english: 'Subculture', pronunciation: 'seo-beu-keol-cheo', example: '서브컬처에 관심이 많아.', exampleTranslation: 'I am very interested in subculture.' },
    { korean: '세대갈등', english: 'Generational conflict', pronunciation: 'se-dae-gal-deung', example: '세대갈등이 심화되고 있어.', exampleTranslation: 'Generational conflict is intensifying.' },
    { korean: '젠더갈등', english: 'Gender conflict', pronunciation: 'jen-deo-gal-deung', example: '젠더갈등이 사회 문제야.', exampleTranslation: 'Gender conflict is a social issue.' },
    { korean: '디지털 원주민', english: 'Digital native', pronunciation: 'di-ji-teol won-ju-min', example: 'Z세대는 디지털 원주민이야.', exampleTranslation: 'Generation Z are digital natives.' },
    { korean: '밀레니얼', english: 'Millennial', pronunciation: 'mil-le-ni-eol', example: '밀레니얼 세대의 특징이야.', exampleTranslation: 'It is a characteristic of millennials.' },
    { korean: 'MZ세대', english: 'MZ generation (Millennial + Gen Z)', pronunciation: 'em-ji-se-dae', example: 'MZ세대가 소비를 주도해.', exampleTranslation: 'The MZ generation leads consumption.' },
    { korean: '오피니언 리더', english: 'Opinion leader', pronunciation: 'o-pi-ni-eon ri-deo', example: '그는 온라인 오피니언 리더야.', exampleTranslation: 'He is an online opinion leader.' },
    { korean: '사이버 불링', english: 'Cyberbullying', pronunciation: 'sa-i-beo bul-ling', example: '사이버 불링은 범죄야.', exampleTranslation: 'Cyberbullying is a crime.' },
    { korean: '온라인 폭력', english: 'Online violence', pronunciation: 'on-la-in pok-lyeok', example: '온라인 폭력이 심각한 문제야.', exampleTranslation: 'Online violence is a serious problem.' },
    { korean: '디지털 발자국', english: 'Digital footprint', pronunciation: 'di-ji-teol bal-ja-guk', example: '디지털 발자국을 관리해야 해.', exampleTranslation: 'You need to manage your digital footprint.' },
    { korean: '개인정보', english: 'Personal information / Privacy', pronunciation: 'gae-in-jeong-bo', example: '개인정보 유출을 조심해.', exampleTranslation: 'Be careful of personal information leaks.' },
    { korean: '익명성', english: 'Anonymity', pronunciation: 'ik-myeong-seong', example: '익명성이 문제를 만들어.', exampleTranslation: 'Anonymity creates problems.' },
    { korean: '탈레반', english: 'Extremist (slang for radical stance)', pronunciation: 'tal-le-ban', example: '그 커뮤니티는 탈레반이야.', exampleTranslation: 'That community is extremist.' },
    { korean: '이분법', english: 'Binary thinking / Black-and-white thinking', pronunciation: 'i-bun-beop', example: '이분법적 사고는 위험해.', exampleTranslation: 'Binary thinking is dangerous.' },
    { korean: '집단지성', english: 'Collective intelligence', pronunciation: 'jip-dan-ji-seong', example: '집단지성의 힘이야.', exampleTranslation: 'It is the power of collective intelligence.' },
    { korean: '디지털 노마드', english: 'Digital nomad', pronunciation: 'di-ji-teol no-ma-deu', example: '디지털 노마드로 살고 싶어.', exampleTranslation: 'I want to live as a digital nomad.' },
    { korean: '긱 이코노미', english: 'Gig economy', pronunciation: 'gik i-ko-no-mi', example: '긱 이코노미가 확산되고 있어.', exampleTranslation: 'The gig economy is expanding.' },
    { korean: '플랫폼 노동', english: 'Platform labor', pronunciation: 'peul-laet-pom no-dong', example: '플랫폼 노동자 보호가 필요해.', exampleTranslation: 'Platform workers need protection.' },
    { korean: '크라우드펀딩', english: 'Crowdfunding', pronunciation: 'keu-ra-u-deu-peon-ding', example: '크라우드펀딩으로 모금했어.', exampleTranslation: 'We raised funds through crowdfunding.' },
    { korean: '구독경제', english: 'Subscription economy', pronunciation: 'gu-dok-gyeong-je', example: '구독경제 시대야.', exampleTranslation: 'It is the era of subscription economy.' },
    { korean: '데이터마이닝', english: 'Data mining', pronunciation: 'de-i-teo-ma-i-ning', example: '데이터마이닝으로 분석했어.', exampleTranslation: 'It was analyzed through data mining.' },
    { korean: '타겟팅', english: 'Targeting (advertising)', pronunciation: 'ta-get-ting', example: '맞춤형 타겟팅 광고야.', exampleTranslation: 'It is personalized targeted advertising.' },
    { korean: '소비문화', english: 'Consumer culture', pronunciation: 'so-bi-mun-hwa', example: '소비문화가 변하고 있어.', exampleTranslation: 'Consumer culture is changing.' },
    { korean: '가치소비', english: 'Value-based consumption', pronunciation: 'ga-chi-so-bi', example: '가치소비를 실천해.', exampleTranslation: 'I practice value-based consumption.' },
    { korean: '미닝아웃', english: 'Meaning out (expressing beliefs through consumption)', pronunciation: 'mi-ning-a-ut', example: '미닝아웃으로 환경을 지키자.', exampleTranslation: 'Let us protect the environment through meaning out.' },
    { korean: '워케이션', english: 'Workation (work + vacation)', pronunciation: 'wo-ke-i-syeon', example: '제주도로 워케이션 갔어.', exampleTranslation: 'I went on a workation to Jeju.' },
    { korean: '디지털 리터러시', english: 'Digital literacy', pronunciation: 'di-ji-teol ri-teo-reo-si', example: '디지털 리터러시가 중요해.', exampleTranslation: 'Digital literacy is important.' },
    { korean: '하이퍼리얼리즘', english: 'Hyperrealism', pronunciation: 'ha-i-peo-ri-eol-li-jeum', example: '하이퍼리얼리즘적 콘텐츠가 유행이야.', exampleTranslation: 'Hyperrealistic content is trending.' },
    { korean: '디스토피아', english: 'Dystopia', pronunciation: 'di-seu-to-pi-a', example: '디스토피아적 현실이야.', exampleTranslation: 'It is a dystopian reality.' },
    { korean: '메타버스', english: 'Metaverse', pronunciation: 'me-ta-beo-seu', example: '메타버스에서 회의했어.', exampleTranslation: 'We had a meeting in the metaverse.' },
    { korean: 'NFT', english: 'NFT (non-fungible token)', pronunciation: 'en-ef-ti', example: 'NFT 아트 시장이 커지고 있어.', exampleTranslation: 'The NFT art market is growing.' },
    { korean: 'AI 생성', english: 'AI-generated', pronunciation: 'e-i-saeng-seong', example: 'AI 생성 콘텐츠가 논란이야.', exampleTranslation: 'AI-generated content is controversial.' },
    { korean: '딥페이크', english: 'Deepfake', pronunciation: 'dip-pe-i-keu', example: '딥페이크 범죄가 늘고 있어.', exampleTranslation: 'Deepfake crimes are increasing.' },
    { korean: '젠트리피케이션', english: 'Gentrification', pronunciation: 'jen-teu-ri-pi-ke-i-syeon', example: '젠트리피케이션 때문에 가게들이 사라져.', exampleTranslation: 'Shops are disappearing due to gentrification.' },
    { korean: '로컬크리에이터', english: 'Local creator', pronunciation: 'ro-keol-keu-ri-e-i-teo', example: '로컬크리에이터가 주목받고 있어.', exampleTranslation: 'Local creators are getting attention.' },
    { korean: '공정성', english: 'Fairness', pronunciation: 'gong-jeong-seong', example: '공정성에 대한 관심이 높아.', exampleTranslation: 'Interest in fairness is high.' },
    { korean: '사회적 자본', english: 'Social capital', pronunciation: 'sa-hoe-jeok ja-bon', example: '사회적 자본이 중요해.', exampleTranslation: 'Social capital is important.' },
    { korean: '문화 자본', english: 'Cultural capital', pronunciation: 'mun-hwa ja-bon', example: '문화 자본의 차이가 크다.', exampleTranslation: 'The difference in cultural capital is large.' },
    { korean: '디지털 격차', english: 'Digital divide', pronunciation: 'di-ji-teol gyeok-cha', example: '디지털 격차를 해소해야 해.', exampleTranslation: 'We need to bridge the digital divide.' },
    { korean: '정보 비대칭', english: 'Information asymmetry', pronunciation: 'jeong-bo bi-dae-ching', example: '정보 비대칭이 문제를 만들어.', exampleTranslation: 'Information asymmetry creates problems.' },
    { korean: '자기검열', english: 'Self-censorship', pronunciation: 'ja-gi-geom-yeol', example: '자기검열이 심해지고 있어.', exampleTranslation: 'Self-censorship is becoming more severe.' },
    { korean: '표현의 자유', english: 'Freedom of expression', pronunciation: 'pyo-hyeon-ui ja-yu', example: '표현의 자유와 책임 사이.', exampleTranslation: 'Between freedom of expression and responsibility.' },
    { korean: '취소문화', english: 'Cancel culture', pronunciation: 'chwi-so-mun-hwa', example: '취소문화가 논란이야.', exampleTranslation: 'Cancel culture is controversial.' },
    { korean: '콜아웃', english: 'Call out (publicly criticizing)', pronunciation: 'kol-a-ut', example: '콜아웃 문화가 확산됐어.', exampleTranslation: 'Call out culture has spread.' },
    { korean: '워킹맘', english: 'Working mom', pronunciation: 'wo-king-mam', example: '워킹맘의 어려움이 많아.', exampleTranslation: 'Working moms face many difficulties.' },
    { korean: '경력단절', english: 'Career interruption', pronunciation: 'gyeong-ryeok-dan-jeol', example: '경력단절 여성을 위한 프로그램이야.', exampleTranslation: 'It is a program for women with career interruptions.' },
    { korean: '유리천장', english: 'Glass ceiling', pronunciation: 'yu-ri-cheon-jang', example: '유리천장을 깨야 해.', exampleTranslation: 'We need to break the glass ceiling.' },
    { korean: '사회적 약자', english: 'Socially disadvantaged', pronunciation: 'sa-hoe-jeok yak-ja', example: '사회적 약자를 보호해야 해.', exampleTranslation: 'We need to protect the socially disadvantaged.' },
    { korean: '혐오사회', english: 'Hate society', pronunciation: 'hyeom-o-sa-hoe', example: '혐오사회를 극복해야 해.', exampleTranslation: 'We need to overcome the hate society.' },
    { korean: '양극화', english: 'Polarization', pronunciation: 'yang-geuk-hwa', example: '양극화가 심해지고 있어.', exampleTranslation: 'Polarization is intensifying.' },
    { korean: '문화적 전유', english: 'Cultural appropriation', pronunciation: 'mun-hwa-jeok jeon-yu', example: '문화적 전유 논란이야.', exampleTranslation: 'It is a cultural appropriation controversy.' },
    { korean: '토착화', english: 'Localization / Indigenization', pronunciation: 'to-chak-hwa', example: '외래문화의 토착화 과정이야.', exampleTranslation: 'It is the process of localizing foreign culture.' },
    { korean: '세계화', english: 'Globalization', pronunciation: 'se-gye-hwa', example: '세계화와 문화 다양성.', exampleTranslation: 'Globalization and cultural diversity.' },
    { korean: '감정노동', english: 'Emotional labor', pronunciation: 'gam-jeong-no-dong', example: '감정노동이 힘들어.', exampleTranslation: 'Emotional labor is exhausting.' },
    { korean: '번아웃증후군', english: 'Burnout syndrome', pronunciation: 'beon-a-ut-jeung-hu-gun', example: '번아웃증후군 증상이 있어.', exampleTranslation: 'I have burnout syndrome symptoms.' },
    { korean: '정신건강', english: 'Mental health', pronunciation: 'jeong-sin-geon-gang', example: '정신건강도 챙겨야 해.', exampleTranslation: 'You need to take care of mental health too.' },
    { korean: '웰빙', english: 'Well-being', pronunciation: 'wel-bing', example: '웰빙 라이프를 추구해.', exampleTranslation: 'I pursue a well-being lifestyle.' },
    { korean: '마이크로어그레션', english: 'Microaggression', pronunciation: 'ma-i-keu-ro-eo-geu-re-syeon', example: '마이크로어그레션에 대해 인지해야 해.', exampleTranslation: 'We need to be aware of microaggressions.' },
    { korean: '공론장', english: 'Public sphere', pronunciation: 'gong-ron-jang', example: '온라인 공론장이 활성화됐어.', exampleTranslation: 'The online public sphere has become active.' },
    { korean: '시민의식', english: 'Civic awareness', pronunciation: 'si-min-ui-sik', example: '시민의식이 높아지고 있어.', exampleTranslation: 'Civic awareness is increasing.' },
    { korean: '뉴미디어', english: 'New media', pronunciation: 'nyu-mi-di-eo', example: '뉴미디어 시대의 저널리즘.', exampleTranslation: 'Journalism in the new media era.' },
    { korean: '팟캐스트', english: 'Podcast', pronunciation: 'pat-kae-seu-teu', example: '팟캐스트 듣는 게 취미야.', exampleTranslation: 'Listening to podcasts is my hobby.' },
    { korean: '뉴스레터', english: 'Newsletter', pronunciation: 'nyu-seu-re-teo', example: '뉴스레터 구독하고 있어.', exampleTranslation: 'I subscribe to a newsletter.' },
    { korean: '큐레이션', english: 'Curation', pronunciation: 'kyu-re-i-syeon', example: '콘텐츠 큐레이션 서비스야.', exampleTranslation: 'It is a content curation service.' },
    { korean: '사회적 거리두기', english: 'Social distancing', pronunciation: 'sa-hoe-jeok geo-ri-du-gi', example: '사회적 거리두기가 일상이 됐어.', exampleTranslation: 'Social distancing became part of daily life.' },
    { korean: '비대면', english: 'Non-face-to-face / Contactless', pronunciation: 'bi-dae-myeon', example: '비대면 서비스가 늘었어.', exampleTranslation: 'Contactless services have increased.' },
    { korean: '플랫폼 자본주의', english: 'Platform capitalism', pronunciation: 'peul-laet-pom ja-bon-ju-ui', example: '플랫폼 자본주의의 문제점이야.', exampleTranslation: 'These are problems of platform capitalism.' },
    { korean: '감시 자본주의', english: 'Surveillance capitalism', pronunciation: 'gam-si ja-bon-ju-ui', example: '감시 자본주의에 대한 비판이 있어.', exampleTranslation: 'There are criticisms of surveillance capitalism.' },
    { korean: '혐오발언', english: 'Hate speech / Hateful remarks', pronunciation: 'hyeom-o-bal-eon', example: '혐오발언은 처벌해야 해.', exampleTranslation: 'Hate speech should be punished.' },
    { korean: '디지털 시민', english: 'Digital citizen', pronunciation: 'di-ji-teol si-min', example: '디지털 시민으로서 책임감이 필요해.', exampleTranslation: 'Responsibility as a digital citizen is needed.' },
    { korean: '소셜미디어 리터러시', english: 'Social media literacy', pronunciation: 'so-syeol-mi-di-eo ri-teo-reo-si', example: '소셜미디어 리터러시를 키워야 해.', exampleTranslation: 'We need to develop social media literacy.' },
    { korean: '콘텐츠 크리에이터', english: 'Content creator', pronunciation: 'kon-ten-cheu keu-ri-e-i-teo', example: '콘텐츠 크리에이터 경제가 성장해.', exampleTranslation: 'The content creator economy is growing.' },
    { korean: '포퓰리즘', english: 'Populism', pronunciation: 'po-pyu-li-jeum', example: '포퓰리즘적 정책이 위험해.', exampleTranslation: 'Populist policies are dangerous.' },
    { korean: '선동', english: 'Incitement / Agitation', pronunciation: 'seon-dong', example: '온라인 선동에 주의해야 해.', exampleTranslation: 'We need to be careful of online incitement.' },
    { korean: '댓글 문화', english: 'Comment culture', pronunciation: 'daet-geul mun-hwa', example: '한국의 댓글 문화는 독특해.', exampleTranslation: 'Korean comment culture is unique.' },
  ],
  6: [
    { korean: '신조어', english: 'Neologism / New word', pronunciation: 'sin-jo-eo', example: '매년 새로운 신조어가 생겨.', exampleTranslation: 'New neologisms appear every year.' },
    { korean: '조어법', english: 'Word formation / Coinage method', pronunciation: 'jo-eo-beop', example: '한국어 신조어의 조어법을 분석해 보자.', exampleTranslation: 'Let us analyze the word formation of Korean neologisms.' },
    { korean: '두문자어', english: 'Acronym / Initialism', pronunciation: 'du-mun-ja-eo', example: '한국 인터넷 두문자어가 많아.', exampleTranslation: 'There are many Korean internet acronyms.' },
    { korean: '혼성어', english: 'Blend word / Portmanteau', pronunciation: 'hon-seong-eo', example: '혼성어는 두 단어를 합친 거야.', exampleTranslation: 'A portmanteau is a combination of two words.' },
    { korean: '축약어', english: 'Abbreviation / Contraction', pronunciation: 'chuk-yak-eo', example: '인터넷에서 축약어를 많이 써.', exampleTranslation: 'People use many abbreviations on the internet.' },
    { korean: '외래어', english: 'Loanword / Foreign word', pronunciation: 'oe-rae-eo', example: '영어 외래어가 많이 쓰여.', exampleTranslation: 'Many English loanwords are used.' },
    { korean: '콩글리시', english: 'Konglish (Korean-English)', pronunciation: 'kong-geul-li-si', example: '콩글리시는 한국식 영어야.', exampleTranslation: 'Konglish is Korean-style English.' },
    { korean: '음운변화', english: 'Phonological change', pronunciation: 'eum-un-byeon-hwa', example: '인터넷 언어에도 음운변화가 있어.', exampleTranslation: 'There are phonological changes in internet language too.' },
    { korean: '의미변화', english: 'Semantic shift', pronunciation: 'ui-mi-byeon-hwa', example: '단어의 의미변화를 추적해.', exampleTranslation: 'Track the semantic shift of words.' },
    { korean: '은유', english: 'Metaphor', pronunciation: 'eun-yu', example: '인터넷 은유가 일상어가 됐어.', exampleTranslation: 'Internet metaphors have become everyday language.' },
    { korean: '환유', english: 'Metonymy', pronunciation: 'hwan-yu', example: '환유적 표현이 신조어에 많아.', exampleTranslation: 'There are many metonymic expressions in neologisms.' },
    { korean: '언어유희', english: 'Wordplay / Pun', pronunciation: 'eon-eo-yu-hui', example: '한국 네티즌은 언어유희를 좋아해.', exampleTranslation: 'Korean netizens enjoy wordplay.' },
    { korean: '패러디', english: 'Parody', pronunciation: 'pae-reo-di', example: '밈은 원본의 패러디야.', exampleTranslation: 'Memes are parodies of the original.' },
    { korean: '아이러니', english: 'Irony', pronunciation: 'a-i-reo-ni', example: '아이러니한 표현이 많아.', exampleTranslation: 'There are many ironic expressions.' },
    { korean: '풍자', english: 'Satire', pronunciation: 'pung-ja', example: '인터넷 풍자가 날카로워.', exampleTranslation: 'Internet satire is sharp.' },
    { korean: '언어적 창의성', english: 'Linguistic creativity', pronunciation: 'eon-eo-jeok chang-ui-seong', example: '신조어에서 언어적 창의성이 보여.', exampleTranslation: 'Linguistic creativity is visible in neologisms.' },
    { korean: '사회방언', english: 'Social dialect / Sociolect', pronunciation: 'sa-hoe-bang-eon', example: '인터넷 언어는 사회방언의 일종이야.', exampleTranslation: 'Internet language is a type of social dialect.' },
    { korean: '레지스터', english: 'Register (linguistic)', pronunciation: 'le-ji-seu-teo', example: '온라인과 오프라인의 레지스터가 달라.', exampleTranslation: 'The register differs between online and offline.' },
    { korean: '코드스위칭', english: 'Code-switching', pronunciation: 'ko-deu-seu-wi-ching', example: '코드스위칭이 자연스러워.', exampleTranslation: 'Code-switching comes naturally.' },
    { korean: '담화분석', english: 'Discourse analysis', pronunciation: 'dam-hwa-bun-seok', example: '온라인 담화분석 논문을 읽었어.', exampleTranslation: 'I read a paper on online discourse analysis.' },
    { korean: '화용론', english: 'Pragmatics', pronunciation: 'hwa-yong-non', example: '인터넷 언어의 화용론적 특징이야.', exampleTranslation: 'These are pragmatic features of internet language.' },
    { korean: '의미론', english: 'Semantics', pronunciation: 'ui-mi-ron', example: '신조어의 의미론적 분석이 필요해.', exampleTranslation: 'Semantic analysis of neologisms is needed.' },
    { korean: '형태론', english: 'Morphology', pronunciation: 'hyeong-tae-ron', example: '형태론적으로 분석해 보자.', exampleTranslation: 'Let us analyze it morphologically.' },
    { korean: '음성학', english: 'Phonetics', pronunciation: 'eum-seong-hak', example: '자음 표현은 음성학적 특성을 반영해.', exampleTranslation: 'Consonant expressions reflect phonetic characteristics.' },
    { korean: '사회언어학', english: 'Sociolinguistics', pronunciation: 'sa-hoe-eon-eo-hak', example: '사회언어학적 관점에서 분석해 보자.', exampleTranslation: 'Let us analyze from a sociolinguistic perspective.' },
    { korean: '언어 변이', english: 'Linguistic variation', pronunciation: 'eon-eo byeon-i', example: '인터넷에서 언어 변이가 활발해.', exampleTranslation: 'Linguistic variation is active on the internet.' },
    { korean: '언어 접촉', english: 'Language contact', pronunciation: 'eon-eo jeop-chok', example: '영어와 한국어의 언어 접촉 현상이야.', exampleTranslation: 'It is a language contact phenomenon between English and Korean.' },
    { korean: '차용어', english: 'Borrowed word', pronunciation: 'cha-yong-eo', example: '일본어 차용어도 인터넷에 많아.', exampleTranslation: 'There are many Japanese borrowed words on the internet too.' },
    { korean: '언어 순화', english: 'Language purification', pronunciation: 'eon-eo sun-hwa', example: '언어 순화 운동이 있었어.', exampleTranslation: 'There was a language purification movement.' },
    { korean: '표준어', english: 'Standard language', pronunciation: 'pyo-jun-eo', example: '인터넷 언어와 표준어의 괴리야.', exampleTranslation: 'It is the gap between internet language and standard language.' },
    { korean: '비표준어', english: 'Non-standard language', pronunciation: 'bi-pyo-jun-eo', example: '비표준어 사용이 증가하고 있어.', exampleTranslation: 'The use of non-standard language is increasing.' },
    { korean: '구어체', english: 'Colloquial style', pronunciation: 'gu-eo-che', example: '인터넷에서 구어체가 많이 쓰여.', exampleTranslation: 'Colloquial style is widely used on the internet.' },
    { korean: '문어체', english: 'Written style', pronunciation: 'mun-eo-che', example: '문어체와 구어체의 경계가 모호해.', exampleTranslation: 'The boundary between written and spoken styles is blurring.' },
    { korean: '통시적 분석', english: 'Diachronic analysis', pronunciation: 'tong-si-jeok bun-seok', example: '신조어의 통시적 분석이 필요해.', exampleTranslation: 'Diachronic analysis of neologisms is needed.' },
    { korean: '공시적 분석', english: 'Synchronic analysis', pronunciation: 'gong-si-jeok bun-seok', example: '공시적 분석으로 현재 사용을 파악해.', exampleTranslation: 'We grasp current usage through synchronic analysis.' },
    { korean: '어휘화', english: 'Lexicalization', pronunciation: 'eo-hwi-hwa', example: '인터넷 용어가 어휘화되고 있어.', exampleTranslation: 'Internet terms are being lexicalized.' },
    { korean: '문법화', english: 'Grammaticalization', pronunciation: 'mun-beop-hwa', example: '접미사의 문법화 과정이야.', exampleTranslation: 'It is the grammaticalization process of suffixes.' },
    { korean: '생산성', english: 'Productivity (linguistic)', pronunciation: 'saeng-san-seong', example: '이 접미사의 생산성이 높아.', exampleTranslation: 'The productivity of this suffix is high.' },
    { korean: '접두사화', english: 'Prefixation', pronunciation: 'jeop-du-sa-hwa', example: '강조 접두사화가 활발해.', exampleTranslation: 'Intensifying prefixation is active.' },
    { korean: '접미사화', english: 'Suffixation', pronunciation: 'jeop-mi-sa-hwa', example: '새로운 접미사화 현상이야.', exampleTranslation: 'It is a new suffixation phenomenon.' },
    { korean: '복합어 형성', english: 'Compound word formation', pronunciation: 'bok-hap-eo hyeong-seong', example: '인터넷 복합어 형성 패턴을 분석해.', exampleTranslation: 'Let us analyze internet compound word formation patterns.' },
    { korean: '파생어 형성', english: 'Derivation', pronunciation: 'pa-saeng-eo hyeong-seong', example: '파생어 형성이 활발해.', exampleTranslation: 'Derivation is active.' },
    { korean: '의미 확장', english: 'Semantic extension', pronunciation: 'ui-mi hwak-jang', example: '기존 단어의 의미 확장이 일어나.', exampleTranslation: 'Semantic extension of existing words occurs.' },
    { korean: '의미 축소', english: 'Semantic narrowing', pronunciation: 'ui-mi chuk-so', example: '의미 축소가 된 사례가 있어.', exampleTranslation: 'There are cases of semantic narrowing.' },
    { korean: '의미 전이', english: 'Semantic transfer', pronunciation: 'ui-mi jeon-i', example: '게임 용어의 의미 전이가 일어났어.', exampleTranslation: 'Semantic transfer of gaming terms occurred.' },
    { korean: '다의어', english: 'Polysemy', pronunciation: 'da-ui-eo', example: '인터넷 용어는 다의어가 많아.', exampleTranslation: 'Internet terms often have multiple meanings.' },
    { korean: '동음이의어', english: 'Homophone / Homonym', pronunciation: 'dong-eum-i-ui-eo', example: '동음이의어를 이용한 언어유희야.', exampleTranslation: 'It is wordplay using homophones.' },
    { korean: '초성체', english: 'Initial consonant writing', pronunciation: 'cho-seong-che', example: 'ㅋㅋ은 초성체의 대표적 예시야.', exampleTranslation: 'ㅋㅋ is a representative example of initial consonant writing.' },
    { korean: '음절 축약', english: 'Syllable contraction', pronunciation: 'eum-jeol chuk-yak', example: '음절 축약이 경제적이야.', exampleTranslation: 'Syllable contraction is economical.' },
    { korean: '문자 표현', english: 'Textual expression / Orthographic representation', pronunciation: 'mun-ja pyo-hyeon', example: '감정의 문자 표현 방식이 다양해.', exampleTranslation: 'Methods of textual emotion expression are diverse.' },
    { korean: '네티즌 문화', english: 'Netizen culture', pronunciation: 'ne-ti-jeun mun-hwa', example: '한국 네티즌 문화가 독특해.', exampleTranslation: 'Korean netizen culture is unique.' },
    { korean: '디지털 담론', english: 'Digital discourse', pronunciation: 'di-ji-teol dam-non', example: '디지털 담론이 사회에 영향을 미쳐.', exampleTranslation: 'Digital discourse affects society.' },
    { korean: '온라인 정체성', english: 'Online identity', pronunciation: 'on-la-in jeong-che-seong', example: '온라인 정체성 구축이 중요해.', exampleTranslation: 'Building online identity is important.' },
    { korean: '가상 공동체', english: 'Virtual community', pronunciation: 'ga-sang gong-dong-che', example: '가상 공동체의 역할이 커지고 있어.', exampleTranslation: 'The role of virtual communities is growing.' },
    { korean: '디지털 문화자본', english: 'Digital cultural capital', pronunciation: 'di-ji-teol mun-hwa-ja-bon', example: '디지털 문화자본이 새로운 계층을 만들어.', exampleTranslation: 'Digital cultural capital creates new class divisions.' },
    { korean: '참여문화', english: 'Participatory culture', pronunciation: 'cham-yeo-mun-hwa', example: '참여문화가 콘텐츠 생산을 바꿔.', exampleTranslation: 'Participatory culture changes content production.' },
    { korean: '프로슈머', english: 'Prosumer (producer + consumer)', pronunciation: 'peu-ro-syu-meo', example: '프로슈머 시대가 열렸어.', exampleTranslation: 'The prosumer era has opened.' },
    { korean: '집단 기억', english: 'Collective memory', pronunciation: 'jip-dan gi-eok', example: '밈은 집단 기억을 형성해.', exampleTranslation: 'Memes form collective memory.' },
    { korean: '문화적 전파', english: 'Cultural transmission / Diffusion', pronunciation: 'mun-hwa-jeok jeon-pa', example: '밈의 문화적 전파 속도가 빨라.', exampleTranslation: 'The cultural transmission speed of memes is fast.' },
    { korean: '기호학', english: 'Semiotics', pronunciation: 'gi-ho-hak', example: '이모티콘의 기호학적 분석이야.', exampleTranslation: 'It is a semiotic analysis of emoticons.' },
    { korean: '텍스트 분석', english: 'Text analysis', pronunciation: 'tek-seu-teu bun-seok', example: 'SNS 텍스트 분석 결과가 나왔어.', exampleTranslation: 'The SNS text analysis results came out.' },
    { korean: '말뭉치', english: 'Corpus', pronunciation: 'mal-mung-chi', example: '인터넷 말뭉치를 수집했어.', exampleTranslation: 'I collected an internet corpus.' },
    { korean: '빈도 분석', english: 'Frequency analysis', pronunciation: 'bin-do bun-seok', example: '신조어 빈도 분석을 실시했어.', exampleTranslation: 'I conducted a frequency analysis of neologisms.' },
    { korean: '언어 규범', english: 'Language norm', pronunciation: 'eon-eo gyu-beom', example: '인터넷 언어는 기존 언어 규범을 깨.', exampleTranslation: 'Internet language breaks existing language norms.' },
    { korean: '언어 정책', english: 'Language policy', pronunciation: 'eon-eo jeong-chaek', example: '인터넷 언어에 대한 언어 정책이 필요해.', exampleTranslation: 'Language policy for internet language is needed.' },
    { korean: '국어심의회', english: 'Korean Language Deliberation Council', pronunciation: 'guk-eo-sim-ui-hoe', example: '국어심의회에서 신조어를 검토해.', exampleTranslation: 'The Korean Language Council reviews neologisms.' },
    { korean: '표준국어대사전', english: 'Standard Korean Language Dictionary', pronunciation: 'pyo-jun-guk-eo-dae-sa-jeon', example: '표준국어대사전에 등재됐어.', exampleTranslation: 'It was registered in the Standard Korean Dictionary.' },
    { korean: '국립국어원', english: 'National Institute of Korean Language', pronunciation: 'guk-rip-guk-eo-won', example: '국립국어원에서 연구했어.', exampleTranslation: 'It was researched by the National Institute of Korean Language.' },
    { korean: '언어 이데올로기', english: 'Language ideology', pronunciation: 'eon-eo i-de-ol-lo-gi', example: '인터넷 언어에 대한 언어 이데올로기가 달라.', exampleTranslation: 'Language ideologies about internet language differ.' },
    { korean: '담화 공동체', english: 'Discourse community', pronunciation: 'dam-hwa gong-dong-che', example: '각 커뮤니티는 담화 공동체를 형성해.', exampleTranslation: 'Each community forms a discourse community.' },
    { korean: '사회적 실천', english: 'Social practice', pronunciation: 'sa-hoe-jeok sil-cheon', example: '언어 사용은 사회적 실천이야.', exampleTranslation: 'Language use is a social practice.' },
    { korean: '상호텍스트성', english: 'Intertextuality', pronunciation: 'sang-ho-tek-seu-teu-seong', example: '밈의 상호텍스트성이 중요해.', exampleTranslation: 'The intertextuality of memes is important.' },
    { korean: '다중양식성', english: 'Multimodality', pronunciation: 'da-jung-yang-sik-seong', example: '인터넷 언어의 다중양식성을 연구해.', exampleTranslation: 'We study the multimodality of internet language.' },
    { korean: '밈학', english: 'Memetics', pronunciation: 'mim-hak', example: '밈학은 문화 전파를 연구해.', exampleTranslation: 'Memetics studies cultural transmission.' },
    { korean: '디지털 인문학', english: 'Digital humanities', pronunciation: 'di-ji-teol in-mun-hak', example: '디지털 인문학적 접근이 필요해.', exampleTranslation: 'A digital humanities approach is needed.' },
    { korean: '비판적 담화분석', english: 'Critical discourse analysis', pronunciation: 'bi-pan-jeok dam-hwa-bun-seok', example: '비판적 담화분석을 적용해 보자.', exampleTranslation: 'Let us apply critical discourse analysis.' },
    { korean: '언어 태도', english: 'Language attitude', pronunciation: 'eon-eo tae-do', example: '신조어에 대한 언어 태도가 달라.', exampleTranslation: 'Language attitudes toward neologisms differ.' },
    { korean: '언어 의식', english: 'Language awareness', pronunciation: 'eon-eo ui-sik', example: '언어 의식이 언어 사용에 영향을 미쳐.', exampleTranslation: 'Language awareness affects language use.' },
    { korean: '문체론', english: 'Stylistics', pronunciation: 'mun-che-ron', example: '인터넷 문체론적 특징을 분석해.', exampleTranslation: 'Let us analyze internet stylistic features.' },
    { korean: '어용론', english: 'Applied linguistics term / Pragmatics (broader)', pronunciation: 'eo-yong-non', example: '어용론적 관점에서 살펴보자.', exampleTranslation: 'Let us examine from a pragmatic perspective.' },
    { korean: '사회구성주의', english: 'Social constructivism', pronunciation: 'sa-hoe-gu-seong-ju-ui', example: '사회구성주의적 관점에서 의미가 만들어져.', exampleTranslation: 'Meaning is constructed from a social constructivist perspective.' },
    { korean: '권력관계', english: 'Power relations', pronunciation: 'gwon-ryeok-gwan-gye', example: '언어 속 권력관계를 분석해.', exampleTranslation: 'Let us analyze power relations in language.' },
    { korean: '언어 권력', english: 'Linguistic power', pronunciation: 'eon-eo gwon-ryeok', example: '표준어와 언어 권력의 관계야.', exampleTranslation: 'It is the relationship between standard language and linguistic power.' },
    { korean: '문화 재생산', english: 'Cultural reproduction', pronunciation: 'mun-hwa jae-saeng-san', example: '밈을 통한 문화 재생산이 일어나.', exampleTranslation: 'Cultural reproduction through memes occurs.' },
    { korean: '상징 자본', english: 'Symbolic capital', pronunciation: 'sang-jing ja-bon', example: '온라인에서 팔로워는 상징 자본이야.', exampleTranslation: 'Followers are symbolic capital online.' },
    { korean: '문화 헤게모니', english: 'Cultural hegemony', pronunciation: 'mun-hwa he-ge-mo-ni', example: '문화 헤게모니가 언어에 반영돼.', exampleTranslation: 'Cultural hegemony is reflected in language.' },
    { korean: '탈권위주의', english: 'Post-authoritarianism', pronunciation: 'tal-gwon-wi-ju-ui', example: '인터넷 문화는 탈권위주의적이야.', exampleTranslation: 'Internet culture is post-authoritarian.' },
    { korean: '수행적 정체성', english: 'Performative identity', pronunciation: 'su-haeng-jeok jeong-che-seong', example: '온라인에서 수행적 정체성을 구축해.', exampleTranslation: 'We construct performative identity online.' },
    { korean: '언어 공동체', english: 'Speech community', pronunciation: 'eon-eo gong-dong-che', example: '각 플랫폼은 고유한 언어 공동체야.', exampleTranslation: 'Each platform is a unique speech community.' },
    { korean: '디지털 언어학', english: 'Digital linguistics', pronunciation: 'di-ji-teol eon-eo-hak', example: '디지털 언어학이 새로운 분야로 떠올라.', exampleTranslation: 'Digital linguistics is emerging as a new field.' },
    { korean: '컴퓨터 매개 의사소통', english: 'Computer-mediated communication', pronunciation: 'keom-pyu-teo mae-gae ui-sa-so-tong', example: '컴퓨터 매개 의사소통의 특징을 연구해.', exampleTranslation: 'We study the features of computer-mediated communication.' },
    { korean: '언어 생태계', english: 'Linguistic ecosystem', pronunciation: 'eon-eo saeng-tae-gye', example: '인터넷 언어 생태계가 다양해.', exampleTranslation: 'The internet linguistic ecosystem is diverse.' },
    { korean: '어문규정', english: 'Language regulations', pronunciation: 'eo-mun-gyu-jeong', example: '어문규정과 실제 사용의 괴리가 있어.', exampleTranslation: 'There is a gap between language regulations and actual use.' },
    { korean: '정보 구조', english: 'Information structure', pronunciation: 'jeong-bo gu-jo', example: '온라인 텍스트의 정보 구조를 분석해.', exampleTranslation: 'Let us analyze the information structure of online text.' },
    { korean: '언어 경관', english: 'Linguistic landscape', pronunciation: 'eon-eo gyeong-gwan', example: '디지털 언어 경관이 변화하고 있어.', exampleTranslation: 'The digital linguistic landscape is changing.' },
    { korean: '메타언어', english: 'Metalanguage', pronunciation: 'me-ta-eon-eo', example: '인터넷 메타언어 분석이 필요해.', exampleTranslation: 'Analysis of internet metalanguage is needed.' },
    { korean: '언어 변천', english: 'Language change', pronunciation: 'eon-eo byeon-cheon', example: '인터넷 시대의 언어 변천을 연구해.', exampleTranslation: 'We study language change in the internet era.' },
    { korean: '언어 계획', english: 'Language planning', pronunciation: 'eon-eo gye-hoek', example: '인터넷 언어에 대한 언어 계획이 논의돼.', exampleTranslation: 'Language planning for internet language is being discussed.' },
    { korean: '코퍼스 언어학', english: 'Corpus linguistics', pronunciation: 'ko-peo-seu eon-eo-hak', example: '코퍼스 언어학으로 신조어를 분석해.', exampleTranslation: 'We analyze neologisms through corpus linguistics.' },
    { korean: '언어 민주화', english: 'Language democratization', pronunciation: 'eon-eo min-ju-hwa', example: '인터넷은 언어 민주화를 촉진해.', exampleTranslation: 'The internet promotes language democratization.' },
  ],
};
