import { ThemeWord } from '../theme-data';

export const TRAVEL_WORDS: Record<number, ThemeWord[]> = {
  1: [
    { korean: '공항', english: 'Airport', pronunciation: 'gong-hang', example: '공항까지 얼마나 걸려요?', exampleTranslation: 'How long does it take to the airport?' },
    { korean: '호텔', english: 'Hotel', pronunciation: 'ho-tel', example: '호텔 예약했어요.', exampleTranslation: 'I reserved a hotel.' },
    { korean: '택시', english: 'Taxi', pronunciation: 'taek-si', example: '택시 타고 갈게요.', exampleTranslation: "I'll take a taxi." },
    { korean: '지하철', english: 'Subway', pronunciation: 'ji-ha-cheol', example: '지하철역이 어디예요?', exampleTranslation: 'Where is the subway station?' },
    { korean: '표', english: 'Ticket', pronunciation: 'pyo', example: '표 한 장 주세요.', exampleTranslation: 'One ticket please.' },
    { korean: '지도', english: 'Map', pronunciation: 'ji-do', example: '지도 좀 볼 수 있어요?', exampleTranslation: 'Can I see a map?' },
    { korean: '화장실', english: 'Bathroom', pronunciation: 'hwa-jang-sil', example: '화장실이 어디예요?', exampleTranslation: 'Where is the bathroom?' },
    { korean: '출구', english: 'Exit', pronunciation: 'chul-gu', example: '출구는 저쪽이에요.', exampleTranslation: 'The exit is over there.' },
    { korean: '입구', english: 'Entrance', pronunciation: 'ip-gu', example: '입구가 어디예요?', exampleTranslation: 'Where is the entrance?' },
    { korean: '버스', english: 'Bus', pronunciation: 'beo-seu', example: '버스 타고 가요.', exampleTranslation: "Let's go by bus." },
    { korean: '기차', english: 'Train', pronunciation: 'gi-cha', example: '기차 시간이 언제예요?', exampleTranslation: 'What time is the train?' },
    { korean: '비행기', english: 'Airplane', pronunciation: 'bi-haeng-gi', example: '비행기 표를 샀어요.', exampleTranslation: 'I bought an airplane ticket.' },
    { korean: '여행', english: 'Travel', pronunciation: 'yeo-haeng', example: '여행 좋아해요?', exampleTranslation: 'Do you like traveling?' },
    { korean: '가방', english: 'Bag', pronunciation: 'ga-bang', example: '가방이 무거워요.', exampleTranslation: 'The bag is heavy.' },
    { korean: '여권', english: 'Passport', pronunciation: 'yeo-gwon', example: '여권을 가져오세요.', exampleTranslation: 'Please bring your passport.' },
    { korean: '돈', english: 'Money', pronunciation: 'don', example: '돈이 얼마나 있어요?', exampleTranslation: 'How much money do you have?' },
    { korean: '전화', english: 'Phone', pronunciation: 'jeon-hwa', example: '전화 좀 빌려주세요.', exampleTranslation: 'Please lend me a phone.' },
    { korean: '식당', english: 'Restaurant', pronunciation: 'sik-dang', example: '근처에 식당 있어요?', exampleTranslation: 'Is there a restaurant nearby?' },
    { korean: '카페', english: 'Cafe', pronunciation: 'ka-pe', example: '카페에서 쉬어요.', exampleTranslation: "Let's rest at a cafe." },
    { korean: '편의점', english: 'Convenience store', pronunciation: 'pyeon-ui-jeom', example: '편의점이 어디예요?', exampleTranslation: 'Where is the convenience store?' },
    { korean: '은행', english: 'Bank', pronunciation: 'eun-haeng', example: '은행이 몇 시에 열어요?', exampleTranslation: 'What time does the bank open?' },
    { korean: '약국', english: 'Pharmacy', pronunciation: 'yak-guk', example: '약국에서 약을 샀어요.', exampleTranslation: 'I bought medicine at the pharmacy.' },
    { korean: '병원', english: 'Hospital', pronunciation: 'byeong-won', example: '병원에 가야 해요.', exampleTranslation: 'I need to go to the hospital.' },
    { korean: '경찰서', english: 'Police station', pronunciation: 'gyeong-chal-seo', example: '경찰서가 어디예요?', exampleTranslation: 'Where is the police station?' },
    { korean: '길', english: 'Road / Way', pronunciation: 'gil', example: '이 길이 맞아요?', exampleTranslation: 'Is this the right way?' },
    { korean: '왼쪽', english: 'Left', pronunciation: 'oen-jjok', example: '왼쪽으로 가세요.', exampleTranslation: 'Go to the left.' },
    { korean: '오른쪽', english: 'Right', pronunciation: 'o-reun-jjok', example: '오른쪽에 있어요.', exampleTranslation: 'It is on the right.' },
    { korean: '앞', english: 'Front', pronunciation: 'ap', example: '호텔 앞에서 만나요.', exampleTranslation: "Let's meet in front of the hotel." },
    { korean: '뒤', english: 'Behind', pronunciation: 'dwi', example: '가게 뒤에 있어요.', exampleTranslation: 'It is behind the store.' },
    { korean: '위', english: 'Above / Up', pronunciation: 'wi', example: '위층으로 올라가세요.', exampleTranslation: 'Go up to the upper floor.' },
    { korean: '아래', english: 'Below / Down', pronunciation: 'a-rae', example: '아래층에 있어요.', exampleTranslation: 'It is on the lower floor.' },
    { korean: '가까워요', english: 'It is close', pronunciation: 'ga-kka-wo-yo', example: '여기서 가까워요.', exampleTranslation: 'It is close from here.' },
    { korean: '멀어요', english: 'It is far', pronunciation: 'meol-eo-yo', example: '공항은 멀어요.', exampleTranslation: 'The airport is far.' },
    { korean: '사진', english: 'Photo', pronunciation: 'sa-jin', example: '사진 찍어도 돼요?', exampleTranslation: 'Can I take a photo?' },
    { korean: '물', english: 'Water', pronunciation: 'mul', example: '물 한 병 주세요.', exampleTranslation: 'One bottle of water please.' },
    { korean: '밥', english: 'Meal / Rice', pronunciation: 'bap', example: '밥 먹으러 가요.', exampleTranslation: "Let's go eat." },
    { korean: '커피', english: 'Coffee', pronunciation: 'keo-pi', example: '커피 한 잔 주세요.', exampleTranslation: 'One cup of coffee please.' },
    { korean: '맛있어요', english: 'It is delicious', pronunciation: 'ma-si-sseo-yo', example: '이 음식이 맛있어요.', exampleTranslation: 'This food is delicious.' },
    { korean: '얼마예요', english: 'How much is it', pronunciation: 'eol-ma-ye-yo', example: '이거 얼마예요?', exampleTranslation: 'How much is this?' },
    { korean: '싸요', english: 'It is cheap', pronunciation: 'ssa-yo', example: '여기가 더 싸요.', exampleTranslation: 'It is cheaper here.' },
    { korean: '비싸요', english: 'It is expensive', pronunciation: 'bi-ssa-yo', example: '너무 비싸요.', exampleTranslation: 'It is too expensive.' },
    { korean: '주세요', english: 'Please give me', pronunciation: 'ju-se-yo', example: '이거 주세요.', exampleTranslation: 'Give me this please.' },
    { korean: '감사합니다', english: 'Thank you', pronunciation: 'gam-sa-ham-ni-da', example: '도와주셔서 감사합니다.', exampleTranslation: 'Thank you for helping me.' },
    { korean: '죄송합니다', english: 'I am sorry', pronunciation: 'joe-song-ham-ni-da', example: '늦어서 죄송합니다.', exampleTranslation: 'I am sorry for being late.' },
    { korean: '안녕하세요', english: 'Hello', pronunciation: 'an-nyeong-ha-se-yo', example: '안녕하세요, 방 있어요?', exampleTranslation: 'Hello, do you have a room?' },
    { korean: '네', english: 'Yes', pronunciation: 'ne', example: '네, 알겠습니다.', exampleTranslation: 'Yes, I understand.' },
    { korean: '아니요', english: 'No', pronunciation: 'a-ni-yo', example: '아니요, 괜찮아요.', exampleTranslation: 'No, it is okay.' },
    { korean: '어디', english: 'Where', pronunciation: 'eo-di', example: '어디에 가요?', exampleTranslation: 'Where are you going?' },
    { korean: '언제', english: 'When', pronunciation: 'eon-je', example: '언제 출발해요?', exampleTranslation: 'When do we depart?' },
    { korean: '시간', english: 'Time', pronunciation: 'si-gan', example: '시간이 얼마나 걸려요?', exampleTranslation: 'How much time does it take?' },
    { korean: '오늘', english: 'Today', pronunciation: 'o-neul', example: '오늘 뭐 해요?', exampleTranslation: 'What are you doing today?' },
    { korean: '내일', english: 'Tomorrow', pronunciation: 'nae-il', example: '내일 떠나요.', exampleTranslation: 'I leave tomorrow.' },
    { korean: '어제', english: 'Yesterday', pronunciation: 'eo-je', example: '어제 서울에 도착했어요.', exampleTranslation: 'I arrived in Seoul yesterday.' },
    { korean: '아침', english: 'Morning', pronunciation: 'a-chim', example: '아침에 일찍 출발해요.', exampleTranslation: 'We depart early in the morning.' },
    { korean: '저녁', english: 'Evening', pronunciation: 'jeo-nyeok', example: '저녁에 뭐 먹을까요?', exampleTranslation: 'What shall we eat in the evening?' },
    { korean: '밤', english: 'Night', pronunciation: 'bam', example: '밤에 야경이 예뻐요.', exampleTranslation: 'The night view is pretty.' },
    { korean: '날씨', english: 'Weather', pronunciation: 'nal-ssi', example: '오늘 날씨가 좋아요.', exampleTranslation: 'The weather is nice today.' },
    { korean: '덥다', english: 'Hot (weather)', pronunciation: 'deop-da', example: '오늘 너무 더워요.', exampleTranslation: 'It is so hot today.' },
    { korean: '춥다', english: 'Cold (weather)', pronunciation: 'chup-da', example: '겨울에 한국은 추워요.', exampleTranslation: 'Korea is cold in winter.' },
    { korean: '비', english: 'Rain', pronunciation: 'bi', example: '비가 와요. 우산 있어요?', exampleTranslation: 'It is raining. Do you have an umbrella?' },
    { korean: '우산', english: 'Umbrella', pronunciation: 'u-san', example: '우산을 가져가세요.', exampleTranslation: 'Take an umbrella.' },
    { korean: '방', english: 'Room', pronunciation: 'bang', example: '방이 깨끗해요.', exampleTranslation: 'The room is clean.' },
    { korean: '열쇠', english: 'Key', pronunciation: 'yeol-soe', example: '방 열쇠 주세요.', exampleTranslation: 'Room key please.' },
    { korean: '짐', english: 'Luggage', pronunciation: 'jim', example: '짐이 많아요.', exampleTranslation: 'I have a lot of luggage.' },
    { korean: '도착', english: 'Arrival', pronunciation: 'do-chak', example: '도착 시간이 언제예요?', exampleTranslation: 'What is the arrival time?' },
    { korean: '출발', english: 'Departure', pronunciation: 'chul-bal', example: '출발 시간을 확인하세요.', exampleTranslation: 'Please check the departure time.' },
    { korean: '예약', english: 'Reservation', pronunciation: 'ye-yak', example: '예약하고 싶어요.', exampleTranslation: 'I would like to make a reservation.' },
    { korean: '카드', english: 'Card', pronunciation: 'ka-deu', example: '카드로 계산할게요.', exampleTranslation: "I'll pay by card." },
    { korean: '현금', english: 'Cash', pronunciation: 'hyeon-geum', example: '현금만 돼요?', exampleTranslation: 'Is it cash only?' },
    { korean: '영수증', english: 'Receipt', pronunciation: 'yeong-su-jeung', example: '영수증 주세요.', exampleTranslation: 'Receipt please.' },
    { korean: '계산', english: 'Payment / Bill', pronunciation: 'gye-san', example: '계산해 주세요.', exampleTranslation: 'The bill please.' },
    { korean: '가게', english: 'Store / Shop', pronunciation: 'ga-ge', example: '이 가게는 몇 시까지 해요?', exampleTranslation: 'Until what time is this store open?' },
    { korean: '시장', english: 'Market', pronunciation: 'si-jang', example: '시장에 가고 싶어요.', exampleTranslation: 'I want to go to the market.' },
    { korean: '선물', english: 'Gift / Souvenir', pronunciation: 'seon-mul', example: '선물 살 거예요.', exampleTranslation: 'I will buy gifts.' },
    { korean: '한국어', english: 'Korean language', pronunciation: 'han-guk-eo', example: '한국어 조금 할 수 있어요.', exampleTranslation: 'I can speak a little Korean.' },
    { korean: '영어', english: 'English language', pronunciation: 'yeong-eo', example: '영어 할 수 있어요?', exampleTranslation: 'Can you speak English?' },
    { korean: '이름', english: 'Name', pronunciation: 'i-reum', example: '이름이 뭐예요?', exampleTranslation: 'What is your name?' },
    { korean: '전화번호', english: 'Phone number', pronunciation: 'jeon-hwa-beon-ho', example: '전화번호 알려주세요.', exampleTranslation: 'Please tell me your phone number.' },
    { korean: '주소', english: 'Address', pronunciation: 'ju-so', example: '호텔 주소가 뭐예요?', exampleTranslation: 'What is the hotel address?' },
    { korean: '도움', english: 'Help', pronunciation: 'do-um', example: '도움이 필요해요.', exampleTranslation: 'I need help.' },
    { korean: '위험', english: 'Danger', pronunciation: 'wi-heom', example: '위험해요! 조심하세요.', exampleTranslation: 'It is dangerous! Be careful.' },
    { korean: '안전', english: 'Safety', pronunciation: 'an-jeon', example: '안전하게 여행하세요.', exampleTranslation: 'Travel safely.' },
    { korean: '약', english: 'Medicine', pronunciation: 'yak', example: '약 좀 사야 해요.', exampleTranslation: 'I need to buy some medicine.' },
    { korean: '아파요', english: 'It hurts / I am sick', pronunciation: 'a-pa-yo', example: '머리가 아파요.', exampleTranslation: 'My head hurts.' },
    { korean: '배고파요', english: 'I am hungry', pronunciation: 'bae-go-pa-yo', example: '배고파요. 먹으러 가요.', exampleTranslation: "I am hungry. Let's go eat." },
    { korean: '피곤해요', english: 'I am tired', pronunciation: 'pi-gon-hae-yo', example: '여행해서 피곤해요.', exampleTranslation: 'I am tired from traveling.' },
    { korean: '재미있어요', english: 'It is fun', pronunciation: 'jae-mi-i-sseo-yo', example: '여행이 재미있어요.', exampleTranslation: 'The trip is fun.' },
    { korean: '예뻐요', english: 'It is pretty', pronunciation: 'ye-ppeo-yo', example: '경치가 예뻐요.', exampleTranslation: 'The scenery is pretty.' },
    { korean: '좋아요', english: 'It is good / I like it', pronunciation: 'jo-a-yo', example: '여기 좋아요!', exampleTranslation: 'This place is good!' },
    { korean: '나쁘다', english: 'Bad', pronunciation: 'na-ppeu-da', example: '날씨가 나빠요.', exampleTranslation: 'The weather is bad.' },
    { korean: '크다', english: 'Big', pronunciation: 'keu-da', example: '이 공원이 커요.', exampleTranslation: 'This park is big.' },
    { korean: '작다', english: 'Small', pronunciation: 'jak-da', example: '방이 작아요.', exampleTranslation: 'The room is small.' },
    { korean: '많다', english: 'Many / A lot', pronunciation: 'man-ta', example: '사람이 많아요.', exampleTranslation: 'There are many people.' },
    { korean: '적다', english: 'Few / Little', pronunciation: 'jeok-da', example: '관광객이 적어요.', exampleTranslation: 'There are few tourists.' },
    { korean: '새롭다', english: 'New', pronunciation: 'sae-rop-da', example: '새로운 곳에 가고 싶어요.', exampleTranslation: 'I want to go to a new place.' },
    { korean: '빨리', english: 'Quickly', pronunciation: 'ppal-li', example: '빨리 가야 해요.', exampleTranslation: 'We need to go quickly.' },
    { korean: '천천히', english: 'Slowly', pronunciation: 'cheon-cheon-hi', example: '천천히 말해 주세요.', exampleTranslation: 'Please speak slowly.' },
    { korean: '같이', english: 'Together', pronunciation: 'ga-chi', example: '같이 여행해요.', exampleTranslation: "Let's travel together." },
    { korean: '혼자', english: 'Alone', pronunciation: 'hon-ja', example: '혼자 여행하고 있어요.', exampleTranslation: 'I am traveling alone.' },
    { korean: '넓다', english: 'Wide / Spacious', pronunciation: 'neol-da', example: '이 광장이 넓어요.', exampleTranslation: 'This square is spacious.' },
  ],
  2: [
    { korean: '관광', english: 'Sightseeing', pronunciation: 'gwan-gwang', example: '서울 관광을 할 거예요.', exampleTranslation: 'I will go sightseeing in Seoul.' },
    { korean: '안내소', english: 'Information center', pronunciation: 'an-nae-so', example: '관광 안내소가 어디예요?', exampleTranslation: 'Where is the tourist information center?' },
    { korean: '환전', english: 'Currency exchange', pronunciation: 'hwan-jeon', example: '환전하고 싶어요.', exampleTranslation: 'I want to exchange currency.' },
    { korean: '환율', english: 'Exchange rate', pronunciation: 'hwan-yul', example: '오늘 환율이 어떻게 돼요?', exampleTranslation: 'What is the exchange rate today?' },
    { korean: '면세점', english: 'Duty-free shop', pronunciation: 'myeon-se-jeom', example: '면세점에서 쇼핑했어요.', exampleTranslation: 'I shopped at the duty-free store.' },
    { korean: '탑승구', english: 'Boarding gate', pronunciation: 'tap-seung-gu', example: '탑승구가 어디예요?', exampleTranslation: 'Where is the boarding gate?' },
    { korean: '수하물', english: 'Baggage', pronunciation: 'su-ha-mul', example: '수하물을 찾아야 해요.', exampleTranslation: 'I need to pick up my baggage.' },
    { korean: '탑승권', english: 'Boarding pass', pronunciation: 'tap-seung-gwon', example: '탑승권 보여 주세요.', exampleTranslation: 'Please show your boarding pass.' },
    { korean: '세관', english: 'Customs', pronunciation: 'se-gwan', example: '세관 신고할 것이 있어요.', exampleTranslation: 'I have something to declare at customs.' },
    { korean: '입국', english: 'Immigration (entry)', pronunciation: 'ip-guk', example: '입국 심사를 받았어요.', exampleTranslation: 'I went through immigration.' },
    { korean: '출국', english: 'Departure (from country)', pronunciation: 'chul-guk', example: '출국 수속을 했어요.', exampleTranslation: 'I completed departure procedures.' },
    { korean: '왕복', english: 'Round trip', pronunciation: 'wang-bok', example: '왕복 표 주세요.', exampleTranslation: 'A round-trip ticket please.' },
    { korean: '편도', english: 'One way', pronunciation: 'pyeon-do', example: '편도 표 얼마예요?', exampleTranslation: 'How much is a one-way ticket?' },
    { korean: '정류장', english: 'Bus stop', pronunciation: 'jeong-nyu-jang', example: '다음 정류장에서 내려요.', exampleTranslation: 'I get off at the next stop.' },
    { korean: '노선', english: 'Route / Line', pronunciation: 'no-seon', example: '몇 번 노선이에요?', exampleTranslation: 'What route number is it?' },
    { korean: '환승', english: 'Transfer', pronunciation: 'hwan-seung', example: '여기서 환승하세요.', exampleTranslation: 'Transfer here.' },
    { korean: '교통카드', english: 'Transit card', pronunciation: 'gyo-tong-ka-deu', example: '교통카드 충전해 주세요.', exampleTranslation: 'Please recharge my transit card.' },
    { korean: '충전', english: 'Recharge / Charge', pronunciation: 'chung-jeon', example: '핸드폰 충전할 곳이 있어요?', exampleTranslation: 'Is there a place to charge my phone?' },
    { korean: '내리다', english: 'To get off', pronunciation: 'nae-ri-da', example: '여기서 내려야 해요.', exampleTranslation: 'I need to get off here.' },
    { korean: '타다', english: 'To get on / ride', pronunciation: 'ta-da', example: '버스를 타세요.', exampleTranslation: 'Take the bus.' },
    { korean: '직진', english: 'Go straight', pronunciation: 'jik-jin', example: '직진하면 나와요.', exampleTranslation: 'Go straight and you will find it.' },
    { korean: '횡단보도', english: 'Crosswalk', pronunciation: 'hoeng-dan-bo-do', example: '횡단보도를 건너세요.', exampleTranslation: 'Cross the crosswalk.' },
    { korean: '신호등', english: 'Traffic light', pronunciation: 'sin-ho-deung', example: '신호등에서 왼쪽으로 가세요.', exampleTranslation: 'Turn left at the traffic light.' },
    { korean: '골목', english: 'Alley', pronunciation: 'gol-mok', example: '이 골목으로 들어가세요.', exampleTranslation: 'Enter through this alley.' },
    { korean: '사거리', english: 'Intersection', pronunciation: 'sa-geo-ri', example: '사거리에서 오른쪽으로 가세요.', exampleTranslation: 'Turn right at the intersection.' },
    { korean: '건너편', english: 'Opposite side', pronunciation: 'geon-neo-pyeon', example: '건너편에 있어요.', exampleTranslation: 'It is on the opposite side.' },
    { korean: '모퉁이', english: 'Corner', pronunciation: 'mo-tung-i', example: '모퉁이를 돌면 있어요.', exampleTranslation: 'Turn the corner and it is there.' },
    { korean: '지하도', english: 'Underground passage', pronunciation: 'ji-ha-do', example: '지하도로 건너세요.', exampleTranslation: 'Cross through the underground passage.' },
    { korean: '육교', english: 'Pedestrian overpass', pronunciation: 'yuk-gyo', example: '육교를 이용하세요.', exampleTranslation: 'Use the pedestrian overpass.' },
    { korean: '공원', english: 'Park', pronunciation: 'gong-won', example: '공원에서 산책해요.', exampleTranslation: "Let's take a walk in the park." },
    { korean: '해변', english: 'Beach', pronunciation: 'hae-byeon', example: '해변이 아름다워요.', exampleTranslation: 'The beach is beautiful.' },
    { korean: '산', english: 'Mountain', pronunciation: 'san', example: '산에 올라갈 거예요.', exampleTranslation: 'I will climb the mountain.' },
    { korean: '강', english: 'River', pronunciation: 'gang', example: '한강에서 자전거를 탔어요.', exampleTranslation: 'I rode a bicycle at the Han River.' },
    { korean: '바다', english: 'Sea / Ocean', pronunciation: 'ba-da', example: '바다를 보러 가요.', exampleTranslation: "Let's go see the sea." },
    { korean: '섬', english: 'Island', pronunciation: 'seom', example: '제주도는 아름다운 섬이에요.', exampleTranslation: 'Jeju is a beautiful island.' },
    { korean: '다리', english: 'Bridge', pronunciation: 'da-ri', example: '다리를 건너면 있어요.', exampleTranslation: 'Cross the bridge and it is there.' },
    { korean: '쇼핑', english: 'Shopping', pronunciation: 'syo-ping', example: '쇼핑하러 가요.', exampleTranslation: "Let's go shopping." },
    { korean: '백화점', english: 'Department store', pronunciation: 'baek-hwa-jeom', example: '백화점에서 옷을 샀어요.', exampleTranslation: 'I bought clothes at the department store.' },
    { korean: '마트', english: 'Mart / Supermarket', pronunciation: 'ma-teu', example: '마트에서 과자를 사요.', exampleTranslation: "Let's buy snacks at the mart." },
    { korean: '기념품', english: 'Souvenir', pronunciation: 'gi-nyeom-pum', example: '기념품을 사고 싶어요.', exampleTranslation: 'I want to buy souvenirs.' },
    { korean: '할인', english: 'Discount', pronunciation: 'har-in', example: '할인해 주세요.', exampleTranslation: 'Please give me a discount.' },
    { korean: '영업시간', english: 'Business hours', pronunciation: 'yeong-eop-si-gan', example: '영업시간이 어떻게 돼요?', exampleTranslation: 'What are the business hours?' },
    { korean: '문을 닫다', english: 'To close (a shop)', pronunciation: 'mun-eul dat-da', example: '가게가 문을 닫았어요.', exampleTranslation: 'The store closed.' },
    { korean: '문을 열다', english: 'To open (a shop)', pronunciation: 'mun-eul yeol-da', example: '몇 시에 문을 열어요?', exampleTranslation: 'What time do you open?' },
    { korean: '교환', english: 'Exchange (product)', pronunciation: 'gyo-hwan', example: '이거 교환할 수 있어요?', exampleTranslation: 'Can I exchange this?' },
    { korean: '환불', english: 'Refund', pronunciation: 'hwan-bul', example: '환불해 주세요.', exampleTranslation: 'Please give me a refund.' },
    { korean: '사이즈', english: 'Size', pronunciation: 'sa-i-jeu', example: '다른 사이즈 있어요?', exampleTranslation: 'Do you have another size?' },
    { korean: '색깔', english: 'Color', pronunciation: 'saek-kkal', example: '다른 색깔 있어요?', exampleTranslation: 'Do you have another color?' },
    { korean: '입어 보다', english: 'To try on', pronunciation: 'i-beo bo-da', example: '이거 입어 봐도 돼요?', exampleTranslation: 'Can I try this on?' },
    { korean: '포장', english: 'Wrapping / Packaging', pronunciation: 'po-jang', example: '선물용으로 포장해 주세요.', exampleTranslation: 'Please wrap it as a gift.' },
    { korean: '봄', english: 'Spring', pronunciation: 'bom', example: '봄에 벚꽃이 피어요.', exampleTranslation: 'Cherry blossoms bloom in spring.' },
    { korean: '여름', english: 'Summer', pronunciation: 'yeo-reum', example: '여름에 해변에 가요.', exampleTranslation: "Let's go to the beach in summer." },
    { korean: '가을', english: 'Autumn', pronunciation: 'ga-eul', example: '가을에 단풍이 예뻐요.', exampleTranslation: 'The autumn leaves are beautiful.' },
    { korean: '겨울', english: 'Winter', pronunciation: 'gyeo-ul', example: '겨울에 스키 타러 가요.', exampleTranslation: "Let's go skiing in winter." },
    { korean: '눈', english: 'Snow', pronunciation: 'nun', example: '눈이 와요!', exampleTranslation: 'It is snowing!' },
    { korean: '꽃', english: 'Flower', pronunciation: 'kkot', example: '꽃이 예뻐요.', exampleTranslation: 'The flowers are pretty.' },
    { korean: '나무', english: 'Tree', pronunciation: 'na-mu', example: '나무가 많아서 시원해요.', exampleTranslation: 'It is cool because there are many trees.' },
    { korean: '하늘', english: 'Sky', pronunciation: 'ha-neul', example: '하늘이 맑아요.', exampleTranslation: 'The sky is clear.' },
    { korean: '구름', english: 'Cloud', pronunciation: 'gu-reum', example: '구름이 많아요.', exampleTranslation: 'There are many clouds.' },
    { korean: '바람', english: 'Wind', pronunciation: 'ba-ram', example: '바람이 많이 불어요.', exampleTranslation: 'It is very windy.' },
    { korean: '일출', english: 'Sunrise', pronunciation: 'il-chul', example: '일출을 보러 갔어요.', exampleTranslation: 'I went to see the sunrise.' },
    { korean: '일몰', english: 'Sunset', pronunciation: 'il-mol', example: '일몰이 아름다워요.', exampleTranslation: 'The sunset is beautiful.' },
    { korean: '경치', english: 'Scenery', pronunciation: 'gyeong-chi', example: '경치가 정말 좋아요.', exampleTranslation: 'The scenery is really nice.' },
    { korean: '놀이공원', english: 'Amusement park', pronunciation: 'nor-i-gong-won', example: '놀이공원에 가고 싶어요.', exampleTranslation: 'I want to go to an amusement park.' },
    { korean: '동물원', english: 'Zoo', pronunciation: 'dong-mul-won', example: '동물원에서 판다를 봤어요.', exampleTranslation: 'I saw pandas at the zoo.' },
    { korean: '박물관', english: 'Museum', pronunciation: 'bang-mul-gwan', example: '박물관에 가 볼까요?', exampleTranslation: 'Shall we go to the museum?' },
    { korean: '미술관', english: 'Art gallery', pronunciation: 'mi-sul-gwan', example: '미술관에서 전시회를 봤어요.', exampleTranslation: 'I saw an exhibition at the art gallery.' },
    { korean: '궁', english: 'Palace', pronunciation: 'gung', example: '궁을 구경하고 싶어요.', exampleTranslation: 'I want to look around the palace.' },
    { korean: '절', english: 'Temple (Buddhist)', pronunciation: 'jeol', example: '절에서 기도했어요.', exampleTranslation: 'I prayed at the temple.' },
    { korean: '한복', english: 'Hanbok (Korean traditional dress)', pronunciation: 'han-bok', example: '한복을 입고 사진을 찍었어요.', exampleTranslation: 'I took photos wearing hanbok.' },
    { korean: '전통', english: 'Tradition', pronunciation: 'jeon-tong', example: '한국 전통 문화가 멋져요.', exampleTranslation: 'Korean traditional culture is wonderful.' },
    { korean: '문화', english: 'Culture', pronunciation: 'mun-hwa', example: '한국 문화를 체험하고 싶어요.', exampleTranslation: 'I want to experience Korean culture.' },
    { korean: '축제', english: 'Festival', pronunciation: 'chuk-je', example: '축제에 가 볼까요?', exampleTranslation: 'Shall we go to the festival?' },
    { korean: '체험', english: 'Experience', pronunciation: 'che-heom', example: '한국 체험 프로그램이 있어요.', exampleTranslation: 'There is a Korean experience program.' },
    { korean: '야시장', english: 'Night market', pronunciation: 'ya-si-jang', example: '야시장에서 먹거리가 많아요.', exampleTranslation: 'There is a lot of food at the night market.' },
    { korean: '지하상가', english: 'Underground shopping center', pronunciation: 'ji-ha-sang-ga', example: '지하상가에서 옷을 싸게 살 수 있어요.', exampleTranslation: 'You can buy clothes cheaply at the underground mall.' },
    { korean: '대중교통', english: 'Public transportation', pronunciation: 'dae-jung-gyo-tong', example: '대중교통이 편리해요.', exampleTranslation: 'Public transportation is convenient.' },
    { korean: '렌터카', english: 'Rental car', pronunciation: 'ren-teo-ka', example: '렌터카를 빌렸어요.', exampleTranslation: 'I rented a car.' },
    { korean: '자전거', english: 'Bicycle', pronunciation: 'ja-jeon-geo', example: '자전거를 빌릴 수 있어요?', exampleTranslation: 'Can I rent a bicycle?' },
    { korean: '걸어가다', english: 'To walk (to a place)', pronunciation: 'geol-eo-ga-da', example: '걸어갈 수 있어요?', exampleTranslation: 'Can we walk there?' },
    { korean: '택배', english: 'Delivery / Parcel', pronunciation: 'taek-bae', example: '짐을 택배로 보낼 수 있어요?', exampleTranslation: 'Can I send my luggage by parcel?' },
    { korean: '우체국', english: 'Post office', pronunciation: 'u-che-guk', example: '우체국이 어디예요?', exampleTranslation: 'Where is the post office?' },
    { korean: '인터넷', english: 'Internet', pronunciation: 'in-teo-net', example: '인터넷 카페가 있어요?', exampleTranslation: 'Is there an internet cafe?' },
    { korean: '와이파이', english: 'Wi-Fi', pronunciation: 'wa-i-pa-i', example: '와이파이 비밀번호 뭐예요?', exampleTranslation: 'What is the Wi-Fi password?' },
    { korean: '전기', english: 'Electricity', pronunciation: 'jeon-gi', example: '전기 콘센트 있어요?', exampleTranslation: 'Is there an electrical outlet?' },
    { korean: '어댑터', english: 'Adapter', pronunciation: 'eo-daep-teo', example: '전기 어댑터가 필요해요.', exampleTranslation: 'I need an electrical adapter.' },
    { korean: '유심', english: 'SIM card', pronunciation: 'yu-sim', example: '유심 카드 어디서 살 수 있어요?', exampleTranslation: 'Where can I buy a SIM card?' },
    { korean: '로밍', english: 'Roaming', pronunciation: 'ro-ming', example: '로밍 서비스를 신청했어요.', exampleTranslation: 'I signed up for roaming service.' },
    { korean: '짐 보관', english: 'Luggage storage', pronunciation: 'jim bo-gwan', example: '짐 보관할 수 있는 곳 있어요?', exampleTranslation: 'Is there a place for luggage storage?' },
    { korean: '안내 방송', english: 'Announcement', pronunciation: 'an-nae bang-song', example: '안내 방송을 잘 들으세요.', exampleTranslation: 'Listen carefully to the announcement.' },
    { korean: '분실물', english: 'Lost and found', pronunciation: 'bun-sil-mul', example: '분실물 센터가 어디예요?', exampleTranslation: 'Where is the lost and found center?' },
    { korean: '무료', english: 'Free (no charge)', pronunciation: 'mu-ryo', example: '입장이 무료예요.', exampleTranslation: 'Admission is free.' },
    { korean: '유료', english: 'Paid / Charged', pronunciation: 'yu-ryo', example: '주차는 유료예요.', exampleTranslation: 'Parking is paid.' },
    { korean: '금연', english: 'No smoking', pronunciation: 'geum-yeon', example: '여기는 금연 구역이에요.', exampleTranslation: 'This is a no-smoking area.' },
    { korean: '흡연', english: 'Smoking', pronunciation: 'heup-yeon', example: '흡연 구역이 어디예요?', exampleTranslation: 'Where is the smoking area?' },
    { korean: '추천', english: 'Recommendation', pronunciation: 'chu-cheon', example: '맛집 추천해 주세요.', exampleTranslation: 'Please recommend a good restaurant.' },
    { korean: '인기', english: 'Popular / Popularity', pronunciation: 'in-gi', example: '이 곳이 인기가 많아요.', exampleTranslation: 'This place is very popular.' },
    { korean: '줄을 서다', english: 'To stand in line', pronunciation: 'jul-eul seo-da', example: '줄을 서야 해요.', exampleTranslation: 'You need to stand in line.' },
    { korean: '대기', english: 'Waiting', pronunciation: 'dae-gi', example: '대기 시간이 얼마나 돼요?', exampleTranslation: 'How long is the waiting time?' },
    { korean: '번호표', english: 'Number ticket', pronunciation: 'beon-ho-pyo', example: '번호표를 뽑으세요.', exampleTranslation: 'Please take a number ticket.' },
  ],
  3: [
    { korean: '숙소', english: 'Accommodation', pronunciation: 'suk-so', example: '숙소를 아직 못 정했어요.', exampleTranslation: "I haven't decided on accommodation yet." },
    { korean: '게스트하우스', english: 'Guesthouse', pronunciation: 'ge-seu-teu-ha-u-seu', example: '게스트하우스에서 외국인 친구를 만났어요.', exampleTranslation: 'I met foreign friends at the guesthouse.' },
    { korean: '민박', english: 'Homestay', pronunciation: 'min-bak', example: '시골에서 민박을 했어요.', exampleTranslation: 'I did a homestay in the countryside.' },
    { korean: '펜션', english: 'Pension (vacation rental)', pronunciation: 'pen-syeon', example: '바다 근처 펜션을 예약했어요.', exampleTranslation: 'I booked a pension near the sea.' },
    { korean: '체크인', english: 'Check-in', pronunciation: 'che-keu-in', example: '체크인 시간이 몇 시예요?', exampleTranslation: 'What time is check-in?' },
    { korean: '체크아웃', english: 'Check-out', pronunciation: 'che-keu-a-ut', example: '체크아웃은 11시까지예요.', exampleTranslation: 'Check-out is until 11 o\'clock.' },
    { korean: '조식', english: 'Breakfast (hotel)', pronunciation: 'jo-sik', example: '조식이 포함되어 있어요?', exampleTranslation: 'Is breakfast included?' },
    { korean: '싱글룸', english: 'Single room', pronunciation: 'sing-geul-lum', example: '싱글룸 하나 주세요.', exampleTranslation: 'One single room please.' },
    { korean: '더블룸', english: 'Double room', pronunciation: 'deo-beul-lum', example: '더블룸이 남아 있어요?', exampleTranslation: 'Is there a double room available?' },
    { korean: '온돌방', english: 'Heated floor room', pronunciation: 'on-dol-bang', example: '온돌방이 따뜻해요.', exampleTranslation: 'The heated floor room is warm.' },
    { korean: '당일치기', english: 'Day trip', pronunciation: 'dang-il-chi-gi', example: '당일치기로 경주에 다녀왔어요.', exampleTranslation: 'I went to Gyeongju on a day trip.' },
    { korean: '패키지여행', english: 'Package tour', pronunciation: 'pae-ki-ji-yeo-haeng', example: '패키지여행이 편해요.', exampleTranslation: 'Package tours are convenient.' },
    { korean: '자유여행', english: 'Independent travel', pronunciation: 'ja-yu-yeo-haeng', example: '자유여행을 선호해요.', exampleTranslation: 'I prefer independent travel.' },
    { korean: '가이드', english: 'Tour guide', pronunciation: 'ga-i-deu', example: '가이드가 설명을 잘 해줬어요.', exampleTranslation: 'The guide explained things well.' },
    { korean: '투어', english: 'Tour', pronunciation: 'tu-eo', example: '시티 투어에 참가했어요.', exampleTranslation: 'I joined a city tour.' },
    { korean: '일정', english: 'Itinerary / Schedule', pronunciation: 'il-jeong', example: '여행 일정을 짰어요.', exampleTranslation: 'I planned the travel itinerary.' },
    { korean: '명소', english: 'Famous spot', pronunciation: 'myeong-so', example: '유명한 명소를 다 가 봤어요.', exampleTranslation: 'I visited all the famous spots.' },
    { korean: '관광지', english: 'Tourist attraction', pronunciation: 'gwan-gwang-ji', example: '이 관광지는 사람이 많아요.', exampleTranslation: 'This tourist attraction has many people.' },
    { korean: '유적지', english: 'Historical site', pronunciation: 'yu-jeok-ji', example: '유적지를 둘러봤어요.', exampleTranslation: 'I looked around the historical site.' },
    { korean: '경복궁', english: 'Gyeongbokgung Palace', pronunciation: 'gyeong-bok-gung', example: '경복궁에서 수문장 교대식을 봤어요.', exampleTranslation: 'I watched the guard changing ceremony at Gyeongbokgung.' },
    { korean: '창덕궁', english: 'Changdeokgung Palace', pronunciation: 'chang-deok-gung', example: '창덕궁의 후원이 아름다워요.', exampleTranslation: "Changdeokgung's secret garden is beautiful." },
    { korean: '북촌', english: 'Bukchon (hanok village)', pronunciation: 'buk-chon', example: '북촌 한옥마을을 걸어 다녔어요.', exampleTranslation: 'I walked around Bukchon Hanok Village.' },
    { korean: '인사동', english: 'Insadong', pronunciation: 'in-sa-dong', example: '인사동에서 전통 공예품을 샀어요.', exampleTranslation: 'I bought traditional crafts in Insadong.' },
    { korean: '남산타워', english: 'Namsan Tower', pronunciation: 'nam-san-ta-wo', example: '남산타워에서 서울을 내려다봤어요.', exampleTranslation: 'I looked down at Seoul from Namsan Tower.' },
    { korean: '한강공원', english: 'Hangang Park', pronunciation: 'han-gang-gong-won', example: '한강공원에서 치맥을 했어요.', exampleTranslation: 'I had chicken and beer at Hangang Park.' },
    { korean: '제주도', english: 'Jeju Island', pronunciation: 'je-ju-do', example: '제주도에 3박 4일로 갔어요.', exampleTranslation: 'I went to Jeju Island for 3 nights and 4 days.' },
    { korean: '부산', english: 'Busan', pronunciation: 'bu-san', example: '부산에서 해운대 해변에 갔어요.', exampleTranslation: 'I went to Haeundae Beach in Busan.' },
    { korean: '경주', english: 'Gyeongju', pronunciation: 'gyeong-ju', example: '경주는 역사 도시예요.', exampleTranslation: 'Gyeongju is a historical city.' },
    { korean: '전주', english: 'Jeonju', pronunciation: 'jeon-ju', example: '전주 한옥마을이 유명해요.', exampleTranslation: 'Jeonju Hanok Village is famous.' },
    { korean: '강릉', english: 'Gangneung', pronunciation: 'gang-neung', example: '강릉에 커피거리가 있어요.', exampleTranslation: 'There is a coffee street in Gangneung.' },
    { korean: '설악산', english: 'Seoraksan Mountain', pronunciation: 'seol-ak-san', example: '설악산에 등산하러 갔어요.', exampleTranslation: 'I went hiking at Seoraksan.' },
    { korean: '등산', english: 'Hiking / Mountain climbing', pronunciation: 'deung-san', example: '한국에서 등산이 인기 많아요.', exampleTranslation: 'Hiking is very popular in Korea.' },
    { korean: '산책', english: 'Walk / Stroll', pronunciation: 'san-chaek', example: '강변에서 산책했어요.', exampleTranslation: 'I took a walk by the river.' },
    { korean: '자연', english: 'Nature', pronunciation: 'ja-yeon', example: '자연이 아름다운 곳이에요.', exampleTranslation: 'It is a place with beautiful nature.' },
    { korean: '폭포', english: 'Waterfall', pronunciation: 'pok-po', example: '폭포가 웅장해요.', exampleTranslation: 'The waterfall is magnificent.' },
    { korean: '동굴', english: 'Cave', pronunciation: 'dong-gul', example: '동굴 탐험을 했어요.', exampleTranslation: 'I explored the cave.' },
    { korean: '온천', english: 'Hot spring', pronunciation: 'on-cheon', example: '온천에서 피로를 풀었어요.', exampleTranslation: 'I relieved fatigue at the hot spring.' },
    { korean: '찜질방', english: 'Jjimjilbang (Korean spa)', pronunciation: 'jjim-jil-bang', example: '찜질방에서 하룻밤 잤어요.', exampleTranslation: 'I slept overnight at the jjimjilbang.' },
    { korean: '사우나', english: 'Sauna', pronunciation: 'sa-u-na', example: '사우나에 가서 땀을 뺐어요.', exampleTranslation: 'I went to the sauna and sweated.' },
    { korean: '벚꽃', english: 'Cherry blossom', pronunciation: 'beot-kkot', example: '봄에 벚꽃 구경 가자.', exampleTranslation: 'Let\'s go see cherry blossoms in spring.' },
    { korean: '단풍', english: 'Autumn foliage', pronunciation: 'dan-pung', example: '단풍이 물들었어요.', exampleTranslation: 'The autumn leaves have turned colors.' },
    { korean: '설경', english: 'Snow scenery', pronunciation: 'seol-gyeong', example: '겨울 설경이 멋져요.', exampleTranslation: 'The winter snow scenery is wonderful.' },
    { korean: '캠핑', english: 'Camping', pronunciation: 'kaem-ping', example: '캠핑하러 갈까요?', exampleTranslation: 'Shall we go camping?' },
    { korean: '글램핑', english: 'Glamping', pronunciation: 'geul-laem-ping', example: '글램핑장을 예약했어요.', exampleTranslation: 'I reserved a glamping site.' },
    { korean: '서핑', english: 'Surfing', pronunciation: 'seo-ping', example: '양양에서 서핑을 했어요.', exampleTranslation: 'I went surfing in Yangyang.' },
    { korean: '스키', english: 'Skiing', pronunciation: 'seu-ki', example: '겨울에 스키 타러 갈 거예요.', exampleTranslation: 'I will go skiing in winter.' },
    { korean: '스노보드', english: 'Snowboard', pronunciation: 'seu-no-bo-deu', example: '스노보드를 처음 탔어요.', exampleTranslation: 'I rode a snowboard for the first time.' },
    { korean: '래프팅', english: 'Rafting', pronunciation: 'rae-peu-ting', example: '래프팅이 정말 재미있었어요.', exampleTranslation: 'Rafting was really fun.' },
    { korean: '짚라인', english: 'Zipline', pronunciation: 'jip-ra-in', example: '짚라인을 타 봤어요?', exampleTranslation: 'Have you tried a zipline?' },
    { korean: '전시회', english: 'Exhibition', pronunciation: 'jeon-si-hoe', example: '전시회에 갈까요?', exampleTranslation: 'Shall we go to the exhibition?' },
    { korean: '공연', english: 'Performance / Show', pronunciation: 'gong-yeon', example: '한국 전통 공연을 봤어요.', exampleTranslation: 'I watched a Korean traditional performance.' },
    { korean: '뮤지컬', english: 'Musical', pronunciation: 'myu-ji-keol', example: '대학로에서 뮤지컬을 봤어요.', exampleTranslation: 'I watched a musical in Daehangno.' },
    { korean: '노래방', english: 'Karaoke room', pronunciation: 'no-rae-bang', example: '노래방에 가서 노래 부르자.', exampleTranslation: "Let's go sing at the karaoke room." },
    { korean: '피시방', english: 'PC room (internet cafe)', pronunciation: 'pi-si-bang', example: '피시방에서 게임했어요.', exampleTranslation: 'I played games at the PC room.' },
    { korean: '한옥', english: 'Hanok (traditional house)', pronunciation: 'han-ok', example: '한옥에서 하룻밤 자 봤어요.', exampleTranslation: 'I stayed overnight in a hanok.' },
    { korean: '비자', english: 'Visa', pronunciation: 'bi-ja', example: '비자를 신청해야 해요.', exampleTranslation: 'I need to apply for a visa.' },
    { korean: '출입국', english: 'Immigration', pronunciation: 'chul-ip-guk', example: '출입국 관리사무소에 갔어요.', exampleTranslation: 'I went to the immigration office.' },
    { korean: '신고', english: 'Declaration / Report', pronunciation: 'sin-go', example: '세관 신고서를 작성했어요.', exampleTranslation: 'I filled out the customs declaration form.' },
    { korean: '보험', english: 'Insurance', pronunciation: 'bo-heom', example: '여행자 보험에 가입했어요.', exampleTranslation: "I signed up for traveler's insurance." },
    { korean: '여행사', english: 'Travel agency', pronunciation: 'yeo-haeng-sa', example: '여행사에서 투어를 예약했어요.', exampleTranslation: 'I booked a tour through a travel agency.' },
    { korean: '가이드북', english: 'Guidebook', pronunciation: 'ga-i-deu-buk', example: '가이드북을 사서 읽었어요.', exampleTranslation: 'I bought and read a guidebook.' },
    { korean: '코스', english: 'Course / Route', pronunciation: 'ko-seu', example: '추천 코스가 있어요?', exampleTranslation: 'Is there a recommended course?' },
    { korean: '올레길', english: 'Olle Trail (Jeju)', pronunciation: 'ol-le-gil', example: '올레길을 걸으면서 힐링했어요.', exampleTranslation: 'I healed while walking the Olle Trail.' },
    { korean: '둘레길', english: 'Dulle Trail', pronunciation: 'dul-le-gil', example: '서울 둘레길이 좋아요.', exampleTranslation: 'The Seoul Dulle Trail is nice.' },
    { korean: '해돋이', english: 'Sunrise (at sea)', pronunciation: 'hae-do-ji', example: '새해 해돋이를 보러 갔어요.', exampleTranslation: 'I went to see the New Year sunrise.' },
    { korean: '야경', english: 'Night view', pronunciation: 'ya-gyeong', example: '서울 야경이 멋져요.', exampleTranslation: 'The night view of Seoul is wonderful.' },
    { korean: '전망대', english: 'Observation deck', pronunciation: 'jeon-mang-dae', example: '전망대에서 경치를 봤어요.', exampleTranslation: 'I saw the view from the observation deck.' },
    { korean: '케이블카', english: 'Cable car', pronunciation: 'ke-i-beul-ka', example: '케이블카를 타고 올라갔어요.', exampleTranslation: 'I went up by cable car.' },
    { korean: '유람선', english: 'Cruise boat', pronunciation: 'yu-ram-seon', example: '한강 유람선을 탔어요.', exampleTranslation: 'I rode the Han River cruise boat.' },
    { korean: '놀거리', english: 'Things to do / Fun activities', pronunciation: 'nol-geo-ri', example: '놀거리가 많은 곳이에요.', exampleTranslation: 'It is a place with many fun activities.' },
    { korean: '먹거리', english: 'Things to eat / Food options', pronunciation: 'meok-geo-ri', example: '이 지역은 먹거리가 풍부해요.', exampleTranslation: 'This area has abundant food options.' },
    { korean: '볼거리', english: 'Things to see / Sights', pronunciation: 'bol-geo-ri', example: '볼거리가 다양해요.', exampleTranslation: 'There are various things to see.' },
    { korean: '노을', english: 'Glow of sunset', pronunciation: 'no-eul', example: '해변에서 본 노을이 예뻤어요.', exampleTranslation: 'The sunset glow I saw at the beach was beautiful.' },
    { korean: '국내여행', english: 'Domestic travel', pronunciation: 'gung-nae-yeo-haeng', example: '요즘 국내여행이 인기예요.', exampleTranslation: 'Domestic travel is popular these days.' },
    { korean: '해외여행', english: 'Overseas travel', pronunciation: 'hae-oe-yeo-haeng', example: '해외여행을 가고 싶어요.', exampleTranslation: 'I want to travel overseas.' },
    { korean: '배낭여행', english: 'Backpacking', pronunciation: 'bae-nang-yeo-haeng', example: '배낭여행으로 유럽을 갔어요.', exampleTranslation: 'I went to Europe backpacking.' },
    { korean: '한류', english: 'Korean Wave (Hallyu)', pronunciation: 'hal-lyu', example: '한류 덕분에 한국 관광객이 늘었어요.', exampleTranslation: 'Korean tourists increased thanks to Hallyu.' },
    { korean: '한식', english: 'Korean food', pronunciation: 'han-sik', example: '한식을 먹으러 갈까요?', exampleTranslation: 'Shall we go eat Korean food?' },
    { korean: '길거리 음식', english: 'Street food', pronunciation: 'gil-geo-ri eum-sik', example: '한국 길거리 음식이 맛있어요.', exampleTranslation: 'Korean street food is delicious.' },
    { korean: '포토존', english: 'Photo zone', pronunciation: 'po-to-jon', example: '포토존에서 사진 찍자.', exampleTranslation: "Let's take photos at the photo zone." },
    { korean: '셀카봉', english: 'Selfie stick', pronunciation: 'sel-ka-bong', example: '셀카봉을 가져왔어요?', exampleTranslation: 'Did you bring a selfie stick?' },
    { korean: '보조배터리', english: 'Portable charger', pronunciation: 'bo-jo-bae-teo-ri', example: '보조배터리가 필요해요.', exampleTranslation: 'I need a portable charger.' },
    { korean: '필수품', english: 'Essentials', pronunciation: 'pil-su-pum', example: '여행 필수품을 챙겼어요.', exampleTranslation: 'I packed travel essentials.' },
    { korean: '환전소', english: 'Currency exchange office', pronunciation: 'hwan-jeon-so', example: '환전소가 근처에 있어요?', exampleTranslation: 'Is there a currency exchange nearby?' },
    { korean: '현지인', english: 'Local person', pronunciation: 'hyeon-ji-in', example: '현지인 추천 맛집에 갔어요.', exampleTranslation: 'I went to a restaurant recommended by locals.' },
    { korean: '관광 버스', english: 'Tour bus', pronunciation: 'gwan-gwang beo-seu', example: '관광 버스를 타고 투어했어요.', exampleTranslation: 'I toured by tour bus.' },
    { korean: '시외버스', english: 'Intercity bus', pronunciation: 'si-oe-beo-seu', example: '시외버스로 전주에 갔어요.', exampleTranslation: 'I went to Jeonju by intercity bus.' },
    { korean: '고속버스', english: 'Express bus', pronunciation: 'go-sok-beo-seu', example: '고속버스 터미널이 어디예요?', exampleTranslation: 'Where is the express bus terminal?' },
    { korean: '터미널', english: 'Terminal', pronunciation: 'teo-mi-neol', example: '버스 터미널에서 만나요.', exampleTranslation: "Let's meet at the bus terminal." },
    { korean: '기내식', english: 'In-flight meal', pronunciation: 'gi-nae-sik', example: '기내식이 맛있었어요.', exampleTranslation: 'The in-flight meal was delicious.' },
    { korean: '기내 반입', english: 'Carry-on (airplane)', pronunciation: 'gi-nae ban-ip', example: '기내 반입이 가능한 크기예요?', exampleTranslation: 'Is this carry-on size?' },
    { korean: '위탁 수하물', english: 'Checked baggage', pronunciation: 'wi-tak su-ha-mul', example: '위탁 수하물이 몇 킬로까지 돼요?', exampleTranslation: 'How many kilos are allowed for checked baggage?' },
    { korean: '트래킹', english: 'Trekking', pronunciation: 'teu-rae-king', example: '트래킹 코스가 잘 되어 있어요.', exampleTranslation: 'The trekking course is well organized.' },
    { korean: '스쿠버', english: 'Scuba diving', pronunciation: 'seu-ku-beo', example: '제주도에서 스쿠버를 했어요.', exampleTranslation: 'I went scuba diving in Jeju.' },
    { korean: '낚시', english: 'Fishing', pronunciation: 'nak-si', example: '바다에서 낚시를 했어요.', exampleTranslation: 'I went fishing at the sea.' },
    { korean: '한정식', english: 'Korean full-course meal', pronunciation: 'han-jeong-sik', example: '한정식을 먹어 봤어요.', exampleTranslation: 'I tried a Korean full-course meal.' },
    { korean: '수상 레저', english: 'Water sports', pronunciation: 'su-sang re-jeo', example: '수상 레저 활동을 즐겼어요.', exampleTranslation: 'I enjoyed water sports activities.' },
    { korean: '패러글라이딩', english: 'Paragliding', pronunciation: 'pae-reo-geul-la-i-ding', example: '양평에서 패러글라이딩을 했어요.', exampleTranslation: 'I went paragliding in Yangpyeong.' },
    { korean: '번지점프', english: 'Bungee jumping', pronunciation: 'beon-ji-jeom-peu', example: '번지점프를 해 본 적 있어요?', exampleTranslation: 'Have you tried bungee jumping?' },
    { korean: '사찰', english: 'Buddhist temple', pronunciation: 'sa-chal', example: '산속에 오래된 사찰이 있어요.', exampleTranslation: 'There is an old Buddhist temple in the mountains.' },
  ],
  4: [
    { korean: '여행 계획', english: 'Travel plan', pronunciation: 'yeo-haeng gye-hoek', example: '여행 계획을 세우고 있어요.', exampleTranslation: 'I am making travel plans.' },
    { korean: '항공편', english: 'Flight', pronunciation: 'hang-gong-pyeon', example: '항공편을 비교하고 있어요.', exampleTranslation: 'I am comparing flights.' },
    { korean: '직항', english: 'Direct flight', pronunciation: 'jik-hang', example: '직항이 있으면 편해요.', exampleTranslation: 'It is convenient if there is a direct flight.' },
    { korean: '경유', english: 'Stopover / Layover', pronunciation: 'gyeong-yu', example: '경유해서 가면 더 싸요.', exampleTranslation: 'It is cheaper to go with a stopover.' },
    { korean: '저가항공', english: 'Budget airline', pronunciation: 'jeo-ga-hang-gong', example: '저가항공으로 표를 샀어요.', exampleTranslation: 'I bought a ticket with a budget airline.' },
    { korean: '마일리지', english: 'Mileage points', pronunciation: 'ma-il-li-ji', example: '마일리지로 항공권을 샀어요.', exampleTranslation: 'I bought a flight ticket with mileage points.' },
    { korean: '항공권', english: 'Airline ticket', pronunciation: 'hang-gong-gwon', example: '항공권 가격이 올랐어요.', exampleTranslation: 'Airline ticket prices went up.' },
    { korean: '특가', english: 'Special deal / Sale', pronunciation: 'teuk-ga', example: '항공권 특가를 잡았어요.', exampleTranslation: 'I grabbed an airline special deal.' },
    { korean: '성수기', english: 'Peak season', pronunciation: 'seong-su-gi', example: '성수기에는 가격이 비싸요.', exampleTranslation: 'Prices are expensive during peak season.' },
    { korean: '비수기', english: 'Off-season', pronunciation: 'bi-su-gi', example: '비수기에 가면 한적해요.', exampleTranslation: 'It is quiet if you go during off-season.' },
    { korean: '여행 경비', english: 'Travel expenses', pronunciation: 'yeo-haeng gyeong-bi', example: '여행 경비를 계산했어요.', exampleTranslation: 'I calculated the travel expenses.' },
    { korean: '예산', english: 'Budget', pronunciation: 'ye-san', example: '여행 예산을 정했어요.', exampleTranslation: 'I set a travel budget.' },
    { korean: '숙박비', english: 'Accommodation cost', pronunciation: 'suk-bak-bi', example: '숙박비가 많이 들었어요.', exampleTranslation: 'The accommodation cost was high.' },
    { korean: '교통비', english: 'Transportation cost', pronunciation: 'gyo-tong-bi', example: '교통비를 줄이고 싶어요.', exampleTranslation: 'I want to reduce transportation costs.' },
    { korean: '입장료', english: 'Admission fee', pronunciation: 'ip-jang-nyo', example: '입장료가 할인이 돼요.', exampleTranslation: 'The admission fee is discounted.' },
    { korean: '가성비', english: 'Cost-effectiveness', pronunciation: 'ga-seong-bi', example: '가성비 좋은 숙소를 찾았어요.', exampleTranslation: 'I found cost-effective accommodation.' },
    { korean: '후기', english: 'Review', pronunciation: 'hu-gi', example: '여행 후기를 읽어 봤어요.', exampleTranslation: 'I read travel reviews.' },
    { korean: '평점', english: 'Rating', pronunciation: 'pyeong-jeom', example: '이 호텔 평점이 높아요.', exampleTranslation: 'This hotel has a high rating.' },
    { korean: '블로그', english: 'Blog', pronunciation: 'beul-lo-geu', example: '여행 블로그에서 정보를 얻었어요.', exampleTranslation: 'I got information from a travel blog.' },
    { korean: '핫플레이스', english: 'Hot place / Trendy spot', pronunciation: 'hat-peul-le-i-seu', example: '요즘 핫플레이스가 어디예요?', exampleTranslation: 'Where is the trendy spot these days?' },
    { korean: '맛집', english: 'Famous restaurant', pronunciation: 'mat-jip', example: '맛집 리스트를 만들었어요.', exampleTranslation: 'I made a list of famous restaurants.' },
    { korean: '카페 투어', english: 'Cafe tour', pronunciation: 'ka-pe tu-eo', example: '성수동에서 카페 투어를 했어요.', exampleTranslation: 'I did a cafe tour in Seongsu-dong.' },
    { korean: '역사', english: 'History', pronunciation: 'yeok-sa', example: '한국 역사에 관심이 있어요.', exampleTranslation: 'I am interested in Korean history.' },
    { korean: '왕조', english: 'Dynasty', pronunciation: 'wang-jo', example: '조선 왕조의 유적이 많아요.', exampleTranslation: 'There are many relics of the Joseon Dynasty.' },
    { korean: '조선', english: 'Joseon (dynasty)', pronunciation: 'jo-seon', example: '조선 시대의 건축물이 아름다워요.', exampleTranslation: 'Joseon era architecture is beautiful.' },
    { korean: '고려', english: 'Goryeo (dynasty)', pronunciation: 'go-ryeo', example: '고려 시대의 청자가 유명해요.', exampleTranslation: 'Goryeo-era celadon is famous.' },
    { korean: '삼국시대', english: 'Three Kingdoms period', pronunciation: 'sam-guk-si-dae', example: '삼국시대의 유물을 봤어요.', exampleTranslation: 'I saw artifacts from the Three Kingdoms period.' },
    { korean: '유물', english: 'Artifact / Relic', pronunciation: 'yu-mul', example: '박물관에 귀한 유물이 있어요.', exampleTranslation: 'There are precious artifacts in the museum.' },
    { korean: '보물', english: 'National treasure (designation)', pronunciation: 'bo-mul', example: '이 탑은 보물로 지정되어 있어요.', exampleTranslation: 'This pagoda is designated as a national treasure.' },
    { korean: '국보', english: 'National treasure (highest)', pronunciation: 'guk-bo', example: '숭례문은 국보 1호예요.', exampleTranslation: 'Sungnyemun is National Treasure No. 1.' },
    { korean: '전통시장', english: 'Traditional market', pronunciation: 'jeon-tong-si-jang', example: '전통시장에서 먹방했어요.', exampleTranslation: 'I ate my way through a traditional market.' },
    { korean: '남대문시장', english: 'Namdaemun Market', pronunciation: 'nam-dae-mun-si-jang', example: '남대문시장에서 쇼핑했어요.', exampleTranslation: 'I went shopping at Namdaemun Market.' },
    { korean: '동대문시장', english: 'Dongdaemun Market', pronunciation: 'dong-dae-mun-si-jang', example: '동대문시장은 밤에도 열어요.', exampleTranslation: 'Dongdaemun Market is open at night too.' },
    { korean: '광장시장', english: 'Gwangjang Market', pronunciation: 'gwang-jang-si-jang', example: '광장시장 빈대떡이 유명해요.', exampleTranslation: 'Gwangjang Market mung bean pancakes are famous.' },
    { korean: '지방', english: 'Province / Regional area', pronunciation: 'ji-bang', example: '지방 여행도 추천해요.', exampleTranslation: 'I also recommend regional travel.' },
    { korean: '수도권', english: 'Capital region', pronunciation: 'su-do-gwon', example: '수도권에 볼거리가 많아요.', exampleTranslation: 'There are many things to see in the capital region.' },
    { korean: '남해', english: 'Southern Sea / Namhae', pronunciation: 'nam-hae', example: '남해 독일마을이 예뻐요.', exampleTranslation: 'The German Village in Namhae is pretty.' },
    { korean: '동해', english: 'East Sea', pronunciation: 'dong-hae', example: '동해에서 해돋이를 봤어요.', exampleTranslation: 'I saw the sunrise at the East Sea.' },
    { korean: '서해', english: 'West Sea', pronunciation: 'seo-hae', example: '서해에서 갯벌 체험을 했어요.', exampleTranslation: 'I experienced a mud flat at the West Sea.' },
    { korean: '갯벌', english: 'Mud flat / Tidal flat', pronunciation: 'gaet-beol', example: '갯벌에서 조개를 캤어요.', exampleTranslation: 'I dug clams at the tidal flat.' },
    { korean: '사투리', english: 'Dialect', pronunciation: 'sa-tu-ri', example: '부산 사투리가 재미있어요.', exampleTranslation: 'The Busan dialect is fun.' },
    { korean: '특산물', english: 'Local specialty product', pronunciation: 'teuk-san-mul', example: '제주 특산물은 감귤이에요.', exampleTranslation: 'The specialty of Jeju is tangerines.' },
    { korean: '향토 음식', english: 'Local cuisine', pronunciation: 'hyang-to eum-sik', example: '각 지방의 향토 음식이 달라요.', exampleTranslation: 'Each region has different local cuisine.' },
    { korean: '해녀', english: 'Female diver (Jeju)', pronunciation: 'hae-nyeo', example: '제주 해녀 문화가 유네스코에 등재됐어요.', exampleTranslation: 'Jeju haenyeo culture was listed by UNESCO.' },
    { korean: '한라산', english: 'Hallasan Mountain', pronunciation: 'hal-la-san', example: '한라산 정상까지 등산했어요.', exampleTranslation: 'I hiked to the summit of Hallasan.' },
    { korean: '용암', english: 'Lava', pronunciation: 'yong-am', example: '제주도는 용암으로 만들어진 섬이에요.', exampleTranslation: 'Jeju Island is an island made of lava.' },
    { korean: '해수욕장', english: 'Swimming beach', pronunciation: 'hae-su-yok-jang', example: '해수욕장에서 수영했어요.', exampleTranslation: 'I swam at the swimming beach.' },
    { korean: '산림욕', english: 'Forest bathing', pronunciation: 'sal-lim-yok', example: '산림욕을 하면 건강에 좋아요.', exampleTranslation: 'Forest bathing is good for health.' },
    { korean: '치유', english: 'Healing', pronunciation: 'chi-yu', example: '자연 속에서 치유의 시간을 보냈어요.', exampleTranslation: 'I spent healing time in nature.' },
    { korean: '힐링', english: 'Healing (relaxation)', pronunciation: 'hil-ling', example: '힐링 여행을 다녀왔어요.', exampleTranslation: 'I went on a healing trip.' },
    { korean: '워케이션', english: 'Workation', pronunciation: 'wo-ke-i-syeon', example: '제주도에서 워케이션을 했어요.', exampleTranslation: 'I did a workation in Jeju.' },
    { korean: '한옥 스테이', english: 'Hanok stay', pronunciation: 'han-ok seu-te-i', example: '한옥 스테이 체험이 좋았어요.', exampleTranslation: 'The hanok stay experience was great.' },
    { korean: '템플 스테이', english: 'Temple stay', pronunciation: 'tem-peul seu-te-i', example: '템플 스테이로 마음을 다스렸어요.', exampleTranslation: 'I calmed my mind through a temple stay.' },
    { korean: '전통 체험', english: 'Traditional experience', pronunciation: 'jeon-tong che-heom', example: '전통 체험 프로그램에 참가했어요.', exampleTranslation: 'I participated in a traditional experience program.' },
    { korean: '도자기', english: 'Pottery / Ceramics', pronunciation: 'do-ja-gi', example: '이천에서 도자기 만들기를 했어요.', exampleTranslation: 'I made pottery in Icheon.' },
    { korean: '김치 만들기', english: 'Kimchi making', pronunciation: 'gim-chi man-deul-gi', example: '김치 만들기 체험을 했어요.', exampleTranslation: 'I did a kimchi-making experience.' },
    { korean: '태권도', english: 'Taekwondo', pronunciation: 'tae-gwon-do', example: '태권도 체험을 할 수 있어요.', exampleTranslation: 'You can experience taekwondo.' },
    { korean: '사물놀이', english: 'Samulnori (percussion)', pronunciation: 'sa-mul-nor-i', example: '사물놀이 공연이 인상적이었어요.', exampleTranslation: 'The samulnori performance was impressive.' },
    { korean: '판소리', english: 'Pansori (narrative singing)', pronunciation: 'pan-so-ri', example: '판소리를 처음 들어 봤어요.', exampleTranslation: 'I heard pansori for the first time.' },
    { korean: '탈춤', english: 'Mask dance', pronunciation: 'tal-chum', example: '안동에서 탈춤을 봤어요.', exampleTranslation: 'I saw a mask dance in Andong.' },
    { korean: '하회마을', english: 'Hahoe Village', pronunciation: 'ha-hoe-ma-eul', example: '하회마을은 유네스코 세계유산이에요.', exampleTranslation: 'Hahoe Village is a UNESCO World Heritage site.' },
    { korean: '안동', english: 'Andong', pronunciation: 'an-dong', example: '안동 찜닭을 먹어 봤어요.', exampleTranslation: 'I tried Andong jjimdak (braised chicken).' },
    { korean: '속초', english: 'Sokcho', pronunciation: 'sok-cho', example: '속초에서 아바이순대를 먹었어요.', exampleTranslation: 'I ate Abai sundae in Sokcho.' },
    { korean: '여수', english: 'Yeosu', pronunciation: 'yeo-su', example: '여수 밤바다가 유명해요.', exampleTranslation: 'The night sea of Yeosu is famous.' },
    { korean: '통영', english: 'Tongyeong', pronunciation: 'tong-yeong', example: '통영 케이블카를 탔어요.', exampleTranslation: 'I rode the cable car in Tongyeong.' },
    { korean: '대구', english: 'Daegu', pronunciation: 'dae-gu', example: '대구는 여름에 정말 더워요.', exampleTranslation: 'Daegu is really hot in summer.' },
    { korean: '광주', english: 'Gwangju', pronunciation: 'gwang-ju', example: '광주 비엔날레에 갔어요.', exampleTranslation: 'I went to the Gwangju Biennale.' },
    { korean: '대전', english: 'Daejeon', pronunciation: 'dae-jeon', example: '대전 성심당 빵이 유명해요.', exampleTranslation: 'Seongsim-dang bakery in Daejeon is famous.' },
    { korean: '인천', english: 'Incheon', pronunciation: 'in-cheon', example: '인천공항에서 출발했어요.', exampleTranslation: 'I departed from Incheon Airport.' },
    { korean: '수원', english: 'Suwon', pronunciation: 'su-won', example: '수원 화성을 구경했어요.', exampleTranslation: 'I looked around Suwon Hwaseong Fortress.' },
    { korean: '촬영지', english: 'Filming location', pronunciation: 'chwal-yeong-ji', example: '드라마 촬영지를 방문했어요.', exampleTranslation: 'I visited a drama filming location.' },
    { korean: '감상', english: 'Appreciation / Viewing', pronunciation: 'gam-sang', example: '벚꽃 감상을 했어요.', exampleTranslation: 'I enjoyed cherry blossom viewing.' },
    { korean: '추억', english: 'Memory', pronunciation: 'chu-eok', example: '좋은 추억을 만들었어요.', exampleTranslation: 'I made good memories.' },
    { korean: '인생샷', english: 'Best photo ever', pronunciation: 'in-saeng-syat', example: '여기서 인생샷을 찍었어요.', exampleTranslation: 'I took the best photo ever here.' },
    { korean: '풍경', english: 'Landscape', pronunciation: 'pung-gyeong', example: '풍경이 그림 같아요.', exampleTranslation: 'The landscape is like a painting.' },
    { korean: '해안도로', english: 'Coastal road', pronunciation: 'hae-an-do-ro', example: '해안도로를 드라이브했어요.', exampleTranslation: 'I drove along the coastal road.' },
    { korean: '드라이브', english: 'Drive (leisure)', pronunciation: 'deu-ra-i-beu', example: '가을에 드라이브하기 좋아요.', exampleTranslation: 'It is nice to drive in autumn.' },
    { korean: '국립공원', english: 'National park', pronunciation: 'gung-nip-gong-won', example: '국립공원에서 캠핑했어요.', exampleTranslation: 'I camped at the national park.' },
    { korean: '습지', english: 'Wetland', pronunciation: 'seup-ji', example: '순천만 습지가 아름다워요.', exampleTranslation: 'Suncheon Bay wetland is beautiful.' },
    { korean: '생태 관광', english: 'Eco-tourism', pronunciation: 'saeng-tae gwan-gwang', example: '생태 관광에 관심이 많아요.', exampleTranslation: 'I am very interested in eco-tourism.' },
    { korean: '농촌 체험', english: 'Farm experience', pronunciation: 'nong-chon che-heom', example: '농촌 체험 마을에 갔어요.', exampleTranslation: 'I went to a farm experience village.' },
    { korean: '이동 시간', english: 'Travel time', pronunciation: 'i-dong si-gan', example: '이동 시간이 너무 길어요.', exampleTranslation: 'The travel time is too long.' },
    { korean: '경로', english: 'Route / Path', pronunciation: 'gyeong-no', example: '최단 경로를 찾아봤어요.', exampleTranslation: 'I looked up the shortest route.' },
    { korean: '내비게이션', english: 'Navigation (GPS)', pronunciation: 'nae-bi-ge-i-syeon', example: '내비게이션을 켜세요.', exampleTranslation: 'Turn on the navigation.' },
    { korean: '주차장', english: 'Parking lot', pronunciation: 'ju-cha-jang', example: '주차장이 넓어요.', exampleTranslation: 'The parking lot is spacious.' },
    { korean: '주차', english: 'Parking', pronunciation: 'ju-cha', example: '주차할 곳이 없어요.', exampleTranslation: 'There is no place to park.' },
    { korean: '톨게이트', english: 'Tollgate', pronunciation: 'tol-ge-i-teu', example: '톨게이트에서 통행료를 냈어요.', exampleTranslation: 'I paid the toll at the tollgate.' },
    { korean: '하이패스', english: 'Hi-Pass (highway toll)', pronunciation: 'ha-i-pae-seu', example: '하이패스가 있으면 편해요.', exampleTranslation: 'It is convenient if you have Hi-Pass.' },
    { korean: '고속도로', english: 'Highway / Expressway', pronunciation: 'go-sok-do-ro', example: '고속도로가 막혀요.', exampleTranslation: 'The highway is congested.' },
    { korean: '교통 체증', english: 'Traffic congestion', pronunciation: 'gyo-tong che-jeung', example: '명절에 교통 체증이 심해요.', exampleTranslation: 'Traffic congestion is severe during holidays.' },
    { korean: '리조트', english: 'Resort', pronunciation: 'ri-jo-teu', example: '리조트에서 쉬면서 지냈어요.', exampleTranslation: 'I relaxed at a resort.' },
    { korean: '콘도', english: 'Condo (vacation)', pronunciation: 'kon-do', example: '콘도를 예약했어요.', exampleTranslation: 'I booked a condo.' },
    { korean: '호캉스', english: 'Hotelcation (hotel + vacation)', pronunciation: 'ho-kang-seu', example: '호캉스로 힐링했어요.', exampleTranslation: 'I healed with a hotelcation.' },
    { korean: '럭셔리', english: 'Luxury', pronunciation: 'reok-syeo-ri', example: '럭셔리 호텔에서 묵었어요.', exampleTranslation: 'I stayed at a luxury hotel.' },
    { korean: '조용하다', english: 'Quiet', pronunciation: 'jo-yong-ha-da', example: '이 마을은 조용하고 좋아요.', exampleTranslation: 'This village is quiet and nice.' },
    { korean: '번잡하다', english: 'Crowded / Bustling', pronunciation: 'beon-jap-ha-da', example: '주말에는 너무 번잡해요.', exampleTranslation: 'It is too crowded on weekends.' },
    { korean: '시골', english: 'Countryside', pronunciation: 'si-gol', example: '시골 여행이 좋았어요.', exampleTranslation: 'The countryside trip was great.' },
    { korean: '도심', english: 'City center', pronunciation: 'do-sim', example: '도심에서 벗어나고 싶어요.', exampleTranslation: 'I want to get away from the city center.' },
    { korean: '문화재', english: 'Cultural property', pronunciation: 'mun-hwa-jae', example: '이곳은 중요한 문화재예요.', exampleTranslation: 'This is an important cultural property.' },
    { korean: '명절', english: 'Holiday (traditional)', pronunciation: 'myeong-jeol', example: '명절에는 귀성 차량이 많아요.', exampleTranslation: 'There are many cars heading home during holidays.' },
  ],
  5: [
    { korean: '문화유산', english: 'Cultural heritage', pronunciation: 'mun-hwa-yu-san', example: '한국의 문화유산을 보존해야 해요.', exampleTranslation: 'We must preserve Korean cultural heritage.' },
    { korean: '세계유산', english: 'World Heritage', pronunciation: 'se-gye-yu-san', example: '한국에 유네스코 세계유산이 많아요.', exampleTranslation: 'Korea has many UNESCO World Heritage sites.' },
    { korean: '무형문화재', english: 'Intangible cultural property', pronunciation: 'mu-hyeong-mun-hwa-jae', example: '판소리는 무형문화재로 지정되어 있어요.', exampleTranslation: 'Pansori is designated as an intangible cultural property.' },
    { korean: '유형문화재', english: 'Tangible cultural property', pronunciation: 'yu-hyeong-mun-hwa-jae', example: '이 건물은 유형문화재예요.', exampleTranslation: 'This building is a tangible cultural property.' },
    { korean: '문화재 보호', english: 'Cultural property protection', pronunciation: 'mun-hwa-jae bo-ho', example: '문화재 보호가 중요해요.', exampleTranslation: 'Cultural property protection is important.' },
    { korean: '복원', english: 'Restoration', pronunciation: 'bok-won', example: '궁궐 복원 작업이 진행 중이에요.', exampleTranslation: 'Palace restoration work is in progress.' },
    { korean: '발굴', english: 'Excavation', pronunciation: 'bal-gul', example: '유적지에서 발굴 작업을 하고 있어요.', exampleTranslation: 'Excavation work is being done at the historical site.' },
    { korean: '고고학', english: 'Archaeology', pronunciation: 'go-go-hak', example: '고고학적으로 중요한 유적이에요.', exampleTranslation: 'It is an archaeologically important site.' },
    { korean: '지형', english: 'Terrain / Topography', pronunciation: 'ji-hyeong', example: '한국의 지형은 산이 많아요.', exampleTranslation: 'Korea\'s terrain is mostly mountainous.' },
    { korean: '반도', english: 'Peninsula', pronunciation: 'ban-do', example: '한국은 반도 국가예요.', exampleTranslation: 'Korea is a peninsular country.' },
    { korean: '해안선', english: 'Coastline', pronunciation: 'hae-an-seon', example: '한국은 해안선이 복잡해요.', exampleTranslation: 'Korea has a complex coastline.' },
    { korean: '해협', english: 'Strait', pronunciation: 'hae-hyeop', example: '대한해협을 건너면 일본이에요.', exampleTranslation: 'Crossing the Korea Strait leads to Japan.' },
    { korean: '분지', english: 'Basin', pronunciation: 'bun-ji', example: '대구는 분지 지형이에요.', exampleTranslation: 'Daegu has a basin topography.' },
    { korean: '평야', english: 'Plain', pronunciation: 'pyeong-ya', example: '호남 평야가 넓어요.', exampleTranslation: 'The Honam Plain is expansive.' },
    { korean: '고원', english: 'Plateau', pronunciation: 'go-won', example: '대관령 고원에서 목장을 봤어요.', exampleTranslation: 'I saw a ranch at the Daegwallyeong Plateau.' },
    { korean: '하류', english: 'Downstream', pronunciation: 'ha-ryu', example: '한강 하류에 습지가 있어요.', exampleTranslation: 'There is a wetland downstream of the Han River.' },
    { korean: '상류', english: 'Upstream', pronunciation: 'sang-nyu', example: '강 상류의 물이 맑아요.', exampleTranslation: 'The water upstream of the river is clear.' },
    { korean: '계곡', english: 'Valley / Gorge', pronunciation: 'gye-gok', example: '여름에 계곡에서 물놀이 해요.', exampleTranslation: 'We play in the water at the valley in summer.' },
    { korean: '화산', english: 'Volcano', pronunciation: 'hwa-san', example: '한라산은 화산이에요.', exampleTranslation: 'Hallasan is a volcano.' },
    { korean: '현무암', english: 'Basalt', pronunciation: 'hyeon-mu-am', example: '제주도에 현무암이 많아요.', exampleTranslation: 'There is a lot of basalt on Jeju Island.' },
    { korean: '용암동굴', english: 'Lava tube / cave', pronunciation: 'yong-am-dong-gul', example: '만장굴은 유명한 용암동굴이에요.', exampleTranslation: 'Manjanggul is a famous lava tube.' },
    { korean: '지질공원', english: 'Geopark', pronunciation: 'ji-jil-gong-won', example: '제주도는 유네스코 지질공원이에요.', exampleTranslation: 'Jeju Island is a UNESCO Geopark.' },
    { korean: '생물권보전지역', english: 'Biosphere reserve', pronunciation: 'saeng-mul-gwon-bo-jeon-ji-yeok', example: '설악산은 생물권보전지역이에요.', exampleTranslation: 'Seoraksan is a biosphere reserve.' },
    { korean: '사증', english: 'Visa (formal)', pronunciation: 'sa-jeung', example: '사증을 발급받아야 해요.', exampleTranslation: 'I need to get a visa issued.' },
    { korean: '체류 기간', english: 'Period of stay', pronunciation: 'che-ryu gi-gan', example: '체류 기간이 만료되었어요.', exampleTranslation: 'The period of stay has expired.' },
    { korean: '체류 자격', english: 'Residency status', pronunciation: 'che-ryu ja-gyeok', example: '체류 자격을 확인하세요.', exampleTranslation: 'Check your residency status.' },
    { korean: '입국 심사', english: 'Immigration inspection', pronunciation: 'ip-guk sim-sa', example: '입국 심사가 엄격해졌어요.', exampleTranslation: 'Immigration inspection has become stricter.' },
    { korean: '출입국 관리', english: 'Immigration control', pronunciation: 'chul-ip-guk gwal-li', example: '출입국 관리 사무소에 가야 해요.', exampleTranslation: 'I need to go to the immigration control office.' },
    { korean: '외교', english: 'Diplomacy', pronunciation: 'oe-gyo', example: '외교적 관계가 관광에 영향을 미쳐요.', exampleTranslation: 'Diplomatic relations affect tourism.' },
    { korean: '대사관', english: 'Embassy', pronunciation: 'dae-sa-gwan', example: '대사관에 비자를 신청했어요.', exampleTranslation: 'I applied for a visa at the embassy.' },
    { korean: '영사관', english: 'Consulate', pronunciation: 'yeong-sa-gwan', example: '가까운 영사관에 연락하세요.', exampleTranslation: 'Contact the nearest consulate.' },
    { korean: '국적', english: 'Nationality', pronunciation: 'guk-jeok', example: '국적이 어디세요?', exampleTranslation: 'What is your nationality?' },
    { korean: '외국인 등록', english: 'Foreigner registration', pronunciation: 'oe-guk-in deung-rok', example: '외국인 등록증을 발급받았어요.', exampleTranslation: 'I received a foreigner registration card.' },
    { korean: '관광 비자', english: 'Tourist visa', pronunciation: 'gwan-gwang bi-ja', example: '관광 비자로 입국했어요.', exampleTranslation: 'I entered the country on a tourist visa.' },
    { korean: '무비자', english: 'Visa-free', pronunciation: 'mu-bi-ja', example: '한국은 무비자 입국이 가능해요.', exampleTranslation: 'Visa-free entry to Korea is possible.' },
    { korean: '검역', english: 'Quarantine', pronunciation: 'geom-yeok', example: '검역 절차를 통과해야 해요.', exampleTranslation: 'You need to pass the quarantine procedure.' },
    { korean: '면세', english: 'Tax-free / Duty-free', pronunciation: 'myeon-se', example: '면세 혜택을 받을 수 있어요.', exampleTranslation: 'You can receive tax-free benefits.' },
    { korean: '부가세 환급', english: 'VAT refund', pronunciation: 'bu-ga-se hwan-geup', example: '부가세 환급을 받았어요.', exampleTranslation: 'I received a VAT refund.' },
    { korean: '관세', english: 'Customs duty', pronunciation: 'gwan-se', example: '관세가 부과될 수 있어요.', exampleTranslation: 'Customs duty may be imposed.' },
    { korean: '반출', english: 'Taking out (of country)', pronunciation: 'ban-chul', example: '문화재 반출이 금지되어 있어요.', exampleTranslation: 'Taking cultural properties out of the country is prohibited.' },
    { korean: '반입', english: 'Bringing in (to country)', pronunciation: 'ban-ip', example: '반입 금지 물품을 확인하세요.', exampleTranslation: 'Check the prohibited items for bringing in.' },
    { korean: '지속 가능한 관광', english: 'Sustainable tourism', pronunciation: 'ji-sok ga-neung-han gwan-gwang', example: '지속 가능한 관광이 중요해요.', exampleTranslation: 'Sustainable tourism is important.' },
    { korean: '생태계', english: 'Ecosystem', pronunciation: 'saeng-tae-gye', example: '이 지역의 생태계를 보호해야 해요.', exampleTranslation: 'We must protect the ecosystem of this area.' },
    { korean: '멸종 위기', english: 'Endangered', pronunciation: 'myeol-jong wi-gi', example: '멸종 위기 동물을 보호해요.', exampleTranslation: 'We protect endangered animals.' },
    { korean: '천연기념물', english: 'Natural monument', pronunciation: 'cheon-yeon-gi-nyeom-mul', example: '이 나무는 천연기념물이에요.', exampleTranslation: 'This tree is a natural monument.' },
    { korean: '명승지', english: 'Scenic spot', pronunciation: 'myeong-seung-ji', example: '한국의 명승지를 여행했어요.', exampleTranslation: 'I traveled to scenic spots in Korea.' },
    { korean: '보호 구역', english: 'Protected area', pronunciation: 'bo-ho gu-yeok', example: '이곳은 야생 동물 보호 구역이에요.', exampleTranslation: 'This is a wildlife protected area.' },
    { korean: '민속촌', english: 'Folk village', pronunciation: 'min-sok-chon', example: '용인 민속촌에 갔어요.', exampleTranslation: 'I went to the Yongin Folk Village.' },
    { korean: '민속 문화', english: 'Folk culture', pronunciation: 'min-sok mun-hwa', example: '한국의 민속 문화가 다양해요.', exampleTranslation: 'Korean folk culture is diverse.' },
    { korean: '전통 공예', english: 'Traditional craft', pronunciation: 'jeon-tong gong-ye', example: '전통 공예를 배우고 싶어요.', exampleTranslation: 'I want to learn traditional crafts.' },
    { korean: '한지', english: 'Hanji (Korean paper)', pronunciation: 'han-ji', example: '한지로 만든 공예품이 아름다워요.', exampleTranslation: 'Crafts made from hanji are beautiful.' },
    { korean: '옻칠', english: 'Lacquer', pronunciation: 'ot-chil', example: '옻칠 공예가 유명해요.', exampleTranslation: 'Lacquer crafts are famous.' },
    { korean: '자수', english: 'Embroidery', pronunciation: 'ja-su', example: '전통 자수가 섬세해요.', exampleTranslation: 'Traditional embroidery is delicate.' },
    { korean: '매듭', english: 'Korean knotting (Maedeup)', pronunciation: 'mae-deup', example: '한국 전통 매듭이 아름다워요.', exampleTranslation: 'Korean traditional knotting is beautiful.' },
    { korean: '인삼', english: 'Ginseng', pronunciation: 'in-sam', example: '금산 인삼이 유명해요.', exampleTranslation: 'Geumsan ginseng is famous.' },
    { korean: '차 문화', english: 'Tea culture', pronunciation: 'cha mun-hwa', example: '한국의 차 문화를 체험했어요.', exampleTranslation: 'I experienced Korean tea culture.' },
    { korean: '다도', english: 'Tea ceremony', pronunciation: 'da-do', example: '다도 체험을 할 수 있어요.', exampleTranslation: 'You can experience a tea ceremony.' },
    { korean: '서예', english: 'Calligraphy', pronunciation: 'seo-ye', example: '서예를 배우러 갔어요.', exampleTranslation: 'I went to learn calligraphy.' },
    { korean: '풍수지리', english: 'Feng shui / Geomancy', pronunciation: 'pung-su-ji-ri', example: '한국의 풍수지리 사상이 흥미로워요.', exampleTranslation: 'Korean feng shui philosophy is interesting.' },
    { korean: '지리산', english: 'Jirisan Mountain', pronunciation: 'ji-ri-san', example: '지리산 종주를 했어요.', exampleTranslation: 'I did a complete traverse of Jirisan.' },
    { korean: '백두대간', english: 'Baekdudaegan (mountain range)', pronunciation: 'baek-du-dae-gan', example: '백두대간은 한반도의 등줄기예요.', exampleTranslation: 'Baekdudaegan is the backbone of the Korean Peninsula.' },
    { korean: '갯바위', english: 'Coastal rocks', pronunciation: 'gaet-ba-wi', example: '갯바위에서 낚시를 했어요.', exampleTranslation: 'I fished from the coastal rocks.' },
    { korean: '해식절벽', english: 'Sea cliff', pronunciation: 'hae-sik-jeol-byeok', example: '해식절벽의 경관이 장관이에요.', exampleTranslation: 'The scenery of the sea cliffs is spectacular.' },
    { korean: '다도해', english: 'Many-island sea (archipelago)', pronunciation: 'da-do-hae', example: '다도해 해상 국립공원이 아름다워요.', exampleTranslation: 'The Dadohae Maritime National Park is beautiful.' },
    { korean: '리아스식 해안', english: 'Ria coast', pronunciation: 'ri-a-seu-sik hae-an', example: '서해안은 리아스식 해안이에요.', exampleTranslation: 'The west coast is a ria coast.' },
    { korean: '간척지', english: 'Reclaimed land', pronunciation: 'gan-cheok-ji', example: '새만금은 대규모 간척지예요.', exampleTranslation: 'Saemangeum is a large-scale reclaimed land.' },
    { korean: '관광 산업', english: 'Tourism industry', pronunciation: 'gwan-gwang san-eop', example: '관광 산업이 경제에 중요해요.', exampleTranslation: 'The tourism industry is important to the economy.' },
    { korean: '관광 정책', english: 'Tourism policy', pronunciation: 'gwan-gwang jeong-chaek', example: '정부의 관광 정책이 바뀌었어요.', exampleTranslation: "The government's tourism policy has changed." },
    { korean: '관광 통계', english: 'Tourism statistics', pronunciation: 'gwan-gwang tong-gye', example: '올해 관광 통계가 발표되었어요.', exampleTranslation: "This year's tourism statistics were announced." },
    { korean: '방한', english: 'Visit to Korea', pronunciation: 'bang-han', example: '외국인 방한 관광객이 늘었어요.', exampleTranslation: 'Foreign visitors to Korea have increased.' },
    { korean: '의료 관광', english: 'Medical tourism', pronunciation: 'ui-ryo gwan-gwang', example: '한국 의료 관광이 인기예요.', exampleTranslation: 'Korean medical tourism is popular.' },
    { korean: '뷰티 관광', english: 'Beauty tourism', pronunciation: 'byu-ti gwan-gwang', example: '뷰티 관광으로 한국을 찾는 사람이 많아요.', exampleTranslation: 'Many people visit Korea for beauty tourism.' },
    { korean: '한류 관광', english: 'Hallyu tourism', pronunciation: 'hal-lyu gwan-gwang', example: '한류 관광이 급성장했어요.', exampleTranslation: 'Hallyu tourism has grown rapidly.' },
    { korean: '고궁', english: 'Ancient palace', pronunciation: 'go-gung', example: '서울에 고궁이 다섯 개 있어요.', exampleTranslation: 'There are five ancient palaces in Seoul.' },
    { korean: '종묘', english: 'Jongmyo (royal shrine)', pronunciation: 'jong-myo', example: '종묘는 유네스코 세계유산이에요.', exampleTranslation: 'Jongmyo is a UNESCO World Heritage site.' },
    { korean: '사직단', english: 'Sajikdan (altar)', pronunciation: 'sa-jik-dan', example: '사직단은 국가 제사를 지내던 곳이에요.', exampleTranslation: 'Sajikdan is where national rites were held.' },
    { korean: '성곽', english: 'Fortress wall', pronunciation: 'seong-gwak', example: '서울 성곽을 따라 걸었어요.', exampleTranslation: 'I walked along the Seoul fortress wall.' },
    { korean: '향교', english: 'Hyanggyo (Confucian school)', pronunciation: 'hyang-gyo', example: '향교에서 유교 문화를 배웠어요.', exampleTranslation: 'I learned about Confucian culture at the hyanggyo.' },
    { korean: '서원', english: 'Seowon (Confucian academy)', pronunciation: 'seo-won', example: '한국의 서원이 세계유산에 등재되었어요.', exampleTranslation: 'Korean seowon were listed as World Heritage.' },
    { korean: '석굴암', english: 'Seokguram Grotto', pronunciation: 'seok-gul-am', example: '석굴암의 불상이 인상적이에요.', exampleTranslation: 'The Buddha statue at Seokguram is impressive.' },
    { korean: '불국사', english: 'Bulguksa Temple', pronunciation: 'bul-guk-sa', example: '불국사는 경주의 대표 관광지예요.', exampleTranslation: 'Bulguksa is a representative tourist spot of Gyeongju.' },
    { korean: '수원 화성', english: 'Suwon Hwaseong Fortress', pronunciation: 'su-won hwa-seong', example: '수원 화성은 정조가 건설한 성이에요.', exampleTranslation: 'Suwon Hwaseong is a fortress built by King Jeongjo.' },
    { korean: '비무장지대', english: 'DMZ (Demilitarized Zone)', pronunciation: 'bi-mu-jang-ji-dae', example: '비무장지대 투어에 참가했어요.', exampleTranslation: 'I participated in a DMZ tour.' },
    { korean: '판문점', english: 'Panmunjeom', pronunciation: 'pan-mun-jeom', example: '판문점은 남북 분단의 상징이에요.', exampleTranslation: 'Panmunjeom is a symbol of the North-South division.' },
    { korean: '분단', english: 'Division (of Korea)', pronunciation: 'bun-dan', example: '한반도 분단의 역사를 배웠어요.', exampleTranslation: 'I learned about the history of the Korean Peninsula division.' },
    { korean: '통일', english: 'Unification', pronunciation: 'tong-il', example: '통일 전망대에서 북한을 봤어요.', exampleTranslation: 'I saw North Korea from the unification observatory.' },
    { korean: '억새', english: 'Silver grass', pronunciation: 'eok-sae', example: '가을에 억새밭이 아름다워요.', exampleTranslation: 'Silver grass fields are beautiful in autumn.' },
    { korean: '철새', english: 'Migratory bird', pronunciation: 'cheol-sae', example: '천수만에 철새가 많이 와요.', exampleTranslation: 'Many migratory birds come to Cheonsu Bay.' },
    { korean: '갈대', english: 'Reed', pronunciation: 'gal-dae', example: '순천만 갈대밭이 장관이에요.', exampleTranslation: 'The reed fields of Suncheon Bay are spectacular.' },
    { korean: '동백꽃', english: 'Camellia flower', pronunciation: 'dong-baek-kkot', example: '겨울에 동백꽃이 피어요.', exampleTranslation: 'Camellia flowers bloom in winter.' },
    { korean: '해안 절경', english: 'Coastal scenic beauty', pronunciation: 'hae-an jeol-gyeong', example: '동해안의 해안 절경을 감상했어요.', exampleTranslation: 'I enjoyed the coastal scenic beauty of the east coast.' },
    { korean: '도립공원', english: 'Provincial park', pronunciation: 'do-rip-gong-won', example: '도립공원에서 힐링했어요.', exampleTranslation: 'I relaxed at the provincial park.' },
    { korean: '군립공원', english: 'County park', pronunciation: 'gun-rip-gong-won', example: '군립공원에 등산로가 잘 되어 있어요.', exampleTranslation: 'The county park has well-maintained hiking trails.' },
    { korean: '자연 보호', english: 'Nature conservation', pronunciation: 'ja-yeon bo-ho', example: '자연 보호에 동참합시다.', exampleTranslation: 'Let us participate in nature conservation.' },
    { korean: '오버투어리즘', english: 'Overtourism', pronunciation: 'o-beo-tu-eo-ri-jeum', example: '오버투어리즘이 사회 문제가 되고 있어요.', exampleTranslation: 'Overtourism is becoming a social issue.' },
    { korean: '관광 개발', english: 'Tourism development', pronunciation: 'gwan-gwang gae-bal', example: '관광 개발과 환경 보존의 균형이 중요해요.', exampleTranslation: 'The balance between tourism development and environmental preservation is important.' },
    { korean: '외래 관광객', english: 'Foreign tourist', pronunciation: 'oe-rae gwan-gwang-gaek', example: '외래 관광객 수가 매년 증가해요.', exampleTranslation: 'The number of foreign tourists increases every year.' },
    { korean: '관광 특구', english: 'Special tourist zone', pronunciation: 'gwan-gwang teuk-gu', example: '이태원은 관광 특구예요.', exampleTranslation: 'Itaewon is a special tourist zone.' },
    { korean: '생태 보전', english: 'Ecological conservation', pronunciation: 'saeng-tae bo-jeon', example: '생태 보전과 관광의 조화가 필요해요.', exampleTranslation: 'Harmony between ecological conservation and tourism is needed.' },
    { korean: '관광 수용력', english: 'Tourism carrying capacity', pronunciation: 'gwan-gwang su-yong-nyeok', example: '관광 수용력을 초과하면 안 돼요.', exampleTranslation: 'We must not exceed the tourism carrying capacity.' },
  ],
  6: [
    { korean: '세계문화유산', english: 'World Cultural Heritage', pronunciation: 'se-gye-mun-hwa-yu-san', example: '한국의 세계문화유산을 탐방했어요.', exampleTranslation: 'I explored Korea\'s World Cultural Heritage sites.' },
    { korean: '세계자연유산', english: 'World Natural Heritage', pronunciation: 'se-gye-ja-yeon-yu-san', example: '제주 화산섬은 세계자연유산이에요.', exampleTranslation: 'Jeju volcanic island is a World Natural Heritage site.' },
    { korean: '기록유산', english: 'Documentary heritage', pronunciation: 'gi-rok-yu-san', example: '조선왕조실록은 기록유산이에요.', exampleTranslation: 'The Annals of the Joseon Dynasty is a documentary heritage.' },
    { korean: '인류무형유산', english: 'Intangible Heritage of Humanity', pronunciation: 'in-ryu-mu-hyeong-yu-san', example: '아리랑은 인류무형유산으로 등재되었어요.', exampleTranslation: 'Arirang was inscribed as Intangible Heritage of Humanity.' },
    { korean: '왕릉', english: 'Royal tomb', pronunciation: 'wang-neung', example: '조선 왕릉은 세계유산이에요.', exampleTranslation: 'Joseon Royal Tombs are World Heritage sites.' },
    { korean: '고분', english: 'Ancient tomb / Tumulus', pronunciation: 'go-bun', example: '경주의 고분에서 유물이 발견되었어요.', exampleTranslation: 'Artifacts were discovered in the ancient tombs of Gyeongju.' },
    { korean: '석탑', english: 'Stone pagoda', pronunciation: 'seok-tap', example: '불국사의 석탑은 국보예요.', exampleTranslation: 'The stone pagodas of Bulguksa are national treasures.' },
    { korean: '석등', english: 'Stone lantern', pronunciation: 'seok-deung', example: '절 앞에 석등이 있어요.', exampleTranslation: 'There is a stone lantern in front of the temple.' },
    { korean: '당간지주', english: 'Flagpole support', pronunciation: 'dang-gan-ji-ju', example: '당간지주가 절 입구에 서 있어요.', exampleTranslation: 'The flagpole support stands at the temple entrance.' },
    { korean: '부도', english: 'Stupa (monk\'s memorial)', pronunciation: 'bu-do', example: '부도밭에 고승들의 사리탑이 있어요.', exampleTranslation: 'There are stupas of high monks in the stupa field.' },
    { korean: '처마', english: 'Eaves', pronunciation: 'cheo-ma', example: '전통 건축의 처마 곡선이 아름다워요.', exampleTranslation: 'The eaves curve of traditional architecture is beautiful.' },
    { korean: '기와', english: 'Roof tile', pronunciation: 'gi-wa', example: '기와지붕이 한옥의 특징이에요.', exampleTranslation: 'Tile roofs are a characteristic of hanok.' },
    { korean: '기둥', english: 'Pillar / Column', pronunciation: 'gi-dung', example: '나무 기둥이 건물을 지탱해요.', exampleTranslation: 'Wooden pillars support the building.' },
    { korean: '대들보', english: 'Main beam', pronunciation: 'dae-deul-bo', example: '대들보에 단청이 그려져 있어요.', exampleTranslation: 'Dancheong (decorative painting) is drawn on the main beam.' },
    { korean: '단청', english: 'Dancheong (decorative painting)', pronunciation: 'dan-cheong', example: '단청의 색감이 화려해요.', exampleTranslation: 'The colors of dancheong are splendid.' },
    { korean: '공포', english: 'Bracket set (architecture)', pronunciation: 'gong-po', example: '공포 양식으로 건축 시대를 알 수 있어요.', exampleTranslation: 'You can tell the architectural era from the bracket set style.' },
    { korean: '배흘림기둥', english: 'Entasis column', pronunciation: 'bae-heul-lim-gi-dung', example: '부석사의 배흘림기둥이 유명해요.', exampleTranslation: 'The entasis columns of Buseoksa are famous.' },
    { korean: '익공', english: 'Wing bracket', pronunciation: 'ik-gong', example: '익공 양식은 조선 시대에 많이 사용되었어요.', exampleTranslation: 'Wing bracket style was widely used in the Joseon era.' },
    { korean: '주심포', english: 'Jusimpo (column-top bracket)', pronunciation: 'ju-sim-po', example: '주심포 양식은 고려 시대의 특징이에요.', exampleTranslation: 'Jusimpo style is a characteristic of the Goryeo era.' },
    { korean: '다포', english: 'Dapo (multi-bracket)', pronunciation: 'da-po', example: '다포 양식의 건물은 규모가 커요.', exampleTranslation: 'Multi-bracket style buildings are large in scale.' },
    { korean: '풍수', english: 'Geomancy / Feng shui', pronunciation: 'pung-su', example: '풍수에 따라 궁궐의 위치를 정했어요.', exampleTranslation: 'The location of the palace was determined by geomancy.' },
    { korean: '명당', english: 'Auspicious site', pronunciation: 'myeong-dang', example: '이곳은 풍수적으로 명당이에요.', exampleTranslation: 'This place is an auspicious site in geomancy.' },
    { korean: '좌청룡 우백호', english: 'Blue Dragon left, White Tiger right (geomancy)', pronunciation: 'jwa-cheong-nyong u-baek-ho', example: '좌청룡 우백호의 지형이 명당의 조건이에요.', exampleTranslation: 'The Blue Dragon left, White Tiger right terrain is a condition for an auspicious site.' },
    { korean: '배산임수', english: 'Mountain behind, water in front', pronunciation: 'bae-san-im-su', example: '배산임수 지형에 마을이 형성되었어요.', exampleTranslation: 'A village was formed on mountain-behind, water-in-front terrain.' },
    { korean: '정원', english: 'Garden (traditional)', pronunciation: 'jeong-won', example: '한국 전통 정원은 자연과 조화를 이뤄요.', exampleTranslation: 'Korean traditional gardens harmonize with nature.' },
    { korean: '소쇄원', english: 'Soswaewon Garden', pronunciation: 'so-swae-won', example: '소쇄원은 조선 시대 대표 정원이에요.', exampleTranslation: 'Soswaewon is a representative garden of the Joseon era.' },
    { korean: '정자', english: 'Pavilion', pronunciation: 'jeong-ja', example: '정자에 앉아 경치를 감상했어요.', exampleTranslation: 'I sat in the pavilion and enjoyed the scenery.' },
    { korean: '누각', english: 'Raised pavilion', pronunciation: 'nu-gak', example: '누각에서 내려다보는 경치가 좋아요.', exampleTranslation: 'The view looking down from the raised pavilion is nice.' },
    { korean: '석조', english: 'Stone structure', pronunciation: 'seok-jo', example: '석조 유물의 보존 상태가 좋아요.', exampleTranslation: 'The stone structure artifacts are in good condition.' },
    { korean: '마애불', english: 'Rock-carved Buddha', pronunciation: 'ma-ae-bul', example: '마애불이 바위에 새겨져 있어요.', exampleTranslation: 'A rock-carved Buddha is engraved on the rock.' },
    { korean: '범종', english: 'Buddhist bell', pronunciation: 'beom-jong', example: '에밀레종은 유명한 범종이에요.', exampleTranslation: 'The Emille Bell is a famous Buddhist bell.' },
    { korean: '첨성대', english: 'Cheomseongdae (observatory)', pronunciation: 'cheom-seong-dae', example: '첨성대는 동양에서 가장 오래된 천문대예요.', exampleTranslation: 'Cheomseongdae is the oldest astronomical observatory in the East.' },
    { korean: '삼층석탑', english: 'Three-story stone pagoda', pronunciation: 'sam-cheung-seok-tap', example: '감은사지 삼층석탑이 유명해요.', exampleTranslation: 'The three-story stone pagoda of Gameunsa is famous.' },
    { korean: '다보탑', english: 'Dabotap Pagoda', pronunciation: 'da-bo-tap', example: '다보탑의 정교한 조각이 뛰어나요.', exampleTranslation: 'The elaborate carvings of Dabotap are outstanding.' },
    { korean: '석가탑', english: 'Seokgatap Pagoda', pronunciation: 'seok-ga-tap', example: '석가탑은 단순미의 극치예요.', exampleTranslation: 'Seokgatap is the epitome of simple beauty.' },
    { korean: '천마총', english: 'Cheonmachong (Heavenly Horse Tomb)', pronunciation: 'cheon-ma-chong', example: '천마총에서 천마도가 발견되었어요.', exampleTranslation: 'The painting of the Heavenly Horse was discovered in Cheonmachong.' },
    { korean: '고인돌', english: 'Dolmen', pronunciation: 'go-in-dol', example: '강화도 고인돌은 세계유산이에요.', exampleTranslation: 'The Ganghwa dolmen is a World Heritage site.' },
    { korean: '선사시대', english: 'Prehistoric era', pronunciation: 'seon-sa-si-dae', example: '선사시대 유적이 발견되었어요.', exampleTranslation: 'Prehistoric era ruins were discovered.' },
    { korean: '청동기시대', english: 'Bronze Age', pronunciation: 'cheong-dong-gi-si-dae', example: '고인돌은 청동기시대의 유적이에요.', exampleTranslation: 'Dolmens are relics of the Bronze Age.' },
    { korean: '철기시대', english: 'Iron Age', pronunciation: 'cheol-gi-si-dae', example: '철기시대에 농업이 발전했어요.', exampleTranslation: 'Agriculture developed during the Iron Age.' },
    { korean: '가야', english: 'Gaya (ancient kingdom)', pronunciation: 'ga-ya', example: '가야 고분군이 세계유산에 등재되었어요.', exampleTranslation: 'The Gaya tumuli were inscribed as World Heritage.' },
    { korean: '백제', english: 'Baekje (ancient kingdom)', pronunciation: 'baek-je', example: '백제 역사 유적 지구를 탐방했어요.', exampleTranslation: 'I explored the Baekje Historic Areas.' },
    { korean: '신라', english: 'Silla (ancient kingdom)', pronunciation: 'sil-la', example: '경주는 신라의 수도였어요.', exampleTranslation: 'Gyeongju was the capital of Silla.' },
    { korean: '고구려', english: 'Goguryeo (ancient kingdom)', pronunciation: 'go-gu-ryeo', example: '고구려 벽화가 인상적이에요.', exampleTranslation: 'Goguryeo murals are impressive.' },
    { korean: '발해', english: 'Balhae (historical kingdom)', pronunciation: 'bal-hae', example: '발해는 고구려의 후예가 세운 나라예요.', exampleTranslation: 'Balhae was a state founded by descendants of Goguryeo.' },
    { korean: '유교', english: 'Confucianism', pronunciation: 'yu-gyo', example: '조선은 유교 국가였어요.', exampleTranslation: 'Joseon was a Confucian state.' },
    { korean: '불교', english: 'Buddhism', pronunciation: 'bul-gyo', example: '고려 시대에 불교가 융성했어요.', exampleTranslation: 'Buddhism flourished during the Goryeo era.' },
    { korean: '무속 신앙', english: 'Shamanism', pronunciation: 'mu-sok sin-ang', example: '무속 신앙은 한국 문화의 기층이에요.', exampleTranslation: 'Shamanism is the foundation of Korean culture.' },
    { korean: '굿', english: 'Gut (shamanistic ritual)', pronunciation: 'gut', example: '굿은 전통적인 의례예요.', exampleTranslation: 'Gut is a traditional ritual.' },
    { korean: '문화 경관', english: 'Cultural landscape', pronunciation: 'mun-hwa gyeong-gwan', example: '이 지역의 문화 경관이 보전되어 있어요.', exampleTranslation: 'The cultural landscape of this area is preserved.' },
    { korean: '역사 도시', english: 'Historic city', pronunciation: 'yeok-sa do-si', example: '경주는 대표적인 역사 도시예요.', exampleTranslation: 'Gyeongju is a representative historic city.' },
    { korean: '도시 재생', english: 'Urban regeneration', pronunciation: 'do-si jae-saeng', example: '도시 재생으로 오래된 마을이 관광지가 되었어요.', exampleTranslation: 'Old villages became tourist attractions through urban regeneration.' },
    { korean: '근대 건축', english: 'Modern architecture', pronunciation: 'geun-dae geon-chuk', example: '군산에 근대 건축물이 많이 남아 있어요.', exampleTranslation: 'Many modern architecture buildings remain in Gunsan.' },
    { korean: '일제강점기', english: 'Japanese colonial period', pronunciation: 'il-je-gang-jeom-gi', example: '일제강점기의 역사를 배웠어요.', exampleTranslation: 'I learned about the history of the Japanese colonial period.' },
    { korean: '독립운동', english: 'Independence movement', pronunciation: 'dong-nip-un-dong', example: '독립운동의 현장을 방문했어요.', exampleTranslation: 'I visited the site of the independence movement.' },
    { korean: '위안부', english: 'Comfort women', pronunciation: 'wi-an-bu', example: '위안부 역사관을 방문했어요.', exampleTranslation: 'I visited the comfort women history museum.' },
    { korean: '광복절', english: 'Liberation Day', pronunciation: 'gwang-bok-jeol', example: '광복절은 한국의 독립기념일이에요.', exampleTranslation: 'Liberation Day is Korea\'s independence day.' },
    { korean: '6.25 전쟁', english: 'Korean War', pronunciation: 'yu-gi-o jeon-jaeng', example: '6.25 전쟁의 역사를 이해하게 되었어요.', exampleTranslation: 'I came to understand the history of the Korean War.' },
    { korean: '전쟁 기념관', english: 'War Memorial', pronunciation: 'jeon-jaeng gi-nyeom-gwan', example: '서울 전쟁 기념관을 방문했어요.', exampleTranslation: 'I visited the Seoul War Memorial.' },
    { korean: '산성', english: 'Mountain fortress', pronunciation: 'san-seong', example: '남한산성은 조선 시대의 산성이에요.', exampleTranslation: 'Namhansanseong is a Joseon-era mountain fortress.' },
    { korean: '읍성', english: 'Town fortress', pronunciation: 'eup-seong', example: '해미읍성은 잘 보존되어 있어요.', exampleTranslation: 'Haemi Eupseong is well preserved.' },
    { korean: '향토사', english: 'Local history', pronunciation: 'hyang-to-sa', example: '향토사 박물관에서 지역 역사를 배웠어요.', exampleTranslation: 'I learned regional history at the local history museum.' },
    { korean: '구비문학', english: 'Oral literature', pronunciation: 'gu-bi-mun-hak', example: '구비문학 속에 지역 문화가 담겨 있어요.', exampleTranslation: 'Regional culture is embedded in oral literature.' },
    { korean: '설화', english: 'Legend / Myth', pronunciation: 'seol-hwa', example: '이 장소에 관한 설화가 있어요.', exampleTranslation: 'There is a legend about this place.' },
    { korean: '전설', english: 'Legend', pronunciation: 'jeon-seol', example: '아기장수 전설을 알고 있어요?', exampleTranslation: 'Do you know the legend of the baby general?' },
    { korean: '신화', english: 'Myth', pronunciation: 'sin-hwa', example: '제주도의 창세 신화가 흥미로워요.', exampleTranslation: 'The creation myth of Jeju Island is interesting.' },
    { korean: '탐라', english: 'Tamna (ancient Jeju kingdom)', pronunciation: 'tam-ra', example: '탐라는 제주도의 옛 이름이에요.', exampleTranslation: 'Tamna is the old name of Jeju Island.' },
    { korean: '문화 다양성', english: 'Cultural diversity', pronunciation: 'mun-hwa da-yang-seong', example: '관광을 통해 문화 다양성을 경험해요.', exampleTranslation: 'We experience cultural diversity through tourism.' },
    { korean: '문화 교류', english: 'Cultural exchange', pronunciation: 'mun-hwa gyo-ryu', example: '관광은 문화 교류의 수단이에요.', exampleTranslation: 'Tourism is a means of cultural exchange.' },
    { korean: '문화 정체성', english: 'Cultural identity', pronunciation: 'mun-hwa jeong-che-seong', example: '관광을 통해 문화 정체성을 재발견해요.', exampleTranslation: 'We rediscover cultural identity through tourism.' },
    { korean: '지역 활성화', english: 'Regional revitalization', pronunciation: 'ji-yeok hwal-seong-hwa', example: '관광이 지역 활성화에 기여해요.', exampleTranslation: 'Tourism contributes to regional revitalization.' },
    { korean: '관광 마케팅', english: 'Tourism marketing', pronunciation: 'gwan-gwang ma-ke-ting', example: '효과적인 관광 마케팅이 필요해요.', exampleTranslation: 'Effective tourism marketing is needed.' },
    { korean: '관광 인프라', english: 'Tourism infrastructure', pronunciation: 'gwan-gwang in-peu-ra', example: '관광 인프라가 잘 갖춰져 있어요.', exampleTranslation: 'Tourism infrastructure is well equipped.' },
    { korean: '관광 자원', english: 'Tourism resources', pronunciation: 'gwan-gwang ja-won', example: '이 지역의 관광 자원을 활용해야 해요.', exampleTranslation: 'We must utilize the tourism resources of this area.' },
    { korean: '역사 해석', english: 'Historical interpretation', pronunciation: 'yeok-sa hae-seok', example: '다양한 역사 해석이 존재해요.', exampleTranslation: 'Various historical interpretations exist.' },
    { korean: '유산 관리', english: 'Heritage management', pronunciation: 'yu-san gwal-li', example: '체계적인 유산 관리가 필요해요.', exampleTranslation: 'Systematic heritage management is needed.' },
    { korean: '문화재 복원', english: 'Cultural property restoration', pronunciation: 'mun-hwa-jae bok-won', example: '문화재 복원 사업이 진행되고 있어요.', exampleTranslation: 'A cultural property restoration project is underway.' },
    { korean: '전통 마을', english: 'Traditional village', pronunciation: 'jeon-tong ma-eul', example: '전통 마을의 생활 양식을 체험했어요.', exampleTranslation: 'I experienced the lifestyle of a traditional village.' },
    { korean: '유네스코', english: 'UNESCO', pronunciation: 'yu-ne-seu-ko', example: '한국에 유네스코 등재 유산이 많아요.', exampleTranslation: 'Korea has many UNESCO-listed heritage sites.' },
    { korean: '등재', english: 'Inscription / Registration', pronunciation: 'deung-jae', example: '세계유산 등재가 확정되었어요.', exampleTranslation: 'World Heritage inscription was confirmed.' },
    { korean: '보존', english: 'Preservation', pronunciation: 'bo-jon', example: '원형 보존이 잘 되어 있어요.', exampleTranslation: 'The original form is well preserved.' },
    { korean: '전승', english: 'Transmission / Passing down', pronunciation: 'jeon-seung', example: '전통 기술의 전승이 중요해요.', exampleTranslation: 'Transmitting traditional skills is important.' },
    { korean: '장인', english: 'Master craftsman', pronunciation: 'jang-in', example: '장인의 손길이 느껴져요.', exampleTranslation: "You can feel the master craftsman's touch." },
    { korean: '인간문화재', english: 'Living National Treasure', pronunciation: 'in-gan-mun-hwa-jae', example: '인간문화재가 전통 기술을 전수해요.', exampleTranslation: 'Living National Treasures pass on traditional skills.' },
    { korean: '관광학', english: 'Tourism studies', pronunciation: 'gwan-gwang-hak', example: '관광학을 전공하고 있어요.', exampleTranslation: 'I am majoring in tourism studies.' },
    { korean: '문화 관광론', english: 'Cultural tourism theory', pronunciation: 'mun-hwa gwan-gwang-non', example: '문화 관광론의 관점에서 분석했어요.', exampleTranslation: 'I analyzed it from the perspective of cultural tourism theory.' },
    { korean: '관광 사회학', english: 'Tourism sociology', pronunciation: 'gwan-gwang sa-hoe-hak', example: '관광 사회학적 연구가 활발해요.', exampleTranslation: 'Tourism sociology research is active.' },
    { korean: '관광 심리학', english: 'Tourism psychology', pronunciation: 'gwan-gwang sim-ri-hak', example: '관광객의 행동을 관광 심리학으로 분석해요.', exampleTranslation: 'Tourist behavior is analyzed through tourism psychology.' },
    { korean: '관광 경제학', english: 'Tourism economics', pronunciation: 'gwan-gwang gyeong-je-hak', example: '관광 경제학적 효과를 측정했어요.', exampleTranslation: 'Tourism economic effects were measured.' },
    { korean: '문화재청', english: 'Cultural Heritage Administration', pronunciation: 'mun-hwa-jae-cheong', example: '문화재청에서 관리하고 있어요.', exampleTranslation: 'It is managed by the Cultural Heritage Administration.' },
    { korean: '관광공사', english: 'Korea Tourism Organization', pronunciation: 'gwan-gwang-gong-sa', example: '한국관광공사에서 정보를 얻었어요.', exampleTranslation: 'I got information from the Korea Tourism Organization.' },
    { korean: '향토 축제', english: 'Local festival', pronunciation: 'hyang-to chuk-je', example: '향토 축제가 지역 경제에 도움이 돼요.', exampleTranslation: 'Local festivals help the regional economy.' },
    { korean: '무형유산 전승자', english: 'Intangible heritage bearer', pronunciation: 'mu-hyeong-yu-san jeon-seung-ja', example: '무형유산 전승자의 기술을 배웠어요.', exampleTranslation: "I learned the skills of an intangible heritage bearer." },
    { korean: '고택', english: 'Historic house', pronunciation: 'go-taek', example: '양동마을의 고택을 방문했어요.', exampleTranslation: 'I visited the historic houses of Yangdong Village.' },
    { korean: '종가', english: 'Head family house', pronunciation: 'jong-ga', example: '종가에서 전통 음식을 맛봤어요.', exampleTranslation: 'I tasted traditional food at the head family house.' },
    { korean: '양동마을', english: 'Yangdong Village', pronunciation: 'yang-dong-ma-eul', example: '양동마을은 조선 시대 양반 마을이에요.', exampleTranslation: 'Yangdong Village is a Joseon-era noble village.' },
    { korean: '해인사', english: 'Haeinsa Temple', pronunciation: 'hae-in-sa', example: '해인사에 팔만대장경이 보관되어 있어요.', exampleTranslation: 'The Tripitaka Koreana is stored at Haeinsa Temple.' },
    { korean: '팔만대장경', english: 'Tripitaka Koreana', pronunciation: 'pal-man-dae-jang-gyeong', example: '팔만대장경은 세계기록유산이에요.', exampleTranslation: 'The Tripitaka Koreana is a Memory of the World.' },
    { korean: '훈민정음', english: 'Hunminjeongeum', pronunciation: 'hun-min-jeong-eum', example: '훈민정음은 한글 창제의 원본이에요.', exampleTranslation: 'Hunminjeongeum is the original document of Hangul creation.' },
    { korean: '문화 해설사', english: 'Cultural heritage interpreter', pronunciation: 'mun-hwa hae-seol-sa', example: '문화 해설사의 설명을 들었어요.', exampleTranslation: 'I listened to the cultural heritage interpreter\'s explanation.' },
  ],
};
